import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {PulseSummary,PulseTrend} from '../../components/dashboard/AttendancePulse';
import {impactedSchedule,pulseLevel,pulseTone,useAttendancePulse} from '../../services/attendancePulse';
import {attendanceChanged,issueLabels,issueRpc,issueStatuses,manila,shiftText,todayManila} from '../../services/attendanceIssues';
const button='inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-300 px-4 py-2 font-semibold dark:border-slate-600 disabled:opacity-50';
const field='mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white p-2 text-slate-900 dark:border-slate-600 dark:bg-slate-900 dark:text-white';
export default function AttendancePulsePage(){
 const [params,setParams]=useSearchParams();const date=params.get('date')||todayManila();const {data,error,load}=useAttendancePulse(date);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const guard=useRef(false);
 const set=(key:string,value:string)=>{const n=new URLSearchParams(params);if(value)n.set(key,value);else n.delete(key);setParams(n);};
 const [kind,setKind]=useState('absence');const [shift,setShift]=useState('');const [status,setStatus]=useState('');
 const units=useMemo(()=>[...new Map((data?.rows||[]).map(r=>[r.businessUnitId,r.businessUnit])).entries()],[data]);
 const affected=new Set(data?.concerns.map(c=>c.businessUnitId).filter(Boolean));
 const rows=(data?.rows||[]).filter(r=>(!params.get('bu')||r.businessUnitId===params.get('bu'))&&(!kind||r.kind===kind)&&(!status||r.status===status)&&(!shift||shiftText(r.schedule)===shift)&&(!params.has('attention')||r.needsAttention||affected.has(r.businessUnitId)));
 const follow=async(id:string,action:string)=>{if(guard.current)return;guard.current=true;setBusy(true);try{await issueRpc('attendance_pulse_followup',{p_id:id,p_action:action});setMessage('Follow-up queued. Duplicate reminders for this request and day are suppressed.');}catch(e){setMessage((e as Error).message);}finally{guard.current=false;setBusy(false);}};
 if(error)return <div role="alert">{error} <button className={button} onClick={()=>void load()}>Retry</button></div>;
 if(!data)return <p role="status">Loading attendance pulse…</p>;
 if(!data.allowed)return <div><h1 className="text-2xl font-bold">Attendance pulse</h1><p>Your account does not have team attendance visibility.</p><Link to="/dashboard">Return to Dashboard</Link></div>;
 const trend=params.get('view')==='trend';
 const highest=[...data.units].filter(b=>b.usual!==null).sort((a,b)=>(b.count-b.usual!)-(a.count-a.usual!))[0];
 return <div className="space-y-5 text-slate-900 dark:text-white"><header className="flex flex-wrap justify-between gap-3"><div><Link className="text-sm underline" to="/dashboard">← Dashboard</Link><h1 className="mt-2 text-3xl font-bold">{trend?'Attendance trend':'Today’s attendance exceptions'}</h1><p className="mt-2 text-slate-500 dark:text-slate-400">{data.scope} · Philippine time</p></div><label>Date<input className={field} type="date" value={date} onChange={e=>set('date',e.target.value)}/></label></header>
 <SuspensionStatusReport /><nav className="flex flex-wrap gap-2"><button className={button+(!trend?' bg-violet-600 text-white':'')} onClick={()=>set('view','')}>Today’s reports</button><button className={button+(trend?' bg-violet-600 text-white':'')} onClick={()=>set('view','trend')}>View attendance trend</button><Link className={button} to={impactedSchedule(date)}>Open impacted schedule</Link></nav>
 {message&&<p role="status" className="rounded-xl border p-3">{message}</p>}
 {trend?<><PulseSummary data={data}/><section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h2 className="text-xl font-bold">Four-week trend</h2><p className="mt-2">{data.reported} reports · {data.usual===null?'Comparable baseline is still building':`${data.usual} usual on this weekday`}</p><PulseTrend data={data} full/>{highest&&<p className="mt-4">Largest increase: {highest.name} · {highest.count} reports, usually {highest.usual}</p>}<RepeatedPatterns date={date}/><p className="mt-3 text-sm text-slate-500 dark:text-slate-400">The baseline uses up to four previous matching weekdays, with at least two tracked dates. Grey bars precede baseline tracking. This reflects structured reports, including HR-logged GC reports.</p><details className="mt-3"><summary>Daily counts</summary><table className="mt-2 w-full text-left"><thead><tr><th>Date</th><th>Reports</th><th>Baseline tracking</th></tr></thead><tbody>{data.trend.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.count}</td><td>{d.tracked?'Tracked':'Not yet tracked'}</td></tr>)}</tbody></table></details></section></>:<>
 <div className="flex flex-wrap gap-4 rounded-xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><strong>{data.reported} reported unable to work</strong><span>{data.approved} approved</span><span>{data.pending} pending</span><span>{data.attention} need attention</span><span className={'rounded-full border px-3 '+pulseTone[data.severity]}>{pulseLevel[data.severity]}</span></div>
 {data.concerns.length>0&&<section className={'rounded-xl border p-4 '+pulseTone[data.severity]}><h2 className="font-bold">What needs attention</h2><ul className="mt-2 space-y-2">{data.concerns.map((c,i)=><li key={i} className="flex flex-wrap justify-between gap-2"><span>{c.text}</span><button className="underline" onClick={()=>{const n=new URLSearchParams(params);n.set('attention','1');if(c.businessUnitId)n.set('bu',c.businessUnitId);setParams(n);}}>Review reports →</button></li>)}</ul></section>}
 <div className="grid gap-3 rounded-xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-800 sm:grid-cols-2 lg:grid-cols-5"><label>Business unit<select className={field} value={params.get('bu')||''} onChange={e=>set('bu',e.target.value)}><option value="">All in your scope</option>{units.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Status<select className={field} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{Object.entries(issueStatuses).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Report type<select className={field} value={kind} onChange={e=>setKind(e.target.value)}><option value="">All report types</option>{Object.entries(issueLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Shift<select className={field} value={shift} onChange={e=>setShift(e.target.value)}><option value="">All shifts</option>{[...new Set(data.rows.map(r=>shiftText(r.schedule)))].map(s=><option key={s}>{s}</option>)}</select></label><label className="flex items-center gap-2"><input type="checkbox" checked={params.has('attention')} onChange={e=>set('attention',e.target.checked?'1':'')}/>Needs attention only</label></div>
 <section className="overflow-hidden rounded-xl border bg-white dark:border-slate-700 dark:bg-slate-800"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600 dark:bg-slate-900 dark:text-slate-300"><tr>{['Employee','Business unit','Scheduled shift','Report / Source','Approval status','Submitted','Action'].map(h=><th className="p-4" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-200 align-top dark:border-slate-700"><td className="p-4 font-semibold">{r.employeeName}<small className="block font-normal text-slate-500 dark:text-slate-400">{r.employeeCode}</small></td><td className="p-4">{r.businessUnit}</td><td className="p-4">{shiftText(r.schedule)}<Link className="mt-2 block underline" to={impactedSchedule(date,r.managerId)}>Open schedule</Link></td><td className="p-4">{issueLabels[r.kind as keyof typeof issueLabels]}<span className="mt-2 block text-xs">{r.source}</span></td><td className="p-4">{r.hrState==='closed'?'HR review completed':issueStatuses[r.status]}{r.needsAttention&&<span className="mt-2 block text-amber-700 dark:text-amber-300">Needs attention</span>}</td><td className="p-4 whitespace-nowrap">{manila(r.submittedAt)}</td><td className="p-4"><div className="flex flex-col items-start gap-2">{r.canReadDetails?<Link className={button} to={'/payroll/attendance-requests?review='+r.id}>{r.canReview?'Review':'View'}</Link>:<span className="text-xs">Staffing summary only</span>}{['pending','details','hr_review'].includes(r.status)&&<><button disabled={busy} className="min-h-11 text-left underline" onClick={()=>void follow(r.id,'manager')}>Remind manager</button><button disabled={busy} className="min-h-11 text-left underline" onClick={()=>void follow(r.id,'hr')}>Notify HR</button></>}</div></td></tr>)}</tbody></table>{rows.length===0&&<p className="p-8 text-center">No reports match these filters.</p>}</div></section><p className="text-sm text-slate-500 dark:text-slate-400">Private reasons and attachments are available only through an authorized request review. Published schedules are preserved.</p></>}
 {data.canManage&&<HRPulseTools onChanged={()=>{attendanceChanged();void load();}}/>}</div>;
}
function HRPulseTools({onChanged}:{onChanged:()=>void}){
 const [open,setOpen]=useState(false);const [data,setData]=useState<any>();const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const guard=useRef(false);const key=useRef(crypto.randomUUID());const [employee,setEmployee]=useState('');const [date,setDate]=useState(todayManila());const [note,setNote]=useState('');const [reason,setReason]=useState('');const [config,setConfig]=useState<any>();const [windows,setWindows]=useState<any[]>([]);const [reference,setReference]=useState('');
 const load=async()=>{try{const d=await issueRpc('get_attendance_pulse_settings');setData(d);setConfig(d.settings);setWindows(d.windows);}catch(e){setMessage((e as Error).message);}};
 useEffect(()=>{if(open&&!data)void load();},[open]);
 const run=async(fn:()=>Promise<void>)=>{if(guard.current)return;guard.current=true;setBusy(true);setMessage('');try{await fn();onChanged();}catch(e){setMessage((e as Error).message);}finally{guard.current=false;setBusy(false);}};
 const fields:[string,string,number,number][]=[['attention_ratio','Comparable weekday multiplier',1.1,20],['attention_count','BU report attention count',2,1000],['overlap_count','Overlapping shift threshold',2,100],['attention_percent','Scheduled workforce attention %',1,100],['critical_percent','Scheduled workforce critical %',1,100],['critical_minimum','Minimum reports for critical percentage',2,100],['urgent_minutes','Urgent review window before shift (minutes)',0,1440],['company_count','Company-wide concern count for BOD',2,10000],['summary_hour','Daily summary hour (0–23, Philippine time)',0,23]];
 return <section className="rounded-xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><button className={button} onClick={()=>setOpen(!open)}>HR: Log GC Report & pulse settings</button>{open&&<>{message&&<p className="mt-3" role="status">{message}</p>}{!data?<p>Loading HR controls…</p>:<div className="mt-5 space-y-6"><form onSubmit={e=>{e.preventDefault();void run(async()=>{const id=await issueRpc<string>('log_gc_attendance_report',{p_employee:employee,p_date:date,p_explanation:note,p_key:key.current});setReference(id);key.current=crypto.randomUUID();setNote('');setMessage('GC report logged. It is awaiting approval.');});}}><h2 className="text-xl font-bold">Log GC Report</h2><p className="mt-2 text-sm">Record an employee’s unable-to-work report from the designated GC. Your HR account is recorded as the logger; the direct manager still decides.</p><fieldset disabled={busy} className="mt-3 grid gap-3 sm:grid-cols-2"><label>Employee<select required className={field} value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">Select employee</option>{data.employees.map((e:any)=><option key={e.id} value={e.id}>{e.name} · {e.code} · {e.businessUnit}</option>)}</select></label><label>Report date<input required type="date" max={todayManila()} value={date} onChange={e=>setDate(e.target.value)} className={field}/></label><label className="sm:col-span-2">Factual GC report note<textarea required minLength={3} maxLength={1000} className={field} rows={2} value={note} onChange={e=>setNote(e.target.value)}/></label><button className={button+' bg-violet-600 text-white'} type="submit">{busy?'Saving…':'Log and Route for Approval'}</button></fieldset>{reference&&<Link className="mt-3 inline-block underline" to={'/payroll/attendance-requests?review='+reference}>Open logged request →</Link>}</form>
 <details><summary className="font-semibold">Staffing thresholds and critical coverage windows</summary><form className="mt-4 space-y-4" onSubmit={e=>{e.preventDefault();void run(async()=>{await issueRpc('save_attendance_pulse_settings',{p_data:config,p_windows:windows,p_reason:reason});setMessage('Pulse settings saved.');await load();});}}><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([k,l,min,max])=><label key={k}>{l}<input required type="number" step={k==='attention_ratio'?0.1:1} min={min} max={max} className={field} value={config[k]} onChange={e=>setConfig({...config,[k]:Number(e.target.value)})}/></label>)}</fieldset><p className="text-sm">Critical windows identify opening, operating, or guest-facing coverage. A critical workforce percentage also requires the minimum report count. Same-team overlapping shifts and overdue urgent reviews can trigger critical alerts.</p>{windows.map((w,i)=><fieldset disabled={busy} key={i} className="grid gap-3 rounded-xl border p-3 sm:grid-cols-3">{[['business_unit_id','Business unit'],['label','Coverage label'],['department','Department (optional)'],['start_time','Starts'],['end_time','Ends'],['minimum_reports','Minimum reports']].map(([k,l])=><label key={k}>{l}{k==='business_unit_id'?<select required className={field} value={w[k]} onChange={e=>setWindows(windows.map((x,j)=>i===j?{...x,[k]:e.target.value}:x))}><option value="">Select BU</option>{data.businessUnits.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select>:<input required={k!=='department'} className={field} type={k.includes('time')?'time':k==='minimum_reports'?'number':'text'} min={k==='minimum_reports'?2:undefined} value={w[k]||''} onChange={e=>setWindows(windows.map((x,j)=>i===j?{...x,[k]:e.target.value}:x))}/>}</label>)}<button type="button" className={button} onClick={()=>setWindows(windows.filter((_,j)=>j!==i))}>Remove window</button></fieldset>)}<button type="button" className={button} disabled={busy} onClick={()=>setWindows([...windows,{business_unit_id:'',department:'',label:'Opening shift',start_time:'09:00',end_time:'11:00',minimum_reports:2}])}>Add critical coverage window</button><label className="block">Change reason<input required minLength={3} className={field} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy} className={button+' bg-violet-600 text-white'}>Save pulse settings</button><p className="text-sm">Last changed: {manila(config.changed_at)} · {data.changedBy||'Default settings'}</p><p className="text-sm">One daily summary. Condition-change alerts are capped at three per recipient per day; identical concerns are suppressed. Individual approval notifications retain their existing routing.</p></form></details></div>}</>}</section>;
}

function RepeatedPatterns({date}:{date:string}){const [rows,setRows]=useState<any[]>([]);const [error,setError]=useState('');useEffect(()=>{let live=true;setRows([]);issueRpc<any[]>('get_attendance_pulse_patterns',{p_date:date}).then(d=>{if(live){setRows(d);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[date]);return <section className="mt-5"><h3 className="font-semibold">Repeated shift or team patterns</h3>{error?<p role="alert">{error}</p>:rows.length?rows.map((r,i)=><p className="mt-2 text-sm" key={i}>{r.businessUnit} · {r.department} · {r.shiftStart}–{r.shiftEnd}: {r.reports} employee-day reports across {r.days} dates</p>):<p className="mt-2 text-sm text-slate-500 dark:text-slate-400">No repeated pattern identified in the available four-week records.</p>}</section>;}
import SuspensionStatusReport from '../../components/payroll/SuspensionStatusReport';
