import React,{useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import AttendanceIssueForm from '../../components/attendance/AttendanceIssueForm';
import AttendanceCasePanel from '../../components/attendance/AttendanceCasePanel';
import {supabase} from '../../services/supabaseClient';
import {AttendanceIssue,attendanceChanged,approvedLabels,caseStates,issueLabels,issueRpc,issueStatuses,requestStatus,manila,shiftText,useAttendanceIssues} from '../../services/attendanceIssues';
const button='min-h-11 rounded-xl border border-slate-300 px-4 py-2 font-semibold dark:border-slate-600 disabled:opacity-50';
function PunchEvidence({id}:{id:string}){const [data,setData]=useState<any>();const [error,setError]=useState('');return <details onToggle={e=>{if(e.currentTarget.open&&!data)issueRpc('get_attendance_issue_punches',{p_id:id}).then(setData).catch(e=>setError(e.message));}} className="mt-3"><summary>Original and corrected punches</summary>{error&&<p role="alert">{error}</p>}{data&&['original','effective'].map(key=><div key={key} className="mt-3"><h4 className="font-semibold">{key==='original'?'Original punches':'Current corrected evidence'}</h4>{data[key].length?data[key].map((p:any,i:number)=><p key={i}>{p.type.replaceAll('_',' ')} · {manila(p.timestamp)}</p>):<p>No original punches recorded.</p>}</div>)}</details>;}
export default function AttendanceRequests(){const data=useAttendanceIssues();const [params,setParams]=useSearchParams();const [form,setForm]=useState(params.has('new'));const [edit,setEdit]=useState<AttendanceIssue>();const [tab,setTab]=useState(params.get('queue')||(params.has('review')?'all':'own'));const [status,setStatus]=useState(params.get('status')||'');const [notes,setNotes]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const guard=useRef(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
 const saved=(id:string)=>{setForm(false);setEdit(undefined);setParams({review:id});setTab('all');setSuccess('Request submitted for approval');void data.load();};
 const run=async(r:AttendanceIssue,action:string)=>{if(guard.current)return;guard.current=true;setBusy(true);setError('');try{await issueRpc('review_attendance_issue',{p_id:r.id,p_revision:r.revision,p_action:action,p_reason:notes[r.id]||''});setSuccess(action==='approve'?approvedLabels[r.kind]:'Request updated successfully');attendanceChanged();await data.load();}catch(e){setError((e as Error).message);}finally{guard.current=false;setBusy(false);}};
 const attachment=async(r:AttendanceIssue)=>{try{const result=await supabase.storage.from('attendance-issue-files').createSignedUrl(r.attachment!,60);if(result.error)throw result.error;window.open(result.data.signedUrl,'_blank','noopener,noreferrer');}catch(e){setError((e as Error).message);}};
 const rows=data.rows.filter(r=>(!params.get('review')||r.id===params.get('review'))&&(params.get('review')|| (tab==='own'?r.isOwn:tab==='action'?r.canReview:tab==='clarification'?r.isManager&&r.status==='details':tab==='resubmitted'?r.canReview&&r.audit.some(a=>a.action==='edited and resubmitted'):true))&&(!status||r.status===status||r.hrState===status));
 return <div className="space-y-5 text-slate-900 dark:text-white"><header className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold">Attendance requests</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Your reports, direct-report approvals, and authorized HR review.</p></div><button className={button+' bg-violet-600 text-white'} onClick={()=>setForm(true)}>Report attendance issue</button></header>
 <Link className="inline-flex min-h-11 items-center underline" to="/approvals">Open Approval Center →</Link>
 {success&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200">{success}</p>}{(error||data.error)&&<p role="alert" className="text-red-700 dark:text-red-300">{error||data.error} <button className="underline" onClick={()=>void data.load()}>Retry loading</button></p>}
 <div className="flex flex-wrap gap-3">{[['own','My Attendance Requests'],['action','Pending Approval'],['clarification','Manager Clarification Queue'],['resubmitted','Resubmitted Requests'],['all','Authorized History / HR Review']].map(([v,l])=><button key={v} className={button+(tab===v?' bg-violet-600 text-white':'')} onClick={()=>{setTab(v);setParams({});setStatus('');}}>{l}</button>)}<label>Status <select className={button+' bg-white dark:bg-slate-800'} value={status} onChange={e=>{setStatus(e.target.value);setParams({});}}><option value="">All statuses</option>{Object.entries({...issueStatuses,...caseStates}).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div>
 {data.loading?<p>Loading attendance requests…</p>:!rows.length&&<p>No attendance requests in this view.</p>}
 {rows.map(r=><article key={r.id} id={'request-'+r.id} className={'rounded-2xl border bg-white p-5 dark:bg-slate-800 '+(params.get('review')===r.id?'border-violet-500 ring-2 ring-violet-400':'border-slate-200 dark:border-slate-700')}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{r.employeeName}</h2><p>{issueLabels[r.kind]} · {r.work_date}</p><p className="mt-1 break-all text-xs text-slate-500 dark:text-slate-400">Reference: {r.id} · Revision {r.revision}</p></div><strong className="text-violet-700 dark:text-violet-300">{requestStatus(r)}{r.escalated_at&&r.status!=='approved'?' · Escalated to HR':''}</strong></div>
 {r.status==='details'&&<div className="my-4 rounded-xl border border-amber-400 p-4"><strong>Action Required: Update Attendance Request</strong><p className="whitespace-pre-wrap">{r.clarification_message||r.audit.filter(a=>a.action==='details').at(-1)?.reason}</p><p>Returned: {r.reviewed_at&&manila(r.reviewed_at)} · Needs Clarification</p></div>}
 {r.status==='rejected'&&!r.hrState?.startsWith('closed')&&<div className="my-4 rounded-xl border border-amber-400 p-4"><strong>Attendance Request Not Approved – HR Review Pending</strong><p>{r.rejection_category}</p><p className="whitespace-pre-wrap">{r.rejection_comments}</p><p>Rejection does not establish a violation. HR will review the facts.</p></div>}
 <dl className="my-4 grid gap-3 sm:grid-cols-2">{[['Scheduled shift',shiftText(r.schedule)],['Reason',r.category],['Explanation',r.explanation],['Approver',r.approverName||'HR fallback — reporting relationship needs review'],['Submitted',manila(r.submitted_at)],['Response due',manila(r.due_at)],...(r.requested_time?[[r.kind==='punch'?String(r.punch_type).replaceAll('_',' '):'Requested time',manila(r.requested_time)]]:[])].map(([k,v])=><div key={k}><dt className="text-sm text-slate-500 dark:text-slate-400">{k}</dt><dd className="break-words">{v}</dd></div>)}</dl>
 {r.attachment&&<button className={button} onClick={()=>void attachment(r)}>Open private attachment</button>}
 {r.status==='approved'&&<div className="my-4 rounded-xl bg-emerald-50 p-4 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-200"><strong>{approvedLabels[r.kind]}</strong><p>Original schedule preserved. Payroll and leave treatment remain for HR review.</p><p>{r.reviewed_at&&manila(r.reviewed_at)} · Approval reference {r.id}</p>{r.kind==='punch'&&<PunchEvidence id={r.id}/>}</div>}
 {r.canReview&&<ManagerDecision request={r} onChanged={()=>{attendanceChanged();void data.load();}}/>}
 {(!r.canReview&&r.isOwn&&['pending','details','hr_review'].includes(r.status)||(data.canManage&&r.status==='approved'&&r.kind!=='punch'))&&<div className="mt-4 space-y-3"><label className="block">Action reason<input className="mt-1 min-h-12 w-full rounded-lg border bg-transparent p-3" value={notes[r.id]||''} onChange={e=>setNotes({...notes,[r.id]:e.target.value})}/></label><button className={button} disabled={busy||(notes[r.id]||'').trim().length<3} onClick={()=>void run(r,r.status==='approved'?'cancel':'withdraw')}>{r.status==='approved'?'Cancel approved exception':'Withdraw request'}</button></div>}
 {r.isOwn&&r.status==='details'&&<button className={button+' mt-3 bg-violet-600 text-white'} onClick={()=>{setEdit(r);setForm(true);}}>Edit and Resubmit</button>}
 {params.get('review')===r.id?<AttendanceCasePanel request={r} onChanged={()=>void data.load()}/>:<button className={button+' mt-4'} onClick={()=>{setParams({review:r.id});setStatus('');}}>View request, revisions & HR review →</button>}</article>)}
 {data.canManage&&<AttendanceSettings/>}{form&&<AttendanceIssueForm initial={edit} onClose={()=>{setForm(false);setEdit(undefined);}} onSaved={saved}/>}</div>;
}
function ManagerDecision({request:r,onChanged}:{request:AttendanceIssue;onChanged:()=>void}){
 const [action,setAction]=useState('');const [reason,setReason]=useState('');const [category,setCategory]=useState('');const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const guard=useRef(false);const [error,setError]=useState('');
 const run=async()=>{if(guard.current)return;guard.current=true;setBusy(true);setError('');try{await issueRpc('review_attendance_issue',{p_id:r.id,p_revision:r.revision,p_action:action,p_reason:reason,p_category:category||null,p_confirm:confirmed});setAction('');onChanged();}catch(e){setError((e as Error).message);}finally{guard.current=false;setBusy(false);}};
 return <div className="mt-4 space-y-3"><div className="flex flex-wrap gap-3">{[['approve','Approve'],['details','Return for Clarification'],['reject','Reject and Send to HR Review']].map(([a,l])=><button key={a} className={button+(action===a?' bg-violet-600 text-white':'')} disabled={busy} onClick={()=>{setAction(a);setConfirmed(false);setReason(a==='approve'?'Reviewed and approved.':'');}}>{l}</button>)}</div>{action&&<fieldset disabled={busy} className="space-y-3 rounded-xl border border-slate-300 p-4 dark:border-slate-600"><legend className="px-2 font-bold">{action==='details'?'What should the employee clarify?':action==='reject'?'Reject attendance request':'Confirm approval'}</legend>{action==='reject'&&<label className="block">Rejection reason<select className="mt-1 min-h-12 w-full rounded-xl border bg-white p-3 dark:bg-slate-900" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Select a reason</option>{['Insufficient information after clarification','Request conflicts with policy','Supporting document not provided','Request submitted too late','Other'].map(v=><option key={v}>{v}</option>)}</select></label>}<label className="block">{action==='details'?'Clarification message':action==='reject'?'Manager comments':'Approval note'}<textarea maxLength={1000} rows={3} className="mt-1 w-full rounded-xl border bg-transparent p-3" value={reason} onChange={e=>setReason(e.target.value)}/></label>{action==='reject'&&<><p className="rounded-lg border border-amber-400 p-3">Rejecting this request does not automatically mean that the employee committed a violation. HR must review the facts before deciding whether further action is appropriate.</p><p>The request stays unapproved. A factual Incident Report draft will be created for HR. No NTE will be sent automatically.</p><label className="flex gap-3"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm this rejection and referral to HR.</label></>}{action==='details'&&<p>This is a request for more information. It does not create an Incident Report or NTE.</p>}<button className={button+' bg-violet-600 text-white'} disabled={reason.trim().length<3||(action==='reject'&&(!category||!confirmed))} onClick={()=>void run()}>{busy?'Saving…':action==='approve'?'Confirm Approval':action==='details'?'Return for Clarification':'Reject and Send to HR Review'}</button></fieldset>}{error&&<p role="alert" className="text-red-700 dark:text-red-300">{error} Your comments have been retained.</p>}</div>;
}
function AttendanceSettings(){const [config,setConfig]=useState<any>();const [hours,setHours]=useState(48);const [minutes,setMinutes]=useState(120);const [recipients,setRecipients]=useState<string[]>([]);const [reason,setReason]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const load=async()=>{try{const d=await issueRpc('get_attendance_issue_settings');setConfig(d);setHours(d.settings.clarification_hours);setMinutes(d.settings.response_minutes);setRecipients(d.settings.fallback_ids);}catch(e){setMessage((e as Error).message);}};useEffect(()=>{void load();},[]);return <details className="rounded-xl border p-4"><summary>HR response period, fallback recipients & email delivery</summary>{message&&<p role="status">{message}</p>}{config&&<div className="mt-4 space-y-3"><label className="block">Response period (minutes)<input type="number" min={15} max={10080} className="ml-3 rounded border bg-transparent p-2" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label className="block">Employee clarification period (hours)<input type="number" min={1} max={720} className="ml-3 rounded border bg-transparent p-2" value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><p>With no recipients selected, all active HR attendance administrators receive alerts within their existing scope.</p>{config.recipients.map((r:any)=><label key={r.id} className="mr-4 inline-flex gap-2"><input type="checkbox" checked={recipients.includes(r.id)} onChange={e=>setRecipients(e.target.checked?[...recipients,r.id]:recipients.filter(x=>x!==r.id))}/>{r.name}</label>)}<label className="block">Change reason<input className="ml-3 rounded border bg-transparent p-2" value={reason} onChange={e=>setReason(e.target.value)}/></label><button className={button} disabled={busy||reason.trim().length<3} onClick={async()=>{setBusy(true);try{await issueRpc('save_attendance_issue_settings',{p_minutes:minutes,p_recipients:recipients,p_reason:reason});await issueRpc('save_attendance_clarification_period',{p_hours:hours,p_reason:reason});setMessage('Settings saved. Existing request deadlines are preserved.');await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Save response settings</button><p>Last changed: {manila(config.settings.changed_at)}</p><details><summary>Recent email delivery attempts</summary>{config.deliveries.map((d:any)=><p key={d.id} className="mt-2 text-sm">{d.event} · {d.status} · {d.attempts} attempts · {manila(d.created_at)} {d.error}</p>)}</details></div>}</details>;}
