import React,{useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import AttendanceIssueForm from '../../components/attendance/AttendanceIssueForm';
import {supabase} from '../../services/supabaseClient';
import {AttendanceIssue,attendanceChanged,approvedLabels,issueLabels,issueRpc,issueStatuses,manila,shiftText,useAttendanceIssues} from '../../services/attendanceIssues';
const button='min-h-11 rounded-xl border border-slate-300 px-4 py-2 font-semibold dark:border-slate-600 disabled:opacity-50';
function PunchEvidence({id}:{id:string}){const [data,setData]=useState<any>();const [error,setError]=useState('');return <details onToggle={e=>{if(e.currentTarget.open&&!data)issueRpc('get_attendance_issue_punches',{p_id:id}).then(setData).catch(e=>setError(e.message));}} className="mt-3"><summary>Original and corrected punches</summary>{error&&<p role="alert">{error}</p>}{data&&['original','effective'].map(key=><div key={key} className="mt-3"><h4 className="font-semibold">{key==='original'?'Original punches':'Current corrected evidence'}</h4>{data[key].length?data[key].map((p:any,i:number)=><p key={i}>{p.type.replaceAll('_',' ')} · {manila(p.timestamp)}</p>):<p>No original punches recorded.</p>}</div>)}</details>;}
export default function AttendanceRequests(){const data=useAttendanceIssues();const [params,setParams]=useSearchParams();const [form,setForm]=useState(params.has('new'));const [edit,setEdit]=useState<AttendanceIssue>();const [tab,setTab]=useState(params.has('review')?'all':'own');const [status,setStatus]=useState('');const [notes,setNotes]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const guard=useRef(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
 const saved=(id:string)=>{setForm(false);setEdit(undefined);setParams({review:id});setTab('all');setSuccess('Request submitted for approval');void data.load();};
 const run=async(r:AttendanceIssue,action:string)=>{if(guard.current)return;guard.current=true;setBusy(true);setError('');try{await issueRpc('review_attendance_issue',{p_id:r.id,p_revision:r.revision,p_action:action,p_reason:notes[r.id]||''});setSuccess(action==='approve'?approvedLabels[r.kind]:'Request updated successfully');attendanceChanged();await data.load();}catch(e){setError((e as Error).message);}finally{guard.current=false;setBusy(false);}};
 const attachment=async(r:AttendanceIssue)=>{try{const result=await supabase.storage.from('attendance-issue-files').createSignedUrl(r.attachment!,60);if(result.error)throw result.error;window.open(result.data.signedUrl,'_blank','noopener,noreferrer');}catch(e){setError((e as Error).message);}};
 const rows=data.rows.filter(r=>(tab==='own'?r.isOwn:tab==='action'?r.canReview:true)&&(!status||r.status===status));
 return <div className="space-y-5 text-slate-900 dark:text-white"><header className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold">Attendance requests</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Your reports, direct-report approvals, and authorized HR review.</p></div><button className={button+' bg-violet-600 text-white'} onClick={()=>setForm(true)}>Report attendance issue</button></header>
 <Link className="inline-flex min-h-11 items-center underline" to="/approvals">Open Approval Center →</Link>
 {success&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200">{success}</p>}{(error||data.error)&&<p role="alert" className="text-red-700 dark:text-red-300">{error||data.error} <button className="underline" onClick={()=>void data.load()}>Retry loading</button></p>}
 <div className="flex flex-wrap gap-3">{[['own','My Attendance Requests'],['action','Needs your approval'],['all','Authorized history / HR review']].map(([v,l])=><button key={v} className={button+(tab===v?' bg-violet-600 text-white':'')} onClick={()=>{setTab(v);setParams({});}}>{l}</button>)}<label>Status <select className={button+' bg-white dark:bg-slate-800'} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{Object.entries(issueStatuses).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div>
 {data.loading?<p>Loading attendance requests…</p>:!rows.length&&<p>No attendance requests in this view.</p>}
 {rows.map(r=><article key={r.id} id={'request-'+r.id} className={'rounded-2xl border bg-white p-5 dark:bg-slate-800 '+(params.get('review')===r.id?'border-violet-500 ring-2 ring-violet-400':'border-slate-200 dark:border-slate-700')}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{r.employeeName}</h2><p>{issueLabels[r.kind]} · {r.work_date}</p></div><strong className="text-violet-700 dark:text-violet-300">{issueStatuses[r.status]}{r.escalated_at&&r.status!=='approved'?' · Escalated to HR':''}</strong></div>
 <dl className="my-4 grid gap-3 sm:grid-cols-2">{[['Scheduled shift',shiftText(r.schedule)],['Reason',r.category],['Explanation',r.explanation],['Approver',r.approverName||'HR fallback — reporting relationship needs review'],['Submitted',manila(r.submitted_at)],['Response due',manila(r.due_at)],...(r.requested_time?[[r.kind==='punch'?String(r.punch_type).replaceAll('_',' '):'Requested time',manila(r.requested_time)]]:[])].map(([k,v])=><div key={k}><dt className="text-sm text-slate-500 dark:text-slate-400">{k}</dt><dd className="break-words">{v}</dd></div>)}</dl>
 {r.attachment&&<button className={button} onClick={()=>void attachment(r)}>Open private attachment</button>}
 {r.status==='approved'&&<div className="my-4 rounded-xl bg-emerald-50 p-4 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-200"><strong>{approvedLabels[r.kind]}</strong><p>Original schedule preserved. Payroll and leave treatment remain for HR review.</p><p>{r.reviewed_at&&manila(r.reviewed_at)} · Approval reference {r.id}</p>{r.kind==='punch'&&<PunchEvidence id={r.id}/>}</div>}
 {(r.canReview||(r.isOwn&&['pending','details','hr_review'].includes(r.status))||(data.canManage&&r.status==='approved'&&r.kind!=='punch'))&&<div className="mt-4 space-y-3"><label className="block">Review / action note<input className="mt-1 min-h-12 w-full rounded-lg border bg-transparent p-3" value={notes[r.id]||''} onChange={e=>setNotes({...notes,[r.id]:e.target.value})}/></label><div className="flex flex-wrap gap-3">{(r.canReview?[['approve','Approve'],['reject','Reject'],['details','Ask for details']]:r.isOwn&&r.status!=='approved'?[['withdraw','Withdraw request']]:[['cancel','Cancel approved exception']]).map(([a,l])=><button key={a} className={button+(a==='approve'?' bg-violet-600 text-white':'')} disabled={busy||(notes[r.id]||'').trim().length<3} onClick={()=>void run(r,a)}>{l}</button>)}</div></div>}
 {r.isOwn&&r.status==='details'&&<button className={button+' mt-3'} onClick={()=>{setEdit(r);setForm(true);}}>Update and resubmit</button>}
 <details open={params.get('review')===r.id} className="mt-4"><summary className="cursor-pointer font-semibold">Request history & approval source</summary>{r.audit.map(a=><p key={a.id} className="mt-3 text-sm">{a.action} · {manila(a.created_at)}{a.actor?` · Account ${a.actor}`:' · System'}{a.reason?` — ${a.reason}`:''}</p>)}</details></article>)}
 {data.canManage&&<AttendanceSettings/>}{form&&<AttendanceIssueForm initial={edit} onClose={()=>{setForm(false);setEdit(undefined);}} onSaved={saved}/>}</div>;
}
function AttendanceSettings(){const [config,setConfig]=useState<any>();const [minutes,setMinutes]=useState(120);const [recipients,setRecipients]=useState<string[]>([]);const [reason,setReason]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const load=async()=>{try{const d=await issueRpc('get_attendance_issue_settings');setConfig(d);setMinutes(d.settings.response_minutes);setRecipients(d.settings.fallback_ids);}catch(e){setMessage((e as Error).message);}};useEffect(()=>{void load();},[]);return <details className="rounded-xl border p-4"><summary>HR response period, fallback recipients & email delivery</summary>{message&&<p role="status">{message}</p>}{config&&<div className="mt-4 space-y-3"><label className="block">Response period (minutes)<input type="number" min={15} max={10080} className="ml-3 rounded border bg-transparent p-2" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><p>With no recipients selected, all active HR attendance administrators receive alerts within their existing scope.</p>{config.recipients.map((r:any)=><label key={r.id} className="mr-4 inline-flex gap-2"><input type="checkbox" checked={recipients.includes(r.id)} onChange={e=>setRecipients(e.target.checked?[...recipients,r.id]:recipients.filter(x=>x!==r.id))}/>{r.name}</label>)}<label className="block">Change reason<input className="ml-3 rounded border bg-transparent p-2" value={reason} onChange={e=>setReason(e.target.value)}/></label><button className={button} disabled={busy||reason.trim().length<3} onClick={async()=>{setBusy(true);try{await issueRpc('save_attendance_issue_settings',{p_minutes:minutes,p_recipients:recipients,p_reason:reason});setMessage('Settings saved. Existing request deadlines are preserved.');await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Save response settings</button><p>Last changed: {manila(config.settings.changed_at)}</p><details><summary>Recent email delivery attempts</summary>{config.deliveries.map((d:any)=><p key={d.id} className="mt-2 text-sm">{d.event} · {d.status} · {d.attempts} attempts · {manila(d.created_at)} {d.error}</p>)}</details></div>}</details>;}
