import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {channelRpc} from '../../services/attendanceChannels';
export default function AttendanceReview(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[bu,setBu]=useState(''),[busy,setBusy]=useState(false);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const [form,setForm]=useState({enabled:false,from:today,minutes:15,count:3,window:30,auto:false});const [notes,setNotes]=useState<Record<string,string>>({});
 const load=async()=>{try{setData(await channelRpc('get_attendance_review'));}catch(e){setError((e as Error).message);}};useEffect(()=>{void load();},[]);
 useEffect(()=>{const p=data?.policies.find((p:any)=>p.business_unit_id===bu);setForm(p?{enabled:p.enabled,from:p.effective_from,minutes:p.late_minutes,count:p.late_count,window:p.window_days,auto:p.auto_ir}:{enabled:false,from:today,minutes:15,count:3,window:30,auto:false});},[bu,data]);
 const run=async(fn:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="space-y-5"><h1 className="text-3xl font-bold">Attendance flags & review</h1><Link className="inline-flex min-h-12 items-center rounded-xl border border-violet-500 px-4 font-semibold" to="/payroll/attendance-requests">Attendance requests & manager follow-up →</Link><p>Review the evidence before deciding. Flags do not issue an NTE or change payroll.</p>{error&&<p role="alert" className="text-red-600">{error}</p>}{data?.canManage&&<section className="rounded-2xl border bg-white p-5 dark:bg-slate-800"><h2 className="text-xl font-semibold">BU review rules</h2><p className="my-2 text-sm">Example thresholds are shown until saved. Automated checks run every 15 minutes for enabled BUs, starting on the effective date. No historical cases are generated automatically.</p><label className="block">Business unit<select value={bu} onChange={e=>setBu(e.target.value)} className="ml-2 min-h-12 rounded border bg-transparent p-2"><option value="">Choose a BU</option>{data.businessUnits.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{bu&&<div className="mt-4 space-y-4"><label className="block"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Enable attendance flags</label><label className="block">Effective date<input type="date" min={today} value={form.from} onChange={e=>setForm({...form,from:e.target.value})} className="ml-2 min-h-12 rounded border bg-transparent p-2"/></label><div className="flex flex-wrap gap-4">{[{key:'minutes',label:'More than this many minutes late (after company grace)',max:240},{key:'count',label:'Or more than this many late days',max:60},{key:'window',label:'Within this many calendar days',max:90}].map(f=><label key={f.key} className="max-w-xs">{f.label}<input type="number" min={f.key==='minutes'?0:1} max={f.max} value={form[f.key as 'minutes'|'count'|'window']} onChange={e=>setForm({...form,[f.key]:Number(e.target.value)})} className="mt-1 block min-h-12 w-full rounded border bg-transparent p-2"/></label>)}</div><label className="block"><input type="checkbox" checked={form.auto} onChange={e=>setForm({...form,auto:e.target.checked})}/> Automatically submit detected cases to IR review</label><p className="text-sm">Missing/unpublished schedules, clock exemptions, flexible shifts, approved/pending leave and pending missed-punch requests are excluded. Any recorded punch prevents a zero-punch absence flag. Skeletal shifts retain their working hours.</p><button disabled={busy} className="min-h-12 rounded-lg bg-violet-600 px-5 font-semibold text-white" onClick={()=>void run(()=>channelRpc('save_attendance_review_policy',{p_bu:bu,p_enabled:form.enabled,p_from:form.from,p_minutes:form.minutes,p_count:form.count,p_window:form.window,p_auto_ir:form.auto}))}>Save review rules</button></div>}</section>}
 {!data?<p>Loading review…</p>:!data.flags.length?<p>No attendance flags to show.</p>:data.flags.map((f:any)=><section key={f.id} className="rounded-2xl border bg-white p-5 dark:bg-slate-800"><h2 className="font-bold">⚠ {f.employeeName} · {f.work_date}</h2><p>{f.kind==='absence'?'Unexcused Absence (AWOL) · for review':(f.evidence.lateCount>f.evidence.thresholdCount?'Habitual Tardiness · for review':'Late Arrival · for review')} · {f.status}</p><p className="mt-2 text-sm">{f.evidence.lateMinutes} minutes late · {f.evidence.lateCount} late days in {f.evidence.windowDays} days · schedule v{f.evidence.version}</p><details className="my-2"><summary>Recorded shift evidence</summary><p>{new Date(f.evidence.shiftStart).toLocaleString('en-PH',{timeZone:'Asia/Manila'})} → {new Date(f.evidence.shiftEnd).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</p><p>Clock-in: {f.evidence.firstIn?new Date(f.evidence.firstIn).toLocaleString('en-PH',{timeZone:'Asia/Manila'}):'No clock-in recorded'}</p></details>{f.incident_id&&<Link className="inline-block min-h-11 underline" to={`/feedback/cases?caseId=${f.incident_id}`}>Open IR review</Link>}{f.canResolve&&f.status==='review'&&<div className="mt-3"><input value={notes[f.id]??''} onChange={e=>setNotes({...notes,[f.id]:e.target.value})} placeholder="HR review note" className="min-h-12 w-full rounded border bg-transparent p-2"/>{['resolved','dismissed'].map(status=><button key={status} disabled={busy||(notes[f.id]??'').trim().length<3} onClick={()=>void run(()=>channelRpc('resolve_attendance_review',{p_id:f.id,p_status:status,p_note:notes[f.id]}))} className="mr-3 mt-2 min-h-11 rounded border px-4">{status==='resolved'?'Mark reviewed':'Dismiss flag'}</button>)}</div>}</section>)}</div>;
}
