import React,{useCallback,useEffect,useState} from 'react';
import {ClockException,ExceptionAdmin,getExceptionAdmin,saveClockException} from '../../services/employeeAttendance';
import AttendanceCorrection from '../../components/attendance/AttendanceCorrection';
const input='mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800';
export default function ClockingExceptions(){
 const [data,setData]=useState<ExceptionAdmin|null>(null);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [edit,setEdit]=useState<ClockException|null>(null);
 const [employee,setEmployee]=useState('');const [type,setType]=useState('');const [requiresClock,setRequiresClock]=useState(true);const [from,setFrom]=useState('');const [to,setTo]=useState('');const [reason,setReason]=useState('');const [reviewEmployee,setReviewEmployee]=useState('');const [reviewDate,setReviewDate]=useState('');
 const load=useCallback(async()=>{try{const d=await getExceptionAdmin();setData(d);setFrom(v=>v||d.today);setReviewDate(v=>v||d.today);}catch(e){setError((e as Error).message);}},[]);useEffect(()=>{void load();},[load]);
 const select=(r:ClockException)=>{setEdit(r);setEmployee(r.employee_id);setType(r.exception_type);setRequiresClock(r.requires_clock);setFrom(r.effective_from);setTo(r.effective_to??'');setReason('');setMessage('Edit the dates or clocking requirement, then save a new version.');};
 const reset=()=>{setEdit(null);setEmployee('');setType('');setRequiresClock(true);setFrom(data?.today??'');setTo('');setReason('');};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await saveClockException({employee,recordId:edit?.record_id??null,revision:edit?.revision??0,type,requiresClock,from,to:to||null,reason});await load();reset();setMessage('Exception version saved. Previous versions remain in the audit history.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const current=data?.records.filter(r=>!data.records.some(n=>n.record_id===r.record_id&&n.revision>r.revision))??[];
 return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Clocking exceptions & attendance review</h1><p className="mt-2 text-slate-500 dark:text-slate-300">Manage dated exceptions and recorded corrections using existing HR/Admin access.</p></div>{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{message&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{message}</p>}{data&&<>
 <section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h2 className="text-xl font-bold">{edit?'Edit / expire exception':'Add clocking exception'}</h2><p className="my-3 text-sm">Choose <strong>No — hide clock controls</strong> for an employee who is exempt. The dashboard updates after the next refresh. Everyone requires clock-in/out unless an explicit exception covers the date. To expire an exception, set its last effective date and save a new version. Job titles and HRIS roles do not determine exemption.</p><form onSubmit={e=>void save(e)}><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2"><label>Employee<select required disabled={!!edit} className={input} value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">Choose employee</option>{data.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Exception type<input required minLength={3} maxLength={100} className={input} value={type} onChange={e=>setType(e.target.value)} placeholder="For example, approved schedule-based attendance"/></label><label>Requires clock-in/out<select aria-label="Requires clock-in/out" className={input} value={String(requiresClock)} onChange={e=>setRequiresClock(e.target.value==='true')}><option value="true">Yes — show clock controls</option><option value="false">No — hide clock controls</option></select></label><label>Effective start date<input required type="date" className={input} value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Effective end date (inclusive)<input type="date" min={from} className={input} value={to} onChange={e=>setTo(e.target.value)}/></label><label className="sm:col-span-2">Reason for this version<textarea required minLength={3} maxLength={1000} className={input} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="flex gap-3 sm:col-span-2"><button className="min-h-12 rounded-xl bg-violet-600 px-5 py-3 font-semibold text-white disabled:opacity-50">{busy?'Saving…':'Save exception version'}</button>{edit&&<button type="button" className="min-h-12 rounded-xl border px-5" onClick={reset}>Cancel edit</button>}</div></fieldset></form></section>
 <section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h2 className="text-xl font-bold">Current exception records</h2>{current.length===0&&<p className="mt-4">No exceptions recorded. Everyone requires clocking.</p>}<div className="mt-4 space-y-3">{current.map(r=><div key={r.id} className="rounded-xl border p-4 dark:border-slate-700"><div className="flex flex-wrap justify-between gap-3"><div><strong>{r.employeeName}</strong><p>{r.exception_type} · Clocking: {r.requires_clock?'Yes':'No'}</p><p className="text-sm">{r.effective_from} → {r.effective_to??'No end date'} · {r.effective_from>data.today?'Upcoming':r.effective_to&&r.effective_to<data.today?'Expired':'Active'}</p></div><button className="min-h-11 rounded-lg border px-4 font-semibold text-violet-700 dark:text-violet-200" disabled={busy} onClick={()=>select(r)}>Edit / expire</button></div><p className="mt-2 text-sm">{r.reason}</p><p className="text-xs text-slate-500">v{r.revision} · {r.createdByName} · {new Date(r.created_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</p><details className="mt-3 text-sm"><summary className="cursor-pointer font-semibold">Audit history</summary>{data.records.filter(x=>x.record_id===r.record_id).map(x=><div key={x.id} className="mt-2 border-t pt-2"><p>v{x.revision} · {x.effective_from}–{x.effective_to??'open'} · Requires clocking: {x.requires_clock?'Yes':'No'}</p><p>{x.exception_type} · {x.reason}</p><p>{x.createdByName} · {new Date(x.created_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</p></div>)}</details></div>)}</div></section>
 <section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h2 className="text-xl font-bold">HR attendance review / correction</h2><p className="my-3 text-sm">Select an employee and date to review the shared attendance record. Corrections retain original punches and create a new audited version.</p><div className="grid gap-4 sm:grid-cols-2"><label>Employee to review<select className={input} value={reviewEmployee} onChange={e=>setReviewEmployee(e.target.value)}><option value="">Choose employee</option>{data.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Work date<input type="date" className={input} value={reviewDate} onChange={e=>setReviewDate(e.target.value)}/></label></div>{reviewEmployee&&reviewDate&&<AttendanceCorrection key={`${reviewEmployee}:${reviewDate}`} employee={reviewEmployee} date={reviewDate}/>}</section>
 </>}</div>;
}
