import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../../services/supabaseClient';
export default function LeaveBalanceImport(){
 const [batches,setBatches]=useState<any[]>([]),[selected,setSelected]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const {data,error}=await supabase.rpc('get_leave_balance_migration_workspace');if(error)throw error;setBatches(data.batches||[]);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const batch=batches.find(b=>b.id===selected);
 async function review(action:string){setBusy(true);setError('');try{const {error}=await supabase.rpc('review_leave_balance_migration',{p_batch_id:selected,p_action:action,p_note:note});if(error)throw error;await load();setNote('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="mx-auto max-w-6xl space-y-5 p-6"><header><h1 className="text-3xl font-bold">Leave balance approvals</h1><p className="mt-2">Imported balances remain inactive until the required independent approval.</p><Link className="mt-4 inline-block rounded-xl bg-violet-600 px-5 py-3 font-semibold text-white" to="/payroll/import/leave-balances">Import or enter opening balances</Link></header>
 {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}
 <label className="block">Saved balance entry<select className="mt-2 w-full rounded-xl border p-3" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select an entry to review</option>{batches.map(b=><option key={b.id} value={b.id}>{b.source_file} · {b.created_by_name} · {b.as_of_date} · {b.status.replaceAll('_',' ')}</option>)}</select></label>
 {batch&&<section className="space-y-4 rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="text-xl font-bold">{batch.source_file}</h2><p>{batch.approval_route} · {batch.status.replaceAll('_',' ')}</p><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{['Employee','Leave type','Remaining balance','As of','Evidence'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{batch.rows.map((r:any)=><tr className="border-t" key={r.id}><td className="p-3">{r.employee_name} · {r.employee_id_code}</td><td>{r.leave_type}</td><td>{Number(r.remaining_balance).toFixed(2)} days</td><td>{r.as_of_date}</td><td>{r.supporting_document&&/^https:\/\//.test(r.supporting_document)?<a className="text-violet-700 underline" href={r.supporting_document} target="_blank" rel="noopener noreferrer">View evidence</a>:r.source}</td></tr>)}</tbody></table></div>
 {batch.can_act&&<><label className="block">Review note<textarea className="mt-2 w-full rounded-xl border p-3" value={note} onChange={e=>setNote(e.target.value)}/></label><div className="flex gap-3">{['approve','return','reject'].map(action=><button className="rounded-xl border px-5 py-3 font-semibold text-violet-700 disabled:opacity-40" key={action} disabled={busy||(action!=='approve'&&!note.trim())} onClick={()=>void review(action)}>{action==='approve'?'Approve and activate':action==='return'?'Return for correction':'Reject'}</button>)}</div></>}
 <details><summary className="cursor-pointer font-semibold">Audit history</summary>{batch.audit.map((a:any)=><p className="mt-2 text-sm" key={a.id}>{a.created_at} · {a.action} · {a.note}</p>)}</details></section>}
 </main>;
}
