import React,{useEffect,useMemo,useState} from 'react';
import Button from '../../components/ui/Button';
import Card from '../../components/ui/Card';
import {usePayrollField} from '../../modules/payroll/usePayrollSelection';
import {formatPayrollDate,payrollCycleLabel,payrollCycleOptions} from '../../modules/payroll/payrollCycle';
import {actDebt,addDebtDocumentLink,createDebtRecord,getDebtContext,openDebtDocument,openDebtLink,peso,reviewDebtDocument,uploadDebtDocument,type CreateDebtRecord,type DebtContext,type DebtDocument,type DebtKind,type DebtStatus,type PayrollDebt} from '../../modules/payroll/debts';

const control='mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-900';
const kindLabel:Record<DebtKind,string>={existing_loan:'Loan',previous_debt:'Debt',external_nte_deduction:'NTE deduction',nte_deduction:'NTE deduction'};
const statusColor:Record<string,string>={Active:'bg-emerald-100 text-emerald-800','Paid or closed':'bg-slate-100 text-slate-700',Completed:'bg-slate-100 text-slate-700','Pending Finance approval':'bg-amber-100 text-amber-900','Returned for correction':'bg-orange-100 text-orange-900',Rejected:'bg-red-100 text-red-800',Draft:'bg-slate-100 text-slate-700',Paused:'bg-amber-100 text-amber-900'};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const cycles=payrollCycleOptions(new Date(),1,8).filter(c=>c.releaseDate>=today()).slice(0,8);
type AddMode='existing_loan'|'previous_debt'|'external_nte_deduction';
type Tab='Active'|'Pending Finance approval'|'Needs correction'|'Paid or closed'|'Authorized NTE deductions';

function statusGroup(debt:PayrollDebt,tab:Tab){if(tab==='Active')return ['Active','Paused'].includes(debt.status)&&debt.debt_kind!=='external_nte_deduction';if(tab==='Pending Finance approval')return debt.status==='Pending Finance approval';if(tab==='Needs correction')return ['Draft','Returned for correction','Rejected'].includes(debt.status);if(tab==='Paid or closed')return ['Paid or closed','Completed','Cancelled'].includes(debt.status);return debt.debt_kind.includes('nte');}
function documentStatus(debt:PayrollDebt){const primary=debt.documents.find(d=>d.is_primary)||debt.documents[0];return primary?.status||'Missing';}
function schedulePreview(balance:string,basis:CreateDebtRecord['deductionBasis'],installment:string,term:number){const remaining=Math.max(Number(balance)||0,0);const regular=basis==='fixed_per_month'?(Number(installment)||0)/2:Number(installment)||0;const count=basis==='remaining_months'?term*2:basis==='remaining_cutoffs'?term:regular>0?Math.ceil(remaining/regular):0;const perCutoff=basis.startsWith('remaining_')&&count?Math.round(remaining/count*100)/100:regular;const final=count?Math.round((remaining-Math.max(0,count-1)*perCutoff)*100)/100:0;return {count,perCutoff,final:Math.max(0,Math.min(perCutoff,final||perCutoff))};}

function DocumentInputs({file,setFile,link,setLink}:{file:File|null;setFile:(file:File|null)=>void;link:{title:string;url:string;provider:string};setLink:(link:{title:string;url:string;provider:string})=>void}){
 const [source,setSource]=useState<'upload'|'link'>('upload');
 return <section className="rounded-2xl border p-4"><h3 className="font-bold">Supporting authority document</h3><p className="mt-1 text-sm text-slate-500">At least one source is required before Finance approval. You may add both later.</p><div className="mt-3 flex gap-2"><Button size="sm" variant={source==='upload'?'primary':'secondary'} onClick={()=>setSource('upload')}>Upload document</Button><Button size="sm" variant={source==='link'?'primary':'secondary'} onClick={()=>setSource('link')}>Add document link</Button></div>{source==='upload'?<label className="mt-3 block">PDF, JPG, or PNG<input className={control} type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/>{file?<span className="text-xs text-emerald-700">Selected: {file.name}</span>:null}</label>:<div className="mt-3 grid gap-3 sm:grid-cols-2"><label>Document title<input className={control} value={link.title} onChange={e=>setLink({...link,title:e.target.value})}/></label><label>Provider<select className={control} value={link.provider} onChange={e=>setLink({...link,provider:e.target.value})}><option>Google Drive</option><option>SharePoint</option><option>Dropbox</option><option>Other approved secure storage</option></select></label><label className="sm:col-span-2">Secure URL<input className={control} type="url" placeholder="https://" value={link.url} onChange={e=>setLink({...link,url:e.target.value})}/></label></div>}</section>;
}

function AddDrawer({mode,context,onClose,onSaved}:{mode:AddMode;context:DebtContext;onClose:()=>void;onSaved:()=>void}){
 const [step,setStep]=useState(1);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [file,setFile]=useState<File|null>(null);const [link,setLink]=useState({title:'',url:'',provider:'Google Drive'});
 const [form,setForm]=useState<CreateDebtRecord>({id:'',employeeId:'',kind:mode,source:mode==='external_nte_deduction'?'Authorized NTE deduction':'',originalAmount:'',openingBalance:'',amountPaid:'',installmentsPaid:0,deductionBasis:'remaining_cutoffs',installment:'',term:6,firstDate:cycles[0]?.releaseDate||'',issuedOn:today(),authorityReference:'',signedOn:today(),notes:''});
 const preview=schedulePreview(form.openingBalance,form.deductionBasis,form.installment,form.term);const employee=context.employees.find(e=>e.id===form.employeeId);
 async function save(submit:boolean){setBusy(true);setError('');try{const id=crypto.randomUUID();await createDebtRecord({...form,id});if(file)await uploadDebtDocument(id,file);if(link.url.trim())await addDebtDocumentLink(id,link.title,link.url,link.provider,form.signedOn,!file);if(submit){if(!file&&!link.url.trim())throw new Error('Upload a document or add a secure document link before submitting.');await actDebt(id,'submit','Submitted to Lenny Rose Casas · Finance');}onSaved();onClose();}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
 const title=mode==='previous_debt'?'Add previous loan or debt':mode==='external_nte_deduction'?'Add authorized NTE deduction':'Add loan or debt';
 return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40" role="dialog" aria-modal="true" aria-labelledby="add-debt-title"><div className="h-full w-full max-w-3xl overflow-y-auto bg-white p-6 shadow-2xl dark:bg-slate-900"><header className="flex items-start justify-between gap-3"><div><p className="font-semibold text-violet-700">Loans & Debt · Step {step} of 3</p><h2 id="add-debt-title" className="text-2xl font-bold">{title}</h2><p className="text-sm text-slate-500">Nothing affects payroll until Finance accepts the authority and approves the record.</p></div><button className="min-h-11 px-3 text-2xl" onClick={onClose} aria-label="Close">×</button></header>
  <div className="my-5 grid grid-cols-3 gap-2">{['Person & type','Balance & schedule','Authority & submit'].map((label,index)=><button key={label} className={`rounded-xl p-3 text-sm font-semibold ${step===index+1?'bg-violet-600 text-white':'bg-slate-100 text-slate-600'}`} onClick={()=>setStep(index+1)}>{index+1}. {label}</button>)}</div>
  {error?<p role="alert" className="mb-4 rounded-xl border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>:null}
  {step===1?<div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">Employee<select className={control} value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}><option value="">Select employee</option>{context.employees.map(e=><option key={e.id} value={e.id}>{e.name} · {e.code}</option>)}</select></label><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-500">Business unit</p><strong>{context.scopes[0]?.name||'Selected payroll scope'}</strong></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-500">Record type</p><strong>{kindLabel[mode]}</strong></div><label className="sm:col-span-2">{mode==='external_nte_deduction'?'Deduction reason':'Loan or debt type / name'}<input className={control} value={form.source} onChange={e=>setForm({...form,source:e.target.value})} placeholder={mode==='external_nte_deduction'?'Reason stated in signed authority':'e.g. Salary loan, cash advance'}/></label>{mode==='external_nte_deduction'?<p className="sm:col-span-2 rounded-xl bg-blue-50 p-4 text-blue-900"><strong>NTE record unavailable — signed authority to deduct provided</strong><br/><span className="text-sm">An HRIS NTE is not required when the employee’s signed authority is attached.</span></p>:null}</div>:null}
  {step===2?<div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label>Original amount<input className={control} inputMode="decimal" value={form.originalAmount} onChange={e=>setForm({...form,originalAmount:e.target.value})}/></label><label>Current remaining balance<input className={control} inputMode="decimal" value={form.openingBalance} onChange={e=>setForm({...form,openingBalance:e.target.value})}/></label><label>Amount already paid<input className={control} inputMode="decimal" value={form.amountPaid} onChange={e=>setForm({...form,amountPaid:e.target.value})}/></label><label>Installments already paid<input className={control} type="number" min="0" value={form.installmentsPaid} onChange={e=>setForm({...form,installmentsPaid:Number(e.target.value)})}/></label><label>Original loan / authority date<input className={control} type="date" value={form.issuedOn} onChange={e=>setForm({...form,issuedOn:e.target.value})}/></label><label>Repayment option<select className={control} value={form.deductionBasis} onChange={e=>setForm({...form,deductionBasis:e.target.value as CreateDebtRecord['deductionBasis']})}><option value="fixed_per_cutoff">Fixed amount per cutoff</option><option value="fixed_per_month">Fixed amount per month</option><option value="remaining_cutoffs">Number of remaining cutoffs</option><option value="remaining_months">Number of remaining months</option></select></label><label>{form.deductionBasis.includes('month')?'Monthly deduction amount':'Deduction per cutoff'}<input className={control} inputMode="decimal" value={form.installment} onChange={e=>setForm({...form,installment:e.target.value})}/></label>{form.deductionBasis.startsWith('remaining_')?<label>Number of remaining {form.deductionBasis==='remaining_months'?'months':'cutoffs'}<input className={control} type="number" min="1" max="120" value={form.term} onChange={e=>setForm({...form,term:Number(e.target.value)})}/></label>:null}</div><fieldset><legend className="font-semibold">Deduction start payroll cycle</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{cycles.slice(0,4).map(c=><label key={c.releaseDate} className={`cursor-pointer rounded-xl border p-3 ${form.firstDate===c.releaseDate?'border-violet-500 bg-violet-50':'border-slate-200'}`}><input className="mr-2" type="radio" name="cycle" checked={form.firstDate===c.releaseDate} onChange={()=>setForm({...form,firstDate:c.releaseDate})}/><strong>{formatPayrollDate(c.releaseDate)}</strong><span className="block pl-6 text-xs text-slate-500">{payrollCycleLabel(c).split('· ')[1]}</span></label>)}</div></fieldset><div className="rounded-2xl bg-violet-50 p-4 text-violet-950"><p className="text-sm font-semibold">Calculated repayment</p><p className="mt-1 text-xl font-bold">{preview.count} cutoffs · {peso(preview.perCutoff)} per cutoff</p><p className="text-sm">Expected final deduction: {peso(preview.final)}. The final deduction never exceeds the remaining balance.</p></div></div>:null}
  {step===3?<div className="space-y-4"><label>{mode==='external_nte_deduction'?'Authority-to-deduct reference':'Existing loan / authority reference'}<input className={control} value={form.authorityReference} onChange={e=>setForm({...form,authorityReference:e.target.value})}/></label><label>Date authority was signed<input className={control} type="date" value={form.signedOn} onChange={e=>setForm({...form,signedOn:e.target.value})}/></label><label>Notes<textarea className={control} rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><DocumentInputs file={file} setFile={setFile} link={link} setLink={setLink}/><div className="rounded-xl bg-slate-50 p-4"><p><strong>{employee?.name||'Employee not selected'}</strong> · {kindLabel[mode]}</p><p className="text-sm">{peso(form.openingBalance)} remaining · {peso(preview.perCutoff)} next cutoff · routed to {context.financeReviewer}</p></div></div>:null}
  <footer className="mt-6 flex flex-wrap justify-between gap-3"><Button variant="secondary" disabled={busy} onClick={()=>step===1?onClose():setStep(step-1)}>{step===1?'Cancel':'Back'}</Button><div className="flex gap-2">{step===3?<Button variant="secondary" disabled={busy} onClick={()=>void save(false)}>Save draft</Button>:null}{step<3?<Button disabled={busy||step===1&&(!form.employeeId||!form.source.trim())} onClick={()=>setStep(step+1)}>Continue</Button>:<Button disabled={busy||!form.authorityReference.trim()} onClick={()=>void save(true)}>Submit to Finance</Button>}</div></footer>
 </div></div>;
}

function ImportDrawer({context,onClose,onSaved}:{context:DebtContext;onClose:()=>void;onSaved:()=>void}){
 const [rows,setRows]=useState<Record<string,string>[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 function read(file:File){void file.text().then(text=>{const [head,...lines]=text.trim().split(/\r?\n/);const headers=head.split(',').map(x=>x.trim());setRows(lines.filter(Boolean).map(line=>Object.fromEntries(line.split(',').map((value,index)=>[headers[index],value.trim()]))));}).catch(c=>setError((c as Error).message));}
 async function save(){setBusy(true);setError('');try{for(const row of rows){const employee=context.employees.find(e=>e.code===row.employee_id);if(!employee)throw new Error(`Employee ${row.employee_id||'is missing'} is not in this payroll scope.`);await createDebtRecord({id:crypto.randomUUID(),employeeId:employee.id,kind:(row.type||'existing_loan') as AddMode,source:row.name,originalAmount:row.original_amount,openingBalance:row.current_balance,amountPaid:row.amount_paid,installmentsPaid:Number(row.installments_paid||0),deductionBasis:(row.repayment_option||'remaining_cutoffs') as CreateDebtRecord['deductionBasis'],installment:row.deduction_amount,term:Number(row.remaining_term||1),firstDate:row.release_date,issuedOn:row.original_date,authorityReference:row.authority_reference,signedOn:row.signed_date,notes:row.notes||''});}onSaved();onClose();}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><Card className="w-full max-w-2xl" title="Import existing records"><p className="text-sm text-slate-500">Imports create drafts. Add authority evidence and submit each record to Finance after review.</p>{error?<p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>:null}<label className="mt-4 block">CSV file<input className={control} type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)read(file);}}/></label><p className="mt-3 text-xs text-slate-500">Columns: employee_id, type, name, original_amount, current_balance, amount_paid, installments_paid, repayment_option, deduction_amount, remaining_term, release_date, original_date, authority_reference, signed_date, notes</p><p className="mt-3 font-semibold">{rows.length} records ready to import as drafts</p><footer className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={busy||rows.length===0} onClick={()=>void save()}>Import drafts</Button></footer></Card></div>;
}

function DocumentList({debt,canApprove,onChanged}:{debt:PayrollDebt;canApprove:boolean;onChanged:()=>void}){
 const [comments,setComments]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function review(doc:DebtDocument,status:DebtDocument['status']){setBusy(true);setError('');try{await reviewDebtDocument(doc.id,status,comments||`${status} by Finance reviewer`);onChanged();}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
 return <section className="mt-5"><h3 className="text-lg font-bold">Authority documents</h3>{error?<p className="mt-2 text-red-700">{error}</p>:null}<div className="mt-2 space-y-2">{debt.documents.length===0?<p className="rounded-xl bg-red-50 p-3 text-red-800">Missing — supporting authority is required.</p>:debt.documents.map(doc=><div className="rounded-xl border p-3" key={doc.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><strong>{doc.file_name||doc.document_title}</strong> {doc.is_primary?<span className="text-xs text-violet-700">· Primary</span>:null}<p className="text-xs text-slate-500">{doc.source_type} · {doc.link_provider||'Secured upload'} · added by {doc.addedBy}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${doc.status==='Accepted'?'bg-emerald-100 text-emerald-800':doc.status.includes('Rejected')||doc.status==='Link unavailable'?'bg-red-100 text-red-800':'bg-amber-100 text-amber-900'}`}>{doc.status}</span></div><div className="mt-2 flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={()=>{try{doc.source_type==='Upload'?void openDebtDocument(doc.storage_path!):openDebtLink(doc.secure_url!);}catch(cause){setError((cause as Error).message);}}}>{doc.source_type==='Upload'?'View or download':'Open document'}</Button>{canApprove?<><Button size="sm" disabled={busy} onClick={()=>void review(doc,'Accepted')}>Accept</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void review(doc,doc.source_type==='Link'?'Link unavailable':'Rejected')}>{doc.source_type==='Link'?'Link unavailable':'Reject'}</Button></>:null}</div></div>)}</div>{canApprove?<label className="mt-3 block">Document review comments<textarea className={control} rows={2} value={comments} onChange={e=>setComments(e.target.value)}/></label>:null}</section>;
}

function DetailDrawer({debt,context,onClose,onChanged}:{debt:PayrollDebt;context:DebtContext;onClose:()=>void;onChanged:()=>void}){
 const [reason,setReason]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [file,setFile]=useState<File|null>(null);const [link,setLink]=useState({title:'',url:'',provider:'Google Drive'});
 async function run(action:string){setBusy(true);setError('');try{await actDebt(debt.id,action,reason||`${action} by authorized reviewer`);onChanged();if(action!=='request_document')onClose();}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
 async function addEvidence(){setBusy(true);setError('');try{if(file)await uploadDebtDocument(debt.id,file);if(link.url)await addDebtDocumentLink(debt.id,link.title,link.url,link.provider,debt.signed_on||today(),!file);onChanged();setFile(null);setLink({title:'',url:'',provider:'Google Drive'});}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
 const editable=['Draft','Returned for correction'].includes(debt.status);
 return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40" role="dialog" aria-modal="true"><div className="h-full w-full max-w-3xl overflow-y-auto bg-white p-6 shadow-2xl dark:bg-slate-900"><header className="flex justify-between gap-3"><div><p className="text-sm font-semibold text-violet-700">{debt.record_number}</p><h2 className="text-2xl font-bold">{debt.employeeName}</h2><p>{debt.businessUnit} · {kindLabel[debt.debt_kind]}</p></div><button className="min-h-11 px-3 text-2xl" onClick={onClose} aria-label="Close">×</button></header>{error?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-800">{error}</p>:null}{debt.returned_reason?<p className="mt-4 rounded-xl bg-orange-50 p-4 text-orange-900"><strong>Correction required:</strong> {debt.returned_reason}</p>:null}
 <div className="mt-5 grid gap-3 sm:grid-cols-4">{[['Original',peso(debt.original_amount)],['Current balance',peso(debt.current_balance)],['Per cutoff',peso(Math.min(Number(debt.installment),Number(debt.current_balance)))],['Remaining',`${debt.remainingCutoffs} cutoffs`]].map(([label,value])=><div className="rounded-xl bg-slate-50 p-3" key={label}><p className="text-xs text-slate-500">{label}</p><strong>{value}</strong></div>)}</div>
 <section className="mt-5 rounded-2xl border p-4"><div className="flex justify-between gap-2"><h3 className="font-bold">{debt.debt_source}</h3><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusColor[debt.status]||'bg-slate-100'}`}>{debt.status}</span></div><dl className="mt-3 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Deduction start</dt><dd>{formatPayrollDate(debt.first_deduction_date)}</dd></div><div><dt className="text-xs text-slate-500">Projected payoff</dt><dd>{formatPayrollDate(debt.expected_final_date)}</dd></div><div><dt className="text-xs text-slate-500">Authority reference</dt><dd>{debt.authority_reference||'Missing'}</dd></div><div><dt className="text-xs text-slate-500">Finance route</dt><dd>{context.financeReviewer}</dd></div></dl></section>
 <DocumentList debt={debt} canApprove={context.canApprove&&debt.status==='Pending Finance approval'} onChanged={onChanged}/>
 {editable&&context.canManage?<section className="mt-5 rounded-2xl border p-4"><h3 className="font-bold">Add or replace evidence</h3><DocumentInputs file={file} setFile={setFile} link={link} setLink={setLink}/><Button className="mt-3" disabled={busy||(!file&&!link.url)} onClick={()=>void addEvidence()}>Save evidence</Button></section>:null}
 <section className="mt-5"><h3 className="font-bold">Repayment schedule</h3><div className="mt-2 max-h-52 overflow-auto rounded-xl border"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Payroll</th><th className="p-2">Deduction</th><th className="p-2">Balance after</th><th className="p-2">Status</th></tr></thead><tbody>{debt.schedule.map(row=><tr className="border-t" key={row.id}><td className="p-2">{row.payroll_date}</td><td className="p-2">{peso(Math.min(Number(row.scheduled_amount),Number(debt.current_balance)))}</td><td className="p-2">{peso(row.balance_after)}</td><td className="p-2">{row.status}</td></tr>)}</tbody></table></div></section>
 <section className="mt-5"><h3 className="font-bold">Audit trail</h3><div className="mt-2 max-h-44 space-y-2 overflow-auto">{debt.audit.map((item,index)=><div className="rounded-xl bg-slate-50 p-3 text-sm" key={`${item.at}-${index}`}><strong>{item.action}</strong> · {item.actor}<p>{item.reason}</p><time className="text-xs text-slate-500">{new Date(item.at).toLocaleString('en-PH')}</time></div>)}</div></section>
 {editable||context.canApprove&&debt.status==='Pending Finance approval'?<footer className="sticky bottom-0 mt-6 rounded-2xl border bg-white p-4"><label>Comments / exact correction required<textarea className={control} rows={2} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="mt-3 flex flex-wrap gap-2">{editable?<Button disabled={busy||debt.documents.length===0} onClick={()=>void run('submit')}>Resubmit same record</Button>:null}{context.canApprove&&debt.status==='Pending Finance approval'?<><Button disabled={busy||!debt.documents.some(d=>d.status==='Accepted')} onClick={()=>void run('approve')}>Approve and activate</Button><Button variant="secondary" disabled={busy||reason.trim().length<3} onClick={()=>void run('return')}>Return for correction</Button><Button variant="secondary" disabled={busy||reason.trim().length<3} onClick={()=>void run('request_document')}>Request another document</Button><Button variant="secondary" disabled={busy||reason.trim().length<3} onClick={()=>void run('reject')}>Reject</Button></>:null}</div></footer>:null}
 </div></div>;
}

export default function Loans(){
 const [scope]=usePayrollField('scope');const [data,setData]=useState<DebtContext|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [mode,setMode]=useState<AddMode|null>(null);const [importing,setImporting]=useState(false);const [selected,setSelected]=useState<PayrollDebt|null>(null);const [refresh,setRefresh]=useState(0);const [tab,setTab]=useState<Tab>('Active');
 useEffect(()=>{let mounted=true;setBusy(true);setError('');void getDebtContext(scope||null).then(result=>{if(mounted)setData(result);}).catch(cause=>{if(mounted)setError((cause as Error).message);}).finally(()=>{if(mounted)setBusy(false);});return()=>{mounted=false;};},[scope,refresh]);
 const debts=data?.debts||[];const filtered=useMemo(()=>debts.filter(d=>statusGroup(d,tab)),[debts,tab]);const active=debts.filter(d=>d.status==='Active');const next=active.reduce((sum,d)=>sum+Math.min(Number(d.installment),Number(d.current_balance)),0);const tabs:Tab[]=['Active','Pending Finance approval','Needs correction','Paid or closed','Authorized NTE deductions'];
 const reload=()=>setRefresh(value=>value+1);
 return <div className="space-y-6"><header><p className="font-semibold text-violet-700">Payroll workspace</p><h1 className="text-3xl font-bold">Loans & Debt</h1><p className="mt-1 text-slate-600 dark:text-slate-300">Record opening balances and signed deduction authorities, route them to Finance, and activate only approved payroll deductions.</p></header>{error?<p role="alert" className="rounded-xl border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>:null}{busy&&!data?<p role="status">Loading secured loan records…</p>:data?<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Total active loans',active.length],['Deductions in next payroll',peso(next)],['Employees with debt',new Set(debts.filter(d=>!['Paid or closed','Completed','Cancelled'].includes(d.status)).map(d=>d.employee_id)).size],['Pending Finance approval',debts.filter(d=>d.status==='Pending Finance approval').length]].map(([label,value])=><Card key={String(label)}><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-3xl">{value}</strong></Card>)}</div>
 {data.routingError?<p className="rounded-xl border border-red-300 bg-red-50 p-3 text-red-800">{data.routingError}</p>:null}{data.canManage?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Button onClick={()=>setMode('existing_loan')}>Add loan or debt</Button><Button variant="secondary" onClick={()=>setMode('previous_debt')}>Add previous loan</Button><Button variant="secondary" onClick={()=>setMode('external_nte_deduction')}>Add authorized NTE deduction</Button><Button variant="secondary" onClick={()=>setImporting(true)}>Import existing records</Button></div>:null}
 <Card><div className="flex gap-2 overflow-x-auto border-b pb-3">{tabs.map(name=><button key={name} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${tab===name?'bg-violet-600 text-white':'bg-slate-100 text-slate-700'}`} onClick={()=>setTab(name)}>{name}<span className="ml-2 rounded-full bg-white/70 px-2 text-slate-800">{debts.filter(d=>statusGroup(d,name)).length}</span></button>)}</div>{filtered.length===0?<div className="py-12 text-center"><p className="text-lg font-semibold">No records in {tab.toLowerCase()}</p><p className="text-sm text-slate-500">Use an action above to record an existing balance or signed deduction authority.</p></div>:<div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead><tr>{['Employee','Business unit','Type','Original amount','Current balance','Per cutoff','Remaining','Next deduction','Authority','Finance status','Action'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(debt=><tr className="border-t" key={debt.id}><td className="p-3 font-semibold">{debt.employeeName}<span className="block text-xs font-normal text-slate-500">{debt.employeeCode} · {debt.record_number}</span></td><td className="p-3">{debt.businessUnit}</td><td className="p-3">{kindLabel[debt.debt_kind]}</td><td className="p-3">{peso(debt.original_amount)}</td><td className="p-3 font-bold">{peso(debt.current_balance)}</td><td className="p-3">{peso(Math.min(Number(debt.installment),Number(debt.current_balance)))}</td><td className="p-3">{debt.remainingCutoffs}</td><td className="p-3">{debt.nextDeductionDate?formatPayrollDate(debt.nextDeductionDate):'—'}</td><td className="p-3">{documentStatus(debt)}</td><td className="p-3"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusColor[debt.status]||'bg-slate-100'}`}>{debt.status}</span></td><td className="p-3"><Button size="sm" variant="secondary" onClick={()=>setSelected(debt)}>View</Button></td></tr>)}</tbody></table></div>}</Card>
 </>:null}{mode&&data?<AddDrawer mode={mode} context={data} onClose={()=>setMode(null)} onSaved={reload}/>:null}{importing&&data?<ImportDrawer context={data} onClose={()=>setImporting(false)} onSaved={reload}/>:null}{selected&&data?<DetailDrawer debt={selected} context={data} onClose={()=>setSelected(null)} onChanged={reload}/>:null}</div>;
}
