import {useAuth} from '../../hooks/useAuth';
import {useSearchParams} from 'react-router-dom';
import React,{useEffect,useState} from 'react';
import {channelRpc} from '../../services/attendanceChannels';
import AttendanceCorrection from '../../components/attendance/AttendanceCorrection';
export default function MissedPunches(){const {user}=useAuth();const [params]=useSearchParams();const [rows,setRows]=useState<any[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [selected,setSelected]=useState('');const [notes,setNotes]=useState<Record<string,string>>({});const load=async()=>{try{setRows(await channelRpc<any[]>('get_missed_punches'));}catch(e){setError((e as Error).message);}};useEffect(()=>{void load();},[]);
 const visible=rows.filter(r=>!params.has('own')||r.employee_id===user?.id);
 const run=async(fn:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="space-y-5"><h1 className="text-3xl font-bold">Missed punches & approvals</h1><p>Employees submit actual times. The direct manager reviews them, then HR applies approved changes through the existing attendance correction process.</p>{error&&<p role="alert" className="text-red-600">{error}</p>}{!visible.length&&<p>No requests to show.</p>}{visible.map(r=><section key={r.id} className="rounded-2xl border bg-white p-5 dark:bg-slate-800 dark:border-slate-700"><h2 className="font-bold">{r.employeeName} · {r.work_date}</h2><p>{r.action.replaceAll('_',' ')} · {new Date(r.actual_time).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}{r.break_end&&` → ${new Date(r.break_end).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}`}</p><p className="my-2">{r.reason}</p><strong>{r.status==='approved'?'Manager approved · awaiting HR application':r.status}</strong>{r.canApprove&&<div className="mt-3 space-y-3"><label className="block">Review note<input className="ml-2 min-h-12 rounded border bg-transparent p-2" value={notes[r.id]??''} onChange={e=>setNotes({...notes,[r.id]:e.target.value})}/></label>{[true,false].map(approve=><button key={String(approve)} disabled={busy||(notes[r.id]??'').trim().length<3} className="mr-3 min-h-12 rounded-lg border px-5 disabled:opacity-50" onClick={()=>void run(()=>channelRpc('review_missed_punch',{p_id:r.id,p_approve:approve,p_note:notes[r.id]}))}>{approve?'Approve for HR correction':'Reject'}</button>)}</div>}{r.canApply&&<div className="mt-3"><button className="min-h-12 rounded-lg border px-4" onClick={()=>setSelected(selected===r.id?'':r.id)}>Review and apply approved times</button>{selected===r.id&&<><AttendanceCorrection employee={r.employee_id} date={r.work_date} proposed={[{type:r.action,timestamp:r.actual_time},...(r.break_end?[{type:'END_BREAK',timestamp:r.break_end}]:[])]} onSaved={()=>void run(()=>channelRpc('complete_missed_punch',{p_id:r.id}))}/><button disabled={busy} className="min-h-11 underline" onClick={()=>void run(()=>channelRpc('complete_missed_punch',{p_id:r.id}))}>Link an already-saved HR correction</button></>}</div>}<details className="mt-3"><summary>Request audit</summary>{r.audit.map((a:any)=><p key={a.id} className="mt-2 text-sm">{a.action} · {new Date(a.created_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})} · {a.note}</p>)}</details></section>)}</div>;
}
