import React,{useCallback,useEffect,useRef,useState} from 'react';
import {Action,actions,labels,capture,enqueue,queued,removeQueued,stationRpc,StationRejection} from '../../services/punchStation';
import './punchStation.css';
type Mode='standby'|'employee'|'pin'|'action'|'supervisor'|'busy'|'result'|'error';
export default function PunchStation(){
 const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const lock=useRef(false);const syncLock=useRef(false);
 const [token,setToken]=useState(()=>localStorage.getItem('punch-device')||'');const [pair,setPair]=useState('');
 const [device,setDevice]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem('punch-device-info')||'null');}catch{return null;}});
 const [offlineReady,setOfflineReady]=useState(false);
 const [online,setOnline]=useState(false);const [clock,setClock]=useState(new Date());const [mode,setMode]=useState<Mode>('standby');const [message,setMessage]=useState('');const [camera,setCamera]=useState(false);const [pending,setPending]=useState(0);
 const [employee,setEmployee]=useState('');const [pin,setPin]=useState('');const [supervisor,setSupervisor]=useState(false);const [auth,setAuth]=useState<any>(null);const [badge,setBadge]=useState('');const [alpha,setAlpha]=useState(false);
 const reset=useCallback(()=>{setMode('standby');setEmployee('');setPin('');setAuth(null);setBadge('');setSupervisor(false);setMessage('');lock.current=false;},[]);
 const startCamera=useCallback(async()=>{try{stream.current?.getTracks().forEach(t=>t.stop());const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:640,height:480},audio:false});stream.current=media;media.getVideoTracks()[0].onended=()=>setCamera(false);if(video.current){video.current.srcObject=media;await video.current.play();}setCamera(true);}catch{setCamera(false);}},[]);
 const health=useCallback(async()=>{if(!token)return;try{const d=await stationRpc('punch_station_status',{p_device_token:token});setDevice(d);localStorage.setItem('punch-device-info',JSON.stringify(d));setOnline(true);}catch{setOnline(false);}},[token]);
 useEffect(()=>{void startCamera();const timer=setInterval(()=>setClock(new Date()),1000);return()=>{clearInterval(timer);stream.current?.getTracks().forEach(t=>t.stop());};},[startCamera]);
 useEffect(()=>{void health();const timer=setInterval(health,15000);window.addEventListener('online',health);const off=()=>setOnline(false);window.addEventListener('offline',off);return()=>{clearInterval(timer);window.removeEventListener('online',health);window.removeEventListener('offline',off);};},[health]);
 useEffect(()=>{if(mode==='busy'||mode==='standby')return;const timer=setTimeout(reset,mode==='result'||mode==='error'?3000:60000);return()=>clearTimeout(timer);},[mode,employee,pin,reset]);
 useEffect(()=>{navigator.serviceWorker?.register('/punch-station/sw.js',{scope:'/punch-station/'}).then(async()=>{const r=await navigator.serviceWorker.ready;const channel=new MessageChannel();channel.port1.onmessage=e=>setOfflineReady(e.data===true);r.active?.postMessage({type:'PREPARE',urls:performance.getEntriesByType('resource').map(e=>e.name).filter(u=>u.startsWith(location.origin+'/assets/')&&/\.(js|css)$/.test(u))},[channel.port2]);}).catch(()=>{});void queued().then(r=>setPending(r.length)).catch(()=>setMessage('Local storage unavailable. Contact your supervisor.'));},[]);
 const sync=useCallback(async()=>{if(!online||syncLock.current||lock.current)return;syncLock.current=true;try{for(const row of await queued()){const {localDeviceId,...payload}=row.payload;if(localDeviceId!==device?.deviceId)throw new Error('Pending captures belong to another device');await stationRpc('punch_station_submit',{...payload,p_device_token:token});await removeQueued(row.id);}setPending((await queued()).length);}catch{/* Keep evidence intact, including uncertain online submissions. */}finally{syncLock.current=false;}},[online,token,device?.deviceId]);
 useEffect(()=>{void sync();const timer=setInterval(sync,15000);return()=>clearInterval(timer);},[sync]);
 const identify=useCallback(async(card?:string)=>{if(lock.current)return;lock.current=true;setMode('busy');try{
 if(!camera&&!supervisor)throw new Error('Camera access is required to complete this punch.');
 if(!online){if(!offlineReady||!card||!device||Date.parse(device.expiresAt)<=Date.now())throw new Error('Offline badge capture requires a previously authorized device. Contact your supervisor.');setBadge(card);setAuth(null);setMode('action');return;}
 const a=await stationRpc('punch_station_auth',{p_device_token:token,p_badge:card||null,p_employee_code:card?null:employee,p_pin:card?null:pin,p_supervisor:supervisor});setPin('');setAuth(a);setBadge(card||'');setMode(a.supervisor?'supervisor':'action');
 }catch(e){setMessage((e as Error).message);setMode('error');}finally{lock.current=false;}},[camera,online,offlineReady,device,token,employee,pin,supervisor]);
 useEffect(()=>{if(mode!=='standby'||!token)return;let buffer='';let last=0;const onKey=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement)return;if(Date.now()-last>1000)buffer='';last=Date.now();if(e.key==='Enter'){e.preventDefault();const code=buffer;buffer='';if(/^[A-Za-z0-9_-]{8,128}$/.test(code))void identify(code);}else if(/^[A-Za-z0-9_-]$/.test(e.key)){buffer=(buffer+e.key).slice(-128);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[mode,token,identify]);
 const punch=async(action:Action)=>{if(lock.current||syncLock.current)return;lock.current=true;setMode('busy');setMessage('Look at the camera. Your photo will be recorded for HR audit.');try{
 await new Promise(r=>setTimeout(r,600));const photo=await capture(video.current!);setMessage('Photo captured. Saving attendance…');const id=crypto.randomUUID();const payload={p_id:id,p_ticket:auth?.ticket||null,p_action:action,p_photo:photo,p_captured_at:new Date().toISOString(),p_offline_badge:auth?null:badge};
 await enqueue(id,{...payload,localDeviceId:device?.deviceId});setPending((await queued()).length);
 if(auth){try{const saved=await stationRpc('punch_station_submit',{...payload,p_device_token:token});await removeQueued(id);if(saved.status!=='Accepted')setMessage('Captured and synced. Pending HR verification.');else setMessage(`${labels[action]} saved at ${new Date(saved.timestamp).toLocaleTimeString('en-PH',{timeZone:'Asia/Manila'})}. Your photo has been recorded for HR audit.`);}catch(e){if(e instanceof StationRejection){await removeQueued(id);throw e;}setMessage('Captured on this tablet. Save not confirmed — pending sync and verification. Do not punch again.');}}
 else setMessage('Captured on this tablet. Pending sync and HR verification. Do not punch again.');
 setPending((await queued()).length);setMode('result');
 }catch(e){setMessage((e as Error).message);setMode('error');}finally{lock.current=false;}};
 const supervisorAction=async(action:string,fn:()=>unknown)=>{try{await stationRpc('punch_station_supervisor_action',{p_device_token:token,p_ticket:auth?.ticket,p_action:action});await fn();}catch(e){setMessage((e as Error).message);setMode('error');}};
 const key=(value:string)=>{if(value==='Enter'){if(mode==='employee'){setMode('pin');setAlpha(false);}else void identify();return;}const setter=mode==='employee'?setEmployee:setPin;setter(v=>value==='Clear'?'':value==='⌫'?v.slice(0,-1):(v+value).slice(0,mode==='employee'?40:supervisor?12:4));};
 return <main className="punch-station"><header><div><strong>Punch Station</strong><small>{device?.name||'TNG HRIS'}</small></div><div className={online?'ps-online':'ps-offline'}>{online?'● System Online':'● Offline / connection unverified'}<small>{pending} capture(s) pending sync · {offlineReady?'Offline prepared':'Preparing offline mode'}</small></div><div><strong>{clock.toLocaleTimeString('en-PH',{timeZone:'Asia/Manila'})}</strong><small>{clock.toLocaleDateString('en-PH',{timeZone:'Asia/Manila',weekday:'long',month:'short',day:'numeric'})}</small></div></header>
 <section className="ps-body"><div className="ps-camera"><video ref={video} autoPlay muted playsInline/><div className="ps-frame"/><p>{camera?'Your punch includes one audit photo':'Camera access is required to complete this punch.'}</p>{!camera&&<button onClick={startCamera}>Enable camera</button>}</div><div className="ps-controls">
 {!token?<><h1>Set up this tablet</h1><p>Authorized HR: create a pairing in Attendance Devices → Punch Station.</p><input aria-label="Device pairing token" type="password" value={pair} onChange={e=>setPair(e.target.value)} autoComplete="off"/><button onClick={async()=>{try{await stationRpc('punch_station_status',{p_device_token:pair});localStorage.setItem('punch-device',pair);setToken(pair);setPair('');}catch(e){setMessage((e as Error).message);}}}>Connect Punch Station</button><p>{message}</p></>:
 mode==='standby'?<><h1>Tap your employee badge to begin</h1><p>Hold your badge against the connected reader.</p>{!online&&<p className="ps-warning">Offline captures require sync and HR verification. PIN fallback is unavailable.</p>}<button disabled={!online} onClick={()=>{setSupervisor(false);setMode('employee');}}>Forgot your badge?</button><button className="ps-secondary" disabled={!online} onClick={()=>{setSupervisor(true);setMode('employee');}}>Supervisor access</button><button className="ps-secondary" onClick={()=>{setToken('');setOnline(false);}}>Enter HR device pairing</button></>:
 mode==='employee'||mode==='pin'?<><h2>{supervisor?'Supervisor access':'Employee verification'}</h2><p>{mode==='employee'?'Enter employee ID':supervisor?'Enter separate 8–12 digit supervisor PIN':'Enter your personal 4-digit PIN'}</p><output>{mode==='employee'?employee||'Employee ID':'●'.repeat(pin.length)||'PIN'}</output><div className={'ps-keypad '+(alpha?'ps-alpha':'')}>{(alpha?'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''):['1','2','3','4','5','6','7','8','9','Clear','0','⌫']).map(k=><button key={k} onClick={()=>key(k)}>{k}</button>)}</div>{mode==='employee'&&<button className="ps-secondary" onClick={()=>setAlpha(!alpha)}>{alpha?'123':'ABC'}</button>}<button disabled={mode==='employee'?!employee:supervisor?pin.length<8:pin.length!==4} onClick={()=>key('Enter')}>Enter</button><button className="ps-secondary" onClick={reset}>Cancel</button></>:
 mode==='action'?<><h1>{auth?`Hello, ${auth.name}`:'Offline badge capture'}</h1><p>{auth?'Choose your attendance action':'Select the actual action. HR will verify this capture after sync.'}</p>{(auth?(auth.requiresClock?actions(auth.state):[]):Object.keys(labels) as Action[]).map(a=><button key={a} onClick={()=>punch(a)} disabled={!camera}>{labels[a]}</button>)}{auth&&(!auth.requiresClock||!actions(auth.state).length)&&<p>No clock action is required. Contact your supervisor if this is unexpected.</p>}<button className="ps-secondary" onClick={reset}>Cancel</button></>:
 mode==='supervisor'?<><h1>Supervisor access active</h1><p>Camera: {camera?'Ready':'Unavailable'} · Connection: {online?'Online':'Unavailable'}</p><p>For corrections or employee information, use your authorized HRIS account on your own device.</p><button onClick={()=>supervisorAction("Camera test",startCamera)}>Camera test</button><button onClick={()=>supervisorAction("Reconnect kiosk",health)}>Reconnect kiosk</button><button onClick={()=>supervisorAction("Exit supervisor mode",reset)}>Exit supervisor mode</button></>:
 <div role={mode==='error'?'alert':'status'} aria-live="polite"><h1>{mode==='busy'?'Please wait…':mode==='error'?'Punch not completed':message.startsWith('Captured')?'Pending confirmation':'Saved'}</h1><p>{message}</p></div>}
 </div></section><footer>Every punch includes a photo for attendance verification and HR audit. Photos are visible only to authorized HR/Admin. No continuous video is recorded.<br/>If the tablet or camera fails, contact your supervisor for the manual attendance log.</footer></main>;
}
