import {supabase} from '../../services/supabaseClient';
export const statuses=['Draft','Pending Approval','Approved','Rejected','Cancelled','Completed','For Review'];
export type OBRequest={id:string;reference:string;employee_id:string;employeeName:string;headName:string;status:string;approval_step:string;revision:number;work_date:string;starts_at:string;ends_at:string;destination:string;latitude:number;longitude:number;radius_metres:number;purpose:string;client_event:string;travel_minutes:number;override_schedule:boolean;supporting_required:boolean;documents:{name:string;path:string}[];last_reason:string;approved_at:string;canHead:boolean;canHr:boolean;canHrApprove:boolean;history:{id:string;action:string;reason:string;actor:string;at:string;status:string;revision:number}[];punches:{id:string;action:string;attempted_at:string;recorded:boolean;latitude:number;longitude:number;accuracy:number;selfie_path:string;reason:string}[]};
export async function obRpc<T=any>(name:string,args:Record<string,unknown>={}):Promise<T>{const c=new AbortController();const t=setTimeout(()=>c.abort(),20000);try{const {data,error}=await supabase.rpc(name,args).abortSignal(c.signal);if(error)throw new Error(c.signal.aborted?'The request timed out. Refresh to confirm whether it was saved before retrying.':error.message);return data as T;}finally{clearTimeout(t);}}
export const listOB=(queue='own',status='',id:string|null=null)=>obRpc<{rows:OBRequest[];headAssigned:boolean;limit:number}>('get_official_business',{p_queue:queue,p_status:status,p_id:id});
export const obAction=(id:string,action:string,revision:number,data:Record<string,unknown>={},reason='')=>obRpc<string>('act_on_official_business',{p_id:id,p_action:action,p_revision:revision,p_data:data,p_reason:reason});
export const phTime=(s:string)=>s?new Date(s).toLocaleString('en-PH',{timeZone:'Asia/Manila',dateStyle:'medium',timeStyle:'short'}):'Not set';
export function validateOBFile(f:File,selfie=false){if(f.size>5*1024*1024)throw new Error('Use a file no larger than 5 MB.');if(!(selfie?['image/jpeg','image/png','image/webp']:['application/pdf','image/jpeg','image/png','image/webp']).includes(f.type))throw new Error(selfie?'Use a JPG, PNG or WebP selfie.':'Use a PDF, JPG, PNG or WebP document.');}
export async function uploadOBFile(user:string,id:string,file:File,selfie=false){validateOBFile(file,selfie);const path=`${user}/${id}/${selfie?'selfies':'documents'}/${crypto.randomUUID()}/${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;let timer:ReturnType<typeof setTimeout>;try{const {error}=await Promise.race([supabase.storage.from('official-business').upload(path,file,{contentType:file.type,upsert:false}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('Upload timed out. No request or punch was submitted; retry with a fresh file.')),20000);})]);if(error)throw error;return path;}finally{clearTimeout(timer);}}
export async function openOBFile(path:string){const tab=window.open('','_blank');if(tab)tab.opener=null;try{const {data,error}=await supabase.storage.from('official-business').createSignedUrl(path,60);if(error)throw error;if(tab)tab.location.href=data.signedUrl;else throw new Error('Allow pop-ups to open the secured attachment.');}catch(e){tab?.close();throw e;}}
export const obChanged=()=>{window.dispatchEvent(new Event('official-business-changed'));window.dispatchEvent(new Event('attendance-updated'));};
