import React,{useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {useAuth} from '../../hooks/useAuth';
import {OBRequest,listOB,obAction,obChanged,openOBFile,phTime,statuses,uploadOBFile} from './api';
const control='w-full rounded-lg border border-gray-300 bg-white p-2 dark:border-slate-600 dark:bg-slate-800';
const button='min-h-11 rounded-lg border border-gray-300 px-4 py-2 text-sm disabled:opacity-40 dark:border-slate-600';
const box='rounded-xl border border-gray-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800';
const empty={work_date:'',starts_at:'',ends_at:'',destination:'',latitude:'',longitude:'',radius_metres:100,purpose:'',client_event:'',travel_minutes:0,override_schedule:false,supporting_required:false,documents:[] as {name:string;path:string}[]};
const localTime=(value:string)=>value?new Date(Date.parse(value)+8*3600000).toISOString().slice(0,16):'';
const fromRow=(r:OBRequest)=>({...empty,...Object.fromEntries(Object.keys(empty).map(k=>[k,r[k]??empty[k]])),starts_at:localTime(r.starts_at),ends_at:localTime(r.ends_at)}) as typeof empty;
const payload=(f:typeof empty)=>({...f,starts_at:f.starts_at?f.starts_at+':00+08:00':null,ends_at:f.ends_at?f.ends_at+':00+08:00':null,latitude:f.latitude===''?null:Number(f.latitude),longitude:f.longitude===''?null:Number(f.longitude)});
export default function OfficialBusinessPage(){
 const {user}=useAuth();const [params,setParams]=useSearchParams();const id=params.get('request');
 const [queue,setQueue]=useState(params.get('queue')||'own'),[status,setStatus]=useState(''),[rows,setRows]=useState<OBRequest[]>([]),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [form,setForm]=useState(empty),[reason,setReason]=useState(''),[amending,setAmending]=useState(false),[headAssigned,setHeadAssigned]=useState(true);const lock=useRef(false),owner=useRef(user?.id);owner.current=user?.id;
 const selected=id?rows.find(r=>r.id===id):null;
 useEffect(()=>{let active=true;setLoading(true);setRows([]);setError('');listOB(id?'all':queue,id?'':status,id).then(d=>{if(active){setRows(d.rows);setHeadAssigned(d.headAssigned);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[user?.id,id,queue,status,revision]);
 useEffect(()=>{setForm(selected?fromRow(selected):empty);setReason('');setAmending(false);},[selected?.id,selected?.revision]);
 const update=(k:string,v:unknown)=>setForm(f=>({...f,[k]:v}));
 const run=async(fn:()=>Promise<unknown>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');const actor=user?.id;try{await fn();if(owner.current===actor){obChanged();setRevision(n=>n+1);}}catch(e:any){if(owner.current===actor)setError(e.message||'Request failed. Refresh before retrying.');}finally{lock.current=false;if(owner.current===actor)setBusy(false);}};
 const save=async(submit=false)=>{if(!selected)return;await obAction(selected.id,amending?'amend':'save',selected.revision,payload(form),reason);if(submit&&!amending){const fresh=(await listOB('all','',selected.id)).rows[0];if(!fresh)throw new Error('Saved request unavailable. Refresh.');await obAction(fresh.id,'submit',fresh.revision);}setNotice(amending?'Amendment recorded. Immediate Head and HR must approve the revised details.':submit?'Submitted to your Immediate Head.':'Draft saved.');};
 const decide=(action:string)=>run(async()=>{await obAction(selected!.id,action,selected!.revision,{},reason);setNotice('Action recorded with its approval history.');});
 const editable=!!selected&&((selected.employee_id===user?.id&&selected.status==='Draft')||amending);
 return <div className="space-y-5 text-gray-900 dark:text-gray-100">
  <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Official Business (OB)</h1><p className="text-sm text-gray-500">Work, meetings and travel away from your regular workplace.</p></div><div className="flex gap-2"><Link className={button} to="/dashboard">Dashboard</Link><Link className={button} to="/approvals">Approval Center</Link><button className={button+' bg-indigo-600 text-white'} disabled={busy} onClick={()=>run(async()=>{const key=crypto.randomUUID();await obAction(key,'save',0,payload(empty));setParams({request:key});})}>New OB request</button></div></div>
  <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950 dark:text-amber-100">Approval authorizes only the stated schedule and location exception. It does not authorize overtime, holiday pay, rest-day pay or travel allowance. Record actual punches with GPS and a selfie.</p>
  {error&&<div role="alert" className={box}>{error} <button className={button} onClick={()=>setRevision(n=>n+1)}>Refresh</button></div>}{notice&&<p role="status" className={box}>{notice}</p>}
  {!id&&<div className="flex flex-wrap gap-3"><label>Requests<select className={control} value={queue} onChange={e=>setQueue(e.target.value)}><option value="own">My requests</option><option value="approvals">Awaiting my approval</option><option value="all">All authorized requests</option></select></label><label>Status<select className={control} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div>}
  {loading?<p role="status">Loading OB requests…</p>:id&&!selected?<p>Request unavailable in your current access scope. <button className={button} onClick={()=>setParams({})}>Back to requests</button></p>:selected?<>
   <button className={button} onClick={()=>setParams({})}>← Back to requests</button>
   <div className={box}><h2 className="text-xl font-semibold">{selected.reference} · {selected.employeeName}</h2><p>{selected.status}{selected.approval_step!=='none'?` · Awaiting ${selected.approval_step==='head'?'Immediate Head':'HR'}`:''}</p><p className="text-sm">Immediate Head: {selected.headName||'Not assigned'} · Version {selected.revision}</p>{selected.last_reason&&<p className="mt-2">Last reason: {selected.last_reason}</p>}</div>
   <form noValidate className={box+' space-y-4'} onSubmit={e=>{e.preventDefault();void run(()=>save(false));}}><fieldset disabled={!editable||busy} className="grid gap-4 md:grid-cols-2">
    <label>OB work date<input required type="date" className={control} value={form.work_date||''} onChange={e=>update('work_date',e.target.value)}/></label>
    <label>Destination / location<input className={control} required value={form.destination||''} onChange={e=>update('destination',e.target.value)}/></label>
    <label>Start (Philippine time)<input className={control} type="datetime-local" required value={form.starts_at} onChange={e=>update('starts_at',e.target.value)}/></label>
    <label>End (Philippine time)<input className={control} type="datetime-local" required value={form.ends_at} onChange={e=>update('ends_at',e.target.value)}/></label>
    <label>Destination latitude<input className={control} type="number" step="any" min="-90" max="90" required value={form.latitude??''} onChange={e=>update('latitude',e.target.value)}/></label>
    <label>Destination longitude<input className={control} type="number" step="any" min="-180" max="180" required value={form.longitude??''} onChange={e=>update('longitude',e.target.value)}/></label>
    <label>Allowed destination radius (metres)<input className={control} type="number" min="50" max="2000" required value={form.radius_metres} onChange={e=>update('radius_metres',Number(e.target.value))}/></label>
    <label>Expected travel time (minutes, informational)<input className={control} type="number" min="0" max="1440" value={form.travel_minutes} onChange={e=>update('travel_minutes',Number(e.target.value))}/></label>
    <label>Client / event<input className={control} value={form.client_event||''} onChange={e=>update('client_event',e.target.value)}/></label>
    <label>Purpose<textarea className={control} required value={form.purpose||''} onChange={e=>update('purpose',e.target.value)}/></label>
    <label className="flex gap-2"><input type="checkbox" checked={form.override_schedule} onChange={e=>update('override_schedule',e.target.checked)}/>Replace my work schedule with the approved OB start/end</label>
    <label className="flex gap-2"><input type="checkbox" checked={form.supporting_required} onChange={e=>update('supporting_required',e.target.checked)}/>Supporting documents are applicable and required</label>
   </fieldset>
   <p className="text-xs text-gray-500">Use the destination’s map coordinates, not your current location unless you are already there. One destination and one OB window per work date. An overnight window must be shorter than 24 hours. A replacement shift retains the existing unpaid-lunch rule. Clocking before or after the approved window is flagged for HR review.</p>
   {editable&&<button type="button" className={button} disabled={busy} onClick={()=>{if(!navigator.geolocation){setError('Location is unavailable.');return;}navigator.geolocation.getCurrentPosition(p=>{update('latitude',String(p.coords.latitude));update('longitude',String(p.coords.longitude));},()=>setError('Allow location access, or enter the destination coordinates.'),{enableHighAccuracy:true,maximumAge:0,timeout:15000});}}>Use my current location as destination</button>}
   <div><h3 className="font-semibold">Supporting documents</h3>{form.documents.map(d=><div key={d.path} className="flex gap-3"><button type="button" className="min-h-11 underline" onClick={()=>void openOBFile(d.path).catch(e=>setError(e.message))}>{d.name}</button>{editable&&<button type="button" onClick={()=>update('documents',form.documents.filter(x=>x.path!==d.path))}>Remove from request</button>}</div>)}
   {selected.status==='Draft'&&selected.employee_id===user?.id&&<label className="block text-sm">Upload PDF or image (up to 5 MB)<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void run(async()=>{const path=await uploadOBFile(user!.id,selected.id,f);const updated={...form,documents:[...form.documents,{name:f.name,path}]};await obAction(selected.id,'save',selected.revision,payload(updated));});}}/></label>}</div>
   {editable&&<div className="flex flex-wrap gap-2"><button className={button} disabled={busy} type="submit">{amending?'Save amendment & restart approvals':'Save draft'}</button>{!amending&&<button className={button+' bg-indigo-600 text-white'} type="button" disabled={busy} onClick={()=>void run(()=>save(true))}>Submit to Immediate Head</button>}</div>}
   </form>
   {(selected.canHead||selected.canHr)&&<div className={box+' space-y-3'}><h3 className="font-semibold">Review & administration</h3><label className="block">Reason / review notes<textarea className={control} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required for rejection, amendment, cancellation or completion"/></label><div className="flex flex-wrap gap-2">
    {(selected.canHead||selected.canHrApprove)&&<><button className={button+' bg-indigo-600 text-white'} disabled={busy||amending} onClick={()=>decide('approve')}>{selected.canHead?'Approve & send to HR':'Approve OB exception'}</button><button className={button} disabled={busy||!reason.trim()||amending} onClick={()=>decide('reject')}>Reject</button></>}
    {selected.canHr&&!['Cancelled','Completed'].includes(selected.status)&&<><button className={button} disabled={busy} onClick={()=>setAmending(v=>!v)}>{amending?'Cancel editing':'Amend details'}</button><button className={button} disabled={busy||!reason.trim()} onClick={()=>decide('cancel')}>Cancel OB</button>{['Approved','For Review'].includes(selected.status)&&<button className={button} disabled={busy||!reason.trim()||Date.parse(selected.ends_at)>Date.now()} onClick={()=>decide('close')}>Close as Completed</button>}</>}
   </div><p className="text-xs">Amendments suspend the current exception until both approvals are repeated. Completion does not create missing punches or approve additional pay. A separate HR approver is required when the Immediate Head also holds an HR role.</p></div>}
   <div className={box}><h3 className="font-semibold">Approval & amendment history</h3>{selected.history.length?selected.history.map(h=><p className="border-b py-2 text-sm dark:border-slate-700" key={h.id}>{phTime(h.at)} · {h.actor} · {h.action} → {h.status}{h.reason?` · ${h.reason}`:''}</p>):<p>No history available.</p>}</div>
   <div className={box}><h3 className="font-semibold">Actual OB punches & review flags</h3>{selected.punches.length?selected.punches.map(p=><div key={p.id} className="border-b py-3 dark:border-slate-700"><p>{p.action.replaceAll('_',' ')} · {phTime(p.attempted_at)} · {p.recorded?'Recorded':'Not recorded — For review'}</p><p className="text-sm">GPS: {p.latitude}, {p.longitude} · Accuracy {Math.round(p.accuracy)} m</p>{p.reason&&<p className="text-amber-700 dark:text-amber-300">{p.reason}</p>}{p.selfie_path&&<button className="min-h-11 underline" onClick={()=>void openOBFile(p.selfie_path).catch(e=>setError(e.message))}>Open secured selfie</button>}</div>):<p>No OB punches yet. Approval does not clock you in automatically.</p>}</div>
  </>:<><p className="text-sm">{rows.length} requests shown (latest 200). Filter by status to narrow the list.</p>{!headAssigned&&queue==='own'&&<p className={box}>Your Immediate Head is not assigned. HR must update your reporting line before you can submit.</p>}<div className="space-y-3">{rows.map(r=><Link key={r.id} to={`?request=${r.id}`} className={box+' block hover:border-indigo-500'}><div className="flex flex-wrap justify-between gap-2"><strong>{r.reference} · {r.employeeName}</strong><span>{r.status}{r.approval_step!=='none'?` · ${r.approval_step==='head'?'Immediate Head':'HR'}`:''}</span></div><p>{r.destination||'Destination not set'} · {phTime(r.starts_at)} – {phTime(r.ends_at)}</p><p className="text-sm text-gray-500">{r.purpose||'Draft'}{r.override_schedule?' · Schedule override requested':''}</p></Link>)}{!rows.length&&<p className={box}>No OB requests in this view.</p>}</div></>}
 </div>;
}
