import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useAuth} from '../../hooks/useAuth';
import {canImportActualAttendance} from './scheduleScope';
import {supabase} from '../../services/supabaseClient';
import {usePayrollField} from './usePayrollSelection';
import {fetchTimeContext,previewTime,TimeScope} from './attendanceReadiness';
import NormalPayrollPeriodSelector from './NormalPayrollPeriodSelector';
import {attendanceCsv,attendanceFields,attendanceRestSample,attendanceSample,dayStatuses,reviewChoices,downloadText,normalizeAttendance,readAttendanceFile} from './actualAttendanceImport';
import type {AttendanceInput} from './actualAttendanceImport';
import AttendanceImportApprovals from './AttendanceImportApprovals';
type Employee={id:string;code:string;name:string;businessUnit:string};
type ImportHistory={id:string;filename:string;accepted_rows:number;duplicate_rows:number;created_at:string};
type Preview={ready:number;duplicates:number;alreadyImported?:boolean;confirmed?:boolean;errors:{row:number;message:string}[];rows:{row:number;employee:string;workDate:string;dayStatus:string;error:string|null;duplicate:boolean;warnings:string[]}[]};
const field='mt-1 w-full rounded-xl border border-slate-300 bg-white p-3 text-slate-900';
const button='inline-flex min-h-11 items-center justify-center rounded-xl border px-4 py-3 font-semibold';
async function downloadWorkbook(){
 const response=await fetch('/templates/attendance-v3.xlsx.b64');if(!response.ok)throw new Error('Attendance template is unavailable. Try again in a moment.');
 const binary=atob((await response.text()).trim());const bytes=new Uint8Array(binary.length);
 for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);
 const url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));
 const a=document.createElement('a');a.href=url;a.download='attendance-v3.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function ActualAttendancePage(){
 const {user}=useAuth();
 const [scope,setScope]=usePayrollField('scope'),[from]=usePayrollField('from'),[to]=usePayrollField('to');
 if(!canImportActualAttendance(user))return <main className="p-6"><h1 className="text-2xl font-bold">Import Attendance</h1><p className="mt-3">Actual attendance imports require Board of Director, Admin, HR Manager or HR Staff access to the selected business unit.</p><Link to="/payroll/run" className="mt-4 inline-block text-violet-600">Return to Prepare payroll</Link></main>;
 return <AttendanceWorkspace key={`${user?.id}:${scope}:${from}:${to}`} scope={scope} setScope={setScope} from={from} to={to}/>;
}
function AttendanceWorkspace({scope,setScope,from,to}:{key?:string;scope:string;setScope:(value:string)=>void;from:string;to:string}){
 const [history,setHistory]=useState<ImportHistory[]>([]),[historyRevision,setHistoryRevision]=useState(0);
 const [dayDefaults,setDayDefaults]=useState<Record<string,string>>({});
 const [scopes,setScopes]=useState<TimeScope[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [rows,setRows]=useState<AttendanceInput[]>([]),[filename,setFilename]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[sample,setSample]=useState(false),[manual,setManual]=useState(false),[entry,setEntry]=useState<string[]>(['','','','Workday','','','','','','','None','']);
 const [submitted,setSubmitted]=useState(''),[rulesExist,setRulesExist]=useState<boolean|null>(null),[holidayVerified,setHolidayVerified]=useState(false),[splitShiftVerified,setSplitShiftVerified]=useState(false),[ruleReference,setRuleReference]=useState('');
 const unit=scopes.find(s=>s.id===scope)?.name||'';
 useEffect(()=>{let active=true;fetchTimeContext().then(x=>{if(active)setScopes(x.scopes.filter(s=>s.canView));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{let active=true;if(!scope||!from||!to)return;
  Promise.resolve(supabase.rpc('get_actual_attendance_import_context',{p_scope:scope,p_from:from,p_to:to})).then(({data,error})=>{if(!active)return;if(error)setError(error.message);else {setEmployees(data.employees);setHistory(data.imports||[]);setDayDefaults(Object.fromEntries((data.dayStatuses||[]).map((d:{employeeId:string;workDate:string;dayStatus:string})=>[`${d.employeeId}:${d.workDate}`,d.dayStatus])));}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};
 },[scope,from,to,historyRevision]);
 useEffect(()=>{let active=true;if(!scope||!from||!to)return;previewTime(scope,from,to).then(result=>{if(active)setRulesExist(result.rules.some(rule=>rule.effective_from<=from&&rule.effective_to>=to));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[scope,from,to,historyRevision]);
 async function check(next:AttendanceInput[],name:string,confirm=false){setBusy(true);setError('');try{
  if(!confirm)setSubmitted('');
  const payload={p_scope:scope,p_from:from,p_to:to,p_filename:name,p_rows:next};
  const {data,error}=confirm?await supabase.rpc('submit_actual_attendance_import',{
   ...payload,p_rules:!rulesExist&&holidayVerified&&ruleReference.trim().length>=3?{holidayCoverageConfirmed:true,splitShiftConfirmed:splitShiftVerified}:null,
   p_rule_reference:!rulesExist&&holidayVerified&&ruleReference.trim().length>=3?ruleReference.trim():null
  }):await supabase.rpc('import_actual_attendance',{...payload,p_confirm:false});
  if(error)throw error;setRows(next);setFilename(name);setPreview(data.preview||data);
  if(data.submitted){setSubmitted(data.status);setHistoryRevision(x=>x+1);}
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(file:File){setBusy(true);setError('');setPreview(null);setSubmitted('');try{await check(await readAttendanceFile(file,unit,dayDefaults),file.name);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="mx-auto max-w-7xl space-y-5 p-5 text-slate-900 dark:text-slate-100">
  <nav aria-label="Timekeeping sections" className="flex flex-wrap gap-2 rounded-xl border border-slate-200 bg-white p-2 dark:border-slate-700 dark:bg-slate-800"><Link className="rounded-lg px-4 py-3 font-semibold text-violet-700 dark:text-violet-300" to={`/payroll/timekeeping?week=${from}&source=payroll&businessUnit=${encodeURIComponent(unit)}`}>Schedules</Link><span aria-current="page" className="rounded-lg bg-violet-600 px-4 py-3 font-semibold text-white">Import Attendance</span></nav>
  <header><Link to="/payroll/run" className="text-violet-600">← Prepare payroll</Link><h1 className="mt-3 text-3xl font-bold">Import Attendance</h1><p className="mt-2 text-slate-500">Upload, review, and submit once. HR Manager reviews staff uploads, then one BOD approves. After approval, these actual punches become the payroll source. Earlier clock records remain in the audit history.</p></header>
  <div className="grid gap-4 lg:grid-cols-2"><label>Business unit<select className={field} value={scope} disabled={busy} onChange={e=>setScope(e.target.value)}><option value="">Choose business unit</option>{scopes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><NormalPayrollPeriodSelector disabled={busy}/></div>
  <Link className={`${button} text-violet-700`} to="/payroll/import/attendance-events">Multiple sessions or breaks? Use the event-log template</Link>
  <section className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="text-xl font-bold">Daily attendance · template version 3</h2><p className="mt-2 text-sm text-slate-500">Choose a day status for each employee/date. Mark missing punches, absence, suspension, rest-day work, holiday work, lunch or OT in Needs review and explain it. Blank punches on an existing rest day are valid. Older version 1 and 2 files still work. Use explicit next-day dates for overnight work.</p>
   <button className={`${button} mt-4 border-violet-300 text-violet-700`} onClick={()=>void downloadWorkbook().catch(e=>setError((e as Error).message))}>Download template (XLSX)</button>
   <div className="mt-4 flex flex-wrap gap-3"><button className={button} onClick={()=>downloadText('attendance-v3.csv',attendanceCsv())}>Download template (CSV)</button><button className={button} disabled={!employees.length} onClick={()=>downloadText('attendance-prefilled.csv',attendanceCsv(employees.flatMap(e=>{const result:string[][]=[];for(let d=new Date(from+'T00:00:00Z');d.toISOString().slice(0,10)<=to;d.setUTCDate(d.getUTCDate()+1)){const date=d.toISOString().slice(0,10);result.push([e.code,unit,date,dayDefaults[`${e.code}:${date}`]||'','','','','','','','None','']);}return result;})))}>Download prefilled template</button><button className={button} onClick={()=>setSample(!sample)}>View sample</button><label className={`${button} bg-violet-600 text-white ${busy||!employees.length?'opacity-50':''}`}>Upload completed file<input className="sr-only" type="file" accept=".csv,.xlsx" disabled={busy||!employees.length} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label><button className={button} onClick={()=>setManual(!manual)}>Enter manually</button></div>
   <p className="mt-3 text-sm text-slate-500">The prefilled template includes every active employee in this business unit and cutoff. Only rows you upload change payroll attendance. Remove an employee's rows if this file should not change their attendance. Use <b>No scheduled work</b> only when the roster confirms it. An uploaded status does not approve an absence or deduction.</p>
   {sample&&<div className="mt-4 overflow-x-auto"><p className="mb-3 font-semibold">Examples only — DEMO-001 is not accepted in a real import.</p><table className="text-sm"><thead><tr>{attendanceFields.map(([h])=><th className="whitespace-nowrap p-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{[attendanceSample,attendanceRestSample].map((row,n)=><tr key={n}>{row.map((v,i)=><td className="whitespace-nowrap border-t p-3" key={i}>{v}</td>)}</tr>)}</tbody></table><button className={`${button} mt-3`} onClick={()=>downloadText('attendance-SAMPLE-DO-NOT-UPLOAD.csv',attendanceCsv([attendanceSample,attendanceRestSample]))}>Download sample CSV</button></div>}
   {manual&&<form className="mt-5" onSubmit={e=>{e.preventDefault();try{void check(normalizeAttendance([[entry[0],unit,...entry.slice(2)]],unit),'Manual attendance entry');}catch(e){setError((e as Error).message);}}}><div className="grid gap-3 sm:grid-cols-3">{attendanceFields.map(([label],i)=>i===1?null:<label key={label} className="text-sm">{label}{i===0?<select className={field} required value={entry[0]} onChange={e=>setEntry(v=>v.map((x,n)=>n===0?e.target.value:x))}><option value="">Choose employee</option>{employees.map(e=><option key={e.id} value={e.code}>{e.name} · {e.code}</option>)}</select>:i===3||i===10?<select className={field} value={entry[i]} onChange={e=>setEntry(v=>v.map((x,n)=>n===i?e.target.value:x))}>{(i===3?dayStatuses:reviewChoices).map(status=><option value={status} key={status}>{status}</option>)}</select>:<input className={field} type={i===2?'date':i>=4&&i<=7?'datetime-local':'text'} required={i===2} value={entry[i]} onChange={e=>setEntry(v=>v.map((x,n)=>n===i?e.target.value:x))}/>}</label>)}</div><button disabled={busy} className={`${button} mt-4`}>Preview actual attendance</button></form>}
  </section>
  {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}
  {busy&&<p role="status">Checking attendance records…</p>}
  <AttendanceImportApprovals scope={scope} from={from} to={to} onApplied={()=>setHistoryRevision(x=>x+1)} key={`${scope}:${from}:${to}:${historyRevision}`}/>
  {!!history.length&&<section className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="text-xl font-bold">Saved imports for this cutoff</h2><p className="mt-2 text-sm text-slate-500">These are actual attendance records, not preview or test data.</p><ul className="mt-3 space-y-2">{history.map(h=><li key={h.id} className="border-t py-3"><span className="font-semibold">{h.filename}</span> · {h.accepted_rows} accepted · {h.duplicate_rows} duplicates skipped · {new Date(h.created_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</li>)}</ul><Link to="/payroll/attendance-readiness" className={`${button} mt-3`}>Review saved attendance</Link></section>}
  {preview&&<section className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="text-xl font-bold">{submitted?'Submitted for approval':preview.alreadyImported?'This file was already imported':'Review before submitting'}</h2><p className="mt-2">{filename} · {unit} · {from}–{to}</p><p className="mt-3 font-semibold">{preview.ready} rows ready · {preview.rows.filter(r=>!r.error&&r.warnings.length).length} needing review · {preview.errors.length} requiring correction · {preview.duplicates} duplicates skipped</p>
   {submitted&&<p className="mt-3 rounded-lg bg-amber-50 p-3 font-semibold text-amber-950">{submitted==='pending_hr_manager'?'Waiting for HR Manager, then one BOD.':'Waiting for one BOD.'} The import is not payroll-effective until final approval.</p>}
   {!submitted&&rulesExist===false&&<div className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><h3 className="font-bold">Cutoff rules need review</h3><p className="mt-1">The standard 5-minute grace, one unpaid lunch hour and one-hour OT minimum can be proposed with this import. Check the actual holiday calendar, including local holidays, before marking it verified. One BOD will approve the proposal. Leave unchecked if it needs separate HR review.</p><label className="mt-3 flex gap-2"><input type="checkbox" checked={holidayVerified} onChange={e=>setHolidayVerified(e.target.checked)}/>I checked holiday coverage for {from}–{to} and this business unit</label><label className="mt-2 flex gap-2"><input type="checkbox" checked={splitShiftVerified} onChange={e=>setSplitShiftVerified(e.target.checked)}/>Split-shift gaps represent the unpaid break and must not be deducted twice</label><label className="mt-3 block">Policy or calendar reference<input className={field} value={ruleReference} onChange={e=>setRuleReference(e.target.value)} placeholder="Approved attendance policy / reviewed holiday calendar"/></label><p className="mt-2">If this is left unconfirmed, the import may be approved as attendance evidence but cutoff rules will still block calculation.</p></div>}
   {rows.length>0&&<div className="mt-4 rounded-xl border border-violet-200 bg-violet-50 p-4 text-sm text-violet-950"><b>{new Set(rows.map(row=>row.employeeId)).size} employees included in this file.</b>{employees.filter(employee=>!new Set(rows.map(row=>row.employeeId)).has(employee.code)).length>0&&<p className="mt-1">Not included: {employees.filter(employee=>!new Set(rows.map(row=>row.employeeId)).has(employee.code)).map(employee=>`${employee.name} (${employee.code})`).join(', ')}. This import will not change their records.</p>}</div>}
   <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Row','Employee','Work date','Day status','Needs review','Result'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{preview.rows.map(r=><tr key={r.row} className="border-t"><td className="p-3">{r.row}</td><td className="p-3">{r.employee}</td><td className="p-3">{r.workDate}</td><td className="p-3">{r.dayStatus||'—'}</td><td className="p-3">{rows.find(input=>input.sourceRow===r.row)?.reviewRequest||'None'}</td><td className={`p-3 ${r.error?'text-red-700':r.warnings.length?'text-amber-700':'text-emerald-700'}`}>{r.error|| (r.duplicate?'Already current — unchanged':r.warnings.join(' ')||'Ready after approval')}</td></tr>)}</tbody></table></div>
   {!!preview.errors.length&&<button className={`${button} mt-4`} onClick={()=>downloadText('attendance-errors.csv','Row,Error\r\n'+preview.errors.map(e=>`${e.row},"${e.message.replaceAll('"','""')}"`).join('\r\n'))}>Download errors</button>}
   {!submitted&&!preview.alreadyImported&&<button disabled={busy||!!preview.errors.length||!preview.ready} className={`${button} mt-4 bg-violet-600 text-white disabled:opacity-50`} onClick={()=>void check(rows,filename,true)}>Submit attendance for approval</button>}
   {(submitted||preview.alreadyImported)&&<Link className={`${button} mt-4`} to="/payroll/run">Return to Prepare payroll</Link>}
  </section>}
 </main>;
}
