import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useAuth} from '../../hooks/useAuth';
import {canImportActualAttendance} from './scheduleScope';
import {supabase} from '../../services/supabaseClient';
import {usePayrollField} from './usePayrollSelection';
import {fetchTimeContext,previewTime,TimeScope} from './attendanceReadiness';
import NormalPayrollPeriodSelector from './NormalPayrollPeriodSelector';
import {attendanceCsv,attendanceFields,attendanceRestSample,attendanceSample,dayStatuses,reviewChoices,downloadText,normalizeAttendance,prefillAttendanceWorkbook,readAttendanceFile,publishedAttendanceReferences} from './actualAttendanceImport';
import type {AttendanceInput,PrefilledAttendanceDay,AttendanceParseIssue} from './actualAttendanceImport';
import AttendanceImportApprovals from './AttendanceImportApprovals';
import AttendancePayDecisions,{AttendancePayDecision} from './AttendancePayDecisions';
type Employee={id:string;code:string;name:string;businessUnit:string};
type ImportHistory={id:string;filename:string;accepted_rows:number;duplicate_rows:number;created_at:string};
type Preview={payDecisions?:AttendancePayDecision[];ready:number;duplicates:number;alreadyImported?:boolean;confirmed?:boolean;errors:{row:number;message:string}[];changes?:{row:number;beforeStatus:string;afterStatus:string;beforeSource:string;reference:string;rosterPublished:boolean;rosterPublicationId:string|null;rosterVersion:number|null;beforeEvents:{type:string;timestamp:string}[];afterEvents:{type:string;timestamp:string}[]}[];rows:{row:number;employee:string;workDate:string;dayStatus:string;error:string|null;duplicate:boolean;warnings:string[]}[]};
const field='mt-1 w-full rounded-xl border border-slate-300 bg-white p-3 text-slate-900';
const button='inline-flex min-h-11 items-center justify-center rounded-xl border px-4 py-3 font-semibold';
async function downloadWorkbook(prefilled?:PrefilledAttendanceDay[],leaveTypes:string[]=[]){
 const response=await fetch('/templates/attendance-v5.xlsx.b64');if(!response.ok)throw new Error('Attendance template is unavailable. Try again in a moment.');
 const binary=atob((await response.text()).trim());const bytes=new Uint8Array(binary.length);
 for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);
 let contents:Uint8Array|ArrayBuffer=bytes;
 if(prefilled)contents=await prefillAttendanceWorkbook(bytes.buffer,prefilled,leaveTypes) as ArrayBuffer;
 const url=URL.createObjectURL(new Blob([contents],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));
 const a=document.createElement('a');a.href=url;a.download=prefilled?'attendance-prefilled-v5.xlsx':'attendance-v5.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function fileBase64(bytes:ArrayBuffer){const array=new Uint8Array(bytes);let result='';for(let i=0;i<array.length;i+=8192)result+=String.fromCharCode(...array.subarray(i,i+8192));return btoa(result);}
function showPunches(events:{type:string;timestamp:string}[]){return events?.length?events.map(event=>`${event.type} ${new Date(event.timestamp).toLocaleString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}`).join(' · '):'No punches';}
function mondayOf(date:string){const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return d.toISOString().slice(0,10);}
export default function ActualAttendancePage(){
 const {user}=useAuth();
 const [scope,setScope]=usePayrollField('scope'),[from]=usePayrollField('from'),[to]=usePayrollField('to');
 if(!canImportActualAttendance(user))return <main className="p-6"><h1 className="text-2xl font-bold">Import Attendance</h1><p className="mt-3">Actual attendance imports require Board of Director, Admin, HR Manager or HR Staff access to the selected business unit.</p><Link to="/payroll/run" className="mt-4 inline-block text-violet-600">Return to Prepare payroll</Link></main>;
 return <AttendanceWorkspace key={`${user?.id}:${scope}:${from}:${to}`} scope={scope} setScope={setScope} from={from} to={to}/>;
}
function AttendanceWorkspace({scope,setScope,from,to}:{key?:string;scope:string;setScope:(value:string)=>void;from:string;to:string}){
 const [history,setHistory]=useState<ImportHistory[]>([]),[historyRevision,setHistoryRevision]=useState(0);
 const [scheduleDays,setScheduleDays]=useState<PrefilledAttendanceDay[]>([]),[leaveTypes,setLeaveTypes]=useState<string[]>([]);
 const [dayDefaults,setDayDefaults]=useState<Record<string,string>>({});
 const [scopes,setScopes]=useState<TimeScope[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [rows,setRows]=useState<AttendanceInput[]>([]),[filename,setFilename]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[sample,setSample]=useState(false),[manual,setManual]=useState(false),[entry,setEntry]=useState<string[]>(['','','','','Worked','','','','','','','None','']);
 const [parseIssues,setParseIssues]=useState<AttendanceParseIssue[]>([]);
 const [sourceBase64,setSourceBase64]=useState('');
 const [submitted,setSubmitted]=useState(''),[rulesExist,setRulesExist]=useState<boolean|null>(null);
 const unit=scopes.find(s=>s.id===scope)?.name||'';
 useEffect(()=>{let active=true;fetchTimeContext().then(x=>{if(active)setScopes(x.scopes.filter(s=>s.canView));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{let active=true;if(!scope||!from||!to)return;
  Promise.resolve(supabase.rpc('get_actual_attendance_import_context',{p_scope:scope,p_from:from,p_to:to})).then(({data,error})=>{if(!active)return;if(error)setError(error.message);else {setEmployees(data.employees);setScheduleDays(publishedAttendanceReferences(data.scheduleDays||[]));setLeaveTypes(data.leaveTypes||[]);setHistory(data.imports||[]);setDayDefaults(Object.fromEntries((data.dayStatuses||[]).map((d:{employeeId:string;workDate:string;dayStatus:string})=>[`${d.employeeId}:${d.workDate}`,d.dayStatus])));}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};
 },[scope,from,to,historyRevision]);
 useEffect(()=>{let active=true;if(!scope||!from||!to)return;previewTime(scope,from,to).then(result=>{if(active)setRulesExist(Array.from({length:Math.round((Date.parse(to)-Date.parse(from))/86400000)+1},(_,i)=>new Date(Date.parse(from)+i*86400000).toISOString().slice(0,10)).every(date=>result.rules.some(rule=>rule.effective_from<=date&&rule.effective_to>=date)));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[scope,from,to,historyRevision]);
 async function check(next:AttendanceInput[],name:string,confirm=false,original=''){setBusy(true);setError('');try{
  if(!confirm){setSubmitted('');setSourceBase64(original);}
  const payload={p_scope:scope,p_from:from,p_to:to,p_filename:name,p_rows:next};
  const {data,error}=confirm?await supabase.rpc('submit_actual_attendance_import',{
   ...payload,p_rules:null,p_rule_reference:null,
   ...(sourceBase64?{p_source_base64:sourceBase64}:{})
  }):await supabase.rpc('import_actual_attendance',{...payload,p_confirm:false});
  if(error)throw error;setRows(next);setFilename(name);setPreview(data.preview||data);
  if(data.submitted){setSubmitted(data.status);setHistoryRevision(x=>x+1);}
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(file:File){setBusy(true);setError('');setPreview(null);setSubmitted('');setParseIssues([]);try{const contents=fileBase64(await file.arrayBuffer());const problems:AttendanceParseIssue[]=[];const parsed=await readAttendanceFile(file,unit,dayDefaults,problems);setParseIssues(problems);if(parsed.length)await check(parsed,file.name,false,contents);else setError('No valid rows yet. Correct the listed rows and upload the file again.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}

 return <main className="mx-auto max-w-7xl space-y-5 p-5 text-slate-900 dark:text-slate-100">
  <nav aria-label="Timekeeping sections" className="flex flex-wrap gap-2 rounded-xl border border-slate-200 bg-white p-2 dark:border-slate-700 dark:bg-slate-800"><Link className="rounded-lg px-4 py-3 font-semibold text-violet-700 dark:text-violet-300" to={`/payroll/timekeeping?week=${mondayOf(from)}&source=payroll&businessUnit=${encodeURIComponent(unit)}`}>Schedules</Link><span aria-current="page" className="rounded-lg bg-violet-600 px-4 py-3 font-semibold text-white">Import Attendance</span></nav>
  <header><Link to="/payroll/run" className="text-violet-600">← Prepare payroll</Link><h1 className="mt-3 text-3xl font-bold">Import Attendance</h1><p className="mt-2 text-slate-500">Upload, review, and submit once. HR Manager reviews staff uploads, then one BOD approves. After approval, these actual punches become the payroll source. Earlier clock records remain in the audit history.</p></header>
  <div className="grid gap-4 lg:grid-cols-2"><label>Business unit<select className={field} value={scope} disabled={busy} onChange={e=>setScope(e.target.value)}><option value="">Choose business unit</option>{scopes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><NormalPayrollPeriodSelector disabled={busy}/></div>
  <Link className={`${button} text-violet-700`} to="/payroll/import/attendance-events">Multiple sessions or breaks? Use the event-log template</Link>
  <section className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="text-xl font-bold">Daily attendance · template version 5</h2><p className="mt-2 text-sm text-slate-500">Choose a day status for each employee/date. Mark missing punches, absence, suspension, rest-day work, holiday work, lunch or OT in Needs review and explain it. Blank punches on an existing rest day are valid. Versions 1–4 still work. Published shifts appear in the prefilled workbook as reference columns; actual punches remain blank. Optional OT and leave columns create separate approval requests. Use explicit next-day dates for overnight work.</p>
   <button className={`${button} mt-4 border-violet-300 text-violet-700`} onClick={()=>void downloadWorkbook().catch(e=>setError((e as Error).message))}>Download template (XLSX)</button>
   <div className="mt-4 flex flex-wrap gap-3"><button className={button} onClick={()=>downloadText('attendance-v5.csv',attendanceCsv())}>Download template (CSV)</button><button className={button} disabled={!scheduleDays.length||busy} onClick={()=>{void downloadWorkbook(scheduleDays,leaveTypes).catch(e=>setError((e as Error).message));}}>Download prefilled template (XLSX)</button><button className={button} onClick={()=>setSample(!sample)}>View sample</button><label className={`${button} bg-violet-600 text-white ${busy||!employees.length?'opacity-50':''}`}>Upload completed file<input className="sr-only" type="file" accept=".csv,.xlsx" disabled={busy||!employees.length} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label><button className={button} onClick={()=>setManual(!manual)}>Enter manually</button></div>
   <p className="mt-3 text-sm text-slate-500">The prefilled template includes employees employed on each work date in this business unit and cutoff. Only rows you upload change payroll attendance. Remove an employee's rows if this file should not change their attendance. Use <b>No scheduled work</b> only when the roster confirms it. An uploaded status does not approve an absence or deduction.</p>
   {sample&&<div className="mt-4 overflow-x-auto"><p className="mb-3 font-semibold">Examples only — DEMO-001 is not accepted in a real import.</p><table className="text-sm"><thead><tr>{attendanceFields.map(([h])=><th className="whitespace-nowrap p-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{[attendanceSample,attendanceRestSample].map((row,n)=><tr key={n}>{row.map((v,i)=><td className="whitespace-nowrap border-t p-3" key={i}>{v}</td>)}</tr>)}</tbody></table><button className={`${button} mt-3`} onClick={()=>downloadText('attendance-SAMPLE-DO-NOT-UPLOAD.csv',attendanceCsv([attendanceSample,attendanceRestSample]))}>Download sample CSV</button></div>}
   {manual&&<form className="mt-5" onSubmit={e=>{e.preventDefault();try{void check(normalizeAttendance([[entry[0],employees.find(emp=>emp.code===entry[0])?.name||'',unit,...entry.slice(3)]],unit),'Manual attendance entry');}catch(e){setError((e as Error).message);}}}><div className="grid gap-3 sm:grid-cols-3">{attendanceFields.slice(0,13).map(([label],i)=>i===1||i===2?null:<label key={label} className="text-sm">{label}{i===0?<select className={field} required value={entry[0]} onChange={e=>setEntry(v=>v.map((x,n)=>n===0?e.target.value:x))}><option value="">Choose employee</option>{employees.map(e=><option key={e.id} value={e.code}>{e.name} · {e.code}</option>)}</select>:i===4||i===11?<select className={field} value={entry[i]} onChange={e=>setEntry(v=>v.map((x,n)=>n===i?e.target.value:x))}>{(i===4?dayStatuses:reviewChoices).map(status=><option value={status} key={status}>{status}</option>)}</select>:<input className={field} type={i===3?'date':i>=5&&i<=8?'datetime-local':'text'} required={i===3} value={entry[i]} onChange={e=>setEntry(v=>v.map((x,n)=>n===i?e.target.value:x))}/>}</label>)}</div><button disabled={busy} className={`${button} mt-4`}>Preview actual attendance</button></form>}
  </section>
  {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}
  {!!parseIssues.length&&<section className="rounded-xl border border-red-300 bg-red-50 p-4 text-red-900"><h2 className="font-bold">{parseIssues.length} spreadsheet rows need correction</h2><p className="mt-1 text-sm">Valid rows are kept in the preview. Nothing will be submitted until these errors are corrected and the file is uploaded again.</p><ul className="mt-2 text-sm">{parseIssues.slice(0,10).map(issue=><li key={issue.row}>{issue.message}</li>)}</ul><button className={`${button} mt-3`} onClick={()=>downloadText('attendance-rows-to-correct.csv',attendanceCsv(parseIssues.map(issue=>Array.from({length:attendanceFields.length},(_,i)=>i===10?[issue.values[i],issue.message].filter(Boolean).join(' — '):issue.values[i]||''))))}>Download rows to correct</button></section>}
  {busy&&<p role="status">Checking attendance records…</p>}
  <AttendanceImportApprovals scope={scope} from={from} to={to} onApplied={()=>setHistoryRevision(x=>x+1)} key={`${scope}:${from}:${to}:${historyRevision}`}/>
  {!!history.length&&<section className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="text-xl font-bold">Saved imports for this cutoff</h2><p className="mt-2 text-sm text-slate-500">These are actual attendance records, not preview or test data.</p><ul className="mt-3 space-y-2">{history.map(h=><li key={h.id} className="border-t py-3"><span className="font-semibold">{h.filename}</span> · {h.accepted_rows} accepted · {h.duplicate_rows} duplicates skipped · {new Date(h.created_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</li>)}</ul><Link to="/payroll/attendance-readiness" className={`${button} mt-3`}>Review saved attendance</Link></section>}
  {preview&&<section className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="text-xl font-bold">{submitted?'Submitted for approval':preview.alreadyImported?'This file was already imported':'Review before submitting'}</h2><p className="mt-2">{filename} · {unit} · {from}–{to}</p><p className="mt-3 font-semibold">{preview.ready} rows ready · {preview.rows.filter(r=>!r.error&&r.warnings.length).length} needing review · {preview.errors.length} requiring correction · {preview.duplicates} duplicates skipped</p>
   {submitted&&<p className="mt-3 rounded-lg bg-amber-50 p-3 font-semibold text-amber-950">{submitted==='pending_hr_manager'?'Waiting for HR Manager, then one BOD.':'Waiting for one BOD.'} The import is not payroll-effective until final approval.</p>}
   {!submitted&&rulesExist===false&&<div className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><h3 className="font-bold">One shared setup task: attendance policy coverage</h3><p className="mt-1">HR needs to confirm the existing attendance policy and holiday calendar for this business unit and period. You can submit attendance now; payroll calculation will wait for this setup.</p><Link className="mt-2 inline-block font-semibold underline" to="/payroll/attendance-readiness#attendance-references">Open attendance settings →</Link></div>}
   {rows.length>0&&<div className="mt-4 rounded-xl border border-violet-200 bg-violet-50 p-4 text-sm text-violet-950"><b>{new Set(rows.map(row=>row.employeeId)).size} employees included in this file.</b>{employees.filter(employee=>!new Set(rows.map(row=>row.employeeId)).has(employee.code)).length>0&&<p className="mt-1">Not included: {employees.filter(employee=>!new Set(rows.map(row=>row.employeeId)).has(employee.code)).map(employee=>`${employee.name} (${employee.code})`).join(', ')}. This import will not change their records.</p>}</div>}
   <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Row','Employee','Work date','Before → proposed','Needs review','Result'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{preview.rows.map(r=>{const change=preview.changes?.find(c=>c.row===r.row);return <tr key={r.row} className="border-t"><td className="p-3">{r.row}</td><td className="p-3">{r.employee}</td><td className="p-3">{r.workDate}</td><td className="p-3">{change?`${change.beforeStatus} → ${change.afterStatus}`:r.dayStatus||'—'}{change&&<span className="block max-w-md text-xs text-slate-500">Before ({change.beforeSource}): {showPunches(change.beforeEvents)}<br/>Proposed: {showPunches(change.afterEvents)}<br/>Evidence: {change.reference||filename}<br/>Roster: {change.rosterPublished?`Published v${change.rosterVersion} (${change.rosterPublicationId})`:change.rosterPublicationId?`Version ${change.rosterVersion} is not current or approved`:'No publication for this date'}</span>}</td><td className="p-3">{rows.find(input=>input.sourceRow===r.row)?.reviewRequest||'None'}</td><td className={`p-3 ${r.error?'text-red-700':r.warnings.length?'text-amber-700':'text-emerald-700'}`}>{r.error|| (r.duplicate?'Already current — unchanged':r.warnings.join(' ')||'Ready after approval')}{r.error&&/roster|schedule/i.test(r.error)&&<Link className="mt-1 block font-semibold underline" to={`/payroll/timekeeping?week=${mondayOf(r.workDate)}&source=payroll&businessUnit=${encodeURIComponent(unit)}`}>Open this week in Schedule Builder →</Link>}</td></tr>;})}</tbody></table></div>
   <AttendancePayDecisions items={preview.payDecisions||[]}/>
   {!!preview.errors.length&&<button className={`${button} mt-4`} onClick={()=>downloadText('attendance-errors.csv','Row,Error\r\n'+preview.errors.map(e=>`${e.row},"${e.message.replaceAll('"','""')}"`).join('\r\n'))}>Download errors</button>}
   {!submitted&&!preview.alreadyImported&&<button disabled={busy||!!parseIssues.length||!!preview.errors.length||!preview.ready} className={`${button} mt-4 bg-violet-600 text-white disabled:opacity-50`} onClick={()=>void check(rows,filename,true)}>Submit attendance for approval</button>}
   {(submitted||preview.alreadyImported)&&<Link className={`${button} mt-4`} to="/payroll/run">Return to Prepare payroll</Link>}
  </section>}
 </main>;
}
