import {usePayrollField} from './usePayrollSelection';
import {validCutoff,modeLabel} from './workspace';
import {workspaceApprovals,nextApproval} from './approvalWorkspace';
import React,{useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import {useAuth} from '../../hooks/useAuth';
import SetupChecklistLink from './SetupChecklistLink';
import {approvalStages,getApproval,submitApproval,actApproval} from './approvals';
import type {Approval,ApprovalSummary} from './approvals';
import DebtApprovalPanel from './DebtApprovalPanel';
import NTEDeductionApprovalPanel from './NTEDeductionApprovalPanel';
import ServiceChargeApprovalPanel from './ServiceChargeApprovalPanel';
import PayrollCycleSelector from './PayrollCycleSelector';
const input='mt-1 block w-full rounded border border-gray-300 p-2 dark:bg-slate-800 dark:border-slate-600';
export default function ApprovalsPage(){
 const {user}=useAuth();const [params,setParams]=useSearchParams();const [items,setItems]=useState<ApprovalSummary[]>([]);const [run,setRun]=useState<Approval|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const [ref,setRef]=useState('');const [contact,setContact]=useState('');
 const [scopeId]=usePayrollField('scope'),[from]=usePayrollField('from'),[to]=usePayrollField('to');const [offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false);
 const loadList=()=>scopeId&&validCutoff(from,to)?workspaceApprovals(scopeId,from,to,offset):Promise.resolve({items:[],hasMore:false});
 const id=params.get('run');const net=params.get('net');const special=params.get('special');
 const [refresh,setRefresh]=useState(0);const viewKey=`${user?.id}:${scopeId}:${from}:${to}:${id}:${net}:${special}:${offset}`;const currentView=useRef(viewKey);currentView.current=viewKey;
 useEffect(()=>{setOffset(0);},[scopeId,from,to]);
 useEffect(()=>{let active=true;setItems([]);setHasMore(false);setRun(null);setError('');setReason('');setRef('');setContact('');setBusy(true);void Promise.allSettled([loadList(),id?getApproval(id):Promise.resolve(null)]).then(([list,r])=>{if(!active)return;if(list.status==='fulfilled'){setItems(list.value.items);setHasMore(list.value.hasMore);}else setError(list.reason.message);if(r.status==='fulfilled')setRun(r.value);else setError(r.reason.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[user?.id,id,net,special,scopeId,from,to,offset,refresh]);
 async function action(type:string){if(!run)return;const key=viewKey;setBusy(true);setError('');try{await actApproval(run.id,run.step,type,reason);const [updated,page]=await Promise.all([getApproval(run.id),loadList()]);if(currentView.current!==key)return;setRun(updated);setItems(page.items);setHasMore(page.hasMore);setReason('');}catch(e){if(currentView.current!==key)return;setError((e as Error).message);try{const updated=await getApproval(run.id);if(currentView.current===key)setRun(updated);}catch{if(currentView.current===key)setRun(null);}}finally{if(currentView.current===key)setBusy(false);}}
 async function submit(){const key=viewKey;setBusy(true);setError('');try{const submitted=await submitApproval(net,special,ref,contact);if(currentView.current===key)setParams({run:submitted});}catch(e){if(currentView.current===key)setError((e as Error).message);}finally{if(currentView.current===key)setBusy(false);}}
 return <div className="space-y-6"><h1 className="text-3xl font-bold">Payroll Approvals</h1><p>Review one saved version through the required sequence. Changed inputs require a new version and fresh approvals.</p><PayrollCycleSelector compact/><SetupChecklistLink/><p>Workspace cutoff: {validCutoff(from,to)?`${from}–${to}`:'not selected'}. <Link className="underline" to="/payroll/home">Choose business unit and cutoff</Link>.</p>
 {error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>}
 {(net||special)&&!id&&<Card title="Submit this saved payroll version"><p className="mb-3 text-sm">Finance submits the current complete version. Regular payroll must already have HR-submitted timekeeping; special pay needs its independent Finance check. Processing must be enabled for shadow review. Submission does not make the payroll approved or paid.</p><form className="space-y-3" onSubmit={e=>{e.preventDefault();void submit();}}><label className="block">Finance submission reference<input className={input} required minLength={3} value={ref} onChange={e=>setRef(e.target.value)} disabled={busy}/></label><label className="block">Payroll correction contact for employees<input className={input} required minLength={3} maxLength={300} value={contact} onChange={e=>setContact(e.target.value)} disabled={busy}/></label><Button disabled={busy}>Submit for HR validation</Button></form></Card>}
 <Card title="Submitted payroll versions"><Button type="button" variant="secondary" disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Refresh approvals</Button><p className="mb-3 text-sm">Only versions for the selected business unit and cutoff within your current payroll and HRIS salary access appear. Your duties and HRIS role must both match the pending step.</p>{busy&&items.length===0?<p role="status">Checking submitted versions…</p>:error&&items.length===0?<p>Submitted versions are unavailable until refreshed.</p>:!scopeId||!validCutoff(from,to)?<p>Select a business unit and cutoff in Payroll Home to load submitted versions.</p>:items.length===0?<p>No submitted payroll is available. Start from a saved version in <Link className="text-indigo-600" to="/payroll/net-pay">Take-home Pay Review</Link> or <Link className="text-indigo-600" to="/payroll/special-pay">Special Pay & Corrections</Link>.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Period / version','Status','Mode','Action'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{items.map(r=><tr key={r.id} className="border-t"><td className="p-2">{r.from}–{r.to} · {r.kind} · v{r.version}</td><td className="p-2">{r.stage}{r.canAct&&<strong className="block text-indigo-600">Your approval is needed</strong>}</td><td className="p-2">{modeLabel(r.mode)}</td><td className="p-2"><Button variant="secondary" disabled={busy} onClick={()=>setParams({run:r.id})}>Open</Button></td></tr>)}</tbody></table></div>}<div className="mt-3 flex gap-3">{offset>0&&<Button disabled={busy} variant="secondary" onClick={()=>setOffset(v=>Math.max(0,v-50))}>Newer versions</Button>}{hasMore&&<Button disabled={busy} variant="secondary" onClick={()=>setOffset(v=>v+50)}>Older versions</Button>}</div></Card>
 {run&&<><Card title={run.stage}><p className="mb-3">Current owner (role): <strong>{nextApproval({...run,from:run.source.from,to:run.source.to,kind:run.source.kind,version:run.source.version}).owner}</strong>. {run.scopeId!==scopeId||run.source.from!==from||run.source.to!==to?'This directly linked version is outside the selected workspace cutoff; its own scope and period apply.':''}</p><p className="mb-3 font-medium">{run.mode==='shadow'?'Shadow review — payment and employee release stay blocked.':'Live payroll version'}</p>{!run.current&&<p role="alert" className="mb-3 text-red-700">Prior approvals cannot authorize changed inputs. {run.staleReason}</p>}<ol className="grid gap-2 sm:grid-cols-2">{approvalStages.map((s,i)=>{const a=run.actions.find(a=>a.step===i);return <li key={s} className={`rounded border p-3 ${i===run.step&&!run.returned?'border-indigo-500':''}`}><strong>{i+1}. {s}</strong><p>{a?`${a.action==='return'?'Returned':'Approved'} by ${a.actor}`:i===run.step?'Pending':'Waiting'}</p>{a&&<p className="text-sm">{a.reason} · {new Date(a.at).toLocaleString('en-PH')}</p>}</li>;})}</ol><p className="mt-3">BOD approvals: {run.actions.filter(a=>a.step>=4&&a.action==='approve').length} of 2. The same BOD cannot approve twice.</p>
 {run.canAct&&<form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();void action('approve');}}><label className="block">Review / decision reference<textarea required minLength={3} maxLength={1000} className={input} value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/></label><div className="flex flex-wrap gap-3"><Button disabled={busy||reason.trim().length<3}>Approve {approvalStages[run.step]}</Button><Button type="button" variant="secondary" disabled={busy||reason.trim().length<3} onClick={()=>void action('return')}>Return for revision</Button></div></form>}
 {!run.canAct&&!run.paid&&run.step<6&&<p className="mt-3 text-sm">Action is available only to the current eligible reviewer. Preparers and material PR editors cannot approve their own version.</p>}</Card>
 <Card title="Private payroll preview"><p className="mb-3 text-sm">Internal review only. This preview is not an employee payslip or proof of payment.</p><p>Period {run.source.from}–{run.source.to} · payday {run.source.payDate} · version {run.source.version}</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{[['Gross',run.source.gross],['Employee deductions',run.source.deductions],['Net',run.source.net]].map(([label,value])=><div key={label}><p>{label}</p><strong>PHP {value}</strong></div>)}</div>{run.source.employees.map(e=><details key={e.employeeId} className="mt-3 border-t pt-3"><summary>{e.employeeName} · PHP {e.net}</summary><p className="my-2">Gross {e.gross} − deductions {e.deductions} = net {e.net}. Tax {e.tax}.</p>{e.lines.map((l,i)=><p className="text-sm" key={i}>{l.label}: PHP {l.remaining??l.amount}</p>)}</details>)}<p className="mt-3 text-sm">Submission: {run.reference}. Payroll contact: {run.contact}.</p></Card>
 <ServiceChargeApprovalPanel scopeId={run.scopeId} from={run.source.from} to={run.source.to} payrollDate={run.source.payDate} employees={run.source.employees}/>
 <DebtApprovalPanel scopeId={run.scopeId} payrollDate={run.source.payDate} employees={run.source.employees}/>
 <NTEDeductionApprovalPanel scopeId={run.scopeId} payrollDate={run.source.payDate} employees={run.source.employees}/>
 {run.mode==='shadow'?<Card title="Test approval — no payment or employee release"><p>Even after all six decisions, this test version cannot release payments or employee payslips. HR and Finance must accept its formal comparison before a separate live handover proposal.</p><Link className="mt-3 inline-block text-indigo-600" to="/payroll/pilot#handover">Continue to Compare & Pilot</Link></Card>:<Card title="Finance payments & payslip release"><p>Record attempts, actual outcomes and linked reissues in Payments & Reports. Complete full-batch reconciliation to release private payslips. Original receipts remain intact if a payment is later returned.</p><Link className="mt-3 inline-block text-indigo-600" to={`/payroll/payments?run=${run.id}`}>Open Payments & Reports</Link></Card>}</>}

 </div>;
}
