import React,{useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import {useAuth} from '../../hooks/useAuth';
import PhaseChecklist from './PhaseChecklist';
import {approvalStages,listApprovals,getApproval,submitApproval,actApproval,recordDisbursement} from './approvals';
import type {Approval,ApprovalSummary} from './approvals';
const input='mt-1 block w-full rounded border border-gray-300 p-2 dark:bg-slate-800 dark:border-slate-600';
export default function ApprovalsPage(){
 const {user}=useAuth();const [params,setParams]=useSearchParams();const [items,setItems]=useState<ApprovalSummary[]>([]);const [run,setRun]=useState<Approval|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const [ref,setRef]=useState('');const [contact,setContact]=useState('');const [paidDate,setPaidDate]=useState('');const [amount,setAmount]=useState('');
 const id=params.get('run');const net=params.get('net');const special=params.get('special');
 useEffect(()=>{let active=true;setRun(null);setError('');setReason('');setRef('');setContact('');setPaidDate('');setAmount('');setBusy(true);void Promise.all([listApprovals(),id?getApproval(id):Promise.resolve(null)]).then(([list,r])=>{if(active){setItems(list);setRun(r);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[user?.id,id,net,special]);
 async function action(type:string){if(!run)return;setBusy(true);setError('');try{await actApproval(run.id,run.step,type,reason);setRun(await getApproval(run.id));setItems(await listApprovals());setReason('');}catch(e){setError((e as Error).message);try{setRun(await getApproval(run.id));}catch{setRun(null);}}finally{setBusy(false);}}
 async function submit(){setBusy(true);setError('');try{setParams({run:await submitApproval(net,special,ref,contact)});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function paid(){if(!run)return;setBusy(true);setError('');try{await recordDisbursement(run.id,ref,paidDate,amount);setRun(await getApproval(run.id));setItems(await listApprovals());}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="space-y-6"><h1 className="text-3xl font-bold">Payroll Approvals</h1><p>Review one saved version through the required sequence. Changed inputs require a new version and fresh approvals.</p><PhaseChecklist/>
 {error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>}
 {(net||special)&&!id&&<Card title="Submit this saved payroll version"><p className="mb-3 text-sm">Finance submits the current complete version. Regular payroll must already have HR-submitted timekeeping; special pay needs its independent Finance check. Processing must be enabled for shadow review. Submission does not make the payroll approved or paid.</p><form className="space-y-3" onSubmit={e=>{e.preventDefault();void submit();}}><label className="block">Finance submission reference<input className={input} required minLength={3} value={ref} onChange={e=>setRef(e.target.value)} disabled={busy}/></label><label className="block">Payroll correction contact for employees<input className={input} required minLength={3} maxLength={300} value={contact} onChange={e=>setContact(e.target.value)} disabled={busy}/></label><Button disabled={busy}>Submit for HR validation</Button></form></Card>}
 <Card title="Submitted payroll versions"><p className="mb-3 text-sm">Only versions within your current payroll and HRIS salary access appear. Your duties and HRIS role must both match the pending step.</p>{items.length===0?<p>No submitted payroll is available. Start from a saved version in <Link className="text-indigo-600" to="/payroll/net-pay">Take-home Pay Review</Link> or <Link className="text-indigo-600" to="/payroll/special-pay">Special Pay & Corrections</Link>.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Period / version','Status','Mode','Action'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{items.map(r=><tr key={r.id} className="border-t"><td className="p-2">{r.from}–{r.to} · {r.kind} · v{r.version}</td><td className="p-2">{r.stage}{r.canAct&&<strong className="block text-indigo-600">Your approval is needed</strong>}</td><td className="p-2">{r.mode}</td><td className="p-2"><Button variant="secondary" disabled={busy} onClick={()=>setParams({run:r.id})}>Open</Button></td></tr>)}</tbody></table></div>}</Card>
 {run&&<><Card title={run.stage}><p className="mb-3 font-medium">{run.mode==='shadow'?'Shadow review — payment and employee release stay blocked.':'Live payroll version'}</p>{!run.current&&<p role="alert" className="mb-3 text-red-700">Prior approvals cannot authorize changed inputs. {run.staleReason}</p>}<ol className="grid gap-2 sm:grid-cols-2">{approvalStages.map((s,i)=>{const a=run.actions.find(a=>a.step===i);return <li key={s} className={`rounded border p-3 ${i===run.step&&!run.returned?'border-indigo-500':''}`}><strong>{i+1}. {s}</strong><p>{a?`${a.action==='return'?'Returned':'Approved'} by ${a.actor}`:i===run.step?'Pending':'Waiting'}</p>{a&&<p className="text-sm">{a.reason} · {new Date(a.at).toLocaleString('en-PH')}</p>}</li>;})}</ol><p className="mt-3">BOD approvals: {run.actions.filter(a=>a.step>=4&&a.action==='approve').length} of 2. The same BOD cannot approve twice.</p>
 {run.canAct&&<form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();void action('approve');}}><label className="block">Review / decision reference<textarea required minLength={3} maxLength={1000} className={input} value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/></label><div className="flex flex-wrap gap-3"><Button disabled={busy||reason.trim().length<3}>Approve {approvalStages[run.step]}</Button><Button type="button" variant="secondary" disabled={busy||reason.trim().length<3} onClick={()=>void action('return')}>Return for revision</Button></div></form>}
 {!run.canAct&&!run.paid&&run.step<6&&<p className="mt-3 text-sm">Action is available only to the current eligible reviewer. Preparers and material PR editors cannot approve their own version.</p>}</Card>
 <Card title="Private payroll preview"><p className="mb-3 text-sm">Internal review only. This preview is not an employee payslip or proof of payment.</p><p>Period {run.source.from}–{run.source.to} · payday {run.source.payDate} · version {run.source.version}</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{[['Gross',run.source.gross],['Employee deductions',run.source.deductions],['Net',run.source.net]].map(([label,value])=><div key={label}><p>{label}</p><strong>PHP {value}</strong></div>)}</div>{run.source.employees.map(e=><details key={e.employeeId} className="mt-3 border-t pt-3"><summary>{e.employeeName} · PHP {e.net}</summary><p className="my-2">Gross {e.gross} − deductions {e.deductions} = net {e.net}. Tax {e.tax}.</p>{e.lines.map((l,i)=><p className="text-sm" key={i}>{l.label}: PHP {l.remaining??l.amount}</p>)}</details>)}<p className="mt-3 text-sm">Submission: {run.reference}. Payroll contact: {run.contact}.</p></Card>
 <Card title="Finance disbursement & payslip release">{run.paid?<p>Confirmed disbursement recorded. Employees can open their own released payslip.</p>:<><p>Release requires both BOD approvals on the current live version and Finance confirmation of actual full payment. A preview, approval or file download never means Paid. Partial, failed, returned and special-pay settlements remain in the Phase 8 payment process.</p>{run.canDisburse&&run.source.kind==='regular'?<form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();void paid();}}><label className="block">Actual payment reference<input className={input} value={ref} onChange={e=>setRef(e.target.value)} required minLength={3} disabled={busy}/></label><label className="block">Actual paid date<input type="date" className={input} value={paidDate} onChange={e=>setPaidDate(e.target.value)} required disabled={busy}/></label><label className="block">Actual full amount (PHP)<input className={input} value={amount} onChange={e=>setAmount(e.target.value)} required disabled={busy}/></label><Button disabled={busy}>Record confirmed payment & release private payslips</Button></form>:<p className="mt-3 font-medium">Payment and employee payslip release are blocked.</p>}</>}</Card></>}
 </div>;
}
