import React,{useCallback,useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import {useAuth} from '../../hooks/useAuth';
import {phaseChecklist} from './phaseChecklist';
import {fetchTimeContext,previewTime,saveTime,submitTime,fetchTimePackage,recordTimeRules,recordTimeHoliday,openOffsetReview,reviewOffset,fetchOffsetReviews,TimeScope,TimePreview,TimeRow,TimeRuleConfig,OffsetReview} from './attendanceReadiness';

const inputClass='mt-1 block w-full rounded-md border border-gray-300 bg-white p-2 text-gray-900 dark:border-slate-600 dark:bg-slate-800 dark:text-white';
const minutes=(value:number)=>Number(value).toLocaleString('en-PH',{maximumFractionDigits:4});
const TextField:React.FC<{label:string;value:string;change:(v:string)=>void;type?:string;required?:boolean}>=({label,value,change,type='text',required})=><label className="block text-sm font-medium">{label}<input className={inputClass} type={type} value={value} onChange={e=>change(e.target.value)} required={required} maxLength={1000}/></label>;

export default function AttendanceReadinessPage(){
 const {user}=useAuth();const [scopes,setScopes]=useState<TimeScope[]>([]);const [scopeId,setScopeId]=useState('');
 const [from,setFrom]=useState('');const [to,setTo]=useState('');const [preview,setPreview]=useState<TimePreview|null>(null);
 const [offsets,setOffsets]=useState<OffsetReview[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const [showAll,setShowAll]=useState(false);
 const [history,setHistory]=useState<Awaited<ReturnType<typeof fetchTimePackage>>|null>(null);const seq=useRef(0);const scope=scopes.find(s=>s.id===scopeId);
 const loadContext=useCallback(async()=>{const n=++seq.current;setPreview(null);setHistory(null);setScopes([]);setOffsets([]);try{const [context,reviews]=await Promise.all([fetchTimeContext(),fetchOffsetReviews()]);if(n===seq.current){setScopes(context.scopes);setOffsets(reviews);}}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Readiness access could not be checked.');}},[user?.id]);
 useEffect(()=>{void loadContext();return()=>{++seq.current;};},[loadContext]);
 const refresh=async()=>{const n=++seq.current;setPreview(null);setHistory(null);setError('');setNotice('');setBusy(true);try{const result=await previewTime(scopeId,from,to);if(n===seq.current)setPreview(result);}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Review could not be loaded.');}finally{if(n===seq.current)setBusy(false);}};
 const mutate=async(action:()=>Promise<unknown>,success:string)=>{const n=++seq.current;setBusy(true);setError('');setNotice('');try{await action();if(n!==seq.current)return;setPreview(null);setHistory(null);const [next,reviews]=await Promise.all([previewTime(scopeId,from,to),fetchOffsetReviews()]);if(n===seq.current){setPreview(next);setOffsets(reviews);setNotice(success);}}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'The change could not be completed.');}finally{if(n===seq.current)setBusy(false);}};
 const openHistory=async(id:string)=>{const n=++seq.current;setHistory(null);try{const saved=await fetchTimePackage(id);if(n===seq.current)setHistory(saved);}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Saved details could not be loaded.');}};
 const rows=history?.result.rows||preview?.result.rows||[];const visible=showAll?rows:rows.filter(r=>!r.ready);
 return <div className="space-y-6 text-gray-800 dark:text-slate-200">
  <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Attendance Readiness</h1><p className="mt-1 text-sm">Check existing time records, resolve missing inputs and submit a saved timekeeping version to Finance.</p></div><span className="self-start rounded-full bg-amber-100 px-3 py-1 text-sm text-amber-900">Payroll processing off</span></div>
  <Card title="Your team's setup checklist"><p className="mb-3 text-sm">Start with the assigned payroll staff and actual dated schedules. You can read this checklist while those inputs are pending. Ordinary employees do not need staff payroll duties to receive pay.</p>
   <details open={!scope?.canView}><summary className="cursor-pointer font-medium">What your team needs for each phase</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Phase</th><th className="p-2">Owner</th><th className="p-2">Your team's task</th></tr></thead><tbody>{phaseChecklist.map(p=><tr key={p.phase} className="border-t border-gray-200 dark:border-slate-700"><td className="p-2 align-top font-medium whitespace-nowrap">{p.link?<Link className="text-indigo-600 dark:text-indigo-300" to={p.link}>{p.phase}</Link>:p.phase}</td><td className="p-2 align-top">{p.owner}</td><td className="p-2">{p.todo}</td></tr>)}</tbody></table></div></details>
  </Card>
  {error&&<p role="alert" className="rounded border border-red-300 p-3 text-red-700 dark:text-red-300">{error}</p>}{notice&&<p role="status" className="text-green-700 dark:text-green-300">{notice}</p>}
  <Card title="Choose a business unit and cutoff"><div className="grid gap-4 sm:grid-cols-3"><label className="block text-sm font-medium">Business unit<select className={inputClass} value={scopeId} onChange={e=>{++seq.current;setScopeId(e.target.value);setPreview(null);setHistory(null);setBusy(false);}}><option value="">Choose a business unit</option>{scopes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><TextField label="From (inclusive)" type="date" value={from} change={v=>{++seq.current;setFrom(v);setPreview(null);setHistory(null);setBusy(false);}}/><TextField label="To (inclusive, maximum 31 days)" type="date" value={to} change={v=>{++seq.current;setTo(v);setPreview(null);setHistory(null);setBusy(false);}}/></div>
  {!scope?.canView?<p className="mt-4 text-sm">Attendance review needs an assigned payroll/timekeeping duty and your existing HRIS Timekeeping permission. Access management alone does not grant attendance or salary work. <Link className="font-medium text-indigo-600 dark:text-indigo-300" to="/payroll/access">Assign the intended staff in Payroll Access.</Link></p>:<Button className="mt-4" disabled={busy||!from||!to||to<from} onClick={()=>void refresh()}>Check attendance readiness</Button>}
  <p className="mt-4 text-sm">Managers enter shifts and explicit rest days in <Link className="text-indigo-600 dark:text-indigo-300" to="/payroll/timekeeping">Timekeeping</Link>. Check punches in <Link className="text-indigo-600 dark:text-indigo-300" to="/payroll/clock-log">Clock Log</Link> and approvals in <Link className="text-indigo-600 dark:text-indigo-300" to="/payroll/overtime">Overtime Requests</Link> and <Link className="text-indigo-600 dark:text-indigo-300" to="/payroll/leave">Leave</Link>. A blank roster never means an absence.</p></Card>
  {preview&&<>
   <Card title="Readiness result"><p>{preview.result.totalDays} employee-days checked · <strong>{preview.result.blockedDays} blocked</strong>. {preview.result.totalDays===0?'No employees fall within this BU/date range.':preview.result.blockedDays?'Resolve the listed inputs through their existing authorized workflows, then refresh.':'No listed attendance blockers. HR can save and submit the completed period.'}</p>
   <p className="mt-2 text-sm">This review does not calculate pay, post leave/offset balances or approve the Payroll Register.</p>
   {scope?.canFinalize&&<div className="mt-4 space-y-3"><TextField label="Review / correction reason and supporting reference" value={reason} change={setReason}/><Button disabled={busy||reason.trim().length<3||!preview.result.totalDays} onClick={()=>void mutate(()=>saveTime(scopeId,from,to,preview.sourceHash,reason),'Timekeeping version saved. Prior versions remain visible.')}>Save review version</Button></div>}
   </Card>
   <Card title={history?`Saved version ${history.version} · ${history.status}${history.current?'':' · sources have changed'}`:'Employee-day details'}>
    {history&&<Button variant="secondary" size="sm" onClick={()=>setHistory(null)}>Back to current review</Button>}
    <label className="my-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/>Show ready days too</label>
    {visible.length===0?<p>No blocked days in this view.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Employee / date','Scheduled / worked minutes','Late / undertime','Approved / actual OT','Needs attention'].map(h=><th key={h} className="p-2 align-top">{h}</th>)}</tr></thead><tbody>{visible.map(row=><TimeDay key={`${row.employeeId}-${row.date}`} row={row} canOpenOffset={Boolean(scope?.canFinalize&&!history)} busy={busy} onOpen={id=>void mutate(()=>openOffsetReview(id,reason),'Offset review opened for HR → GM → two BOD approvals.')} hasReason={reason.trim().length>=3}/>)}</tbody></table></div>}
   </Card>
   <Card title="Saved versions and HR submission"><p className="mb-3 text-sm">Finance reads the submitted version here. Any later source change marks it out of date; HR must save and submit a linked new version. The payroll calculation phase must check this version again before use.</p>{preview.packages.length===0?<p>No saved versions for these dates.</p>:preview.packages.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 border-t py-3 dark:border-slate-700"><div><p className="font-medium">Version {p.version} · {p.status} · {p.current?'current inputs':'inputs changed'}</p><p className="text-sm">{p.reason}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" size="sm" disabled={busy} onClick={()=>{void openHistory(p.id);}}>View saved details</Button>{scope?.canFinalize&&p.status==='draft'&&<Button size="sm" disabled={busy||!p.current||p.blockedDays>0} onClick={()=>void mutate(()=>submitTime(p.id),'HR submitted this timekeeping version to Finance. Payroll remains off.')}>Submit to Finance</Button>}</div></div>)}</Card>
   {scope?.canConfigure&&<RulesCard key={`${scopeId}-${from}-${to}`} scopeId={scopeId} from={from} to={to} preview={preview} busy={busy} mutate={mutate}/>}
  </>}
  {offsets.length>0&&<Card title="Manager offset approvals"><p className="mb-3 text-sm">HR Manager → General Manager → two distinct BOD users. This records approved work minutes; existing balance conversion still needs reconciliation against the approved policy. Salary access is separate.</p>{offsets.map(o=><OffsetCard key={o.id} review={o} refresh={loadContext}/>)}</Card>}
 </div>;
}

const TimeDay:React.FC<{row:TimeRow;canOpenOffset:boolean;busy:boolean;onOpen:(id:string)=>void;hasReason:boolean}>=({row,canOpenOffset,busy,onOpen,hasReason})=>{
 return <tr className="border-t border-gray-200 dark:border-slate-700"><td className="p-2 align-top"><p className="font-medium">{row.employeeName}</p><p>{row.date}</p><p className="text-xs">{row.restDay?'Rest day':row.approvedFullLeave?'Approved leave':'Scheduled work'}{row.holiday?' · holiday':''}</p></td><td className="p-2 align-top">{minutes(row.scheduledMinutes)} / {minutes(row.actualMinutes)}<p className="text-xs">Break: {minutes(row.breakMinutes)}{row.workedLunch?' · worked lunch approved':''}</p></td><td className="p-2 align-top">{minutes(row.lateMinutes)} / {minutes(row.undertimeMinutes)}</td><td className="p-2 align-top">{minutes(row.approvedOtMinutes)} / {minutes(row.actualOtMinutes)}</td><td className="p-2 align-top">{row.ready?<span className="text-green-700 dark:text-green-300">Ready for attendance submission</span>:<ul className="list-disc pl-4">{row.issues.map(i=><li key={i}>{i}</li>)}</ul>}<details className="mt-2"><summary className="cursor-pointer">Source references</summary><p className="break-all text-xs">Shifts: {row.shiftIds.join(', ')||'missing'}<br/>Punches: {row.eventIds.join(', ')||'missing'}<br/>Leave: {row.leaveIds.join(', ')||'none'}</p>{row.segments.map((s,i)=><p className="text-xs" key={i}>{s.date}: {new Date(s.start).toLocaleTimeString('en-PH',{timeZone:'Asia/Manila'})}–{new Date(s.end).toLocaleTimeString('en-PH',{timeZone:'Asia/Manila'})}</p>)}</details>{canOpenOffset&&row.ot.filter(o=>o.type==='Offset'&&o.status==='Approved').map(o=><Button key={o.id} className="mt-2" size="sm" variant="secondary" disabled={busy||!hasReason} onClick={()=>onOpen(o.id)}>Open offset approval review</Button>)}</td></tr>;
}

const RulesCard:React.FC<{scopeId:string;from:string;to:string;preview:TimePreview;busy:boolean;mutate:(fn:()=>Promise<unknown>,message:string)=>Promise<void>}>=({scopeId,from,to,preview,busy,mutate})=>{
 const [config,setConfig]=useState<TimeRuleConfig>(preview.rules[0]?.config||{restTemplates:[],meals:{},holidayCoverageConfirmed:false,splitShiftConfirmed:false,leavePolicyRef:'',offsetPolicyRef:''});const [source,setSource]=useState('');const [holidayDate,setHolidayDate]=useState('');const [holidayName,setHolidayName]=useState('');const [holidayKind,setHolidayKind]=useState('regular');const [holidaySource,setHolidaySource]=useState('');const [replaces,setReplaces]=useState('');
 return <Card title="Approved attendance references"><p className="text-sm">These references apply to the selected date range. The confirmed five-minute grace is excluded, lunch is one unpaid hour, and the OT minimum is one hour. Unsettled treatment stays blocked. Existing leave balances are reused.</p>
 {preview.rules.map(r=><p key={r.id} className="mt-2 text-sm">{r.effective_from}–{r.effective_to}: {r.source_ref}</p>)}
 <details className="mt-4"><summary className="cursor-pointer font-medium">Record a reviewed rule version</summary><form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();void mutate(()=>recordTimeRules(scopeId,from,to,config,source),'Reviewed attendance references recorded. Refresh reflects the new version.');}}><fieldset disabled={busy} className="space-y-3"><label className="flex gap-2 text-sm"><input type="checkbox" checked={config.holidayCoverageConfirmed} onChange={e=>setConfig({...config,holidayCoverageConfirmed:e.target.checked})}/>Holiday coverage, including local holidays and overnight boundaries, checked for these dates</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={config.splitShiftConfirmed} onChange={e=>setConfig({...config,splitShiftConfirmed:e.target.checked})}/>Split-shift gaps represent the unpaid break and must not be deducted twice</label>
 <p className="text-sm font-medium">Identify rest-day presets and prescribed meal start times</p>{preview.templates.map(t=><div key={t.id} className="grid gap-2 rounded border p-3 sm:grid-cols-2 dark:border-slate-700"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={config.restTemplates.includes(t.id)} onChange={e=>setConfig({...config,restTemplates:e.target.checked?[...config.restTemplates,t.id]:config.restTemplates.filter(id=>id!==t.id)})}/>{t.name} is an explicit rest-day preset</label><TextField label={`${t.name}: prescribed meal start (only where supported)`} type="time" value={config.meals[t.id]||''} change={v=>setConfig({...config,meals:Object.fromEntries(Object.entries({...config.meals,[t.id]:v}).filter(([,time])=>time))})}/></div>)}
 <TextField label="Approved leave accrual / regularization policy reference (if settled)" value={config.leavePolicyRef||''} change={v=>setConfig({...config,leavePolicyRef:v})}/><TextField label="Approved offset conversion / balance reconciliation reference (if settled)" value={config.offsetPolicyRef||''} change={v=>setConfig({...config,offsetPolicyRef:v})}/><TextField label="Supporting policy and review reference" value={source} change={setSource} required/><Button type="submit" disabled={source.trim().length<3}>Record reviewed rules</Button></fieldset></form></details>
 <details className="mt-4"><summary className="cursor-pointer font-medium">Record a missing local holiday / corrected classification</summary><form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();void mutate(()=>recordTimeHoliday(scopeId,holidayDate,holidayName,holidayKind,holidaySource,replaces||null),'Holiday reference recorded for this business unit.');}}><fieldset disabled={busy} className="space-y-3"><TextField label="Holiday date" type="date" value={holidayDate} change={setHolidayDate} required/><TextField label="Holiday name" value={holidayName} change={setHolidayName} required/><label className="block text-sm">Classification<select className={inputClass} value={holidayKind} onChange={e=>setHolidayKind(e.target.value)}><option value="regular">Regular holiday</option><option value="special_nonworking">Special non-working</option><option value="special_working">Special working</option><option value="double_regular">Double regular holiday</option></select></label><TextField label="Official / approved source reference" value={holidaySource} change={setHolidaySource} required/><label className="block text-sm">Correct an existing local holiday<select className={inputClass} value={replaces} onChange={e=>setReplaces(e.target.value)}><option value="">New holiday reference</option>{preview.holidays.filter(h=>h.source!=="Existing HRIS holiday"&&h.date===holidayDate).map(h=><option key={h.id} value={h.id}>{h.date} · {h.name} · {h.kind}</option>)}</select></label><Button type="submit" disabled={holidayName.trim().length<3||holidaySource.trim().length<3}>Record holiday reference</Button></fieldset></form></details>
 </Card>;
}
const OffsetCard:React.FC<{review:OffsetReview;refresh:()=>Promise<void>}>=({review,refresh})=>{
 const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const rejected=review.actions.some(a=>a.decision==='reject');const bodCount=review.actions.filter(a=>a.stage==='bod'&&a.decision==='approve').length;
 const act=async(approve:boolean)=>{setBusy(true);setError('');try{await reviewOffset(review.id,approve,reason);await refresh();}catch(e){setError(e instanceof Error?e.message:'Offset review failed.');}finally{setBusy(false);}};
 return <div className="space-y-3 border-t py-4 dark:border-slate-700"><p className="font-medium">{review.employeeName} · {review.date} · {minutes(review.minutes)} minutes</p><p>{!review.current?'Source changed — new review required':rejected?'Rejected':review.complete?'Approved by HR, GM and two BOD users':`${bodCount} of 2 BOD approvals`}</p><p className="text-sm">{review.actions.map(a=>`${a.stage.toUpperCase()}: ${a.decision}`).join(' → ')||'Awaiting HR Manager review'}</p>{error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}{review.current&&!review.complete&&!rejected&&!review.isSelf&&<><TextField label="Approval / rejection reason" value={reason} change={setReason}/><Button disabled={busy||reason.trim().length<3} onClick={()=>void act(true)}>Approve current stage</Button><Button className="ml-2" variant="secondary" disabled={busy||reason.trim().length<3} onClick={()=>void act(false)}>Reject</Button></>}</div>;
}
