import ProcessingModeBadge from './ProcessingModeBadge';
import {usePayrollField} from './usePayrollSelection';
import React,{useCallback,useEffect,useRef,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import {useAuth} from '../../hooks/useAuth';
import PhaseChecklist from './PhaseChecklist';
import {validCutoff} from './workspace';
import {TimekeepingEmployeeTable} from './TimekeepingEmployeeTable';
import {fetchTimeContext,previewTime,saveTime,submitTime,fetchTimePackage,recordTimeRules,recordTimeHoliday,openOffsetReview,reviewOffset,fetchOffsetReviews,fetchTimeTestEvidence,TimeScope,TimePreview,TimeRuleConfig,OffsetReview,TestTimeEvidence} from './attendanceReadiness';

const inputClass='mt-1 block w-full rounded-md border border-gray-300 bg-white p-2 text-gray-900 dark:border-slate-600 dark:bg-slate-800 dark:text-white';
const minutes=(value:number)=>Number(value).toLocaleString('en-PH',{maximumFractionDigits:4});
const TextField:React.FC<{label:string;value:string;change:(v:string)=>void;type?:string;required?:boolean}>=({label,value,change,type='text',required})=><label className="block text-sm font-medium">{label}<input className={inputClass} type={type} value={value} onChange={e=>change(e.target.value)} required={required} maxLength={1000}/></label>;

export default function AttendanceReadinessPage(){
 const {user}=useAuth();const [scopeId,setScopeId]=usePayrollField('scope');const [from,setFrom]=usePayrollField('from');const [to,setTo]=usePayrollField('to');
 return <ReviewWorkspace key={`${user?.id}:${scopeId}:${from}:${to}`} scopeId={scopeId} from={from} to={to} setScopeId={setScopeId} setFrom={setFrom} setTo={setTo}/>;
}
const ReviewWorkspace:React.FC<{scopeId:string;from:string;to:string;setScopeId:(v:string)=>void;setFrom:(v:string)=>void;setTo:(v:string)=>void}>=({scopeId,from,to,setScopeId,setFrom,setTo})=>{
 const location=useLocation();const [scopes,setScopes]=useState<TimeScope[]>([]);const [contextRetry,setContextRetry]=useState(0);const [contextError,setContextError]=useState('');
 const [preview,setPreview]=useState<TimePreview|null>(null);const [history,setHistory]=useState<Awaited<ReturnType<typeof fetchTimePackage>>|null>(null);
 const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const seq=useRef(0);const writeLock=useRef(false);
 const [showTest,setShowTest]=useState(false);const [test,setTest]=useState<TestTimeEvidence[]>([]);const [testError,setTestError]=useState('');const [testBusy,setTestBusy]=useState(false);const [testRetry,setTestRetry]=useState(0);
 const [offsets,setOffsets]=useState<OffsetReview[]>([]);const [offsetBusy,setOffsetBusy]=useState(false);const [offsetError,setOffsetError]=useState('');const alive=useRef(true);
 const scope=scopes.find(s=>s.id===scopeId);const valid=validCutoff(from,to);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;++seq.current;};},[]);
 useEffect(()=>{let active=true;setContextError('');fetchTimeContext().then(c=>{if(active)setScopes(c.scopes);}).catch(e=>{if(active)setContextError(e.message);});return()=>{active=false;};},[contextRetry]);
 const refresh=useCallback(async()=>{if(writeLock.current)return;const n=++seq.current;setPreview(null);setHistory(null);setError('');setBusy(true);setTestRetry(v=>v+1);try{const result=await previewTime(scopeId,from,to);if(n===seq.current)setPreview(result);}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Review could not be loaded.');}finally{if(n===seq.current)setBusy(false);}},[scopeId,from,to]);
 useEffect(()=>{if(scope?.canView&&valid)void refresh();},[scope?.canView,valid,refresh]);
 useEffect(()=>{let active=true;setTest([]);setTestError('');if(!showTest||!scope?.canView||!valid)return;setTestBusy(true);fetchTimeTestEvidence(scopeId,from,to).then(r=>{if(active)setTest(r);}).catch(e=>{if(active)setTestError(e.message);}).finally(()=>{if(active)setTestBusy(false);});return()=>{active=false;};},[showTest,scope?.canView,scopeId,from,to,valid,testRetry]);
 const loadOffsets=async()=>{setOffsetBusy(true);setOffsetError('');try{const result=await fetchOffsetReviews();if(alive.current)setOffsets(result.filter(o=>o.scopeId===scopeId&&o.date>=from&&o.date<=to));}catch(e){if(alive.current)setOffsetError(e instanceof Error?e.message:'Offset reviews unavailable.');}finally{if(alive.current)setOffsetBusy(false);}};
 const mutate=async(action:()=>Promise<unknown>,success:string)=>{if(writeLock.current)return;writeLock.current=true;const n=++seq.current;setBusy(true);setError('');setNotice('');try{await action();if(n!==seq.current)return;setPreview(null);setHistory(null);const next=await previewTime(scopeId,from,to);if(n===seq.current){setPreview(next);setNotice(success);}}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'The change could not be completed. Refresh before retrying.');}finally{writeLock.current=false;if(n===seq.current)setBusy(false);}};
 const openHistory=async(id:string)=>{if(writeLock.current)return;const n=++seq.current;setHistory(null);setError('');setBusy(true);try{const saved=await fetchTimePackage(id);if(n===seq.current)setHistory(saved);}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Saved details could not be loaded.');}finally{if(n===seq.current)setBusy(false);}};
 const rows=history?.result.rows||preview?.result.rows||[];
 const canSave=!!preview&&preview.result.totalDays>0&&preview.result.blockedDays===0&&preview.result.rows.length===preview.result.totalDays&&preview.result.rows.every(r=>r.ready&&r.issues.length===0);
 return <main className="space-y-6 text-gray-800 dark:text-slate-200">
  <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Timekeeping Review</h1><p className="mt-1 text-sm">Review one Business Unit and cutoff, resolve exceptions, then save and submit the verified version to Finance.</p></div><ProcessingModeBadge scopeId={scopeId}/></div>
  {contextError&&<div role="alert"><p>{contextError}</p><Button variant="secondary" onClick={()=>setContextRetry(v=>v+1)}>Retry access check</Button></div>}
  {error&&<p role="alert" className="rounded border border-red-300 p-3 text-red-700 dark:text-red-300">{error}</p>}{notice&&<p role="status" className="text-green-700 dark:text-green-300">{notice}</p>}
  <Card title="Business Unit and cutoff"><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-3"><label className="block text-sm font-medium">Business Unit<select className={inputClass} value={scopeId} onChange={e=>setScopeId(e.target.value)}><option value="">Choose a Business Unit</option>{scopes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><TextField label="From (inclusive)" type="date" value={from} change={setFrom}/><TextField label="To (inclusive, maximum 31 days)" type="date" value={to} change={setTo}/></fieldset>
  {!scope?.canView?<p className="mt-4 text-sm">A scoped payroll/timekeeping duty and existing HRIS Timekeeping permission are required. <Link className="underline" to="/payroll/access">Manage Payroll Access</Link></p>:<Button className="mt-4" disabled={busy||!valid} onClick={()=>void refresh()}>{busy?'Loading review…':'Refresh review and saved versions'}</Button>}
  {!valid&&<p className="mt-3 text-sm">Choose valid cutoff dates covering at most 31 days.</p>}</Card>
  {preview&&<>
   <Card title="Cutoff readiness"><p><strong>{preview.result.totalDays} employee-days checked · {preview.result.blockedDays} blocked</strong>. {!preview.result.totalDays?'No employees fall within this BU/date range.':!canSave?'Resolve the listed inputs through their existing workflows, then refresh.':'Required attendance checks passed. Authorized HR may save and submit this cutoff.'}</p><p className="mt-2 text-sm">Saving creates a review version. Submitting hands that version to Finance. Neither action approves payroll or releases payment. Schedule publication and request approvals remain separate.</p></Card>
   <Card title={history?`Saved version ${history.version} · ${history.status}${history.current?' · current sources':' · sources changed'}`:'Employee cutoff review'}>
    {history?<div className="mb-4 space-y-2"><p>Showing the saved totals and original evidence. Later corrections do not rewrite this version.</p><Button variant="secondary" size="sm" disabled={busy} onClick={()=>setHistory(null)}>Back to current review</Button></div>:<div className="mb-4 space-y-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={showTest} onChange={e=>setShowTest(e.target.checked)}/>Show documented historical test evidence alongside live attendance</label>{testBusy&&<p role="status">Loading historical sources…</p>}{testError&&<div role="alert"><p className="text-red-700">Historical evidence unavailable: {testError}</p><Button size="sm" variant="secondary" onClick={()=>setTestRetry(v=>v+1)}>Retry evidence</Button></div>}{showTest&&!testBusy&&!testError&&!test.length&&<p className="text-sm">No committed historical test records in this cutoff. <Link className="underline" to="/payroll/historical-attendance">Import historical attendance</Link></p>}</div>}
    <TimekeepingEmployeeTable key={history?.id||'current'} rows={rows} test={!history&&showTest?test:[]} saved={!!history} canOpenOffset={!!scope?.canFinalize} busy={busy} hasReason={reason.trim().length>=3} onOpenOffset={id=>void mutate(()=>openOffsetReview(id,reason),'Offset review opened; complete the existing HR → GM → BOD approval process.')}/>
   </Card>
   <Card title="Save and submit timekeeping"><p className="mb-3 text-sm">Only an assigned HR timekeeping finalizer may save or submit. The server rechecks blockers, permissions and source changes. Prior versions and original evidence remain available.</p>
    {scope?.canFinalize&&!history&&<div className="mb-5 space-y-3"><TextField label="Review / correction reason and supporting reference" value={reason} change={setReason}/><Button disabled={busy||reason.trim().length<3||!canSave} onClick={()=>void mutate(()=>saveTime(scopeId,from,to,preview.sourceHash,reason),'Review version saved and reloaded from the server. Submit it below when ready.')}>Save verified review version</Button>{!canSave&&<p className="text-sm">Save and submission stay blocked until the required checks pass.</p>}</div>}
    {preview.packages.length===0?<p>No saved versions for this cutoff.</p>:preview.packages.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 border-t py-3 dark:border-slate-700"><div><p className="font-medium">Version {p.version} · {p.status==='submitted'?'Submitted to Finance':'Saved — not submitted'} · {p.current?'current inputs':'inputs changed — new review required'}</p><p className="text-sm">{p.reason}</p>{p.previousId&&<p className="text-xs">Linked to a prior version</p>}</div><div className="flex flex-wrap gap-2"><Button variant="secondary" size="sm" disabled={busy} onClick={()=>void openHistory(p.id)}>View saved evidence</Button>{scope?.canFinalize&&p.status==='draft'&&<Button size="sm" disabled={busy||!p.current||p.blockedDays!==0||!canSave} onClick={()=>void mutate(()=>submitTime(p.id),'Timekeeping version submitted to Finance and reloaded from the server.')}>Submit to Finance</Button>}</div></div>)}
   </Card>
   <section id="attendance-references">{scope?.canConfigure&&<RulesCard key={`${scopeId}-${from}-${to}-${preview.sourceHash}`} scopeId={scopeId} from={from} to={to} preview={preview} busy={busy} mutate={mutate}/>}</section>
   <details id="offset-approvals" open={location.hash==='#offset-approvals'?true:undefined} className="rounded-xl border p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">Offset approvals for this cutoff</summary><p className="my-3 text-sm">Existing HR Manager → General Manager → two distinct BOD approvals. Approval authority is checked on the server.</p><Button size="sm" variant="secondary" disabled={offsetBusy||busy} onClick={()=>void loadOffsets()}>{offsetBusy?'Loading…':'Load cutoff offset reviews'}</Button>{offsetError&&<p role="alert">{offsetError}</p>}{offsets.map(o=><OffsetCard key={o.id} review={o} refresh={async()=>{await loadOffsets();await refresh();}}/>)}</details>
  </>}
  <details id="team-checklist" open={location.hash==='#team-checklist'?true:undefined} className="rounded-xl border p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">Team setup checklist</summary><PhaseChecklist/></details>
 </main>;
};

const RulesCard:React.FC<{scopeId:string;from:string;to:string;preview:TimePreview;busy:boolean;mutate:(fn:()=>Promise<unknown>,message:string)=>Promise<void>}>=({scopeId,from,to,preview,busy,mutate})=>{
 const [config,setConfig]=useState<TimeRuleConfig>(preview.rules[0]?.config||{restTemplates:[],meals:{},holidayCoverageConfirmed:false,splitShiftConfirmed:false,leavePolicyRef:'',offsetPolicyRef:''});const [source,setSource]=useState('');const [holidayDate,setHolidayDate]=useState('');const [holidayName,setHolidayName]=useState('');const [holidayKind,setHolidayKind]=useState('regular');const [holidaySource,setHolidaySource]=useState('');const [replaces,setReplaces]=useState('');
 return <Card title="Approved attendance references"><p className="text-sm">These references apply to the selected date range. The confirmed five-minute grace is excluded, lunch is one unpaid hour, and the OT minimum is one hour. Unsettled treatment stays blocked. Existing leave balances are reused.</p>
 {preview.rules.map(r=><p key={r.id} className="mt-2 text-sm">{r.effective_from}–{r.effective_to}: {r.source_ref}</p>)}
 <details className="mt-4"><summary className="cursor-pointer font-medium">Record a reviewed rule version</summary><form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();void mutate(()=>recordTimeRules(scopeId,from,to,config,source),'Reviewed attendance references recorded. Refresh reflects the new version.');}}><fieldset disabled={busy} className="space-y-3"><label className="flex gap-2 text-sm"><input type="checkbox" checked={config.holidayCoverageConfirmed} onChange={e=>setConfig({...config,holidayCoverageConfirmed:e.target.checked})}/>Holiday coverage, including local holidays and overnight boundaries, checked for these dates</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={config.splitShiftConfirmed} onChange={e=>setConfig({...config,splitShiftConfirmed:e.target.checked})}/>Split-shift gaps represent the unpaid break and must not be deducted twice</label>
 <p className="text-sm font-medium">Identify rest-day presets and prescribed meal start times</p>{preview.templates.map(t=><div key={t.id} className="grid gap-2 rounded border p-3 sm:grid-cols-2 dark:border-slate-700"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={config.restTemplates.includes(t.id)} onChange={e=>setConfig({...config,restTemplates:e.target.checked?[...config.restTemplates,t.id]:config.restTemplates.filter(id=>id!==t.id)})}/>{t.name} is an explicit rest-day preset</label><TextField label={`${t.name}: prescribed meal start (only where supported)`} type="time" value={config.meals[t.id]||''} change={v=>setConfig({...config,meals:Object.fromEntries(Object.entries({...config.meals,[t.id]:v}).filter(([,time])=>time))})}/></div>)}
 <TextField label="Approved leave accrual / regularization policy reference (if settled)" value={config.leavePolicyRef||''} change={v=>setConfig({...config,leavePolicyRef:v})}/><TextField label="Approved offset conversion / balance reconciliation reference (if settled)" value={config.offsetPolicyRef||''} change={v=>setConfig({...config,offsetPolicyRef:v})}/><TextField label="Supporting policy and review reference" value={source} change={setSource} required/><Button type="submit" disabled={source.trim().length<3}>Record reviewed rules</Button></fieldset></form></details>
 <details className="mt-4"><summary className="cursor-pointer font-medium">Record a missing local holiday / corrected classification</summary><form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();void mutate(()=>recordTimeHoliday(scopeId,holidayDate,holidayName,holidayKind,holidaySource,replaces||null),'Holiday reference recorded for this business unit.');}}><fieldset disabled={busy} className="space-y-3"><TextField label="Holiday date" type="date" value={holidayDate} change={setHolidayDate} required/><TextField label="Holiday name" value={holidayName} change={setHolidayName} required/><label className="block text-sm">Classification<select className={inputClass} value={holidayKind} onChange={e=>setHolidayKind(e.target.value)}><option value="regular">Regular holiday</option><option value="special_nonworking">Special non-working</option><option value="special_working">Special working</option><option value="double_regular">Double regular holiday</option></select></label><TextField label="Official / approved source reference" value={holidaySource} change={setHolidaySource} required/><label className="block text-sm">Correct an existing local holiday<select className={inputClass} value={replaces} onChange={e=>setReplaces(e.target.value)}><option value="">New holiday reference</option>{preview.holidays.filter(h=>h.source!=="Existing HRIS holiday"&&h.date===holidayDate).map(h=><option key={h.id} value={h.id}>{h.date} · {h.name} · {h.kind}</option>)}</select></label><Button type="submit" disabled={holidayName.trim().length<3||holidaySource.trim().length<3}>Record holiday reference</Button></fieldset></form></details>
 </Card>;
}
const OffsetCard:React.FC<{review:OffsetReview;refresh:()=>Promise<void>}>=({review,refresh})=>{
 const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const rejected=review.actions.some(a=>a.decision==='reject');const bodCount=review.actions.filter(a=>a.stage==='bod'&&a.decision==='approve').length;
 const act=async(approve:boolean)=>{setBusy(true);setError('');try{await reviewOffset(review.id,approve,reason);await refresh();}catch(e){setError(e instanceof Error?e.message:'Offset review failed.');}finally{setBusy(false);}};
 return <div className="space-y-3 border-t py-4 dark:border-slate-700"><p className="font-medium">{review.employeeName} · {review.date} · {minutes(review.minutes)} minutes</p><p>{!review.current?'Source changed — new review required':rejected?'Rejected':review.complete?'Approved by HR, GM and two BOD users':`${bodCount} of 2 BOD approvals`}</p><p className="text-sm">{review.actions.map(a=>`${a.stage.toUpperCase()}: ${a.decision}`).join(' → ')||'Awaiting HR Manager review'}</p>{error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}{review.current&&!review.complete&&!rejected&&!review.isSelf&&<><TextField label="Approval / rejection reason" value={reason} change={setReason}/><Button disabled={busy||reason.trim().length<3} onClick={()=>void act(true)}>Approve current stage</Button><Button className="ml-2" variant="secondary" disabled={busy||reason.trim().length<3} onClick={()=>void act(false)}>Reject</Button></>}</div>;
}
