import {supabase} from '../../services/supabaseClient';
import type {CompareInput,CompareTemplate} from './pilot';
import type {DifferenceRow} from './calculationModel';
export type CalculationWorkspaceData={scopeId:string;from:string;to:string;mode:string;grossId:string|null;netId:string|null;grossCurrent:boolean|null;netCurrent:boolean|null;canCompare:boolean;blockers:string[];employees:{employeeId:string;employeeName:string;missingSalaryDates:string[];salarySources:string[];deductionSource:string|null;openingSource:string|null;issues:string[]}[];previousCutoff:null|{id:string;from:string;to:string;version:number};linkedPreviousNet:string|null;grossRuns:{id:string;version:number}[];netRuns:{id:string;version:number}[];adjacentCutoffs:{from:string;to:string;version:number}[]};
export type CalculationComparisonData={template:CompareTemplate;current:boolean;staleReason:string|null;canSave:boolean;revisions:{id:string;createdAt:string;sourceRef:string;coverageRef:string;rows:DifferenceRow[]}[]};
async function rpc<T>(name:string,args:Record<string,unknown>):Promise<T>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),25000);try{const {data,error}=await supabase.rpc(name,args).abortSignal(controller.signal);if(controller.signal.aborted)throw new Error('Review took too long. Refresh to retry; no automatic retry was started.');if(error)throw new Error(error.message);return data as T;}finally{clearTimeout(timer);}}
export const calculationWorkspace=(scope:string,from:string,to:string,grossId:string,netId:string)=>rpc<CalculationWorkspaceData>('get_payroll_calculation_workspace',{p_scope:scope,p_from:from,p_to:to,p_gross:grossId||null,p_net:netId||null});
export const calculationComparison=(id:string)=>rpc<CalculationComparisonData>('get_payroll_calculation_comparison',{p_net:id});
export const saveCalculationComparison=(t:CompareTemplate,input:CompareInput)=>rpc<string>('save_payroll_calculation_comparison',{p_net:t.runId,p_hash:t.sourceHash,p_input:input});
