import React,{useEffect,useState} from 'react';
import {supabase} from '../../services/supabaseClient';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
const input='block w-full mt-1 p-2 rounded border dark:bg-slate-800 dark:border-slate-600';
async function rpc(name:string,args:Record<string,unknown>){const {data,error}=await supabase.rpc(name,args);if(error)throw Error(error.message);return data;}
export function EmployeePolicyPanel({employeeId,canApprove}:{employeeId:string;canApprove:boolean}){
 const [data,setData]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [rule,setRule]=useState({from:'',to:'',compensationType:'Monthly',workweek:'',scheduledDays:'6',divisor:'313',rankAndFile:true,offsetEligible:false}),[ref,setRef]=useState('');
 useEffect(()=>{let active=true;setData(null);rpc('get_confirmed_payroll_policy',{p_employee:employeeId}).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[employeeId]);
 const field=(key:keyof typeof rule,label:string,type='text')=><label>{label}<input className={input} type={type} required value={String(rule[key])} onChange={e=>setRule({...rule,[key]:e.target.value})}/></label>;
 return <Card title="Employee payroll configuration"><p className="text-sm">Effective-dated compensation and workweek assessment. Unassessed employees remain OT-eligible. Daily-paid employees retain their approved daily rate.</p>{message&&<p role="status" className="mt-3">{message}</p>}{data?.employeeRules?.map((r:any)=><p key={r.id} className="mt-3 text-sm">{r.effective_from}–{r.effective_to} · {r.compensation_type} · {r.scheduled_days} days/week · divisor {r.divisor} · {r.offset_eligible?'Offset eligible / OT exempt':'OT eligible'} · {r.source_ref}</p>)}{canApprove&&<details className="mt-4"><summary>Record approved assessment</summary><form className="mt-3 space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await rpc('save_confirmed_employee_rule',{p_employee:employeeId,p_rule:rule,p_ref:ref});setData(await rpc('get_confirmed_payroll_policy',{p_employee:employeeId}));setMessage('Approved configuration version recorded.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2">{field('from','Effective start','date')}{field('to','Effective end (inclusive)','date')}<label>Compensation type<select className={input} value={rule.compensationType} onChange={e=>setRule({...rule,compensationType:e.target.value})}>{['Monthly','Daily','Hourly'].map(x=><option key={x}>{x}</option>)}</select></label>{field('workweek','Workweek configuration')}{field('scheduledDays','Scheduled workdays per week','number')}{field('divisor','Applicable annual divisor','number')}<label><input type="checkbox" checked={rule.rankAndFile} onChange={e=>setRule({...rule,rankAndFile:e.target.checked})}/> Rank-and-file assessment</label><label><input type="checkbox" checked={rule.offsetEligible} onChange={e=>setRule({...rule,offsetEligible:e.target.checked})}/> Formally assessed offset-eligible / OT-exempt</label><label>Approval / assessment reference<input className={input} required minLength={3} value={ref} onChange={e=>setRef(e.target.value)}/></label><Button type="submit">Record version</Button></fieldset></form></details>}</Card>;
}
export function BankingPolicyPanel({scopeId}:{scopeId:string}){
 const [day,setDay]=useState(''),[data,setData]=useState<any>(null),[ref,setRef]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[exception,setException]=useState(''),[open,setOpen]=useState(false);
 const refresh=()=>rpc('get_confirmed_payroll_policy',{p_scope:scopeId,p_payday:day||null}).then(setData);
 useEffect(()=>{let active=true;setData(null);rpc('get_confirmed_payroll_policy',{p_scope:scopeId,p_payday:day||null}).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[scopeId,day]);
 async function act(name:string,args:Record<string,unknown>){setBusy(true);try{await rpc(name,args);await refresh();setMessage('Bank calendar evidence recorded.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <Card title="Originating bank and advance payday"><p>{data?.policy?.bank_name} · {data?.policy?.bank_branch}</p><p className="text-sm">{data?.policy?.bank_address}</p><p className="mt-2 text-sm">Review bank processing cutoffs, BSP suspensions and local holidays. Both HR and Finance must confirm the calendar before disbursement.</p><fieldset disabled={busy} className="space-y-3 mt-3"><label>Scheduled payday<input className={input} type="date" value={day} onChange={e=>setDay(e.target.value)}/></label>{data?.bankingDay&&<p>Proposed banking date: <strong>{data.bankingDay}</strong></p>}<label>Bank calendar / processing reference<input className={input} value={ref} onChange={e=>setRef(e.target.value)} minLength={3}/></label><div className="flex flex-wrap gap-3">{['hr','finance'].map(stage=><Button key={stage} disabled={!day||ref.trim().length<3} onClick={()=>void act('confirm_payroll_banking_date',{p_scope:scopeId,p_day:day,p_stage:stage,p_ref:ref})}>{stage==='hr'?'HR':'Finance'} confirmation</Button>)}</div>{data?.bankConfirmations?.map((r:any)=><p key={r.id}>{r.stage.toUpperCase()} confirmed · {r.banking_day} · {r.source_ref}</p>)}<details><summary>Bank calendar exception</summary><label>Date<input className={input} type="date" value={exception} onChange={e=>setException(e.target.value)}/></label><label className="block my-3"><input type="checkbox" checked={open} onChange={e=>setOpen(e.target.checked)}/> Payroll processing available on this date</label><Button disabled={!exception||ref.trim().length<3} onClick={()=>void act('save_confirmed_bank_day',{p_day:exception,p_open:open,p_ref:ref})}>Record bank exception</Button></details></fieldset>{message&&<p role="status" className="mt-3">{message}</p>}</Card>;
}
export function CompensableWorkPanel({employees}:{employees:{id:string;name:string}[]}){
 const [employee,setEmployee]=useState(''),[date,setDate]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[kind,setKind]=useState('worked_lunch'),[ref,setRef]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <details className="rounded border p-4 dark:border-slate-700"><summary>Validate worked lunch or additional overtime</summary><p className="my-3 text-sm">The employee’s direct manager validates actual work. This creates review evidence for timekeeping; finalized periods still require the existing approved correction workflow.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await rpc('validate_compensable_work',{p_employee:employee,p_date:date,p_start:start,p_end:end,p_kind:kind,p_ref:ref});setMessage('Compensable work recorded for timekeeping review.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2"><label>Employee<select className={input} required value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">Choose employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Work date<input className={input} required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Start<input className={input} required type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End<input className={input} required type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Review type<select className={input} value={kind} onChange={e=>setKind(e.target.value)}><option value="worked_lunch">Worked lunch</option><option value="excess_ot">Actual OT beyond prior approval</option></select></label><label>Validation reason / evidence<input className={input} required minLength={3} value={ref} onChange={e=>setRef(e.target.value)}/></label><Button type="submit">Validate actual work</Button></fieldset></form>{message&&<p role="status">{message}</p>}</details>;
}
