import React,{useEffect,useMemo,useState} from 'react';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import {getDebtContext,peso,type DebtContext,type PayrollDebt} from './debts';

function ReviewDrawer({debt,onClose}:{debt:PayrollDebt;onClose:()=>void}){const authority=debt.documents.find(document=>document.is_primary)||debt.documents[0];return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40" role="dialog" aria-modal="true"><div className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl dark:bg-slate-900"><header className="flex justify-between"><div><h2 className="text-2xl font-bold">Review employee deductions</h2><p>{debt.employeeName}</p></div><button className="min-h-11 px-3 text-2xl" onClick={onClose} aria-label="Close">×</button></header><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Total balance',peso(debt.current_balance)],['This payroll',debt.status==='Active'?peso(Math.min(Number(debt.installment),Number(debt.current_balance))):'Excluded'],['Remaining after payroll',debt.status==='Active'?peso(Math.max(0,Number(debt.current_balance)-Number(debt.installment))):peso(debt.current_balance)]].map(([label,value])=><div className="rounded-xl bg-violet-50 p-3" key={label}><p className="text-xs">{label}</p><strong className="text-xl">{value}</strong></div>)}</div><section className="mt-5 rounded-2xl border p-4"><h3 className="font-bold">Loan or debt deduction</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2"><div><dt>Source</dt><dd>{debt.debt_source}</dd></div><div><dt>Original amount</dt><dd>{peso(debt.original_amount)}</dd></div><div><dt>Current balance</dt><dd>{peso(debt.current_balance)}</dd></div><div><dt>Deduction this cutoff</dt><dd>{debt.status==='Active'?peso(Math.min(Number(debt.installment),Number(debt.current_balance))):'Not included'}</dd></div><div><dt>Remaining cutoffs</dt><dd>{debt.remainingCutoffs}</dd></div><div><dt>Next deduction</dt><dd>{debt.nextDeductionDate||'—'}</dd></div><div><dt>Authority status</dt><dd>{authority?.status||'Missing'}</dd></div><div><dt>Finance approval</dt><dd>{debt.status}</dd></div></dl></section>{debt.status!=='Active'?<p className="mt-4 rounded-xl bg-amber-50 p-3 text-amber-900">Pending or unapproved records do not affect payroll.</p>:null}<h3 className="mt-5 font-bold">Audit history</h3>{debt.audit.map((entry,index)=><p className="mt-2 rounded-xl bg-slate-50 p-3 text-sm" key={`${entry.at}-${index}`}><strong>{entry.action}</strong> · {entry.actor}<br/>{entry.reason}</p>)}</div></div>}

export default function DebtApprovalPanel({scopeId,payrollDate,employees}:{scopeId:string;payrollDate:string;employees:{employeeId:string;employeeName:string;net:string}[]}){
 const [data,setData]=useState<DebtContext|null>(null);const [error,setError]=useState('');const [selected,setSelected]=useState<PayrollDebt|null>(null);
 useEffect(()=>{let active=true;setError('');void getDebtContext(scopeId,payrollDate).then(value=>{if(active)setData(value);}).catch(reason=>{if(active)setError((reason as Error).message);});return()=>{active=false;};},[scopeId,payrollDate]);
 const debts=useMemo(()=>data?.debts.filter(debt=>!['Cancelled','Completed','Paid or closed'].includes(debt.status))||[],[data]);const active=debts.filter(debt=>debt.status==='Active');const due=active.reduce((sum,debt)=>sum+Math.min(Number(debt.current_balance),Number(debt.installment)),0);
 return <><Card title="Employee loans & debt"><p className="mb-3 text-sm">Approved debt is visible during payroll review. Draft and pending records are never deducted.</p>{error?<p role="alert" className="text-red-700">{error}</p>:!data?<p role="status">Loading debt review…</p>:<><div className="grid gap-3 sm:grid-cols-4">{[['Active loans',active.length],['This payroll',peso(due)],['Employees with debt',new Set(debts.map(debt=>debt.employee_id)).size],['Needs review',debts.filter(debt=>debt.status!=='Active').length]].map(([label,value])=><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800" key={String(label)}><p className="text-xs text-slate-500">{label}</p><strong className="text-lg">{value}</strong></div>)}</div>{debts.length===0?<p className="mt-4">No active or pending employee debt for this payroll scope.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr>{['Employee','Net pay','Original balance','Remaining balance','This payroll deduction','Repayment term','Status','Review'].map(heading=><th className="p-2" key={heading}>{heading}</th>)}</tr></thead><tbody>{debts.map(debt=>{const employee=employees.find(item=>item.employeeId===debt.employee_id);const scheduled=debt.schedule.find(row=>row.payroll_date===payrollDate&&row.status==='Scheduled');return <tr className="border-t" key={debt.id}><td className="p-2">{debt.employeeName}</td><td className="p-2">{employee?peso(employee.net):'—'}</td><td className="p-2">{peso(debt.original_amount)}</td><td className="p-2 font-bold">{peso(debt.current_balance)}</td><td className="p-2">{debt.status==='Active'&&scheduled?peso(Math.min(Number(scheduled.scheduled_amount),Number(debt.current_balance))):'—'}</td><td className="p-2">{debt.remainingCutoffs} cutoffs left</td><td className="p-2">{debt.status}</td><td className="p-2"><Button size="sm" variant="secondary" onClick={()=>setSelected(debt)}>Review</Button></td></tr>;})}</tbody></table></div>}</>}</Card>{selected&&<ReviewDrawer debt={selected} onClose={()=>setSelected(null)}/>}</>;
}
