import {supabase} from '../../services/supabaseClient';

export type DebtKind='existing_loan'|'previous_debt'|'external_nte_deduction'|'nte_deduction';
export type DebtStatus='Draft'|'Pending Approval'|'Pending Finance approval'|'Returned for correction'|'Rejected'|'Approved'|'Active'|'Paused'|'Completed'|'Paid or closed'|'Cancelled';
export type DebtSchedule={id:string;sequence_no:number;payroll_date:string;scheduled_amount:string;actual_amount:string|null;balance_after:string;status:string;excluded_reason:string|null};
export type DebtAudit={action:string;reason:string;before:unknown;after:unknown;at:string;actor:string};
export type DebtDocument={id:string;source_type:'Upload'|'Link';storage_path:string|null;file_name:string|null;document_title:string|null;secure_url:string|null;link_provider:string|null;signed_on:string|null;status:'Missing'|'Uploaded'|'Link added'|'Needs review'|'Accepted'|'Rejected'|'Link unavailable';is_primary:boolean;addedBy:string;added_at:string;reviewer:string|null;reviewed_at:string|null;approval_comments:string|null};
export type PayrollDebt={id:string;record_number:string;scope_id:string;employee_id:string;employeeName:string;employeeCode:string;businessUnit:string;debt_kind:DebtKind;debt_source:string;original_amount:string;opening_balance:string;current_balance:string;amount_already_paid:string;installments_paid:number;issued_on:string;repayment_method:'months'|'cutoffs';deduction_basis:'fixed_per_cutoff'|'fixed_per_month'|'remaining_cutoffs'|'remaining_months';term_count:number;cutoff_count:number;installment:string;first_deduction_date:string;nextDeductionDate:string|null;expected_final_date:string;authority_reference:string|null;signed_on:string|null;notes:string|null;status:DebtStatus;schedule_version:number;totalPaid:string;remainingCutoffs:number;schedule:DebtSchedule[];documents:DebtDocument[];audit:DebtAudit[];created_by:string;financeReviewer:string;approval_comments:string|null;returned_reason:string|null};
export type DebtContext={canManage:boolean;canApprove:boolean;canViewScope?:boolean;financeReviewer:string;routingError?:string|null;scopes:{id:string;name:string}[];employees:{id:string;name:string;code:string}[];debts:PayrollDebt[];payrollDate?:string;locked?:boolean};
export type CreateDebtRecord={id:string;employeeId:string;kind:Exclude<DebtKind,'nte_deduction'>;source:string;originalAmount:string;openingBalance:string;amountPaid:string;installmentsPaid:number;deductionBasis:PayrollDebt['deduction_basis'];installment:string;term:number;firstDate:string;issuedOn:string;authorityReference:string;signedOn:string;notes:string};

async function rpc<T>(name:string,args:Record<string,unknown>):Promise<T>{const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message);return data as T;}
export const getDebtContext=(scope:string|null,payrollDate:string|null=null)=>rpc<DebtContext>('get_payroll_debt_context',{p_scope:scope||null,p_payroll_date:payrollDate||null});
export const createDebtRecord=(record:CreateDebtRecord)=>rpc<string>('create_payroll_debt_record',{p_id:record.id,p_payload:{employeeId:record.employeeId,kind:record.kind,source:record.source,originalAmount:record.originalAmount,openingBalance:record.openingBalance,amountPaid:record.amountPaid,installmentsPaid:record.installmentsPaid,deductionBasis:record.deductionBasis,installment:record.installment,term:record.term,firstDate:record.firstDate,issuedOn:record.issuedOn,authorityReference:record.authorityReference,signedOn:record.signedOn,notes:record.notes}});
export const attachDebtDocument=(id:string,path:string,name:string)=>rpc<void>('attach_payroll_debt_document',{p_id:id,p_path:path,p_name:name});
export const addDebtDocumentLink=(id:string,title:string,url:string,provider:string,signedOn:string,primary=true)=>rpc<string>('add_payroll_debt_document_link',{p_id:id,p_title:title,p_url:url,p_provider:provider,p_signed_on:signedOn,p_primary:primary});
export const reviewDebtDocument=(documentId:string,status:DebtDocument['status'],comments:string)=>rpc<void>('review_payroll_debt_document',{p_document:documentId,p_status:status,p_comments:comments});
export const actDebt=(id:string,action:string,reason:string,payload:Record<string,unknown>={})=>rpc<PayrollDebt>('act_on_payroll_debt',{p_id:id,p_action:action,p_reason:reason,p_payload:payload});

export async function uploadDebtDocument(id:string,file:File){if(file.size>10*1024*1024||!['application/pdf','image/png','image/jpeg'].includes(file.type))throw new Error('Choose a PDF, PNG, or JPEG up to 10 MB.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${id}/${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('payroll-debt-documents').upload(path,file,{contentType:file.type,upsert:false});if(error)throw new Error(error.message);await attachDebtDocument(id,path,file.name);return path;}
export async function openDebtDocument(path:string){const tab=window.open('','_blank');if(tab)tab.opener=null;const {data,error}=await supabase.storage.from('payroll-debt-documents').createSignedUrl(path,60);if(error){tab?.close();throw new Error(error.message);}if(tab)tab.location.href=data.signedUrl;else throw new Error('Allow pop-ups to open the secured document.');}
export function openDebtLink(url:string){let parsed:URL;try{parsed=new URL(url);}catch{throw new Error('Document link is invalid.');}if(parsed.protocol!=='https:')throw new Error('Only secure HTTPS document links can be opened.');const tab=window.open(parsed.toString(),'_blank','noopener,noreferrer');if(!tab)throw new Error('Allow pop-ups to open the document link.');}
export const peso=(value:string|number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(value)||0);
