import {supabase} from '../../services/supabaseClient';

export type DebtSchedule={id:string;sequence_no:number;payroll_date:string;scheduled_amount:string;actual_amount:string|null;balance_after:string;status:string;excluded_reason:string|null};
export type DebtAudit={action:string;reason:string;before:unknown;after:unknown;at:string;actor:string};
export type PayrollDebt={id:string;scope_id:string;employee_id:string;employeeName:string;employeeCode:string;debt_source:string;original_amount:string;opening_balance:string;current_balance:string;issued_on:string;repayment_method:'months'|'cutoffs';term_count:number;cutoff_count:number;installment:string;first_deduction_date:string;expected_final_date:string;authority_reference:string|null;document_path:string|null;document_name:string|null;status:'Draft'|'Pending Approval'|'Active'|'Paused'|'Completed'|'Cancelled';schedule_version:number;totalPaid:string;remainingCutoffs:number;schedule:DebtSchedule[];audit:DebtAudit[];created_by:string};
export type DebtContext={canManage:boolean;canApprove:boolean;canViewScope?:boolean;scopes:{id:string;name:string}[];employees:{id:string;name:string;code:string}[];debts:PayrollDebt[];payrollDate?:string;locked?:boolean};
type CreateDebt={id:string;employeeId:string;source:string;original:string;opening:string;issued:string;method:'months'|'cutoffs';term:number;firstDate:string;authority:string;submit:boolean};
async function rpc<T>(name:string,args:Record<string,unknown>):Promise<T>{const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message);return data as T;}
export const getDebtContext=(scope:string|null,payrollDate:string|null=null)=>rpc<DebtContext>('get_payroll_debt_context',{p_scope:scope||null,p_payroll_date:payrollDate||null});
export const createDebt=(d:CreateDebt)=>rpc<string>('create_payroll_debt',{p_id:d.id,p_employee:d.employeeId,p_source:d.source,p_original:d.original,p_opening:d.opening,p_issued:d.issued,p_method:d.method,p_term:d.term,p_first:d.firstDate,p_authority:d.authority,p_submit:d.submit});
export const attachDebtDocument=(id:string,path:string,name:string)=>rpc<void>('attach_payroll_debt_document',{p_id:id,p_path:path,p_name:name});
export const actDebt=(id:string,action:string,reason:string,payload:Record<string,unknown>={})=>rpc<PayrollDebt>('act_on_payroll_debt',{p_id:id,p_action:action,p_reason:reason,p_payload:payload});
export async function uploadDebtDocument(id:string,file:File){if(file.size>10*1024*1024||!['application/pdf','image/png','image/jpeg'].includes(file.type))throw new Error('Choose a PDF, PNG, or JPEG up to 10 MB.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${id}/${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('payroll-debt-documents').upload(path,file,{contentType:file.type,upsert:false});if(error)throw new Error(error.message);await attachDebtDocument(id,path,file.name);return path;}
export async function openDebtDocument(path:string){const tab=window.open('','_blank');if(tab)tab.opener=null;const {data,error}=await supabase.storage.from('payroll-debt-documents').createSignedUrl(path,60);if(error){tab?.close();throw new Error(error.message);}if(tab)tab.location.href=data.signedUrl;else throw new Error('Allow pop-ups to open the secured document.');}
export const peso=(value:string|number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(value)||0);
