import React from 'react';
import {EmployeePayslipDocumentData, friendlyContribution, peso} from './payslipPresentation';

export default function DetailedPayrollCalculationReport({slip: s, assumptions = [], calculationVersion, snapshotId}: {slip: EmployeePayslipDocumentData; assumptions?: string[]; calculationVersion?: string; snapshotId?: string | null}) {
  const allLines=[...(s.lines||[]),...(s.loans||[]),...(s.otherDeductions||[])];
  return <section aria-label="Detailed payroll calculation report" className="space-y-5 rounded-2xl border border-slate-300 bg-slate-50 p-5 dark:border-slate-700 dark:bg-slate-950">
    <header><p className="text-xs font-bold uppercase tracking-widest text-violet-700">Authorized payroll users only</p><h4 className="mt-1 text-xl font-bold">Detailed Payroll Calculation Report</h4><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Daily attendance, formulas, sources, statutory calculations, and reconciliation evidence remain here—not on the employee payslip.</p></header>
    <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr>{['Date','Calculation item','Quantity','Rate','Multiplier','Amount','Source'].map(label=><th className="border-b p-2" key={label}>{label}</th>)}</tr></thead><tbody>{allLines.map((line,index)=><tr className="border-b border-slate-200 align-top dark:border-slate-700" key={index}><td className="p-2">{line.date||'—'}</td><td className="p-2 font-medium">{line.label||line.account||'Payroll item'}</td><td className="p-2">{line.quantity??'—'}</td><td className="p-2">{line.rate??'—'}</td><td className="p-2">{line.factor??'—'}</td><td className="p-2 text-right font-semibold">{peso(line.remaining??line.amount)}</td><td className="max-w-64 break-words p-2 text-xs">{line.sourceRef||'Recorded payroll source'}</td></tr>)}</tbody></table></div>
    <div className="grid gap-4 md:grid-cols-2"><section className="rounded-xl bg-white p-4 dark:bg-slate-900"><h5 className="font-bold">Government and tax calculation</h5>{(s.contributions||[]).map((line,index)=><div className="mt-2 flex justify-between gap-3 text-sm" key={index}><span>{friendlyContribution(line.label)}</span><strong>{peso(line.amount)}</strong></div>)}<div className="mt-3 flex justify-between border-t pt-3"><span>Withholding tax</span><strong>{peso(s.tax)}</strong></div></section><section className="rounded-xl bg-white p-4 dark:bg-slate-900"><h5 className="font-bold">Reconciliation</h5><p className="mt-2 text-sm">Gross {peso(s.gross)} − deductions {peso(s.deductions)} = net {peso(s.net)}</p><p className="mt-2 text-sm">The approved payroll calculation remains the source of the employee-facing net pay.</p></section></div>
    {assumptions.length>0&&<details><summary className="cursor-pointer font-semibold">Test assumptions and calculation notes</summary><ul className="mt-2 list-disc pl-5 text-sm">{assumptions.map(item=><li key={item}>{item}</li>)}</ul></details>}
    <dl className="grid gap-2 rounded-xl bg-slate-900 p-4 text-xs text-slate-100 sm:grid-cols-3"><div><dt className="text-slate-400">Calculation version</dt><dd className="break-all">{calculationVersion||s.version||'Pending'}</dd></div><div><dt className="text-slate-400">Payroll snapshot</dt><dd className="break-all">{snapshotId||'Not saved'}</dd></div><div><dt className="text-slate-400">Approval status</dt><dd>{s.payrollStatus||s.status||'Draft'}</dd></div></dl>
  </section>;
}
