import React,{useState} from 'react';
import type {NetEmployee,NetInputs,NetWorkspace} from './netPay';
import {financeFields,fieldRequired,fieldValue,financeIssues,validField,updateField,taxGroups,updateTaxGroup,money} from './financeInputs';
const input='mt-1 block w-full rounded border border-slate-300 bg-white p-2 text-slate-900 dark:bg-slate-800 dark:text-slate-100';
export default function FinanceExceptions({w,p,disabled,onChange}:{w:NetWorkspace;p:NetInputs;disabled:boolean;onChange:(p:NetInputs)=>void}){
 const issues=financeIssues(w,p);const [editing,setEditing]=useState<string|null>(null);
 const change=(next:NetEmployee)=>onChange({...p,employees:p.employees.map(e=>e.employeeId===next.employeeId?next:e)});
 return <section className="my-4 rounded-lg border p-4"><h3 className="font-semibold">{issues.length?`${issues.length} employees have missing Finance records`:'No missing Finance inputs — ready to calculate'}</h3><p className="mt-2 text-sm">Approved pay and attendance are already loaded. Only missing records or corrections need entry. A workbook upload is optional. Enter 0 only when the actual record is zero.</p>
 {!p.previousRunId&&issues.length>0&&<p className="mt-2 text-sm text-amber-800 dark:text-amber-200">This is the first payroll recorded here for this period. Earlier tax and contribution amounts must come from your previous payroll records; they are not included in a salary package.</p>}
 <div className="mt-3 divide-y">{p.employees.map(e=>{const issue=issues.find(x=>x.employeeId===e.employeeId);const name=w.gross.result.employees.find(x=>x.employeeId===e.employeeId)?.employeeName;return <div key={e.employeeId} className="py-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong>{name}</strong><p className={`text-sm ${issue?'text-amber-800 dark:text-amber-200':'text-green-700 dark:text-green-300'}`}>{issue?Array.from(new Set(financeFields.filter(([k,,kind])=>fieldRequired(e,p,k)&&!validField(fieldValue(e,k),kind)).map(([, , ,group])=>group).concat(issue.labels.includes('Tax treatment of earnings')?['Tax treatment']:[]))).join(' · '):'Saved figures complete'}</p></div><button type="button" disabled={disabled} className="rounded border px-3 py-2 text-sm text-violet-700 dark:text-violet-300" onClick={()=>setEditing(editing===e.employeeId?null:e.employeeId)}>{editing===e.employeeId?'Close':issue?'Fill missing records':'Edit only if changed'}</button></div>
 {e.deductions.length>0&&<details className="mt-2 text-sm"><summary className="cursor-pointer">{e.deductions.length} additional deductions · PHP {e.deductions.reduce((total,d)=>total+Number(d.amount),0).toFixed(2)}</summary>{e.deductions.map((d,i)=><p key={i} className="mt-1">{d.label}: PHP {d.amount} · {d.sourceRef}</p>)}</details>}
 {editing===e.employeeId&&<fieldset disabled={disabled} className="mt-4 space-y-4">{['Contributions','Earlier payroll','Earlier contributions'].map(group=>{const fields=financeFields.filter(([k,,,section])=>section===group&&fieldRequired(e,p,k));if(!fields.length)return null;return <details key={group} open={fields.some(([k,,kind])=>!validField(fieldValue(e,k),kind))}><summary className="cursor-pointer font-semibold">{group}</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{fields.map(([k,label,kind])=><label key={k} className="text-sm">{label}{kind==='boolean'?<select className={input} value={typeof fieldValue(e,k)==='boolean'?String(fieldValue(e,k)):''} onChange={ev=>change(updateField(e,k,ev.target.value===''?'':ev.target.value==='true'))}><option value="">Choose</option><option value="true">Yes</option><option value="false">No</option></select>:<input className={input} type={kind==='text'?'text':'number'} step={kind==='count'?'1':'0.01'} min={kind==='text'?undefined:'0'} max={kind==='count'?'23':undefined} value={String(fieldValue(e,k))} onChange={ev=>change(updateField(e,k,ev.target.value))}/>}</label>)}</div></details>;})}
 <details open={issue?.labels.includes('Tax treatment of earnings')}><summary className="cursor-pointer font-semibold">Tax treatment of earnings</summary><p className="mt-2 text-sm">Review each pay type once. These are taxable earnings, not the tax deduction. Approved tax treatment stays fixed.</p>{taxGroups(w,e).map(g=><TaxGroup key={JSON.stringify(g.indexes)} w={w} e={e} g={g} onChange={change}/>)}</details></fieldset>}
 </div>;})}</div></section>;
}
const TaxGroup:React.FC<{w:NetWorkspace;e:NetEmployee;g:ReturnType<typeof taxGroups>[number];onChange:(e:NetEmployee)=>void}>=({w,e,g,onChange})=>{
 const [amount,setAmount]=useState(g.taxable),[kind,setKind]=useState(g.kind),[ref,setRef]=useState(g.exemptionRef),[error,setError]=useState('');
 function apply(){try{onChange(updateTaxGroup(w,e,g,amount,kind,ref));setError('');}catch(e){setError((e as Error).message);}}
 return <div className="mt-3 rounded border bg-slate-50 p-3 dark:bg-slate-900"><strong className="text-sm">{g.label} · PHP {money(g.gross)}</strong><div className="mt-2 grid gap-2 sm:grid-cols-3"><label className="text-sm">Taxable earnings<input className={input} type="number" step="0.01" disabled={['included','excluded'].includes(g.treatment)} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="text-sm">Pay category<select className={input} value={kind} onChange={e=>setKind(e.target.value)}><option value="regular">Regular</option><option value="supplement">Supplementary / OT</option></select></label><label className="text-sm">Exemption basis, if applicable<input className={input} value={ref} onChange={e=>setRef(e.target.value)}/></label></div><button type="button" className="mt-2 rounded border bg-white px-3 py-2 text-sm text-violet-700" onClick={apply}>Apply this pay type</button>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div>;
}
