import React,{useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import {useAuth} from '../../hooks/useAuth';
import SetupChecklistLink from './SetupChecklistLink';
import {grossContext,grossRuns,getGrossRun,prepareGross,setShadow,saveGrossRules,GrossScope,GrossRun,RunSummary,GrossConfig} from './grossPay';
const input='mt-1 block w-full rounded border border-gray-300 bg-white p-2 dark:bg-slate-800 dark:border-slate-600';
const Field:React.FC<{label:string;value:string;onChange:(s:string)=>void;type?:string}>=({label,value,onChange,type='text'})=><label className="block text-sm">{label}<input className={input} value={value} onChange={e=>onChange(e.target.value)} type={type} required maxLength={1000} step={type==='number'?'any':undefined}/></label>;
export default function GrossPayPage(){
 const {user}=useAuth();const [scopes,setScopes]=useState<GrossScope[]>([]);const [scopeId,setScopeId]=useState('');const [timeId,setTimeId]=useState('');const [reason,setReason]=useState('');const [runs,setRuns]=useState<RunSummary[]>([]);const [run,setRun]=useState<GrossRun|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const seq=useRef(0);const scope=scopes.find(s=>s.id===scopeId);
 useEffect(()=>{let active=true;setScopes([]);setRun(null);setRuns([]);setScopeId('');setError('');void grossContext().then(d=>{if(active)setScopes(d.scopes);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;++seq.current;};},[user?.id]);
 useEffect(()=>{const n=++seq.current;setRun(null);setRuns([]);setTimeId('');setBusy(false);if(scope?.canView)void grossRuns(scopeId).then(d=>{if(n===seq.current)setRuns(d);}).catch(e=>{if(n===seq.current)setError(e.message);});},[scopeId,scope?.canView]);
 async function act(action:()=>Promise<unknown>,open=false){const n=++seq.current;setBusy(true);setError('');setRun(null);try{const id=await action();const context=await grossContext();const list=scope?.canView?await grossRuns(scopeId):[];const details=open?await getGrossRun(String(id)):null;if(n===seq.current){setScopes(context.scopes);setRuns(list);setRun(details);}}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'The action could not be completed.');}finally{if(n===seq.current)setBusy(false);}}
 async function open(id:string){const n=++seq.current;setRun(null);setError('');setBusy(true);try{const d=await getGrossRun(id);if(n===seq.current)setRun(d);}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Run unavailable.');}finally{if(n===seq.current)setBusy(false);}}
 return <div className="space-y-6 text-gray-800 dark:text-slate-200"><div><h1 className="text-2xl font-bold">Gross Pay Review</h1><p className="mt-1">Prepare an internal Payroll Register from HR-submitted attendance and reviewed dated pay. Live payroll is disabled.</p></div>
 <SetupChecklistLink/>
 {error&&<p role="alert" className="whitespace-pre-wrap rounded border border-red-300 p-3 text-red-700 dark:text-red-300">{error}</p>}
 <Card title="Business unit / shadow review"><label className="block">Scope<select className={input} value={scopeId} disabled={busy} onChange={e=>{setError('');setScopeId(e.target.value);}}><option value="">Choose a scope</option>{scopes.map(s=><option key={s.id} value={s.id}>{s.name} · {s.mode}</option>)}</select></label>
 {!scope?.canView&&<p className="mt-3">Salary work needs the assigned payroll duty and existing compensation and attendance permissions. <Link className="text-indigo-600" to="/payroll/access">Payroll Access</Link></p>}
 {scope&&<div className="mt-3 space-y-3"><Field label="Preparation / change reason and approval reference" value={reason} onChange={setReason}/>{scope.canManage&&<><p className="text-sm">Shadow permits internal calculations only. Enable both “All business units” (master gate) and the intended BU. Other BUs stay off. This never grants salary access.</p><Button disabled={busy||reason.trim().length<3} variant="secondary" onClick={()=>void act(()=>setShadow(scopeId,scope.mode!=='shadow',reason))}>{scope.mode==='shadow'?'Turn processing off':'Enable shadow review for this scope'}</Button></>}</div>}
 {scope?.canView&&<div className="mt-4 space-y-3"><label>HR-submitted attendance version<select className={input} disabled={busy} value={timeId} onChange={e=>{setTimeId(e.target.value);setRun(null);}}><option value="">Choose a submitted cutoff</option>{scope.timePackages.map(p=><option key={p.id} value={p.id}>{p.from}–{p.to} · version {p.version}</option>)}</select></label>{scope.timePackages.length===0&&<p>Waiting for HR to resolve and submit attendance in <Link className="text-indigo-600" to="/payroll/attendance-readiness">Attendance Readiness</Link>.</p>}<p className="text-sm">Missing pay versions or policy coverage blocks preparation. Source changes require a new review; retries reuse the same result.</p><Button disabled={busy||!scope.canPrepare||!scope.canCalculate||!timeId||reason.trim().length<3} onClick={()=>void act(()=>prepareGross(timeId,reason),true)}>Prepare gross-pay review</Button>{!scope.canCalculate&&<p className="text-sm">Calculation remains off until the access manager enables shadow for this BU and its parent scope.</p>}</div>}
 </Card>
 {scope?.canConfigure&&<RuleForm key={scopeId} scope={scope} busy={busy} save={(from,to,c,ref)=>act(()=>saveGrossRules(scopeId,from,to,c,ref))}/>}
 {scope?.canView&&<Card title="Saved Payroll Register versions">{runs.length===0?<p>No gross-pay reviews saved yet.</p>:runs.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 border-t py-3"><span>{r.from}–{r.to} · version {r.version}</span><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void open(r.id)}>Open and check sources</Button></div>)}</Card>}
 {run&&<Card title={`Internal gross PR · version ${run.version}`}><p className={run.current?'text-green-700':'text-red-700'}>{run.current?'Saved inputs are current.':`Inputs changed — prepare a new version. ${run.staleReason||''}`}</p><p className="mt-2 font-semibold">Gross total: PHP {run.result.gross}</p><p className="text-sm">Gross only. Continue in Take-home Pay Review for deductions and net pay. Approvals, payment and payslip release follow in later phases.</p><p className="mt-2 text-sm">{run.reason}</p><p className="text-xs">Engine {run.engineVersion} · attendance {run.timePackageId} · input reference {run.sourceHash}{run.previousId?` · prior PR ${run.previousId}`:''}</p>{run.result.employees.map(e=><details key={e.employeeId} className="mt-4 border-t pt-3"><summary className="cursor-pointer font-medium">{e.employeeName} · PHP {e.gross} · Explain amounts</summary><div className="overflow-x-auto"><table className="mt-3 w-full text-left text-sm"><thead><tr>{['Date / amount','Quantity × rate × multiplier','PHP','Source / rule / rounding'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{e.lines.map((l,i)=><tr key={i} className="border-t"><td className="p-2 align-top">{l.date}<p>{l.label}</p>{l.category&&<p>{l.category}</p>}</td><td className="p-2 align-top break-all">{l.quantity} × {l.rate} × {l.factor}</td><td className="p-2 align-top">{l.amount}</td><td className="p-2 min-w-72"><p>{l.packageSource}</p><p>{l.ruleSource}</p><p>{l.rounding} · unrounded {l.unrounded}</p><details><summary>Source references</summary><p className="break-all">Pay {l.packageId} · rule {l.ruleId}</p><p>Base {l.baseRate} / {l.rateType}; divisor {l.annualDivisor}; hours/day {l.hoursPerDay}</p><p className="break-all">Punches {l.eventIds?.join(', ')} · shifts {l.shiftIds?.join(', ')} · OT {l.otId}</p>{l.start&&<p>{l.start}–{l.end}</p>}</details></td></tr>)}</tbody></table></div></details>)}</Card>}
 </div>;
}
const empty:GrossConfig={monthlyMethod:'',rounding:'',recurringMethod:'',annualDivisor:'',hoursPerDay:'',nightStart:'',nightEnd:'',offsetCash:'excluded',gracePay:'base_only',rateBoundary:'shift_date',premiums:{}};
const categories=['ordinary','ordinary_rest','regular','regular_rest','special_nonworking','special_nonworking_rest','special_working','special_working_rest','double_regular','double_regular_rest'];
const RuleForm:React.FC<{scope:GrossScope;busy:boolean;save:(from:string,to:string,c:GrossConfig,ref:string)=>Promise<void>}>=({scope,busy,save})=>{
 const [c,setC]=useState<GrossConfig>(scope.rules[0]?.config||empty);const [from,setFrom]=useState('');const [to,setTo]=useState('');const [ref,setRef]=useState('');const [confirmed,setConfirmed]=useState(false);
 const change=(key:keyof GrossConfig,value:string)=>setC(prev=>({...prev,[key]:value}));
 return <Card title="Approved gross-pay rules"><p className="text-sm">HR records the approved policy and its dates. Values are intentionally blank until confirmed. Each new version preserves earlier rules and makes affected saved PRs out of date.</p>{scope.rules.map(r=><p key={r.id} className="mt-2 text-sm">{r.effective_from}–{r.effective_to}: {r.source_ref}</p>)}<details className="mt-3"><summary className="cursor-pointer font-medium">Record a reviewed rule version</summary><form className="mt-3 space-y-4" onSubmit={e=>{e.preventDefault();void save(from,to,c,ref);}}><fieldset disabled={busy} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Effective from" type="date" value={from} onChange={setFrom}/><Field label="Effective through" type="date" value={to} onChange={setTo}/><Field label="Approved annual day divisor" type="number" value={c.annualDivisor} onChange={v=>change('annualDivisor',v)}/><Field label="Approved hours per day" type="number" value={c.hoursPerDay} onChange={v=>change('hoursPerDay',v)}/><Field label="Night period starts (Manila)" type="time" value={c.nightStart} onChange={v=>change('nightStart',v)}/><Field label="Night period ends (Manila)" type="time" value={c.nightEnd} onChange={v=>change('nightEnd',v)}/></div>
 <label className="block">Monthly basic proration<select required className={input} value={c.monthlyMethod} onChange={e=>change('monthlyMethod',e.target.value)}><option value="">Choose the approved method</option><option value="calendar_prorated">Half-month salary × eligible calendar days / cutoff days; hourly unpaid-time deduction</option><option value="earned_minutes">Earned regular / paid-leave / grace minutes × converted hourly rate</option></select></label>
 <label className="block">Recurring monthly allowances<select required className={input} value={c.recurringMethod} onChange={e=>change('recurringMethod',e.target.value)}><option value="">Choose the approved method</option><option value="calendar_prorated">Monthly amount / 2 × eligible calendar days / cutoff days</option><option value="earned_fraction">Monthly amount × 12 / annual divisor × earned-day fraction</option></select></label>
 <label className="block">Rounding<select required className={input} value={c.rounding} onChange={e=>change('rounding',e.target.value)}><option value="">Choose the approved method</option><option value="per_line_half_up">Round each explanation line to cents, half up</option><option value="employee_total_half_up">Round employee total to cents, show reconciliation line</option></select></label>
 <p className="text-sm">Select only reviewed premium categories. Regular and OT are total hourly multipliers. Night columns are additional base-hourly multipliers, with stacking already included. Rest-day approved work uses the OT column. Uncovered categories block the affected calculation.</p>
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Coverage','Regular total','OT total','Night regular add-on','Night OT add-on'].map(h=><th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{categories.map(cat=><tr key={cat}><td className="p-2"><label><input type="checkbox" checked={Boolean(c.premiums[cat])} onChange={e=>setC(prev=>{const premiums={...prev.premiums};if(e.target.checked)premiums[cat]={regular:'',ot:'',nightRegular:'',nightOt:''};else delete premiums[cat];return {...prev,premiums};})}/> {cat.replaceAll('_',' ')}</label></td>{(['regular','ot','nightRegular','nightOt'] as const).map(k=><td className="p-2" key={k}>{c.premiums[cat]&&<input aria-label={`${cat} ${k}`} type="number" step="any" min={k==='regular'?1:0} max={10} required className={`${input} min-w-24`} value={c.premiums[cat][k]} onChange={e=>setC(prev=>({...prev,premiums:{...prev.premiums,[cat]:{...prev.premiums[cat],[k]:e.target.value}}}))}/>}</td>)}</tr>)}</tbody></table></div>
 <p className="text-sm">This version supports rates by shift date, grace paid at base rate only, and approved offset work excluded from cash. It uses the reviewed Phase 2 components for allowances and one-time gross additions. Different rules, unworked holiday eligibility or separate consultant fees require review before calculation.</p><Field label="Approved policy / independently checked example reference" value={ref} onChange={setRef}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have verified these methods, coverage and multipliers against the approved source for this BU.</label><Button type="submit" disabled={busy||!confirmed||ref.trim().length<3}>Record approved rules</Button></fieldset></form></details></Card>;
};
