import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useAuth} from '../../hooks/useAuth';
import AttendanceCorrection from '../../components/attendance/AttendanceCorrection';
import {AttendanceDay} from '../../services/employeeAttendance';
import {usePayrollField} from './usePayrollSelection';
import {validCutoff} from './workspace';
import {historyContext,historyRpc,HistoryContext} from './historicalAttendance';
export default function HistoricalCorrectionPage(){
 const {user}=useAuth();const [scope]=usePayrollField('scope');const [from]=usePayrollField('from');const [to]=usePayrollField('to');const [context,setContext]=useState<HistoryContext|null>(null);const [employee,setEmployee]=useState('');const [date,setDate]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 useEffect(()=>{let active=true;setContext(null);setEmployee('');setDate('');setError('');if(!scope||!validCutoff(from,to))return;setLoading(true);historyContext(scope,from,to).then(c=>{if(active)setContext(c);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[scope,from,to,user?.id]);
 return <main className="space-y-5 p-4 sm:p-6"><h1 className="text-3xl font-bold">Genuine historical corrections</h1><div className="rounded-xl border border-amber-400 bg-amber-50 p-5 text-amber-950"><strong>LIVE ATTENDANCE — separate from test imports</strong><p className="mt-2">Authorized HR may correct verified actual times. Every save requires a reason, evidence reference and explicit authorization. Existing attendance permissions, revision checks and audit history remain in force. This can change live attendance results; it does not bypass payroll approvals.</p><p className="mt-2">Do not enter times inferred from DTR summaries. Test records cannot be promoted here. Review supporting actual-time evidence independently.</p></div><Link className="inline-block underline" to="/payroll/historical-attendance">Return to isolated test imports</Link>
 {error&&<p role="alert" className="text-red-700">{error}</p>}{loading?<p>Checking HR correction authority…</p>:!scope||!validCutoff(from,to)?<Link to="/payroll/home">Select a Business Unit and cutoff in Payroll Home.</Link>:!context?.canCorrect?<p>Existing HR attendance-management permission and a scoped timekeeping-finalizer duty are required.</p>:<section className="rounded-xl border p-5"><h2 className="text-lg font-bold">{context.scopeName} · {from}–{to}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label>Employee<select className="mt-2 min-h-11 w-full rounded border bg-transparent p-2" value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">Choose employee</option>{context.employees.map(e=><option key={e.id} value={e.id}>{e.code} · {e.name}</option>)}</select></label><label>Work date<input className="mt-2 min-h-11 w-full rounded border bg-transparent p-2" type="date" min={from} max={to} value={date} onChange={e=>setDate(e.target.value)}/></label></div>
 {employee&&date>=from&&date<=to&&<AttendanceCorrection key={`${scope}:${employee}:${date}`} employee={employee} date={date} requireAuthorization onCorrect={(employee,date,revision,events,reason)=>historyRpc<AttendanceDay>('correct_genuine_historical_attendance',{p_scope:scope,p_employee:employee,p_date:date,p_revision:revision,p_events:events,p_reason:reason,p_authorized:true})}/>}</section>}
 </main>;
}
