import React,{useEffect,useMemo,useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {useAuth} from '../../hooks/useAuth';
import PayrollCycleSelector from './PayrollCycleSelector';
import PresetAttendanceCorrection from './PresetAttendanceCorrection';
import {usePayrollField} from './usePayrollSelection';
import {validCutoff} from './workspace';
import {historyContext,HistoryContext} from './historicalAttendance';
import {previewTime} from './attendanceReadiness';
import {formatCutoff,payrollCycleForCutoff,payrollCycleLabel} from './payrollCycle';

const field='mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800';
type QueueItem={employeeId:string;employeeName:string;date:string;issue:string};

export default function HistoricalCorrectionPage(){
 const {user}=useAuth();const navigate=useNavigate();const [params,setParams]=useSearchParams();const [scope]=usePayrollField('scope');const [from]=usePayrollField('from');const [to]=usePayrollField('to');const [context,setContext]=useState<HistoryContext|null>(null);const [queue,setQueue]=useState<QueueItem[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const employee=params.get('employee')||'';const date=params.get('date')||'';const issue=params.get('issue')||'';
 const load=async()=>{if(!scope||!validCutoff(from,to))return;setLoading(true);setError('');try{const [nextContext,preview]=await Promise.all([historyContext(scope,from,to),previewTime(scope,from,to)]);setContext(nextContext);setQueue(preview.result.rows.flatMap(row=>row.issues.map(value=>({employeeId:row.employeeId,employeeName:row.employeeName,date:row.date,issue:value}))));}catch(reason){setError(reason instanceof Error?reason.message:'Correction workspace could not be loaded.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[scope,from,to,user?.id]);
 const current=useMemo(()=>queue.find(item=>item.employeeId===employee&&item.date===date&&(!issue||item.issue===issue))||queue.find(item=>item.employeeId===employee&&(!date||item.date===date))||null,[queue,employee,date,issue]);const currentIssue=issue||current?.issue||'';const cycle=payrollCycleForCutoff(from,to);const cycleLabel=cycle?payrollCycleLabel(cycle):from&&to?`Special payroll · ${formatCutoff(from,to)}`:'Payroll cycle not selected';
 const selectEmployee=(value:string)=>{const first=queue.find(item=>item.employeeId===value);if(first)setParams({employee:first.employeeId,date:first.date,issue:first.issue});else setParams(value?{employee:value}:{});};
 const saved=async(openNext:boolean)=>{await load();if(!openNext)return;const index=queue.findIndex(item=>item.employeeId===current?.employeeId&&item.date===current?.date&&item.issue===currentIssue);const next=queue[index+1]||queue.find(item=>item.employeeId!==current?.employeeId||item.date!==current?.date);if(next)setParams({employee:next.employeeId,date:next.date,issue:next.issue});else navigate('/payroll/attendance-readiness');};
 return <main className="space-y-6 p-4 text-slate-800 dark:text-slate-200 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-slate-500"><Link to="/payroll/attendance-readiness">Payroll readiness</Link> / {current?.employeeName||'Attendance correction'}</p><h1 className="mt-2 text-3xl font-bold">Review attendance</h1><p className="mt-1 text-sm text-slate-500">Use a preset for common corrections; open advanced times only when necessary.</p></div>{current&&<span className="text-sm font-semibold text-violet-700">Issue {Math.max(1,queue.indexOf(current)+1)} of {queue.length}</span>}</div><PayrollCycleSelector compact/>
  {error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error}</p>}{loading?<p role="status" className="rounded-xl border border-dashed p-8 text-center">Loading attendance evidence…</p>:!scope||!validCutoff(from,to)?<Link className="font-semibold text-violet-700" to="/payroll/home">Select a payroll cycle first.</Link>:!context?.canCorrect?<p className="rounded-xl bg-amber-50 p-4 text-amber-900">Existing HR attendance-management permission and a scoped timekeeping-finalizer duty are required.</p>:<>
   <section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><div className="grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium">Employee<select className={field} value={employee} onChange={event=>selectEmployee(event.target.value)}><option value="">Choose employee</option>{context.employees.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label className="text-sm font-medium">Issue date<select className={field} value={date} onChange={event=>{const target=queue.find(item=>item.employeeId===employee&&item.date===event.target.value);if(target)setParams({employee,date:target.date,issue:target.issue});}}><option value="">Choose date</option>{[...new Set(queue.filter(item=>item.employeeId===employee).map(item=>item.date))].map(value=><option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium">Issue<select className={field} value={currentIssue} onChange={event=>setParams({employee,date,issue:event.target.value})}><option value="">Choose issue</option>{queue.filter(item=>item.employeeId===employee&&item.date===date).map((item,index)=><option key={`${item.issue}:${index}`} value={item.issue}>{item.issue.replace(/Employee profile information incomplete/ig,'Timekeeping setup needed')}</option>)}</select></label></div></section>
   {current&&<PresetAttendanceCorrection key={`${current.employeeId}:${current.date}:${currentIssue}`} scopeId={scope} employeeId={current.employeeId} employeeName={current.employeeName} date={current.date} issue={currentIssue} businessUnit={context.scopeName} cycleLabel={cycleLabel} onSaved={saved}/>} {!current&&<div className="rounded-xl border border-dashed p-8 text-center text-slate-500">Choose an employee and issue. If no issue appears, refresh Payroll Readiness.</div>}
  </>}
 </main>;
}
