import React,{useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {useAuth} from '../../hooks/useAuth';
import {usePayrollField} from './usePayrollSelection';
import {validCutoff} from './workspace';
import {historyContext,historyDetail,stageHistory,historyRpc,downloadHistoricalSource,saveDownload,HistoryBatch,HistoryContext,HistoryKind,HistoryPreview} from './historicalAttendance';
import {historicalTemplate} from './historicalTemplates';
const input='mt-2 block min-h-11 w-full rounded-lg border border-slate-300 bg-white p-3 dark:border-slate-600 dark:bg-slate-800';
const button='min-h-11 rounded-lg border px-4 py-2 font-semibold disabled:opacity-50';
export default function HistoricalAttendancePage(){
 const {user}=useAuth();const [scope]=usePayrollField('scope');const [from]=usePayrollField('from');const [to]=usePayrollField('to');
 return <HistoricalWorkspace key={`${user?.id}:${scope}:${from}:${to}`} scope={scope} from={from} to={to}/>;
}
const HistoricalWorkspace:React.FC<{scope:string;from:string;to:string}>=({scope,from,to})=>{
 const key=`${scope}:${from}:${to}`;
 const [context,setContext]=useState<HistoryContext|null>(null);const [kind,setKind]=useState<HistoryKind>('punches');const [file,setFile]=useState<File|null>(null);const [reference,setReference]=useState('');const [confirmed,setConfirmed]=useState(false);
 const [batch,setBatch]=useState<HistoryBatch|null>(null);const [page,setPage]=useState(0);const [errorsOnly,setErrorsOnly]=useState(false);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [refresh,setRefresh]=useState(0);const sequence=useRef(0);
 useEffect(()=>{const seq=++sequence.current;setContext(null);setBatch(null);setFile(null);setError('');setNotice('');setConfirmed(false);setPage(0);setBusy(false);if(!scope||!validCutoff(from,to)){setLoading(false);return;}
 setLoading(true);historyContext(scope,from,to).then(c=>{if(seq===sequence.current)setContext(c);}).catch(e=>{if(seq===sequence.current)setError(e.message);}).finally(()=>{if(seq===sequence.current)setLoading(false);});return()=>{++sequence.current;};},[key,refresh]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'The import could not be completed.');}finally{setBusy(false);}}
 async function preview(){const seq=sequence.current;if(!file)return;const b=await stageHistory(scope,from,to,kind,file,reference);if(seq!==sequence.current)return;setBatch(b);setPage(0);setConfirmed(false);setNotice(b.duplicateFile?'This exact source was already uploaded. Its existing preview/import is shown. No duplicate batch was created.':'Source saved. Review every error and the matched employees before importing test data.');setContext(await historyContext(scope,from,to));}
 async function commit(){if(!batch||!confirmed)return;const seq=sequence.current;const result=await historyRpc<{status:string;error?:string;preview?:HistoryPreview;imported?:number;alreadyImported?:boolean}>('commit_historical_attendance_test',{p_batch:batch.id});if(seq!==sequence.current)return;
 if(result.error){setBatch({...batch,preview:result.preview||batch.preview});setError(result.error);setConfirmed(false);return;}setBatch(await historyDetail(batch.id));setContext(await historyContext(scope,from,to));setConfirmed(false);setNotice(result.alreadyImported?'This test batch was already imported.':`${result.imported||0} test records imported. Live attendance and payroll are unchanged.`);}
 const rows=(batch?.preview.rows||[]).filter(r=>!errorsOnly||r.errors.length);const visible=rows.slice(page*50,page*50+50);
 return <main className="space-y-6 p-4 text-slate-900 dark:text-slate-100 sm:p-6">
 <header><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-bold">Import Historical Attendance</h1><span className="rounded-full bg-violet-100 px-4 py-2 font-bold text-violet-900">TEST DATA ONLY</span></div><p className="mt-3">{context?.scopeName||'Selected payroll workspace'} · {from||'Choose start'} to {to||'Choose end'}</p><Link className="mt-2 inline-block underline" to="/payroll/home">Change Business Unit / cutoff</Link></header>
 <section className="rounded-xl border border-violet-300 bg-violet-50 p-5 text-violet-950"><h2 className="font-bold">Safe historical testing</h2><p className="mt-2">Imports are stored separately from live attendance. They do not create attendance penalties, change leave balances, submit timekeeping, or authorize payment. These test records do not make Payroll Home’s live readiness counts change.</p><p className="mt-2">This phase validates and preserves test attendance. It does not calculate payroll from the imported dataset.</p></section>
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-emerald-50 p-4 text-emerald-900">{notice}</p>}
 {loading?<p role="status">Loading the cutoff and import history…</p>:!scope||!validCutoff(from,to)?<p>Select a BU and valid cutoff in Payroll Home first.</p>:!context?<button className={button} onClick={()=>setRefresh(n=>n+1)}>Retry loading</button>:<>
 {context.canImport?<section className="space-y-4 rounded-xl border p-5 dark:border-slate-700"><h2 className="text-xl font-bold">1. Choose the evidence and prepare the file</h2>
 <label className="block">Import type<select className={input} disabled={busy} value={kind} onChange={e=>{setKind(e.target.value as HistoryKind);setFile(null);setBatch(null);setConfirmed(false);}}><option value="punches">Actual punch logs — individual recorded events</option><option value="dtr">Reviewed DTR summaries — totals only, never punches</option></select></label>
 <p>{kind==='punches'?'Use one row per recorded CLOCK_IN, START_BREAK, END_BREAK or CLOCK_OUT. Include the full date, time and timezone (+08:00 for Philippine time). For overnight work, retain the starting Work Date even when clock-out falls the following day. Missing punches are not inferred.':'Use one row per employee and work date. Enter whole minute totals and a review reference identifying the reviewer and supporting DTR. Enter 0 for a confirmed zero. Totals remain summaries; they do not prove punch times or overtime approval.'}</p>
 <div className="flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={()=>saveDownload(new Blob([historicalTemplate(kind,context.scopeName,[],from)],{type:'text/csv;charset=utf-8'}),`Historical-${kind}-Template.csv`)}>Download blank CSV template</button><button className={button} disabled={busy} onClick={()=>saveDownload(new Blob([historicalTemplate(kind,context.scopeName,context.employees,from)],{type:'text/csv;charset=utf-8'}),`Historical-${kind}-${from}.csv`)}>Template with BU employee codes</button></div>
 <p className="text-sm">Open in Excel and save as CSV UTF-8. Maximum 512 KB / 5,000 rows. Employee codes are matched to the selected BU’s current roster; employment dates are checked. Historical BU transfers require HR review. Remove unused template rows. No times or totals are prefilled.</p>
 <label className="block">Source / reviewer reference<textarea className={input} disabled={busy} minLength={3} maxLength={1000} value={reference} onChange={e=>setReference(e.target.value)} placeholder="For example: device export reference, or reviewed DTR and reviewer name"/></label>
 <label className="block">Upload completed CSV<input key={key+kind} className={input} type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setBatch(null);setConfirmed(false);}}/></label>
 <button className={`${button} bg-violet-600 text-white`} disabled={busy||!file||reference.trim().length<3} onClick={()=>void run(preview)}>{busy?'Working…':'Save source and preview'}</button>
 </section>:<p>Your existing payroll role can review test imports. Uploading requires a scoped HR timekeeping-finalizer or Finance payroll-preparer duty.</p>}
 {batch&&<section className="space-y-4 rounded-xl border p-5 dark:border-slate-700"><h2 className="text-xl font-bold">2. Preview — {batch.filename}</h2><p><strong>{batch.status==='imported'?'Imported test batch':'Preview only'}</strong> · Preview validation: {batch.preview.ready} ready · {batch.preview.invalid} invalid · {batch.preview.duplicates} duplicate rows</p><p className="text-sm">The source and initial preview are retained. Import rechecks current employee/BU data and existing test records. Invalid rows block the whole batch; duplicates are skipped.</p>
 <label><input type="checkbox" checked={errorsOnly} onChange={e=>{setErrorsOnly(e.target.checked);setPage(0);}}/> Show errors only</label>
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['CSV row','Employee code / match','Work date','Evidence','Result'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.line} className="border-t"><td className="p-2">{r.line}</td><td className="p-2">{r.code}<p>{r.employeeName||'Unmatched'}</p></td><td className="whitespace-nowrap p-2">{r.workDate}</td><td className="min-w-64 p-2">{r.payload.kind==='punches'?<>{String(r.payload.action||'')}<p>{String(r.payload.timestamp||'')}</p><p>{String(r.payload.sourceReference||'')}</p></>:<>{Object.entries((r.payload.minutes||{}) as Record<string,number>).map(([k,v])=><p key={k}>{k.replace('MINUTES','').toLowerCase()}: {v} min</p>)}<p>{String(r.payload.reviewReference||'')}</p></>}</td><td className="min-w-64 p-2">{r.errors.length?r.errors.map((e,i)=><p key={i} className="text-red-700 dark:text-red-300">{e}</p>):r.duplicate?'Duplicate — skipped':'Ready for test import'}</td></tr>)}</tbody></table></div>
 <div className="flex items-center gap-3"><button className={button} disabled={page===0} onClick={()=>setPage(n=>n-1)}>Previous</button><span>{rows.length?`${page*50+1}–${Math.min((page+1)*50,rows.length)} of ${rows.length} rows`:'No rows'}</span><button className={button} disabled={(page+1)*50>=rows.length} onClick={()=>setPage(n=>n+1)}>Next</button></div>
 {batch.status==='preview'&&context.canImport&&<div className="space-y-3"><label className="flex gap-2"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/><span>I checked the employee matches and source evidence. Import these records as isolated test data only.</span></label><button className={`${button} bg-violet-600 text-white`} disabled={busy||!confirmed||batch.preview.invalid>0} onClick={()=>void run(commit)}>Import test records</button></div>}
 <button className={button} disabled={busy} onClick={()=>void run(async()=>{const b=await historyDetail(batch.id,true);downloadHistoricalSource(b);setBatch(b);})}>Download original source</button>
 <details><summary className="cursor-pointer font-semibold">Source fingerprint and audit history</summary><p className="break-all py-2 text-xs">SHA-256: {batch.sourceHash}</p>{batch.audit?.map(a=><p className="my-2 text-sm" key={a.id}>{new Date(a.created_at).toLocaleString()} · {a.action.replaceAll('_',' ')} · actor {a.actor} · {JSON.stringify({...a.details,rows:undefined})}</p>)}{!batch.audit&&<button className={button} disabled={busy} onClick={()=>void run(async()=>setBatch(await historyDetail(batch.id)))}>Load audit history</button>}</details>
 </section>}
 <section className="rounded-xl border p-5 dark:border-slate-700"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-bold">Test import history for this cutoff</h2><button className={button} disabled={busy} onClick={()=>setRefresh(n=>n+1)}>Refresh history</button></div><p className="mt-2 text-sm">Latest 100 uploads. All source files and audit events remain retained.</p>{!context.batches.length&&<p className="mt-3">No test imports for this cutoff.</p>}{context.batches.map(b=><article key={b.id} className="mt-4 border-t pt-4"><strong>{b.filename}</strong><p>{b.kind==='punches'?'Actual punches':'Reviewed DTR summary'} · {b.status==='imported'?`Imported — ${b.imported_records} test records`:`Preview — ${b.preview_invalid} invalid rows`} · {new Date(b.created_at).toLocaleString()}</p><p>{b.reference}</p><button className={`${button} mt-2`} disabled={busy} onClick={()=>void run(async()=>{setBatch(await historyDetail(b.id));setConfirmed(false);setPage(0);setErrorsOnly(false);})}>View source, rows & audit</button></article>)}</section>
 <section className="rounded-xl border border-amber-300 p-5"><h2 className="text-xl font-bold">Need a genuine historical correction?</h2><p className="my-3">Use the separate HR correction process with verified actual times, a supporting reference and explicit authorization. It changes live attendance and retains previous versions. Test batches cannot be promoted, and summary totals cannot be converted into punches.</p>{context.canCorrect?<Link className="font-semibold underline" to="/payroll/historical-corrections">Open genuine historical corrections →</Link>:<p>Ask an authorized HR attendance reviewer with timekeeping-finalizer access.</p>}</section>
 </>}
 </main>;
}
