import {supabase} from '../../services/supabaseClient';

export type ReconciliationRecord={id:string;kind:'employee'|'schedule'|'attendance'|'original_payroll';record_key:string;employee_id:string;work_date?:string;payload:Record<string,unknown>;revision:number;created_at:string};
export type ReconciliationEmployee={id:string;employeeId:string;name:string;businessUnit:string;department:string;dateHired?:string;endDate?:string;package?:{id:string;effectiveFrom:string;rateType:string;baseAmount:number;components:Record<string,unknown>[];treatment:Record<string,unknown>;sourceRef:string}|null};
export type ReconciliationRun={id:string;version:number;createdAt:string;result:{employees:ReconciliationResult[];summary:ReconciliationSummary}};
export type ReconciliationResult={employeeId:string;employeeCode:string;employeeName:string;packageId?:string;packageEffectiveFrom?:string;packageSource?:string;basic:number;components:number;overtime:number;governmentContributions:number;withholdingTax:number;loanDeductions:number;originalGross:number;recalculatedGross:number;grossDifference:number;originalDeductions:number;recalculatedDeductions:number;deductionDifference:number;originalNet:number;recalculatedNet:number;netDifference:number;issues:string[];status:'Match'|'Difference found'|'Missing historical information'|'Needs review'};
export type ReconciliationSummary={reviewed:number;matched:number;differences:number;missing:number;originalGross:number;recalculatedGross:number;grossVariance:number;originalNet:number;recalculatedNet:number;netVariance:number};
export type ReconciliationContext={scopes:{id:string;name:string;businessUnitId:string}[];reconciliations:{id:string;scopeId:string;scopeName:string;releaseDate:string;dateFrom:string;dateTo:string;employeeGroup:string;status:string;updatedAt:string}[];reconciliation?:{id:string;scopeId:string;releaseDate:string;dateFrom:string;dateTo:string;employeeGroup:string;status:string}|null;employees:ReconciliationEmployee[];records:ReconciliationRecord[];sources:{id:string;kind:string;filename?:string;reference:string;sourceHash?:string;createdAt:string}[];runs:ReconciliationRun[];audit:{id:string;action:string;details:Record<string,unknown>;createdAt:string;actor:string}[]};

async function rpc<T>(name:string,args:Record<string,unknown>){const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message);return data as T;}
export const loadReconciliation=(id?:string|null)=>rpc<ReconciliationContext>('get_historical_reconciliation_context',{p_reconciliation:id||null});
export const saveReconciliation=(id:string|null,scope:string,release:string,from:string,to:string,group:string)=>rpc<string>('save_historical_reconciliation',{p_id:id,p_scope:scope,p_release:release,p_from:from,p_to:to,p_employee_group:group});
export const saveDataset=(id:string,kind:string,rows:Record<string,unknown>[],reference:string,file?:{name:string;base64:string})=>rpc<{saved:number;sourceHash?:string}>('save_historical_reconciliation_dataset',{p_reconciliation:id,p_kind:kind,p_rows:rows,p_filename:file?.name||null,p_source_base64:file?.base64||null,p_reference:reference});
export const runReconciliation=(id:string)=>rpc<ReconciliationRun>('run_historical_payroll_reconciliation',{p_reconciliation:id});
export const archiveReconciliation=(id:string)=>rpc<void>('archive_historical_reconciliation',{p_reconciliation:id});
export async function fileBase64(file:File){const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary);}
export const money=(value:unknown)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',minimumFractionDigits:2}).format(Number(value)||0);
export function downloadCsv(name:string,rows:(string|number)[][]){const csv=rows.map(row=>row.map(value=>`"${String(value??'').replaceAll('"','""')}"`).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
