import React,{useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {useAuth} from '../../hooks/useAuth';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import Modal from '../../components/ui/Modal';
import {myPayslips,myPayslip,canReviewIssues,EmployeePayslip,money,inputClass} from './selfService';
import PayslipView from './PayslipView';
import ReportPayrollIssue from './ReportPayrollIssue';
import {downloadPayslip} from './payslipPdf';
export default function MyPayslipsPage(){
 const {user}=useAuth();const [params,setParams]=useSearchParams();const [list,setList]=useState<EmployeePayslip[]>([]),[slip,setSlip]=useState<EmployeePayslip|null>(null),[report,setReport]=useState<EmployeePayslip|null>(null),[year,setYear]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[review,setReview]=useState(false);const selected=params.get('slip');
 useEffect(()=>{let active=true;setList([]);setSlip(null);setReport(null);setReview(false);setLoading(true);setError('');Promise.all([myPayslips(),canReviewIssues()]).then(([l,r])=>{if(active){setList(l);setReview(r);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[user?.id]);
 useEffect(()=>{let active=true;setSlip(null);if(selected)myPayslip(selected).then(s=>{if(active)setSlip(s);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[selected,user?.id]);
 async function pdf(s:EmployeePayslip){setBusy(true);setError('');try{await downloadPayslip(await myPayslip(s.id));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold">My Payslips</h1><div className="flex flex-wrap gap-4 text-indigo-600 dark:text-indigo-300"><Link to="/payroll/my-issues">My Payroll Issues</Link>{review&&<Link to="/payroll/my-issues?review=1">Review payroll issues</Link>}</div></div><p className="text-sm text-gray-600 dark:text-slate-300">Your released payslips, newest first.</p>{error&&<p role="alert" className="text-red-600 dark:text-red-300">{error}</p>}<label className="block max-w-xs">Year<select className={inputClass} value={year} onChange={e=>setYear(e.target.value)}><option value="">All years</option>{[...new Set(list.map(s=>s.to.slice(0,4)))].sort().reverse().map(y=><option key={y}>{y}</option>)}</select></label>
 {loading?<p role="status">Loading your payslips…</p>:list.filter(s=>!year||s.to.startsWith(year)).length===0?<Card title="No payslips yet"><p>{list.length?'No payslips for this year.':'Your payslips will appear here after payroll is approved and payment is confirmed.'}</p></Card>:list.filter(s=>!year||s.to.startsWith(year)).map(s=><Card key={s.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-semibold">{s.from} – {s.to}</h2><p className="text-sm">Pay date {s.payDate} · {s.payrollStatus}{s.correctionKind==='revised'?' · Revised':s.correctionKind==='adjustment'?' · Adjustment':''} · v{s.version}</p></div></div><dl className="my-4 grid gap-3 sm:grid-cols-3">{[['Gross pay',s.gross],['Total deductions',s.deductions],['Net pay',s.net]].map(([k,v])=><div key={k}><dt className="text-sm">{k}</dt><dd className="text-lg font-semibold">{money(v)}</dd></div>)}</dl><div className="flex flex-wrap gap-3"><Button onClick={()=>setParams({slip:s.id})}>View Payslip</Button><Button variant="secondary" disabled={busy} onClick={()=>void pdf(s)}>Download PDF</Button><Button variant="secondary" onClick={()=>setReport(s)}>Report an Issue</Button></div></Card>)}
 {slip&&<Modal isOpen onClose={()=>setParams({})} title="Your payslip" size="3xl"><PayslipView slip={slip}/>{slip.originalPayslipId&&<Link className="mt-3 block text-indigo-600 dark:text-indigo-300" to={`/payroll/payslips?slip=${slip.originalPayslipId}`}>View original payslip</Link>}<div className="mt-5 flex flex-wrap gap-3"><Button disabled={busy} onClick={()=>void pdf(slip)}>Download PDF</Button><Button variant="secondary" onClick={()=>{setReport(slip);setParams({});}}>Report an Issue</Button></div></Modal>}
 {report&&<ReportPayrollIssue slip={report} onClose={()=>setReport(null)}/>}
 </div>;
}
