import React,{useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import {useAuth} from '../../hooks/useAuth';
import SetupChecklistLink from './SetupChecklistLink';
import {grossContext,grossRuns,GrossScope,RunSummary} from './grossPay';
import {netWorkspace,saveNetReview,prepareNet,getNetRun,recordLoan,initialNetInputs,NetWorkspace,NetInputs,NetRun,Loan} from './netPay';
import {downloadNetWorkbook,importNetWorkbook} from './netWorkbook';
const input='mt-1 block w-full rounded border border-gray-300 bg-white p-2 dark:bg-slate-800 dark:border-slate-600';
const Field:React.FC<{label:string;value:string;onChange:(v:string)=>void;type?:string}>=({label,value,onChange,type='text'})=><label className="block text-sm">{label}<input type={type} className={input} required value={value} maxLength={1000} onChange={e=>onChange(e.target.value)}/></label>;
export default function NetPayPage(){
 const {user}=useAuth();const [scopes,setScopes]=useState<GrossScope[]>([]);const [scopeId,setScopeId]=useState('');const [grossId,setGrossId]=useState('');const [list,setList]=useState<RunSummary[]>([]);const [w,setW]=useState<NetWorkspace|null>(null);const [run,setRun]=useState<NetRun|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const seq=useRef(0);const scope=scopes.find(s=>s.id===scopeId);
 useEffect(()=>{let active=true;setScopes([]);setScopeId('');setW(null);setRun(null);void grossContext().then(d=>{if(active)setScopes(d.scopes);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;++seq.current;};},[user?.id]);
 useEffect(()=>{const n=++seq.current;setList([]);setGrossId('');setW(null);setRun(null);if(scope?.canView)void grossRuns(scopeId).then(d=>{if(n===seq.current)setList(d);}).catch(e=>{if(n===seq.current)setError(e.message);});},[scopeId,scope?.canView]);
 async function openGross(id:string){const n=++seq.current;setGrossId(id);setW(null);setRun(null);setError('');setNotice('');if(!id)return;setBusy(true);try{const d=await netWorkspace(id);if(n===seq.current)setW(d);}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Review unavailable.');}finally{if(n===seq.current)setBusy(false);}}
 async function action(fn:()=>Promise<unknown>,openResult=false){const n=++seq.current;setBusy(true);setError('');setNotice('');setRun(null);try{const id=await fn();const d=await netWorkspace(grossId);const r=openResult?await getNetRun(String(id)):null;if(n===seq.current){setW(d);setRun(r);setNotice(openResult?'Shadow take-home-pay review saved. No payment or loan posting was made.':'Finance review recorded. Prepare net pay to check all inputs and reconcile amounts.');}}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Action failed.');}finally{if(n===seq.current)setBusy(false);}}
 async function openRun(id:string){const n=++seq.current;setBusy(true);setError('');setRun(null);try{const r=await getNetRun(id);if(n===seq.current)setRun(r);}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Review unavailable.');}finally{if(n===seq.current)setBusy(false);}}
 return <div className="space-y-6 text-gray-800 dark:text-slate-200"><div><h1 className="text-2xl font-bold">Take-home Pay Review</h1><p className="mt-1">Review statutory deductions, withholding, authorized deductions and loan projections from a current gross Payroll Register. Live payroll remains disabled.</p></div><SetupChecklistLink/>
 {error&&<p role="alert" className="whitespace-pre-wrap rounded border border-red-300 p-3 text-red-700 dark:text-red-300">{error}</p>}{notice&&<p role="status" className="rounded border border-green-300 p-3">{notice}</p>}
 <Card title="Choose the gross-pay version"><label>Business unit<select className={input} value={scopeId} disabled={busy} onChange={e=>{setScopeId(e.target.value);setError('');setNotice('');}}><option value="">Choose a scope</option>{scopes.filter(s=>s.canView||s.canManage).map(s=><option key={s.id} value={s.id}>{s.name} · {s.mode}</option>)}</select></label>
 {!scope?.canView&&<p className="mt-3">Salary review needs an assigned payroll duty and existing compensation/attendance permissions. <Link className="text-indigo-600" to="/payroll/access">Payroll Access</Link></p>}
 {scope?.canView&&<label className="mt-4 block">Saved gross Payroll Register<select className={input} value={grossId} disabled={busy} onChange={e=>void openGross(e.target.value)}><option value="">Choose a gross-pay version</option>{list.map(r=><option key={r.id} value={r.id}>{r.from}–{r.to} · version {r.version}</option>)}</select>{list.length===0&&<p className="mt-2">Waiting for a reviewed cutoff in <Link className="text-indigo-600" to="/payroll/gross-pay">Gross Pay Review</Link>.</p>}</label>}
 </Card>
 {w&&<><Card title="Reviewed sources"><p>Gross total: PHP {w.gross.result.gross} · {w.gross.result.employees.length} employees</p><p className="mt-2">Finance-reviewed rows: {w.review?.inputs.employees.length||0} / {w.gross.result.employees.length}. Any remaining row needs an authorized reviewer other than that employee.</p><p className={`mt-2 ${w.gross.current?'text-green-700':'text-red-700'}`}>{w.gross.current?'Gross source checks passed.':`Gross inputs changed. Recalculate gross first. ${w.gross.staleReason||''}`}</p><p className="mt-3 text-sm">Rules verified September 6, 2026 for covered employee payments January 6–December 31, 2026. Finance confirms applicability and monthly bases. Contractor fees, fringe-benefit-tax cases, annual settlement and released payslips require their separate review.</p><div className="mt-2 flex flex-wrap gap-4 text-sm text-indigo-600"><a href="https://www.sss.gov.ph/sss-contribution-table/" target="_blank" rel="noreferrer">SSS schedule</a><a href="https://www.philhealth.gov.ph/circulars/2019/circ2019-0009.pdf" target="_blank" rel="noreferrer">PhilHealth rules</a><a href="https://www.dbm.gov.ph/wp-content/uploads/Issuances/2024/Circular-Letter/CIRCULAR-LETTER-NO-2024-2-DATED-FEBRUARY-01-2024.pdf" target="_blank" rel="noreferrer">Pag-IBIG schedule</a><a href="https://bir-cdn.bir.gov.ph/local/pdf/Annex%20E%20RR%2011-2018.pdf" target="_blank" rel="noreferrer">BIR withholding table</a><a href="https://bir-cdn.bir.gov.ph/BIR/pdf/RR%20No.%2029-2025.pdf" target="_blank" rel="noreferrer">Benefit exemption limits</a></div></Card>
 {w.canReview?<ReviewForm key={`${w.gross.id}:${w.review?.id||'new'}`} w={w} busy={busy} onWorking={setBusy} save={(p,ref)=>action(()=>saveNetReview(grossId,p,ref))}/>:<Card title="Finance input review"><p>{w.review?'Finance review is recorded.':'Waiting for the assigned Finance reviewer to record contribution bases, tax treatment and opening balances.'} Authorize Finance and existing compensation-edit permission are required.</p></Card>}
 <Card title="Recorded loan balances"><p className="text-sm">Approved openings and reconciliations are preserved. Shadow deductions show projected balances only; they never reduce these actual balances.</p>{w.loans.length===0?<p className="mt-2">No reviewed loan balances recorded. Finance must confirm loan and deduction completeness.</p>:<div className="overflow-x-auto"><table className="mt-3 w-full text-left text-sm"><thead><tr>{['Employee / account','As of','Balance / installment (PHP)','Source / version'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{w.loans.map(l=><tr key={l.id} className="border-t"><td className="p-2">{w.gross.result.employees.find(e=>e.employeeId===l.employee_id)?.employeeName}<p>{l.account_ref}</p></td><td className="p-2">{l.as_of}</td><td className="p-2">{l.balance} / {l.installment}</td><td className="p-2">{l.source_ref} · {l.revision}</td></tr>)}</tbody></table></div>}</Card>
 <Card title="Prepare the internal net Payroll Register"><Field label="Preparation reason / checked payroll reference" value={reason} onChange={setReason}/><p className="my-3 text-sm">Requires a current Finance review and shadow enabled for this BU and its parent. Changed gross, employee statutory data, prior versions or loan openings require a fresh calculation. Repeating the same inputs reopens the same result.</p><Button disabled={busy||!scope?.canPrepare||!scope?.canCalculate||!w.gross.current||!w.review||w.review.inputs.employees.length!==w.gross.result.employees.length||reason.trim().length<3} onClick={()=>void action(()=>prepareNet(grossId,reason),true)}>Prepare take-home-pay review</Button>{!scope?.canCalculate&&<p className="mt-2">Processing is off. The access manager can enable the selected BU’s shadow review in <Link to="/payroll/gross-pay" className="text-indigo-600">Gross Pay Review</Link>.</p>}</Card>
 <Card title="Saved take-home-pay versions">{w.runs.length===0?<p>No net-pay reviews saved yet.</p>:w.runs.map(r=><div key={r.id} className="flex flex-wrap justify-between gap-3 border-t py-3"><span>{r.from}–{r.to} · version {r.version} · payday {r.payDate}</span><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void openRun(r.id)}>Open and check sources</Button></div>)}</Card></>}
 {run&&<Card title={`Internal net PR · version ${run.version}`}><p className={run.current?'text-green-700':'text-red-700'}>{run.current?'Saved inputs are current.':`Inputs changed — recalculate the affected versions. ${run.staleReason||''}`}</p><div className="my-4 grid gap-3 sm:grid-cols-4">{[['Gross',run.result.gross],['Employee deductions',run.result.deductions],['Take-home pay',run.result.net],['Employer cost in addition',run.result.employer]].map(([label,value])=><div key={label}><p className="text-sm">{label}</p><strong>PHP {value}</strong></div>)}</div><p className="mb-3"><Link className="text-indigo-600" to={`/payroll/approvals?net=${run.id}`}>Submit this version for payroll approval</Link></p><p>Payday {run.payDate} · contribution month {run.contributionMonth} · cutoff {run.cutoff}</p><p className="mt-2 text-sm">Internal review only. No employee payslip has been released and no loan or payment has been posted.</p><p className="mt-2 text-sm">Finance source: {run.reviewRef}</p>{run.result.employees.map(e=><details key={e.employeeId} className="mt-4 border-t pt-3"><summary className="cursor-pointer font-semibold">{e.employeeName} · PHP {e.net} take-home · Explain</summary><p className="mt-2">Gross {e.gross} − employee deductions {e.deductions} = net {e.net}. Employer share {e.employer} is separate.</p><div className="overflow-x-auto"><table className="mt-3 w-full text-left text-sm"><thead><tr>{['Contribution','Monthly due','Earlier cutoff','This cutoff'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{e.contributions.map(c=><tr key={c.label} className="border-t"><td className="p-2">{c.label.replace('EE',' · employee').replace('ER',' · employer')}</td><td className="p-2">{c.monthly}</td><td className="p-2">{c.prior}</td><td className="p-2">{c.amount}</td></tr>)}</tbody></table></div><p className="mt-3 text-sm">Withholding {e.tax}: {e.taxExplanation.method.replaceAll('_',' ')}. Taxable regular {e.taxExplanation.regular}, supplementary {e.taxExplanation.supplement}, exempt {e.taxExplanation.exempt}; prior taxable {e.taxExplanation.priorTaxable}, tax withheld {e.taxExplanation.priorWithheld}, {e.taxExplanation.priorPeriods} prior periods.</p>{e.loans.map(l=><p key={l.account} className="mt-2 text-sm">Loan {l.account}: available {l.balance}, installment {l.installment}, deduct {l.amount}, defer {l.deferred}, projected balance {l.projectedBalance}. {l.sourceRef}</p>)}{e.otherDeductions.map((d,i)=><p key={i} className="mt-2 text-sm">{d.label}: deduct {d.amount}, defer {d.deferred}. {d.sourceRef}</p>)}</details>)}</Card>}
 </div>;
}
const ReviewForm:React.FC<{w:NetWorkspace;busy:boolean;onWorking:(v:boolean)=>void;save:(p:NetInputs,ref:string)=>Promise<void>}>=({w,busy,onWorking,save})=>{
 const [p,setP]=useState<NetInputs>(()=>initialNetInputs(w));const [ref,setRef]=useState(w.review?.sourceRef||'');const [confirmed,setConfirmed]=useState(false);const [working,setWorking]=useState(false);const [error,setError]=useState('');const [loans,setLoans]=useState<Loan[]>([]);const [loanStatus,setLoanStatus]=useState<Record<string,string>>({});const [imported,setImported]=useState(Boolean(w.review));
 const disabled=busy||working;const change=(k:keyof NetInputs,v:string)=>{setP(prev=>({...prev,[k]:v}));setConfirmed(false);};
 async function download(){setWorking(true);onWorking(true);setError('');try{await downloadNetWorkbook(w,p);}catch(e){setError(e instanceof Error?e.message:'Workbook could not be downloaded.');}finally{setWorking(false);onWorking(false);}}
 async function upload(file:File){setWorking(true);onWorking(true);setError('');setConfirmed(false);try{const d=await importNetWorkbook(file,w,p);setP(d.inputs);setLoans(d.loans);setLoanStatus({});setImported(true);}catch(e){setError(e instanceof Error?e.message:'Workbook could not be read.');}finally{setWorking(false);onWorking(false);}}
 async function saveLoans(){setWorking(true);onWorking(true);setError('');const next={...loanStatus};try{for(const l of loans){const key=`${l.employee_id}:${l.account_ref}`;if(next[key]==='Recorded')continue;try{await recordLoan(l);next[key]='Recorded';}catch(e){next[key]=e instanceof Error?e.message:'Not recorded';}setLoanStatus({...next});}}finally{setWorking(false);onWorking(false);}}
 return <Card title="Finance review — all employees in one workbook"><p className="text-sm">Download the workbook, fill the reviewed values for all employees, then import it for review. Import alone saves nothing. Your own pay row requires another Finance reviewer; their existing approval is retained only while that row and the review policy remain unchanged. Missing schedules and payroll duties remain on the team checklist.</p><div className="mt-3 flex flex-wrap items-center gap-4"><Button variant="secondary" disabled={disabled} onClick={()=>void download()}>Download review workbook</Button><label className="text-sm">Import completed workbook<input className={input} type="file" accept=".xlsx" disabled={disabled} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label></div>
 {error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}
 {imported&&<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Employee','Monthly bases: SSS / PH / HDMF','Tax lines / deductions','Reviewed sources'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{p.employees.map(e=><tr key={e.employeeId} className="border-t"><td className="p-2">{w.gross.result.employees.find(x=>x.employeeId===e.employeeId)?.employeeName}</td><td className="p-2">{e.sssBase} / {e.philhealthBase} / {e.pagibigBase}</td><td className="p-2"><details><summary>{e.taxLines.length} tax lines; {e.deductions.length} deductions</summary>{e.taxLines.map((l,i)=><p key={i}>{w.gross.result.employees.find(x=>x.employeeId===e.employeeId)?.lines[i]?.label}: taxable {l.taxable} · {l.kind} · {l.exemptionRef}</p>)}{e.deductions.map((d,i)=><p key={i}>{d.label}: {d.amount} · {d.sourceRef}</p>)}</details></td><td className="p-2"><p>{e.sourceRef}</p><p>{e.openingRef}</p><p>Prior taxable {e.openingTaxable}; withheld {e.openingWithheld}; periods {e.openingPeriods}</p></td></tr>)}</tbody></table></div>}
 {loans.length>0&&<div className="mt-4 rounded border p-3"><p className="font-medium">Imported loan openings / reconciliations</p><p className="text-sm">Record only checked actual balances and the authorized installment. Each row saves separately and preserves prior records. A failed row stays listed for correction.</p>{loans.map(l=>{const key=`${l.employee_id}:${l.account_ref}`;return <p key={key} className="mt-2 text-sm">{w.gross.result.employees.find(e=>e.employeeId===l.employee_id)?.employeeName} · {l.account_ref} · {l.as_of} · balance {l.balance}, installment {l.installment} · {l.source_ref} — {loanStatus[key]||'Not recorded'}</p>;})}<Button className="mt-3" variant="secondary" disabled={disabled} onClick={()=>void saveLoans()}>Record reviewed loan balances</Button></div>}
 <form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();void save(p,ref);}}><fieldset disabled={disabled} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Reviewed payday" type="date" value={p.payDate} onChange={v=>change('payDate',v)}/><Field label="Contribution month (first day of month)" type="date" value={p.contributionMonth} onChange={v=>change('contributionMonth',v)}/></div>
 <label className="block">Cutoff within that contribution month<select required className={input} value={p.cutoff} onChange={e=>change('cutoff',e.target.value)}><option value="">Choose</option><option value="1">First cutoff</option><option value="2">Second cutoff — monthly due less earlier deduction</option></select></label>
 <label className="block">Immediately preceding net review<select className={input} value={p.previousRunId} onChange={e=>change('previousRunId',e.target.value)}><option value="">Start from Finance-reviewed opening balances</option>{w.runs.filter(r=>r.to<w.gross.from).map(r=><option key={r.id} value={r.id}>{r.from}–{r.to} · v{r.version} · payday {r.payDate}</option>)}</select></label><p className="text-sm">A linked prior cutoff supplies YTD and projected loan deductions. For a midyear start, review opening taxable income, withholding, prior periods and benefits used, including previous employers. Starting at the second cutoff also requires reviewed month-to-date contribution amounts.</p>
 <div className="grid gap-3 sm:grid-cols-3">{['sss','philhealth','pagibig'].map(k=><label key={k}>{k.toUpperCase()} first-cutoff share<select required className={input} value={p.allocation[k]} onChange={e=>{setP(prev=>({...prev,allocation:{...prev.allocation,[k]:e.target.value}}));setConfirmed(false);}}><option value="">Choose approved allocation</option><option value="0">0% (all on second cutoff)</option><option value="0.5">50%</option><option value="1">100% (reconcile on second)</option></select></label>)}</div>
 <label className="block">Approved insufficient-net policy<select required className={input} value={p.insufficientNet} onChange={e=>change('insufficientNet',e.target.value)}><option value="">Choose approved policy</option><option value="block">Block and reconcile before payroll</option><option value="defer_authorized">Defer unpaid authorized loans/deductions</option></select></label><p className="text-sm">Under deferral, statutory deductions come first, then loans in account order, then other deductions in worksheet order. Statutory deductions exceeding gross always block the run.</p>
 <Field label="Approved payday, allocation and insufficient-net policy reference" value={p.policyRef} onChange={v=>change('policyRef',v)}/><Field label="Finance approval / checked payroll source reference" value={ref} onChange={v=>{setRef(v);setConfirmed(false);}}/>
 <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified this rule set’s applicability, monthly bases, every taxable/exempt portion and benefit limit, statutory HRIS details, all YTD/opening balances and authorized loans/deductions. Unsupported fringe-benefit-tax or separate fee cases require review before inclusion.</label>
 <Button type="submit" disabled={disabled||!confirmed||!imported||!w.gross.current||loans.some(l=>loanStatus[`${l.employee_id}:${l.account_ref}`]!=='Recorded')}>Record Finance review</Button></fieldset></form>
 </Card>;
};
