import {assertArrangementLive} from './payPackageImport';
import {supabase} from '../../services/supabaseClient';
import type {GrossRun} from './grossPay';
export const contributionKeys=['sssEE','sssER','mpfEE','mpfER','ecER','philhealthEE','philhealthER','pagibigEE','pagibigER'] as const;
export type TaxLine={taxable:string;kind:string;exemptionRef:string};
export type Deduction={label:string;amount:string;sourceRef:string;kind?:string;carryForward?:boolean};
export type NetEmployee={payBasis?:string;netTarget?:string;arrangementRef?:string;grossUpBasisRef?:string;grossUpConfirmed?:boolean;voluntaryPercent?:string;higherDeductionAuthorization?:string;higherDeductionLegalBasis?:string;employeeId:string;sssBase:string;philhealthBase:string;pagibigBase:string;sssCovered:boolean|string;philhealthCovered:boolean|string;pagibigCovered:boolean|string;coverageRef:string;openingTaxable:string;openingWithheld:string;openingPeriods:string;previousEmployer:boolean|string;cumulativeAlready:boolean|string;sourceRef:string;openingRef:string;openingContributions:Record<string,string>;taxLines:TaxLine[];deductions:Deduction[]};
export type NetInputs={ruleset:string;payDate:string;contributionMonth:string;cutoff:string;allocation:Record<string,string>;insufficientNet:string;policyRef:string;previousRunId:string;employees:NetEmployee[]};
export type Loan={id?:string;employee_id:string;account_ref:string;as_of:string;balance:string;installment:string;source_ref:string;revision?:number};
export type NetSummary={id:string;grossId:string;version:number;from:string;to:string;payDate:string};
export type NetWorkspace={gross:GrossRun;canReview:boolean;review:null|{id:string;inputs:NetInputs;sourceRef:string;approvedAt:string};loans:Loan[];runs:NetSummary[]};
export type NetResult={payBasis?:string;sourceGross?:string;companyTopUp?:string;netTarget?:string;employerTotalCost?:string;grossUpBasisRef?:string;employeeId:string;employeeName:string;gross:string;mandatory:string;tax:string;other:string;deductions:string;net:string;employer:string;contributions:{label:string;monthly:string;prior:string;amount:string}[];taxExplanation:{regular:string;supplement:string;exempt:string;method:string;priorTaxable:string;priorWithheld:string;priorPeriods:number;amount:string};loans:{account:string;balance:string;installment:string;amount:string;deferred:string;projectedBalance:string;sourceRef:string}[];otherDeductions:{label:string;amount:string;requested:string;deferred:string;sourceRef:string}[]};
export type NetRun={id:string;version:number;previousId:string|null;grossId:string;current:boolean;staleReason:string|null;from:string;to:string;payDate:string;contributionMonth:string;cutoff:string;sourceHash:string;reviewRef:string;reason:string;result:{employerTotalCost?:string;gross:string;deductions:string;net:string;employer:string;employees:NetResult[]}};
async function rpc<T>(name:string,args:Record<string,unknown>):Promise<T>{const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message);return data as T;}
export const netWorkspace=(id:string)=>rpc<NetWorkspace>('get_payroll_net_workspace',{p_gross_id:id});
export const saveNetReview=(id:string,inputs:NetInputs,ref:string)=>{inputs.employees.forEach(e=>assertArrangementLive(e.payBasis||'gross'));return rpc<string>('save_payroll_net_review',{p_gross_id:id,p_inputs:inputs,p_source_ref:ref});};
export const prepareNet=(id:string,reason:string)=>rpc<string>('prepare_payroll_net',{p_gross_id:id,p_reason:reason});
export const getNetRun=(id:string)=>rpc<NetRun>('get_payroll_net_run',{p_run_id:id});
export const recordLoan=(l:Loan)=>rpc<string>('record_payroll_loan_balance',{p_employee_id:l.employee_id,p_account_ref:l.account_ref,p_as_of:l.as_of,p_balance:l.balance,p_installment:l.installment,p_source_ref:l.source_ref});
export function emptyNetInputs(w:NetWorkspace):NetInputs{return {ruleset:'PH-2026-09-06',payDate:'',contributionMonth:'',cutoff:'',allocation:{sss:'',philhealth:'',pagibig:''},insufficientNet:'',policyRef:'',previousRunId:'',employees:w.gross.result.employees.map(e=>({employeeId:e.employeeId,sssBase:'',philhealthBase:'',pagibigBase:'',sssCovered:'',philhealthCovered:'',pagibigCovered:'',coverageRef:'',openingTaxable:'',openingWithheld:'',openingPeriods:'',previousEmployer:'',cumulativeAlready:'',sourceRef:'',openingRef:'',openingContributions:Object.fromEntries(contributionKeys.map(k=>[k,''])),taxLines:e.lines.map(()=>({taxable:'',kind:'',exemptionRef:''})),deductions:[]}))};}
export function initialNetInputs(w:NetWorkspace):NetInputs{const blank=emptyNetInputs(w);return w.review?{...w.review.inputs,employees:blank.employees.map(e=>w.review!.inputs.employees.find(x=>x.employeeId===e.employeeId)||e)}:blank;}
