import React,{useEffect,useMemo,useState} from 'react';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import NTEDeductionPanel from '../nte/NTEDeductionPanel';
import {getNteDeductions,ntePeso,type NTEDeduction,type NTEScopeContext} from './nteDeductions';

function ReviewDrawer({item,onClose}:{item:NTEDeduction;onClose:()=>void}){return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40" role="dialog" aria-modal="true"><div className="h-full w-full max-w-3xl overflow-y-auto bg-white p-6 shadow-2xl dark:bg-slate-900"><header className="mb-5 flex items-start justify-between gap-3"><div><h2 className="text-2xl font-bold">Review NTE deduction</h2><p>{item.employeeName} · {item.nteNumber}</p></div><button className="min-h-11 px-3 text-2xl" onClick={onClose} aria-label="Close">×</button></header><NTEDeductionPanel nteId={item.nteId}/></div></div>;}

export default function NTEDeductionApprovalPanel({scopeId,payrollDate,employees}:{scopeId:string;payrollDate:string;employees:{employeeId:string;employeeName:string;net:string}[]}){
 const [data,setData]=useState<NTEScopeContext|null>(null);const [error,setError]=useState('');const [selected,setSelected]=useState<NTEDeduction|null>(null);const [refresh,setRefresh]=useState(0);
 useEffect(()=>{let active=true;setError('');void getNteDeductions(scopeId,payrollDate).then(value=>{if(active)setData(value);}).catch(cause=>{if(active)setError((cause as Error).message);});return()=>{active=false;};},[scopeId,payrollDate,refresh]);
 const employeeIds=useMemo(()=>new Set(employees.map(employee=>employee.employeeId)),[employees]);
 const items=useMemo(()=>data?.items.filter(item=>employeeIds.has(item.employeeId))||[],[data,employeeIds]);
 const waitingSignature=items.filter(item=>item.workflowStatus==='ATD Generated — Awaiting Employee Signature').length;
 const waitingHr=items.filter(item=>item.workflowStatus==='Signed — Awaiting HR Verification').length;
 const waitingFinance=items.filter(item=>item.workflowStatus==='HR Verified — Awaiting Finance Approval').length;
 const invalid=items.filter(item=>['Blocked','Rejected','Decision Issued — ATD Pending'].includes(item.workflowStatus)||!item.generatedDocumentPath).length;
 const scheduleIssues=items.filter(item=>item.schedule?.some(row=>row.payroll_date===payrollDate&&row.status!=='Scheduled')).length;
 return <><Card title="NTE deductions"><p className="mb-3 text-sm">A blocked deduction is visible for resolution but never reduces employee net pay.</p>{error?<p role="alert" className="text-red-700">{error}</p>:!data?<p role="status">Loading protected NTE deductions…</p>:<>
   {(waitingSignature+waitingHr+waitingFinance+invalid+scheduleIssues)>0&&<section className="mb-4 rounded-2xl border border-amber-300 bg-amber-50 p-4"><h3 className="font-bold text-amber-950">Needs attention</h3><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{[['ATDs waiting for employee signature',waitingSignature],['Signed ATDs waiting for HR',waitingHr],['Waiting for Finance approval',waitingFinance],['Invalid or missing documents',invalid],['Schedules needing correction',scheduleIssues]].map(([label,count])=><div className="rounded-xl bg-white p-3" key={String(label)}><strong className="text-xl">{count}</strong><p className="text-xs">{label}</p></div>)}</div></section>}
   {items.length===0?<p>No NTE deductions are linked to employees in this payroll.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr>{['Employee','Net pay','NTE deduction','Current balance','Remaining balance','Status','Review'].map(heading=><th className="p-2" key={heading}>{heading}</th>)}</tr></thead><tbody>{items.map(item=>{const employee=employees.find(row=>row.employeeId===item.employeeId);const schedule=item.schedule?.find(row=>row.payroll_date===payrollDate);const ready=item.workflowStatus==='Approved for Payroll'&&schedule?.status==='Scheduled';const amount=ready?Math.min(Number(schedule.scheduled_amount),Number(item.currentBalance)):0;return <tr className="border-t" key={item.id}><td className="p-2 font-semibold">{item.employeeName}<span className="block text-xs font-normal">{item.nteNumber}</span></td><td className="p-2">{employee?ntePeso(employee.net):'—'}</td><td className="p-2">{amount?ntePeso(amount):'—'}</td><td className="p-2">{item.canViewSensitive?ntePeso(item.currentBalance):'Restricted'}</td><td className="p-2">{item.canViewSensitive?ntePeso(Math.max(0,Number(item.currentBalance)-amount)):'Restricted'}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${ready?'bg-emerald-100 text-emerald-800':'bg-red-100 text-red-800'}`}>{ready?'Approved for Payroll':`Blocked: ${item.workflowStatus}`}</span></td><td className="p-2"><Button size="sm" variant="secondary" onClick={()=>setSelected(item)}>Review</Button></td></tr>;})}</tbody></table></div>}
  </>}</Card>{selected&&<ReviewDrawer item={selected} onClose={()=>{setSelected(null);setRefresh(value=>value+1);}}/>}</>;
}
