import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import NTEDeductionPanel from '../nte/NTEDeductionPanel';
import {getNteDeductions,ntePeso,type NTEDeduction,type NTEScopeContext} from './nteDeductions';

export default function NTEDeductionList({scopeId}:{scopeId:string}){
 const [data,setData]=useState<NTEScopeContext|null>(null);const [error,setError]=useState('');const [selected,setSelected]=useState<NTEDeduction|null>(null);const [refresh,setRefresh]=useState(0);
 useEffect(()=>{let active=true;setError('');void getNteDeductions(scopeId).then(value=>{if(active)setData(value);}).catch(cause=>{if(active)setError((cause as Error).message);});return()=>{active=false;};},[scopeId,refresh]);
 const items=data?.items||[];const approved=useMemo(()=>items.filter(item=>item.workflowStatus==='Approved for Payroll'),[items]);const attention=items.length-approved.length;
 return <><Card title="NTE-related deductions"><p className="mb-4 text-sm text-slate-500">Created only from an approved and acknowledged Notice of Decision. NOD acknowledgment alone never authorizes payroll deduction.</p>{error?<p role="alert" className="text-red-700">{error}</p>:!data?<p role="status">Loading NTE deduction records…</p>:<><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p className="text-xs">NTE deductions</p><strong className="text-2xl">{items.length}</strong></div><div className="rounded-xl bg-emerald-50 p-3 text-emerald-900"><p className="text-xs">Approved for payroll</p><strong className="text-2xl">{approved.length}</strong></div><div className="rounded-xl bg-amber-50 p-3 text-amber-950"><p className="text-xs">Needs attention</p><strong className="text-2xl">{attention}</strong></div></div>{items.length===0?<p className="mt-4">No NTE deductions are available in this payroll scope.</p>:<div className="mt-4 space-y-3">{items.map(item=><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4" key={item.id}><div><p className="font-semibold">{item.employeeName} · {item.nteNumber}</p><p className="text-sm">{item.canViewSensitive?`${ntePeso(item.currentBalance)} remaining · `:''}{item.workflowStatus}</p></div><div className="flex gap-2"><Link className="inline-flex min-h-10 items-center text-sm font-semibold text-violet-700 underline" to={`/feedback/nte/${item.nteId}`}>Open NTE</Link><Button size="sm" variant="secondary" onClick={()=>setSelected(item)}>Review deduction</Button></div></div>)}</div>}</>}</Card>
  {selected&&<div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40" role="dialog" aria-modal="true"><div className="h-full w-full max-w-3xl overflow-y-auto bg-white p-6 shadow-2xl dark:bg-slate-900"><header className="mb-5 flex justify-between"><div><h2 className="text-2xl font-bold">NTE deduction detail</h2><p>{selected.employeeName} · {selected.nteNumber}</p></div><button className="min-h-11 px-3 text-2xl" aria-label="Close" onClick={()=>{setSelected(null);setRefresh(v=>v+1);}}>×</button></header><NTEDeductionPanel nteId={selected.nteId}/></div></div>}
 </>;
}
