import {arrangements,assertArrangementLive,NET_ARRANGEMENTS_LIVE} from './payPackageImport';
import PayPackageBatchUpload from './PayPackageBatchUpload';
import {EmployeePolicyPanel} from './ConfirmedPolicyPanels';
import React, {useCallback,useEffect,useId,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import {useAuth} from '../../hooks/useAuth';
import {emptyTreatment,fetchPayDirectory,fetchPayPackages,newComponent,PayComponent,PayContext,PayPackage,reviewPayPackage,savePayPackage,savePaySettings,Treatment,treatmentFields,treatmentPending,verifyPaymentDetails} from './payPackages';

const fieldClass='mt-1 block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 dark:border-slate-600 dark:bg-slate-700 dark:text-white';
const money=(value:string|number|null|undefined)=>value==null?'Not recorded':`PHP ${Number(value).toLocaleString('en-PH',{maximumFractionDigits:6})}`;
const Field:React.FC<{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean;readOnly?:boolean;children?:React.ReactNode}>=({label,value,onChange,type='text',required,readOnly,children})=>{
 const id=useId();return <label htmlFor={id} className="block text-sm font-medium">{label}{children?<select id={id} className={fieldClass} value={value} onChange={e=>onChange(e.target.value)} required={required} disabled={readOnly}>{children}</select>:<input id={id} className={fieldClass} value={value} type={type} step={type==='number'?'0.000001':undefined} min={type==='number'?'0':undefined} maxLength={1000} onChange={e=>onChange(e.target.value)} required={required} readOnly={readOnly}/>}</label>;
};
const Treatments:React.FC<{value:Treatment;onChange:(value:Treatment)=>void}>=({value,onChange})=><div className="grid gap-3 sm:grid-cols-3">{treatmentFields.map(([key,label])=><Field key={key} label={label} value={value[key]||'unreviewed'} onChange={v=>onChange({...value,[key]:v})}><option value="unreviewed">Not yet reviewed</option><option value="included">Included / applies</option><option value="excluded">Excluded / does not apply</option><option value="rule_defined">Defined by referenced policy</option></Field>)}</div>;

const PayPackagesPage:React.FC=()=>{
 const {user}=useAuth(); const [params,setParams]=useSearchParams();
 const [directory,setDirectory]=useState<{id:string;name:string;employeeCode:string}[]>([]);
 const [employeeId,setEmployeeId]=useState(params.get('employee')||'');
 const [data,setData]=useState<PayContext|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const sequence=useRef(0);
 const refresh=useCallback(async()=>{const n=++sequence.current;setLoading(true);setError('');setData(null);try{const list=await fetchPayDirectory();if(n!==sequence.current)return;setDirectory(list);const id=employeeId||list[0]?.id;if(!id){setLoading(false);return;}if(!employeeId)setEmployeeId(id);const next=await fetchPayPackages(id);if(n===sequence.current)setData(next);}catch(e){if(n===sequence.current)setError(e instanceof Error?e.message:'Pay packages could not be loaded.');}finally{if(n===sequence.current)setLoading(false);}},[employeeId,user?.id]);
 useEffect(()=>{void refresh();const onFocus=()=>void refresh();window.addEventListener('focus',onFocus);return()=>{++sequence.current;window.removeEventListener('focus',onFocus);};},[refresh]);
 const run=async(fn:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');setNotice('');try{await fn();setNotice(message);await refresh();}catch(e){setError(e instanceof Error?e.message:'The change could not be saved.');}finally{setBusy(false);}};
 return <div className="space-y-6 text-gray-800 dark:text-slate-200">
  <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Pay Packages & Salary History</h1><p className="mt-1 text-sm text-gray-500 dark:text-slate-400">Review dated pay, keep prior versions and record the supporting approval.</p></div><span className="self-start rounded-full bg-amber-100 px-3 py-1 text-sm font-medium text-amber-900">Payroll processing off</span></div>
  <Card><Field label="Employee" value={employeeId} onChange={id=>{setEmployeeId(id);setParams({employee:id});setNotice('');}}><option value="">Select an employee</option>{directory.map(u=><option value={u.id} key={u.id}>{u.name} · {u.employeeCode}</option>)}</Field><p className="mt-3 text-sm">Salary work requires a scoped payroll duty and existing HRIS compensation permission. <Link className="text-indigo-600 dark:text-indigo-300" to="/payroll/access">Manage Payroll Access</Link></p></Card>
  <PayPackageBatchUpload key={user?.id} directory={directory} onSaved={()=>void refresh()}/>
  {error&&<Card><p role="alert" className="text-red-700 dark:text-red-300">{error}</p><Button className="mt-3" onClick={()=>void refresh()}>Refresh</Button></Card>}{notice&&<p role="status" className="text-green-700 dark:text-green-300">{notice}</p>}
  {loading?<p role="status">Loading pay packages…</p>:data?<PackageWorkspace key={data.employeeId} data={data} busy={busy} run={run}/>:<Card><p>No accessible employee records.</p></Card>}
 </div>;
};

const PackageWorkspace:React.FC<{data:PayContext;busy:boolean;run:(fn:()=>Promise<unknown>,message:string)=>Promise<void>}>=({data,busy,run})=>{
 const [effective,setEffective]=useState('');const [base,setBase]=useState('');const [rate,setRate]=useState('');const [source,setSource]=useState('');const [reason,setReason]=useState('');
 const [components,setComponents]=useState<PayComponent[]>([]);const [treatment,setTreatment]=useState<Treatment>(emptyTreatment());const [scope,setScope]=useState('');
 const [stream,setStream]=useState('employee_payroll');const [engagement,setEngagement]=useState('');const [taxRef,setTaxRef]=useState('');const [replaces,setReplaces]=useState('');const [formOpen,setFormOpen]=useState(false);const [sourcePan,setSourcePan]=useState('');
 const [reviewReason,setReviewReason]=useState('');const [bankRef,setBankRef]=useState('');const [asOf,setAsOf]=useState('');
 const editScopes=data.scopes.filter(s=>s.canEdit);const scopeId=editScopes.some(s=>s.id===scope)?scope:editScopes[0]?.id||'';
 const canEdit=editScopes.length>0;
 const selectSource=(id:string)=>{setSourcePan(id);const s=data.sources.find(s=>(s.id||'')===id);if(!s)return;setBase(String(s.baseAmount??''));if(s.rateType)setRate(s.rateType);if(s.effectiveFrom)setEffective(s.effectiveFrom);setComponents(old=>[...old.filter(c=>!c.legacyField),...(['deminimis','reimbursable'] as const).filter(k=>Number(s[k])>0).map(k=>({...newComponent(),name:k,legacyField:k,amount:String(s[k])}))]);};
 const copy=(p?:PayPackage)=>{setFormOpen(true);setEffective('');setSource('');setReason('');setReplaces('');setScope(p?.scope_id||scopeId);setSourcePan(p?.source_pan_id||'');setBase(String(p?.base_amount??data.sources[0]?.baseAmount??''));setRate(p?.rate_type||data.legacy.rateType||'');setTreatment(p?.treatment||emptyTreatment());setStream(p?.stream||'employee_payroll');setEngagement(p?.engagement_key==='employee'?'':p?.engagement_key||'');setTaxRef(p?.tax_profile_ref||'');
  setComponents(p?p.components.map(c=>({...c})):[]);if(!p||p.stream==='employee_payroll')selectSource(p?.source_pan_id||'');};
 const visiblePackages=asOf?data.packages.filter(p=>p.status==='approved'&&p.effective_from<=asOf&&(!p.effective_until||asOf<p.effective_until)):data.packages;
 return <>
 <EmployeePolicyPanel key={data.employeeId} employeeId={data.employeeId} canApprove={data.canApprove}/>
 <Card title="Current HRIS record"><dl className="grid gap-4 sm:grid-cols-3"><div><dt className="text-sm text-gray-500">Recorded rate</dt><dd>{money(data.legacy.rateAmount)} / {data.legacy.rateType||'unit missing'}</dd></div><div><dt className="text-sm text-gray-500">Legacy basic field</dt><dd>{money(data.legacy.salaryBasic)}</dd></div><div><dt className="text-sm text-gray-500">Salary source</dt><dd>Existing HRIS / approved PAN</dd></div></dl>
 <p className="mt-4 text-sm">Use the existing HRIS/PAN workflow to change base salary or its existing allowances. This page records reviewed snapshots and additional payroll components, preserving one writer for each amount.</p>
 {data.sourceMatches===false&&<p role="alert" className="mt-3 text-sm text-amber-800 dark:text-amber-300">The current HRIS pay differs from the latest applicable package. Reconcile a new dated snapshot before using it for payroll.</p>}
 {!data.managed&&<p className="mt-4 text-sm">This is a preview of existing records. Confirm the amount, rate unit and effective date against the approved source before importing. A zero legacy basic field is not proof of zero salary.</p>}
 {canEdit&&<Button className="mt-4" onClick={()=>copy()}>{data.managed?'Prepare a dated change':'Review & prepare initial package'}</Button>}</Card>
 {formOpen&&canEdit&&<Card title="Prepare pay package"><form className="space-y-4" onSubmit={e=>{e.preventDefault();try{assertArrangementLive(treatment.payBasis||'gross');}catch(error){void run(()=>Promise.reject(error),'');return;}void run(()=>savePayPackage(data.employeeId,scopeId,{effectiveFrom:effective,rateType:rate,baseAmount:base,components,treatment,sourceRef:source,sourcePanId:stream==='employee_payroll'?sourcePan||null:null,reason,stream,engagementKey:stream==='employee_payroll'?'employee':engagement,taxProfileRef:taxRef,replacesId:replaces||null},data.sourceHash!),'Draft saved for HR authorization.');}}><fieldset disabled={busy} className="space-y-4">
 {stream==='employee_payroll'&&<><Field label="Approved salary source" value={sourcePan} onChange={selectSource}>{data.sources.map(s=><option key={s.id||'current'} value={s.id||''}>{s.label}</option>)}</Field><p className="text-sm">Base pay and existing allowances must match this source. For a PAN, use its effective date and confirm the amount unit from the supporting document.</p></>}
 <div className="grid gap-4 sm:grid-cols-2"><Field label="Business unit / payroll group" value={scopeId} onChange={setScope}>{editScopes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Field><Field label="Pay stream" value={stream} onChange={v=>{setStream(v);if(v==='employee_payroll')selectSource(sourcePan);}}><option value="employee_payroll">Employee payroll</option><option value="professional_fee">Separate professional fees</option></Field>
 {stream==='professional_fee'&&<><Field label="Distinct engagement reference" value={engagement} onChange={setEngagement} required/><Field label="Reviewed engagement / tax-profile document" value={taxRef} onChange={setTaxRef} required/></>}
 <Field label="Effective from (inclusive)" type="date" value={effective} onChange={setEffective} required/><Field label="Basic pay / fee amount (PHP)" type="number" value={base} onChange={setBase} required readOnly={stream==='employee_payroll'}/>
 <Field label="Amount unit" value={rate} onChange={setRate} required readOnly={stream==='employee_payroll'&&!sourcePan}><option value="">Select the approved unit</option>{['Monthly','Daily','Hourly'].map(v=><option key={v}>{v}</option>)}</Field>
 <Field label="Correction of an existing effective date" value={replaces} onChange={id=>{setReplaces(id);const p=data.packages.find(x=>x.id===id);if(p)setEffective(p.effective_from);}}><option value="">New effective date</option>{data.packages.filter(p=>p.status==='approved'&&p.engagement_key===(stream==='employee_payroll'?'employee':engagement)).map(p=><option value={p.id} key={p.id}>{p.effective_from} · {money(p.base_amount)}</option>)}</Field></div>
 <div className="rounded border p-4 space-y-3"><h3 className="font-semibold">Gross / net agreement and tax review</h3>{!NET_ARRANGEMENTS_LIVE&&<p className="rounded bg-amber-100 p-3 text-sm text-amber-950">Net/custom arrangement saving is pending approval of the production payroll-engine update.</p>}<p className="text-sm">Net is not tax exempt. Keep the approved HRIS basic amount above unchanged; record the agreed target separately. Targets use the Amount unit above and are before loans/other deductions. Finance reviews cutoff allocation and final contribution bases.</p><Field label="Salary arrangement" value={treatment.payBasis||'gross'} onChange={v=>setTreatment({...treatment,payBasis:v,netTarget:v==='gross'?'':treatment.netTarget||''})}>{Object.entries(arrangements).map(([label,value])=><option key={value} value={value}>{label}</option>)}</Field>{(treatment.payBasis||'gross')!=='gross'&&<>{treatment.payBasis!=='custom_review'&&<Field label="Agreed net amount (PHP, in the unit above)" type="number" value={treatment.netTarget||''} onChange={v=>setTreatment({...treatment,netTarget:v})} required/>}<Field label="Approved arrangement document / custom terms" value={treatment.arrangementRef||''} onChange={v=>setTreatment({...treatment,arrangementRef:v})} required/></>}<Field label="Tax treatment request (subject to HR / Finance review)" value={treatment.taxRequest||'Standard - Finance reviews'} onChange={v=>setTreatment({...treatment,taxRequest:v,tax:'unreviewed'})}>{['Standard - Finance reviews','Exemption requested - evidence required','Custom - needs review'].map(v=><option key={v}>{v}</option>)}</Field>{treatment.taxRequest&&treatment.taxRequest!=='Standard - Finance reviews'&&<Field label="Exemption legal basis, evidence and applicable limits" value={treatment.taxBasisRef||''} onChange={v=>setTreatment({...treatment,taxBasisRef:v})} required/>}<p className="text-sm">Selecting exemption does not approve it or stop withholding. Custom arrangements must be resolved before approval. Separate consultant fees keep their own withholding review.</p></div>
 <details><summary className="cursor-pointer font-medium">Basic-pay treatment</summary><p className="my-3 text-sm">Record the approved classification. Names such as “de minimis” never establish tax exemption. Leave unsettled rules as not yet reviewed.</p><Treatments value={treatment} onChange={setTreatment}/></details>
 <div className="space-y-4"><h3 className="font-semibold">Pay components</h3>{components.map((c,i)=><div key={i} className="space-y-3 rounded-lg border border-gray-200 p-4 dark:border-slate-600"><div className="grid gap-3 sm:grid-cols-2"><Field label="Component name" value={c.name} onChange={v=>setComponents(old=>old.map((x,j)=>j===i?{...x,name:v}:x))} required/><Field label="Amount (PHP)" value={c.amount} type="number" onChange={v=>setComponents(old=>old.map((x,j)=>j===i?{...x,amount:v}:x))} required/><Field label="Frequency" value={c.recurrence} onChange={v=>setComponents(old=>old.map((x,j)=>j===i?{...x,recurrence:v}:x))}><option value="recurring">Recurring</option><option value="one_time">One time</option></Field>{c.recurrence==='one_time'&&<Field label="One-time payable date" type="date" value={c.payableDate||''} onChange={v=>setComponents(old=>old.map((x,j)=>j===i?{...x,payableDate:v}:x))} required/>}</div><details><summary className="cursor-pointer text-sm">Treatment and legacy display</summary><div className="mt-3 space-y-3"><Treatments value={c} onChange={v=>setComponents(old=>old.map((x,j)=>j===i?{...x,...v}:x))}/><Field label="Existing HRIS display field" value={c.legacyField||''} onChange={v=>setComponents(old=>old.map((x,j)=>j===i?{...x,legacyField:v}:x))}><option value="">Additional component</option><option value="deminimis">De minimis</option><option value="reimbursable">Reimbursable</option></Field></div></details><Button size="sm" variant="secondary" onClick={()=>setComponents(old=>old.filter((_,j)=>j!==i))}>Remove component</Button></div>)}<Button variant="secondary" disabled={components.length>=30} onClick={()=>setComponents(old=>[...old,newComponent()])}>Add component</Button></div>
 <Field label="Approved source / document reference" value={source} onChange={setSource} required/><Field label="Reason and reconciliation notes" value={reason} onChange={setReason} required/>
 <p className="text-sm">Preview: {money(data.legacy.rateAmount)} / {data.legacy.rateType||'unknown'} currently → {money(base||null)} / {rate||'choose unit'} from {effective||'choose date'}. Saving creates a draft; HR authorization records approval. Historical and future dates do not create payments.</p>
 <Button type="submit" isLoading={busy} disabled={!scopeId||source.trim().length<3||reason.trim().length<3}>Save draft</Button><Button className="ml-3" variant="secondary" onClick={()=>setFormOpen(false)}>Close</Button>
 </fieldset></form></Card>}
 <Card title="Dated packages & prior versions"><div className="mb-4 max-w-xs"><Field label="Check pay applicable on a date" type="date" value={asOf} onChange={setAsOf}/></div>{visiblePackages.length===0?<p>{asOf?'No approved pay package covers this date. Payroll must remain blocked for that gap.':'No pay package has been approved or prepared yet.'}</p>:<div className="space-y-4">{visiblePackages.map(p=><section key={p.id} className="rounded-lg border border-gray-200 p-4 dark:border-slate-600"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{money(p.base_amount)} / {p.rate_type} <span className="text-sm font-normal">· {p.stream==='professional_fee'?`Professional fees: ${p.engagement_key}`:'Employee payroll'}</span></h3><span className="text-sm capitalize">{p.status}</span></div><p className="mt-1 text-sm">{p.effective_from} → {p.effective_until?`${p.effective_until} (exclusive)`:'next approved change'}{p.source_pan_id?' · Approved PAN':''}</p><p className="mt-2 text-sm">Source: {p.source_ref}</p><p className="text-sm">{p.reason}</p><p className="mt-2 text-sm font-medium">Arrangement: {Object.entries(arrangements).find(([,v])=>v===(p.treatment.payBasis||'gross'))?.[0]||'Needs review'}{p.treatment.netTarget? ` · Agreed net PHP ${p.treatment.netTarget} / ${p.rate_type}`:''}</p>{p.treatment.arrangementRef&&<p className="text-sm">Agreement: {p.treatment.arrangementRef}</p>}{p.treatment.taxRequest&&<p className="text-sm">Tax request: {p.treatment.taxRequest} · {p.treatment.taxBasisRef||'Finance reviews ordinary tax treatment'}</p>}
 {p.components.length>0&&<ul className="mt-3 space-y-1 text-sm">{p.components.map((c,i)=><li key={i}>{c.name}: {money(c.amount)} · {c.recurrence==='one_time'?`one time on ${c.payableDate}`:'recurring'}</li>)}</ul>}
 {(treatmentPending(p.treatment)||p.components.some(treatmentPending))&&<p className="mt-3 text-sm text-amber-800 dark:text-amber-300">Some tax, contribution or proration treatment still needs review. This package is not ready for payroll calculation.</p>}
 <details className="mt-3 text-sm"><summary className="cursor-pointer">View recorded treatments</summary><dl className="mt-2 grid gap-2 sm:grid-cols-3">{treatmentFields.map(([k,label])=><div key={k}><dt>{label}</dt><dd>{p.treatment[k]||'unreviewed'}</dd></div>)}</dl>{p.components.map((c,i)=><p className="mt-2" key={i}>{c.name}: {treatmentFields.map(([k,label])=>`${label}: ${c[k]||'unreviewed'}`).join(' · ')}</p>)}</details>
 {canEdit&&<Button size="sm" variant="secondary" className="mt-3" onClick={()=>copy(p)}>Copy into a new draft</Button>}
 {p.status==='draft'&&data.scopes.some(s=>s.id===p.scope_id&&s.canApprove)&&<div className="mt-4 space-y-3 border-t pt-3"><Field label="Review reason" value={reviewReason} onChange={setReviewReason}/><Button disabled={busy||reviewReason.trim().length<3} onClick={()=>void run(()=>reviewPayPackage(p.id,true,reviewReason),'Package approved. Prior salary history is retained.')}>Approve package</Button><Button className="ml-3" variant="secondary" disabled={busy||reviewReason.trim().length<3} onClick={()=>void run(()=>reviewPayPackage(p.id,false,reviewReason),'Draft rejected; approved pay is unchanged.')}>Reject draft</Button></div>}
 </section>)}</div>}</Card>
 {data.bank&&<Card title="Payment-instruction verification"><p>{data.bank.bankName||'Bank not recorded'} · account ending {data.bank.accountLast4||'not recorded'} · {data.bank.accountType}</p><p className="mt-2">{data.bank.verified?'Current bank details have a recorded verification.':'Current bank details have not been verified.'}</p><p className="mt-2 text-sm">Review the full details in the existing employee bank record against the supporting document. Changing that record invalidates its verification automatically.</p>{data.bank.canVerify&&<div className="mt-3 space-y-3"><Field label="Verification document / source" value={bankRef} onChange={setBankRef}/><Button disabled={busy||bankRef.trim().length<3} onClick={()=>void run(()=>verifyPaymentDetails(data.employeeId,data.bank!.fingerprint,bankRef),'Verification recorded for the current bank details.')}>Record verification</Button></div>}</Card>}
 {data.scopes.some(s=>s.canApprove)&&<SettingsCard data={data} busy={busy} run={run}/>}
 </>;
};

const SettingsCard:React.FC<{data:PayContext;busy:boolean;run:(fn:()=>Promise<unknown>,message:string)=>Promise<void>}>=({data,busy,run})=>{
 const [date,setDate]=useState('');const [source,setSource]=useState('');const [holiday,setHoliday]=useState('unconfirmed');const [dayA,setDayA]=useState('5');const [offsetA,setOffsetA]=useState('1');const [dayB,setDayB]=useState('20');const [offsetB,setOffsetB]=useState('0');
 return <Card title="Approved payroll calendar"><p className="text-sm">The values below preview the plan’s 11–25 and 26–10 cutoffs. Confirm the pay month and holiday rule against an approved calendar before recording them. Unconfirmed rules do not become active payroll rules.</p>{data.settings.map(s=><p className="mt-3 text-sm" key={s.id}>From {s.effective_from}: {s.calendar.map(c=>`${c.startDay}–${c.endDay} pays day ${c.payDay}, ${c.payMonthOffset===1?'month after cutoff end':'cutoff-end month'}`).join('; ')}. Holiday rule: {s.holiday_handling}. Source: {s.policy_ref}</p>)}<details className="mt-4"><summary className="cursor-pointer font-medium">Record an approved calendar version</summary><form className="mt-4 space-y-4" onSubmit={e=>{e.preventDefault();void run(()=>savePaySettings(data.scopeId,date,[{startDay:11,endDay:25,payDay:Number(dayA),payMonthOffset:Number(offsetA)},{startDay:26,endDay:10,payDay:Number(dayB),payMonthOffset:Number(offsetB)}],holiday,source),'Calendar version recorded; payroll remains off.');}}><fieldset disabled={busy} className="space-y-4"><Field label="Effective from" type="date" value={date} onChange={setDate} required/><div className="grid gap-4 sm:grid-cols-2"><Field label="11–25 cutoff: payday" type="number" value={dayA} onChange={setDayA} required/><Field label="11–25 cutoff: pay month" value={offsetA} onChange={setOffsetA}><option value="1">Month after cutoff end</option><option value="0">Cutoff-end month</option></Field><Field label="26–10 cutoff: payday" type="number" value={dayB} onChange={setDayB} required/><Field label="26–10 cutoff: pay month" value={offsetB} onChange={setOffsetB}><option value="0">Cutoff-end month</option><option value="1">Month after cutoff end</option></Field></div><Field label="Weekend / holiday payday handling" value={holiday} onChange={setHoliday}><option value="unconfirmed">Not yet confirmed</option><option value="previous_business_day">Previous business day</option><option value="next_business_day">Next business day</option><option value="unchanged">Keep the scheduled date</option></Field><Field label="Approved calendar / policy reference" value={source} onChange={setSource} required/><Button type="submit" isLoading={busy} disabled={source.trim().length<3}>Record approved settings</Button></fieldset></form></details></Card>;
};
export default PayPackagesPage;
