import React,{useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import type {GrossRun} from './grossPay';
import type {NetResult} from './netPay';
import {amountCents,pesoCents,breakdownGroups,breakdownLabels,categoryFor,lineUnits,lineRate,type BreakdownCategory} from './payrollBreakdownModel';
const panel='rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900 sm:p-5';
const button='inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-violet-200 bg-white px-4 py-2 text-sm font-semibold text-violet-700 hover:bg-violet-50 disabled:opacity-50 dark:bg-slate-900 dark:text-violet-300';
const tones={basic:'bg-blue-50 text-blue-950 dark:bg-blue-950 dark:text-blue-100',overtime:'bg-emerald-50 text-emerald-950 dark:bg-emerald-950 dark:text-emerald-100',premium:'bg-amber-50 text-amber-950 dark:bg-amber-950 dark:text-amber-100',night:'bg-indigo-50 text-indigo-950 dark:bg-indigo-950 dark:text-indigo-100',unpaid:'bg-rose-50 text-rose-900 dark:bg-rose-950 dark:text-rose-100',benefits:'bg-cyan-50 text-cyan-950 dark:bg-cyan-950 dark:text-cyan-100',rounding:'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-100',total:'bg-violet-50 text-violet-950 dark:bg-violet-950 dark:text-violet-100'};
export type PayrollBreakdownProps={gross:GrossRun;employeeId:string;unitName:string;netEmployee?:NetResult;netCurrent?:boolean;issues?:{date:string;message:string}[];busy:boolean;canRecalculate:boolean;onRecalculate:()=>void;onReview:()=>void;sources:readonly (readonly [string,string])[]};
export const PayrollBreakdown:React.FC<PayrollBreakdownProps>=({gross,employeeId,unitName,netEmployee,netCurrent,issues=[],busy,canRecalculate,onRecalculate,onReview,sources})=>{
 const employee=gross.result.employees.find(e=>e.employeeId===employeeId);
 const [filter,setFilter]=useState('all'),[showAll,setShowAll]=useState(false);const details=useRef<HTMLElement>(null);
 if(!employee)return <p>This employee is not in the selected payroll.</p>;
 const groups=breakdownGroups(employee.lines),earnings=groups.filter(g=>!g.adjustment),adjustments=groups.filter(g=>g.adjustment);
 const total=groups.reduce((n,g)=>n+g.amount,0n),before=earnings.reduce((n,g)=>n+g.amount,0n),adjusted=adjustments.reduce((n,g)=>n+g.amount,0n);
 const saved=amountCents(employee.gross),reconciles=total===saved;
 const filtered=employee.lines.filter(l=>filter==='all'||categoryFor(l)===filter).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));
 const rows=showAll?filtered:filtered.slice(0,5);
 function viewDates(category:string){setFilter(category);setShowAll(true);details.current?.scrollIntoView({behavior:'smooth',block:'start'});details.current?.focus({preventScroll:true});}
 const categories=[...new Set(groups.map(g=>g.category))];
 const cards:BreakdownCategory[]=['basic','overtime','premium','unpaid',...(['night','benefits','rounding'] as BreakdownCategory[]).filter(c=>groups.some(g=>g.category===c&&g.amount!==0n))];
 function summary(c:BreakdownCategory){const lines=employee!.lines.filter(l=>categoryFor(l)===c);if(c==='basic'&&lines.length&&lines.every(l=>l.label.toLowerCase().includes('calendar-prorated semi-monthly basic'))){const dates=new Set(lines.map(l=>l.date));const rates=new Set(lines.map(l=>l.amount));if(rates.size===1)return `${dates.size} paid days × ${pesoCents(amountCents(lines[0].amount))}`;}return `${lines.length} ${lines.length===1?'entry':'entries'}`;}
 return <div className="space-y-4 text-slate-950 dark:text-slate-100">
 <header className={panel}><div className="flex flex-wrap items-start justify-between gap-4"><div className="grid gap-4 sm:grid-cols-[minmax(180px,1.4fr)_1fr_1.4fr]"><div><h2 className="text-xl font-bold">{employee.employeeName}</h2><p className="mt-1 text-sm text-slate-500">Payroll version {gross.version}</p></div><div className="sm:border-l sm:pl-5"><p className="text-sm text-slate-500">Business unit</p><p className="mt-1 font-semibold">{unitName}</p></div><div className="sm:border-l sm:pl-5"><p className="text-sm text-slate-500">Payroll cutoff</p><p className="mt-1 font-semibold">{gross.from} — {gross.to}</p><p className="text-sm text-slate-500">Semi-monthly</p></div></div><span className={`rounded-full px-3 py-2 text-sm font-semibold ${gross.current&&reconciles?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-900'}`}>{!gross.current?'Needs recalculation':!reconciles?'Needs reconciliation':'Gross calculated'}</span></div>
 {!gross.current&&<p role="alert" className="mt-3 text-amber-800">{gross.staleReason||'Source records changed. Recalculate payroll.'}</p>}{!reconciles&&<p role="alert" className="mt-3 text-red-700">The saved gross total does not match these earnings lines. Recalculate before proceeding.</p>}
 <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(c=><div key={c} className={`rounded-xl p-4 ${tones[c]}`}><div className="flex items-center gap-2"><ItemIcon category={c}/><h3 className="text-sm font-semibold">{c==='unpaid'?'Unpaid minutes deduction':breakdownLabels[c]}</h3></div><p className="mt-2 text-2xl font-bold tabular-nums">{pesoCents(groups.filter(g=>g.category===c).reduce((n,g)=>n+g.amount,0n))}</p><p className="mt-2 text-xs opacity-75">{summary(c)}</p></div>)}<div className={`rounded-xl p-4 ${tones.total}`}><div className="flex items-center gap-2"><ItemIcon category="total"/><h3 className="text-sm font-semibold">Total earnings</h3></div><p className="mt-2 text-2xl font-bold tabular-nums">{pesoCents(saved)}</p><p className="mt-2 text-xs opacity-75">After attendance adjustments · before tax and other payroll deductions</p></div></div></header>
 {issues.length>0&&<section className="rounded-xl bg-amber-50 p-4 text-amber-950"><h3 className="font-semibold">Attendance items to review</h3>{issues.map((i,n)=><p key={n} className="mt-2 text-sm">{i.date} · {i.message}</p>)}</section>}
 <div className="grid gap-4 lg:grid-cols-2"><section className={panel}><h3 className="text-lg font-bold">Earnings breakdown</h3><p className="mb-3 mt-1 text-sm text-slate-500">Calculated earnings for this cutoff</p><GroupTable groups={earnings} onDates={viewDates}/><div className="mt-3 flex justify-between gap-3 rounded-lg bg-emerald-50 p-3 font-semibold text-emerald-900"><span>Total earnings before adjustments</span><span className="tabular-nums">{pesoCents(before)}</span></div></section><section className={panel}><h3 className="text-lg font-bold">Attendance adjustments</h3><p className="mb-3 mt-1 text-sm text-slate-500">Unpaid time and other earnings adjustments</p><GroupTable groups={adjustments} onDates={viewDates}/><div className="mt-3 flex justify-between gap-3 rounded-lg bg-rose-50 p-3 font-semibold text-rose-900"><span>Total adjustments</span><span className="tabular-nums">{pesoCents(adjusted)}</span></div></section></div>
 <section ref={details} tabIndex={-1} className={`${panel} scroll-mt-4 outline-none`}><div className="mb-3 flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-bold">Date details</h3><p className="mt-1 text-sm text-slate-500">Select “View dates” above to see that pay item.</p></div><label className="flex items-center gap-2 text-sm">Show<select className="rounded-lg border bg-white p-2 dark:bg-slate-800" value={filter} onChange={e=>{setFilter(e.target.value);setShowAll(false);}}><option value="all">All items</option>{categories.map(c=><option key={c} value={c}>{breakdownLabels[c]}</option>)}</select></label></div><div className="overflow-x-auto"><table className="w-full min-w-[740px] text-left text-sm"><thead className="bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><tr>{['Date','Item','Units / minutes','Rate (PHP)','Amount (PHP)','Status'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map((l,i)=><tr key={i} className="border-b border-slate-100 dark:border-slate-800"><td className="whitespace-nowrap p-3">{l.date||'Cutoff total'}</td><td className="p-3">{l.label}</td><td className="whitespace-nowrap p-3">{lineUnits(l)}</td><td className="whitespace-nowrap p-3">{lineRate(l)}{Number(l.factor)!==1&&Number.isFinite(Number(l.factor))&&<span className="block text-xs text-slate-500">× {l.factor} multiplier</span>}</td><td className={`whitespace-nowrap p-3 font-semibold tabular-nums ${amountCents(l.amount)<0n?'text-rose-700':''}`}>{pesoCents(amountCents(l.amount))}</td><td className="p-3"><span className={`rounded px-2 py-1 text-xs font-medium ${amountCents(l.amount)<0n?'bg-rose-50 text-rose-800':categoryFor(l)==='overtime'?'bg-violet-50 text-violet-800':'bg-emerald-50 text-emerald-800'}`}>{amountCents(l.amount)<0n?'Deduction':categoryFor(l)==='rounding'?'Adjustment':categoryFor(l)==='overtime'&&l.label.toLowerCase().includes('approved')?'Approved':'Included'}</span></td></tr>)}</tbody></table></div>{filtered.length===0&&<p className="p-3 text-sm text-slate-500">No entries for this item.</p>}{filtered.length>5&&<div className="mt-3 text-right"><button className="text-sm font-semibold text-violet-700 dark:text-violet-300" onClick={()=>setShowAll(!showAll)}>{showAll?'Show fewer entries':`View all ${filtered.length} entries →`}</button></div>}</section>
 <section className={panel}><h3 className="font-bold">Take-home pay</h3>{netEmployee?<><p className="mt-1 text-sm text-slate-500">{netCurrent?'Calculated from the saved Finance review.':'This net calculation needs refreshing.'}</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{[['Gross after any company-funded tax adjustment',netEmployee.gross],['Tax, contributions and other deductions',netEmployee.deductions],['Take-home pay',netEmployee.net]].map(([label,value])=><div key={label} className="rounded-lg bg-violet-50 p-3 text-violet-950"><p className="text-sm">{label}</p><p className="mt-1 text-xl font-bold">{pesoCents(amountCents(value))}</p></div>)}</div></>:<p className="mt-2 text-sm text-slate-500">Tax, contributions and other payroll deductions will appear after Finance calculation. Total earnings above is not yet take-home pay.</p>}</section>
 <footer className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-white py-3 dark:bg-slate-900"><div className="flex flex-wrap gap-2">{sources.map(([label,path])=><Link key={label} className={button} to={`${path}?employee=${encodeURIComponent(employeeId)}`}>{label}</Link>)}</div><div className="flex flex-wrap gap-2"><button className={button} disabled={busy||!canRecalculate} onClick={onRecalculate}>Recalculate</button><button className={`${button} !bg-violet-600 !text-white`} disabled={busy} onClick={onReview}>Review payroll</button></div></footer>
 </div>;
};
const GroupTable:React.FC<{groups:ReturnType<typeof breakdownGroups>;onDates:(category:string)=>void}>=({groups,onDates})=><div className="overflow-x-auto"><table className="w-full min-w-[430px] text-left text-sm"><thead className="bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><tr><th className="p-3">Item</th><th className="p-3">Details</th><th className="p-3 text-right">Amount (PHP)</th><th className="p-3"><span className="sr-only">Dates</span></th></tr></thead><tbody>{groups.map(g=><tr key={g.key} className="border-b border-slate-100 dark:border-slate-800"><td className="p-3 font-semibold"><span className="flex items-center gap-2"><ItemIcon category={g.category}/>{g.label}</span></td><td className="p-3 text-slate-500">{g.lines.length} {g.lines.length===1?'entry':'entries'}</td><td className={`whitespace-nowrap p-3 text-right font-semibold tabular-nums ${g.amount<0n?'text-rose-700':''}`}>{pesoCents(g.amount)}</td><td className="p-3"><button aria-label={`View dates for ${g.label}`} className="whitespace-nowrap font-semibold text-violet-700 dark:text-violet-300" onClick={()=>onDates(g.category)}>View dates →</button></td></tr>)}</tbody></table>{!groups.length&&<p className="p-3 text-sm text-slate-500">No adjustments recorded.</p>}</div>;
const ItemIcon:React.FC<{category:BreakdownCategory|'total'}>=({category})=><span className={`inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${tones[category]}`}><svg aria-hidden="true" className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{category==='overtime'||category==='night'?<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l4 2"/></>:category==='unpaid'?<><circle cx="12" cy="12" r="9"/><path d="M7 12h10"/></>:category==='premium'?<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2L12 17.3l-5.6 2.9 1.1-6.2L3 9.6l6.2-.9Z"/>:<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 11h2m4 0h2M8 15h2m4 0h2"/></>}</svg></span>;
