import React,{useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {supabase} from '../../services/supabaseClient';
import {usePayrollField} from './usePayrollSelection';
import {fetchTimeContext,TimeScope} from './attendanceReadiness';
import NormalPayrollPeriodSelector,{ConfiguredPeriod} from './NormalPayrollPeriodSelector';
import {inputTemplates,readInputFile,validateInputRow,templateCsv,ImportRow} from './inputTemplates';
import {attendanceStamp,downloadText} from './actualAttendanceImport';
const button='inline-flex min-h-11 items-center justify-center rounded-xl border px-4 py-3 text-sm font-semibold disabled:opacity-40';
const panel='rounded-2xl border bg-white p-5 dark:bg-slate-900';
type Employee={id:string;code:string;name:string;businessUnit:string};
type Preview={rows?:{employee:string;warning?:string}[];ready:number;duplicates:number;errors:{row:number;message:string}[];confirmed?:boolean;alreadyImported?:boolean};
const sourcePath:Record<string,string>={schedules:'/payroll/timekeeping','leave-balances':'/payroll/leave-balances/import','leave-taken':'/payroll/leave',deductions:'/payroll/loans','service-charge':'/payroll/service-charge',additions:'/payroll/import/additions','attendance-events':'/payroll/attendance-readiness'};
export default function PayrollInputImport(){const {kind='schedules'}=useParams();const [scope,setScope]=usePayrollField('scope'),[from]=usePayrollField('from'),[to]=usePayrollField('to');return <InputWorkspace key={`${kind}:${scope}:${from}:${to}`} kind={kind} scope={scope} setScope={setScope} from={from} to={to}/>;}
function InputWorkspace({kind,scope,setScope,from,to}:{key?:string;kind:string;scope:string;setScope:(v:string)=>void;from:string;to:string}){
 const schema=inputTemplates[kind];const [scopes,setScopes]=useState<TimeScope[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[canImport,setCanImport]=useState(false),[additions,setAdditions]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]);
 const [rows,setRows]=useState<ImportRow[]>([]),[mapping,setMapping]=useState<Awaited<ReturnType<typeof readInputFile>>|null>(null),[filename,setFilename]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[sample,setSample]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[cycle,setCycle]=useState<ConfiguredPeriod|null>(null),[reviewNote,setReviewNote]=useState('');
 const unit=scopes.find(s=>s.id===scope)?.name||'';
 useEffect(()=>{let active=true;fetchTimeContext().then(x=>{if(active)setScopes(x.scopes.filter(s=>s.canView));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{let active=true;if(!scope)return;Promise.resolve(supabase.rpc('get_payroll_input_context',{p_scope:scope,p_from:from,p_to:to})).then(({data,error})=>{if(!active)return;if(error)setError(error.message);else{setEmployees(data.employees);setCanImport(data.canImport);setAdditions(data.additions||[]);setHistory(data.imports||[]);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[scope,from,to,revision]);
 if(!schema)return <p className="p-6">Unknown template. <Link to="/payroll/run">Return to payroll</Link></p>;
 function convert(m:NonNullable<typeof mapping>){if(new Set(m.mapping.filter(n=>n>=0)).size!==m.mapping.filter(n=>n>=0).length){setError('Each file column may be mapped only once.');return;}const next=m.raw.map(r=>validateInputRow(schema,Object.fromEntries(schema.fields.map((f,i)=>[f.key,r.cells[m.mapping[i]]||''])),r.row));setRows(next);setMapping(null);setPreview(null);}
 async function upload(file:File){setBusy(true);setError('');setPreview(null);setRows([]);setMapping(null);try{const m=await readInputFile(file,schema);setFilename(file.name);if(m.needsMapping)setMapping(m);else convert(m);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function check(confirm=false){setBusy(true);setError('');try{
  let args:any={p_kind:kind,p_scope:scope,p_from:from,p_to:to,p_filename:filename,p_rows:rows.map(r=>({rowNumber:r.rowNumber,values:r.values})),p_confirm:confirm},rpc='import_payroll_inputs';
  if(kind==='attendance-events'){
   const groups=new Map<string,any>();for(const {values:v} of rows){const key=v.employeeId+':'+v.workDate;if(!groups.has(key))groups.set(key,{employeeId:v.employeeId,businessUnit:v.businessUnit,workDate:v.workDate,events:[],reference:v.reference,notes:v.notes});groups.get(key).events.push({type:v.eventType,timestamp:attendanceStamp(v.timestamp)});}const grouped=[...groups.values()];for(const r of grouped)r.events.sort((a:any,b:any)=>a.timestamp.localeCompare(b.timestamp));
   rpc='import_actual_attendance';delete args.p_kind;args.p_rows=grouped;
  }
  const {data,error}=await supabase.rpc(rpc,args);if(error)throw error;setPreview(data);if(data.confirmed)setRevision(v=>v+1);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function review(id:string,decision:string){setBusy(true);setError('');try{const {error}=await supabase.rpc('review_payroll_input_addition',{p_id:id,p_decision:decision,p_note:reviewNote});if(error)throw error;setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const invalid=rows.filter(r=>r.errors.length).length,total=rows.reduce((n,r)=>n+Number(r.values.amount||r.values.balance||0),0);
 const approvals=['leave-balances','leave-taken','deductions','additions'].includes(kind);
 function prefill(){const records:Record<string,string>[]=[];for(const employee of employees){if(['schedules','attendance-events'].includes(kind)){for(let d=new Date(from+'T00:00:00Z');d.toISOString().slice(0,10)<=to;d.setUTCDate(d.getUTCDate()+1))records.push({employeeId:employee.code,employeeName:employee.name,businessUnit:unit,workDate:d.toISOString().slice(0,10)});}else records.push({employeeId:employee.code,employeeName:employee.name,businessUnit:unit,payrollDate:cycle?.releaseDate||''});}downloadText(`${kind}-prefilled.csv`,templateCsv(schema,records));}
 return <main className="mx-auto max-w-7xl space-y-5 p-5 pb-24"><header><Link className="text-violet-700" to="/payroll/run">← Prepare payroll</Link><h1 className="mt-3 text-3xl font-bold">Import {schema.title.toLowerCase()}</h1><p className="mt-2 text-slate-500">{schema.meaning}</p></header>
  <div className="grid gap-4 md:grid-cols-2"><label>Business unit<select className="mt-2 min-h-12 w-full rounded-xl border p-3" disabled={busy} value={scope} onChange={e=>setScope(e.target.value)}><option value="">Choose business unit</option>{scopes.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><NormalPayrollPeriodSelector disabled={busy} onPeriod={setCycle}/></div>
  <section className={panel}><h2 className="text-xl font-bold">{schema.title} · version {schema.version}</h2><p className="my-3 text-sm">{schema.notice}</p>{kind==='attendance-events'&&<p className="mb-3 text-sm">Importing saves actual attendance for this period. Review before confirming. Existing records will not be overwritten automatically.</p>}<div className="flex flex-wrap gap-3"><a className={button} download href={`/templates/${kind}-v1.xlsx`}>Download template (XLSX)</a><button className={button} onClick={()=>downloadText(`${kind}-v1.csv`,templateCsv(schema))}>Download template (CSV)</button><button className={button} disabled={!employees.length} onClick={prefill}>Download prefilled template</button><button className={button} onClick={()=>setSample(v=>!v)}>View sample</button><button className={button} disabled={busy||!canImport} onClick={()=>{setFilename('Manual entry');setPreview(null);setRows(r=>[...r,validateInputRow(schema,{businessUnit:unit,payrollDate:cycle?.releaseDate||''},(r.at(-1)?.rowNumber||1)+1)]);}}>Add a record manually</button><label className={`${button} bg-violet-600 text-white`}>Upload completed file<input className="sr-only" type="file" accept=".csv,.xlsx" disabled={busy||!canImport} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value='';}}/></label></div>
   {sample&&<div className="mt-4"><p className="font-semibold text-amber-700">Examples only. DEMO IDs cannot be imported.</p><div className="overflow-x-auto"><table className="mt-3 text-left text-sm"><thead><tr>{schema.fields.map(f=><th className="min-w-40 p-2" key={f.key}>{f.label}</th>)}</tr></thead><tbody><tr>{schema.fields.map(f=><td className="border-t p-2" key={f.key}>{schema.sample[f.key]||'—'}</td>)}</tr></tbody></table></div><button className={`${button} mt-3`} onClick={()=>downloadText(`${kind}-SAMPLE-DO-NOT-UPLOAD.csv`,templateCsv(schema,[schema.sample]))}>Download sample CSV</button></div>}
   <details className="mt-4"><summary className="cursor-pointer font-semibold">Field guide</summary><dl className="mt-3 grid gap-3 sm:grid-cols-2">{schema.fields.map(f=><div key={f.key}><dt className="font-medium">{f.label}</dt><dd className="text-sm text-slate-500">{f.help||`Enter ${f.type==='number'?'a numeric value':f.type==='date'?'YYYY-MM-DD or a real Excel date':'the source value'}.`}{f.choices&&` Allowed: ${f.choices.join(', ')}.`}</dd></div>)}</dl></details>
  </section>
  {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}
  {mapping&&<section className={panel}><h2 className="font-bold">Match your file columns</h2><p className="my-2 text-sm">This file is not an official template. Choose each column explicitly.</p><div className="grid gap-3 sm:grid-cols-2">{schema.fields.map((f,i)=><label key={f.key}>{f.label}<select className="mt-1 w-full rounded-lg border p-2" value={mapping.mapping[i]} onChange={e=>setMapping(m=>m&&({...m,mapping:m.mapping.map((v,n)=>n===i?Number(e.target.value):v)}))}><option value={-1}>Not mapped</option>{mapping.headers.map((h,j)=><option key={j} value={j}>{h}</option>)}</select></label>)}</div><button className={`${button} mt-3`} disabled={schema.fields.some((f,i)=>f.required&&mapping.mapping[i]<0)} onClick={()=>convert(mapping)}>Review mapped rows</button></section>}
  {!!rows.length&&<section className={panel}><h2 className="text-xl font-bold">Upload → Preview → {approvals?'Submit for approval':'Confirm import'}</h2><p className="my-3">{filename} · {schema.title} · {unit} · {from}–{to}</p><p>{rows.length-invalid} locally valid · {invalid} requiring correction{preview&&` · ${preview.ready} ready · ${preview.duplicates} duplicates`}{approvals&&` · ${preview?.ready??rows.length-invalid} requiring approval`}</p>{['deductions','additions','service-charge'].includes(kind)&&<p className="mt-2 font-bold">{kind==='deductions'?'Outstanding balances':'Import total'}: {new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(total)}</p>}
   <div className="mt-4 max-h-[480px] overflow-auto"><table className="text-left text-sm"><thead><tr><th className="p-2">Row</th>{schema.fields.map(f=><th className="min-w-44 p-2" key={f.key}>{f.label}</th>)}<th className="min-w-64">Issues</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.rowNumber} className="border-t"><td className="p-2">{r.rowNumber}</td>{schema.fields.map(f=><td className="p-2" key={f.key}><input aria-label={`Row ${r.rowNumber} ${f.label}`} className="w-44 rounded border p-2" disabled={busy||preview?.confirmed||preview?.alreadyImported} value={r.values[f.key]||''} onChange={e=>{setPreview(null);setRows(v=>v.map((x,n)=>n===i?validateInputRow(schema,{...x.values,[f.key]:e.target.value},x.rowNumber):x));}}/></td>)}<td className="p-2 text-red-700">{r.errors.join(' ')} {preview?.errors.filter(e=>e.row===r.rowNumber).map(e=>e.message).join(' ')}</td></tr>)}</tbody></table></div>
   {kind==='deductions'&&<details className="mt-4"><summary className="font-semibold">Preview repayment amounts</summary>{rows.filter(r=>!r.errors.length).map(r=>{const v=r.values,n=v.method==='Amount per cutoff'?Math.ceil(Number(v.balance)/Number(v.installment)):Number(v.duration)*(v.method==='Number of months'?2:1),installment=v.method==='Amount per cutoff'?Number(v.installment):Math.ceil(Number(v.balance)*100/n)/100;return <p className="mt-2" key={r.rowNumber}>{v.employeeId} · {v.reference}: {n} cutoffs from {v.payrollDate}, ₱{installment.toFixed(2)} per cutoff; final cutoff ₱{Math.max(0,Number(v.balance)-installment*(n-1)).toFixed(2)}. Finance reviews the saved dated schedule before approval.</p>;})}</details>}
   {preview?.rows?.filter(r=>r.warning).map((r,i)=><p key={i} className="mt-3 text-amber-800">{r.employee} — {r.warning}</p>)}{preview?.errors.map(e=><p key={`${e.row}:${e.message}`} className="mt-3 text-red-700">Row {e.row} — {e.message}</p>)}
   <div className="mt-4 flex flex-wrap gap-3"><button className={button} disabled={busy||!!invalid||preview?.confirmed||preview?.alreadyImported} onClick={()=>void check()}>Validate preview</button><button className={button} onClick={()=>downloadText(`${kind}-with-errors.csv`,templateCsv({...schema,fields:[...schema.fields,{key:'errors',label:'Errors (remove before upload)',type:'text',required:false,help:''}]},rows.map(r=>({...r.values,errors:[...r.errors,...(preview?.errors.filter(e=>e.row===r.rowNumber).map(e=>e.message)||[])].join(' ')}))))}>Download file with errors</button>{preview&&!preview.confirmed&&!preview.alreadyImported&&<button className={`${button} bg-violet-600 text-white`} disabled={busy||!!invalid||!!preview.errors.length||!preview.ready} onClick={()=>void check(true)}>{approvals?'Submit for approval':'Confirm import'}</button>}</div>
   {(preview?.confirmed||preview?.alreadyImported)&&<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-4 text-emerald-900">{preview.alreadyImported?'These records were already received. No duplicates were added.':approvals?'Saved and submitted for required approval. Pending records are not yet active.':kind==='schedules'?'Draft schedules saved. Review and publish in Schedule Builder.':kind==='service-charge'?'Allocations saved. Review and include the service-charge preview before calculation.':'Actual attendance saved.'} <Link className="underline" to={sourcePath[kind]}>Open source records</Link></p>}
  </section>}
  {kind==='additions'&&!!additions.length&&<section className={panel}><h2 className="font-bold">Finance review of one-time additions</h2><input className="my-3 w-full rounded border p-3" aria-label="Finance evidence review note" placeholder="Receipt, duplicate package component and tax treatment reviewed" value={reviewNote} onChange={e=>setReviewNote(e.target.value)}/>{additions.map(r=><div key={r.id} className="border-t py-3"><strong>{r.employeeName}: {r.data.description} · ₱{Number(r.data.amount).toFixed(2)}</strong><p>{r.data.tax} · {r.status} · {r.data.approvalReference}</p>{r.data.document&&<a href={r.data.document} target="_blank" rel="noopener noreferrer" className="text-violet-700 underline">View source document</a>}{r.canReview&&<div className="mt-2 flex gap-3"><button disabled={busy||reviewNote.trim().length<3} className={button} onClick={()=>void review(r.id,'approved')}>Approve verified addition</button><button disabled={busy||reviewNote.trim().length<3} className={button} onClick={()=>void review(r.id,'rejected')}>Reject</button></div>}</div>)}</section>}
  {!!history.length&&<details className={panel}><summary>Saved import history for this cutoff</summary>{history.filter(h=>h.kind===kind).map(h=><p className="mt-3" key={h.id}>{h.filename} · {new Date(h.created_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</p>)}</details>}
 </main>;
}
