import React,{useCallback,useEffect,useRef,useState} from 'react';
import {supabase} from '../../services/supabaseClient';
import {useAuth} from '../../hooks/useAuth';
import {BreakDecisionCard,Review} from './RecordedBreakApprovals';
type Batch=Review&{scopeName:string;date_from:string;date_to:string};
export default function PayrollAttendanceInbox(){
 const {user}=useAuth();const [batches,setBatches]=useState<Batch[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notes,setNotes]=useState<Record<string,string>>({});const lock=useRef(false),generation=useRef(0);
 const load=useCallback(async()=>{const n=++generation.current;try{const {data,error}=await supabase.rpc('get_payroll_break_review_inbox');if(error)throw error;if(n===generation.current){setBatches(data||[]);setError('');}}catch(e){if(n===generation.current)setError((e as Error).message);}finally{if(n===generation.current)setLoading(false);}},[user?.id]);
 useEffect(()=>{setBatches([]);setLoading(true);if(!user)return;void load();const focus=()=>{if(!lock.current)void load();};window.addEventListener('focus',focus);window.addEventListener('payroll-attendance-decided',focus);return()=>{++generation.current;window.removeEventListener('focus',focus);window.removeEventListener('payroll-attendance-decided',focus);};},[load,user?.id]);
 const decide=async(batch:Batch,action:string)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const {data,error}=await supabase.rpc('decide_payroll_break_review',{p_id:batch.id,p_action:action,p_note:notes[batch.id]||''});if(error)throw error;setNotice(data==='pending_bod'?'Batch approved by HR Manager and sent to one independent BOD.':data==='approved'?'Batch applied. Payroll needs recalculation.':`Batch ${data}.`);await load();window.dispatchEvent(new Event('payroll-attendance-decided'));}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}};
 if(!user||(!loading&&!batches.length&&!error&&!notice))return null;
 return <section aria-label="Payroll attendance approvals" className="mb-6 space-y-4 rounded-2xl border border-violet-200 bg-white p-5 dark:bg-slate-800"><h2 className="text-xl font-bold">Payroll attendance approvals · {batches.length} {batches.length===1?'batch':'batches'}</h2>{loading&&<p role="status">Checking attendance batches…</p>}<p className="text-sm">{batches.reduce((n,b)=>n+b.items.length,0)} attendance dates in these batches. Approve each batch once; date-by-date approval is not needed.</p>{error&&<p role="alert" className="text-red-700">{error} <button disabled={busy} className="underline" onClick={()=>void load()}>Retry</button></p>}{notice&&<p role="status">{notice}</p>}{batches.map(batch=><div key={batch.id}><h3 className="mb-2 font-semibold">{batch.scopeName} · {batch.date_from} – {batch.date_to}</h3><p className="mb-2 text-sm">Accept the uploaded unpaid break durations. No punch times or approved OT hours change.</p><BreakDecisionCard review={batch} busy={busy} note={notes[batch.id]||''} setNote={note=>setNotes(old=>({...old,[batch.id]:note}))} onDecision={action=>decide(batch,action)}/></div>)}</section>;
}
