import React,{useEffect,useState} from 'react';
import Button from '../../components/ui/Button';
import {fetchPayrollCalendarSettings,PayrollCalendarRule,savePayrollCalendarOverride,TimeScope} from './attendanceReadiness';

const field='mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-600 dark:bg-slate-800';
const defaultRules:PayrollCalendarRule['cutoffRules']=[{releaseDay:5,startDay:11,endDay:25,startMonthOffset:-1,endMonthOffset:-1},{releaseDay:20,startDay:26,endDay:10,startMonthOffset:-1,endMonthOffset:0}];

export default function PayrollCalendarSettings({scopes}:{scopes:TimeScope[]}){
 const [data,setData]=useState<Awaited<ReturnType<typeof fetchPayrollCalendarSettings>>|null>(null);const [scope,setScope]=useState('');const [effective,setEffective]=useState('');const [policy,setPolicy]=useState('');const [rules,setRules]=useState(defaultRules);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const load=()=>fetchPayrollCalendarSettings().then(setData).catch(reason=>setError(reason instanceof Error?reason.message:'Payroll calendar settings could not be loaded.'));
 useEffect(()=>{void load();},[]);const editable=scopes.filter(item=>item.canConfigure||item.canManage);
 const setRule=(index:number,key:'releaseDay'|'startDay'|'endDay',value:string)=>setRules(current=>current.map((item,i)=>i===index?{...item,[key]:Number(value)}:item));
 const save=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');setNotice('');try{await savePayrollCalendarOverride(scope,effective,rules,policy);setNotice('Future business-unit payroll calendar recorded. Existing and open payroll periods were not changed.');setEffective('');setPolicy('');await load();}catch(reason){setError(reason instanceof Error?reason.message:'Payroll calendar override could not be saved.');}finally{setBusy(false);}};
 return <div className="space-y-5"><div><h2 className="text-2xl font-bold">Payroll Settings</h2><p className="mt-1 text-sm text-slate-500">Manage the global calendar and future-dated business-unit exceptions. Every change is audited.</p></div>{error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-900">{notice}</p>}
  <section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-violet-700">Global payroll calendar</p><h3 className="mt-1 text-xl font-bold">All business units use the global payroll calendar</h3></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-sm font-semibold text-emerald-800">Global default</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-violet-50 p-4"><strong>11th–25th</strong><p className="text-sm">Payroll release on the 5th</p></div><div className="rounded-xl bg-violet-50 p-4"><strong>26th–10th</strong><p className="text-sm">Payroll release on the 20th</p></div></div><p className="mt-3 text-xs text-slate-500">Effective {data?.global?.effectiveFrom||'for all current periods'} · {data?.global?.policyRef||'Confirmed payroll calendar'}</p></section>
  {data?.overrides?.length?<section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><h3 className="font-bold">Business-unit overrides</h3>{data.overrides.map(item=><div className="mt-3 flex flex-wrap items-center justify-between gap-3 border-t pt-3 dark:border-slate-700" key={item.id}><div><strong>{item.scopeName}</strong><p className="text-sm">Effective {item.effectiveFrom} · {item.policyRef}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold text-amber-800">This business unit uses a custom payroll calendar.</span></div>)}</section>:<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600 dark:bg-slate-800">No business-unit override is active. All business units use the global payroll calendar.</p>}
  {data?.canConfigure&&<form className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-900" onSubmit={event=>void save(event)}><h3 className="font-bold">Schedule a business-unit override</h3><p className="mt-1 text-sm text-slate-500">The effective date must be in the future. An override cannot change an already-open payroll period.</p><fieldset disabled={busy} className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Business unit<select required className={field} value={scope} onChange={event=>setScope(event.target.value)}><option value="">Choose business unit</option>{editable.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Effective date<input required className={field} type="date" value={effective} onChange={event=>setEffective(event.target.value)}/></label>{rules.map((rule,index)=><React.Fragment key={index}><label className="text-sm font-medium">Payroll release day<input required className={field} type="number" min="1" max="28" value={rule.releaseDay} onChange={event=>setRule(index,'releaseDay',event.target.value)}/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Cutoff start<input required className={field} type="number" min="1" max="31" value={rule.startDay} onChange={event=>setRule(index,'startDay',event.target.value)}/></label><label className="text-sm font-medium">Cutoff end<input required className={field} type="number" min="1" max="31" value={rule.endDay} onChange={event=>setRule(index,'endDay',event.target.value)}/></label></div></React.Fragment>)}<label className="text-sm font-medium md:col-span-2">Policy and approval reference<textarea required minLength={3} maxLength={1000} className={field} value={policy} onChange={event=>setPolicy(event.target.value)}/></label></fieldset><Button className="mt-4" disabled={busy||!scope||!effective||policy.trim().length<3}>Save future override</Button></form>}
 </div>;
}

