export const phaseChecklist = [
  {phase:'1 · Payroll access',owner:'Kay + HR / Finance',todo:'Confirm who finalizes timekeeping, prepares the PR, reviews/endorses, authorizes HR, authorizes Finance, gives the two BOD approvals, and releases payment. Assign each person the appropriate BU or All business units.',link:'/payroll/access'},
  {phase:'2 · Pay packages',owner:'HR + Finance',todo:'Review current salary amounts, allowances, real effective dates and approved salary changes. Confirm any separate consultant engagement, bank details, payday calendar and unresolved component treatments.',link:'/payroll/pay-packages'},
  {phase:'3 · Attendance readiness',owner:'BU managers + HR',todo:'Review actual saved preset times; confirm next-day ends for overnight shifts and paid hours for flexible shifts. Enter actual shifts, explicit Rest Day or Leave / No Schedule, then publish each reviewed week in the existing roster. Blank days block payroll. Employees record actual Clock In, Take a Break, End Break and Clock Out on their dashboard. HR/Admin must enter any approved dated clocking exemptions through Manage clocking exceptions & attendance review; default is clocking required. Review actual attendance and corrections before finalization. Complete leave, WFH and OT approvals; verify holiday coverage and prescribed lunch times. Identify the HR Manager, GM and two BOD offset reviewers. Resolve the readiness list before HR finalizes and submits to Finance. Finalization freezes the schedule version; subsequent changes require independent scoped HR Manager approval and a linked timekeeping version.',link:'/payroll/timekeeping'},
  {phase:'4 · Gross pay',link:'/payroll/gross-pay',owner:'HR + Finance',todo:'Confirm divisor applicability, proration and rounding. Supply independently checked normal, mid-cutoff change and holiday/night/OT examples to compare with the explanation of each amount.'},
  {phase:'5 · Take-home pay',link:'/payroll/net-pay',owner:'Finance + HR',todo:'Fill the batch review workbook: monthly contribution bases/coverage, taxable and exempt portions with benefit-limit evidence, prior-employer/YTD balances and loan authorizations. Confirm contribution allocation and insufficient-net policy. Compare one full checked payroll and two cutoffs of the same contribution month; include a final loan installment smaller than the regular amount.'},
  {phase:'6 · Special pay / corrections',link:'/payroll/special-pay',owner:'HR + Finance',todo:'Compare three real cases: a past salary correction, 13th-month pay from actual basic earnings, and final pay matching the HRIS end date. Supply earlier settlements, approved leave conversion, authorized accountabilities, benefit-limit usage and current/previous-employer tax balances. An independent Finance reviewer checks each saved version.'},
  {phase:'7 · Approvals / payslips',link:'/payroll/approvals',owner:'HR + Finance + two BOD users',todo:'Assign eligible HR reviewers, HR Manager, independent Finance authorizer and two distinct BODs. Preparers/material PR editors cannot approve their own version. Walk one shadow version through every step, return/revise one, and verify stale/out-of-order/repeated approvals are blocked. Employee release requires confirmed full live payment; individual outcomes and linked unpaid reissues are in Payments & Reports. Special-pay settlements use the assigned existing process.'},
  {phase:'8 · Payment / reports',link:'/payroll/payments',owner:'Finance',todo:'Assign the actual owners and existing bank, BIR 1601-C/1604-C/2316, SSS, PhilHealth, Pag-IBIG and special-pay processes. Verify current bank details and compare register, contribution/tax workpapers and payment totals. Supply an approved bank specification before any bank upload format is built. Real failure/return/reissue and loan-reversal acceptance waits for Phase 9 prerequisites; do not create fake payment evidence.'},
  {phase:'9 · Compare / activate',link:'/payroll/pilot',owner:'Kay + HR + Finance',todo:'Compare two consecutive real shadow cutoffs covering one contribution month using the whole-cutoff workbook. Complete independent HR/Finance acceptance; name the pilot BU, first live cutoff, legacy ownership/stop, opening balances and existing filing owners. Two BODs approve the handover; a scoped access manager activates only that BU. Reconcile the actual first live payment and obtain HR/Finance review before continuing or adding another BU.'},
];
