export const phaseChecklist = [
  {phase:'1 · Payroll access',owner:'Kay + HR / Finance',todo:'Confirm who finalizes timekeeping, prepares the PR, reviews/endorses, authorizes HR, authorizes Finance, gives the two BOD approvals, and releases payment. Assign each person the appropriate BU or All business units.',link:'/payroll/access'},
  {phase:'2 · Pay packages',owner:'HR + Finance',todo:'Review current salary amounts, allowances, real effective dates and approved salary changes. Confirm any separate consultant engagement, bank details, payday calendar and unresolved component treatments.',link:'/payroll/pay-packages'},
  {phase:'3 · Attendance readiness',owner:'BU managers + HR',todo:'Enter actual dated shifts and explicit rest days in the existing roster. Provide clock/biometric punches. Complete leave, WFH and OT approvals; verify holiday coverage and prescribed lunch times. Identify the HR Manager, GM and two BOD offset reviewers. Resolve the readiness list before HR submits the saved version to Finance.',link:'/payroll/timekeeping'},
  {phase:'4 · Gross pay',link:'/payroll/gross-pay',owner:'HR + Finance',todo:'Confirm divisor applicability, proration and rounding. Supply independently checked normal, mid-cutoff change and holiday/night/OT examples to compare with the explanation of each amount.'},
  {phase:'5 · Take-home pay',link:'/payroll/net-pay',owner:'Finance + HR',todo:'Fill the batch review workbook: monthly contribution bases/coverage, taxable and exempt portions with benefit-limit evidence, prior-employer/YTD balances and loan authorizations. Confirm contribution allocation and insufficient-net policy. Compare one full checked payroll and two cutoffs of the same contribution month; include a final loan installment smaller than the regular amount.'},
  {phase:'6 · Special pay / corrections',link:'/payroll/special-pay',owner:'HR + Finance',todo:'Compare three real cases: a past salary correction, 13th-month pay from actual basic earnings, and final pay matching the HRIS end date. Supply earlier settlements, approved leave conversion, authorized accountabilities, benefit-limit usage and current/previous-employer tax balances. An independent Finance reviewer checks each saved version.'},
  {phase:'7 · Approvals / payslips',link:'/payroll/approvals',owner:'HR + Finance + two BOD users',todo:'Assign eligible HR reviewers, HR Manager, independent Finance authorizer and two distinct BODs. Preparers/material PR editors cannot approve their own version. Walk one shadow version through every step, return/revise one, and verify stale/out-of-order/repeated approvals are blocked. Employee release requires confirmed full live payment; failed, partial and special-pay settlement handling remains Phase 8.'},
  {phase:'8 · Payment / reports',owner:'Finance',todo:'Provide the actual bank file specification if an export is needed and the current report/filing process. Reconcile totals and define how successful, failed and reissued payments are recorded.'},
  {phase:'9 · Compare / activate',owner:'Kay + HR + Finance',todo:'Select the pilot BU and handover cutoff. Review two full cutoffs of comparisons and resolve every unexplained difference before authorizing live processing.'},
];
