export const phaseChecklist = [
  {phase:'1 · Payroll access',owner:'Kay + HR / Finance',todo:'Confirm who finalizes timekeeping, prepares the PR, reviews/endorses, authorizes HR, authorizes Finance, gives the two BOD approvals, and releases payment. Assign each person the appropriate BU or All business units.',link:'/payroll/access'},
  {phase:'2 · Pay packages',owner:'HR + Finance',todo:'Review current salary amounts, allowances, real effective dates and approved salary changes. Confirm any separate consultant engagement, bank details, payday calendar and unresolved component treatments.',link:'/payroll/pay-packages'},
  {phase:'3 · Attendance readiness',owner:'BU managers + HR',todo:'Enter actual dated shifts and explicit rest days in the existing roster. Provide clock/biometric punches. Complete leave, WFH and OT approvals; verify holiday coverage and prescribed lunch times. Identify the HR Manager, GM and two BOD offset reviewers. Resolve the readiness list before HR submits the saved version to Finance.',link:'/payroll/timekeeping'},
  {phase:'4 · Gross pay',owner:'HR + Finance',todo:'Confirm divisor applicability, proration and rounding. Supply independently checked normal, mid-cutoff change and holiday/night/OT examples to compare with the explanation of each amount.'},
  {phase:'5 · Take-home pay',owner:'Finance + HR',todo:'Review statutory/tax employee data and applicable current rules; reconcile year-to-date/opening balances and outstanding loans/deductions. Provide one checked full payroll and two cutoffs covering a contribution month.'},
  {phase:'6 · Special pay / corrections',owner:'HR + Finance',todo:'Provide a real correction example, 13th-month records and a separated employee case, including leave conversion, accountabilities and any earlier payments.'},
  {phase:'7 · Approvals / payslips',owner:'HR + Finance + two BOD users',todo:'Confirm actual assignees, complete the ordered review using the same PR version, and decide when employees may receive payslips if payment is pending or failed.'},
  {phase:'8 · Payment / reports',owner:'Finance',todo:'Provide the actual bank file specification if an export is needed and the current report/filing process. Reconcile totals and define how successful, failed and reissued payments are recorded.'},
  {phase:'9 · Compare / activate',owner:'Kay + HR + Finance',todo:'Select the pilot BU and handover cutoff. Review two full cutoffs of comparisons and resolve every unexplained difference before authorizing live processing.'},
];
