import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import {useAuth} from '../../hooks/useAuth';
import PhaseChecklist from './PhaseChecklist';
import {listApprovals} from './approvals';
import type {ApprovalSummary} from './approvals';
import {setShadow} from './grossPay';
import {pilotWorkspace,comparisonTemplate,saveComparison,acceptComparison,proposePilot,approvePilot,activatePilot,reviewPilot,continuePilot,pilotEvidence} from './pilot';
import type {PilotWorkspace,CompareTemplate,CompareInput} from './pilot';
const input='mt-1 block w-full rounded border border-gray-300 p-2 dark:bg-slate-800 dark:border-slate-600';
export default function PilotPage(){
 const {user}=useAuth();const [scopeId,setScopeId]=useState('');const [w,setW]=useState<PilotWorkspace|null>(null);const [runs,setRuns]=useState<ApprovalSummary[]>([]);
 const [runId,setRunId]=useState('');const [template,setTemplate]=useState<CompareTemplate|null>(null);const [upload,setUpload]=useState<CompareInput|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const [reference,setReference]=useState(''),[confirmBU,setConfirmBU]=useState('');
 const [first,setFirst]=useState(''),[second,setSecond]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[evidence,setEvidence]=useState<Record<string,string>>({});const [liveRun,setLiveRun]=useState('');
 const scope=w?.scopes.find(s=>s.id===scopeId);const accepted=w?.comparisons.filter(c=>c.ready&&c.acceptances.length===2)??[];
 useEffect(()=>{let active=true;setW(null);setRuns([]);setTemplate(null);setUpload(null);setRunId('');setFirst('');setSecond('');setLiveRun('');setEvidence({});setReference('');setConfirmBU('');setError('');setBusy(true);
 void Promise.all([pilotWorkspace(scopeId||null),listApprovals()]).then(([data,items])=>{if(active){setW(data);setRuns(items.filter(r=>(r as ApprovalSummary&{scopeId:string}).scopeId===scopeId));}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[user?.id,scopeId]);
 async function perform(work:()=>Promise<unknown>,message:string){setBusy(true);setError('');setNotice('');try{await work();setW(await pilotWorkspace(scopeId||null));setNotice(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function load(id:string){setRunId(id);setTemplate(null);setUpload(null);if(id)await perform(async()=>setTemplate(await comparisonTemplate(id)),'Comparison source loaded.');}
 const refOK=reference.trim().length>=3;
 return <div className="space-y-6"><h1 className="text-3xl font-bold">Compare & Pilot</h1><p>Compare two real cutoffs, agree the handover, then activate one business unit. The first live cutoff must be paid and reviewed before continuing.</p><PhaseChecklist/>
 {error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded bg-green-50 p-3 text-green-800">{notice}</p>}
 <Card title="Business unit"><label>Choose business unit<select disabled={busy} className={input} value={scopeId} onChange={e=>setScopeId(e.target.value)}><option value="">Select…</option>{w?.scopes.map(s=><option key={s.id} value={s.id}>{s.name} · {s.mode}</option>)}</select></label>{!w?.scopes.length&&!busy&&<p className="mt-3">Your scoped Payroll Access assignment is needed. <Link className="text-indigo-600" to="/payroll/access">Manage Payroll Access</Link></p>}{scope&&<p className="mt-3 font-medium">Processing: {scope.mode}. Other business units keep their own processing setting.</p>}{w?.blockedReason&&<p className="mt-3">{w.blockedReason}</p>}</Card>
 {scope&&<><Card title="Team readiness"><ol className="list-decimal space-y-2 pl-5"><li>Assign actual HR, Finance and two BOD reviewers in <Link to="/payroll/access" className="text-indigo-600">Payroll Access</Link>. Existing HRIS permissions still apply.</li><li>Complete schedules, punches, approved leave/OT, reviewed pay and policy inputs. Use retained actual cutoffs or complete upcoming cutoffs.</li><li>Prepare and approve two consecutive shadow cutoffs covering one contribution month. HR and Finance accept each comparison. Accepted comparisons available: {accepted.length}.</li><li>Assign all eight existing bank, tax, agency and special-pay processes in <Link to="/payroll/payments" className="text-indigo-600">Payments & Reports</Link>. Recorded process types: {w?.processCount??0}/8.</li><li>Finance documents opening balances, legacy payroll ownership and the first live cutoff; two BODs approve. Kay or another scoped access manager activates that BU.</li></ol><p className="mt-3 text-sm">Checklist status alone never enables processing. Unsupported special-pay settlements and unvalidated submission formats remain with the assigned existing process.</p></Card>
 <Card title="Decision reference"><label className="block">Reference for the acceptance, BOD decision, activation, continuation or stop you are recording<textarea className={input} minLength={3} maxLength={1000} value={reference} disabled={busy} onChange={e=>setReference(e.target.value)}/></label><p className="mt-2 text-sm">Enter this before recording an acceptance or processing decision. Each action saves its own copy of the reference.</p></Card>
 {scope.canView&&<><Card title="1. Compare the entire cutoff"><label>Saved regular shadow approval version<select className={input} value={runId} disabled={busy} onChange={e=>void load(e.target.value)}><option value="">Select…</option>{runs.filter(r=>r.mode==='shadow'&&r.kind==='regular'&&r.current).map(r=><option key={r.id} value={r.id}>{r.from}–{r.to} · v{r.version} · {r.stage}</option>)}</select></label>{!runs.length&&<p className="mt-3">No submitted payroll is available yet. Start with <Link to="/payroll/net-pay" className="text-indigo-600">Take-home Pay Review</Link>, then complete <Link to="/payroll/approvals" className="text-indigo-600">Payroll Approvals</Link>.</p>}
 {template&&<div className="mt-4 space-y-3"><Button variant="secondary" disabled={busy} onClick={()=>void perform(async()=>{const m=await import('./comparisonWorkbook');await m.downloadComparisonWorkbook(template);},'Whole-cutoff template downloaded.')}>Download whole-cutoff workbook</Button><p>Fill the legacy amounts, complete legacy employee roster and source references. Explain every difference and cite its approved policy. Upload once for the whole cutoff.</p>{w?.canPrepare&&<><label className="block">Preview completed workbook<input type="file" accept=".xlsx" className={input} disabled={busy} onChange={e=>{const f=e.target.files?.[0];setUpload(null);if(f)void perform(async()=>{const m=await import('./comparisonWorkbook');setUpload(await m.parseComparisonWorkbook(await f.arrayBuffer(),template));},'Workbook checked locally; save to record it.');e.target.value='';}}/></label>{upload&&<div><p>{upload.legacyEmployees.length} employees · {upload.rows.length} component/total rows · legacy reference: {upload.sourceRef}</p><Button disabled={busy} onClick={()=>void perform(async()=>{await saveComparison(template,upload);setUpload(null);},'Comparison revision saved. HR and Finance can review the differences below.')}>Save comparison revision</Button></div>}</>}</div>}</Card>
 <Card title="2. Review differences and accept"><p>Zero differences are included in the saved comparison. Every nonzero difference needs both an explanation and policy evidence; acceptance records your review of them.</p>{w?.comparisons.length===0&&<p className="mt-3">No comparisons recorded.</p>}{w?.comparisons.map(c=><details key={c.id} className="mt-4 rounded border p-3"><summary>{c.from}–{c.to} · {c.rows.filter(r=>Number(r.difference)!==0).length} differences · {c.acceptances.length}/2 acceptances · {c.ready?'Ready for acceptance':'Needs attention'}</summary><p className="mt-3">{c.sourceRef} · {c.coverageRef}</p>{c.blockedReason&&<p className="mt-2 text-amber-800">{c.blockedReason}</p>}<div className="overflow-x-auto"><table className="my-3 w-full text-left text-sm"><thead><tr>{['Employee / component','System PHP','Legacy PHP','Difference','Explanation / source'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{c.rows.filter(r=>Number(r.difference)!==0).map(r=><tr key={`${r.employeeId}/${r.key}`} className="border-t"><td className="p-2">{r.employeeName}<br/>{r.label}</td><td className="p-2">{r.amount}</td><td className="p-2">{r.legacyAmount}</td><td className="p-2">{r.difference}</td><td className="p-2">{r.explanation||'Missing explanation'}<br/>{r.policyRef||'Missing policy reference'}</td></tr>)}</tbody></table></div>{c.acceptances.map(a=><p key={a.duty}>{a.duty}: {a.actor} · {a.reference}</p>)}<div className="mt-3 flex gap-3">{c.canHR&&<Button disabled={busy||!refOK} onClick={()=>void perform(()=>acceptComparison(c.id,'hr',reference),'HR acceptance recorded.')}>Accept as HR</Button>}{c.canFinance&&<Button disabled={busy||!refOK} onClick={()=>void perform(()=>acceptComparison(c.id,'finance',reference),'Finance acceptance recorded.')}>Accept as Finance</Button>}</div></details>)}</Card>
 {w?.canPropose&&!w.activation&&<Card title="3. Propose the first live cutoff"><form className="space-y-3" onSubmit={e=>{e.preventDefault();void perform(()=>proposePilot(scopeId,first,second,from,to,evidence),'Pilot proposed. Two distinct BOD decisions are required.');}}><div className="grid gap-3 sm:grid-cols-2">{[['First accepted cutoff',first,setFirst],['Second accepted cutoff',second,setSecond]].map(([label,value,set])=><label key={label as string}>{label as string}<select required className={input} value={value as string} disabled={busy} onChange={e=>(set as (s:string)=>void)(e.target.value)}><option value="">Select…</option>{accepted.map(c=><option key={c.id} value={c.id}>{c.from}–{c.to} · {c.sourceRef}</option>)}</select></label>)}<label>First live cutoff starts<input required type="date" className={input} value={from} disabled={busy} onChange={e=>setFrom(e.target.value)}/></label><label>First live cutoff ends<input required type="date" className={input} value={to} disabled={busy} onChange={e=>setTo(e.target.value)}/></label></div>{pilotEvidence.map(([key,label])=><label className="block" key={key}>{label}<textarea required minLength={3} maxLength={1000} className={input} value={evidence[key]??''} disabled={busy} onChange={e=>setEvidence(v=>({...v,[key]:e.target.value}))}/></label>)}<p className="text-sm">These references must identify actual reconciliations and who owns payment at handover. TNG HRIS cannot switch off an external payroll system for you.</p><Button disabled={busy||accepted.length<2}>Submit pilot proposal</Button></form></Card>}
 <Card title="4. BOD decisions and scoped activation">{w?.proposals.length===0&&<p>No pilot has been proposed. Payroll stays at its current setting.</p>}{w?.proposals.map(p=><div key={p.id} className="mb-4 rounded border p-3"><strong>{p.date_from}–{p.date_to} · BOD decisions {p.decisions.length}/2</strong><details className="my-3"><summary>Review handover evidence</summary>{pilotEvidence.map(([key,label])=><p className="mt-2" key={key}><strong>{label}:</strong> {p.evidence[key]}</p>)}</details>{p.decisions.map(d=><p key={d.actor}>{d.actor} · {d.reference}</p>)}{p.blockedReason&&!w.activation&&<p className="my-2 text-amber-800">{p.blockedReason}</p>}{p.canBOD&&<Button disabled={busy||!refOK} onClick={()=>void perform(()=>approvePilot(p.id,reference),'BOD pilot approval recorded.')}>Approve this pilot as BOD</Button>}{scope.canManage&&scope.mode!=='live'&&((p.ready&&p.decisions.length===2&&!w.activation)||w.activation?.proposal_id===p.id)&&<Button disabled={busy||!refOK||confirmBU!==scope.name} onClick={()=>void perform(()=>activatePilot(p.id,reference),'This business unit is now live within its approved handover window.')}>{w.activation?'Resume':'Activate'} live payroll for {scope.name}</Button>}</div>)}</Card>
 {w?.activation&&<Card title="5. Review the actual first live cutoff"><p>Reconcile actual payments, any failures/returns/reissues, loan postings and employee payslips. HR and Finance record independent acceptance below. Future cutoffs stay blocked until both reviews are current and the access manager continues.</p><label className="mt-3 block">Paid first live approval version<select className={input} value={liveRun} disabled={busy} onChange={e=>setLiveRun(e.target.value)}><option value="">Select…</option>{runs.filter(r=>r.mode==='live'&&r.paid).map(r=><option key={r.id} value={r.id}>{r.from}–{r.to} · v{r.version}</option>)}</select></label><div className="my-3 flex flex-wrap gap-3">{w.canHR&&<Button disabled={busy||!refOK||!liveRun} onClick={()=>void perform(()=>reviewPilot(w.activation!.id,liveRun,'hr',reference),'HR first-live-cutoff review recorded.')}>Accept first live cutoff as HR</Button>}{w.canFinance&&<Button disabled={busy||!refOK||!liveRun} onClick={()=>void perform(()=>reviewPilot(w.activation!.id,liveRun,'finance',reference),'Finance first-live-cutoff review recorded.')}>Accept first live cutoff as Finance</Button>}</div>{w.activation.monitoring.map((m,i)=><p key={i}>{m.duty}: {m.reference}</p>)}{w.activation.continued?<p className="mt-3 font-semibold">First live cutoff accepted. Subsequent regular cutoffs and the next BU’s pilot are permitted.</p>:scope.canManage&&<Button disabled={busy||!refOK||confirmBU!==scope.name} onClick={()=>void perform(()=>continuePilot(w.activation!.id,reference),'Pilot review accepted. Subsequent cutoffs and the next BU’s pilot can proceed.')}>Continue this BU after pilot review</Button>}</Card>}
 </>}
 <Card title="Processing controls">{scope.canManage&&<><label className="mt-3 block">For activation or continuation, type the business unit name: {scope.name}<input className={input} value={confirmBU} disabled={busy} onChange={e=>setConfirmBU(e.target.value)}/></label><Button className="mt-3" variant="secondary" disabled={busy||!refOK||scope.mode==='off'} onClick={()=>void perform(()=>setShadow(scopeId,false,reference),'Processing stopped for this business unit. Existing receipts and review records are retained.')}>Stop processing for {scope.name}</Button><p className="mt-3 text-sm">To prepare shadow comparisons, enable the BU and parent shadow gate in <Link className="text-indigo-600" to="/payroll/gross-pay">Gross Pay Review</Link>. Stopping processing does not cancel a bank instruction already sent through your existing process.</p></>}</Card></>}
 </div>;
}
