import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import Button from '../../components/ui/Button';
import AttendanceCorrection from '../../components/attendance/AttendanceCorrection';
import {getHrAttendanceDay,AttendanceDay} from '../../services/employeeAttendance';
import {applyPayrollAttendancePreset} from './attendanceReadiness';
import {presetForIssue} from './readinessDashboardModel';

const labels:Record<string,{title:string;detail:string;action:string}>={
 use_scheduled_break:{title:'Use scheduled break',detail:'Set break to 12:00 PM–1:00 PM.',action:'Use this'},mark_break_compliant:{title:'Mark break compliant',detail:'No pay impact; retain original punch evidence.',action:'Use this'},keep_exception:{title:'Keep as exception',detail:'Send to manager for review.',action:'Send for review'},use_scheduled_end:{title:'Use scheduled end time',detail:'Add the published shift end as clock-out.',action:'Use this'},send_clarification:{title:'Send for clarification',detail:'Keep the record open and request verified information.',action:'Send for clarification'},open_schedule:{title:'Open schedule builder',detail:'Publish the missing schedule for this date.',action:'Open schedule'},copy_previous_schedule:{title:'Copy previous schedule',detail:'Open the builder and copy the employee’s prior week.',action:'Open builder'},request_schedule_confirmation:{title:'Request schedule confirmation',detail:'Keep payroll blocked until the schedule is confirmed.',action:'Request confirmation'},review_lateness:{title:'Review lateness',detail:'Inspect the original punch and pay impact.',action:'Review'},approved_adjustment:{title:'Apply approved adjustment',detail:'Record a reviewed attendance adjustment.',action:'Use this'},send_manager:{title:'Send to manager',detail:'Require manager review before payroll is ready.',action:'Send for review'},open_advanced:{title:'Open advanced fields',detail:'Enter only the verified time that needs correction.',action:'Open fields'}
};
const display=(stamp:string)=>new Date(stamp).toLocaleString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});

export default function PresetAttendanceCorrection({scopeId,employeeId,employeeName,date,issue,businessUnit,cycleLabel,onSaved}:{scopeId:string;employeeId:string;employeeName:string;date:string;issue:string;businessUnit:string;cycleLabel:string;onSaved:(openNext:boolean)=>Promise<void>|void}){
 const [day,setDay]=useState<AttendanceDay|null>(null);const [selected,setSelected]=useState('');const [note,setNote]=useState('');const [openNext,setOpenNext]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const presets=useMemo(()=>presetForIssue(issue),[issue]);
 useEffect(()=>{let active=true;setBusy(true);getHrAttendanceDay(employeeId,date).then(value=>{if(active)setDay(value);}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Attendance record could not be loaded.');}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[employeeId,date]);
 const scheduled=day?.schedule.entries.find(entry=>entry.kind==='work');const save=async(continueToNext=openNext)=>{if(!selected)return;if(['open_schedule','copy_previous_schedule','open_advanced'].includes(selected))return;setBusy(true);setError('');setNotice('');try{await applyPayrollAttendancePreset(scopeId,employeeId,date,selected,note);setNotice('Correction saved. Payroll readiness and affected dates were recalculated.');await onSaved(continueToNext);}catch(reason){setError(reason instanceof Error?reason.message:'Correction could not be saved.');}finally{setBusy(false);}};
 return <div className="space-y-5">{error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-900">{notice}</p>}
  <section className="rounded-2xl bg-gradient-to-r from-violet-50 to-indigo-50 p-6 dark:from-violet-950/30 dark:to-indigo-950/20"><div className="flex flex-wrap items-start gap-4"><span className="grid h-14 w-14 place-items-center rounded-full bg-violet-200 text-lg font-bold text-violet-800">{employeeName.split(/\s+/).map(part=>part[0]).slice(0,2).join('')}</span><div><h2 className="text-xl font-bold">{employeeName} · {new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',month:'long',day:'numeric',year:'numeric'}).format(new Date(`${date}T12:00:00Z`))}</h2><span className="mt-2 inline-block rounded-lg bg-amber-100 px-3 py-2 text-sm font-semibold text-amber-900">⚠ {issue}</span><p className="mt-2 text-sm text-slate-500">{businessUnit} · {cycleLabel}</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div><p className="text-sm text-slate-500">Scheduled</p><strong>{scheduled?`${scheduled.start}–${scheduled.end}`:'Missing schedule'}</strong></div><div><p className="text-sm text-slate-500">Recorded punches</p>{day?.events.length?day.events.map(event=><p className="text-sm" key={event.id||`${event.type}:${event.timestamp}`}>{event.type.replaceAll('_',' ')} · {display(event.timestamp)}</p>):<strong>Missing</strong>}</div><div><p className="text-sm text-slate-500">Attendance / pay impact</p><strong className="text-rose-700">{issue} · Review needed</strong></div></div></section>
  <div className="grid gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(300px,.75fr)]"><section className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><h3 className="text-xl font-bold">Choose the quickest correction</h3><p className="mt-1 text-sm text-slate-500">Select a preset. One click plus save resolves common issues without re-entering every time field.</p><div className="mt-4 grid gap-3 md:grid-cols-3">{presets.map(preset=>{const config=labels[preset]||{title:preset.replaceAll('_',' '),detail:'Use the approved workflow for this issue.',action:'Use this'};const navigation=['open_schedule','copy_previous_schedule'].includes(preset);return <div className={`rounded-xl border p-4 ${selected===preset?'border-violet-600 bg-violet-50 dark:bg-violet-950/20':'dark:border-slate-700'}`} key={preset}><button type="button" className="w-full text-left" onClick={()=>setSelected(preset)}><span className="mb-5 block h-5 w-5 rounded-full border-2 border-violet-500 p-0.5">{selected===preset&&<span className="block h-full w-full rounded-full bg-violet-600"/>}</span><strong className="block">{config.title}</strong><p className="mt-2 min-h-10 text-sm text-slate-500">{config.detail}</p></button>{navigation?<Link className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-lg bg-violet-600 px-3 font-semibold text-white" to="/payroll/timekeeping">{config.action}</Link>:<Button className="mt-4 w-full" variant={selected===preset?'primary':'secondary'} onClick={()=>setSelected(preset)}>{config.action}</Button>}</div>;})}</div><p className="mt-4 rounded-lg bg-slate-50 p-3 text-sm text-slate-600 dark:bg-slate-800">ⓘ Common corrections use a preset. Open advanced fields only when needed.</p><details className="mt-4 rounded-xl border p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">Advanced details · show all time fields</summary><AttendanceCorrection employee={employeeId} date={date} requireAuthorization onSaved={()=>void onSaved(openNext)}/></details></section>
   <aside className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><h3 className="text-xl font-bold">What will happen</h3><ul className="mt-4 space-y-3 text-sm"><li>✓ Attendance status is recalculated</li><li>✓ Only this employee and date refresh</li><li>✓ Original punches remain in audit history</li><li>✓ Duplicate corrections are prevented</li></ul><label className="mt-6 block text-sm font-medium">Correction note (optional)<textarea className="mt-2 min-h-28 w-full rounded-xl border bg-transparent p-3" value={note} onChange={event=>setNote(event.target.value)} placeholder="Add a note only if this is unusual." maxLength={1000}/></label><p className="mt-1 text-xs text-slate-500">Not required for preset actions.</p></aside></div>
  <footer className="flex flex-wrap items-center justify-between gap-3 border-t pt-5 dark:border-slate-700"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={openNext} onChange={event=>setOpenNext(event.target.checked)}/>Open next issue after saving</label><div className="flex flex-wrap gap-3"><Button variant="secondary" disabled={busy||!selected||['open_schedule','copy_previous_schedule','open_advanced'].includes(selected)} onClick={()=>void save(false)}>Save correction</Button><Button disabled={busy||!selected||['open_schedule','copy_previous_schedule','open_advanced'].includes(selected)} onClick={()=>void save()}>Save & recalculate</Button><Link className="inline-flex min-h-11 items-center rounded-lg border px-4 font-semibold" to="/payroll/attendance-readiness">Cancel</Link></div></footer>
 </div>;
}
