import React,{useEffect,useState} from 'react';
import {supabase} from '../../services/supabaseClient';
type RecordPayment={id:string;amount:string;paid_on:string;reference:string;evidence:string;status:string;canReview:boolean};
const currency=(v:number|string)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(v));
export default function PreviousPaymentCard({scope,from,to,net}:{scope:string;from:string;to:string;net?:string}){
 const [records,setRecords]=useState<RecordPayment[]>([]),[canRecord,setCanRecord]=useState(false),[open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 const [form,setForm]=useState({amount:'',paidOn:'',reference:'',evidence:''}),[note,setNote]=useState('');
 useEffect(()=>{let active=true;Promise.resolve(supabase.rpc('get_payroll_previous_payments',{p_scope:scope,p_from:from,p_to:to})).then(({data,error})=>{if(!active)return;if(error)setError(error.message);else{setRecords(data.records);setCanRecord(data.canRecord);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[scope,from,to,revision]);
 async function save(){setBusy(true);setError('');try{const {error}=await supabase.rpc('record_payroll_previous_payment',{p_scope:scope,p_from:from,p_to:to,p_amount:form.amount,p_paid_on:form.paidOn,p_reference:form.reference,p_evidence:form.evidence});if(error)throw error;setOpen(false);setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function review(id:string,decision:string){setBusy(true);setError('');try{const {error}=await supabase.rpc('review_payroll_previous_payment',{p_id:id,p_decision:decision,p_note:note});if(error)throw error;setRevision(v=>v+1);setNote('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const verified=records.filter(r=>r.status==='verified').reduce((a,r)=>a+Number(r.amount),0);
 return <section className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h2 className="text-lg font-bold">Already paid outside HRIS?</h2><p className="my-3 text-sm text-slate-500">Record actual payment evidence. A past pay date alone does not mean paid.</p>{error&&<p role="alert" className="my-3 text-sm text-red-700">{error}</p>}
  {records.map(r=><div key={r.id} className="my-3 border-t py-3 text-sm"><strong>{currency(r.amount)}</strong> · {r.paid_on}<p>{r.reference} · {r.status.replaceAll('_',' ')}</p><a className="text-violet-700 underline" href={r.evidence} target="_blank" rel="noopener noreferrer">View payment evidence</a>{r.canReview&&<div className="mt-2"><input aria-label="Payment verification note" value={note} onChange={e=>setNote(e.target.value)} className="w-full rounded-lg border p-2" placeholder="Document and amount verified"/><button disabled={busy||!note.trim()} className="mt-2 rounded-lg border p-2 text-violet-700" onClick={()=>void review(r.id,'verified')}>Verify previous payment</button><button disabled={busy||!note.trim()} className="ml-2 rounded-lg border p-2" onClick={()=>void review(r.id,'rejected')}>Reject evidence</button></div>}</div>)}
  {records.some(r=>r.status!=='rejected')&&<p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">A second disbursement is blocked. Recorded evidence does not post loan repayments or leave movements.</p>}
  {!!verified&&net!==undefined&&<p className="mt-3 text-sm">Calculated net: {currency(net)}<br/>Verified previous payment: {currency(verified)}<br/><strong>Difference: {currency(Number(net)-verified)}</strong></p>}
  {canRecord&&!open&&<button className="mt-3 font-semibold text-violet-700" onClick={()=>setOpen(true)}>Record previous payment →</button>}
  {open&&<form onSubmit={e=>{e.preventDefault();void save();}} className="mt-3 space-y-3">{[['amount','Actual amount','number'],['paidOn','Actual payment date','date'],['reference','Payment reference','text'],['evidence','Evidence document URL','url']].map(([key,label,type])=><label key={key} className="block text-sm">{label}<input required type={type} min={type==='number'?'0.01':undefined} step={type==='number'?'0.01':undefined} className="mt-1 w-full rounded-lg border p-2" value={form[key as keyof typeof form]} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))}/></label>)}<p className="text-sm text-slate-500">Independent Finance or BOD verification is required. This records evidence; it does not make a payment.</p><button disabled={busy} className="rounded-lg bg-violet-600 px-3 py-2 text-white">Save payment evidence</button></form>}
 </section>;
}
