import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import Button from '../../components/ui/Button';
import type {ReviewTimeRow} from './attendanceReadiness';
import {applyPayrollGraceBulk,fetchPayrollAttendanceActions} from './attendanceReadiness';
import {attendanceFixCandidates} from './readinessDashboardModel';
import {formatCutoff,payrollCycleForCutoff,payrollCycleLabel} from './payrollCycle';

const field='min-h-11 rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-600 dark:bg-slate-800';
const displayDate=(value:string)=>new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric'}).format(new Date(`${value}T12:00:00Z`));
const clock=(value:string)=>{if(/am|pm/i.test(value))return value;const [hour,minute]=value.split(':').map(Number);return `${hour%12||12}:${String(minute||0).padStart(2,'0')} ${hour>=12?'PM':'AM'}`;};

export default function QuickAttendanceFixes({rows,scopeId,scopeName,from,to,onApplied}:{rows:ReviewTimeRow[];scopeId:string;scopeName:string;from:string;to:string;onApplied:()=>Promise<void>|void}){
 const [employee,setEmployee]=useState('');const [dateFrom,setDateFrom]=useState('');const [dateTo,setDateTo]=useState('');const [selected,setSelected]=useState<Set<string>>(new Set());const [resolved,setResolved]=useState<Set<string>>(new Set());const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [summary,setSummary]=useState<{applied:number;skipped:string[]} | null>(null);
 const candidates=useMemo(()=>attendanceFixCandidates(rows,5).filter(item=>!resolved.has(item.key)),[rows,resolved]);const employees=useMemo(()=>[...new Set(candidates.map(item=>item.employeeName))].sort(),[candidates]);
 useEffect(()=>{let active=true;void fetchPayrollAttendanceActions(scopeId,from,to).then(actions=>{if(active)setResolved(new Set(actions.filter(action=>action.action==='grace_applied').map(action=>`${action.employeeId}:${action.date}`)));}).catch(()=>{});return()=>{active=false;};},[scopeId,from,to]);
 const filtered=candidates.filter(item=>(!employee||item.employeeName===employee)&&(!dateFrom||item.date>=dateFrom)&&(!dateTo||item.date<=dateTo));const eligible=filtered.filter(item=>item.eligible),detailed=filtered.filter(item=>!item.eligible);const cycle=payrollCycleForCutoff(from,to);
 const apply=async(items:typeof candidates)=>{if(!items.length||!window.confirm(`Apply the approved grace period to ${items.length} selected attendance record${items.length===1?'':'s'}?`))return;setBusy(true);setError('');setSummary(null);try{const result=await applyPayrollGraceBulk(scopeId,from,to,items.map(item=>({employeeId:item.employeeId,date:item.date})));setResolved(current=>new Set([...current,...result.applied.map(item=>`${item.employeeId}:${item.date}`)]));setSelected(new Set());setSummary({applied:result.applied.length,skipped:result.skipped.map(item=>`${item.date}: ${item.reason}`)});await onApplied();}catch(reason){setError(reason instanceof Error?reason.message:'Grace could not be applied.');}finally{setBusy(false);}};
 return <div className="space-y-5">
  <header className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">Quick attendance fixes</h2><p className="mt-1 text-sm text-slate-500">Review small exceptions without opening each attendance record.</p></div><Link className="text-sm font-semibold text-violet-700" to="/payroll/attendance-readiness#attendance-references">⚙ Manage grace-period policy</Link></header>
  <div className="rounded-xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><p className="font-bold text-violet-900 dark:text-violet-100">{cycle?payrollCycleLabel(cycle):`Special payroll · ${formatCutoff(from,to)}`}</p><p className="mt-1 text-sm text-slate-500">{scopeName} · Same cutoff rules across all business units</p></div>
  <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="text-sm font-medium">Business unit<select className={`${field} mt-1 w-full`} disabled><option>{scopeName}</option></select></label><label className="text-sm font-medium">Employee<select className={`${field} mt-1 w-full`} value={employee} onChange={event=>setEmployee(event.target.value)}><option value="">All employees</option>{employees.map(name=><option key={name}>{name}</option>)}</select></label><label className="text-sm font-medium">Issue type<select className={`${field} mt-1 w-full`} disabled><option>Minor and major lateness</option></select></label><label className="text-sm font-medium">Date from<input className={`${field} mt-1 w-full`} type="date" min={from} max={to} value={dateFrom} onChange={event=>setDateFrom(event.target.value)}/></label><label className="text-sm font-medium">Date to<input className={`${field} mt-1 w-full`} type="date" min={from} max={to} value={dateTo} onChange={event=>setDateTo(event.target.value)}/></label></section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[String(filtered.length),'Minor late arrivals','👥'],[String(eligible.length),'Eligible for grace','✓'],['₱0','Pay impact','₱'],[String(detailed.length),'Needs detailed review','!']].map(([value,label,icon])=><div className="rounded-xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-900" key={label}><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-violet-100 font-bold text-violet-700">{icon}</span><div><strong className="text-2xl">{value}</strong><p className="text-sm text-slate-500">{label}</p></div></div></div>)}</section>
  <div className="rounded-xl border border-violet-200 bg-violet-50 p-4 text-sm text-violet-950 dark:border-violet-800 dark:bg-violet-950/20 dark:text-violet-100"><strong>These arrivals are within the 5-minute grace period.</strong><p>Applying grace removes the late flag and records an automatic audit note: “Within approved grace period.”</p></div>
  {error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error}</p>}{summary&&<div role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-900"><strong>{summary.applied} attendance record{summary.applied===1?'':'s'} updated and recalculated.</strong>{summary.skipped.length>0&&<p className="mt-1">Skipped: {summary.skipped.join(' · ')}</p>}</div>}
  <section className="overflow-hidden rounded-xl border bg-white dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3 p-4"><div><h3 className="font-bold">Minor late arrivals (within grace period)</h3><p className="text-sm text-slate-500">Original punches remain unchanged in the audit trail.</p></div><Button disabled={busy||eligible.length===0} onClick={()=>void apply(eligible)}>⚡ Apply grace to all {eligible.length}</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 dark:bg-slate-800"><tr>{['','Employee','Date','Scheduled','Clock in','Difference','Status','Action'].map(label=><th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{eligible.map(item=><tr className="border-t dark:border-slate-700" key={item.key}><td className="p-3"><input aria-label={`Select ${item.employeeName} ${item.date}`} type="checkbox" checked={selected.has(item.key)} onChange={event=>setSelected(current=>{const next=new Set(current);if(event.target.checked)next.add(item.key);else next.delete(item.key);return next;})}/></td><td className="p-3 font-semibold">{item.employeeName}</td><td className="p-3">{displayDate(item.date)}</td><td className="p-3">{clock(item.scheduled)}</td><td className="p-3">{item.actual}</td><td className="p-3">{item.difference} min late</td><td className="p-3"><span className="rounded-full bg-emerald-100 px-3 py-1 font-semibold text-emerald-800">✓ Within grace</span></td><td className="p-3"><Button size="sm" disabled={busy} onClick={()=>void apply([item])}>Apply grace</Button></td></tr>)}{eligible.length===0&&<tr><td colSpan={8} className="p-6 text-center text-slate-500">No eligible minor lateness records match these filters.</td></tr>}</tbody></table></div>{selected.size>0&&<div className="sticky bottom-0 flex flex-wrap items-center justify-between gap-3 border-t bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><strong>{selected.size} selected</strong><Button disabled={busy} onClick={()=>void apply(eligible.filter(item=>selected.has(item.key)))}>⚡ Apply grace to selected</Button></div>}</section>
  {detailed.length>0&&<section className="overflow-hidden rounded-xl border border-rose-200 bg-rose-50/40 dark:border-rose-900"><div className="p-4"><h3 className="font-bold text-rose-900">⚠ Needs detailed review</h3><p className="text-sm text-slate-600">Only complex issues open the detailed correction screen.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] bg-white text-left text-sm dark:bg-slate-900"><thead><tr>{['Employee','Date','Scheduled','Clock in','Difference','Status','Action'].map(label=><th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{detailed.map(item=><tr className="border-t dark:border-slate-700" key={item.key}><td className="p-3 font-semibold">{item.employeeName}</td><td className="p-3">{displayDate(item.date)}</td><td className="p-3">{clock(item.scheduled)}</td><td className="p-3">{item.actual}</td><td className="p-3">{item.difference} min late</td><td className="p-3"><span className="rounded-full bg-amber-100 px-3 py-1 font-semibold text-amber-800">Major lateness</span></td><td className="p-3"><Link className="font-semibold text-violet-700" to={`/payroll/historical-corrections?employee=${item.employeeId}&date=${item.date}&issue=${encodeURIComponent('Major lateness')}`}>Open correction</Link></td></tr>)}</tbody></table></div></section>}
 </div>;
}
