import React,{useCallback,useEffect,useRef,useState} from 'react';
import {supabase} from '../../services/supabaseClient';
import Button from '../../components/ui/Button';
export type Item={employeeId:string;employeeName:string;date:string;breakMinutes:number;blocked:string|null;remainingIssues:string[]};
export type Review={id:string;items:Item[];status:string;canAct:boolean;stale:boolean;submitter:string;hrName:string|null;bodName:string|null;submitted_at:string;hr_at:string|null;bod_at:string|null;note:string|null};
type Workspace={sourceHash:string;items:Item[];reviews:Review[];route:string};
const key=(item:Item)=>`${item.employeeId}:${item.date}`;
const label=(status:string)=>({pending_hr_manager:'Waiting for HR Manager',pending_bod:'Waiting for one BOD',approved:'Applied',returned:'Returned',rejected:'Rejected'}[status]||status);
async function rpc<T>(name:string,args:Record<string,unknown>):Promise<T>{const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message);return data;}
export default function RecordedBreakApprovals({scope,from,to,employeeId,onApplied}:{scope:string;from:string;to:string;employeeId?:string;onApplied?:()=>void}){
 const [opened,setOpened]=useState(!!employeeId);
 const [data,setData]=useState<Workspace|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[notes,setNotes]=useState<Record<string,string>>({});
 const lock=useRef(false);const generation=useRef(0);
 const load=useCallback(async()=>{const n=++generation.current;try{const result=await rpc<Workspace>('get_payroll_break_review',{p_scope:scope,p_from:from,p_to:to});if(n===generation.current){setData(result);setSelected(new Set());}}catch(e){if(n===generation.current)setError((e as Error).message);}},[scope,from,to]);
 useEffect(()=>{if(!opened)return;setData(null);setError('');void load();return()=>{generation.current++;};},[load,opened]);
 const run=async(action:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await action();await load();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}};
 const items=(data?.items||[]).filter(item=>!employeeId||item.employeeId===employeeId),eligible=items.filter(item=>!item.blocked),chosen=eligible.filter(item=>selected.has(key(item)));
 const awaiting=items.filter(item=>item.blocked==='Already submitted for approval.');
 const corrections=items.filter(item=>!!item.blocked&&item.blocked!=='Already submitted for approval.');
 const pending=(data?.reviews||[]).filter(review=>['pending_hr_manager','pending_bod'].includes(review.status)&&(!employeeId||review.items.some(item=>item.employeeId===employeeId)));
 const submit=()=>run(async()=>{if(!data||!chosen.length)return;await rpc('submit_payroll_break_review',{p_scope:scope,p_from:from,p_to:to,p_hash:data.sourceHash,p_items:chosen.map(({employeeId,date})=>({employeeId,date}))});setNotice(`${chosen.length} recorded breaks submitted. ${data.route}. Attendance has not been changed.`);});
 const decide=(review:Review,action:string)=>run(async()=>{const status=await rpc<string>('decide_payroll_break_review',{p_id:review.id,p_action:action,p_note:notes[review.id]||''});setNotice(status==='approved'?'Recorded breaks accepted. Recalculate payroll; other pay decisions remain separate.':status==='pending_bod'?'HR Manager approved. Waiting for one independent BOD.':label(status));if(status==='approved')onApplied?.();});
 if(!opened)return <section className="my-4 rounded-xl border border-violet-200 p-4"><h3 className="font-bold">Recorded-break fixes and approvals</h3><p className="my-2 text-sm">Prepare one batch from uploaded break times, then HR Manager and one BOD can approve it.</p><Button onClick={()=>setOpened(true)}>Prepare break fixes &amp; approvals</Button></section>;
 return <section className="my-4 space-y-3 rounded-xl border border-violet-200 bg-white p-4 dark:bg-slate-900" aria-label="Recorded break decisions">
  <h3 className="text-lg font-bold">Accept uploaded break durations</h3>
  <p className="text-sm">Keep the uploaded break start and end times. HR and BOD can accept the recorded unpaid break duration instead of requiring exactly 60 minutes.</p>
  <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-950"><b>Effect:</b> clears only the break-duration review after final approval. Punches and calculated hours stay unchanged. This does not approve overtime, remove other blockers, or increase authorized pay.</p>
  {error&&<p role="alert" className="text-red-700">{error} <button className="underline" disabled={busy} onClick={()=>void load()}>Retry</button></p>}{notice&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-emerald-900">{notice}</p>}
  {!data&&!error&&<p role="status">Checking eligible dates…</p>}
  {data&&<>
   <p className="text-sm">{eligible.length} dates ready to submit · {awaiting.length} dates awaiting approval · {corrections.length} dates need correction</p>
   {eligible.length>0&&<><label className="flex items-center gap-2 font-semibold"><input type="checkbox" disabled={busy||!eligible.length} checked={eligible.length>0&&chosen.length===eligible.length} onChange={event=>setSelected(event.target.checked?new Set(eligible.map(key)):new Set())}/>Select all eligible dates</label>
   <div className="max-h-64 space-y-2 overflow-auto">{eligible.map(item=><label key={key(item)} className="flex items-start gap-2 rounded-lg border p-3 text-sm"><input className="mt-1" type="checkbox" aria-label={`Select ${item.employeeName} ${item.date}`} disabled={busy||!!item.blocked} checked={selected.has(key(item))} onChange={event=>setSelected(old=>{const next=new Set(old);event.target.checked?next.add(key(item)):next.delete(key(item));return next;})}/><span><b>{item.employeeName} · {item.date}</b><span className="block">Accept {item.breakMinutes} minutes recorded unpaid break</span>{item.blocked&&<span className="block text-red-700">{item.blocked}</span>}{item.remainingIssues.length>0&&<span className="block text-slate-500">{item.remainingIssues.length} other checks remain</span>}</span></label>)}</div>
   <Button disabled={busy||!chosen.length} onClick={()=>void submit()}>Accept {chosen.length} recorded breaks → send for approval</Button></>}
   {corrections.length>0&&<details><summary className="cursor-pointer text-sm">{corrections.length} dates need verified corrections</summary>{corrections.map(item=><p className="mt-2 text-sm" key={key(item)}>{item.employeeName} · {item.date}: {item.blocked}</p>)}</details>}
   {pending.length>0&&<p className="font-semibold">{pending.length} approval batches · {pending.reduce((n,r)=>n+r.items.length,0)} dates. One decision per batch, not per date.</p>}
   {!items.length&&!pending.length&&<p>No recorded breaks need this decision.</p>}
   {pending.map(review=><BreakDecisionCard key={review.id} review={review} busy={busy} note={notes[review.id]||''} setNote={note=>setNotes(old=>({...old,[review.id]:note}))} onDecision={action=>decide(review,action)}/>)}
   <details><summary className="cursor-pointer text-sm">Decision history</summary>{data.reviews.filter(review=>!['pending_hr_manager','pending_bod'].includes(review.status)).map(review=><p key={review.id} className="mt-2 text-sm">{label(review.status)} · {review.items.length} dates · {review.bodName||review.submitter} · {review.bod_at||review.submitted_at}{review.note?` · ${review.note}`:''}{review.stale?' · Source changed; earlier acceptance is no longer applied.':''}</p>)}</details>
  </>}
 </section>;
}

export function BreakDecisionCard({review,busy,note,setNote,onDecision}:{review:Review;busy:boolean;note:string;setNote:(note:string)=>void;onDecision:(action:string)=>Promise<void>}){return <article key={review.id} className="space-y-3 rounded-xl border p-4"><h4 className="font-bold">1 attendance batch · {review.items.length} dates · {label(review.status)}</h4><p className="text-sm">Submitted by {review.submitter} · {new Date(review.submitted_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</p>{review.hrName&&<p className="text-sm">HR Manager: {review.hrName} · {review.hr_at}</p>}<details><summary className="cursor-pointer">View dates and recorded breaks (optional)</summary><ul>{review.items.map(item=><li key={key(item)}>{item.employeeName} · {item.date} · accept {item.breakMinutes} minutes unpaid break</li>)}</ul></details>
    {review.stale&&<p role="alert" className="text-red-700">Evidence changed. Return this batch and prepare it again.</p>}
    {review.canAct?<><label className="block text-sm">Approval comment (optional); reason required to return or reject<textarea className="mt-1 block w-full rounded-lg border bg-transparent p-2" value={note} onChange={event=>setNote(event.target.value)}/></label><div className="flex flex-wrap gap-2"><Button disabled={busy||review.stale} onClick={()=>void onDecision('approve')}>{review.status==='pending_hr_manager'?`Approve batch → send to BOD`:`Approve and apply batch`}</Button><Button variant="secondary" disabled={busy||!(note.trim().length>=3)} onClick={()=>void onDecision('return')}>Return for correction</Button><Button variant="secondary" disabled={busy||!(note.trim().length>=3)} onClick={()=>void onDecision('reject')}>Reject</Button></div></>:<p className="text-sm">Waiting for an independent reviewer. Submitters cannot approve their own batch.</p>}
   </article>;}
