import React,{useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import Modal from '../../components/ui/Modal';
import Button from '../../components/ui/Button';
import {EmployeePayslip,issueCategories,inputClass,payrollRpc,uploadIssueFile} from './selfService';
export default function ReportPayrollIssue({slip,onClose}:{slip:EmployeePayslip;onClose:()=>void}){
 const [category,setCategory]=useState(issueCategories[0]),[item,setItem]=useState('whole'),[date,setDate]=useState(''),[explanation,setExplanation]=useState(''),[expected,setExpected]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');const request=useRef(crypto.randomUUID());
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const id=await payrollRpc<string>('submit_payroll_issue',{p_slip:slip.id,p_category:category,p_item:item,p_date:date||null,p_explanation:explanation,p_expected:expected,p_request:request.current});setSaved(id);if(file){try{await uploadIssueFile(id,file);}catch(e){setError(`Your issue was submitted, but the attachment failed: ${(e as Error).message} Add it from My Payroll Issues.`);}}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal isOpen onClose={()=>{if(!busy)onClose();}} title="Report a payroll issue"><p className="mb-4 text-sm">{slip.from} – {slip.to} · payroll version {slip.version}</p>{error&&<p role="alert" className="mb-3 text-red-600 dark:text-red-300">{error}</p>}{saved?<div role="status"><p>Your concern has been submitted for HR review.</p><Link onClick={onClose} className="mt-4 inline-block text-indigo-600 dark:text-indigo-300" to={`/payroll/my-issues?issue=${saved}`}>View your payroll issue →</Link></div>:<form onSubmit={submit} className="space-y-4"><fieldset disabled={busy} className="space-y-4"><label className="block">Issue category<select className={inputClass} value={category} onChange={e=>setCategory(e.target.value)}>{issueCategories.map(c=><option key={c}>{c}</option>)}</select></label><label className="block">Affected payslip item<select className={inputClass} value={item} onChange={e=>setItem(e.target.value)}>{slip.items.map(i=><option key={i.key} value={i.key}>{i.label}</option>)}</select></label><label className="block">Affected date (optional)<input className={inputClass} type="date" min={slip.from} max={slip.to} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="block">Short explanation<textarea className={inputClass} required minLength={3} maxLength={2000} value={explanation} onChange={e=>setExplanation(e.target.value)}/></label><label className="block">Expected correction (optional)<textarea className={inputClass} maxLength={1000} value={expected} onChange={e=>setExpected(e.target.value)}/></label><label className="block">Supporting attachment (optional)<input className={inputClass} type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/><span className="text-sm">PDF, PNG or JPEG, up to 5 MB.</span></label><Button type="submit" className="min-h-12 w-full" disabled={busy}>{busy?'Submitting…':'Submit issue'}</Button></fieldset></form>}</Modal>
}
