import React, {useEffect, useState} from 'react';
import {supabase} from '../../services/supabaseClient';
type Employee={id:string;name:string;code:string;hireDate:string|null;endDate:string|null};
type Day={employeeId:string;date:string;lateMinutes:number;undertimeMinutes:number;actualMinutes:number;breakMinutes:number;approvedOtMinutes:number;issues:string[]};
type Line={date?:string;label:string;quantity:string;rate:string;factor:string;amount:string;packageSource?:string};
type Gross={employeeId:string;gross:string|null;lines:Line[];issues:string[]};
type Net={employeeId:string;gross:string;deductions:string;net:string;mandatory:string;tax:string;companyTopUp:string;other:string;payBasis:string;contributions:{label:string;amount:string}[]};
type Source={events:{employeeId:string;timestamp:string;type:string}[]};
type Demo={calculatedAt:string;assumptions:string[];assumptionChanges:{employeeId:string;reason:string}[];timeResult:{rows:Day[]};scenarioGross:{employees:Gross[]};comparisonGross:{employees:Gross[]};comparisonTime:{rows:Day[]};comparisonSource:Source;comparisonNet:{ready:boolean;gross:string;deductions:string;net:string;employees:Net[];issues:{employeeId:string;message:string}[]}};
type Package={employee_id:string;effective_from:string;base_amount:number;rate_type:string;status:string;source_ref:string;treatment:Record<string,unknown>;components:unknown[];isMock?:boolean};
type Run={label:string;status:string;canCalculateTest:boolean;snapshot:{employees:Employee[];packages:Package[];demo?:Demo;mockPackageAudit?:{employeeId:string;employeeName:string;createdAt:string;amount:number}[];blockers:{employeeId:string;reason:string}[];scenarios:{employeeId:string;date:string;scenario:string}[];timeResult:{rows:Day[]};source:Source}};
const money=(value:string|number|null|undefined)=>value==null?'Held for review':new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(value));
function CalculationLines({lines}:{lines:Line[]}){return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Date','Component','Quantity × rate × factor','Amount'].map(h=><th className="border-b p-2" key={h}>{h}</th>)}</tr></thead><tbody>{lines.map((l,i)=><tr key={i}><td className="border-b p-2">{l.date||'Cutoff'}</td><td className="border-b p-2">{l.label}</td><td className="border-b p-2">{Number(l.quantity).toFixed(4)} × {money(l.rate)} × {l.factor}</td><td className="border-b p-2">{money(l.amount)}</td></tr>)}</tbody></table></div>}
export default function ScenarioRun({scope,from,to}:{scope:string;from:string;to:string}){
 const [run,setRun]=useState<Run|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[view,setView]=useState<'comparison'|'scenarios'>('comparison');
 useEffect(()=>{let active=true;setError('');setLoading(true);
 Promise.resolve(supabase.rpc('get_payroll_scenario_run',{p_scope:scope,p_from:from,p_to:to})).then(({data,error})=>{if(!active)return;if(error)setError(error.message);else setRun(data as Run|null);setLoading(false);}).catch(e=>{if(active){setError(e.message||'Unable to load test run');setLoading(false);}});return()=>{active=false;};},[scope,from,to,revision]);
 const calculate=async()=>{setBusy(true);setActionError('');try{const {data,error}=await supabase.rpc('calculate_payroll_scenario_demo',{p_scope:scope,p_from:from,p_to:to});if(error)throw error;setRun(r=>r?{...r,snapshot:{...r.snapshot,demo:data as Demo}}:r);}catch(e){setActionError(e instanceof Error?e.message:(e as {message?:string}).message||'Calculation failed. Retry; saved inputs are retained.');}finally{setBusy(false);}};
 if(loading)return <p role="status">Loading saved test payroll…</p>;
 if(error)return <p role="alert">Test run could not be loaded: {error} <button className="underline" onClick={()=>setRevision(v=>v+1)}>Retry</button></p>;
 if(!run)return null;
 const s=run.snapshot,demo=s.demo,comparison=view==='comparison';
 return <section className="space-y-5 rounded-xl border-2 border-violet-500 bg-white p-5 dark:bg-slate-900" aria-label="Isolated payroll test run">
 <div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-bold">{run.label}</h2><strong>{demo?.comparisonNet.ready?'Calculated — test comparison only':'Ready for test calculation'}</strong></div>
 <p>August 11–25, 2026 · Pay date September 5, 2026 · Asia/Manila</p>
 <p className="font-semibold text-amber-800 dark:text-amber-200">MOCK CALCULATION — no live attendance, balances, approvals, notifications or payments are changed.</p>
 <p>{s.employees.length} employees · {s.packages.length} package snapshots · {s.scenarios.length} seeded daily scenarios.</p>
 <div className="flex flex-wrap gap-3"><button disabled={busy||!run.canCalculateTest} onClick={calculate} className="min-h-11 rounded-lg bg-violet-600 px-5 py-2 font-semibold text-white disabled:opacity-50">{busy?'Calculating…':demo?'Recalculate Test Payroll':'Calculate Test Payroll'}</button><button disabled={busy} className="min-h-11 rounded-lg border px-4 py-2" onClick={()=>setRevision(v=>v+1)}>Reload saved results</button></div>
 {!run.canCalculateTest&&<p>Your payroll role can inspect these results. Recalculation requires scoped preparation, HR rules or payroll administration access.</p>}
 {actionError&&<p role="alert" className="text-red-700">{actionError}</p>}
 {demo&&<><p className="text-sm">Saved {new Date(demo.calculatedAt).toLocaleString('en-PH',{timeZone:'Asia/Manila'})} PHT. Repeating unchanged inputs returns the same saved version.</p>
 <details className="rounded-lg border border-amber-300 p-3"><summary className="cursor-pointer font-semibold">Mock calculation settings and assumptions</summary><ul className="mt-3 list-disc space-y-2 pl-5">{demo.assumptions.map(x=><li key={x}>{x}</li>)}</ul></details>
 <div className="flex flex-wrap gap-3" aria-label="Result view">{(['comparison','scenarios'] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)} className={`min-h-11 rounded-lg border px-4 ${view===v?'bg-violet-600 text-white':''}`}>{v==='comparison'?'1. Complete-attendance example':'2. Attendance scenarios & exceptions'}</button>)}</div>
 <p>{comparison?'This separate mock comparison assumes complete attendance, Sundays off and no leave or overtime. Open an employee to trace gross pay, contributions, tax and net pay.':'These are the original seeded scenarios. Valid days show component adjustments. Unresolved days hold the employee’s cutoff total; partial lines are not a payable total.'}</p>
 {comparison&&demo.comparisonNet.ready&&<div className="grid gap-4 sm:grid-cols-3">{[['Mock gross pay',demo.comparisonNet.gross],['Mock deductions',demo.comparisonNet.deductions],['Mock net pay',demo.comparisonNet.net]].map(([label,value])=><div className="rounded-lg bg-violet-50 p-4 text-violet-950" key={label}><p>{label}</p><strong className="text-2xl">{money(value)}</strong></div>)}</div>}
 {!!demo.comparisonNet.issues.length&&comparison&&<p role="alert">Some comparison calculations need review. See the affected employee’s details below.</p>}
 </>}
 {s.employees.map(e=>{const p=s.packages.find(p=>p.employee_id===e.id);const rows=(demo?(comparison?demo.comparisonTime:demo.timeResult):s.timeResult).rows.filter(r=>r.employeeId===e.id);const gross=(comparison?demo?.comparisonGross:demo?.scenarioGross)?.employees.find(x=>x.employeeId===e.id);const net=comparison?demo?.comparisonNet.employees.find(x=>x.employeeId===e.id):undefined;const punches=(comparison&&demo?demo.comparisonSource:s.source).events.filter(x=>x.employeeId===e.id);return <details key={`${e.id}:${view}`} className="rounded-lg border p-4">
 <summary className="cursor-pointer font-semibold">{e.name} · {e.code||'Code missing in live profile'} · {p?.isMock?'Mock package':'Source package'}{demo?` · ${comparison?`Mock net: ${money(net?.net)}`:`Scenario gross: ${money(gross?.gross)}`}`:''}</summary>
 <p className="mt-3">{p?`${money(p.base_amount)} / ${p.rate_type} · effective ${p.effective_from} · ${p.isMock?'Mock only':p.status}`:'No package'}</p>
 <p>Arrangement: {p?.treatment.payBasis==='net_tax'?'Net of tax only; employee contributions still deducted':'Gross salary'}.</p>
 {comparison&&demo?.assumptionChanges.filter(a=>a.employeeId===e.id).map(a=><p className="mt-2 text-amber-700" key={a.reason}>{a.reason}</p>)}
 {net&&<div className="my-4 grid gap-2 sm:grid-cols-2">{[['Gross including company top-up',net.gross],['Company tax top-up',net.companyTopUp],['Employee statutory contributions',net.mandatory],['Income tax withheld',net.tax],['Other deductions',net.other],['Take-home pay',net.net]].map(([label,val])=><p key={label}>{label}: <strong>{money(val)}</strong></p>)}</div>}
 {comparison&&demo?.comparisonNet.issues.filter(x=>x.employeeId===e.id).map(x=><p role="alert" key={x.message}>{x.message}</p>)}
 {!!gross?.issues.length&&<p className="my-3 text-amber-700">{gross.issues.join(' ')}</p>}
 {gross&&<details className="my-3"><summary className="cursor-pointer font-medium">Gross pay component calculations ({gross.lines.length} lines)</summary><CalculationLines lines={gross.lines}/></details>}
 {net&&<details className="my-3"><summary className="cursor-pointer font-medium">Contribution breakdown (EE = employee, ER = employer)</summary>{net.contributions.map(c=><p key={c.label}>{c.label}: {money(c.amount)}</p>)}</details>}
 <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Date / scenario','Actual minutes','Late minutes','Undertime minutes','Break minutes','Approved OT minutes','Review findings'].map(h=><th key={h} className="border-b p-2">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.date}><td className="border-b p-2">{r.date}<br/>{comparison&&demo?'Complete-attendance comparison':s.scenarios.find(x=>x.employeeId===e.id&&x.date===r.date)?.scenario}</td>{[r.actualMinutes,r.lateMinutes,r.undertimeMinutes,r.breakMinutes,r.approvedOtMinutes].map((v,i)=><td key={i} className="border-b p-2">{v??'—'}</td>)}<td className="border-b p-2">{r.issues.length?r.issues.join('; '):'Ready for test calculation'}</td></tr>)}</tbody></table></div>
 <details className="mt-3"><summary className="cursor-pointer">{comparison&&demo?'Comparison':'Seeded scenario'} punch evidence</summary><ul>{punches.map((x,i)=><li key={i}>{new Date(x.timestamp).toLocaleString('en-PH',{timeZone:'Asia/Manila'})} PHT · {x.type}</li>)}</ul></details>
 {p&&<details className="mt-3"><summary className="cursor-pointer">Original package snapshot and treatments</summary><pre className="overflow-auto whitespace-pre-wrap text-sm">{JSON.stringify({source:p.source_ref,treatment:p.treatment,components:p.components},null,2)}</pre></details>}
 </details>})}
 {!!s.mockPackageAudit?.length&&<details className="rounded-lg border p-3"><summary className="cursor-pointer font-semibold">Mock-package audit history</summary><ul>{s.mockPackageAudit.map(x=><li key={x.employeeId}>{x.employeeName}: {money(x.amount)}/month — {new Date(x.createdAt).toLocaleString('en-PH',{timeZone:'Asia/Manila'})} PHT.</li>)}</ul></details>}
 <details><summary className="cursor-pointer">Original data gaps for live payroll (do not block this mock comparison)</summary><ul className="list-disc pl-5">{s.blockers.map((b,i)=><li key={i}>{s.employees.find(e=>e.id===b.employeeId)?.name}: {b.reason}</li>)}</ul><p>The approved net-of-tax correction and mock packages are recorded separately. Original evidence is retained.</p></details>
 </section>;
}
