import React,{useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {supabase} from '../../services/supabaseClient';

type Employee={id:string;name:string;code:string;hireDate:string|null;endDate:string|null};
type Day={employeeId:string;date:string;ready?:boolean;scheduleState?:string;lateMinutes:number;undertimeMinutes:number;actualMinutes:number;breakMinutes:number;approvedOtMinutes:number;issues:string[]};
type Line={date?:string;label:string;quantity:string;rate:string;factor:string;amount:string};
type Gross={employeeId:string;gross:string|null;lines:Line[];issues:string[]};
type Net={employeeId:string;gross:string;deductions:string;net:string};
type Event={employeeId:string;timestamp:string;type:string};
type Shift={employeeId:string;date:string;kind:string;name?:string;start?:string;end?:string};
type Source={events:Event[];shifts:Shift[]};
type Demo={calculatedAt:string;assumptions:string[];timeResult:{rows:Day[]};scenarioGross:{employees:Gross[]};comparisonNet:{ready:boolean;gross:string;deductions:string;net:string;employees:Net[]};scenarioSource?:Source};
type Package={employee_id:string;effective_from:string;base_amount:number;rate_type:string;status:string;source_ref:string;treatment:Record<string,unknown>;components:unknown[];isMock?:boolean};
type FormValues={scheduleKind:string;scheduleStart:string;scheduleEnd:string;clockIn:string;breakStart:string;breakEnd:string;clockOut:string};
type Correction={employee_id:string;work_date:string;issue_type:string;original_value:FormValues;corrected_value:FormValues;reason:string;status:string;failure_message?:string;updated_at:string};
type Audit={employeeId:string;workDate:string;action:string;reason:string;createdAt:string};
type Snapshot={employees:Employee[];packages:Package[];demo?:Demo;blockers:{employeeId:string;reason:string}[];scenarios:{employeeId:string;date:string;scenario:string}[];timeResult:{rows:Day[]};source:Source};
type Run={label:string;status:string;date_from:string;date_to:string;pay_date:string;timezone:string;canCalculateTest:boolean;canApproveTestCorrections:boolean;corrections:Correction[];correctionAudit:Audit[];snapshot:Snapshot};
type Issue={employee:Employee;day:Day;label:string;action:'Fix attendance'|'Review schedule'|'Review overtime'|'Review pay package'|'Send for approval';severity:'attention'|'blocked'|'pending'};

const money=(value:string|number|null|undefined)=>value==null?'Held':new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(value));
const displayDate=(value:string,withYear=false)=>new Date(`${value}T00:00:00+08:00`).toLocaleDateString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',year:withYear?'numeric':undefined});
const time=(stamp?:string)=>stamp?new Date(stamp).toLocaleTimeString('en-PH',{timeZone:'Asia/Manila',hour:'numeric',minute:'2-digit'}):'—';
const emptyForm:FormValues={scheduleKind:'work',scheduleStart:'09:00',scheduleEnd:'18:00',clockIn:'',breakStart:'',breakEnd:'',clockOut:''};
const issueAction=(issues:string[]):Issue['action']=>{const text=issues.join(' ').toLowerCase();if(text.includes('schedule'))return'Review schedule';if(text.includes('ot ')||text.includes('overtime'))return'Review overtime';return'Fix attendance';};
const issueLabel=(issues:string[])=>{const text=issues.join(' ').toLowerCase();if(text.includes('clock-out')||text.includes('unpaired'))return'Missing punches';if(text.includes('lunch')||text.includes('break'))return'Missing or extended break';if(text.includes('schedule'))return'Missing schedule';if(text.includes('ot ')||text.includes('overtime'))return'OT approval incomplete';if(text.includes('employment start'))return'Employee profile information incomplete';if(text.includes('absence'))return'Attendance or absence needs review';return issues[0]||'Attendance needs review';};

function StatusPill({status}:{status:string}){const color=status==='Ready'||status==='Ready after correction'?'bg-emerald-100 text-emerald-800':status==='Blocked'||status==='Recalculation failed'?'bg-rose-100 text-rose-800':status==='Pending approval'?'bg-blue-100 text-blue-800':'bg-amber-100 text-amber-800';return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${color}`}>{status}</span>}

function CorrectionDrawer({open,scope,run,employee,day,values,issue,title,onClose,onSaved,onRecalculate}:{open:boolean;scope:string;run:Run;employee:Employee|null;day:Day|null;values:FormValues;issue:string;title:string;onClose:()=>void;onSaved:()=>void;onRecalculate:()=>Promise<void>}){
 const [form,setForm]=useState(values),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setForm(values);setReason('');setError('');},[values,employee?.id,day?.date,open]);
 if(!open||!employee||!day)return null;
 const save=async(mode:'save'|'recalculate'|'approval')=>{setError('');if(reason.trim().length<3){setError('Enter a correction reason.');return;}setBusy(true);try{const {error}=await supabase.rpc('save_test_payroll_correction',{p_scope:scope,p_from:run.date_from,p_to:run.date_to,p_employee:employee.id,p_date:day.date,p_issue:issue,p_values:form,p_reason:reason,p_submit_for_approval:mode==='approval'});if(error)throw error;onSaved();if(mode==='recalculate')await onRecalculate();if(mode!=='save')onClose();}catch(e){setError((e as {message?:string}).message||'The correction could not be saved.');}finally{setBusy(false);}};
 const set=(key:keyof FormValues,value:string)=>setForm(v=>({...v,[key]:value}));
 return <div className="fixed inset-0 z-[90] bg-slate-950/35" role="dialog" aria-modal="true" aria-label="Fix attendance"><aside className="ml-auto flex h-full w-full max-w-xl flex-col overflow-y-auto bg-white p-6 shadow-2xl dark:bg-slate-900">
  <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-violet-600">{run.label}</p><h2 className="mt-1 text-2xl font-black">{title}</h2><p className="mt-2 font-semibold">{employee.name} · {displayDate(day.date,true)}</p><p className="text-amber-700">{issue}</p></div><button className="min-h-11 px-3 text-2xl" onClick={onClose} aria-label="Close correction drawer">×</button></div>
  <div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Work date<input className="mt-1 w-full rounded-lg border bg-slate-100 px-3 py-2 font-normal" value={day.date} readOnly/></label><label className="text-sm font-bold">Schedule<select className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" value={form.scheduleKind} onChange={e=>set('scheduleKind',e.target.value)}><option value="work">Work day</option><option value="rest">Rest day</option></select></label>{form.scheduleKind==='work'&&<><label className="text-sm font-bold">Schedule start<input type="time" className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" value={form.scheduleStart} onChange={e=>set('scheduleStart',e.target.value)}/></label><label className="text-sm font-bold">Schedule end<input type="time" className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" value={form.scheduleEnd} onChange={e=>set('scheduleEnd',e.target.value)}/></label></>}{[['Clock in','clockIn'],['Break start','breakStart'],['Break end','breakEnd'],['Clock out','clockOut']].map(([label,key])=><label className="text-sm font-bold" key={key}>{label}<input type="time" className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" value={form[key as keyof FormValues]} onChange={e=>set(key as keyof FormValues,e.target.value)}/></label>)}</div>
  <label className="mt-5 text-sm font-bold">Correction reason<textarea className="mt-1 min-h-24 w-full rounded-lg border p-3 font-normal" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why is this attendance record being corrected?"/></label>
  <div className="mt-5 rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p><b>Attendance:</b> Needs attention → Ready after correction</p><p><b>Pay impact:</b> Recalculate after saving</p><p className="mt-3 text-sm font-semibold">This correction affects only this employee and this date.</p></div>
  {error&&<div className="mt-4 rounded-lg bg-rose-50 p-3 text-sm font-semibold text-rose-700" role="alert">{error}</div>}
  <div className="mt-auto flex flex-wrap justify-end gap-2 pt-6"><button disabled={busy} className="min-h-11 rounded-lg border px-4" onClick={onClose}>Cancel</button><button disabled={busy} className="min-h-11 rounded-lg border border-violet-300 px-4 font-bold text-violet-700" onClick={()=>void save('save')}>Save attendance correction</button><button disabled={busy} className="min-h-11 rounded-lg bg-violet-600 px-4 font-bold text-white" onClick={()=>void save('recalculate')}>{busy?'Saving…':'Save & recalculate'}</button><button disabled={busy} className="min-h-11 rounded-lg bg-slate-800 px-4 font-bold text-white" onClick={()=>void save('approval')}>Send to manager for approval</button></div>
 </aside></div>;
}

export default function ScenarioRun({scope,from,to}:{scope:string;from:string;to:string}){
 const navigate=useNavigate();
 const [run,setRun]=useState<Run|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[employeeId,setEmployeeId]=useState<string|null>(null),[focusDate,setFocusDate]=useState<string|null>(null),[drawer,setDrawer]=useState(false),[drawerTitle,setDrawerTitle]=useState('Fix attendance'),[showAll,setShowAll]=useState(false);
 useEffect(()=>{let active=true;setLoading(true);setError('');Promise.resolve(supabase.rpc('get_payroll_scenario_run',{p_scope:scope,p_from:from,p_to:to})).then(({data,error})=>{if(!active)return;if(error)setError(error.message);else setRun(data as Run|null);setLoading(false);}).catch(e=>{if(active){setError(e.message||'Unable to load test run');setLoading(false);}});return()=>{active=false};},[scope,from,to,revision]);
 const calculate=async()=>{if(!run)return;setBusy(true);setActionError('');try{const {error}=await supabase.rpc('calculate_payroll_scenario_demo',{p_scope:scope,p_from:from,p_to:to});if(error)throw error;setRevision(v=>v+1);}catch(e){const message=(e as {message?:string}).message||'Recalculation failed. Your saved corrections were kept.';setActionError(message);if(employeeId&&focusDate)await supabase.rpc('mark_test_payroll_recalculation_failed',{p_scope:scope,p_from:from,p_to:to,p_employee:employeeId,p_date:focusDate,p_message:message});setRevision(v=>v+1);}finally{setBusy(false);}};
 const approve=async(c:Correction)=>{setBusy(true);setActionError('');try{const {error}=await supabase.rpc('approve_test_payroll_correction',{p_scope:scope,p_from:from,p_to:to,p_employee:c.employee_id,p_date:c.work_date,p_reason:'Approved for isolated test payroll'});if(error)throw error;await calculate();}catch(e){setActionError((e as {message?:string}).message||'Approval failed.');}finally{setBusy(false);}};
 const s=run?.snapshot,demo=s?.demo,source=demo?.scenarioSource||s?.source;
 const issues=useMemo<Issue[]>(()=>{if(!run||!s)return[];const rows=(demo?.timeResult||s.timeResult).rows;const found:Issue[]=[];for(const b of s.blockers){const employee=s.employees.find(e=>e.id===b.employeeId);if(employee)found.push({employee,day:{employeeId:employee.id,date:run.date_from,lateMinutes:0,undertimeMinutes:0,actualMinutes:0,breakMinutes:0,approvedOtMinutes:0,issues:[b.reason]},label:b.reason,action:'Review pay package',severity:'blocked'});}for(const day of rows.filter(r=>r.issues?.length)){const employee=s.employees.find(e=>e.id===day.employeeId);if(!employee)continue;const correction=run.corrections?.find(c=>c.employee_id===day.employeeId&&c.work_date===day.date);if(correction?.status==='Ready after correction')continue;found.push({employee,day,label:correction?.status==='Pending approval'?'Attendance correction awaiting approval':correction?.status==='Recalculation failed'?'Recalculation failed':issueLabel(day.issues),action:correction?.status==='Pending approval'?'Send for approval':issueAction(day.issues),severity:correction?.status==='Pending approval'?'pending':day.issues.some(x=>x.toLowerCase().includes('employment start'))?'blocked':'attention'});}return found.sort((a,b)=>({blocked:0,pending:1,attention:2}[a.severity]-{blocked:0,pending:1,attention:2}[b.severity])||a.day.date.localeCompare(b.day.date));},[run,s,demo]);
 if(loading)return <div className="rounded-xl border bg-white p-6" role="status">Loading test payroll…</div>;
 if(error)return <div className="rounded-xl border border-rose-300 bg-rose-50 p-5 text-rose-800" role="alert">Test payroll could not be loaded. {error} <button className="font-bold underline" onClick={()=>setRevision(v=>v+1)}>Retry</button></div>;
 if(!run||!s||!source)return null;
 const blockedEmployees=new Set(issues.filter(i=>i.severity==='blocked').map(i=>i.employee.id)),attentionEmployees=new Set(issues.filter(i=>i.severity!=='blocked').map(i=>i.employee.id)),ready=Math.max(0,s.employees.length-new Set([...blockedEmployees,...attentionEmployees]).size);const selected=s.employees.find(e=>e.id===employeeId)||null,selectedRows=(demo?.timeResult||s.timeResult).rows.filter(r=>r.employeeId===employeeId),selectedPackage=s.packages.find(p=>p.employee_id===employeeId),selectedGross=demo?.scenarioGross.employees.find(e=>e.employeeId===employeeId),selectedNet=demo?.comparisonNet.employees.find(e=>e.employeeId===employeeId),selectedStatus=selected?(blockedEmployees.has(selected.id)?'Blocked':attentionEmployees.has(selected.id)?'Needs attention':'Ready after correction'):'';
 const open=(item:Issue)=>{setEmployeeId(item.employee.id);setFocusDate(item.day.date);if(item.action==='Review pay package'){navigate(`/payroll/pay-packages?employee=${item.employee.id}`);return;}setDrawerTitle(item.action==='Review schedule'?'Review schedule':item.action==='Review overtime'?'Review overtime':'Fix attendance');setDrawer(true);};
 const currentDay=selectedRows.find(r=>r.date===focusDate)||null,existingCorrection=run.corrections?.find(c=>c.employee_id===employeeId&&c.work_date===focusDate),dayEvents=source.events.filter(e=>e.employeeId===employeeId&&e.timestamp.slice(0,10)===focusDate),dayShift=source.shifts.find(x=>x.employeeId===employeeId&&x.date===focusDate),drawerValues:FormValues=existingCorrection?.corrected_value||{...emptyForm,scheduleKind:dayShift?.kind||'work',scheduleStart:dayShift?.start||'09:00',scheduleEnd:dayShift?.end||'18:00',clockIn:dayEvents.find(x=>x.type==='CLOCK_IN')?.timestamp.slice(11,16)||'',breakStart:dayEvents.find(x=>x.type==='START_BREAK')?.timestamp.slice(11,16)||'',breakEnd:dayEvents.find(x=>x.type==='END_BREAK')?.timestamp.slice(11,16)||'',clockOut:dayEvents.find(x=>x.type==='CLOCK_OUT')?.timestamp.slice(11,16)||''};
 return <section className="space-y-6 rounded-2xl border bg-slate-50 p-4 sm:p-6 dark:bg-slate-950" aria-label="Isolated payroll test run">
  <header className="rounded-2xl bg-white p-5 shadow-sm dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-black">{run.label}</h2><span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-black text-violet-700">TEST RUN</span></div><div className="mt-3 flex flex-wrap gap-x-7 gap-y-2 text-sm"><span><b>Payroll period:</b> {displayDate(run.date_from,true)}–{displayDate(run.date_to,true)}</span><span><b>Pay date:</b> {displayDate(run.pay_date,true)}</span><span><b>Business unit:</b> Bakebe – SM Aura</span></div></div><button disabled={busy||!run.canCalculateTest} onClick={()=>void calculate()} className="min-h-11 rounded-xl bg-violet-600 px-5 font-bold text-white disabled:opacity-50">{busy?'Recalculating…':'Recalculate payroll'}</button></div>{actionError&&<div role="alert" className="mt-4 rounded-lg bg-rose-50 p-3 font-semibold text-rose-700">{actionError} <button className="underline" onClick={()=>void calculate()}>Retry</button></div>}</header>
  <div className="grid gap-4 sm:grid-cols-3">{[{label:'Employees',value:s.employees.length,tone:'slate'},{label:'Ready',value:ready,tone:'green'},{label:'Needs attention',value:attentionEmployees.size+blockedEmployees.size,tone:'amber'}].map(card=><div key={card.label} className={`rounded-2xl border-l-4 bg-white p-5 shadow-sm ${card.tone==='green'?'border-emerald-500':card.tone==='amber'?'border-amber-500':'border-slate-400'}`}><p className="font-semibold text-slate-500">{card.label}</p><strong className="mt-1 block text-3xl">{card.value}</strong>{card.label==='Needs attention'&&<p className="mt-1 text-xs text-rose-600">{blockedEmployees.size} blocked</p>}</div>)}</div>
  <section className="rounded-2xl bg-white shadow-sm dark:bg-slate-900"><div className="flex items-center justify-between border-b p-5"><div><h3 className="text-xl font-black">Needs attention</h3><p className="text-sm text-slate-500">Resolve these items before payroll approval.</p></div><StatusPill status={issues.length?'Needs attention':'Ready'}/></div>{issues.length?<div className="divide-y">{issues.slice(0,showAll?undefined:10).map((item,index)=>{const correction=run.corrections?.find(c=>c.employee_id===item.employee.id&&c.work_date===item.day.date);return <div key={`${item.employee.id}:${item.day.date}:${index}`} className="grid gap-3 p-4 md:grid-cols-[1.2fr_.7fr_1.5fr_1fr_auto] md:items-center"><button className="text-left font-bold hover:text-violet-700" onClick={()=>{setEmployeeId(item.employee.id);setFocusDate(item.day.date)}}>{item.employee.name}</button><span>{displayDate(item.day.date)}</span><div><p className="font-semibold">{item.label}</p>{correction?.status==='Recalculation failed'&&<p className="text-xs text-rose-600">{correction.failure_message}</p>}</div><span className="text-sm text-slate-500">{item.action==='Fix attendance'?'Complete the missing time':item.action}</span>{correction?.status==='Pending approval'&&run.canApproveTestCorrections?<button disabled={busy} className="min-h-11 rounded-lg bg-violet-600 px-4 font-bold text-white" onClick={()=>void approve(correction)}>Approve correction</button>:<button className="min-h-11 rounded-lg bg-violet-600 px-4 font-bold text-white" onClick={()=>open(item)}>{correction?.status==='Recalculation failed'?'Retry correction':item.action}</button>}</div>})}</div>:<div className="p-8 text-center text-emerald-700"><b>All attendance items are ready.</b></div>}{issues.length>10&&<button className="m-4 font-bold text-violet-700 underline" onClick={()=>setShowAll(v=>!v)}>{showAll?'Show fewer issues':`Show all ${issues.length} issues`}</button>}</section>
  {selected&&<section className="rounded-2xl bg-white p-5 shadow-sm dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-4"><div><button className="mb-3 text-sm font-bold text-violet-700" onClick={()=>setEmployeeId(null)}>← Back to payroll overview</button><h3 className="text-2xl font-black">{selected.name}</h3><p className="text-slate-500">{selected.code||'Employee code unavailable'} · {selectedPackage?`${money(selectedPackage.base_amount)} / ${selectedPackage.rate_type}`:'No pay package'}</p></div><StatusPill status={selectedStatus}/></div>
   <ol className="my-6 grid gap-2 rounded-xl bg-slate-100 p-2 text-center text-sm font-bold sm:grid-cols-3 dark:bg-slate-800"><li className="rounded-lg bg-violet-600 p-3 text-white">1. Review attendance</li><li className={`rounded-lg p-3 ${selectedStatus==='Ready after correction'?'bg-violet-100 text-violet-700':''}`}>2. Review pay</li><li className="rounded-lg p-3">3. Ready for approval</li></ol>
   <div className="grid gap-3 sm:grid-cols-3">{[['Gross pay',selectedGross?.gross],['Total deductions',selectedGross?.gross?selectedNet?.deductions:null],['Net pay',selectedGross?.gross&&selectedNet?Number(selectedGross.gross)-Number(selectedNet.deductions):null]].map(([label,value])=><div className="rounded-xl border p-4" key={label as string}><p className="text-sm text-slate-500">{label}</p><b className="text-xl">{money(value as string|number|null)}</b></div>)}</div>
   <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr>{['Date','Schedule','Clock in','Break','Clock out','Result','Action'].map(h=><th className="border-b p-3" key={h}>{h}</th>)}</tr></thead><tbody>{selectedRows.map(row=>{const ev=source.events.filter(e=>e.employeeId===selected.id&&e.timestamp.slice(0,10)===row.date),sh=source.shifts.find(x=>x.employeeId===selected.id&&x.date===row.date),correction=run.corrections?.find(c=>c.employee_id===selected.id&&c.work_date===row.date),result=correction?.status||(!row.issues.length?'Ready':row.lateMinutes?`${time(ev.find(x=>x.type==='CLOCK_IN')?.timestamp)} · ${row.lateMinutes} minute${row.lateMinutes===1?'':'s'} late`:issueLabel(row.issues)),action=issueAction(row.issues);return <tr key={row.date} className={focusDate===row.date?'bg-violet-50':''}><td className="border-b p-3">{displayDate(row.date)}</td><td className="border-b p-3">{sh?sh.kind==='rest'?'Rest day':`${sh.start}–${sh.end}`:'Missing schedule'}</td><td className="border-b p-3">{time(ev.find(x=>x.type==='CLOCK_IN')?.timestamp)}</td><td className="border-b p-3">{time(ev.find(x=>x.type==='START_BREAK')?.timestamp)}–{time(ev.find(x=>x.type==='END_BREAK')?.timestamp)}</td><td className="border-b p-3">{time(ev.find(x=>x.type==='CLOCK_OUT')?.timestamp)}</td><td className="border-b p-3"><StatusPill status={result}/></td><td className="border-b p-3">{row.issues.length&&correction?.status!=='Ready after correction'?<button className="min-h-11 font-bold text-violet-700 underline" onClick={()=>open({employee:selected,day:row,label:issueLabel(row.issues),action,severity:'attention'})}>{action}</button>:<span className="text-emerald-700">No action</span>}</td></tr>})}</tbody></table></div>
  </section>}
  <details className="rounded-2xl bg-white p-5 shadow-sm dark:bg-slate-900"><summary className="cursor-pointer font-bold">View audit details</summary><div className="mt-4 space-y-4 text-sm"><p>Test-only package snapshots: {s.packages.length} · Seeded attendance scenarios: {s.scenarios.length} · Saved calculations: {demo?new Date(demo.calculatedAt).toLocaleString('en-PH',{timeZone:'Asia/Manila'}):'Not calculated'}</p>{demo&&<details><summary className="cursor-pointer font-semibold">Mock assumptions</summary><ul className="mt-2 list-disc pl-5">{demo.assumptions.map(x=><li key={x}>{x}</li>)}</ul></details>}<details><summary className="cursor-pointer font-semibold">Pay package snapshots</summary><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap">{JSON.stringify(s.packages,null,2)}</pre></details><details><summary className="cursor-pointer font-semibold">Correction audit history</summary>{run.correctionAudit?.length?<ul className="mt-2 space-y-2">{run.correctionAudit.map((a,i)=><li key={i}>{displayDate(a.workDate,true)} · {s.employees.find(e=>e.id===a.employeeId)?.name} · {a.action} · {a.reason} · {new Date(a.createdAt).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</li>)}</ul>:<p className="mt-2">No corrections saved yet.</p>}</details></div></details>
  <CorrectionDrawer open={drawer} scope={scope} run={run} employee={selected} day={currentDay} values={drawerValues} issue={currentDay?issueLabel(currentDay.issues):'Attendance issue'} title={drawerTitle} onClose={()=>setDrawer(false)} onSaved={()=>setRevision(v=>v+1)} onRecalculate={calculate}/>
 </section>;
}
