import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import Card from '../../components/ui/Card';
import {getDebtContext,type PayrollDebt} from './debts';
import {getNteDeductions,type NTEDeduction} from './nteDeductions';
import {getServiceCharge,peso,type ServiceChargeContext} from './serviceCharge';

type Employee={employeeId:string;employeeName:string;gross:string;deductions:string;net:string};
export default function ServiceChargeApprovalPanel({scopeId,from,to,payrollDate,employees}:{scopeId:string;from:string;to:string;payrollDate:string;employees:Employee[]}){
 const [data,setData]=useState<ServiceChargeContext|null>(null);const [debts,setDebts]=useState<PayrollDebt[]>([]);const [ntes,setNtes]=useState<NTEDeduction[]>([]);const [error,setError]=useState('');
 useEffect(()=>{let active=true;setError('');void Promise.all([getServiceCharge(scopeId,from,to,payrollDate),getDebtContext(scopeId,payrollDate),getNteDeductions(scopeId,payrollDate)]).then(([service,debt,nte])=>{if(active){setData(service);setDebts(debt.debts);setNtes(nte.items);}}).catch(e=>active&&setError((e as Error).message));return()=>{active=false;};},[scopeId,from,to,payrollDate]);
 const setup=data?.setup;const selected=setup?.allocations.filter(a=>a.selected)||[];const needingReview=setup?.allocations.filter(a=>['Not configured','Needs review'].includes(a.eligibilityStatus)).length||0;
 const buCount=useMemo(()=>new Set(selected.map(a=>a.businessUnitId).filter(Boolean)).size,[selected]);
 return <Card title="Service charge allocation" actions={<Link className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white" to="/payroll/service-charge">Review service-charge selection</Link>}>
  {error?<p role="alert" className="text-red-700">{error}</p>:!data?<p role="status">Loading service-charge review…</p>:!data.configured?<div className="rounded-xl bg-amber-50 p-4 text-amber-900"><strong>Not configured for this payroll.</strong><p>Service charge will not be inferred from prior payouts, job titles, salaries, allowances, or historical payroll.</p></div>:setup&&<><div className="grid gap-3 sm:grid-cols-5">{[['Service-charge pool',peso(setup.pool_amount)],['Employee allocation',peso(setup.allocatedAmount)],['Selected employees',selected.length],['Eligible business units',buCount],['Needs review',needingReview]].map(([label,value])=><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900" key={String(label)}><p className="text-xs text-slate-500">{label}</p><strong>{value}</strong></div>)}</div>
   {setup.status!=='Included in payroll snapshot'&&setup.status!=='Released'?<p className="mt-4 rounded-xl bg-red-50 p-3 font-semibold text-red-800">Blocked: confirm the individual selection and 100% allocation before this variable-pay line can enter payroll.</p>:<p className="mt-4 rounded-xl bg-emerald-50 p-3 font-semibold text-emerald-800">100% distributed · snapshot {setup.snapshot_id} · service charge remains separate from salary, commission and deductions.</p>}
   <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead><tr>{['Employee','Business unit','Classification','Gross pay','Service charge','Loan / debt','NTE deduction','Net pay','Status','Review'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{setup.allocations.map(a=>{const employee=employees.find(e=>e.employeeId===a.employeeId);const debt=debts.find(d=>d.employee_id===a.employeeId&&d.status==='Active');const debtRow=debt?.schedule.find(row=>row.payroll_date===payrollDate&&row.status==='Scheduled');const nte=ntes.find(n=>n.employeeId===a.employeeId&&n.workflowStatus==='Approved for Payroll');const nteRow=nte?.schedule?.find(row=>row.payroll_date===payrollDate&&row.status==='Scheduled');return <tr className="border-t" key={a.id}><td className="p-2 font-semibold">{a.employeeName}</td><td className="p-2">{a.businessUnit}</td><td className="p-2">{a.classification}</td><td className="p-2">{employee?peso(employee.gross):'—'}</td><td className="p-2 font-semibold">{a.selected?peso(a.amount):'—'}</td><td className="p-2">{debt&&debtRow?peso(Math.min(Number(debt.current_balance),Number(debtRow.scheduled_amount))):'—'}</td><td className="p-2">{nte&&nteRow?peso(Math.min(Number(nte.currentBalance),Number(nteRow.scheduled_amount))):'—'}</td><td className="p-2">{employee?peso(employee.net):'—'}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${a.selected?'bg-emerald-100 text-emerald-800':a.eligibilityStatus==='Not configured'?'bg-red-100 text-red-800':'bg-amber-100 text-amber-900'}`}>{a.inclusionStatus}</span></td><td className="p-2"><Link className="font-semibold text-violet-700 underline" to="/payroll/service-charge">Review</Link></td></tr>;})}</tbody></table></div>
  </>}
 </Card>;
}
