import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import {usePayrollField} from './usePayrollSelection';
import {validCutoff} from './workspace';
import {getServiceCharge,includeServiceCharge,initializeServiceCharge,peso,previewServiceCharge,reviseServiceCharge,saveServiceCharge,type ServiceChargeAllocation,type ServiceChargeContext,type ServiceChargeSetup} from './serviceCharge';
import PayrollCycleSelector from './PayrollCycleSelector';

const input='mt-1 block min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-900';
const statusTone=(status:string)=>status==='Eligible'||status.includes('Included')||status==='Released'?'bg-emerald-100 text-emerald-800':status==='Not configured'||status==='Needs review'?'bg-red-100 text-red-800':'bg-amber-100 text-amber-900';
const tomorrowAfter=(date:string)=>{if(!date)return '';const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+11);return d.toISOString().slice(0,10);};

function AllocationTable({setup,setSetup,disabled}:{setup:ServiceChargeSetup;setSetup:(s:ServiceChargeSetup)=>void;disabled:boolean}){
 const [search,setSearch]=useState('');const [classification,setClassification]=useState('All');
 const shown=useMemo(()=>setup.allocations.filter(a=>(classification==='All'||a.classification===classification)&&`${a.employeeName} ${a.employeeCode||''}`.toLowerCase().includes(search.toLowerCase())),[setup.allocations,search,classification]);
 const classifications=Array.from(new Set(setup.allocations.map(a=>a.classification)));
 const change=(id:string,patch:Partial<ServiceChargeAllocation>)=>setSetup({...setup,allocations:setup.allocations.map(a=>a.id===id?{...a,...patch}:a)});
 const selectAll=(selected:boolean)=>setSetup({...setup,allocations:setup.allocations.map(a=>shown.some(row=>row.id===a.id)&&a.eligibilityStatus!=='Not configured'?{...a,selected,amount:selected?a.amount:'0',reason:selected?a.reason:(a.reason||'Excluded from this payroll')} : a)});
 return <Card title="Individual employee selection" actions={<span className="text-sm font-semibold">{setup.allocations.filter(a=>a.selected).length} selected · {setup.allocations.filter(a=>!a.selected).length} excluded</span>}>
  <div className="grid gap-3 md:grid-cols-[1fr_240px_auto_auto]"><label>Search employee or ID<input className={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or employee code"/></label><label>Classification<select className={input} value={classification} onChange={e=>setClassification(e.target.value)}><option>All</option>{classifications.map(v=><option key={v}>{v}</option>)}</select></label><Button className="self-end" variant="secondary" disabled={disabled} onClick={()=>selectAll(true)}>Select filtered</Button><Button className="self-end" variant="secondary" disabled={disabled} onClick={()=>selectAll(false)}>Deselect filtered</Button></div>
  <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead><tr>{['Select','Employee','Business unit','Classification','Eligibility','Service charge','Decision','Reason / approved override'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{shown.map(a=><tr className="border-t" key={a.id}><td className="p-2"><input aria-label={`Select ${a.employeeName}`} className="h-5 w-5 accent-violet-600" type="checkbox" checked={a.selected} disabled={disabled||a.eligibilityStatus==='Not configured'} onChange={e=>change(a.id,{selected:e.target.checked,amount:e.target.checked?a.amount:'0'})}/></td><td className="p-2 font-semibold">{a.employeeName}<span className="block text-xs font-normal text-slate-500">{a.employeeCode||'No employee ID'}</span></td><td className="p-2">{a.businessUnit}</td><td className="p-2">{a.classification}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${statusTone(a.eligibilityStatus)}`}>{a.eligibilityStatus}{a.overrideApplied?' · override':''}</span></td><td className="p-2"><input aria-label={`Allocation for ${a.employeeName}`} className="w-32 rounded border p-2" type="number" min="0" step="0.01" disabled={disabled||!a.selected} value={a.amount} onChange={e=>change(a.id,{amount:e.target.value})}/></td><td className="p-2">{a.selected?'Selected for this payroll':'Excluded from this payroll'}</td><td className="p-2"><input aria-label={`Reason for ${a.employeeName}`} className="min-w-60 rounded border p-2" disabled={disabled} value={a.reason||''} onChange={e=>change(a.id,{reason:e.target.value})} placeholder={a.classification!=='Rank and file'&&a.selected?'Required approved override reason':!a.selected&&a.eligibilityStatus==='Eligible'?'Required exclusion reason':'Optional note'}/></td></tr>)}</tbody></table>{shown.length===0&&<p className="p-4">No employees match these filters.</p>}</div>
 </Card>;
}

export default function ServiceChargeSetupPage(){
 const [scope]=usePayrollField('scope'),[from]=usePayrollField('from'),[to]=usePayrollField('to');const [payDate,setPayDate]=useState('');const [data,setData]=useState<ServiceChargeContext|null>(null);const [draft,setDraft]=useState<ServiceChargeSetup|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [searchKey,setSearchKey]=useState(0);const [revisionReason,setRevisionReason]=useState('');
 useEffect(()=>{setPayDate(tomorrowAfter(to));},[to]);
 useEffect(()=>{let active=true;if(!scope||!validCutoff(from,to)){setData(null);setDraft(null);return;}setError('');void getServiceCharge(scope,from,to).then(value=>{if(active){setData(value);setDraft(value.setup?structuredClone(value.setup):null);if(value.setup?.pay_date)setPayDate(value.setup.pay_date);}}).catch(e=>active&&setError((e as Error).message));return()=>{active=false;};},[scope,from,to,searchKey]);
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();setSearchKey(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 if(!scope||!validCutoff(from,to))return <Card title="Service Charge Setup"><p>Select a business unit and payroll cutoff in <Link className="text-violet-700 underline" to="/payroll/home">Payroll Home</Link>.</p></Card>;
 const frozen=!!draft&&!['Draft','Needs review'].includes(draft.status);const allocated=Number(draft?.allocatedAmount||0),pool=Number(draft?.pool_amount||0),difference=pool-allocated;
 return <div className="space-y-6"><header><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold">Service charge setup</h1>{draft&&<span className={`rounded-full px-3 py-1 text-sm font-semibold ${statusTone(draft.status)}`}>{draft.status}</span>}</div><p className="mt-1 text-slate-600">Configure eligibility before finalizing payroll · {from}–{to}</p></header><PayrollCycleSelector compact/>
  <div className="rounded-xl border border-sky-200 bg-sky-50 p-4 text-sky-900">Service charge is variable pay. Only configured business units and the confirmed employee selection are included.</div>
  {error&&<div role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 text-red-800"><strong>Action blocked</strong><p>{error}</p></div>}
  {!data?<p role="status">Loading service-charge setup…</p>:!data.configured?<Card title="Start this payroll selection"><p className="mb-4">Rank-and-file employees will appear selected by default, but nothing enters payroll until you review every employee, allocate the approved pool, preview it, and freeze the snapshot.</p><label className="block max-w-xs">Pay date<input className={input} type="date" min={to} value={payDate} onChange={e=>setPayDate(e.target.value)}/></label><Button className="mt-4" size="lg" disabled={busy||!data.canManage||!payDate} onClick={()=>act(()=>initializeServiceCharge(scope,from,to,payDate))}>Start service-charge setup</Button></Card>:draft&&<>
   <section className="grid gap-4 md:grid-cols-4">{[['Approved pool',peso(draft.pool_amount)],['Selected employees',draft.selectedCount],['Excluded employees',draft.excludedCount],['Unallocated',peso(difference)]].map(([label,value])=><div className="rounded-2xl bg-white p-5 shadow" key={String(label)}><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-2xl">{value}</strong></div>)}</section>
   <Card title="Business unit, policy and payroll period"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label>Payroll period<input className={input} value={`${draft.period_from} – ${draft.period_to}`} disabled/></label><label>Pay date<input className={input} value={draft.pay_date} disabled/></label><label>Effective date<input className={input} type="date" disabled={frozen} value={draft.effective_date} onChange={e=>setDraft({...draft,effective_date:e.target.value})}/></label><label>Service-charge pool<input className={input} type="number" min="0" step="0.01" disabled={frozen} value={draft.pool_amount} onChange={e=>setDraft({...draft,pool_amount:e.target.value})}/></label><label>Default classification<input className={input} value="Rank and file" disabled/></label><label>Approved allocation rule<input className={input} disabled={frozen} value={draft.approved_rule_name||''} onChange={e=>setDraft({...draft,approved_rule_name:e.target.value})} placeholder="Approved policy name"/></label><label>Rule reference<input className={input} disabled={frozen} value={draft.approved_rule_reference||''} onChange={e=>setDraft({...draft,approved_rule_reference:e.target.value})} placeholder="Required approval/reference"/></label><label>Rule version<input className={input} disabled={frozen} value={draft.approved_rule_version||''} onChange={e=>setDraft({...draft,approved_rule_version:e.target.value})}/></label><label>Allocation basis<input className={input} disabled={frozen} value={draft.allocation_basis||''} onChange={e=>setDraft({...draft,allocation_basis:e.target.value})} placeholder="Approved basis; no formula builder"/></label><label>Funding source<input className={input} disabled={frozen} value={draft.funding_source||''} onChange={e=>setDraft({...draft,funding_source:e.target.value})} placeholder="Required funding source"/></label><label className="md:col-span-2">Selection notes<input className={input} disabled={frozen} value={draft.selection_notes||''} onChange={e=>setDraft({...draft,selection_notes:e.target.value})}/></label></div><p className="mt-4 rounded-xl bg-violet-50 p-3 font-medium text-violet-900">Rank-and-file employees are selected by default. Review and confirm the individual employees included in this payroll.</p></Card>
   <AllocationTable setup={draft} setSetup={setDraft} disabled={frozen||!data.canManage}/>
   <Card title="Allocation preview"><div className="grid gap-3 md:grid-cols-4">{[['Total service-charge pool',peso(pool)],['Employee allocation',peso(allocated)],['Unallocated amount',peso(difference)],['Validation',Math.abs(difference)<0.005&&pool>0?'100% distributed':'Blocked']].map(([label,value])=><div className="rounded-xl bg-slate-50 p-4" key={String(label)}><p className="text-xs text-slate-500">{label}</p><strong className={label==='Validation'&&value==='Blocked'?'text-red-700':'text-slate-900'}>{value}</strong></div>)}</div>{Math.abs(difference)>=0.005&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-red-800">The allocation differs from the approved pool by {peso(difference)}. Correct the selection or amounts before previewing.</p>}<p className="mt-3 text-sm">Bank, processing, and administrative fees do not reduce the approved service-charge pool.</p></Card>
   <div className="sticky bottom-3 rounded-2xl border bg-white p-4 shadow-xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>1 Save selection → 2 Preview allocation → 3 Include in payroll snapshot</strong><p className="text-sm text-slate-500">Changing eligibility after snapshot creation requires a new review and makes downstream calculations stale.</p></div><div className="flex flex-wrap gap-2">{['Draft','Needs review'].includes(draft.status)&&<><Button variant="secondary" disabled={busy||!data.canManage} onClick={()=>act(()=>saveServiceCharge(draft))}>Save selection</Button><Button disabled={busy||!data.canManage||!draft.selection_confirmed||Math.abs(difference)>=0.005} onClick={()=>act(()=>previewServiceCharge(draft.id))}>Preview allocation</Button></>}{draft.status==='Previewed'&&<Button size="lg" disabled={busy||!data.canManage} onClick={()=>act(()=>includeServiceCharge(draft.id))}>Include in payroll snapshot</Button>}{draft.status==='Included in payroll snapshot'&&<div className="flex gap-2"><input className="rounded border p-2" value={revisionReason} onChange={e=>setRevisionReason(e.target.value)} placeholder="Reason for new review"/><Button variant="secondary" disabled={busy||revisionReason.trim().length<3} onClick={()=>act(()=>reviseServiceCharge(draft.id,revisionReason))}>Start new review</Button></div>}<Link className="inline-flex min-h-11 items-center rounded-lg border px-4" to="/payroll/approvals">Back to payroll approval</Link></div></div></div>
   {data.audit&&data.audit.length>0&&<details className="rounded-xl bg-white p-4 shadow"><summary className="cursor-pointer font-semibold">Audit history</summary><div className="mt-3 space-y-2">{data.audit.map((a,i)=><p className="rounded-lg bg-slate-50 p-3 text-sm" key={`${a.at}-${i}`}><strong>{a.action}</strong> · {a.actor} · {new Date(a.at).toLocaleString()}<br/>{a.reason}</p>)}</div></details>}
  </>}
 </div>;
}
