import {supabase} from '../../services/supabaseClient';
export type SpecialLine={sourceKey:string;label:string;kind:string;category:string;amount:string;settled:string;taxable:string;sourceRef:string;taxRef:string};
export type BasicPeriod={period:string;amount:string;sourceRef:string};
export type SpecialInputs={kind:string;caseRef:string;dateFrom:string;dateTo:string;payDate:string;sourceNetId:string;documentId:string;sourceRef:string;settlementRef:string;taxRef:string;eligibilityRef:string;offboardingRef:string;leaveRef:string;accountabilityRef:string;contributionRef:string;bonusSettled:string;benefitsUsed:string;taxMethod:string;priorTaxable:string;previousEmployerTaxable:string;priorWithheld:string;previousEmployerWithheld:string;taxableContributionAdjustment:string;reviewedTax:string;reviewedCoverage:boolean;lines:SpecialLine[];basicPeriods:BasicPeriod[]};
export type SpecialEmployee={id:string;name:string;businessUnit:string;endDate:string|null};
export type SpecialContext={canPrepare:boolean;canCalculate:boolean;canReview:boolean;endDate:string|null;runs:{id:string;kind:string;key:string;version:number;dateTo:string}[];netRuns:{id:string;from:string;to:string;version:number}[];documents:{id:string;title:string;status:string}[]};
export type SpecialRun={id:string;employee_id:string;kind:string;case_key:string;version:number;previous_id:string|null;created_by:string;current:boolean;staleReason:string|null;inputs:SpecialInputs;reason:string;review:null|{reference:string;at:string;by:string};result:{gross:string;deductions:string;net:string;employer:string;tax:string;taxableChange:string;annualBasic:string;thirteenthEntitlement:string;lines:(SpecialLine&{remaining:string})[];negativeBalance:boolean}};
async function rpc<T>(name:string,args:Record<string,unknown>={}):Promise<T>{const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message);return data as T;}
export const specialEmployees=()=>rpc<{employees:SpecialEmployee[]}>('get_payroll_special_context');
export const specialContext=(id:string)=>rpc<SpecialContext>('get_payroll_special_context',{p_employee_id:id});
export const getSpecialRun=(id:string)=>rpc<SpecialRun>('get_payroll_special_run',{p_run_id:id});
export const prepareSpecial=(employee:string,p:SpecialInputs,reason:string,expected:string|null)=>rpc<string>('prepare_payroll_special',{p_employee_id:employee,p_inputs:p,p_reason:reason,p_expected_id:expected});
export const reviewSpecial=(id:string,ref:string)=>rpc<string>('review_payroll_special',{p_run_id:id,p_source_ref:ref});
export const emptyLine=():SpecialLine=>({sourceKey:'',label:'',kind:'earning',category:'other',amount:'',settled:'',taxable:'',sourceRef:'',taxRef:''});
export const emptySpecial=():SpecialInputs=>({kind:'correction',caseRef:'',dateFrom:'',dateTo:'',payDate:'',sourceNetId:'',documentId:'',sourceRef:'',settlementRef:'',taxRef:'',eligibilityRef:'',offboardingRef:'',leaveRef:'',accountabilityRef:'',contributionRef:'',bonusSettled:'',benefitsUsed:'',taxMethod:'',priorTaxable:'',previousEmployerTaxable:'',priorWithheld:'',previousEmployerWithheld:'',taxableContributionAdjustment:'',reviewedTax:'',reviewedCoverage:false,lines:[],basicPeriods:[]});
