import React,{useEffect,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import {useAuth} from '../../hooks/useAuth';
import PhaseChecklist from './PhaseChecklist';
import {emptyLine,emptySpecial,specialEmployees,specialContext,getSpecialRun,prepareSpecial,reviewSpecial} from './specialPay';
import type {SpecialEmployee,SpecialContext,SpecialInputs,SpecialRun,SpecialLine} from './specialPay';
const input='mt-1 block w-full rounded border border-gray-300 p-2 dark:bg-slate-800 dark:border-slate-600';
const kinds={correction:'Past payroll correction',supplement:'Supplemental pay',thirteenth:'13th-month pay',final:'Final pay'};
const Field:React.FC<{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}>=({label,value,onChange,type='text',required=true})=>{return <label className="block text-sm">{label}<input className={input} type={type} value={value} onChange={e=>onChange(e.target.value)} required={required} maxLength={1000}/></label>;}
export default function SpecialPayPage(){
 const {user}=useAuth();const location=useLocation();const [employees,setEmployees]=useState<SpecialEmployee[]>([]);const [employee,setEmployee]=useState('');const [context,setContext]=useState<SpecialContext|null>(null);
 const [p,setP]=useState<SpecialInputs>(()=>({...emptySpecial(),kind:location.pathname.endsWith('/final-pay')?'final':'correction'}));const [reason,setReason]=useState('');const [run,setRun]=useState<SpecialRun|null>(null);const [expected,setExpected]=useState<string|null>(null);const [ref,setRef]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);setEmployees([]);setEmployee('');setContext(null);setRun(null);void specialEmployees().then(d=>{if(active)setEmployees(d.employees);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[user?.id]);
 useEffect(()=>{let active=true;setContext(null);setRun(null);setExpected(null);setReason('');setRef('');setError('');setP({...emptySpecial(),kind:location.pathname.endsWith('/final-pay')?'final':'correction'});if(!employee)return;setLoading(true);void specialContext(employee).then(d=>{if(active)setContext(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[employee,location.pathname]);
 const special=p.kind==='thirteenth'||p.kind==='final';
 const change=(key:keyof SpecialInputs,value:string)=>setP(old=>({...old,[key]:value,reviewedCoverage:false}));
 async function open(id:string){setBusy(true);setError('');try{const r=await getSpecialRun(id);setRun(r);setP({...r.inputs,reviewedCoverage:false});setExpected(r.id);setReason(r.reason);setRef('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function prepare(){setBusy(true);setError('');try{const id=await prepareSpecial(employee,p,reason,expected);setRun(await getSpecialRun(id));setExpected(id);setContext(await specialContext(employee));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function review(){if(!run)return;setBusy(true);setError('');try{await reviewSpecial(run.id,ref);setRun(await getSpecialRun(run.id));setRef('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function lineChange(i:number,key:keyof SpecialLine,value:string){setP(old=>({...old,reviewedCoverage:false,lines:old.lines.map((l,j)=>i===j?{...l,[key]:value}:l)}));}
 return <div className="space-y-6">
  <div><h1 className="text-3xl font-bold">Special Pay & Corrections</h1><p className="mt-2">Review remaining amounts, preserve original payroll and keep each revision linked to its source.</p></div>
  <PhaseChecklist/>
  <Card title="Choose an employee"><label>Employee<select className={input} value={employee} disabled={busy||loading} onChange={e=>setEmployee(e.target.value)}><option value="">Choose</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name} · {e.businessUnit}{e.endDate?` · ended ${e.endDate}`:''}</option>)}</select></label>
   {!loading&&employees.length===0&&<p className="mt-3">A scoped payroll duty and existing HRIS salary permission are required. <Link className="text-indigo-600" to="/payroll/access">Manage Payroll Access</Link>. The checklist remains available while assignments are pending.</p>}
   {context&&<><p className="mt-3">{context.canCalculate?'Shadow review enabled.':'Payroll processing is off. The access manager must enable shadow for the selected BU and parent scope before preparation.'}</p><p className="mt-2 text-sm">Recorded HRIS end date: {context.endDate||'Not recorded'}. <Link className="text-indigo-600" to={`/employees/view/${employee}`}>Open existing employee profile</Link> for offboarding and supporting documents.</p></>}
  </Card>
  {error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>}
  {context&&<Card title="Saved cases & prior versions"><div className="flex flex-wrap gap-2">{context.runs.map(r=><Button key={r.id} variant="secondary" disabled={busy} onClick={()=>void open(r.id)}>{kinds[r.kind as keyof typeof kinds]} · {r.dateTo} · v{r.version}</Button>)}{context.runs.length===0&&<p>No saved cases.</p>}</div><Button className="mt-3" variant="secondary" disabled={busy} onClick={()=>{setP(emptySpecial());setRun(null);setExpected(null);setReason('');setRef('');}}>Start another case</Button></Card>}
  {context?.canPrepare&&<form className="space-y-5" onSubmit={e=>{e.preventDefault();void prepare();}}><fieldset disabled={busy} className="space-y-5">
   <Card title={expected?'Revise the opened case':'Prepare a special-pay case'}><div className="grid gap-3 sm:grid-cols-2">
    <label>Case type<select className={input} value={p.kind} disabled={Boolean(expected)} onChange={e=>{change('kind',e.target.value);}}>{Object.entries(kinds).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
    <Field label="Stable case / correction reference" value={p.caseRef} onChange={v=>change('caseRef',v)}/>
    <Field label="Period from" type="date" value={p.dateFrom} onChange={v=>change('dateFrom',v)}/><Field label={p.kind==='final'?'Last day — must match HRIS':'Period through'} type="date" value={p.dateTo} onChange={v=>change('dateTo',v)}/><Field label="Reviewed payday" type="date" value={p.payDate} onChange={v=>change('payDate',v)}/>
    <label>Original payroll reference<select className={input} value={p.sourceNetId} onChange={e=>change('sourceNetId',e.target.value)}><option value="">Existing external payroll — cite its reference below</option>{context.netRuns.map(r=><option value={r.id} key={r.id}>{r.from}–{r.to} · v{r.version}</option>)}</select></label>
    <label>Supporting HRIS document (optional)<select className={input} value={p.documentId} onChange={e=>change('documentId',e.target.value)}><option value="">Use approved document reference below</option>{context.documents.map(d=><option key={d.id} value={d.id}>{d.title} · {d.status}</option>)}</select></label>
    <Field label="Approved salary / entitlement source" value={p.sourceRef} onChange={v=>change('sourceRef',v)}/><Field label="Earlier payments / recoveries reconciliation reference" value={p.settlementRef} onChange={v=>change('settlementRef',v)}/><Field label="Reason for this version" value={reason} onChange={setReason}/>
   </div><p className="mt-3 text-sm">Use the same case reference for revisions. Enter actual settled amounts from payment records; a shadow calculation does not mean an amount was paid. Original payroll and loan balances remain intact.</p></Card>
   <Card title="Earnings, deductions and employer costs"><p className="mb-3 text-sm">Each line: corrected total entitlement or liability − already settled = remaining amount. For a new supplement, explicitly enter zero settled. Use a stable source key such as the payroll reference plus its line number. Do not enter the automatically calculated 13th month or income tax here.</p>
    {p.lines.map((l,i)=><fieldset key={i} className="mb-4 rounded border p-3"><legend>Line {i+1}</legend><div className="grid gap-3 sm:grid-cols-3">
     <Field label="Unique source item key" value={l.sourceKey} onChange={v=>lineChange(i,'sourceKey',v)}/><Field label="Description" value={l.label} onChange={v=>lineChange(i,'label',v)}/>
     <label>Type<select className={input} value={l.kind} onChange={e=>lineChange(i,'kind',e.target.value)}><option value="earning">Earning</option><option value="deduction">Employee deduction</option><option value="employer">Employer cost</option></select></label>
     <label>Category<select className={input} value={l.category} onChange={e=>lineChange(i,'category',e.target.value)}>{['other','basic','leave','loan','accountability','mandatory'].map(c=><option key={c}>{c}</option>)}</select></label>
     <Field label="Corrected total (PHP)" value={l.amount} onChange={v=>lineChange(i,'amount',v)}/><Field label="Already settled (PHP)" value={l.settled} onChange={v=>lineChange(i,'settled',v)}/><Field label="Taxable remaining amount (signed; 0 for deductions)" value={l.taxable} onChange={v=>lineChange(i,'taxable',v)}/><Field label="Approval / settlement source" value={l.sourceRef} onChange={v=>lineChange(i,'sourceRef',v)}/><Field label="Exemption evidence (if any portion exempt)" value={l.taxRef} required={false} onChange={v=>lineChange(i,'taxRef',v)}/>
    </div><Button type="button" variant="secondary" className="mt-3" onClick={()=>setP(old=>({...old,reviewedCoverage:false,lines:old.lines.filter((_,j)=>i!==j)}))}>Remove line</Button></fieldset>)}
    <Button type="button" variant="secondary" disabled={p.lines.length>=100} onClick={()=>setP(old=>({...old,reviewedCoverage:false,lines:[...old.lines,emptyLine()]}))}>Add reviewed line</Button>
   </Card>
   {special&&<Card title="13th-month entitlement"><p className="mb-3 text-sm">Use actual basic salary earned in this calendar year, including reviewed corrections. The calculation divides the total by 12, then subtracts earlier 13th-month payments. Eligibility and more favorable company benefits require their approved source. Do not mix a monthly total with its cutoff totals.</p>
    {p.basicPeriods.map((b,i)=><div key={i} className="mb-3 grid gap-3 sm:grid-cols-4"><Field label="Period: 2026-MM or 2026-MM-1/2" value={b.period} onChange={v=>setP(old=>({...old,reviewedCoverage:false,basicPeriods:old.basicPeriods.map((x,j)=>i===j?{...x,period:v}:x)}))}/><Field label="Actual basic earned (PHP)" value={b.amount} onChange={v=>setP(old=>({...old,reviewedCoverage:false,basicPeriods:old.basicPeriods.map((x,j)=>i===j?{...x,amount:v}:x)}))}/><Field label="Payroll / basic earnings source" value={b.sourceRef} onChange={v=>setP(old=>({...old,reviewedCoverage:false,basicPeriods:old.basicPeriods.map((x,j)=>i===j?{...x,sourceRef:v}:x)}))}/><Button type="button" variant="secondary" onClick={()=>setP(old=>({...old,reviewedCoverage:false,basicPeriods:old.basicPeriods.filter((_,j)=>i!==j)}))}>Remove period</Button></div>)}
    <Button type="button" variant="secondary" onClick={()=>setP(old=>({...old,reviewedCoverage:false,basicPeriods:[...old.basicPeriods,{period:'',amount:'',sourceRef:''}]}))}>Add basic-earnings period</Button>
    <div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Eligibility / complete basic earnings approval" value={p.eligibilityRef} onChange={v=>change('eligibilityRef',v)}/><Field label="13th month already paid this year (PHP)" value={p.bonusSettled} onChange={v=>change('bonusSettled',v)}/><Field label="90,000 benefit exemption already used across employers (PHP)" value={p.benefitsUsed} onChange={v=>change('benefitsUsed',v)}/></div>
   </Card>}
   <Card title="Reviewed leave and accountabilities"><div className="grid gap-3 sm:grid-cols-2"><Field label="Leave conversion approval: balance, rate, policy (or confirmed none)" required={p.kind==='final'||p.lines.some(l=>l.category==='leave')} value={p.leaveRef} onChange={v=>change('leaveRef',v)}/><Field label="Accountabilities / loan reconciliation and deduction authority (or none)" required={p.kind==='final'||p.lines.some(l=>['loan','accountability'].includes(l.category))} value={p.accountabilityRef} onChange={v=>change('accountabilityRef',v)}/>{p.kind==='final'&&<Field label="Existing offboarding / clearance reference" value={p.offboardingRef} onChange={v=>change('offboardingRef',v)}/>}</div><p className="mt-3 text-sm">Use existing HRIS offboarding and document workflows. No assumed leave conversion rate, automatic clearance deduction or second offboarding record is created.</p></Card>
   <Card title="Tax reconciliation"><label>Method<select className={input} required value={p.taxMethod} onChange={e=>change('taxMethod',e.target.value)}><option value="">Choose reviewed method</option><option value="annual">Annualized — final pay or December year-end</option>{p.kind!=='final'&&<option value="reviewed_adjustment">Finance-calculated withholding adjustment</option>}</select></label>
    <div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Tax calculation / applicability and exemption evidence" value={p.taxRef} onChange={v=>change('taxRef',v)}/><Field label="Remaining deductible employee contributions (signed; explicit 0 if none)" value={p.taxableContributionAdjustment} onChange={v=>change('taxableContributionAdjustment',v)}/><Field label="Contribution reconciliation source (when nonzero)" required={false} value={p.contributionRef} onChange={v=>change('contributionRef',v)}/>
    {p.taxMethod==='annual'?<>{([['priorTaxable','Current employer taxable paid before this case'],['priorWithheld','Current employer tax already withheld, net of refunds'],['previousEmployerTaxable','Previous employer taxable income this year'],['previousEmployerWithheld','Previous employer tax withheld, net of refunds']] as const).map(([key,label])=><Field key={key} label={`${label} (PHP)`} value={p[key]} onChange={v=>change(key,v)}/>)}</>:<Field label="Reviewed tax adjustment (PHP; negative is a supported refund)" value={p.reviewedTax} onChange={v=>change('reviewedTax',v)}/>}
    </div><p className="mt-3 text-sm">Annualization uses actual taxable earnings and prior-employer values; it does not project remaining months. Enter previous amounts excluding this case’s remaining earnings and net of earlier refunds. Finance must confirm applicability; unsupported consultant, fringe-benefit or other tax cases stay with the existing reviewed process.</p></Card>
   <label className="flex gap-2 text-sm"><input type="checkbox" checked={p.reviewedCoverage} onChange={e=>setP(old=>({...old,reviewedCoverage:e.target.checked}))}/>I reconciled all relevant earnings, prior payments, benefit limits, tax coverage and authorized deductions. Every amount is source-backed, including explicit zero/none values.</label>
   <Button type="submit" disabled={busy||!context.canCalculate||!p.reviewedCoverage}>Prepare shadow version</Button>
  </fieldset></form>}
  {run&&<Card title={`Saved ${kinds[run.kind as keyof typeof kinds]} · version ${run.version}`}><p className={`mb-3 ${run.current?'text-green-700':'text-amber-800'}`}>{run.current?'Current inputs':'Inputs changed or a newer version exists — revise before review.'} {run.staleReason}</p><div className="grid gap-3 sm:grid-cols-4">{[['Remaining earnings',run.result.gross],['Employee deductions, including tax',run.result.deductions],['Remaining net',run.result.net],['Employer cost',run.result.employer]].map(([label,value])=><div key={label}><p className="text-sm">{label}</p><strong>PHP {value}</strong></div>)}</div><p className="mt-3">Tax adjustment: PHP {run.result.tax}. {Number(run.result.tax)<0?'Refund included in the remaining net.':''}</p><p className="mt-2 text-sm">Shadow review only. No payment, payslip release, loan posting or final payroll authorization has occurred.</p>{run.result.negativeBalance&&<p role="alert" className="mt-2 text-red-700">Negative balance: use the documented recovery process. Finance review is blocked.</p>}
   <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Line','Type','Corrected total','Settled','Remaining','Source'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{run.result.lines.map((l,i)=><tr key={i} className="border-t"><td className="p-2">{l.label}</td><td className="p-2">{l.kind}</td><td className="p-2">{l.amount}</td><td className="p-2">{l.settled}</td><td className="p-2">{l.remaining}</td><td className="p-2">{l.sourceRef}</td></tr>)}</tbody></table></div>
   {run.review?<p className="mt-4">Finance checked this exact version: {run.review.reference} · {new Date(run.review.at).toLocaleDateString('en-PH')}. {run.current?'':'That review does not carry to the changed version.'}</p>:<p className="mt-4">Waiting for an independent Finance review.</p>}
   {context?.canReview&&!run.review&&run.created_by!==user?.id&&run.current&&!run.result.negativeBalance&&<form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();void review();}}><Field label="Independent Finance comparison / approval reference" value={ref} onChange={setRef}/><Button disabled={busy||ref.trim().length<3}>Record Finance check of saved version</Button></form>}
  </Card>}
 </div>;
}
