import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import RecordedBreakApprovals from './RecordedBreakApprovals';
import Button from '../../components/ui/Button';
import type {ReviewTimeRow,TestTimeEvidence} from './attendanceReadiness';
import {correctionLink,employeeReviews,timeTotals} from './timeReviewModel';
import {groupEmployeeReadiness,ReadinessCategory,EmployeeReadinessCard,setupDependencies} from './readinessDashboardModel';
import {downloadHistoricalSource,historyDetail} from './historicalAttendance';

const link='text-indigo-700 underline dark:text-indigo-300';
const num=(value:number)=>value.toLocaleString('en-PH',{maximumFractionDigits:4});
const stamp=(value:string)=>new Date(value).toLocaleString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
export const TimekeepingEmployeeTable:React.FC<{rows:ReviewTimeRow[];test:TestTimeEvidence[];saved:boolean;canOpenOffset:boolean;busy:boolean;hasReason:boolean;onOpenOffset:(id:string)=>void;scopeId?:string;onApplied?:()=>void;scopeName?:string;from?:string;to?:string}>=({rows,test,saved,canOpenOffset,busy,hasReason,onOpenOffset,scopeId,onApplied,scopeName='Selected business unit',from='',to=''})=>{
 const [review,setReview]=useState<{key:string;issue:string|null}|null>(null);
 const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [expanded,setExpanded]=useState<string|null>(null);const totals=useMemo(()=>timeTotals(rows),[rows]);const cards=useMemo(()=>groupEmployeeReadiness(rows,scopeName,from,to),[rows,scopeName,from,to]);const historical=useMemo(()=>employeeReviews([],test),[test]);
 const shared=setupDependencies(rows).filter(item=>item.key==='payroll_setup:Attendance policy — Needs setup'||item.key==='payroll_setup:Government holiday calendar — Update needed');
 const sharedLabels=new Set(shared.map(item=>item.label));
 const filtered=cards.filter(card=>(!status||card.status===status)&&(!search||`${card.employeeName} ${card.employeeCode}`.toLowerCase().includes(search.trim().toLowerCase())));
 return <div className="space-y-4">
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[cards.length,'employees','👥'],[shared.length+cards.reduce((sum,card)=>sum+card.total-card.setup.filter(item=>sharedLabels.has(item.label)).length,0),'grouped tasks','▤'],[cards.reduce((sum,card)=>sum+card.counts.attendance,0),'attendance tasks','◷'],[shared.length+cards.reduce((sum,card)=>sum+card.setup.filter(item=>!sharedLabels.has(item.label)).length,0),'setup tasks','⚙']].map(([value,label,icon])=><div className="rounded-xl bg-violet-50 p-4 dark:bg-violet-950/20" key={String(label)}><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-white text-violet-700 dark:bg-slate-800">{icon}</span><div><strong className="text-2xl">{value}</strong><p className="text-sm text-slate-500">{label}</p></div></div></div>)}</div>
  {!!shared.length&&<section className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-950"><h3 className="font-bold">Shared setup · fix once for this business unit</h3>{shared.map(item=><div key={item.key} className="mt-3 text-sm"><Link className="font-semibold underline" to={item.path}>{item.label} →</Link><p>{item.dates.length} affected dates · One shared task; saved coverage applies across payroll runs</p></div>)}</section>}
  <div className="flex flex-wrap items-end gap-3"><label className="text-sm font-medium">Find employee<input className="mt-1 block min-h-11 rounded-xl border bg-transparent px-3" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or employee ID"/></label><label className="text-sm font-medium">Status<select className="mt-1 block min-h-11 rounded-xl border bg-transparent px-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>Ready</option><option>Needs attention</option><option>Blocking payroll</option></select></label><span className="pb-3 text-sm text-slate-500">{filtered.length} of {cards.length} employee cards</span></div>
  <p className="text-xs text-slate-500">{num(totals.scheduledMinutes/60)} scheduled hours · {num(totals.actualMinutes/60)} actual hours · {num(totals.approvedOtMinutes/60)} approved OT hours. Issues are grouped once per employee and business unit.</p>
  {filtered.map(card=>{const open=expanded===card.key;const tone=card.status==='Ready'?'bg-emerald-100 text-emerald-800':card.status==='Needs attention'?'bg-amber-100 text-amber-800':'bg-rose-100 text-rose-800';const categories:[ReadinessCategory,string,string][]=[['attendance','Attendance','◷'],['schedule','Schedule','▣'],['overtime','Overtime review','↗'],['payroll_setup','Payroll setup','⚙']];const grouped=new Map<string,{label:string;dates:string[];issue:typeof card.issues[number]}>();for(const issue of card.issues){const key=`${issue.category}:${issue.label}`,prior=grouped.get(key);if(prior){if(!prior.dates.includes(issue.date))prior.dates.push(issue.date);}else grouped.set(key,{label:issue.label,dates:[issue.date],issue});}return <article className="overflow-hidden rounded-2xl border bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900" key={card.key}>
   <button type="button" className="flex w-full items-center justify-between gap-4 p-5 text-left" onClick={()=>setExpanded(open?null:card.key)} aria-expanded={open}><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-full bg-violet-100 font-bold text-violet-800">{card.employeeName.split(/\s+/).map(part=>part[0]).slice(0,2).join('')}</span><div><h3 className="text-lg font-bold">{card.employeeName}</h3><p className="text-sm text-slate-500">{card.employeeCode} · {card.businessUnit}</p></div></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-sm font-semibold ${tone}`}>{card.total} {card.total===1?'issue':'issues'} · {card.status}</span><span>{open?'⌃':'⌄'}</span></div></button>
   {open&&<div className="border-t p-5 dark:border-slate-700"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{categories.map(([category,label,icon])=><div className={`rounded-xl p-3 ${card.counts[category]?'bg-amber-50 dark:bg-amber-950/20':'bg-slate-50 dark:bg-slate-800'}`} key={category}><span className="mr-2">{icon}</span><strong>{card.counts[category]}</strong><span className="ml-2 text-sm">{label}</span></div>)}</div>
    <div className="mt-4 divide-y rounded-xl border dark:divide-slate-700 dark:border-slate-700">{(['attendance','schedule','overtime','payroll_setup'] as ReadinessCategory[]).map(category=>{const setup=(category==='schedule'?card.setup.filter(item=>item.key.startsWith('schedule:')):category==='payroll_setup'?card.setup.filter(item=>!item.key.startsWith('schedule:')):[]).filter(item=>!sharedLabels.has(item.label));const issues=[...grouped.values()].filter(item=>item.issue.category===category);if(!setup.length&&!issues.length)return null;return <section className="p-4" key={category}><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="font-bold capitalize">{category.replace('_',' ')}</h4><p className="text-xs text-slate-500">{setup.length+issues.length} grouped {setup.length+issues.length===1?'dependency':'items'}</p></div>{category==='attendance'&&<Link className={link} to={`/payroll/import-attendance?employee=${card.employeeId}`}>Review attendance →</Link>}{category==='schedule'&&<Link className={link} to="/payroll/timekeeping">Review schedules →</Link>}{category==='payroll_setup'&&<Link className={link} to={`/payroll/pay-packages?employee=${card.employeeId}`}>Open employee setup →</Link>}</div>
     <div className="mt-3 flex flex-wrap gap-2">{setup.map(item=><Link key={item.key} to={item.path} className="rounded-full bg-rose-100 px-3 py-2 text-sm font-medium text-rose-800">● {taskCopy(item.label).title} · {item.dates.length} dates</Link>)}{issues.map(item=><button type="button" key={`${item.issue.label}:${item.dates.join()}`} onClick={()=>setReview({key:card.key,issue:item.label})} className="rounded-full bg-amber-100 px-3 py-2 text-left text-sm font-medium text-amber-900">● {taskCopy(item.label).title} · {item.dates.length} dates</button>)}</div>
     {setup.length>0&&<div className="mt-3 rounded-lg bg-violet-50 p-3 text-sm text-violet-950 dark:bg-violet-950/20 dark:text-violet-100"><strong>This is one setup dependency affecting multiple dates.</strong> Fix it once and the affected payroll dates will refresh automatically.</div>}</section>;})}</div>
    <div className="mt-4 flex flex-wrap gap-3"><Button onClick={()=>setReview({key:card.key,issue:null})}>Review all issues</Button>{card.total>0&&<Button variant="secondary" onClick={()=>setReview({key:card.key,issue:card.issues[0]?.label||card.setup[0]?.label||null})}>Fix next</Button>}</div>
    <details className="mt-5"><summary className="cursor-pointer font-semibold text-slate-600">View daily evidence and original source IDs</summary><div className="mt-4 space-y-4">{card.days.map(day=><DayDetail key={day.date} row={day} saved={saved} canOpenOffset={canOpenOffset} busy={busy} hasReason={hasReason} onOpenOffset={onOpenOffset}/>)}{historical.find(item=>item.id===card.employeeId)?.test.length?<HistoricalSources records={historical.find(item=>item.id===card.employeeId)!.test}/>:null}</div></details>
   </div>}
  </article>;})}
  {review&&cards.find(card=>card.key===review.key)&&<EmployeeIssueReview key={review.key} card={cards.find(card=>card.key===review.key)!} initialIssue={review.issue} scopeId={scopeId} onApplied={onApplied} saved={saved} onClose={()=>setReview(null)}/>}
  {!filtered.length&&<div className="rounded-xl border border-dashed p-8 text-center text-slate-500">{cards.length?'No employees match these filters.':'No employee records for this payroll cycle.'}</div>}
 </div>;
};

const duration=(minutes:number)=>{const n=Math.round(minutes);return `${Math.floor(n/60)}h${n%60?` ${n%60}m`:''}`;};
const workDate=(date:string)=>new Intl.DateTimeFormat('en-PH',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`));
function taskCopy(raw:string){
 if(/lunch|break/i.test(raw))return {title:'Review recorded breaks',detail:'Check the uploaded break times. If the employee worked during the break, the manager must approve that work separately.',owner:'HR · manager if worked-break approval is needed'};
 if(/worked and scheduled|scheduled.*reconcil/i.test(raw))return {title:'Check hours against the schedule',detail:'Recorded hours differ from scheduled hours. Check whether the attendance or schedule needs correction. Extra time is not automatically paid overtime.',owner:'HR / timekeeping reviewer'};
 if(/overtime|\bOT\b|outside.*schedule/i.test(raw))return {title:'Review overtime approval',detail:'Check the approved overtime request and hours. A later clock-out alone does not authorize overtime pay.',owner:'Overtime approver / HR'};
 if(/punch|clock/i.test(raw))return {title:'Complete missing attendance',detail:'Check the source file and correct only verified times. Do not fill in a guessed time.',owner:'HR'};
 if(/Attendance policy|time rules/i.test(raw))return {title:'Confirm attendance rules once',detail:'HR needs to confirm the applicable attendance rules for this business unit and cutoff. This is one setup task covering all listed dates.',owner:'Authorized HR'};
 if(/Holiday coverage|holiday calendar/i.test(raw))return {title:'Confirm the holiday calendar once',detail:'HR needs to confirm the approved holiday calendar for this cutoff. Do not enter a holiday rule for each employee.',owner:'Authorized HR'};
 if(/Published schedule|unpublished schedule/i.test(raw))return {title:'Check the published schedule',detail:'Check the employee and dates in Schedule Builder, then correct or publish the applicable schedule.',owner:'Scheduling manager'};
 return {title:raw,detail:'Review the affected dates and use the source action below to resolve this task.',owner:'Authorized reviewer'};
}
function EmployeeIssueReview({card,initialIssue,saved,onClose,scopeId,onApplied}:{scopeId?:string;onApplied?:()=>void;card:EmployeeReadinessCard;initialIssue:string|null;saved:boolean;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);
 const [selected,setSelected]=useState(initialIssue||'');
 const [date,setDate]=useState('');
 useEffect(()=>{const node=dialog.current;node?.showModal();return()=>{node?.close();};},[]);
 const groups=[...new Set([...card.issues.map(issue=>issue.label),...card.setup.map(issue=>issue.label)])];
 const issues=card.issues.filter(issue=>issue.label===selected);
 const setup=card.setup.find(issue=>issue.label===selected);
 const dates=[...new Set([...issues.map(issue=>issue.date),...(setup?.dates||[])])].sort();
 const activeDate=dates.includes(date)?date:dates[0];
 const day=card.days.find(day=>day.date===activeDate);
 const raw=issues.find(issue=>issue.date===activeDate)?.raw||selected;
 const copy=taskCopy(raw);
 const target=day?correctionLink(raw,day):null;
 const choose=(label:string)=>{setSelected(label);setDate('');};
 return <dialog ref={dialog} onCancel={onClose} onClick={event=>{if((event.target as HTMLElement).closest('a'))onClose();}} aria-labelledby="employee-issue-title" className="fixed inset-0 m-auto max-h-[90dvh] w-[min(860px,94vw)] overflow-auto rounded-2xl border bg-white p-5 text-slate-900 shadow-xl backdrop:bg-black/50 dark:bg-slate-900 dark:text-white">
  <div className="flex items-start justify-between gap-4"><div><h2 id="employee-issue-title" className="text-xl font-bold">Payroll tasks · {card.employeeName}</h2><p className="mt-1 text-sm text-slate-500">{card.businessUnit} · {card.from} – {card.to}</p></div><Button variant="secondary" onClick={onClose}>Close review</Button></div>
  {saved&&<p role="status" className="my-3">Saved version · read-only. Open current readiness to make corrections.</p>}
  {!selected?<><p className="my-4 font-semibold">{groups.length} tasks to resolve. Repeated dates are grouped together.</p><div className="space-y-3">{groups.map(label=>{const task=taskCopy(card.issues.find(issue=>issue.label===label)?.raw||label);const affected=new Set([...card.issues.filter(issue=>issue.label===label).map(issue=>issue.date),...(card.setup.find(issue=>issue.label===label)?.dates||[])]);return <section key={label} className="rounded-xl border p-4"><h3 className="font-bold">{task.title}</h3><p className="mt-1 text-sm">{task.detail}</p><p className="my-3 text-sm text-slate-500">{affected.size} affected dates · Who acts: {task.owner}</p><Button onClick={()=>choose(label)}>Review task</Button></section>;})}</div>{!groups.length&&<p>No outstanding tasks for this employee.</p>}</>:<>
   <Button variant="secondary" className="my-4" onClick={()=>choose('')}>← All tasks</Button>
   <section className="rounded-xl bg-violet-50 p-4 text-violet-950"><h3 className="text-lg font-bold">{copy.title}</h3><p className="mt-2">{copy.detail}</p><p className="mt-2 text-sm">Who acts: {copy.owner} · {dates.length} affected dates</p></section>
   {setup?<section className="my-4"><p className="mb-3">Complete this setup once for all {dates.length} dates.</p>{!saved&&<Link className="inline-flex min-h-11 items-center rounded-lg bg-violet-700 px-4 font-semibold text-white" to={setup.path}>{setup.action} →</Link>}<details className="mt-4"><summary className="cursor-pointer">Show affected dates</summary><p>{dates.map(workDate).join(' · ')}</p></details></section>:day&&<>
    <label className="my-4 block font-semibold">Date to review<select className="mt-1 block w-full rounded-lg border bg-white p-3 text-slate-900" value={activeDate} onChange={event=>setDate(event.target.value)}>{dates.map(value=><option key={value} value={value}>{workDate(value)}</option>)}</select></label>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Scheduled work',duration(day.scheduledMinutes)],['Recorded work',duration(day.actualMinutes)],['Recorded break',duration(day.breakMinutes)],['Approved OT',duration(day.approvedOtMinutes)]].map(([label,value])=><div key={label} className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><p className="text-xs text-slate-500">{label}</p><strong>{value}</strong></div>)}</div>
    <p className="my-3 text-sm text-slate-500">These are the current recorded totals. Corrections and pay approvals remain separate.</p>
    {!saved&&scopeId&&/lunch|break/i.test(raw)?<RecordedBreakApprovals scope={scopeId} from={card.from} to={card.to} employeeId={card.employeeId} onApplied={onApplied}/>:!saved&&target&&<Link className="inline-flex min-h-11 items-center rounded-lg bg-violet-700 px-4 font-semibold text-white" to={target.path}>{target.label} →</Link>}
    <details key={`${selected}:${activeDate}`} className="mt-5 rounded-xl border p-3"><summary className="cursor-pointer font-semibold">Show logs and technical details (optional)</summary><div className="mt-3"><DayDetail row={{...day,issues:day.issues.filter(issue=>issue===raw)}} saved={true} canOpenOffset={false} busy={false} hasReason={false} onOpenOffset={()=>{}}/></div></details>
   </>}
  </>}
 </dialog>;
}

const DayDetail:React.FC<{row:ReviewTimeRow;saved:boolean;canOpenOffset:boolean;busy:boolean;hasReason:boolean;onOpenOffset:(id:string)=>void}>=({row:r,saved,canOpenOffset,busy,hasReason,onOpenOffset})=>{
 const evidence=r.evidence;
 return <section className="rounded-lg border bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><h3 className="font-semibold">{r.date} · {r.restDay?'Rest day':r.approvedFullLeave?'Approved leave':'Workday'}{r.holiday?' · Holiday':''} · {r.ready?'Checks passed':'Needs review'}</h3>
  {r.officialBusiness&&<p>Official Business · {r.officialBusiness.reference} · {r.officialBusiness.status}</p>}
  <div className="mt-3 grid gap-4 lg:grid-cols-3">
   <div><h4 className="font-medium">Schedule · {evidence?.scheduleStatus||'evidence unavailable'}</h4><p>{num(r.scheduledMinutes)} scheduled minutes</p>{evidence?.shifts.map((s,i)=><p key={`${s.id}-${i}`} className="mt-1 text-xs">{s.name||s.kind||'Shift'} · {s.start||'—'}–{s.end||'—'}{s.endDayOffset?` (+${s.endDayOffset} day)`:''}<span className="block break-all">Publication {s.publicationId||'reference unavailable'}{s.publicationVersion?` · v${s.publicationVersion}`:''}</span></p>)}</div>
   <div><h4 className="font-medium">Attendance evidence</h4><p>{num(r.actualMinutes)} actual · {num(r.breakMinutes)} break minutes</p>{r.requiresClock===false&&<p className="text-xs">Approved schedule-based attendance exception; punches are not fabricated.</p>}{evidence?.punches.length?evidence.punches.map((p,i)=><p key={`${p.id}-${i}`} className="mt-1 text-xs">{p.type} · {stamp(p.timestamp)} PHT<span className="block break-all">{p.source||'Recorded'} · {p.id}{p.revision!=null?` · revision ${p.revision}`:''}</span></p>):<p className="text-xs">No punch evidence in this result. See attendance requirements and blockers.</p>}<p className="mt-2">Late {num(r.lateMinutes)} · Undertime {num(r.undertimeMinutes)}</p></div>
   <div><h4 className="font-medium">Leave and OT approval evidence</h4><p>Approved OT {num(r.approvedOtMinutes)} · Actual OT {num(r.actualOtMinutes)}</p>{evidence?.leave.map(l=><p key={l.id} className="mt-1 break-all text-xs">{l.type} · {l.status}{l.configurationRequired?' · approval setup incomplete':''} · {l.startDate}–{l.endDate} · {l.id}</p>)}{evidence?.ot.map(o=><p key={o.id} className="mt-1 break-all text-xs">{o.type} OT · {o.status}{o.configurationRequired?' · approval setup incomplete':''} · {o.start}–{o.end} · {o.approvedHours??'—'} approved hours · {o.id}{o.reviewRef?` · ${o.reviewRef}`:''}</p>)}{!r.leaveIds.length&&<p className="text-xs">No leave source requests.</p>}</div>
  </div>
  {r.issues.length>0&&<ul className="mt-4 space-y-2 border-t pt-3 dark:border-slate-700">{r.issues.map(issue=>{const target=correctionLink(issue,r);return <li key={issue}><span className="font-medium">{issue}</span>{!saved&&<span className="block text-xs"><Link className={link} to={target.path}>{target.label}</Link> · Responsible: {target.owner}</span>}</li>;})}</ul>}
  <details className="mt-3 text-xs"><summary>Original source IDs</summary><p className="break-all">Shifts: {r.shiftIds.join(', ')||'none'}<br/>Punches: {r.eventIds.join(', ')||'none'}<br/>Leave: {r.leaveIds.join(', ')||'none'}</p></details>
  {canOpenOffset&&!saved&&r.ot.filter(o=>o.type==='Offset'&&o.status==='Approved').map(o=><Button key={o.id} className="mt-3" size="sm" variant="secondary" disabled={busy||!hasReason} onClick={()=>onOpenOffset(o.id)}>Open offset approval review</Button>)}
 </section>;
};

const HistoricalSources:React.FC<{records:TestTimeEvidence[]}>=({records})=>{
 const [error,setError]=useState('');const [downloading,setDownloading]=useState(false);const [page,setPage]=useState(0);
 const download=async(id:string)=>{setError('');setDownloading(true);try{downloadHistoricalSource(await historyDetail(id,true));}catch(e){setError(e instanceof Error?e.message:'Source download failed.');}finally{setDownloading(false);}};
 const batches=[...new Map<string,TestTimeEvidence>(records.map(r=>[r.batchId,r] as [string,TestTimeEvidence])).values()];const current=Math.min(page,Math.max(0,Math.ceil(records.length/50)-1));
 return <section className="space-y-3 rounded border border-amber-400 p-4"><h3 className="font-bold">Historical test evidence · not live attendance</h3><p>Documented imports remain separate from live totals, approval checks and submission. DTR totals do not create punches or approve OT.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}
 {batches.map(b=><div key={b.batchId} className="text-xs"><Button size="sm" variant="secondary" disabled={downloading} onClick={()=>void download(b.batchId)}>Download {b.filename}</Button><p>{b.reference} · Batch {b.batchId}</p></div>)}
 <ul className="space-y-2 text-xs">{records.slice(current*50,current*50+50).map(r=><li key={r.id}><strong>{r.workDate} · {r.kind==='dtr'?'Reviewed DTR summary':'Recorded punch'} · {r.filename} row {r.sourceRow}</strong>{r.kind==='dtr'?<p>Regular {num(r.payload.minutes?.REGULARMINUTES??0)} · OT {num(r.payload.minutes?.OVERTIMEMINUTES??0)} · Night {num(r.payload.minutes?.NIGHTMINUTES??0)} · Late {num(r.payload.minutes?.LATEMINUTES??0)} · Undertime {num(r.payload.minutes?.UNDERTIMEMINUTES??0)} · Unpaid break {num(r.payload.minutes?.UNPAIDBREAKMINUTES??0)} minutes · {r.payload.reviewReference}</p>:<p>{r.payload.action} · {r.payload.timestamp?stamp(r.payload.timestamp):'Time unavailable'} PHT · {r.payload.sourceReference}</p>}</li>)}</ul>
 {records.length>50&&<div className="flex items-center gap-3"><Button size="sm" variant="secondary" disabled={!current} onClick={()=>setPage(current-1)}>Previous sources</Button><span>{current*50+1}–{Math.min((current+1)*50,records.length)} of {records.length}</span><Button size="sm" variant="secondary" disabled={(current+1)*50>=records.length} onClick={()=>setPage(current+1)}>Next sources</Button></div>}
 <Link className={link} to="/payroll/historical-attendance">Open import validation and audit history</Link>
 </section>;
};
