import React,{useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import Button from '../../components/ui/Button';
import type {ReviewTimeRow,TestTimeEvidence} from './attendanceReadiness';
import {correctionLink,employeeReviews,timeTotals} from './timeReviewModel';
import {groupEmployeeReadiness,ReadinessCategory} from './readinessDashboardModel';
import {downloadHistoricalSource,historyDetail} from './historicalAttendance';

const link='text-indigo-700 underline dark:text-indigo-300';
const num=(value:number)=>value.toLocaleString('en-PH',{maximumFractionDigits:4});
const stamp=(value:string)=>new Date(value).toLocaleString('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
export const TimekeepingEmployeeTable:React.FC<{rows:ReviewTimeRow[];test:TestTimeEvidence[];saved:boolean;canOpenOffset:boolean;busy:boolean;hasReason:boolean;onOpenOffset:(id:string)=>void;scopeName?:string;from?:string;to?:string}>=({rows,test,saved,canOpenOffset,busy,hasReason,onOpenOffset,scopeName='Selected business unit',from='',to=''})=>{
 const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [expanded,setExpanded]=useState<string|null>(null);const totals=useMemo(()=>timeTotals(rows),[rows]);const cards=useMemo(()=>groupEmployeeReadiness(rows,scopeName,from,to),[rows,scopeName,from,to]);const historical=useMemo(()=>employeeReviews([],test),[test]);
 const filtered=cards.filter(card=>(!status||card.status===status)&&(!search||`${card.employeeName} ${card.employeeCode}`.toLowerCase().includes(search.trim().toLowerCase())));
 return <div className="space-y-4">
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[cards.length,'employees','👥'],[cards.reduce((sum,card)=>sum+card.total,0),'total issues','▤'],[cards.reduce((sum,card)=>sum+card.counts.attendance,0),'attendance corrections','◷'],[cards.reduce((sum,card)=>sum+card.counts.payroll_setup+card.counts.schedule,0),'setup blockers','⚙']].map(([value,label,icon])=><div className="rounded-xl bg-violet-50 p-4 dark:bg-violet-950/20" key={String(label)}><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-white text-violet-700 dark:bg-slate-800">{icon}</span><div><strong className="text-2xl">{value}</strong><p className="text-sm text-slate-500">{label}</p></div></div></div>)}</div>
  <div className="flex flex-wrap items-end gap-3"><label className="text-sm font-medium">Find employee<input className="mt-1 block min-h-11 rounded-xl border bg-transparent px-3" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or employee ID"/></label><label className="text-sm font-medium">Status<select className="mt-1 block min-h-11 rounded-xl border bg-transparent px-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>Ready</option><option>Needs attention</option><option>Blocking payroll</option></select></label><span className="pb-3 text-sm text-slate-500">{filtered.length} of {cards.length} employee cards</span></div>
  <p className="text-xs text-slate-500">{num(totals.scheduledMinutes)} scheduled · {num(totals.actualMinutes)} actual · {num(totals.approvedOtMinutes)} approved OT minutes. Issues are grouped once per employee and business unit.</p>
  {filtered.map(card=>{const open=expanded===card.key;const tone=card.status==='Ready'?'bg-emerald-100 text-emerald-800':card.status==='Needs attention'?'bg-amber-100 text-amber-800':'bg-rose-100 text-rose-800';const categories:[ReadinessCategory,string,string][]=[['attendance','Attendance','◷'],['schedule','Schedule','▣'],['overtime','Overtime review','↗'],['payroll_setup','Payroll setup','⚙']];const grouped=new Map<string,{label:string;dates:string[];issue:typeof card.issues[number]}>();for(const issue of card.issues){const key=`${issue.category}:${issue.label}`,prior=grouped.get(key);if(prior){if(!prior.dates.includes(issue.date))prior.dates.push(issue.date);}else grouped.set(key,{label:issue.label,dates:[issue.date],issue});}return <article className="overflow-hidden rounded-2xl border bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900" key={card.key}>
   <button type="button" className="flex w-full items-center justify-between gap-4 p-5 text-left" onClick={()=>setExpanded(open?null:card.key)} aria-expanded={open}><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-full bg-violet-100 font-bold text-violet-800">{card.employeeName.split(/\s+/).map(part=>part[0]).slice(0,2).join('')}</span><div><h3 className="text-lg font-bold">{card.employeeName}</h3><p className="text-sm text-slate-500">{card.employeeCode} · {card.businessUnit}</p></div></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-sm font-semibold ${tone}`}>{card.total} {card.total===1?'issue':'issues'} · {card.status}</span><span>{open?'⌃':'⌄'}</span></div></button>
   {open&&<div className="border-t p-5 dark:border-slate-700"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{categories.map(([category,label,icon])=><div className={`rounded-xl p-3 ${card.counts[category]?'bg-amber-50 dark:bg-amber-950/20':'bg-slate-50 dark:bg-slate-800'}`} key={category}><span className="mr-2">{icon}</span><strong>{card.counts[category]}</strong><span className="ml-2 text-sm">{label}</span></div>)}</div>
    <div className="mt-4 divide-y rounded-xl border dark:divide-slate-700 dark:border-slate-700">{(['attendance','schedule','overtime','payroll_setup'] as ReadinessCategory[]).map(category=>{const setup=category==='schedule'?card.setup.filter(item=>item.key.startsWith('schedule:')):category==='payroll_setup'?card.setup.filter(item=>!item.key.startsWith('schedule:')):[];const issues=[...grouped.values()].filter(item=>item.issue.category===category);if(!setup.length&&!issues.length)return null;return <section className="p-4" key={category}><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="font-bold capitalize">{category.replace('_',' ')}</h4><p className="text-xs text-slate-500">{setup.length+issues.length} grouped {setup.length+issues.length===1?'dependency':'items'}</p></div>{category==='attendance'&&<Link className={link} to={`/payroll/historical-corrections?employee=${card.employeeId}`}>Review attendance →</Link>}{category==='schedule'&&<Link className={link} to="/payroll/timekeeping">Review schedules →</Link>}{category==='payroll_setup'&&<Link className={link} to={`/payroll/pay-packages?employee=${card.employeeId}`}>Open employee setup →</Link>}</div>
     <div className="mt-3 flex flex-wrap gap-2">{setup.map(item=><Link key={item.key} to={item.path} className="rounded-full bg-rose-100 px-3 py-2 text-sm font-medium text-rose-800">● {item.label} · {item.dates.join(', ')}</Link>)}{issues.map(item=><Link key={`${item.issue.label}:${item.dates.join()}`} to={`${item.issue.path}?employee=${card.employeeId}&date=${item.dates[0]}&issue=${encodeURIComponent(item.issue.label)}`} className="rounded-full bg-amber-100 px-3 py-2 text-sm font-medium text-amber-900">● {item.label} · {item.dates.join(', ')}</Link>)}</div>
     {setup.length>0&&<div className="mt-3 rounded-lg bg-violet-50 p-3 text-sm text-violet-950 dark:bg-violet-950/20 dark:text-violet-100"><strong>This is one setup dependency affecting multiple dates.</strong> Fix it once and the affected payroll dates will refresh automatically.</div>}</section>;})}</div>
    <div className="mt-4 flex flex-wrap gap-3"><Button onClick={()=>setExpanded(card.key)}>Review all issues</Button>{card.total>0&&<Link className="inline-flex min-h-11 items-center rounded-lg border px-4 font-semibold text-violet-700" to={card.issues[0]?`${card.issues[0].path}?employee=${card.employeeId}&date=${card.issues[0].date}&issue=${encodeURIComponent(card.issues[0].label)}`:card.setup[0]?.path||'/employees'}>Fix next</Link>}</div>
    <details className="mt-5"><summary className="cursor-pointer font-semibold text-slate-600">View daily evidence and original source IDs</summary><div className="mt-4 space-y-4">{card.days.map(day=><DayDetail key={day.date} row={day} saved={saved} canOpenOffset={canOpenOffset} busy={busy} hasReason={hasReason} onOpenOffset={onOpenOffset}/>)}{historical.find(item=>item.id===card.employeeId)?.test.length?<HistoricalSources records={historical.find(item=>item.id===card.employeeId)!.test}/>:null}</div></details>
   </div>}
  </article>;})}
  {!filtered.length&&<div className="rounded-xl border border-dashed p-8 text-center text-slate-500">{cards.length?'No employees match these filters.':'No employee records for this payroll cycle.'}</div>}
 </div>;
};

const DayDetail:React.FC<{row:ReviewTimeRow;saved:boolean;canOpenOffset:boolean;busy:boolean;hasReason:boolean;onOpenOffset:(id:string)=>void}>=({row:r,saved,canOpenOffset,busy,hasReason,onOpenOffset})=>{
 const evidence=r.evidence;
 return <section className="rounded-lg border bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><h3 className="font-semibold">{r.date} · {r.restDay?'Rest day':r.approvedFullLeave?'Approved leave':'Workday'}{r.holiday?' · Holiday':''} · {r.ready?'Checks passed':'Needs review'}</h3>
  {r.officialBusiness&&<p>Official Business · {r.officialBusiness.reference} · {r.officialBusiness.status}</p>}
  <div className="mt-3 grid gap-4 lg:grid-cols-3">
   <div><h4 className="font-medium">Schedule · {evidence?.scheduleStatus||'evidence unavailable'}</h4><p>{num(r.scheduledMinutes)} scheduled minutes</p>{evidence?.shifts.map((s,i)=><p key={`${s.id}-${i}`} className="mt-1 text-xs">{s.name||s.kind||'Shift'} · {s.start||'—'}–{s.end||'—'}{s.endDayOffset?` (+${s.endDayOffset} day)`:''}<span className="block break-all">Publication {s.publicationId||'reference unavailable'}{s.publicationVersion?` · v${s.publicationVersion}`:''}</span></p>)}</div>
   <div><h4 className="font-medium">Attendance evidence</h4><p>{num(r.actualMinutes)} actual · {num(r.breakMinutes)} break minutes</p>{r.requiresClock===false&&<p className="text-xs">Approved schedule-based attendance exception; punches are not fabricated.</p>}{evidence?.punches.length?evidence.punches.map((p,i)=><p key={`${p.id}-${i}`} className="mt-1 text-xs">{p.type} · {stamp(p.timestamp)} PHT<span className="block break-all">{p.source||'Recorded'} · {p.id}{p.revision!=null?` · revision ${p.revision}`:''}</span></p>):<p className="text-xs">No punch evidence in this result. See attendance requirements and blockers.</p>}<p className="mt-2">Late {num(r.lateMinutes)} · Undertime {num(r.undertimeMinutes)}</p></div>
   <div><h4 className="font-medium">Leave and OT approval evidence</h4><p>Approved OT {num(r.approvedOtMinutes)} · Actual OT {num(r.actualOtMinutes)}</p>{evidence?.leave.map(l=><p key={l.id} className="mt-1 break-all text-xs">{l.type} · {l.status}{l.configurationRequired?' · approval setup incomplete':''} · {l.startDate}–{l.endDate} · {l.id}</p>)}{evidence?.ot.map(o=><p key={o.id} className="mt-1 break-all text-xs">{o.type} OT · {o.status}{o.configurationRequired?' · approval setup incomplete':''} · {o.start}–{o.end} · {o.approvedHours??'—'} approved hours · {o.id}{o.reviewRef?` · ${o.reviewRef}`:''}</p>)}{!r.leaveIds.length&&<p className="text-xs">No leave source requests.</p>}</div>
  </div>
  {r.issues.length>0&&<ul className="mt-4 space-y-2 border-t pt-3 dark:border-slate-700">{r.issues.map(issue=>{const target=correctionLink(issue,r);return <li key={issue}><span className="font-medium">{issue}</span>{!saved&&<span className="block text-xs"><Link className={link} to={target.path}>{target.label}</Link> · Responsible: {target.owner}</span>}</li>;})}</ul>}
  <details className="mt-3 text-xs"><summary>Original source IDs</summary><p className="break-all">Shifts: {r.shiftIds.join(', ')||'none'}<br/>Punches: {r.eventIds.join(', ')||'none'}<br/>Leave: {r.leaveIds.join(', ')||'none'}</p></details>
  {canOpenOffset&&!saved&&r.ot.filter(o=>o.type==='Offset'&&o.status==='Approved').map(o=><Button key={o.id} className="mt-3" size="sm" variant="secondary" disabled={busy||!hasReason} onClick={()=>onOpenOffset(o.id)}>Open offset approval review</Button>)}
 </section>;
};

const HistoricalSources:React.FC<{records:TestTimeEvidence[]}>=({records})=>{
 const [error,setError]=useState('');const [downloading,setDownloading]=useState(false);const [page,setPage]=useState(0);
 const download=async(id:string)=>{setError('');setDownloading(true);try{downloadHistoricalSource(await historyDetail(id,true));}catch(e){setError(e instanceof Error?e.message:'Source download failed.');}finally{setDownloading(false);}};
 const batches=[...new Map<string,TestTimeEvidence>(records.map(r=>[r.batchId,r] as [string,TestTimeEvidence])).values()];const current=Math.min(page,Math.max(0,Math.ceil(records.length/50)-1));
 return <section className="space-y-3 rounded border border-amber-400 p-4"><h3 className="font-bold">Historical test evidence · not live attendance</h3><p>Documented imports remain separate from live totals, approval checks and submission. DTR totals do not create punches or approve OT.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}
 {batches.map(b=><div key={b.batchId} className="text-xs"><Button size="sm" variant="secondary" disabled={downloading} onClick={()=>void download(b.batchId)}>Download {b.filename}</Button><p>{b.reference} · Batch {b.batchId}</p></div>)}
 <ul className="space-y-2 text-xs">{records.slice(current*50,current*50+50).map(r=><li key={r.id}><strong>{r.workDate} · {r.kind==='dtr'?'Reviewed DTR summary':'Recorded punch'} · {r.filename} row {r.sourceRow}</strong>{r.kind==='dtr'?<p>Regular {num(r.payload.minutes?.REGULARMINUTES??0)} · OT {num(r.payload.minutes?.OVERTIMEMINUTES??0)} · Night {num(r.payload.minutes?.NIGHTMINUTES??0)} · Late {num(r.payload.minutes?.LATEMINUTES??0)} · Undertime {num(r.payload.minutes?.UNDERTIMEMINUTES??0)} · Unpaid break {num(r.payload.minutes?.UNPAIDBREAKMINUTES??0)} minutes · {r.payload.reviewReference}</p>:<p>{r.payload.action} · {r.payload.timestamp?stamp(r.payload.timestamp):'Time unavailable'} PHT · {r.payload.sourceReference}</p>}</li>)}</ul>
 {records.length>50&&<div className="flex items-center gap-3"><Button size="sm" variant="secondary" disabled={!current} onClick={()=>setPage(current-1)}>Previous sources</Button><span>{current*50+1}–{Math.min((current+1)*50,records.length)} of {records.length}</span><Button size="sm" variant="secondary" disabled={(current+1)*50>=records.length} onClick={()=>setPage(current+1)}>Next sources</Button></div>}
 <Link className={link} to="/payroll/historical-attendance">Open import validation and audit history</Link>
 </section>;
};
