import React from 'react';
import {Link} from 'react-router-dom';
import {Pulse,impactedSchedule,pulseLevel,pulsePath,pulseTone,useAttendancePulse} from '../../services/attendancePulse';
const link='inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-300 px-4 py-2 font-semibold dark:border-slate-600';
export function PulseTrend({data,full=false}:{data:Pulse;full?:boolean}){
 const days=data.trend.slice(full?0:-7),max=Math.max(1,...days.map(d=>d.count));
 return <div><div className="mt-4 flex h-16 items-end gap-1" role="img" aria-label={days.map(d=>`${d.date}: ${d.tracked?d.count+' reports':'baseline not yet tracked'}`).join('; ')}>{days.map(d=><div key={d.date} title={`${d.date}: ${d.count} reports${d.tracked?'':' (before baseline tracking)'}`} className="flex h-full flex-1 items-end"><div className={'w-full min-h-1 rounded-t '+(d.date===data.date?'bg-violet-600':d.tracked?'bg-violet-300 dark:bg-violet-500':'bg-slate-200 dark:bg-slate-700')} style={{height:`${Math.max(4,d.count/max*100)}%`}}/></div>)}</div><div className="mt-2 flex justify-between text-xs text-slate-500 dark:text-slate-400"><span>{days[0]?.date}</span><span>{days.at(-1)?.date}</span></div></div>;
}
export function PulseSummary({data}:{data:Pulse}){
 const delta=data.usual&&data.usual>0?Math.round((data.reported-data.usual)/data.usual*100):null;
 return <section className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 text-slate-900 shadow-sm dark:border-slate-700 dark:bg-slate-800 dark:text-white sm:p-6" aria-labelledby="pulse-heading"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-slate-500 dark:text-slate-400">Today at a glance · {data.scope}</p><h2 id="pulse-heading" className="text-2xl font-bold">Attendance pulse</h2></div><span className={'rounded-full border px-3 py-1 text-sm font-semibold '+pulseTone[data.severity]}>{pulseLevel[data.severity]}</span></div>
 <div className="grid gap-6 lg:grid-cols-2"><div><p className="text-5xl font-bold tracking-tight">{data.reported}</p><p className="mt-2 text-lg">reported unable to work {data.date===new Date(Date.now()+28800000).toISOString().slice(0,10)?'today':`on ${data.date}`}</p><p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{data.approved} approved · {data.pending} pending · {data.attention} need attention</p><p className="mt-5 font-semibold">{data.usual===null?'Building a comparable-workday baseline':`Usually ${data.usual} on this weekday${delta===null?'':` · ${delta>=0?'+':''}${delta}%`}`}</p><PulseTrend data={data}/><Link className="mt-3 inline-flex min-h-11 items-center font-semibold text-violet-700 dark:text-violet-300" to={pulsePath(data.date)+'&view=trend'}>View attendance trend →</Link></div>
 <div><h3 className="mb-3 font-semibold">Business units</h3>{data.units.length===0?<p className="text-slate-500 dark:text-slate-400">No unable-to-work reports for this date.</p>:[...data.units].sort((a,b)=>b.count-a.count).map(b=><Link to={pulsePath(data.date)+'&bu='+b.id} key={b.id||b.name} className="mb-3 block rounded-lg focus:outline-violet-500"><div className="flex justify-between gap-4 text-sm"><span>{b.name}</span><strong>{b.count}</strong></div><div className="mt-1 h-2 rounded-full bg-slate-100 dark:bg-slate-700"><div className="h-2 rounded-full bg-violet-500" style={{width:`${b.count/Math.max(1,data.reported)*100}%`}}/></div></Link>)}
 {data.concerns.length>0&&<div className={'mt-5 rounded-xl border p-4 '+pulseTone[data.severity]}><h3 className="font-bold">What needs attention</h3><ul className="mt-2 space-y-2 text-sm">{data.concerns.slice(0,3).map((c,i)=><li key={i}><Link className="underline" to={pulsePath(data.date)+'&attention=1'+(c.businessUnitId?'&bu='+c.businessUnitId:'')}>{c.text} →</Link></li>)}</ul></div>}
 <div className="mt-5 flex flex-wrap gap-2"><Link className={link+' bg-violet-600 text-white'} to={pulsePath(data.date)}>Review today’s reports</Link><Link className={link} to={impactedSchedule(data.date)}>Open impacted schedule</Link></div></div></div><p className="mt-4 text-xs text-slate-500 dark:text-slate-400">Reports are not approved absences. Counts exclude withdrawn and cancelled reports; pending overdue reports also appear under attention.</p></section>;
}
export default function AttendancePulse(){const {data,error,load}=useAttendancePulse();if(error)return <div className="mb-4 text-sm" role="status">Attendance pulse could not load. <button className="underline" onClick={()=>void load()}>Retry</button></div>;if(!data?.allowed)return null;return <PulseSummary data={data}/>;}
