import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import AttendanceIssueForm from '../attendance/AttendanceIssueForm';
import {AttendanceIssue,caseStates,issueLabels,manila,shiftText,useAttendanceIssues} from '../../services/attendanceIssues';
const link='inline-flex min-h-11 items-center rounded-lg border border-violet-300 px-3 py-2 font-semibold text-violet-800 dark:border-violet-600 dark:text-violet-200';
export default function AttendanceFollowups(){const data=useAttendanceIssues();const [edit,setEdit]=useState<AttendanceIssue>();
 const action=data.rows.filter(r=>r.isOwn&&(r.status==='details'||r.hrState==='employee_clarification'));
 const rejected=data.rows.filter(r=>r.isOwn&&r.status==='rejected'&&r.hrState&&!r.hrState.startsWith('closed'));
 const manager=data.rows.filter(r=>r.isManager);const hr=data.rows.filter(r=>r.hrState&&!r.isOwn);
 return <div className="mb-5 space-y-4 text-slate-900 dark:text-white">{data.error&&<p role="alert">Attendance follow-ups could not load. <button className="underline" onClick={()=>void data.load()}>Retry</button></p>}
 {action.map(r=><section key={r.id} className="rounded-2xl border border-amber-400 bg-amber-50 p-5 dark:bg-amber-950"><h2 className="text-xl font-bold">Action Required: Update Attendance Request</h2><p className="mt-2">{issueLabels[r.kind]} · {r.work_date}</p><p>Scheduled shift: {shiftText(r.schedule)}</p><p className="my-2 whitespace-pre-wrap">{r.status==='details'?r.clarification_message:'HR has requested your written clarification. Open the request to read the message and respond.'}</p><p className="text-sm">{r.status==='details'&&r.reviewed_at?`Returned ${manila(r.reviewed_at)} · Needs Clarification`:'HR clarification required'}</p>{r.status==='details'?<button className={link+' mt-3'} onClick={()=>setEdit(r)}>Edit and Resubmit</button>:<Link className={link+' mt-3'} to={'/payroll/attendance-requests?review='+r.id}>Review HR Clarification</Link>}</section>)}
 {rejected.filter(r=>r.hrState!=='employee_clarification').map(r=><section key={r.id} className="rounded-2xl border border-slate-300 p-5 dark:border-slate-600"><h2 className="font-bold">{r.hrState==='nte_sent'?'NTE Response Required':r.hrState==='nte_response_received'?'NTE Response Received – HR Review':'Attendance Request Not Approved – HR Review Pending'}</h2><p>{issueLabels[r.kind]} · {r.work_date} · {shiftText(r.schedule)}</p><p>{r.rejection_category}</p><p className="whitespace-pre-wrap">{r.rejection_comments}</p><Link className={link+' mt-3'} to={'/payroll/attendance-requests?review='+r.id}>View Request History & HR Status</Link></section>)}
 <div className="flex flex-wrap gap-2">{data.rows.some(r=>r.isOwn)&&[['pending','Pending Attendance Requests'],['approved','Approved Requests'],['rejected','Rejected Requests / HR Review']].map(([s,l])=><Link key={s} className={link} to={'/payroll/attendance-requests?status='+s}>{l}</Link>)}{manager.some(r=>r.status==='details')&&<Link className={link} to="/payroll/attendance-requests?queue=clarification">Manager Clarification Queue</Link>}{manager.some(r=>r.canReview&&r.audit.some(a=>a.action==='edited and resubmitted'))&&<Link className={link} to="/payroll/attendance-requests?queue=resubmitted">Resubmitted Requests</Link>}{manager.some(r=>r.status==='rejected')&&<Link className={link} to="/payroll/attendance-requests?queue=all&status=rejected">Rejected Requests Sent to HR</Link>}</div>
 {data.canManage&&hr.length>0&&<section className="rounded-2xl border border-slate-300 p-5 dark:border-slate-600"><h2 className="text-xl font-bold">Attendance HR Review</h2><p className="mt-1 mb-3">Attendance cases are separate from manager clarification requests.</p><div className="flex flex-wrap gap-2">{Object.entries(caseStates).map(([s,l])=><Link key={s} className={link} to={'/payroll/attendance-requests?queue=all&status='+s}>{l}</Link>)}</div></section>}
 {edit&&<AttendanceIssueForm initial={edit} onClose={()=>setEdit(undefined)} onSaved={()=>{setEdit(undefined);void data.load();}}/>}</div>;
}
