import React,{useEffect,useMemo,useRef,useState} from 'react';
import {supabase} from '../../services/supabaseClient';
import {LeaveRequest,LeaveRequestStatus} from '../../types';
import {useAuth} from '../../hooks/useAuth';
import Modal from '../ui/Modal';
import Button from '../ui/Button';
import Input from '../ui/Input';
import Textarea from '../ui/Textarea';
import FileUploader from '../ui/FileUploader';
import {classifyLeaveRequest,ExceptionOutcome,leavePresentation} from '../../modules/payroll/leaveManagementModel';
import {getApprovalStatusLabel,getApprovalStepLabel} from '../../utils/approvalPresentation';
interface Props{isOpen:boolean;onClose:()=>void;request:LeaveRequest|null;leaveTypes:{id:string;name:string;paid?:boolean}[];availableBalances?:Record<string,number>;onSave:(request:Partial<LeaveRequest>&Record<string,unknown>,status:LeaveRequestStatus)=>void|Promise<void>;onApprove:(request:LeaveRequest,approved:boolean,notes:string,outcome?:ExceptionOutcome)=>void|Promise<void>;onFileSelect?:(file:File|null)=>void;}
const icons:Record<string,string>={vacation:'🌴',sick:'✚',offset:'💼',lwop:'◷'};
const fmt=(value:unknown)=>Number(value||0).toLocaleString('en-PH',{maximumFractionDigits:3});
export default function LeaveRequestModal({isOpen,onClose,request,leaveTypes,availableBalances={},onSave,onApprove,onFileSelect}:Props){
 const {user}=useAuth();const [current,setCurrent]=useState<any>({}),[progress,setProgress]=useState<any>(null),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[outcome,setOutcome]=useState<ExceptionOutcome>('lwop');
 const lock=useRef(false),isNew=!request,canEdit=isNew||request?.status===LeaveRequestStatus.Draft,isReviewer=!!request&&request.employeeId!==user?.id&&[LeaveRequestStatus.Pending,LeaveRequestStatus.PendingGM,LeaveRequestStatus.PendingBOD].includes(request.status);
 useEffect(()=>{if(!isOpen)return;setCurrent(request||{leaveTypeId:leaveTypes[0]?.id||'',startDate:new Date(),endDate:new Date(),durationDays:1,status:LeaveRequestStatus.Draft});setNote('');setError('');setConfirmed(false);setOutcome('lwop');setProgress(null);if(request?.id)supabase.rpc('get_leave_exception_approval_context',{p_request_id:request.id}).then(({data,error})=>{if(error){setError(error.message);return;}setProgress(data);const shortfall=Number(data?.creditShortfall||0);setOutcome(shortfall>0||data?.isLwop?'lwop':data?.isProbationary?'paid_exception':'lwop');});},[isOpen,request?.id,leaveTypes]);
 const selected=leaveTypes.find(type=>type.id===current.leaveTypeId)||leaveTypes[0];const selectedInfo=leavePresentation(selected?.name||'Leave Without Pay',availableBalances[selected?.id||'']||0);
 const calculation=useMemo(()=>classifyLeaveRequest(selected?.name||'',current.durationDays||1,availableBalances[selected?.id||'']||0,confirmed),[selected?.name,selected?.id,current.durationDays,availableBalances,confirmed]);
 const requestType=leaveTypes.find(type=>type.id===request?.leaveTypeId)?.name||progress?.selectedLeaveType||'Leave request';const exception=!!(progress?.requiresBodException??progress?.creditException??request?.approvalContext?.creditException);const authorizedBod=request?.status===LeaveRequestStatus.PendingBOD&&progress?.canAct===true;const bodStage=request?.status===LeaveRequestStatus.PendingBOD;const decisionEnabled=!bodStage||progress?.canAct===true;const leaveOutcomeLabel=(Number(progress?.unpaidDays||request?.unpaidDays||0)>0||progress?.isLwop||progress?.finalClassification==='lwop')?'Leave Without Pay (LWOP)':'Paid leave';
 const setDate=(key:'startDate'|'endDate',value:string)=>{const next=new Date(value+'T00:00:00');const start=key==='startDate'?next:new Date(current.startDate);let end=key==='endDate'?next:new Date(current.endDate);if(end<start)end=start;setCurrent((old:any)=>({...old,[key]:next,startDate:start,endDate:end,durationDays:Math.floor((end.getTime()-start.getTime())/86400000)+1}));setConfirmed(false);};
 async function save(status:LeaveRequestStatus){if(lock.current)return;if(status===LeaveRequestStatus.Pending&&calculation.requiresConfirmation){setError('Confirm that this request will be filed as Leave Without Pay before submitting.');return;}lock.current=true;setBusy(true);setError('');try{await onSave({...current,selectedLeaveTypeId:current.leaveTypeId,selectedLeaveType:selected?.name,paidDays:calculation.paidDays,unpaidDays:calculation.unpaidDays,creditShortfall:calculation.creditShortfall,finalClassification:calculation.finalClassification,lwopConfirmed:confirmed||selectedInfo.kind==='lwop'},status);}catch(e:any){setError(e.message||'The request was not saved.');}finally{lock.current=false;setBusy(false);}}
 async function decide(approved:boolean){if(lock.current||!request)return;if(!approved&&!note.trim()){setError('A rejection reason is required.');return;}lock.current=true;setBusy(true);setError('');try{await onApprove(request,approved,note,exception?outcome:undefined);}catch(e:any){setError(e.message||'The decision was not saved.');}finally{lock.current=false;setBusy(false);}}
 const footer=isReviewer?<div className="w-full space-y-3"><Textarea label={request?.status===LeaveRequestStatus.PendingBOD?'BOD note (optional for approval)':'Approval note'} value={note} onChange={e=>setNote(e.target.value)} rows={2}/><p className="text-xs text-slate-500">A rejection reason is required.</p><div className="grid grid-cols-2 gap-3"><Button variant="danger" disabled={busy||progress?.alreadyApproved||!decisionEnabled} onClick={()=>void decide(false)}>Reject</Button><Button disabled={busy||progress?.alreadyApproved||!decisionEnabled} onClick={()=>void decide(true)}>{progress?.alreadyApproved?'Already approved by you':'Approve'}</Button></div></div>:canEdit?<div className="flex w-full flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="secondary" disabled={busy} onClick={onClose}>Change dates / cancel</Button><Button variant="secondary" disabled={busy} onClick={()=>void save(LeaveRequestStatus.Draft)}>Save draft</Button><Button disabled={busy||calculation.requiresConfirmation} onClick={()=>void save(LeaveRequestStatus.Pending)}>{calculation.unpaidDays>0?'Continue as Leave Without Pay':'Submit request'}</Button></div>:<Button variant="secondary" onClick={onClose}>Close</Button>;
 return <Modal acknowledgmentRequestType={canEdit?'Leave':undefined} acknowledgmentDraft={!isNew} isOpen={isOpen} onClose={busy?()=>{}:onClose} title={isNew?'Request Leave':'Leave Request Details'} size={isNew?'full':'2xl'} viewportFit={isNew} footer={footer}><div className="space-y-5">{error&&<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-800">{error}</div>}{isNew?<div className="grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(340px,0.85fr)]"><div className="space-y-6">
  <section><div className="mb-3 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-violet-600 font-bold text-white">1</span><div><h3 className="font-bold">What type of leave are you applying for?</h3><p className="text-sm text-slate-500">Select the leave type, then choose your dates.</p></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{leaveTypes.map(type=>{const info=leavePresentation(type.name,availableBalances[type.id]||0),active=type.id===current.leaveTypeId;return <button key={type.id} type="button" onClick={()=>{setCurrent((old:any)=>({...old,leaveTypeId:type.id}));setConfirmed(false);}} className={`relative min-h-36 rounded-2xl border-2 p-4 text-left transition ${active?'border-violet-600 bg-violet-50 shadow-sm':'border-slate-200 hover:border-violet-300'}`}><span className="text-2xl">{icons[info.kind]}</span><strong className="mt-3 block">{info.label}</strong><span className="block text-sm text-slate-500">{info.paid?'Paid time off':'Unpaid leave'}</span><span className="mt-2 block text-sm font-semibold text-slate-600">{info.available==null?'Does not use credits':`${fmt(info.available)} available`}</span>{active&&<span className="absolute right-3 top-3 flex h-6 w-6 items-center justify-center rounded-full bg-violet-600 text-white">✓</span>}</button>})}</div></section>
  {calculation.creditShortfall>0&&selectedInfo.kind!=='lwop'&&<div className="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-950"><strong className="text-lg">⚠ You do not have enough available credits.</strong><p className="mt-1">You selected <strong>{selected?.name}</strong>, but you have {fmt(calculation.availableCredits)} available credits. This request will be filed as <strong>Leave Without Pay</strong>.</p></div>}
  <section><div className="mb-3 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-violet-600 font-bold text-white">2</span><h3 className="font-bold">When are you taking leave?</h3></div><div className="grid gap-4 sm:grid-cols-3"><Input label="Start date" type="date" value={current.startDate?new Date(current.startDate).toISOString().slice(0,10):''} onChange={e=>setDate('startDate',e.target.value)}/><Input label="End date" type="date" value={current.endDate?new Date(current.endDate).toISOString().slice(0,10):''} onChange={e=>setDate('endDate',e.target.value)}/><Input label="Number of days" type="number" value={String(current.durationDays||1)} disabled/></div></section>
  <section><div className="mb-3 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-violet-600 font-bold text-white">3</span><h3 className="font-bold">Reason for leave</h3></div><Textarea label="Reason" value={current.reason||''} onChange={e=>setCurrent((old:any)=>({...old,reason:e.target.value}))} rows={4} required/></section>
  <section><div className="mb-3 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-violet-600 font-bold text-white">4</span><h3 className="font-bold">Attach document <span className="font-normal text-slate-500">(optional)</span></h3></div><FileUploader onFileUpload={(file:any)=>onFileSelect?.(file||null)}/></section>
 </div><aside className="rounded-2xl border bg-gradient-to-b from-violet-50 to-white p-5"><h3 className="text-xl font-black">Request Summary</h3><p className="text-sm text-slate-500">Review the details before submitting.</p><dl className="mt-5 space-y-4 text-sm"><div className="rounded-xl border border-amber-200 bg-amber-50 p-3"><dt className="text-slate-500">Leave type</dt><dd className="font-bold">{calculation.unpaidDays>0?'Leave Without Pay (LWOP)':selected?.name}</dd>{calculation.unpaidDays>0&&<small>Selected request: {selected?.name}</small>}</div>{[['Dates',`${current.startDate?new Date(current.startDate).toLocaleDateString('en-PH'):''} – ${current.endDate?new Date(current.endDate).toLocaleDateString('en-PH'):''}`],['Number of days',`${fmt(calculation.requestedDays)} day(s)`],['Paid days',`${fmt(calculation.paidDays)} day(s)`],['Unpaid days',`${fmt(calculation.unpaidDays)} day(s)`],['Reason',current.reason||'Not specified'],['Attachment','Optional supporting document'],['Approval route',calculation.creditShortfall?'Manager review → BOD exception review':'Manager approval'],['Expected payroll impact',calculation.unpaidDays?`${fmt(calculation.unpaidDays)} unpaid day(s) may be deducted from payroll`:'Paid leave; credits will be consumed']].map(([label,value])=><div key={label} className="flex justify-between gap-4 border-b pb-3"><dt className="text-slate-500">{label}</dt><dd className="max-w-[60%] text-right font-semibold">{value}</dd></div>)}</dl>{calculation.creditShortfall>0&&<label className="mt-5 flex cursor-pointer gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1 h-4 w-4"/><span><strong>Please confirm</strong><span className="block">I understand this will be filed as Leave Without Pay because I do not have enough available credits.</span></span></label>}</aside></div>:
 <div className="mx-auto max-w-2xl space-y-5"><div className="rounded-2xl border bg-white p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xl font-black">{request?.employeeName}</p><p className="text-slate-500">Employee</p></div>{exception&&<span className="rounded-full bg-amber-100 px-4 py-2 text-sm font-bold text-amber-800">BOD exception review</span>}</div><div className="mt-5 grid gap-4 border-t pt-5 sm:grid-cols-2"><div><small className="text-slate-500">Leave type</small><strong className="block">{requestType}</strong></div><div><small className="text-slate-500">Leave period</small><strong className="block">{new Date(request!.startDate).toLocaleDateString('en-PH')} – {new Date(request!.endDate).toLocaleDateString('en-PH')} · {fmt(request?.durationDays)} day(s)</strong></div></div></div>
  {exception&&<><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><strong className="text-lg">BOD exception approval required.</strong><p>{progress?.creditException?'The employee has insufficient earned credits. The request remains available for an authorized BOD decision.':progress?.isLwop?'This request is classified as Leave Without Pay; paid-leave credits will not be deducted.':progress?.isProbationary?'The employee is probationary. That status does not block an authorized BOD decision.':'This request requires an authorized BOD exception decision.'}</p></div>{authorizedBod&&<div className="rounded-2xl border border-amber-200 bg-gradient-to-r from-amber-50 to-yellow-50 p-5 text-amber-950"><strong>♛ You are an authorized BOD approver.</strong><p>You may approve this exception.</p></div>}</>}
  <div className="rounded-2xl border border-indigo-200 bg-indigo-50 p-5"><h3 className="font-bold">Approval decision context</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Paid or unpaid</dt><dd className="font-semibold">{leaveOutcomeLabel}</dd></div><div><dt className="text-sm text-slate-500">Current approval stage</dt><dd className="font-semibold">{progress?.currentStage||request?.status||'Loading'}</dd></div><div><dt className="text-sm text-slate-500">Required approver</dt><dd className="font-semibold">{progress?.requiredApprover||(bodStage?'Authorized Board of Director':'Current assigned approver')}</dd></div><div><dt className="text-sm text-slate-500">Employment status</dt><dd className="font-semibold">{progress?.employmentStatus||'Not provided'}</dd></div></dl>{bodStage&&!progress?.canAct&&<p className="mt-3 text-sm font-semibold text-rose-700">This request is awaiting an authorized BOD approver. You cannot approve your own request.</p>}</div>
  <div className="rounded-2xl border p-5"><h3 className="font-bold">Leave Credits Summary</h3><dl className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4">{[['Available credits',progress?.availableCredits],['Requested days',progress?.requestedCredits??request?.durationDays],['Credit shortfall',progress?.creditShortfall],['Balance after request',progress?.remainingBalance]].map(([label,value])=><div key={label} className="border-r last:border-0"><dd className={`text-3xl font-black ${label==='Credit shortfall'?'text-rose-600':''}`}>{label==="Available credits"&&progress?.creditTracked===false?"Not tracked":fmt(value)}</dd><dt className="text-sm text-slate-500">{label}</dt></div>)}</dl></div>
  {exception&&isReviewer&&<fieldset className="rounded-2xl border p-5"><legend className="px-2 font-bold">Result after approval</legend><div className="grid gap-3 sm:grid-cols-2"><label className={`cursor-pointer rounded-xl border-2 p-4 ${outcome==='paid_exception'?'border-violet-600 bg-violet-50':'border-slate-200'}`}><input type="radio" className="mr-2" checked={outcome==='paid_exception'} onChange={()=>setOutcome('paid_exception')}/><strong>Approved paid leave exception</strong><span className="mt-1 block text-sm text-slate-500">No credits are added. The shortfall and negative balance remain in the audit.</span></label><label className={`cursor-pointer rounded-xl border-2 p-4 ${outcome==='lwop'?'border-violet-600 bg-violet-50':'border-slate-200'}`}><input type="radio" className="mr-2" checked={outcome==='lwop'} onChange={()=>setOutcome('lwop')}/><strong>Approved Leave Without Pay</strong><span className="mt-1 block text-sm text-slate-500">No paid-leave credits are consumed.</span></label></div></fieldset>}
  <div className="rounded-2xl border p-5"><h3 className="font-bold">Approval details</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Current approval step</dt><dd className="font-semibold">{getApprovalStepLabel(request!.status)}</dd></div><div><dt className="text-sm text-slate-500">Status</dt><dd className="font-semibold">{getApprovalStatusLabel(request!.status)}</dd></div><div className="sm:col-span-2"><dt className="text-sm text-slate-500">Approval history</dt><dd className="mt-2 space-y-2">{request?.historyLog?.length?request.historyLog.map((item:any,index)=><p key={index} className="rounded-lg bg-slate-50 p-2 text-sm"><strong>{item.action}</strong> · {item.userName||item.userId} · {new Date(item.timestamp).toLocaleString('en-PH')}{item.details?` · ${item.details}`:''}</p>):'No recorded decisions yet.'}</dd></div></dl></div>
 </div>}</div></Modal>;
}
