import React, {useState} from 'react';
import type {SchedulePublication,ScheduleEntry} from '../../services/schedulePublicationService';
import {getPublicationHistory,PublicationHistory} from '../../services/schedulePublicationService';
import Button from '../ui/Button';
const entry=(x:ScheduleEntry)=>`${x.date}: ${x.kind==='rest'?'Rest Day':x.kind==='no_schedule'?'Leave / No Schedule':x.flexible?`Flexible · ${(x.paidMinutes??0)/60} paid hours`:`${x.start}–${x.end}${x.endDayOffset===1?' (+1 day)':''}`} · ${x.name}`;
export default function SchedulePublicationStatus({rows,names,onReview,busy,onPublish,reviewNote,onReviewNote,week}:{week:string;rows:SchedulePublication[];names:Record<string,string>;onReview:(id:string,approve:boolean)=>void;busy:boolean;onPublish?:(employeeId:string)=>void;reviewNote:string;onReviewNote:(value:string)=>void}){
 const [selected,setSelected]=useState('');
 return <details className="mb-4 rounded border p-3 text-sm"><summary className="cursor-pointer font-semibold">Advanced schedule versions</summary><p className="my-2">Published versions, proposed changes and override history.</p>
 {onPublish&&<div className="my-3 flex flex-wrap gap-2"><select aria-label="Employee to publish" value={selected} onChange={e=>setSelected(e.target.value)} className="rounded border p-2 dark:bg-slate-800"><option value="">Select employee</option>{rows.filter(r=>!r.published&&!r.pending).map(r=><option key={r.employeeId} value={r.employeeId}>{names[r.employeeId]}</option>)}</select><Button variant="secondary" disabled={busy||!rows.some(r=>r.employeeId===selected&&!r.published&&!r.pending)} onClick={()=>onPublish(selected)}>Publish selected employee</Button></div>}
 {rows.some(r=>r.canApprove)&&<label className="block">Override review note<input value={reviewNote} onChange={e=>onReviewNote(e.target.value)} className="m-2 rounded border p-2 dark:bg-slate-800"/></label>}

 {rows.map(r=><div key={r.employeeId} className="border-t py-2"><strong>{names[r.employeeId]??'Employee'}</strong> · {r.version?`v${r.version}`:'Unpublished'} · {r.pending?'Override pending':r.decision==='reject'?'Override rejected':r.published?'Published':'Draft changes / unpublished'}{r.frozen?' · HR-finalized version retained':''}
 <VersionHistory key={week+r.employeeId+r.version} employee={r.employeeId} week={week}/>
 {r.pending&&<details className="my-2"><summary>Review original and proposed schedule</summary><div className="grid gap-3 sm:grid-cols-2"><div><strong>Effective v{r.activeVersion}</strong>{r.before?.map((x,i)=><p key={i}>{entry(x)}</p>)}</div><div><strong>Proposed v{r.version}</strong>{r.after?.map((x,i)=><p key={i}>{entry(x)}</p>)}</div></div><p className="my-2">Reason: {r.reference}</p>{r.canApprove&&<div className="flex gap-2"><Button disabled={busy} onClick={()=>onReview(r.publicationId!,true)}>Approve override</Button><Button variant="secondary" disabled={busy} onClick={()=>onReview(r.publicationId!,false)}>Reject override</Button></div>}</details>}</div>)}
 </details>;
}

function VersionHistory({employee,week}:{employee:string;week:string}){const [rows,setRows]=useState<PublicationHistory[]|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);const fetchHistory=async()=>{if(loading)return;setLoading(true);setError('');try{setRows(await getPublicationHistory(employee,week));}catch(e){setError((e as Error).message);}finally{setLoading(false);}};return <details className="my-2" onToggle={e=>{if(e.currentTarget.open&&rows===null&&!loading)void fetchHistory();}}><summary className="cursor-pointer">Version &amp; audit history</summary>{loading&&<p>Loading history…</p>}{error&&<p role="alert">{error} <button onClick={fetchHistory} className="underline">Retry</button></p>}{rows?.length===0&&<p>No published versions.</p>}{rows?.map(r=><div key={r.version} className="my-2 rounded bg-slate-500/10 p-2"><strong>Version {r.version}</strong> · {r.from}–{r.to}<p>{r.publisher} · {new Date(r.publishedAt).toLocaleString('en-PH',{timeZone:'Asia/Manila'})} Philippine time</p><p>{r.note}</p><p>{r.approvalRequired?`HR override: ${r.decision||'Pending'}`:'Published'}</p></div>)}</details>;}
