import React from 'react';
import type {SchedulePublication,ScheduleEntry} from '../../services/schedulePublicationService';
import Button from '../ui/Button';
const entry=(x:ScheduleEntry)=>`${x.date}: ${x.kind==='rest'?'Rest Day':x.kind==='no_schedule'?'Leave / No Schedule':x.flexible?`Flexible · ${(x.paidMinutes??0)/60} paid hours`:`${x.start}–${x.end}${x.endDayOffset===1?' (+1 day)':''}`} · ${x.name}`;
export default function SchedulePublicationStatus({rows,names,onReview,busy,onPublish}:{rows:SchedulePublication[];names:Record<string,string>;onReview:(id:string,approve:boolean)=>void;busy:boolean;onPublish?:(employeeId:string)=>void}){
 return <details className="mb-4 rounded border p-3 text-sm"><summary>Schedule versions · {rows.filter(r=>r.published).length}/{rows.length} current · {rows.filter(r=>r.pending).length} pending overrides</summary><p className="my-2">Blank days remain Missing Schedule. Published versions cover the displayed Monday–Sunday dates. After HR finalizes, draft edits wait for an independent HR Manager’s override approval and a linked timekeeping version.</p>
 {rows.map(r=><div key={r.employeeId} className="border-t py-2"><strong>{names[r.employeeId]??'Employee'}</strong> · {r.version?`v${r.version}`:'Unpublished'} · {r.pending?'Override pending':r.decision==='reject'?'Override rejected':r.published?'Published':'Draft changes / unpublished'}{r.frozen?' · HR-finalized version retained':''}{onPublish&&!r.published&&!r.pending&&<Button className="ml-3" disabled={busy} onClick={()=>onPublish(r.employeeId)}>Publish employee week</Button>}
 {r.pending&&<details className="my-2"><summary>Review original and proposed schedule</summary><div className="grid gap-3 sm:grid-cols-2"><div><strong>Effective v{r.activeVersion}</strong>{r.before?.map((x,i)=><p key={i}>{entry(x)}</p>)}</div><div><strong>Proposed v{r.version}</strong>{r.after?.map((x,i)=><p key={i}>{entry(x)}</p>)}</div></div><p className="my-2">Reason: {r.reference}</p>{r.canApprove&&<div className="flex gap-2"><Button disabled={busy} onClick={()=>onReview(r.publicationId!,true)}>Approve override</Button><Button variant="secondary" disabled={busy} onClick={()=>onReview(r.publicationId!,false)}>Reject override</Button></div>}</details>}</div>)}
 </details>;
}
