import React,{useEffect,useState} from 'react';
import {supabase} from '../../services/supabaseClient';
import {dateKey} from '../../services/scheduleStatuses';
import {csvCell} from '../../services/pulseQuestionRules';

export default function SuspensionStatusReport(){
 const [month,setMonth]=useState(()=>dateKey(new Date()).slice(0,7)),[rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let active=true;setLoading(true);setRows([]);setError('');if(!/^\d{4}-\d{2}$/.test(month)){setLoading(false);return;}
 const [year,m]=month.split('-').map(Number);supabase.rpc('get_suspension_status_report',{p_from:month+'-01',p_to:dateKey(new Date(year,m,0))}).then(({data,error})=>{if(!active)return;if(error)setError(error.message);else setRows(data||[]);setLoading(false);});return()=>{active=false;};},[month]);
 const exportRows=()=>{const body=[['Date','Employee','Business Unit','Department','Status','Reason','Changed by','Changed at'],...rows.map(r=>[r.work_date,r.employeeName,r.businessUnit,r.department,'Suspended',r.reason,r.createdByName,r.created_at])].map(r=>r.map(v=>csvCell(String(v??''))).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+body],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`suspension-status-${month}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <details className="my-4 rounded-xl border border-cyan-300 p-4"><summary className="cursor-pointer font-semibold">Suspension status report · separate from absences</summary><p className="my-2 text-sm">Suspended dates do not require punches and are excluded from attendance violations. This report does not set payroll treatment.</p><label>Month <input className="rounded border bg-transparent p-2" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button disabled={loading||!!error||!rows.length} onClick={exportRows} className="ml-3 min-h-11 underline disabled:opacity-50">Export suspension dates</button>{error&&<p role="alert">{error}</p>}{loading?<p>Loading suspension dates…</p>:<><p>{rows.length} suspension dates in your permitted scope.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Date','Employee','Business Unit','Reason','Changed by'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-2">{r.work_date}</td><td>{r.employeeName}</td><td>{r.businessUnit}</td><td>{r.reason}</td><td>{r.createdByName}</td></tr>)}</tbody></table></div></>}</details>;
}
