import React,{useEffect,useRef,useState} from 'react';
import Button from '../../components/ui/Button';
import SignaturePad,{SignaturePadRef} from '../../components/ui/SignaturePad';
import {actNteDeduction,downloadNteAtd,generateNteAtd,getNteDeductionContext,ntePeso,openNteAtdDocument,uploadGeneratedNteAtd,uploadSignedNteAtd,type NTEContext,type NTEDeduction} from '../payroll/nteDeductions';

const control='mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-900';
const steps=['NOD acknowledged','ATD generated','Employee signed','HR verified','Finance approved','Available for payroll'];
function progress(d:NTEDeduction|null,nod:boolean){if(!nod)return 0;if(!d)return 1;if(d.financeApprovedAt)return 6;if(d.hrVerifiedAt)return 4;if(d.employeeSignedAt)return 3;return 2;}
function Stepper({current}:{current:number}){return <ol className="grid gap-2 sm:grid-cols-3 xl:grid-cols-6">{steps.map((label,index)=>{const done=current>index;const active=current===index+1;return <li key={label} className={`rounded-xl border p-3 text-center text-xs font-semibold ${done?'border-emerald-300 bg-emerald-50 text-emerald-800':active?'border-amber-300 bg-amber-50 text-amber-900':'border-slate-200 text-slate-500'}`}><span className="mb-1 block text-lg">{done?'✓':index+1}</span>{label}</li>;})}</ol>;}

export default function NTEDeductionPanel({nteId,refresh=0}:{nteId:string;refresh?:number}){
 const [ctx,setCtx]=useState<NTEContext|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [version,setVersion]=useState(0);
 const [method,setMethod]=useState<'months'|'cutoffs'>('cutoffs');const [term,setTerm]=useState(6);const [firstDate,setFirstDate]=useState('');const [reason,setReason]=useState('');const [consent,setConsent]=useState(false);const sig=useRef<SignaturePadRef>(null);
 const load=()=>getNteDeductionContext(nteId).then(setCtx);
 useEffect(()=>{let active=true;setError('');void getNteDeductionContext(nteId).then(value=>{if(active){setCtx(value);const d=value.debt;if(d){setMethod(d.repaymentMethod||'cutoffs');setTerm(d.termCount||6);setFirstDate(d.firstDeductionDate||'');}}}).catch(cause=>{if(active)setError((cause as Error).message);});return()=>{active=false;};},[nteId,refresh,version]);
 if(ctx&&ctx.resolutionType!=='Salary Deduction')return null;
 const d=ctx?.debt||null;const current=progress(d,Boolean(ctx?.nodAcknowledged));
 async function run(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();await load();setVersion(v=>v+1);setReason('');}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
 async function generate(){await run(async()=>{const generated=await generateNteAtd(nteId,method,term,firstDate,reason);try{await uploadGeneratedNteAtd(generated);}catch(cause){throw new Error(`ATD version ${generated.atdVersion} was saved, but the PDF could not be attached: ${(cause as Error).message}. Use Retry document generation.`);}});}
 async function upload(file:File){if(!d)return;await run(()=>uploadSignedNteAtd(d,file));}
 return <section className="space-y-4 rounded-2xl border border-violet-200 bg-white p-4 dark:border-violet-900 dark:bg-slate-900">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-bold">NTE payroll deduction</h3><p className="text-sm text-slate-500">Acknowledgment is receipt—not consent. Payroll remains blocked until the signed ATD passes HR and Finance review.</p></div><span className={`rounded-full px-3 py-1 text-sm font-semibold ${ctx?.workflowStatus==='Approved for Payroll'||ctx?.workflowStatus==='Completed'?'bg-emerald-100 text-emerald-800':ctx?.workflowStatus==='Blocked'||ctx?.workflowStatus==='Rejected'?'bg-red-100 text-red-800':'bg-amber-100 text-amber-900'}`}>{ctx?.workflowStatus||'Loading…'}</span></div>
  {error&&<p role="alert" className="rounded-xl border border-red-300 bg-red-50 p-3 text-red-800">{error}</p>}
  {!ctx?<p role="status">Loading protected deduction workflow…</p>:<>
   <Stepper current={current}/>
   {d?.canViewSensitive&&<><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-violet-50 p-4"><p className="text-sm">Current balance</p><strong className="text-2xl">{ntePeso(d.currentBalance)}</strong></div><div className="rounded-2xl bg-violet-50 p-4"><p className="text-sm">This payroll deduction</p><strong className="text-2xl">{ntePeso(d.installment)}</strong></div><div className="rounded-2xl bg-violet-50 p-4"><p className="text-sm">Remaining after payroll</p><strong className="text-2xl">{ntePeso(Math.max(0,Number(d.currentBalance)-Number(d.installment)))}</strong></div></div>
    <dl className="grid gap-3 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-2 dark:bg-slate-800"><div><dt>Employee</dt><dd className="font-semibold">{d.employeeName}</dd></div><div><dt>NTE number</dt><dd className="font-semibold">{d.nteNumber}</dd></div><div><dt>Approved deduction</dt><dd className="font-semibold">{ntePeso(d.approvedAmount)}</dd></div><div><dt>Repayment term</dt><dd className="font-semibold">{d.termCount} {d.repaymentMethod} · {d.cutoffCount} cutoffs</dd></div><div><dt>First deduction</dt><dd className="font-semibold">{d.firstDeductionDate}</dd></div><div><dt>Expected final deduction</dt><dd className="font-semibold">{d.expectedFinalDate}</dd></div></dl>
   </>}
   {d&&<div className="flex flex-wrap gap-3"><Button variant="secondary" onClick={()=>downloadNteAtd(d)}>Download ATD v{d.atdVersion}</Button>{d.generatedDocumentPath&&<Button variant="secondary" onClick={()=>void openNteAtdDocument(d.generatedDocumentPath!)}>Open stored ATD</Button>}{d.signedDocumentPath&&<Button variant="secondary" onClick={()=>void openNteAtdDocument(d.signedDocumentPath!)}>Open signed ATD</Button>}{!d.generatedDocumentPath&&ctx.canGenerate&&<Button variant="secondary" disabled={busy} onClick={()=>void run(()=>uploadGeneratedNteAtd(d))}>Retry document generation</Button>}</div>}
   {ctx.canGenerate&&ctx.nodAcknowledged&&(!d||d.workflowStatus!=='Completed')&&<div className="rounded-xl border p-4"><h4 className="font-bold">{d?'Revise the Authority to Deduct schedule':'Generate Authority to Deduct'}</h4><p className="text-sm text-slate-500">Changing amount or schedule invalidates the current pending version and requires a new signature, HR verification, and Finance approval.</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><label>Repay over<select className={control} value={method} onChange={e=>setMethod(e.target.value as 'months'|'cutoffs')}><option value="months">Number of months</option><option value="cutoffs">Number of payroll cutoffs</option></select></label><label>{method==='months'?'Months':'Payroll cutoffs'}<input className={control} type="number" min="1" max="120" value={term} onChange={e=>setTerm(Number(e.target.value))}/></label><label>First deduction date<input className={control} type="date" value={firstDate} onChange={e=>setFirstDate(e.target.value)}/></label></div><label className="mt-3 block">Generation / revision reason<textarea className={control} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button className="mt-3" variant={d?'secondary':'primary'} disabled={busy||!firstDate||reason.trim().length<3} onClick={()=>void generate()}>{d?'Generate revised ATD':'Generate Authority to Deduct'}</Button></div>}
   {d?.authorityStatus==='Awaiting Employee Signature'&&ctx.isEmployee&&d.generatedDocumentPath&&<div className="rounded-xl border border-amber-300 bg-amber-50 p-4"><h4 className="font-bold">Sign the Authority to Deduct</h4><label className="mt-3 flex items-start gap-2"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I authorize the deduction and repayment schedule shown in ATD version {d.atdVersion}.</label><SignaturePad ref={sig}/><Button disabled={busy||!consent} onClick={()=>void run(()=>actNteDeduction(nteId,'digital_sign','Employee signed the current Authority to Deduct',{consent:'I authorize the stated deduction',signature:sig.current?.getSignatureDataUrl()}))}>Sign Authority to Deduct</Button><label className="ml-3 inline-flex cursor-pointer text-sm font-semibold text-violet-700 underline">Or upload signed ATD<input className="sr-only" type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label></div>}
   {d?.authorityStatus==='Awaiting Employee Signature'&&ctx.isEmployee&&!d.generatedDocumentPath&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">The generated ATD document is missing. Finance must retry document generation before you can sign.</p>}
   {d?.authorityStatus==='Awaiting Employee Signature'&&!ctx.isEmployee&&(ctx.canHrVerify||ctx.canGenerate)&&<div className="rounded-xl border border-amber-300 bg-amber-50 p-4"><p>The employee has not separately signed the current ATD.</p><Button className="mt-3" disabled={busy} onClick={()=>void run(()=>actNteDeduction(nteId,'request_signature','Current Authority to Deduct sent for employee signature'))}>Request employee signature</Button></div>}
   {d?.authorityStatus==='Signed — Awaiting HR Verification'&&ctx.canHrVerify&&<div className="rounded-xl border p-4"><label>HR verification reason<textarea className={control} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Confirm signature, document, legal basis, and current version"/></label><div className="mt-3 flex flex-wrap gap-3"><Button disabled={busy||reason.trim().length<3} onClick={()=>void run(()=>actNteDeduction(nteId,'verify',reason))}>Verify signed document</Button><Button variant="secondary" disabled={busy||reason.trim().length<3} onClick={()=>void run(()=>actNteDeduction(nteId,'return',reason))}>Return for correction</Button></div></div>}
   {d?.authorityStatus==='HR Verified — Awaiting Finance Approval'&&ctx.canFinanceApprove&&<div className="rounded-xl border p-4"><label>Finance approval reference / reason<textarea className={control} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Confirm approved amount, remaining balance, schedule, and payroll scope"/></label><div className="mt-3 flex flex-wrap gap-3"><Button disabled={busy||reason.trim().length<3} onClick={()=>void run(()=>actNteDeduction(nteId,'finance_approve',reason))}>Approve for payroll</Button><Button variant="secondary" disabled={busy||reason.trim().length<3} onClick={()=>void run(()=>actNteDeduction(nteId,'return',reason))}>Return for correction</Button></div></div>}
   {d?.schedule&&d.schedule.length>0&&<details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Repayment timeline · {d.remainingCutoffs} cutoffs remaining</summary><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr>{['Payroll date','Scheduled','Actual','Balance after','Status'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{d.schedule.map(row=><tr className="border-t" key={row.id}><td className="p-2">{row.payroll_date}</td><td className="p-2">{ntePeso(row.scheduled_amount)}</td><td className="p-2">{row.actual_amount?ntePeso(row.actual_amount):'—'}</td><td className="p-2">{ntePeso(row.balance_after)}</td><td className="p-2">{row.status}</td></tr>)}</tbody></table></div></details>}
   {d?.audit&&d.audit.length>0&&<details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Immutable audit history</summary>{d.audit.map((row,index)=><p className="mt-2 rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800" key={`${row.at}-${index}`}><strong>{row.action}</strong> · {row.actor} ({row.role})<br/>{row.reason} · {new Date(row.at).toLocaleString('en-PH')}</p>)}</details>}
  </>}
 </section>;
}
