import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {build} from 'esbuild';
const compiled=await build({entryPoints:['modules/payroll/actualAttendanceImport.ts'],bundle:true,platform:'node',format:'esm',write:false,external:['exceljs']});
const {normalizeAttendance,attendanceCsv,strictDate,attendanceStamp}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
assert.throws(()=>strictDate('2026-02-30'));
assert.throws(()=>strictDate('09/10/2026'));
assert.throws(()=>attendanceStamp('2026-08-26 24:00'));
assert.throws(()=>normalizeAttendance([['DEMO-001','Fixture','2026-08-26','2026-08-26 09:00']],'Fixture'));
assert.ok(attendanceCsv().includes('Employee ID*'));assert.ok(!attendanceCsv().includes('DEMO'));
const overnight=normalizeAttendance([['00001','Fixture','2026-08-26','2026-08-26 22:00','','','2026-08-27 06:00']],'Fixture')[0];
assert.equal(overnight.events[1].timestamp,'2026-08-27T06:00:00+08:00');
const db=new PGlite();
await db.exec(`create schema private;create schema auth;create role anon;create role authenticated;
create function auth.uid() returns uuid language sql as $$select '00000000-0000-4000-8000-000000000001'::uuid$$;
create function public.current_hris_user_id() returns uuid language sql as $$select auth.uid()$$;
create function private.payroll_actor_id() returns uuid language sql as $$select auth.uid()$$;
create function private.historical_reconciliation_user(uuid) returns boolean language sql as $$select current_setting('test.allowed',true)='yes'$$;
create function private.payroll_time_permission(uuid,text) returns boolean language sql as $$select $1='00000000-0000-4000-8000-000000000002'::uuid$$;
create function private.is_schedule_suspended(uuid,date) returns boolean language sql as $$select current_setting('test.suspended',true)='yes'$$;
create function private.ob_for_day(uuid,date) returns jsonb language sql as $$select case when current_setting('test.ob',true)='yes' then '{}'::jsonb else null end$$;
create function private.attendance_exception(uuid,date) returns jsonb language sql as $$select jsonb_build_object('requires_clock',current_setting('test.exempt',true) is distinct from 'yes')$$;
create table public.payroll_access_scopes(id uuid primary key,business_unit_id uuid,name text);
create table public.hris_users(id uuid primary key,employee_id text,full_name text,business_unit_id uuid,date_hired date,end_date date,is_duplicate boolean);
create table public.time_events(id uuid default gen_random_uuid(),employee_id uuid,timestamp timestamptz,type text,source text,timezone text,created_by uuid,notes text);
create table public.payroll_schedule_freezes(employee_id uuid,date_from date,date_to date);
create table public.attendance_clock_sessions(employee_id uuid,work_date date);
create table public.payroll_calendar_rules(scope_id uuid,effective_from date,calendar jsonb,policy_ref text,created_at timestamptz default now());
insert into public.payroll_calendar_rules(scope_id,effective_from,calendar,policy_ref) values(null,'2000-01-01','[{"releaseDay":5,"startDay":11,"endDay":25,"startMonthOffset":-1,"endMonthOffset":-1},{"releaseDay":20,"startDay":26,"endDay":10,"startMonthOffset":-1,"endMonthOffset":0}]','Shared calendar');
insert into public.payroll_access_scopes values('00000000-0000-4000-8000-000000000002','00000000-0000-4000-8000-000000000003','Fixture');
insert into public.hris_users values('00000000-0000-4000-8000-000000000004','00001','Fixture','00000000-0000-4000-8000-000000000003','2020-01-01',null,false);
set test.allowed='yes';`);
await db.exec(fs.readFileSync('supabase/real_attendance_import.sql','utf8'));
const scope='00000000-0000-4000-8000-000000000002';
let calendar=(await db.query('select public.get_normal_payroll_periods($1,2026) c',[scope])).rows[0].c;
assert.deepEqual(calendar.find(p=>p.releaseDate==='2026-09-20'),{releaseDate:'2026-09-20',from:'2026-08-26',to:'2026-09-10',policy:'Shared calendar',override:false});
await db.query("insert into public.payroll_calendar_rules(scope_id,effective_from,calendar,policy_ref) values($1,'2026-09-11','[{\"releaseDay\":6,\"startDay\":11,\"endDay\":25,\"startMonthOffset\":-1,\"endMonthOffset\":-1},{\"releaseDay\":21,\"startDay\":26,\"endDay\":10,\"startMonthOffset\":-1,\"endMonthOffset\":0}]','Future approved override')",[scope]);
calendar=(await db.query('select public.get_normal_payroll_periods($1,2026) c',[scope])).rows[0].c;
assert.ok(calendar.find(p=>p.releaseDate==='2026-09-20'&&!p.override));assert.ok(calendar.find(p=>p.releaseDate==='2026-10-06'&&p.override));assert.ok(!calendar.find(p=>p.releaseDate==='2026-10-05'));
const call=async(rows,confirm=false)=>(await db.query('select public.import_actual_attendance($1,$2,$3,$4,$5,$6) as result',[scope,'2026-08-26','2026-09-10','fixture.csv',JSON.stringify(rows),confirm])).rows[0].result;
const count=async()=>(await db.query('select count(*)::int n from public.time_events')).rows[0].n;
let result=await call([overnight]);assert.equal(result.errors.length,0);assert.equal(result.ready,1);assert.equal(await count(),0);
result=await call([overnight],true);assert.equal(result.confirmed,true);assert.equal(await count(),2);
result=await call([overnight],true);assert.equal(result.alreadyImported,true);assert.equal(await count(),2);
result=await call([{...overnight,reference:'Changed filename or metadata'}],true);assert.equal(result.duplicates,1);assert.equal(await count(),2);
const conflict={...overnight,events:[{type:'ClockIn',timestamp:'2026-08-26T21:00:00+08:00'}]};
result=await call([conflict]);assert.match(result.errors[0].message,/conflicts/);await assert.rejects(()=>call([conflict],true),/Correct all rows/);assert.equal(await count(),2);
await db.exec("set test.allowed='no'");await assert.rejects(()=>call([overnight]),/authorized BOD/);
await db.exec("set test.allowed='yes';insert into public.payroll_schedule_freezes values('00000000-0000-4000-8000-000000000004','2026-09-01','2026-09-10')");
const locked={...overnight,workDate:'2026-09-01',events:[{type:'ClockIn',timestamp:'2026-09-01T09:00:00+08:00'}]};
result=await call([locked]);assert.match(result.errors[0].message,/locked/);
const incomplete={...overnight,workDate:'2026-08-28',events:[{type:'ClockIn',timestamp:'2026-08-28T09:00:00+08:00'}]};
result=await call([incomplete]);assert.equal(result.errors.length,0);assert.ok(result.rows[0].warnings.length);
for(const [flag,message] of [['suspended',/suspension/],['ob',/Official Business/],['exempt',/clock-exempt/]]){
 await db.exec(`set test.${flag}='yes'`);result=await call([incomplete]);assert.match(result.errors[0].message,message);await db.exec(`set test.${flag}='no'`);
}
// Use the actual production interpreter with persisted imported evidence, not a mock calculation.
const extract=(path,name,delimiter)=>{const sql=fs.readFileSync(path,'utf8');const start=sql.toLowerCase().indexOf(`function private.${name}(`);assert.ok(start>=0);const open=sql.indexOf(delimiter,start);const end=sql.indexOf(delimiter,open+delimiter.length);return 'create or replace '+sql.slice(start,end+delimiter.length)+';';};
await db.exec(extract('supabase/migrations/20260906112648_payroll_schedule_versions.sql','payroll_schedule_validate','$$'));
await db.exec(extract('supabase/migrations/20260907015502_confirmed_hr_payroll_rules.sql','interpret_payroll_time','$function$'));
const day=normalizeAttendance([['00001','Fixture','2026-08-29','2026-08-29 09:00','2026-08-29 12:00','2026-08-29 13:00','2026-08-29 18:00']],'Fixture')[0];
await call([day],true);
const emp='00000000-0000-4000-8000-000000000004';
const source={employees:[{id:emp,name:'Fixture',hireDate:'2020-01-01',status:'Active'}],rules:[{id:'fixture-rule',revision:1,effective_from:'2026-01-01',effective_to:'2026-12-31',config:{holidayCoverageConfirmed:true,splitShiftConfirmed:true,restTemplates:[],meals:{fixture:'12:00'}}}],shifts:[{id:'fixture-shift',employeeId:emp,date:'2026-08-29',templateId:'fixture',start:'09:00',end:'18:00',breakMinutes:60,kind:'work',endDayOffset:0,paidMinutes:480,published:true}],scheduleDays:[{employeeId:emp,date:'2026-08-29',status:'published'}],leave:[],ot:[],holidays:[],wfh:[],leavePolicies:[]};
source.events=(await db.query(`select id,"employee_id" as "employeeId",timestamp,case type when 'ClockIn' then 'CLOCK_IN' when 'ClockOut' then 'CLOCK_OUT' when 'BreakStart' then 'START_BREAK' else 'END_BREAK' end type,source from public.time_events where timestamp>='2026-08-29T00:00:00+08:00' and timestamp<'2026-08-30T00:00:00+08:00' order by timestamp`)).rows;
const interpret=async()=>(await db.query("select private.interpret_payroll_time($1,'2026-08-29','2026-08-29') r",[JSON.stringify(source)])).rows[0].r.rows[0];
let calculated=await interpret();assert.equal(calculated.regularMinutes,480);assert.equal(calculated.ready,true,JSON.stringify(calculated.issues));assert.equal(calculated.actualOtMinutes,0);
source.events.at(-1).timestamp='2026-08-29T19:00:00+08:00';calculated=await interpret();assert.equal(calculated.actualOtMinutes,0);assert.equal(calculated.ready,false);assert.ok(calculated.issues.some(i=>i.includes('outside the reviewed schedule')));
await db.exec('set role anon');await assert.rejects(()=>call([overnight]),/permission denied/);
await db.exec('reset role;set role authenticated');await assert.rejects(()=>db.exec('select * from private.payroll_actual_imports'),/permission denied/);
await db.close();console.log('PASS: strict dates, overnight punches, preview without writes, confirmation, duplicate files/records, conflicts, locks, role guards and missing-punch warnings.');
