import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const source=readFileSync(new URL('../pages/ApprovalCenter.tsx',import.meta.url),'utf8');
const file=ts.createSourceFile('ApprovalCenter.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
let toggle;
function visit(node){if(ts.isCallExpression(node)&&node.expression.getText(file)==='setExpanded'&&node.arguments[0]?.getText(file).includes('current === group.kind'))toggle=node.arguments[0].getText(file);ts.forEachChild(node,visit);}visit(file);
assert.ok(toggle);const apply=vm.runInNewContext('('+toggle+')',{group:{kind:'pan'}});
assert.equal(apply(null),'pan');assert.equal(apply('pan'),null);assert.equal(apply('wfh'),'pan');
assert.doesNotMatch(source,/setExpanded\(preferred\)|Pending approval categories|aria-label="Request type"/);
console.log('PASS: row toggle opens/closes; no automatic polling expansion or category filter navigation.');
