// Run locally with node tests/approvalUiBrowserHarness.mjs, then open localhost:4174.
// Uses the actual components with isolated fixture hooks; never calls production APIs.
import {build} from 'esbuild';
import {createServer} from 'node:http';
import {fixture,fixturePlugin,attendanceFixture,panFixture} from './approvalUiFixtures.mjs';
const result=await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import {BrowserRouter,Routes,Route,Link} from 'react-router-dom';import Inbox from './components/dashboard/ApprovalWidget';import Center from './pages/ApprovalCenter';import PANModal from './components/employees/PANModal';
const revive=(key,value)=>['createdAt','effectiveDate','date','startDate','endDate','submittedAt','submissionDate','dateNeeded'].includes(key)&&typeof value==='string'?new Date(value):value;
globalThis.inboxFixture=JSON.parse(${JSON.stringify(JSON.stringify(fixture))},revive);globalThis.attendanceFixture=${JSON.stringify([attendanceFixture])};const pan=JSON.parse(${JSON.stringify(JSON.stringify(panFixture))},revive);
sessionStorage.setItem('approval-view-v1:test',JSON.stringify({filters:{kind:'wfh',search:'stale hidden filter'},expanded:'wfh',scroll:5000,savedAt:Date.now()}));
const noop=()=>{};function Review(){const [open,setOpen]=React.useState(true);return <><Link to="/approvals">Return to Approval Center</Link><PANModal isOpen={open} onClose={()=>setOpen(false)} pan={pan} templates={[]} employees={[]} approvers={[]} businessUnits={[]} onSaveDraft={async()=>pan} onSendForAcknowledgement={async()=>pan} onAcknowledge={noop} onDownloadPdf={noop} onApprove={noop} onReject={noop}/></>}
createRoot(document.getElementById('root')).render(<BrowserRouter><div className="mx-auto max-w-[1500px] p-6"><nav className="mb-6 flex gap-6"><Link to="/dashboard">Dashboard</Link><Link to="/approvals">All approvals</Link><Link to="/employees/pan?review=pan-preview">PAN preview</Link></nav><Routes><Route path="/dashboard" element={<Inbox/>}/><Route path="/employees/pan" element={<Review/>}/><Route path="*" element={<Center/>}/></Routes></div></BrowserRouter>);`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,platform:'browser',format:'iife',plugins:[fixturePlugin()]});
const html='<!doctype html><html lang="en" class="dark"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Approval UI fixture verification</title><script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={darkMode:"class"}</script></head><body class="bg-slate-900 text-slate-100"><div id="root"></div><script src="/app.js"></script></body></html>';
createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/app.js'?'text/javascript':'text/html');res.end(req.url==='/app.js'?result.outputFiles[0].text:html)}).listen(4174,'0.0.0.0',()=>console.log('Approval fixture harness listening on :4174'));
