import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createServer} from 'vite';
import react from '@vitejs/plugin-react';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright');
import {createAssetMaintenanceFixture,id} from './assetMaintenanceFixture.mjs';
const db=await createAssetMaintenanceFixture();
const methods={ops_workspace:['p_unit'],ops_save_template:['p_id','p_unit','p_kind','p_content','p_revision','p_publish'],ops_assign:['p_unit','p_version','p_selection','p_due','p_priority','p_instructions','p_attachments','p_verify'],import_assets_batch:['p_rows']};
const harness=`import React from 'react';import {createRoot} from 'react-dom/client';import {BrowserRouter} from 'react-router-dom';import {AuthContext} from '/context/AuthContext.tsx';import {PermissionsContext} from '/context/PermissionsContext.tsx';import {SettingsContext} from '/context/SettingsContext.tsx';import AssetManagement from '/pages/employees/AssetManagement.tsx';import OperationsStation from '/pages/OperationsStation.tsx';const user={id:window.__TEST_ACTOR,name:'BOD',email:'bod@example.test',businessUnitId:window.__TEST_UNIT};const assetPage=location.pathname.includes('assets');const permission={authorized:true,roles:['Board of Director'],dataScope:{type:window.__TEST_SCOPE||'GLOBAL'},features:{Assets:window.__TEST_SCOPE?['view']:['manage']}};createRoot(document.getElementById('root')).render(React.createElement(BrowserRouter,null,React.createElement(AuthContext.Provider,{value:{user,loading:false,authError:null}},React.createElement(PermissionsContext.Provider,{value:{effectiveRbac:permission,loadingPermissions:false,authorizationError:null}},React.createElement(SettingsContext.Provider,{value:{settings:{},approverConfigs:{}}},React.createElement(assetPage?AssetManagement:OperationsStation))))));`;
const server=await createServer({configFile:false,root:process.cwd(),plugins:[react(),{name:'asset-test',configureServer(s){s.middlewares.use(async(req,res,next)=>{if(req.url?.startsWith('/__test-')){res.setHeader('Content-Type','text/html');res.end(await s.transformIndexHtml(req.url,'<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><script src="/__tailwind.js"></script></head><body style="margin:0;padding:24px;background:#f1f5f9"><div id="root"></div><script type="module" src="/__asset-test.tsx"></script></body></html>'));}else if(req.url==='/__tailwind.js'){res.setHeader('Content-Type','text/javascript');res.end(fs.readFileSync('/tmp/tng-ops-tailwind.js'));}else next();});},resolveId(source){if(source==='/__asset-test.tsx')return '\0asset-test.tsx';},load(source){if(source==='\0asset-test.tsx')return harness;}}],define:{'import.meta.env.VITE_SUPABASE_URL':JSON.stringify('https://asset-test.invalid'),'import.meta.env.VITE_SUPABASE_ANON_KEY':JSON.stringify('test-key')},server:{host:'127.0.0.1',port:3191,strictPort:true}});
await server.listen();const browser=await chromium.launch({headless:true,executablePath:process.env.TNG_TEST_CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});let queue=Promise.resolve();const errors=[];
async function pageFor(actor=10,scope='',viewport={width:1440,height:1000}){const context=await browser.newContext({viewport,acceptDownloads:true});await context.addInitScript(({actor,scope,unit})=>{window.__TEST_ACTOR=actor;window.__TEST_SCOPE=scope;window.__TEST_UNIT=unit;},{actor:id(actor),scope,unit:id(1)});const page=await context.newPage();page.on('pageerror',e=>(errors.push(e.message),console.error('Page error:',e.message)));page.on('dialog',d=>d.dismiss());await page.route('https://asset-test.invalid/**',async route=>{const req=route.request(),url=new URL(req.url()),name=url.pathname.split('/').pop();const headers={'access-control-allow-origin':'*','access-control-allow-headers':'*'};if(req.method()==='OPTIONS'){await route.fulfill({status:200,headers});return;}queue=queue.then(async()=>{try{await db.exec(`reset role;set test.actor='${id(actor)}';set role authenticated`);let result;
 if(url.pathname.includes('/rpc/')){
  if(name==='get_accessible_hris_users'){await db.exec('reset role');result=(await db.query('select * from hris_users')).rows;}
  else if(methods[name]){const params=req.postDataJSON();result=(await db.query(`select public.${name}(${methods[name].map((_,i)=>'$'+(i+1)).join(',')}) r`,methods[name].map(k=>params[k]??null))).rows[0].r;}
  else throw new Error('Unhandled RPC '+name);
 }else if(req.method()==='GET'){
  if(['assets','business_units','hris_users','asset_assignments'].includes(name)){if(name!=='assets')await db.exec('reset role');result=(await db.query(`select * from public.${name}`)).rows;}
  else throw new Error('Unhandled table '+name);
 }else if(name==='assets'){
  const payload=req.postDataJSON();const keys=Object.keys(payload);assert.ok(keys.every(k=>/^[a-z_]+$/.test(k)));const values=Object.values(payload);const updated=url.searchParams.get('id')?.replace(/^eq\./,'');result=updated?(await db.query(`update assets set ${keys.map((k,i)=>k+'=$'+(i+1)).join(',')} where id=$${keys.length+1} returning *`,[...values,updated])).rows[0]:(await db.query(`insert into assets(${keys.join(',')}) values(${keys.map((_,i)=>'$'+(i+1)).join(',')}) returning *`,values)).rows[0];if(!result)throw new Error('Asset write not authorized');
 }else if(name==='audit_logs'){await db.exec('reset role');const p=req.postDataJSON();await db.query('insert into audit_logs(user_id,user_email,action,entity,entity_id,details) values($1,$2,$3,$4,$5,$6)',[p.user_id,p.user_email,p.action,p.entity,p.entity_id,p.details]);result=null;}
 else throw new Error('Unhandled mutation '+name);
 await route.fulfill({status:200,headers,contentType:'application/json',body:JSON.stringify(result)});
 }catch(e){await route.fulfill({status:400,headers,contentType:'application/json',body:JSON.stringify({message:e.message,code:e.code})});}});await queue;});return page;}
async function nav(p,label){const desktop=p.getByRole('navigation',{name:'Operations desktop navigation'});if(await desktop.isVisible())await desktop.getByRole('button',{name:label,exact:true}).click();else await p.getByRole('navigation',{name:'Operations workspace tools'}).getByRole('button',{name:label,exact:true}).click();}
try{
 const p=await pageFor();await p.goto('http://127.0.0.1:3191/__test-assets');await p.getByRole('button',{name:'Edit Office laptop',exact:true}).waitFor();await p.getByRole('button',{name:'Add New Asset',exact:true}).click();await p.getByLabel('Asset Tag',{exact:true}).fill('AC-001');await p.getByLabel('Asset Name',{exact:true}).fill('Bar air conditioner');await p.getByLabel('Business Unit',{exact:true}).selectOption(id(1));await p.getByLabel('Type',{exact:true}).selectOption('Equipment');await p.getByRole('checkbox',{name:'Requires maintenance',exact:true}).check();await p.getByRole('button',{name:'Create Asset',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});await p.reload();await p.getByRole('button',{name:'Edit Bar air conditioner',exact:true}).waitFor();await p.getByLabel('Maintenance',{exact:true}).selectOption('yes');assert.equal(await p.getByRole('button',{name:'Edit Office laptop',exact:true}).count(),0);
 const download=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Export CSV',exact:true}).click()]);const csv=fs.readFileSync(await download[0].path(),'utf8');assert.match(csv,/Requires Maintenance/);assert.match(csv,/"Yes"/);
 await p.getByRole('button',{name:'Edit Bar air conditioner',exact:true}).click();assert.equal(await p.getByRole('checkbox',{name:'Requires maintenance',exact:true}).isChecked(),true);await p.getByRole('checkbox',{name:'Requires maintenance',exact:true}).uncheck();await p.getByRole('button',{name:'Save Changes',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});await p.getByText('No assets found.',{exact:true}).waitFor();await p.getByLabel('Maintenance',{exact:true}).selectOption('no');await p.getByRole('button',{name:'Edit Bar air conditioner',exact:true}).click();await p.getByRole('checkbox',{name:'Requires maintenance',exact:true}).check();await p.getByRole('button',{name:'Save Changes',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});
 await p.getByRole('button',{name:'Batch Upload Assets',exact:true}).click();const templateDownload=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Download CSV Template',exact:true}).click()]);const template=fs.readFileSync(await templateDownload[0].path(),'utf8');assert.match(template,/requires_maintenance/);const header=template.replace(/^\uFEFF/,'').split(/\r?\n/)[0];const keys=header.split(',').map(k=>k.replace(/"/g,''));const row={asset_tag:'FREEZER-IMPORT',asset_name:'Imported freezer',asset_type:'Equipment',business_unit:'Unit A',purchase_date:'2026-10-10',requires_maintenance:'Yes'};await p.locator('input[type=file]').setInputFiles({name:'equipment.csv',mimeType:'text/csv',buffer:Buffer.from(header+'\n'+keys.map(k=>row[k]||'').join(','))});await p.getByRole('button',{name:'Import Validated Assets',exact:true}).click();await p.getByText('Successfully imported',{exact:true}).waitFor();await p.getByRole('button',{name:'Close',exact:true}).click();await p.getByLabel('Maintenance',{exact:true}).selectOption('yes');await p.getByRole('button',{name:'Edit Imported freezer',exact:true}).waitFor();await p.screenshot({path:'/tmp/tng-maintenance-assets.png',fullPage:true});
 await db.exec('reset role');await db.query("insert into assets(name,business_unit_id,asset_tag,type,requires_maintenance) values('Other unit freezer',$1,'BU-B','Equipment',true)",[id(2)]);
 await p.goto('http://127.0.0.1:3191/__test-operations');await p.getByLabel('Business-unit workspace').waitFor();await p.getByLabel('Business-unit workspace').selectOption(id(1));await nav(p,'Task Library');await p.getByRole('button',{name:'Create task',exact:true}).first().click();const options=await p.getByLabel('Linked maintenance asset').locator('option').allTextContents();assert.ok(options.includes('Bar air conditioner'));assert.ok(options.includes('Imported freezer'));assert.ok(!options.includes('Office laptop'));assert.ok(!options.includes('Other unit freezer'));await p.getByLabel('Title',{exact:true}).fill('Aircon filter cleaning');await p.getByLabel('Linked maintenance asset').selectOption({label:'Bar air conditioner'});await p.getByRole('button',{name:'Publish',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});
 await nav(p,'Assign Tasks');await p.getByLabel('Maintenance asset').selectOption({label:'Bar air conditioner'});const work=p.getByLabel('Published task or checklist',{exact:true});await work.waitFor();assert.deepEqual(await work.locator('option').allTextContents(),['Choose from library','Aircon filter cleaning · task v1']);await work.selectOption({label:'Aircon filter cleaning · task v1'});await p.getByRole('checkbox',{name:'BUM A BUM',exact:true}).check();await p.getByRole('button',{name:'Assign to 1',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});await p.reload();await nav(p,'Tasks');await p.getByRole('button',{name:'Team Tasks',exact:true}).click();await p.getByText('Aircon filter cleaning',{exact:true}).waitFor();
 const mobile=await pageFor(13,'HOME_ONLY',{width:390,height:844});await mobile.goto('http://127.0.0.1:3191/__test-assets');await mobile.getByRole('row').filter({hasText:'Bar air conditioner'}).waitFor();assert.equal(await mobile.getByRole('button',{name:/Edit /}).count(),0);assert.equal(await mobile.getByRole('button',{name:'Add New Asset',exact:true}).count(),0);assert.equal(await mobile.getByRole('row').filter({hasText:'Other unit freezer'}).count(),0);assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.screenshot({path:'/tmp/tng-maintenance-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('Maintenance browser passed: actual asset page create/edit/refresh, Equipment type, flag on/off, maintenance filter, CSV export + import template and imported flag, backend-filtered task asset selector, asset filter in assignment, assigned work persistence, scoped read-only mobile UI.');
}catch(e){console.error(e);for(const c of browser.contexts())for(const p of c.pages()){console.error((await p.locator('body').innerText()).slice(-2600));await p.screenshot({path:'/tmp/tng-assets-browser-failure.png',fullPage:true});}process.exitCode=1;}finally{await browser.close();await server.close();await db.close();}
