-- Transaction-only fixtures. No committed notifications, emails or personnel records.
begin;
set local statement_timeout='45s';
set local lock_timeout='5s';
do $$declare e record;m record;hr record;candidate record;bod record;outsider record;r uuid;ir uuid;n uuid;k uuid:=gen_random_uuid();policy text;payload jsonb;d jsonb;rev integer;nc integer;deadline timestamptz:=clock_timestamp()+interval '10 days';checks jsonb;
begin
 select h.id,h.auth_user_id,private.punch_direct_manager(h.id) manager into e from public.hris_users h where lower(h.status)='active' and h.auth_user_id is not null and private.punch_direct_manager(h.id) is not null order by (h.business_unit_id is distinct from (select business_unit_id from public.hris_users where id=private.punch_direct_manager(h.id))) desc limit 1;
 if e.id is null then raise exception 'No active direct-report fixture';end if;
 select id,auth_user_id into m from public.hris_users where id=e.manager;
 select id,auth_user_id into outsider from public.hris_users where lower(status)='active' and auth_user_id is not null and role='Employee' and id not in(e.id,m.id) limit 1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',e.auth_user_id,'role','authenticated')::text,true);
 payload:=jsonb_build_object('kind','absence','date',(clock_timestamp() at time zone 'Asia/Manila')::date+23,'category','Other','explanation','Transaction-only attendance review fixture','confirmed',true);
 r:=public.submit_attendance_issue(payload,gen_random_uuid());
 perform set_config('request.jwt.claims',jsonb_build_object('sub',m.auth_user_id,'role','authenticated')::text,true);
 perform public.review_attendance_issue(r,'details','Please explain the requested date.',1);
 if exists(select 1 from attendance_issues.hr_cases where request_id=r) then raise exception 'Clarification created a disciplinary case';end if;
 if (select clarification_message from attendance_issues.requests where id=r)<>'Please explain the requested date.' then raise exception 'Clarification message missing';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',e.auth_user_id,'role','authenticated')::text,true);
 if public.submit_attendance_issue(payload||'{"changesConfirmed":true,"explanation":"Revised employee explanation"}',k,r,2)<>r then raise exception 'Resubmission changed request ID';end if;
 if public.submit_attendance_issue(payload||'{"changesConfirmed":true,"explanation":"Revised employee explanation"}',k,r,2)<>r or (select revision from attendance_issues.requests where id=r)<>3 then raise exception 'Retry created a second revision';end if;
 if (select manager_id from attendance_issues.requests where id=r)<>m.id then raise exception 'Resubmission rerouted incorrectly';end if;
 if not exists(select 1 from attendance_issues.audit where request_id=r and action='edited and resubmitted' and previous->>'explanation'=payload->>'explanation' and new_value->>'explanation'='Revised employee explanation') then raise exception 'Prior revision lost';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',m.auth_user_id,'role','authenticated')::text,true);
 begin perform public.review_attendance_issue(r,'reject','Factual rejection for HR review',3);raise exception 'MISSING_CONFIRMATION_BYPASS';exception when others then if sqlerrm='MISSING_CONFIRMATION_BYPASS' then raise;end if;end;
 perform public.review_attendance_issue(r,'reject','Factual rejection for HR review',3,'Other',true);
 select incident_id into ir from attendance_issues.hr_cases where request_id=r;
 if ir is null or (select status::text from public.incident_reports where id=ir)<>'Draft' then raise exception 'Factual IR draft missing';end if;
 if exists(select 1 from public.ntes where incident_report_id=ir) then raise exception 'Rejection automatically created NTE';end if;
 if exists(select 1 from attendance_issues.exceptions where request_id=r) then raise exception 'Rejection approved attendance';end if;
 if (private.attendance_review_facts(e.id,(payload->>'date')::date)->>'eligible')::boolean then raise exception 'Pending HR review classified automatically';end if;
 if outsider.id is not null then
 perform set_config('request.jwt.claims',jsonb_build_object('sub',outsider.auth_user_id,'role','authenticated')::text,true);
 if jsonb_array_length(public.get_attendance_issues(r)->'rows')<>0 then raise exception 'Unrelated employee can read case';end if;
 begin perform public.get_attendance_case(r);raise exception 'PRIVATE_CASE_EXPOSED';exception when insufficient_privilege then null;end;
 end if;
 for candidate in select id,auth_user_id from public.hris_users where attendance_issues.hr_recipient(id) and id<>e.id loop
 perform set_config('request.jwt.claims',jsonb_build_object('sub',candidate.auth_user_id,'role','authenticated')::text,true);
 if attendance_issues.hr_access(r) and private.can_issue_nte() then hr:=candidate;exit;end if;
 end loop;
 if hr.id is null then raise exception 'Scoped HR fixture unavailable';end if;
 perform public.act_attendance_hr_case(r,'clarify',1,jsonb_build_object('reason','Please provide a factual written explanation.','deadline',deadline));
 begin perform public.act_attendance_hr_case(r,'draft',2,jsonb_build_object('reason','Must await response','facts','Verified facts','allegation','Proposed allegation'));raise exception 'CLARIFICATION_NTE_BYPASS';exception when others then if sqlerrm='CLARIFICATION_NTE_BYPASS' then raise;end if;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',e.auth_user_id,'role','authenticated')::text,true);
 perform public.act_attendance_hr_case(r,'respond',2,jsonb_build_object('reason','Additional employee explanation to HR.','link','https://example.com/evidence'));
 if (select status from attendance_issues.requests where id=r)<>'rejected' then raise exception 'Employee response erased manager rejection';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',hr.auth_user_id,'role','authenticated')::text,true);
 select id::text into policy from public.memos limit 1;
 if policy is null then raise exception 'Existing policy fixture needed';end if;
 perform public.act_attendance_hr_case(r,'draft',3,jsonb_build_object('reason','Reviewed employee facts and policy in rollback fixture','facts','Verified attendance timeline in test only','allegation','Proposed issue for explanation, not a conclusion','body','Transaction-only draft. Do not send.','policyIds',jsonb_build_array(policy),'deadline',deadline));
 perform public.act_attendance_hr_case(r,'edit_draft',4,jsonb_build_object('reason','Reviewed revised draft','facts','Updated verified timeline','allegation','Proposed allegation for review','body','Revised transaction-only draft.','policyIds',jsonb_build_array(policy),'deadline',deadline));
 select id,preferred_role_id,(select auth_user_id from public.hris_users h where h.id=a.id) auth_user_id into bod from public.get_eligible_nte_approvers(ir,e.id) a where has_bod_role and id<>hr.id limit 1;
 if bod.id is null then raise exception 'Eligible BOD fixture needed';end if;
 perform public.act_attendance_hr_case(r,'submit_nte',5,jsonb_build_object('reason','HR verified draft for designated review','confirmed',true,'approvers',jsonb_build_array(jsonb_build_object('userId',bod.id,'roleId',bod.preferred_role_id,'selectionReason','Transaction-only test'))));
 select nte_id into n from attendance_issues.hr_cases where request_id=r;
 if (select status::text from public.ntes where id=n)<>'PendingApproval' then raise exception 'Existing NTE approvals bypassed';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',e.auth_user_id,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 if public.get_attendance_case(r)->'case'->>'nte_id' is not null then raise exception 'Unsent NTE exposed to employee';end if;
 begin perform * from attendance_issues.requests limit 1;raise exception 'PRIVATE_TABLE_ACCESS_ALLOWED';exception when insufficient_privilege then null;end;
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',bod.auth_user_id,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 if not exists(select 1 from public.ntes where id=n) then raise exception 'Assigned approver cannot view NTE through RLS';end if;
 perform public.act_on_nte_approval(n,'approve','Designated approver rollback test');
 execute 'reset role';
 if (select status::text from public.ntes where id=n)<>'Approved' then raise exception 'NTE sent before explicit HR confirmation';end if;
 if private.nte_is_published(n) then raise exception 'Unsent NTE marked published';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',hr.auth_user_id,'role','authenticated')::text,true);
 begin update public.ntes set status='Issued' where id=n;raise exception 'DIRECT_SEND_BYPASS';exception when insufficient_privilege then null;end;
 begin perform public.act_attendance_hr_case(r,'send_nte',6,'{"reason":"Missing required checks"}');raise exception 'SEND_CHECKS_BYPASS';exception when others then if sqlerrm='SEND_CHECKS_BYPASS' then raise;end if;end;
 checks:='{"reason":"Reviewed and confirmed all facts and selected policy","irReviewed":true,"timelineComplete":true,"clarificationsConsidered":true,"reasonDocumented":true,"policySelected":true,"deadlineCorrect":true,"contentReviewed":true}';
 perform public.act_attendance_hr_case(r,'send_nte',6,checks);
 if not private.nte_is_published(n) then raise exception 'Authorized HR send failed';end if;
 if (select status from attendance_issues.requests where id=r)<>'rejected' then raise exception 'NTE changed unapproved timekeeping';end if;
 if not exists(select 1 from attendance_issues.audit where request_id=r and action='HR case send_nte' and actor=hr.id and request_revision=4 and nte_id=n) then raise exception 'Linked audit context missing';end if;
 -- Independent closed/no-violation path must never create an NTE.
 perform set_config('request.jwt.claims',jsonb_build_object('sub',e.auth_user_id,'role','authenticated')::text,true);
 r:=public.submit_attendance_issue(payload||jsonb_build_object('date',(payload->>'date')::date+1),gen_random_uuid());
 perform set_config('request.jwt.claims',jsonb_build_object('sub',m.auth_user_id,'role','authenticated')::text,true);
 perform public.review_attendance_issue(r,'reject','Review this factual report',1,'Other',true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',hr.auth_user_id,'role','authenticated')::text,true);
 perform public.act_attendance_hr_case(r,'close',1,'{"reason":"Evidence supports no violation","approveAttendance":false}');
 if (select state from attendance_issues.hr_cases where request_id=r)<>'closed_no_violation' then raise exception 'No-violation closure failed';end if;
 if exists(select 1 from attendance_issues.hr_cases where request_id=r and nte_id is not null) then raise exception 'No-violation closure created NTE';end if;
 begin delete from attendance_issues.audit where request_id=r;raise exception 'AUDIT_DELETION_ALLOWED';exception when others then if sqlerrm='AUDIT_DELETION_ALLOWED' then raise;end if;end;
end $$;
set constraints all immediate;
select 'PASS: clarification, revisions, direct-manager routing, rejection confirmation, factual IR, scoped HR, response pause, draft edits, BOD approvals, HR-only send, unapproved timekeeping, closure and immutable linked audit' result;
rollback;
