-- Focused native channel verification; all fixtures roll back.
begin;set local lock_timeout='2s';set local statement_timeout='40s';
do $test$
declare emp uuid;actor uuid;admin_emp uuid;admin_auth uuid;bu uuid;site uuid;qrdev uuid;biodev uuid;day date:=(now() at time zone 'Asia/Manila')::date;wk date;pub uuid;req uuid;ctx jsonb;challenge jsonb;pair jsonb;imp jsonb;r jsonb;bad boolean;lat numeric;lon numeric;begin
 select h.id,h.auth_user_id,h.business_unit_id into strict emp,actor,bu from public.hris_users h where h.auth_user_id is not null and h.business_unit_id is not null and lower(h.status)='active' and not coalesce(h.is_duplicate,false) and exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id join public.role_permissions rp on rp.role_id=r.id where ur.user_id=h.id and ur.is_active and r.is_active and rp.resource_id='ClockInOut' and 'create'=any(rp.permissions)) and not exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=h.id and ur.is_active and r.dashboard_type in('admin','hr','executive')) and not exists(select 1 from public.payroll_schedule_publications p where p.employee_id=h.id) limit 1;
 select h.id,h.auth_user_id into strict admin_emp,admin_auth from public.hris_users h join public.user_roles ur on ur.user_id=h.id join public.roles r on r.id=ur.role_id where h.auth_user_id is not null and lower(h.status)='active' and ur.is_active and r.is_active and r.dashboard_type='admin' and ur.scope_type='GLOBAL' limit 1;
 insert into public.sites(name,business_unit_id,latitude,longitude,radius_meters,timezone) values('Rollback site',bu,14.5,121.0,200,'Asia/Manila') returning id into site;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_auth,'role','authenticated')::text,true);set local role authenticated;
 qrdev:=public.save_attendance_device(null,bu,site,'Rollback kiosk','qr',true);biodev:=public.save_attendance_device(null,bu,site,'Rollback biometric','biometric',true);
 perform public.save_attendance_channel_settings(bu,0,false,true,true,'Rollback channel verification');perform public.map_attendance_device_employee(biodev,'TEST-CODE',emp,true);
 pair:=public.pair_attendance_kiosk(qrdev);reset role;
 set local role anon;challenge:=public.get_attendance_kiosk_display(pair->>'token');reset role;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);set local role authenticated;
 bad:=false;begin perform public.get_attendance_channel_admin();exception when insufficient_privilege then bad:=true;end;if not bad then raise exception 'Employee opened device administration';end if;
 bad:=false;begin perform public.pair_attendance_kiosk(qrdev);exception when insufficient_privilege then bad:=true;end;if not bad then raise exception 'Employee paired kiosk';end if;
 bad:=false;begin perform public.record_my_attendance('CLOCK_IN',gen_random_uuid(),0,day);exception when raise_exception then bad:=true;end;if not bad then raise exception 'Web bypass accepted when disabled';end if;
 bad:=false;begin perform public.record_my_attendance_verified('CLOCK_IN',gen_random_uuid(),0,day,jsonb_build_object('method','gps','siteId',site,'latitude',15.5,'longitude',121,'accuracy',5));exception when raise_exception then bad:=true;end;if not bad then raise exception 'Outside geofence accepted';end if;
 bad:=false;begin perform public.record_my_attendance_verified('CLOCK_IN',gen_random_uuid(),0,day,jsonb_build_object('method','gps','siteId',site));exception when raise_exception then bad:=true;end;if not bad then raise exception 'GPS without coordinates/accuracy accepted';end if;
 bad:=false;begin perform public.record_my_attendance_verified('CLOCK_IN',gen_random_uuid(),0,day,jsonb_build_object('method','qr','token','invalid'));exception when raise_exception then bad:=true;end;if not bad then raise exception 'Invalid QR accepted';end if;
 reset role;wk:=date_trunc('week',day)::date;
 insert into public.payroll_schedule_publications(employee_id,business_unit_id,effective_from,effective_to,version,source_hash,snapshot,approval_required,published_by,reference) values(emp,bu,wk,wk+6,1,md5(private.payroll_schedule_draft(emp,wk)::text),jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'employeeId',emp,'date',day,'kind','work','start','09:00:00','end','18:00:00','breakMinutes',60,'flexible',false,'endDayOffset',0)),false,admin_emp,'Rollback publication') returning id into pub;
 set local role authenticated;req:=gen_random_uuid();ctx:=public.record_my_attendance_verified('CLOCK_IN',req,0,day,jsonb_build_object('method','gps','siteId',site,'latitude',14.5,'longitude',121,'accuracy',5));if ctx->>'state'<>'working' then raise exception 'GPS clock failed';end if;
 ctx:=public.record_my_attendance_verified('CLOCK_IN',req,0,day,jsonb_build_object('method','gps','siteId',site,'latitude',14.5,'longitude',121,'accuracy',5));if ctx->>'revision'<>'1' then raise exception 'GPS retry duplicated';end if;
 ctx:=public.record_my_attendance_verified('START_BREAK',gen_random_uuid(),1,day,jsonb_build_object('method','qr','token',challenge->>'token'));if ctx->>'state'<>'on_break' then raise exception 'Valid kiosk QR failed';end if;
 bad:=false;begin perform public.record_my_attendance_verified('END_BREAK',gen_random_uuid(),2,day,jsonb_build_object('method','qr','token',challenge->>'token'));exception when raise_exception then bad:=true;end;if not bad then raise exception 'QR replay accepted';end if;
 ctx:=public.record_my_attendance_verified('END_BREAK',gen_random_uuid(),2,day,jsonb_build_object('method','gps','siteId',site,'latitude',14.5,'longitude',121,'accuracy',5));
 ctx:=public.record_my_attendance_verified('CLOCK_OUT',gen_random_uuid(),3,day,jsonb_build_object('method','gps','siteId',site,'latitude',14.5,'longitude',121,'accuracy',5));reset role;
 if (select count(*) from public.attendance_channel_evidence e join public.attendance_clock_events c on c.id=e.event_id where c.employee_id=emp)<>4 then raise exception 'Channel evidence missing/duplicated';end if;
 -- A prior-day export exercises actual historical device times and payroll ledger.
 day:=day-2;wk:=date_trunc('week',day)::date;
 insert into public.payroll_schedule_publications(employee_id,business_unit_id,effective_from,effective_to,version,source_hash,snapshot,approval_required,published_by,reference) values(emp,bu,wk,wk+6,2,md5(private.payroll_schedule_draft(emp,wk)::text),jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'employeeId',emp,'date',day,'kind','work','start','09:00:00','end','18:00:00','breakMinutes',60,'flexible',false,'endDayOffset',0)),false,admin_emp,'Rollback historical publication');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_auth,'role','authenticated')::text,true);set local role authenticated;
 imp:=public.preview_attendance_import(biodev,'rollback.csv',jsonb_build_array(jsonb_build_object('code','TEST-CODE','timestamp',day::text||'T09:00:00+08:00','action','CLOCK_IN'),jsonb_build_object('code','TEST-CODE','timestamp',day::text||'T12:00:00+08:00','action','START_BREAK'),jsonb_build_object('code','TEST-CODE','timestamp',day::text||'T13:00:00+08:00','action','END_BREAK'),jsonb_build_object('code','TEST-CODE','timestamp',day::text||'T18:00:00+08:00','action','CLOCK_OUT')));
 r:=public.commit_attendance_import((imp->>'id')::uuid,imp->>'sourceHash');if r->>'inserted'<>'4' then raise exception 'Biometric import failed';end if;
 if public.commit_attendance_import((imp->>'id')::uuid,imp->>'sourceHash')<>r then raise exception 'Import retry not idempotent';end if;
 imp:=public.preview_attendance_import(biodev,'repeat.csv',jsonb_build_array(jsonb_build_object('code','TEST-CODE','timestamp',day::text||'T09:00:00+08:00','action','CLOCK_IN')));r:=public.commit_attendance_import((imp->>'id')::uuid,imp->>'sourceHash');if r->>'duplicates'<>'1' or r->>'inserted'<>'0' then raise exception 'Repeated file not deduplicated';end if;
 bad:=false;begin perform public.preview_attendance_import(biodev,'unknown.csv','[{"code":"UNMAPPED","timestamp":"2026-01-01T09:00:00+08:00","action":"CLOCK_IN"}]');exception when raise_exception then bad:=true;end;if not bad then raise exception 'Unmapped code accepted';end if;
 reset role;
end $test$;
select 'PASS: scoped administration, disabled-web rejection, GPS boundary and retry, paired signed-out kiosk, invalid/replayed QR denial, evidence retention, actual biometric import, repeated batch/file deduplication and unmapped-code denial. Fixtures rolled back.' as result;
rollback;
