begin;
do $$declare hr record; reporter record; other_user record; ir record; q uuid; m uuid; v jsonb; nonce uuid:=gen_random_uuid(); n integer;begin
 select distinct h.id,h.auth_user_id into hr from public.hris_users h join public.user_roles ur on ur.user_id=h.id and ur.is_active where ur.role_id in('HR Manager','HR Staff','Admin') and lower(h.status)='active' and h.auth_user_id is not null order by h.id limit 1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',hr.auth_user_id,'role','authenticated')::text,true);
 select r.id,r.reported_by into ir from public.incident_reports r join public.hris_users h on h.id=r.reported_by where lower(h.status)='active' and h.auth_user_id is not null and r.reported_by<>hr.id and case_correspondence.manage(r.id) and not exists(select 1 from public.user_roles ur where ur.user_id=h.id and ur.is_active and ur.role_id in('HR Manager','HR Staff','Admin','Board of Director')) limit 1;
 if ir.id is null then raise exception 'No permitted case fixture';end if;
 select id,auth_user_id into reporter from public.hris_users where id=ir.reported_by;
 select id,auth_user_id into other_user from public.hris_users where auth_user_id is not null and lower(status)='active' and id not in(hr.id,reporter.id) and not exists(select 1 from public.user_roles where user_id=hris_users.id and is_active and role_id in('HR Manager','HR Staff','Admin','Board of Director')) and not exists(select 1 from case_correspondence.questions where recipient=hris_users.id and case_id=ir.id) limit 1;
 execute 'set local role authenticated';
 q:=public.send_case_question(ir.id,'Rollback question: clarify the factual timeline','No disciplinary conclusion',clock_timestamp()+interval '2 days',true,null,nonce);
 if public.send_case_question(ir.id,'Rollback question: clarify the factual timeline','No disciplinary conclusion',clock_timestamp()+interval '2 days',true,null,nonce)<>q then raise exception 'Question idempotency failed';end if;
 perform public.save_case_reply(ir.id,null,'PRIVATE_INTERNAL_MARKER','[]','[]',false,'internal',gen_random_uuid());
 execute 'reset role';
 if (select count(*) from case_correspondence.questions where id=q)<>1 then raise exception 'Duplicate question';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',reporter.auth_user_id,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 v:=public.get_case_questions(ir.id);
 if v::text like '%PRIVATE_INTERNAL_MARKER%' then raise exception 'Internal note leaked';end if;
 if v->'original'->>'description' is null then raise exception 'Original report unavailable';end if;
 if not exists(select 1 from jsonb_array_elements(public.get_my_case_questions()) t where t->>'id'=q::text) then raise exception 'Dashboard action missing';end if;
 perform public.save_case_reply(ir.id,q,'Draft one','[]','[]',true,'reply',gen_random_uuid());
 perform public.save_case_reply(ir.id,q,'Draft two','[]','[]',true,'reply',gen_random_uuid());
 nonce:=gen_random_uuid();m:=public.save_case_reply(ir.id,q,'Final factual response','[]','["https://example.com/support"]',false,'reply',nonce);
 if public.save_case_reply(ir.id,q,'Final factual response','[]','["https://example.com/support"]',false,'reply',nonce)<>m then raise exception 'Final reply idempotency failed';end if;
 begin perform public.send_case_question(ir.id,'Unauthorized question','',clock_timestamp()+interval '1 day',false,null,gen_random_uuid());raise exception 'EMPLOYEE_QUESTION_ALLOWED';exception when insufficient_privilege then null;end;
 begin perform * from case_correspondence.messages;raise exception 'PRIVATE_TABLE_ACCESS_ALLOWED';exception when insufficient_privilege then null;end;
 execute 'reset role';
 if (select count(*) from case_correspondence.messages where question_id=q)<>3 then raise exception 'Draft versions not retained';end if;
 if not exists(select 1 from case_correspondence.questions where id=q and state='received' and opened_at is not null and replied_at is not null) then raise exception 'Server timestamps missing';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',other_user.auth_user_id,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 begin perform public.get_case_questions(ir.id);raise exception 'UNRELATED_CASE_ALLOWED';exception when insufficient_privilege then null;end;
 begin perform public.save_case_reply(ir.id,q,'Impersonation','[]','[]',false,'reply',gen_random_uuid());raise exception 'IMPERSONATION_ALLOWED';exception when insufficient_privilege then null;end;
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',hr.auth_user_id,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 v:=public.get_case_questions(ir.id);
 if v::text not like '%Final factual response%' then raise exception 'Reviewer cannot read response';end if;
 perform public.review_case_correspondence(ir.id,q,'reviewed','Evidence reviewed');
 execute 'reset role';
 if (select state from case_correspondence.questions where id=q)<>'reviewed' then raise exception 'Review not saved';end if;
 if not exists(select 1 from case_correspondence.deliveries where case_id=ir.id and event='Case Response Received' and recipient=hr.id) then raise exception 'Reviewer notification missing';end if;
 begin update case_correspondence.messages set body='rewrite' where id=m;raise exception 'MESSAGE_MUTATION_ALLOWED';exception when others then if sqlerrm='MESSAGE_MUTATION_ALLOWED' then raise;end if;end;
 begin delete from case_correspondence.audit where case_id=ir.id;raise exception 'AUDIT_DELETE_ALLOWED';exception when others then if sqlerrm='AUDIT_DELETE_ALLOWED' then raise;end if;end;
 begin update case_correspondence.cases set original='{}' where id=ir.id;raise exception 'ORIGINAL_MUTATION_ALLOWED';exception when others then if sqlerrm='ORIGINAL_MUTATION_ALLOWED' then raise;end if;end;
end$$;
select 'PASS: scoped questions, same-recipient replies, immutable original and messages, private notes, drafts, idempotency, server timestamps, dashboard action, review, queued notifications, unrelated-user rejection' result;
rollback;
