import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
await db.exec(`create schema private;create schema auth;create schema storage;create role authenticated;create role anon;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
create function public.current_hris_user_id() returns uuid language sql stable as $$select auth.uid()$$;
create function public.has_active_role(text) returns boolean language sql stable as $$select $1=current_setting('test.role',true)$$;
create function public.is_hr_or_admin() returns boolean language sql stable as $$select current_setting('test.role',true) in ('Admin','HR Manager','HR Staff','Board of Director')$$;
create function public.has_feature_permission(text,text) returns boolean language sql stable as $$select current_setting('test.role',true) in ('Admin','Manager')$$;
create table public.business_units(id uuid primary key,name text);
create table public.hris_users(id uuid primary key,full_name text,position text,role text,business_unit_id uuid);
create table public.award_templates(id uuid primary key,title text);
create table public.employee_awards(id uuid primary key,employee_id uuid,award_template_id uuid,notes text,business_unit_id uuid,department_id uuid,created_by_user_id uuid,approver_id uuid,status text,approver_steps jsonb,submitted_at timestamptz default now(),issued_at timestamptz,issued_by uuid,certificate_snapshot_url text,is_acknowledged_by_employee boolean default false,rejection_reason text);
create table public.notifications(user_id text,title text,message text,link text,dedupe_key text);
create table public.audit_fixture(action text,id uuid,details text);
create function private.award_audit(text,uuid,text) returns void language sql as $$insert into public.audit_fixture values($1,$2,$3)$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb);
alter table storage.objects enable row level security;
grant usage on schema public,private,auth,storage to authenticated;grant select,insert on storage.objects to authenticated;
grant select on public.employee_awards to authenticated;
create function public.mark_employee_award_issued(p_award_id uuid,p_certificate_snapshot_url text) returns public.employee_awards language plpgsql security definer as $$declare a public.employee_awards;begin
 select * into a from public.employee_awards where id=p_award_id;
 if a.status<>'Approved' then raise exception 'Approval required';end if;
 update public.employee_awards set status='Issued',certificate_snapshot_url=p_certificate_snapshot_url where id=p_award_id returning * into a;
 insert into public.notifications values(a.employee_id::text,'Award','','','award-issued:'||a.id::text);return a;end$$;
create function public.submit_employee_award(uuid,uuid,text,uuid,uuid,uuid[]) returns public.employee_awards language plpgsql as $$begin raise exception 'unused';end$$;
insert into business_units values('${id(10)}','Bakebe - Test'),('${id(11)}','Other Unit');
insert into hris_users values('${id(1)}','Test Recipient One','Employee','Employee','${id(10)}'),('${id(2)}','Test Recipient Two','Employee','Employee','${id(10)}'),('${id(3)}','Test HR','HR Manager','HR Manager','${id(10)}'),('${id(4)}','Test Approver','Director','Board of Director','${id(10)}'),('${id(5)}','Other BU Employee','Employee','Employee','${id(11)}');
insert into award_templates values('${id(20)}','Service Excellence');
insert into employee_awards(id,employee_id,award_template_id,notes,business_unit_id,created_by_user_id,approver_id,status,approver_steps) values
 ('${id(30)}','${id(1)}','${id(20)}','Thank you for your excellent service.','${id(10)}','${id(3)}','${id(4)}','Approved','[{"userId":"${id(4)}","status":"Approved"}]'),
 ('${id(31)}','${id(2)}','${id(20)}','Your teamwork made a difference.','${id(10)}','${id(3)}','${id(4)}','Approved','[{"userId":"${id(4)}","status":"Approved"}]');`);
await db.exec(fs.readFileSync('supabase/migrations/20260915045401_award_commendation_letters.sql','utf8'));
const actor=async(n,role='Employee')=>{await db.exec('reset role');await db.query("select set_config('test.actor',$1,false),set_config('test.role',$2,false)",[id(n),role]);await db.exec('set role authenticated');};
const action=async(n,a,p={})=>(await db.query('select public.award_letter_action($1,$2,$3) result',[id(n),a,p])).rows[0].result;
await actor(3,'HR Manager');
let first=await action(30,'prepare');assert.equal(first.snapshot.employeeName,'Test Recipient One');assert.equal(first.snapshot.brand.accent,'#f56600');assert.equal(first.state,'Draft');assert.equal(first.snapshot.approvers[0].name,'Test Approver');
await assert.rejects(()=>action(30,'finalize'),/not stored/);
await action(30,'error',{message:'Simulated upload failure'});
first=await action(30,'prepare');assert.equal(first.state,'Draft');
await db.query("insert into storage.objects(bucket_id,name,metadata) values('award-commendations',$1,'{\"size\":1000}')",[first.file_path]);
const issued=await action(30,'finalize');assert.equal(issued.state,'Issued');
await db.exec('reset role');assert.equal((await db.query('select status from employee_awards where id=$1',[id(30)])).rows[0].status,'Issued');assert.match((await db.query('select link from notifications')).rows[0].link,/letter=/);
await actor(1);await assert.rejects(()=>action(30,'acknowledge'),/Open your own letter/);
assert.equal((await db.query("select count(*)::int n from storage.objects where name=$1",[first.file_path])).rows[0].n,1);
await action(30,'open');const ack=await action(30,'acknowledge');assert(ack.acknowledged_at);assert.equal((await action(30,'acknowledge')).acknowledged_at,ack.acknowledged_at);
await actor(5);assert.equal((await db.query('select count(*)::int n from award_letters')).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from storage.objects')).rows[0].n,0);await assert.rejects(()=>action(30,'open'),/unavailable/);await assert.rejects(()=>action(30,'acknowledge'),/unavailable/);
await actor(3,'HR Manager');const second=await action(31,'prepare');assert.equal(second.snapshot.employeeName,'Test Recipient Two');assert.notEqual(first.file_path,second.file_path);
await db.query("update commendation_templates set config=jsonb_set(config,'{wordmark}','\"UPDATED BRAND\"') where id=$1",[first.template_id]);
const frozen=(await db.query('select * from award_letters where award_id=$1',[id(30)])).rows[0];assert.deepEqual(frozen.snapshot,first.snapshot);assert.equal(frozen.template_version,1);assert.equal((await db.query('select version from commendation_templates where id=$1',[first.template_id])).rows[0].version,2);
await assert.rejects(()=>db.query("update award_letters set snapshot='{}'"),/permission denied/);
await assert.rejects(()=>db.query("update storage.objects set name='replacement.pdf'"),/permission denied/);
await assert.rejects(()=>action(30,'withdraw',{reason:''}),/reason/);await action(30,'withdraw',{reason:'Issued in error'});
await db.exec('reset role');assert.equal((await db.query('select status from employee_awards where id=$1',[id(30)])).rows[0].status,'Rejected');assert((await db.query('select count(*)::int n from audit_fixture')).rows[0].n>5);
console.log('PASS: BU branding and personalized snapshot; separate recipient paths; storage failure leaves Draft and retry succeeds; issuance notification; own-letter read and open-before-acknowledge; other-BU RLS denial; template version freezes issued snapshot; no client overwrite; audited withdrawal removes issued status.');
await db.close();
