import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const Module = require('node:module');
const empty = {pendingLeaveApprovals:[],pendingWfhApprovals:[],pendingOtApprovals:[],pendingManpowerApprovals:[],pendingNTEApprovals:[],pendingPANApprovals:[],pendingBenefitApprovals:[],pendingRequisitionApprovals:[],pendingAwardApprovals:[],pendingOfferApprovals:[],pendingAssetApprovals:[]};
globalThis.inboxFixture = {...empty,pendingPANApprovals:[{id:'pan-1',employeeName:'Test Employee',action:'Promotion',createdAt:'2020-01-01',effectiveDate:'2099-01-01'}],pendingNTEApprovals:[{id:'nte-1',employeeName:'Second Employee',reference:'NTE-TEST',currentStep:'Issuance review',createdAt:new Date().toISOString()}]};
const result=await build({stdin:{contents:"import React from 'react'; import {renderToStaticMarkup} from 'react-dom/server'; import {MemoryRouter} from 'react-router-dom'; import Inbox from './components/dashboard/ApprovalWidget'; export const render=()=>renderToStaticMarkup(<MemoryRouter><Inbox/></MemoryRouter>);",resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,platform:'node',format:'cjs',packages:'external',plugins:[{name:'authorized-queue-fixtures',setup(b){b.onResolve({filter:/hooks\/use(Auth|Approvals|AdditionalApprovals)$/},args=>({path:args.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path.endsWith('useAuth')?"export const useAuth=()=>({user:{id:'test'}})":'export const '+(args.path.endsWith('useAdditionalApprovals')?'useAdditionalApprovals':'useApprovals')+'=()=>globalThis.inboxFixture;',loader:'js'}));}}]});
const mod=new Module(process.cwd()+'/inbox-test.cjs');mod.paths=Module._nodeModulePaths(process.cwd());mod._compile(result.outputFiles[0].text,mod.filename||'inbox-test.cjs');
const html=mod.exports.render();
assert.match(html,/Needs your approval/);
assert.match(html,/Review PAN for Test Employee/);
assert.match(html,/\/employees\/pan\?review=pan-1/);
assert.match(html,/\/feedback\/nte\/nte-1/);
assert.equal((html.match(/>Review<\/a>/g)||[]).length,2);
assert.doesNotMatch(html,/Approval workload|Review queue|Due today|Overdue/);
globalThis.inboxFixture=empty;
assert.equal(mod.exports.render(),'');
globalThis.inboxFixture={...empty,approvalError:'Failed'};
assert.match(mod.exports.render(),/Retry/);
console.log('PASS: individual review links, no false deadlines or workload summaries, empty and failed queues.');
