import assert from 'node:assert/strict';
import {build} from 'esbuild';
import Module,{createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {createClient} from '@supabase/supabase-js';
const root=fileURLToPath(new URL('../',import.meta.url));
globalThis.dashboardHarness={state:[],index:0,effects:[],deps:[]};
const h=globalThis.dashboardHarness;
let requestUrl;
globalThis.testClient=createClient('https://example.test','test-key',{auth:{persistSession:false,autoRefreshToken:false},global:{fetch:async(url)=>{requestUrl=String(url);return new Response(JSON.stringify([{id:'assigned-pan'}]),{status:200,headers:{'Content-Type':'application/json'}});}}});
const result=await build({stdin:{contents:"export * from './components/dashboard/AttendancePulse';export {ScheduleTask} from './modules/scheduleCompliance';export {default as Access} from './components/auth/AssignedPanAccess';",resolveDir:root,loader:'tsx'},bundle:true,jsx:'transform',tsconfigRaw:{compilerOptions:{jsx:'react'}},platform:'node',format:'cjs',write:false,plugins:[{name:'isolated-hooks',setup(b){
 b.onResolve({filter:/^react$|react-router-dom$|supabaseClient$|attendancePulse$/},a=>({path:a.path,namespace:'mock'}));
 b.onLoad({filter:/.*/,namespace:'mock'},a=>({loader:'js',contents:a.path==='react'?`
 const h=globalThis.dashboardHarness;
 export const useState=v=>{const i=h.index++;if(!(i in h.state))h.state[i]=v;return[h.state[i],v=>h.state[i]=typeof v==='function'?v(h.state[i]):v]};
 export const useEffect=(f,deps)=>{const i=h.index++;if(!h.deps[i]||deps.some((v,j)=>v!==h.deps[i][j])){h.deps[i]=deps;h.effects.push(f);}};
 export default {createElement:(type,props,...children)=>({type,props:{...props,children}})};
 `:a.path==='react-router-dom'?`export const Link='a';`:a.path.endsWith('supabaseClient')?`export const supabase=globalThis.testClient;export const retryTransientSupabaseRead=f=>f();`:`export const useAttendancePulse=()=>({});export const impactedSchedule=d=>'/schedule?date='+d;export const pulsePath=d=>'/pulse?date='+d;export const pulseLevel={normal:'Normal',attention:'Needs attention',critical:'Critical staffing risk'};export const pulseTone={normal:'green',attention:'amber',critical:'red'};`}));
}}]});
const mod=new Module(root+'compact-dashboard.cjs');mod.filename=root+'compact-dashboard.cjs';mod.paths=Module._nodeModulePaths(root);mod.require=createRequire(mod.filename);mod._compile(result.outputFiles[0].text,mod.filename);
const {PulseAccordion,ScheduleTask,Access}=mod.exports;
const reset=()=>{h.state=[];h.deps=[];h.effects=[];};
const render=(View,props)=>{h.index=0;return View(props);};
const effects=()=>{for(const f of h.effects.splice(0))f();};
const nodes=t=>!t||typeof t!=='object'?[]:[t,...Object.values(t.props||{}).flatMap(v=>Array.isArray(v)?v.flatMap(nodes):nodes(v))];
const data={pending:0,attention:0,severity:'normal',concerns:[],rows:[],scope:'Company-wide',date:'2026-09-10'};
let tree=render(PulseAccordion,{data});effects();assert.equal(nodes(tree).find(n=>n.type==='button').props['aria-expanded'],false);assert.ok(!nodes(tree).some(n=>n.props?.id==='dashboard-pulse-details'));
nodes(tree).find(n=>n.type==='button').props.onClick();tree=render(PulseAccordion,{data});assert.equal(nodes(tree).find(n=>n.type==='button').props['aria-expanded'],true);
const issue={...data,pending:1};render(PulseAccordion,{data:issue});effects();tree=render(PulseAccordion,{data:issue});assert.equal(nodes(tree).find(n=>n.type==='button').props['aria-expanded'],true);
nodes(tree).find(n=>n.type==='button').props.onClick();assert.equal(nodes(render(PulseAccordion,{data:issue})).find(n=>n.type==='button').props['aria-expanded'],false);
render(PulseAccordion,{data});effects();assert.equal(nodes(render(PulseAccordion,{data})).find(n=>n.type==='button').props['aria-expanded'],false);
reset();assert.equal(nodes(render(PulseAccordion,{data:issue})).find(n=>n.type==='button').props['aria-expanded'],true,'Refresh with pending reports opens details');
reset();h.state[0]={required:9,remaining:9,completed:0,percentage:0,exempt:0,week:'2026-09-14',deadline:'2026-09-12T15:59:00Z',status:'Due Tomorrow',hr:true,employees:[]};
tree=render(ScheduleTask,{});assert.match(tree.props.className,/border-2 border-red-500/);assert.ok(nodes(tree).some(n=>n.props?.children?.includes('URGENT')));assert.ok(nodes(tree).some(n=>n.props?.children?.includes('Set Schedules')&&n.props.className.includes('bg-violet-600')));
h.state[0].status='Completed';h.state[0].remaining=0;const completedTree=render(ScheduleTask,{});assert.ok(!nodes(completedTree).some(n=>n.props?.id==='schedule-task'),'Completed schedule tasks are hidden from the dashboard');
reset();h.state[0]={required:3,remaining:0,completed:3,percentage:100,exempt:0,week:'2026-09-14',deadline:'2026-09-12T15:59:00Z',status:'Completed',hr:false,employees:[]};assert.equal(render(ScheduleTask,{}),null,'Completed employee-manager tasks render nothing');
reset();render(Access,{userId:'manager-id',requestId:null,children:{type:'authorized'}});effects();await new Promise(r=>setImmediate(r));
assert.equal(new URL(requestUrl).searchParams.get('or'),'(employee_id.eq.manager-id,routing_steps.cs.[{"userId":"manager-id"}])','JSONB filter must not serialize as PostgreSQL object array');
assert.equal(render(Access,{userId:'manager-id',requestId:null,children:{type:'authorized'}}).type,'authorized');
console.log('PASS: normal/pending accordion defaults, manual toggles, refresh defaults, urgent schedule styling, purple action, real Supabase JSONB request serialization');
