import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import ts from 'typescript';
const source=await fs.readFile(new URL('../modules/employeeSnapshot/model.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {isBod,money,tenure,taxCopy}=await import(`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`);
assert(isBod({role:'Board of Director'}));assert(isBod({role:'Admin',roles:['Admin','Board of Director']}));
for(const role of ['Admin','HR Manager','Finance Staff','Manager','Auditor','Employee','IT'])assert(!isBod({role}));
assert(!isBod({role:'Board of Director',roles:['Employee']}));assert(!isBod(null));
assert.equal(money(null),'Unavailable');assert.equal(money(undefined),'Unavailable');assert.notEqual(money(0),'Unavailable');
assert.equal(tenure('2024-05-08',null,'Active','2026-09-08'),'2 years 4 months with TNG');
assert.equal(tenure('2024-05-08','2025-05-08','Inactive','2026-09-08'),'1 year with TNG');
assert.equal(tenure(null,null,'Active','2026-09-08'),'Tenure unavailable');
assert.equal(tenure('2024-05-08',null,'Inactive','2026-09-08'),'Tenure unavailable');
assert.equal(tenure('2026-10-08',null,'Active','2026-09-08'),'Tenure unavailable');
assert.equal(tenure('2026-09-08',null,'Active','2026-09-08'),'Less than 1 month with TNG');
assert.match(taxCopy['Net of tax'],/Company shoulders/);
const page=await fs.readFile(new URL('../modules/employeeSnapshot/EmployeeSnapshotPage.tsx',import.meta.url),'utf8');
assert.match(page,/setTimeout\(\(\)=>setDebounced\(q\),250\)/);assert.match(page,/controller\.abort/);
assert.match(page,/result.identity.id===selected/);assert.match(page,/detailSequence/);
assert(!/localStorage|sessionStorage|\.from\(/.test(page));
assert.match(page,/Previous employee/);assert.match(page,/Next employee/);assert.match(page,/Browse all employees/);
assert.match(page,/dark:/);assert.match(page,/No issued NTEs recorded/);
const sql=await fs.readFile(new URL('./bodSnapshotProposal.sql',import.meta.url),'utf8');
assert.match(sql,/has_active_role\('Board of Director'\)/);
assert(!/create policy|alter policy|grant select|insert into|update public|delete from/i.test(sql));
assert.match(sql,/calculate_payroll_net_v1\(r.source_snapshot\)/);
assert.match(sql,/limit lim offset off/);assert.match(sql,/lim integer:=25/);
assert.match(sql,/Awaiting explanation — no finding yet/);
assert(!/bank_account_number|sss_no|emergency_contact/.test(sql));
console.log('PASS: role combinations, missing vs zero, tenure/end-date boundaries, explicit tax text, debounce/cancellation guards, read-only API structure and bounded pagination.');
