import assert from 'node:assert/strict';
import {build} from 'esbuild';
import Module,{createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
const root=fileURLToPath(new URL('../',import.meta.url));
const result=await build({stdin:{contents:"export * from './components/attendance/AttendanceMission';",resolveDir:root,loader:'tsx'},bundle:true,platform:'node',format:'cjs',write:false,packages:'external',plugins:[{name:'isolate-view',setup(b){b.onResolve({filter:/^react$/},()=>({path:'react',external:true}));b.onResolve({filter:/react-router-dom$|attendanceIssues$/},a=>({path:a.path,namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='react-router-dom'?"const React=require('react');exports.Link=({to,...p})=>React.createElement('a',{...p,href:to});":"exports.approvedLabels={absence:'Approved absence · No clock-in required'};exports.manila=v=>v;",loader:'js'}));}}]});
const mod=new Module(root+'clock-focus.cjs');mod.filename=root+'clock-focus.cjs';mod.paths=Module._nodeModulePaths(root);mod.require=createRequire(mod.filename);mod._compile(result.outputFiles[0].text,mod.filename);
const {AttendanceMissionView:View,weeklyTotals,attendanceHelpLabel}=mod.exports;
const day={workDate:'2026-09-10',serverTime:'2026-09-10T03:15:00Z',timezone:'Asia/Manila',requiresClock:true,state:'working',elapsedSeconds:3600,breakSeconds:0,events:[{type:'CLOCK_IN',timestamp:'2026-09-10T01:00:00Z'}],schedule:{published:true,entries:[{id:'shift',templateId:'x',kind:'work',name:'Day',start:'09:00:00',end:'18:00:00',paidMinutes:480,endDayOffset:0}]}};
const history={weekStart:'2026-09-07',days:[{...day,workDate:'2026-09-09',elapsedSeconds:7200},day],needsClarification:false};
const props={day,elapsed:4000,busy:false,error:'',onAction:()=>{},onRefresh:()=>{},onHelp:()=>{},onAbsence:()=>{},onHistory:()=>{},history,historyError:''};
let html=renderToStaticMarkup(React.createElement(View,props));
for(const text of ['CLOCK OUT','TAKE A BREAK','Need to fix an attendance issue?','Report that I am unable to work today','TODAY','THIS WEEK','3h 6m','Not taken','In progress'])assert.ok(html.includes(text),text);
for(const text of ['Recharge','Back at it','Forgot to','Manage clocking','My missed punches','TODAY’S PROGRESS'])assert.ok(!html.includes(text),text);
assert.equal((html.match(/Need to fix an attendance issue/g)||[]).length,1);
assert.match(html,/<button[^>]*text-slate-600[^>]*>Report that I am unable/);
assert.deepEqual(weeklyTotals(history,day,4000),{seconds:11200,scheduled:57600});
assert.equal(weeklyTotals(history,{...day,workDate:'2026-09-01'},99999).seconds,10800,'prior-week open shift excluded');
html=renderToStaticMarkup(React.createElement(View,{...props,day:{...day,state:'on_break'}}));assert.ok(html.includes('END BREAK'));assert.ok(html.includes('RETURN TO WORK'));assert.ok(html.includes('Currently on break'));
html=renderToStaticMarkup(React.createElement(View,{...props,day:{...day,state:'not_started',events:[]}}));assert.ok(html.includes('OFF THE CLOCK'));assert.ok(html.includes('CLOCK IN'));
html=renderToStaticMarkup(React.createElement(View,{...props,day:{...day,state:'completed'}}));assert.ok(html.includes('Clock-out recorded.'));assert.ok(!html.includes('>CLOCK IN<'));
assert.equal(attendanceHelpLabel(day,true),'Update returned request');
assert.equal(attendanceHelpLabel({...day,workDate:'2026-09-09'}),'Review a missed punch');
assert.equal(attendanceHelpLabel({...day,workDate:'2026-09-09',serverTime:'2026-09-10T01:00:00Z',schedule:{...day.schedule,entries:[{...day.schedule.entries[0],end:'10:00:00',endDayOffset:1}]}}),'Need to fix an attendance issue?','ongoing overnight shift must not be falsely flagged');
console.log('Clock focus checks passed: action hierarchy, own weekly totals, break/completed states, overnight and returned-request alerts.');
