import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
process.on('uncaughtException',e=>{console.error(e.message,e.code,e.where);process.exit(1);});
const db=new PGlite(),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
// Reuse the isolated preset schema fixtures, never production user impersonation.
const setup=fs.readFileSync('tests/schedulePresetVisibilityTest.mjs','utf8').match(/await db.exec\(`([\s\S]*?)`\);/)[1];await db.exec(setup);
await db.exec(fs.readFileSync('tests/fixtures/schedulePresetExistingFunctions.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20260914232027_schedule_preset_reporting_visibility.sql','utf8'));
const original=fs.readFileSync('supabase/migrations/20260913235724_bod_schedule_validation_and_rest_days.sql','utf8');await db.exec(original.slice(original.indexOf('create or replace function public.review_bod_schedule_submission')));
await db.exec(`
create or replace function private.workflow_user_has_role(e uuid,r text) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.hris_users where id=e and role=r and lower(status)='active')$$;
create or replace function private.payroll_schedule_draft(e uuid,w date) returns jsonb language sql stable security definer set search_path='' as $$select coalesce(jsonb_agg(jsonb_build_object('date',a.date,'templateId',a.shift_template_id,'name','Synthetic shift') order by a.date),'[]') from public.shift_assignments a where a.employee_id=e and a.date between w and w+6$$;
create function private.approved_schedule_leave(e uuid,d date) returns jsonb language sql as $$select '[]'::jsonb$$;
create function private.attendance_exception(e uuid,d date) returns jsonb language sql as $$select '{"requires_clock":true}'::jsonb$$;
create function public.set_schedule_day_status(e uuid,d date,t text,r text) returns void language plpgsql as $$begin if t='rest' then insert into public.schedule_day_statuses(id,employee_id,work_date,tag) values(gen_random_uuid(),e,d,t);end if;end$$;
create table public.test_publications(employee_id uuid,week date,snapshot jsonb);
create function public.publish_payroll_schedule_week(es uuid[],w date,r text,expected jsonb) returns jsonb language plpgsql set search_path='' as $$declare e uuid;begin foreach e in array es loop if not private.payroll_schedule_can_edit(e) then raise exception 'Publication denied' using errcode='42501';end if;insert into public.test_publications values(e,w,private.payroll_schedule_draft(e,w));end loop;return '{}'::jsonb;end$$;
insert into schedule_compliance.settings values(2,'23:59');
revoke all on schedule_compliance.submissions from public,anon,authenticated;
revoke all on function public.get_bod_schedule_workflow(date),public.submit_my_bod_schedule(date,jsonb,text),public.review_bod_schedule_submission(uuid,integer,boolean,text) from public,anon;
grant execute on function public.get_bod_schedule_workflow(date),public.submit_my_bod_schedule(date,jsonb,text),public.review_bod_schedule_submission(uuid,integer,boolean,text) to authenticated;
`);
await db.exec('drop function schedule_compliance.bod_manager(uuid)');
await db.exec(fs.readFileSync('supabase/migrations/20260916050014_gm_direct_report_schedule_submission.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20260920090000_schedule_submission_notes_optional.sql','utf8'));
const people=[[1,'GM','GeneralManager',null],[2,'Employee','Employee',1],[3,'Other GM','GeneralManager',null],[4,'Other employee','Employee',3],[5,'BOD','Board of Director',null],[6,'BOD report','Employee',5],[7,'Ordinary manager','Manager',null],[8,'Ordinary report','Employee',7]];
for(const [n,name,role,m] of people)await db.query('insert into public.hris_users(id,auth_user_id,full_name,role,reports_to,business_unit_id) values($1,$2,$3,$4,$5,$6)',[id(n),id(1000+n),name,role,m?id(m):null,id(20)]);
await db.query("insert into shift_templates(id,name,business_unit_id,created_by,start_time,end_time) values($1,'GM preset',$3,$2,'09:00','18:00'),($4,'Other preset',$3,$5,'09:00','18:00')",[id(30),id(1),id(20),id(31),id(3)]);
const call=async(name,args=[])=>(await db.query(`select ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
const admin=async(sql,args=[])=>{await db.exec('reset role');return db.query(sql,args);};
const actor=async n=>{await db.exec('reset role');await db.query("select set_config('test.actor',$1,false)",[id(1000+n)]);await db.exec('set role authenticated');};
const week=(await admin("select date_trunc('week',now() at time zone 'Asia/Manila')::date::text w")).rows[0].w;
const entries=Array.from({length:7},(_,n)=>({date:new Date(Date.parse(week+'T00:00:00Z')+86400000*n).toISOString().slice(0,10),templateId:id(30)}));
await actor(2);let workflow=await call('get_bod_schedule_workflow',[week]);assert.equal(workflow.eligible,true);assert.equal(workflow.managerRole,'GM');assert.equal(workflow.templates.length,1);
const submit=()=>call('submit_my_bod_schedule',[week,entries,'Synthetic employee proposal']);const request=await submit();assert.equal(await submit(),request,'Retry returns the same proposal');
const weekWithoutNotes=new Date(Date.parse(week+'T00:00:00Z')+86400000*14).toISOString().slice(0,10);
const entriesWithoutNotes=entries.map((e,n)=>({...e,date:new Date(Date.parse(weekWithoutNotes+'T00:00:00Z')+86400000*n).toISOString().slice(0,10)}));
const noNotesRequest=await call('submit_my_bod_schedule',[weekWithoutNotes,entriesWithoutNotes,'']);
assert.ok(noNotesRequest,'A schedule may be submitted without notes');
assert.equal((await admin('select count(*)::int n from shift_assignments')).rows[0].n,0,'Pending proposal never changes attendance schedules');
await actor(2);await assert.rejects(()=>call('review_bod_schedule_submission',[request,1,true,'Self approval']),/assigned BOD or GM/);
await actor(3);assert.equal((await call('get_bod_schedule_workflow',[week])).pending.length,0);await assert.rejects(()=>call('review_bod_schedule_submission',[request,1,true,'Wrong GM']),/assigned BOD or GM/);
await actor(1);workflow=await call('get_bod_schedule_workflow',[week]);assert.equal(workflow.isGm,true);assert.equal(workflow.pending[0].id,request);
await call('review_bod_schedule_submission',[request,1,false,'Please revise Monday']);
await actor(2);assert.equal((await call('get_bod_schedule_workflow',[week])).submission.status,'Rejected');await submit();assert.equal((await call('get_bod_schedule_workflow',[week])).submission.version,2);
await actor(1);await assert.rejects(()=>call('review_bod_schedule_submission',[request,1,true,'Old revision']),/Refresh the submission/);
await admin('insert into payroll_schedule_freezes values($1,$2,$2)',[id(2),week]);await actor(1);await assert.rejects(()=>call('review_bod_schedule_submission',[request,2,true,'Frozen week']),/frozen/);await admin('delete from payroll_schedule_freezes');
await actor(1);await call('review_bod_schedule_submission',[request,2,true,'Approved proposed week']);await call('review_bod_schedule_submission',[request,2,true,'Retry approved week']);
assert.equal((await admin('select count(*)::int n from shift_assignments')).rows[0].n,7);assert.equal((await admin('select count(*)::int n from test_publications')).rows[0].n,1,'Idempotent publication');
await actor(2);assert.equal((await call('get_bod_schedule_workflow',[week])).submission.status,'Approved');
// A current reporting-line change revokes the former approver immediately.
const week2=new Date(Date.parse(week+'T00:00:00Z')+86400000*7).toISOString().slice(0,10),rests=entries.map((e,n)=>({date:new Date(Date.parse(week2+'T00:00:00Z')+86400000*n).toISOString().slice(0,10),restDay:true,templateId:null}));
const reassigned=await call('submit_my_bod_schedule',[week2,rests,'Rest week proposal']);await admin('update hris_users set reports_to=$1 where id=$2',[id(3),id(2)]);
await actor(1);await assert.rejects(()=>call('review_bod_schedule_submission',[reassigned,1,true,'Former manager']),/assigned BOD or GM/);
await actor(2);assert.equal((await call('get_bod_schedule_workflow',[week2])).needsResubmission,true);await call('submit_my_bod_schedule',[week2,rests,'Resubmit to new GM']);
await actor(3);assert.equal((await call('get_bod_schedule_workflow',[week2])).pending[0].version,2);await call('review_bod_schedule_submission',[reassigned,2,true,'Approve rest week']);
await actor(6);assert.equal((await call('get_bod_schedule_workflow',[week])).managerRole,'BOD');
await actor(8);assert.equal((await call('get_bod_schedule_workflow',[week])).eligible,false);await assert.rejects(()=>call('submit_my_bod_schedule',[week,entries,'Not an eligible direct report']),/reporting directly/);
await admin("update hris_users set status='Inactive' where id=$1",[id(3)]);await actor(2);assert.equal((await call('get_bod_schedule_workflow',[week])).eligible,false);
await assert.rejects(()=>db.query('select * from schedule_compliance.submissions'),/permission denied/);
await db.close();console.log('PASS: canonical GM role and reports_to routing; employee proposal, rejection/resubmission, GM approval, current-assignment checks, BOD compatibility, outsider/self denial, preset scope, frozen-week rejection, idempotent publication and persisted status. Local publication fixture; no production schedules written.');
