import fs from 'node:fs';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();await db.exec(`create schema private;create role anon;create role authenticated;
create function private.payroll_time_sources(uuid,date,date) returns jsonb language sql as $$select '{}'::jsonb$$;
create function public.get_payroll_break_review(p_scope uuid,p_from date,p_to date) returns jsonb language plpgsql as $$declare src jsonb:='{}';hash text;begin hash:=md5((src-'approvedRecordedBreaks')::text);return '{}';end$$;
create function public.preview_payroll_time(uuid,date,date) returns jsonb language plpgsql as $$declare review jsonb:='{}';begin return jsonb_build_object('holidays',review#>'{source,holidays}');end$$;`);
const original=fs.readFileSync('supabase/migrations/20260906021209_payroll_attendance_readiness_phase3.sql','utf8');const start=original.indexOf('create function private.interpret_payroll_time(');await db.exec(original.slice(start,original.indexOf('end $$;',start)+7));
const defaults=fs.readFileSync('supabase/migrations/20260930042837_payroll_break_inbox_and_standing_defaults.sql','utf8');await db.exec(defaults.slice(0,defaults.indexOf('-- Lightweight')));
const src={employees:[{id:'e1',name:'Sample',hireDate:'2020-01-01',status:'Active'}],rules:[],shifts:[{id:'s1',employeeId:'e1',date:'2026-08-31',templateId:'t1',start:'09:00',end:'18:00',breakMinutes:60}],events:[['CLOCK_IN','09:00'],['START_BREAK','12:00'],['END_BREAK','13:00'],['CLOCK_OUT','18:00']].map(([type,time],i)=>({id:'p'+i,employeeId:'e1',type,timestamp:`2026-08-31T${time}:00+08:00`})),leave:[],ot:[],holidays:[{id:'manual',date:'2026-08-31',name:'National Heroes Day',kind:'regular'}],leavePolicies:[]};
const interpret=async(s,from='2026-08-31',to=from)=>(await db.query('select private.interpret_payroll_time($1,$2,$3) v',[JSON.stringify(s),from,to])).rows[0].v;
const before=(await interpret(src)).rows[0];
await db.exec(fs.readFileSync('supabase/migrations/20260930045717_government_holiday_calendar.sql','utf8'));
let calendars=(await db.query('select jsonb_agg(to_jsonb(c)) v from private.payroll_government_calendar c')).rows[0].v;
assert.equal(calendars[0].holidays.length,21);assert.equal(new Set(calendars[0].holidays.map(h=>h.date)).size,21);
const merge=async(s,from,to=from)=>(await db.query('select private.with_government_holidays($1,$2,$3,$4) v',[JSON.stringify(s),JSON.stringify(calendars),from,to])).rows[0].v;
const merged=await merge(src,'2026-08-31');assert.equal(merged.holidays.length,1);assert.equal(merged.holidays[0].kind,'regular');assert.equal(merged.holidays[0].government,true);assert.notDeepEqual(merged,src);assert.deepEqual(merged.events,src.events);
const after=(await interpret(merged)).rows[0];assert(before.issues.includes('Holiday calendar coverage needs review'));assert(!after.issues.some(x=>/holiday calendar/i.test(x)));assert.deepEqual(after.issues,before.issues.filter(x=>x!=='Holiday calendar coverage needs review'));for(const k of ['actualMinutes','regularMinutes','breakMinutes','approvedOtMinutes','actualOtMinutes','lateMinutes','undertimeMinutes'])assert.equal(after[k],before[k]);
const year=await merge({holidays:[]},'2026-01-01','2026-12-31');assert.equal(year.holidays.find(x=>x.date==='2026-02-25').kind,'special_working');assert.equal(year.holidays.find(x=>x.date==='2026-03-20').kind,'regular');assert.equal(year.holidays.find(x=>x.date==='2026-05-27').kind,'regular');
const local=await merge({holidays:[{id:'local',date:'2026-08-30',kind:'special_nonworking'}]},'2026-08-30');assert.equal(local.holidays.find(x=>x.id==='local').kind,'special_nonworking');
const unknown={...src,rules:[{id:'manual-confirmation',revision:1,effective_from:'2027-01-01',effective_to:'2027-12-31',config:{holidayCoverageConfirmed:true}}]};const next=await merge(unknown,'2027-01-01');assert.equal(next.governmentCalendar.covered,false);assert((await interpret(next,'2027-01-01')).rows[0].issues.includes('Government holiday calendar update needed'),'a client checkbox cannot claim government coverage');
// Overnight punches retain their source and each calendar-day segment checks coverage.
const overnight={...src,shifts:[{...src.shifts[0],date:'2026-12-31',start:'22:00',end:'06:00'}],events:[{id:'on',employeeId:'e1',type:'CLOCK_IN',timestamp:'2026-12-31T22:00:00+08:00'},{id:'off',employeeId:'e1',type:'CLOCK_OUT',timestamp:'2027-01-01T06:00:00+08:00'}]};
const over=await merge(overnight,'2026-12-31');const overrow=(await interpret(over,'2026-12-31')).rows[0];assert(overrow.segments.some(s=>s.date==='2027-01-01'));assert(overrow.issues.includes('Government holiday calendar update needed'));
for(const role of ['anon','authenticated']){assert.equal((await db.query("select has_table_privilege($1,'private.payroll_government_calendar','insert') ok",[role])).rows[0].ok,false);assert.equal((await db.query("select has_function_privilege($1,'private.with_government_holidays(jsonb,jsonb,date,date)','execute') ok",[role])).rows[0].ok,false);}
await db.close();console.log('PASS: official 21-date calendar, exact classifications, Eid proclamations, deduplication, retained local declarations, unchanged punches/quantities, missing-year fail-closed, overnight coverage, private ACL.');
