process.on('uncaughtException',e=>{console.error(e.message,e.code,e.position,e.where);process.exit(1);});
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {historicalTemplate} from '../modules/payroll/historicalTemplates.ts';
const db=new PGlite();const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
await db.exec(`create schema auth;create schema private;create role authenticated;create role anon;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
create function private.payroll_time_permission(uuid,text) returns boolean language sql as $$select $1='${id(10)}'::uuid and auth.uid() in('${id(9)}','${id(11)}','${id(12)}') and ($2='view' or auth.uid()='${id(9)}')$$;
create function private.payroll_has_access(text,uuid) returns boolean language sql as $$select auth.uid()='${id(11)}'::uuid and $2='${id(10)}'::uuid and $1='prepare_pr'$$;
create function private.attendance_admin() returns boolean language sql as $$select auth.uid()='${id(9)}'::uuid$$;
create function public.can_access_hris_user(uuid) returns boolean language sql as $$select $1='${id(1)}'::uuid$$;
create table payroll_access_scopes(id uuid primary key,name text,business_unit_id uuid);insert into payroll_access_scopes values('${id(10)}','Bakebe - SM Aura','${id(100)}'),('${id(20)}','Other BU','${id(200)}');
create table hris_users(id uuid primary key,employee_id text,full_name text,business_unit_id uuid,date_hired date,end_date date,is_duplicate boolean);
insert into hris_users values('${id(1)}','EMP-001','Synthetic One','${id(100)}','2025-01-01',null,false),('${id(2)}','EMP-002','Other BU employee','${id(200)}','2025-01-01',null,false);
create table attendance_clock_events(id int);insert into attendance_clock_events values(1);
create table attendance_clock_adjustments(id int);insert into attendance_clock_adjustments values(1);
create table attendance_penalties(id int);insert into attendance_penalties values(1);
create table leave_balances(id int);insert into leave_balances values(1);
create table payroll_disbursements(id int);insert into payroll_disbursements values(1);
create table payroll_time_packages(id uuid);create table time_logs(id int);
create function public.correct_attendance_day(uuid,date,integer,jsonb,text) returns jsonb language plpgsql as $$begin insert into public.attendance_clock_adjustments values(2);return jsonb_build_object('corrected',true);end $$;
`);
await db.exec(fs.readFileSync('supabase/migrations/20260916024456_payroll_historical_test_imports.sql','utf8'));
await db.exec(`select set_config('test.actor','${id(9)}',false);set role authenticated;`);
const actor=async n=>db.exec(`select set_config('test.actor','${id(n)}',false)`);
const punchHead='Employee Code,Business Unit,Work Date,Punch Time,Event Type,Source Reference\r\n';
const punch=punchHead+' emp-001 ,Bakebe - SM Aura,2026-09-10,2026-09-10T22:00:00+08:00,CLOCK_IN,Device evidence 123\r\nEMP-001,Bakebe - SM Aura,2026-09-10,2026-09-11T06:00:00+08:00,CLOCK_OUT,Device evidence 124\r\n';
const stage=async(text,kind='punches',scope=id(10),name='actual.csv')=>(await db.query('select public.stage_historical_attendance_test($1,$2,$3,$4,$5,$6,$7) result',[scope,'2026-08-26','2026-09-10',kind,name,Buffer.from(text).toString('base64'),'Reviewed source: synthetic test fixture'])).rows[0].result;
const commit=async batch=>(await db.query('select public.commit_historical_attendance_test($1) result',[batch])).rows[0].result;
const detail=async(batch,download=false)=>(await db.query('select public.get_historical_attendance_test($1,$2) result',[batch,download])).rows[0].result;
const protectedCounts=async()=>{await db.exec('reset role');const r=(await db.query("select jsonb_build_object('events',(select count(*) from attendance_clock_events),'adjustments',(select count(*) from attendance_clock_adjustments),'penalties',(select count(*) from attendance_penalties),'leave',(select count(*) from leave_balances),'payments',(select count(*) from payroll_disbursements),'packages',(select count(*) from payroll_time_packages),'logs',(select count(*) from time_logs)) counts")).rows[0].counts;await db.exec('set role authenticated');return r;};
const before=await protectedCounts();
let b=await stage(punch);assert.equal(b.preview.ready,2);assert.equal(b.preview.invalid,0);assert.equal(b.preview.rows[1].workDate,'2026-09-10');assert.equal(b.preview.rows[1].payload.timestamp,'2026-09-10T22:00:00Z');
assert.equal((await commit(b.id)).imported,2);assert.equal((await commit(b.id)).alreadyImported,true);
const repeated=await stage(punch,'punches',id(10),'renamed.csv');assert.equal(repeated.id,b.id);assert.equal(repeated.duplicateFile,true);
const semantic=await stage(punch.replaceAll('\r\n','\n'));assert.equal(semantic.preview.duplicates,2);assert.equal((await commit(semantic.id)).imported,0);
const d=await detail(b.id,true);assert.equal(Buffer.from(d.sourceBase64,'base64').toString(),punch);assert(d.audit.some(x=>x.action==='test_imported'));assert(d.audit.some(x=>x.action==='duplicate_upload'));assert(d.audit.some(x=>x.action==='source_downloaded'));
const dtrHead='Employee Code,Business Unit,Work Date,Regular Minutes,Overtime Minutes,Night Minutes,Late Minutes,Undertime Minutes,Unpaid Break Minutes,Review Reference\n';
const dtr=dtrHead+'EMP-001,Bakebe - SM Aura,2026-09-09,420,60,120,0,0,60,"Reviewed by HR, DTR A"\n';
const summary=await stage('\uFEFF'+dtr,'dtr');assert.equal(summary.preview.ready,1);assert.equal(summary.preview.rows[0].payload.timestamp,undefined);assert.equal((await commit(summary.id)).imported,1);
const conflict=await stage(dtr.replace('420,60','400,60'),'dtr');assert.equal(conflict.preview.invalid,1);assert.match(conflict.preview.rows[0].errors.join(' '),/Conflicting/);assert.equal((await commit(conflict.id)).status,'preview');
const cases=[['wrong employee',punch.replaceAll('EMP-001','MISSING').replace('emp-001','MISSING'),/Employee code/],['wrong BU',punch.replaceAll('Bakebe - SM Aura','Other BU'),/Business Unit/],['employee in another BU',punch.replaceAll('EMP-001','EMP-002').replace('emp-001','EMP-002'),/outside/],['cutoff date',punch.replaceAll('2026-09-10,','2026-09-12,'),/outside the selected cutoff/],['overnight beyond next day',punch.replace('2026-09-11T06','2026-09-12T06'),/following day/],['missing timezone',punch.replaceAll('+08:00',''),/timezone|ISO timestamp/]];
for(const [name,source,pattern] of cases){const x=await stage(source);assert(x.preview.invalid>0,name);assert.match(x.preview.rows.flatMap(r=>r.errors).join(' '),pattern,name);assert.equal((await commit(x.id)).status,'preview',name);}
const sameFileRows=await stage(punchHead+punch.split('\r\n').slice(1,2).concat(punch.split('\r\n').slice(1,2)).join('\r\n'));assert.equal(sameFileRows.preview.duplicates,2);
const malformed=await stage('Employee Code,WRONG HEADER\nEMP-001,x');assert.equal(malformed.preview.invalid,1);assert.equal((await detail(malformed.id,true)).sourceBase64.replace(/\s/g,''),Buffer.from('Employee Code,WRONG HEADER\nEMP-001,x').toString('base64'));
const blank=await stage(historicalTemplate('punches','Bakebe - SM Aura',[{code:'EMP-001'}],'2026-09-10'));assert.equal(blank.preview.invalid,1);assert.match(blank.preview.rows[0].errors.join(' '),/Punch Time/);
await actor(12);await detail(b.id);await assert.rejects(()=>stage(punch),/required/);await assert.rejects(()=>commit(b.id),/authorized/);
await actor(11);const finance=await stage(dtr.replace('2026-09-09','2026-09-08'),'dtr');assert.equal((await commit(finance.id)).imported,1);
await actor(9);await assert.rejects(()=>stage(punch,'punches',id(20)),/required/);await assert.rejects(()=>stage(punch,'live'),/Choose/);await assert.rejects(()=>db.query("update payroll_history_private.batches set mode='live'"),/permission denied/);await assert.rejects(()=>db.query("insert into payroll_history_private.records(scope_id) values($1)",[id(10)]),/permission denied/);
await db.exec('reset role');await assert.rejects(()=>db.query("update payroll_history_private.batches set filename='changed.csv' where id=$1",[b.id]),/immutable/);await assert.rejects(()=>db.query('delete from payroll_history_private.records'),/immutable/);await db.exec('set role authenticated');
assert.deepEqual(await protectedCounts(),before,'test imports must not write live data or create payroll packages');
await assert.rejects(()=>db.query('select correct_genuine_historical_attendance($1,$2,$3,0,$4,$5,false)',[id(10),id(1),'2026-09-10','[]','Verified actual source']),/Explicit authorization/);
await assert.rejects(()=>db.query('select correct_genuine_historical_attendance($1,$2,$3,0,$4,$5,true)',[id(10),summary.id,'2026-09-10','[]','No batch promotion']),/Explicit authorization/);
await actor(11);await assert.rejects(()=>db.query('select correct_genuine_historical_attendance($1,$2,$3,0,$4,$5,true)',[id(10),id(1),'2026-09-10','[]','Verified actual source']),/Explicit authorization/);
await actor(9);assert.equal((await db.query('select correct_genuine_historical_attendance($1,$2,$3,0,$4,$5,true) r',[id(10),id(1),'2026-09-10','[]','Verified actual source'])).rows[0].r.corrected,true);
await db.exec('reset role;set role anon');await assert.rejects(()=>detail(b.id),/permission denied/);
await db.close();console.log('PASS: actual punches and DTR summaries; exact/semantic duplicates; employee/BU/date errors; overnight/timezone handling; original source/audit retention; scope/role protections; unchanged live data; separately authorized corrections.');
