import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite(); const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
await db.exec(`create role authenticated;create role anon;create schema auth;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
create function current_hris_user_id() returns uuid language sql stable as $$select auth.uid()$$;
create function has_feature_permission(text,text) returns boolean language sql stable as $$select auth.uid()='${id(1)}'::uuid$$;
create function can_access_hris_user(uuid) returns boolean language sql stable as $$select $1<>'${id(9)}'::uuid$$;
create table hris_users(id uuid primary key,email text,status text,role text,account_inactivated_at timestamptz,end_date date,is_duplicate boolean,employment_status text,business_unit_id uuid,reports_to uuid,employee_id text,created_at timestamptz default now());
create table audit_logs(user_id text,user_email text,action text,entity text,entity_id text,details text,created_at timestamptz default now());
create table rbac_audit_log(target_user_id uuid,action text);
insert into hris_users(id,status,role) values('${id(1)}','Active','HR Manager'),('${id(2)}','Inactive','Employee'),('${id(3)}','Inactive','Employee'),('${id(4)}','Inactive','Employee'),('${id(5)}','Inactive','Employee'),('${id(6)}','Inactive','Employee'),('${id(9)}','Inactive','Employee');
update hris_users set account_inactivated_at=now() where id='${id(3)}';
insert into rbac_audit_log select id,'SELF_REGISTRATION' from hris_users;
insert into audit_logs(action,entity,entity_id,details) values('DELETE','UserRegistration','${id(4)}','Rejected and deleted new user registration.'),('APPROVE','UserRegistration','${id(5)}','Approved');`);
const migration=fs.readFileSync('supabase/migrations/20260915071343_hr_registration_queue_persistence.sql','utf8');
await db.exec(migration.split('-- Existing secure self-registration')[0]);
assert.match(migration,/registration_status,\s+auth_user_id/);assert.match(migration,/'Pending',\s+p_auth_user_id/);
await db.exec(`grant select,update on hris_users to authenticated;select set_config('test.actor','${id(1)}',false);set role authenticated;`);
const queue=async()=>(await db.query('select id from get_pending_registrations()')).rows.map(r=>r.id);
assert.deepEqual(await queue(),[id(2),id(6)]);
await assert.rejects(()=>db.query("update hris_users set registration_status='Pending' where id=$1",[id(4)]),/review action/);
await assert.rejects(()=>db.query("select review_registration($1,'Rejected','')",[id(2)]),/reason/);
assert.equal((await db.query("select review_registration($1,'Rejected','Duplicate registration') result",[id(2)])).rows[0].result,'Rejected');
assert.deepEqual(await queue(),[id(6)]); // fresh server query
await assert.rejects(()=>db.query("select review_registration($1,'Approved',null,$2,'E2')",[id(2),id(1)]),/no longer/);
await assert.rejects(()=>db.query("select review_registration($1,'Rejected','Duplicate')",[id(9)]),/permission/);
await db.query("select review_registration($1,'Approved',null,$2,'E6')",[id(6),id(1)]);
assert.deepEqual(await queue(),[]);
await db.exec('reset role');
assert.equal((await db.query('select count(*)::int n from hris_users')).rows[0].n,7);
assert.equal((await db.query('select status from hris_users where id=$1',[id(3)])).rows[0].status,'Inactive');
assert.equal((await db.query("select count(*)::int n from audit_logs where action='REJECT'")).rows[0].n,1);
await db.exec(`select set_config('test.actor','${id(2)}',false);set role authenticated;`);
await assert.rejects(()=>queue(),/permission/);
await db.exec('reset role;set role anon');await assert.rejects(()=>queue(),/permission denied/);
console.log('PASS: lifecycle exclusion, legacy rejection, persistent decisions, approval, stale retry, required reason, scope, unauthorized access, immutable review status, retained profiles and audit.');
await db.close();
