import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
process.on('uncaughtException',e=>{console.error(e.message,e.where||'');process.exit(1);});
const db=new PGlite();
const extract=(path,name,delimiter)=>{const sql=fs.readFileSync(path,'utf8');const start=sql.toLowerCase().indexOf(`function private.${name}(`);const open=sql.indexOf(delimiter,start),end=sql.indexOf(delimiter,open+delimiter.length);return 'create or replace '+sql.slice(start,end+delimiter.length)+';';};
await db.exec('create schema private');
await db.exec(extract('supabase/migrations/20260906112648_payroll_schedule_versions.sql','payroll_schedule_validate','$$'));
let interpreter=extract('supabase/migrations/20260907015502_confirmed_hr_payroll_rules.sql','interpret_payroll_time','$function$').replace('private.interpret_payroll_time(', 'private.interpret_payroll_time_before_ob(');
interpreter=interpreter.replace("(value->>'timestamp')::timestamptz>=ws-interval '4 hours' and (value->>'timestamp')::timestamptz<=we+interval '8 hours'", "((value->>'importWorkDate'=d::text) or (value->>'importWorkDate' is null and (value->>'timestamp')::timestamptz>=ws-interval '4 hours' and (value->>'timestamp')::timestamptz<=we+interval '8 hours'))");
await db.exec(interpreter);
await db.exec(fs.readFileSync('supabase/migrations/20260929124000_imported_day_event_boundaries.sql','utf8'));
const emp='00000000-0000-4000-8000-000000000004';
const source={employees:[{id:emp,name:'Fixture',hireDate:'2020-01-01',status:'Active'}],rules:[{id:'rule',revision:1,effective_from:'2026-01-01',effective_to:'2026-12-31',config:{holidayCoverageConfirmed:true,splitShiftConfirmed:true,restTemplates:[],meals:{}}}],shifts:[{id:'shift',employeeId:emp,date:'2026-08-29',templateId:'fixture',start:'09:00',end:'18:00',breakMinutes:60,kind:'work',endDayOffset:0,paidMinutes:480,published:true}],scheduleDays:[{employeeId:emp,date:'2026-08-29',status:'published'}],actualAttendanceDays:[{employeeId:emp,date:'2026-08-29'}],leave:[],ot:[],holidays:[],wfh:[],leavePolicies:[],events:[]};
for(const [type,time] of [['CLOCK_IN','09:00'],['START_BREAK','12:00'],['END_BREAK','13:00'],['CLOCK_OUT','18:00']])source.events.push({id:type,employeeId:emp,type,timestamp:`2026-08-29T${time}:00+08:00`,importWorkDate:'2026-08-29'});
source.shifts.push({...source.shifts[0],id:'next-shift',date:'2026-08-30',start:'01:00',end:'10:00'});
source.events.push({id:'neighbor',employeeId:emp,type:'CLOCK_IN',timestamp:'2026-08-30T01:00:00+08:00'});
const calc=async()=>(await db.query("select private.interpret_payroll_time_before_ob($1,'2026-08-29','2026-08-29') r",[source])).rows[0].r.rows[0];
let row=await calc();assert.equal(row.ready,true,JSON.stringify(row.issues));assert.equal(row.regularMinutes,480);assert.equal(row.actualMinutes,480);assert.ok(!row.eventIds.includes('neighbor'));
source.events.find(e=>e.type==='CLOCK_OUT').timestamp='2026-08-29T20:00:00+08:00';
source.ot=[{id:'approved-ot',employeeId:emp,date:'2026-08-29',start:'18:00',end:'20:00',type:'Paid',status:'Approved',approvedHours:1}];
row=await calc();assert.equal(row.actualOtMinutes,60,'Only one approved hour is payroll eligible');assert.equal(row.actualMinutes,600,'Actual evidence remains intact');assert.equal(row.ready,false,'Extra actual time still requires a separate decision');
source.actualAttendanceDays=[];source.events.forEach(e=>delete e.importWorkDate);row=await calc();assert.ok(row.issues.includes('Adjacent shifts share a punch window — review boundaries'),'Unassigned raw punches retain boundary review');
await db.close();console.log('PASS: imported day ownership, adjacent shift separation, break deducted once, approved OT cap, raw boundary review preserved.');
