import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createServer} from 'vite';
import react from '@vitejs/plugin-react';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright');
import {createMaintenanceFixture,id} from './maintenanceFixture.mjs';
const db=await createMaintenanceFixture();
const methods={ops_workspace:['p_unit'],ops_save_template:['p_id','p_unit','p_kind','p_content','p_revision','p_publish'],ops_assign:['p_unit','p_version','p_selection','p_due','p_priority','p_instructions','p_attachments','p_verify'],import_assets_batch:['p_rows'],ops_save_rule:['p_id','p_unit','p_title','p_version','p_config','p_status','p_revision','p_note'],ops_maintenance_workspace:['p_unit','p_from','p_to','p_offset','p_filters'],ops_maintenance_preview:['p_unit','p_version','p_config','p_from'],ops_retry_rule:['p_id'],ops_automation_workspace:['p_unit','p_date'],ops_save_response:['p_item','p_revision','p_value','p_remarks','p_issue','p_note'],ops_submit_run:['p_run','p_revision'],ops_occurrence_action:['p_id','p_revision','p_action','p_employee','p_note','p_payload']};
const harness=`import React from 'react';import {createRoot} from 'react-dom/client';import {BrowserRouter} from 'react-router-dom';import {AuthContext} from '/context/AuthContext.tsx';import {PermissionsContext} from '/context/PermissionsContext.tsx';import {SettingsContext} from '/context/SettingsContext.tsx';import AssetManagement from '/pages/employees/AssetManagement.tsx';import OperationsStation from '/pages/OperationsStation.tsx';const user={id:window.__TEST_ACTOR,name:'BOD',email:'bod@example.test',businessUnitId:window.__TEST_UNIT};const assetPage=location.pathname.includes('assets');const permission={authorized:true,roles:['Board of Director'],dataScope:{type:window.__TEST_SCOPE||'GLOBAL'},features:{Assets:window.__TEST_SCOPE?['view']:['manage']}};createRoot(document.getElementById('root')).render(React.createElement(BrowserRouter,null,React.createElement(AuthContext.Provider,{value:{user,loading:false,authError:null}},React.createElement(PermissionsContext.Provider,{value:{effectiveRbac:permission,loadingPermissions:false,authorizationError:null}},React.createElement(SettingsContext.Provider,{value:{settings:{},approverConfigs:{}}},React.createElement(assetPage?AssetManagement:OperationsStation))))));`;
const server=await createServer({configFile:false,root:process.cwd(),plugins:[react(),{name:'asset-test',configureServer(s){s.middlewares.use(async(req,res,next)=>{if(req.url?.startsWith('/__test-')){res.setHeader('Content-Type','text/html');res.end(await s.transformIndexHtml(req.url,'<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><script src="/__tailwind.js"></script></head><body style="margin:0;padding:24px;background:#f1f5f9"><div id="root"></div><script type="module" src="/__asset-test.tsx"></script></body></html>'));}else if(req.url==='/__tailwind.js'){res.setHeader('Content-Type','text/javascript');res.end(fs.readFileSync('/tmp/tng-ops-tailwind.js'));}else next();});},resolveId(source){if(source==='/__asset-test.tsx')return '\0asset-test.tsx';},load(source){if(source==='\0asset-test.tsx')return harness;}}],define:{'import.meta.env.VITE_SUPABASE_URL':JSON.stringify('https://asset-test.invalid'),'import.meta.env.VITE_SUPABASE_ANON_KEY':JSON.stringify('test-key')},server:{host:'127.0.0.1',port:3191,strictPort:true}});
await server.listen();const browser=await chromium.launch({headless:true,executablePath:process.env.TNG_TEST_CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});let queue=Promise.resolve();const errors=[];
async function pageFor(actor=10,scope='',viewport={width:1440,height:1000}){const context=await browser.newContext({viewport,acceptDownloads:true});await context.addInitScript(({actor,scope,unit})=>{window.__TEST_ACTOR=actor;window.__TEST_SCOPE=scope;window.__TEST_UNIT=unit;},{actor:id(actor),scope,unit:id(1)});const page=await context.newPage();page.on('pageerror',e=>(errors.push(e.message),console.error('Page error:',e.message)));page.on('dialog',d=>d.dismiss());await page.route('https://asset-test.invalid/**',async route=>{const req=route.request(),url=new URL(req.url()),name=url.pathname.split('/').pop();const headers={'access-control-allow-origin':'*','access-control-allow-headers':'*'};if(req.method()==='OPTIONS'){await route.fulfill({status:200,headers});return;}queue=queue.then(async()=>{try{await db.exec(`reset role;set test.actor='${id(actor)}';set role authenticated`);let result;
 if(url.pathname.includes('/rpc/')){
  if(name==='get_accessible_hris_users'){await db.exec('reset role');result=(await db.query('select * from hris_users')).rows;}
  else if(methods[name]){const params=req.postDataJSON();result=(await db.query(`select public.${name}(${methods[name].map((_,i)=>'$'+(i+1)).join(',')}) r`,methods[name].map(k=>k==='p_value'?JSON.stringify(params[k]??null):(params[k]??null)))).rows[0].r;}
  else throw new Error('Unhandled RPC '+name);
 }else if(req.method()==='GET'){
  if(['assets','business_units','hris_users','asset_assignments'].includes(name)){if(name!=='assets')await db.exec('reset role');result=(await db.query(`select * from public.${name}`)).rows;}
  else throw new Error('Unhandled table '+name);
 }else if(name==='assets'){
  const payload=req.postDataJSON();const keys=Object.keys(payload);assert.ok(keys.every(k=>/^[a-z_]+$/.test(k)));const values=Object.values(payload);const updated=url.searchParams.get('id')?.replace(/^eq\./,'');result=updated?(await db.query(`update assets set ${keys.map((k,i)=>k+'=$'+(i+1)).join(',')} where id=$${keys.length+1} returning *`,[...values,updated])).rows[0]:(await db.query(`insert into assets(${keys.join(',')}) values(${keys.map((_,i)=>'$'+(i+1)).join(',')}) returning *`,values)).rows[0];if(!result)throw new Error('Asset write not authorized');
 }else if(name==='audit_logs'){await db.exec('reset role');const p=req.postDataJSON();await db.query('insert into audit_logs(user_id,user_email,action,entity,entity_id,details) values($1,$2,$3,$4,$5,$6)',[p.user_id,p.user_email,p.action,p.entity,p.entity_id,p.details]);result=null;}
 else throw new Error('Unhandled mutation '+name);
 await route.fulfill({status:200,headers,contentType:'application/json',body:JSON.stringify(result)});
 }catch(e){await route.fulfill({status:400,headers,contentType:'application/json',body:JSON.stringify({message:e.message,code:e.code})});}});await queue;});return page;}
async function nav(p,label){const desktop=p.getByRole('navigation',{name:'Operations desktop navigation'});if(await desktop.isVisible())await desktop.getByRole('button',{name:label,exact:true}).click();else await p.getByRole('navigation',{name:'Operations workspace tools'}).getByRole('button',{name:label,exact:true}).click();}
try{
 const day=(await db.query("select (now() at time zone 'Asia/Manila')::date::text d")).rows[0].d;
 await db.exec(`set test.actor='${id(11)}'`);const tid=(await db.query("select ops_save_template(null,$1,'checklist',$2,null,true) id",[id(1),{title:'Generic maintenance checks',items:[{snapshot:{title:'Clean exterior'},required:true,response_type:'none'},{snapshot:{title:'Record temperature',unit:'C'},required:true,response_type:'numeric'}]}])).rows[0].id;
 await db.query("insert into assets(id,name,business_unit_id,asset_tag,type,requires_maintenance) values($1,'Bar freezer',$2,'FREEZER-A','Equipment',true),($3,'Other BU asset',$4,'B-01','Equipment',true)",[id(52),id(1),id(53),id(2)]);
 for(const emp of [13,15])await db.query("insert into payroll_schedule_publications(employee_id,business_unit_id,effective_from,effective_to,snapshot) values($1,$2,$3,$3,$4)",[id(emp),id(1),day,[{date:day,kind:'work',start:'08:00',end:'17:00'}]]);
 const p=await pageFor(11,'HOME_ONLY');await p.goto('http://127.0.0.1:3191/__test-operations');await p.getByLabel('Business-unit workspace').selectOption(id(1));await nav(p,'Maintenance');await p.getByRole('button',{name:'Create maintenance plan',exact:true}).waitFor();await p.getByRole('button',{name:'Create maintenance plan',exact:true}).click();
 assert.ok(!(await p.getByLabel('Maintenance asset',{exact:true}).locator('option').allTextContents()).some(x=>x.includes('Other BU')));await p.getByLabel('Rule title',{exact:true}).fill('Daily freezer cleaning');await p.getByLabel('Published task or checklist',{exact:true}).selectOption({label:'Generic maintenance checks · published v1'});await p.getByRole('checkbox',{name:'Employee A · Staff',exact:true}).check();await p.getByRole('checkbox',{name:'Supervisor A · Supervisor',exact:true}).check();await p.getByLabel('Preferred owner',{exact:true}).selectOption(id(13));await p.getByLabel('Rule status',{exact:true}).selectOption('Active');await p.getByRole('button',{name:'Preview next 12 occurrences',exact:true}).click();await p.getByText('Generation preview',{exact:true}).waitFor();await p.getByRole('button',{name:'Save maintenance plan',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});await p.getByRole('heading',{name:'Daily freezer cleaning',exact:true}).waitFor();await p.reload();await nav(p,'Maintenance');await p.getByRole('navigation',{name:'Maintenance navigation'}).getByRole('button',{name:'Maintenance Plans',exact:true}).click();await p.getByRole('heading',{name:'Daily freezer cleaning',exact:true}).waitFor();const e=await pageFor(13,'HOME_ONLY',{width:390,height:844});await e.goto('http://127.0.0.1:3191/__test-operations');await e.getByLabel('Business-unit workspace').selectOption(id(1));await e.getByText('No assignments yet',{exact:true}).waitFor();assert.equal(await e.getByRole('button',{name:/Daily freezer cleaning/}).count(),0);await p.getByRole('button',{name:'Generate / retry now',exact:true}).click();await e.getByRole('button',{name:/Daily freezer cleaning/}).first().waitFor({timeout:45000});await p.getByRole('navigation',{name:'Maintenance navigation'}).getByRole('button',{name:'Service History',exact:true}).click();await p.getByRole('button',{name:'View findings & audit',exact:true}).first().waitFor();await p.screenshot({path:'/tmp/tng-maintenance-service-desktop.png',fullPage:true});
 // Employee execution is the existing shared checklist, with frozen maintenance context.
 await e.getByRole('navigation',{name:'Operations bottom navigation'}).getByRole('button',{name:'Tasks',exact:true}).click();for(const term of ['Daily freezer cleaning','FREEZER-A','Bar freezer','Generic maintenance checks']){await e.getByLabel('Search assignments').fill(term);await e.getByRole('button',{name:/Daily freezer cleaning/}).first().waitFor();}await e.getByLabel('Search assignments').fill('');await e.getByRole('button',{name:/Daily freezer cleaning/}).first().click();await e.getByRole('heading',{name:'Maintenance · Bar freezer · FREEZER-A',exact:true}).waitFor();await e.getByRole('checkbox',{name:'Confirm Clean exterior',exact:true}).check();await e.getByRole('button',{name:'Save response',exact:true}).first().click();await e.getByText('Employee A ·',{exact:false}).first().waitFor();await e.getByLabel('Reading: Record temperature (C)',{exact:true}).fill('7');await Promise.all([e.waitForResponse(r=>r.url().endsWith('/rpc/ops_workspace')),e.evaluate(()=>window.dispatchEvent(new Event('focus')))]);await e.getByText('Shared team execution · 1 / 2 answered',{exact:true}).waitFor();assert.equal(await e.getByLabel('Reading: Record temperature (C)',{exact:true}).inputValue(),'7');e.removeAllListeners('dialog');e.on('dialog',d=>d.accept());await e.getByRole('button',{name:'Close modal',exact:true}).click();await e.getByRole('dialog').waitFor({state:'hidden'});await e.getByRole('navigation',{name:'Operations bottom navigation'}).getByRole('button',{name:'Today',exact:true}).click();
 const h=await pageFor(15,'HOME_ONLY');await h.goto('http://127.0.0.1:3191/__test-operations');await h.getByLabel('Business-unit workspace').selectOption(id(1));await h.getByRole('button',{name:/Daily freezer cleaning/}).first().click();await h.getByLabel('Reading: Record temperature (C)',{exact:true}).fill('4');await h.getByRole('button',{name:'Save response',exact:true}).nth(1).click();await h.getByRole('button',{name:'Submit work',exact:true}).click();await h.getByText('Submitted — not independently verified.',{exact:true}).waitFor();
 await p.getByRole('button',{name:'Refresh maintenance',exact:true}).click();await p.getByRole('button',{name:'View findings & audit',exact:true}).last().click();await p.getByText('Employee A ·',{exact:false}).first().waitFor();await p.getByText('Supervisor A ·',{exact:false}).first().waitFor();await p.getByRole('button',{name:'Close modal',exact:true}).click();const download=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Export service history CSV',exact:true}).click()]);const csv=fs.readFileSync(await download[0].path(),'utf8');assert.match(csv,/FREEZER-A/);assert.match(csv,/Completed/);assert.match(csv,/Employee A/);assert.match(csv,/Supervisor A/);
 await queue;await db.exec('reset role');await db.query('update assets set requires_maintenance=false where id=$1',[id(52)]);await p.getByRole('navigation',{name:'Maintenance navigation'}).getByRole('button',{name:'Maintenance Plans',exact:true}).click();await p.getByText('Blocked: Requires maintenance disabled',{exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Generate / retry now',exact:true}).isDisabled(),true);
 await e.reload();await e.getByRole('navigation',{name:'Operations bottom navigation'}).getByRole('button',{name:'Tasks',exact:true}).click();await e.getByRole('button',{name:'Completed',exact:true}).click();await e.getByRole('button',{name:/Daily freezer cleaning/}).first().click();await e.getByText('Submitted — not independently verified.',{exact:true}).waitFor();assert.equal(await e.getByRole('button',{name:'Submit work',exact:true}).count(),0);await e.getByRole('button',{name:'Close modal',exact:true}).click();await e.getByRole('button',{name:'Maintenance',exact:true}).click();await e.getByRole('navigation',{name:'Maintenance navigation'}).waitFor();assert.equal(await e.getByRole('button',{name:'Create maintenance plan',exact:true}).count(),0);assert.equal(await e.getByRole('link',{name:'Add / edit assets',exact:true}).count(),0);await e.getByRole('navigation',{name:'Maintenance navigation'}).getByRole('button',{name:'Service History',exact:true}).click();await e.getByRole('button',{name:'View findings & audit',exact:true}).first().waitFor();assert.ok(await e.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await e.screenshot({path:'/tmp/tng-maintenance-service-mobile.png',fullPage:true});
 const other=await pageFor(12,'HOME_ONLY');await other.goto('http://127.0.0.1:3191/__test-operations');await other.getByLabel('Business-unit workspace').selectOption(id(2));await nav(other,'Maintenance');await other.getByRole('navigation',{name:'Maintenance navigation'}).getByRole('button',{name:'Maintenance Plans',exact:true}).click();await other.getByText('No authorized maintenance plans yet.',{exact:true}).waitFor();assert.equal(await other.getByRole('heading',{name:'Daily freezer cleaning',exact:true}).count(),0);assert.deepEqual(errors,[]);
 console.log('Maintenance browser passed: integrated navigation, eligible BU assets, published version preview, plan creation/calendar preview, persistence, generation appearing automatically in Today without refresh, maintenance title/asset search in My Tasks, unsaved edits preserved on focus, direct mobile/desktop shared execution and normal Completed filter by two contributors, completed service history/CSV, eligibility block UI, employee action restrictions and BU isolation.');
}catch(e){console.error(e);for(const c of browser.contexts())for(const p of c.pages()){console.error((await p.locator('body').innerText()).slice(-1800));await p.screenshot({path:'/tmp/tng-maintenance-browser-failure.png',fullPage:true});}process.exitCode=1;}finally{await browser.close();await server.close();await db.close();}
