import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {PGlite} from '@electric-sql/pglite';import {createMaintenanceFixture,id} from './maintenanceFixture.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tng-maint-plans-'));let db=await createMaintenanceFixture(dir);
const actor=async n=>db.exec(`reset role;set request.jwt.claim.sub='';set request.jwt.claims='';set test.actor='${id(n)}';set role authenticated`);
const rpc=async(n,a=[])=> (await db.query(`select public.${n}(${a.map((_,i)=>'$'+(i+1)).join(',')}) result`,n==='ops_save_response'?a.map((v,i)=>i===2?JSON.stringify(v):v):a)).rows[0].result;
const today=(await db.query("select (now() at time zone 'Asia/Manila')::date::text d")).rows[0].d;
const config={frequency:'daily',interval:1,start_date:today,end_date:'',mode:'shift',execution:'shared',timezone:'Asia/Manila',anchor:'fixed',start_time:'08:00',end_time:'12:00',due_time:'11:30',end_day_offset:0,due_day_offset:0,employee_ids:[id(13),id(15)],backup_ids:[id(15)],preferred_owner:id(13),auto_backup:true,allow_claim:true,weekdays:[1,2,3,4,5],month_day:31,short_month:'last',horizon_days:2,grace_minutes:15,remind_before:30,overdue_every:120,priority:'Normal',maintenance:{asset_id:id(52),category:'Cleaning',description:'Clean per manufacturer manual',sop_url:'https://example.test/manual',estimated_minutes:30,responsible_manager_id:id(11)}};
const work=()=>rpc('ops_maintenance_workspace',[id(1),today,'2027-12-31',0,{}]);
const save=(name,c=config,status='Active',existing=null,rev=null,version=ver)=>rpc('ops_save_rule',[existing,id(1),name,version,c,status,rev,existing?'Reviewed plan change':'']);
let ver,plan,second;
try{
 await db.exec(`insert into assets(id,name,asset_tag,type,business_unit_id,requires_maintenance) values('${id(52)}','Bar air conditioner','AC-A','Equipment','${id(1)}',true),('${id(53)}','Unit B freezer','FREEZER-B','Equipment','${id(2)}',true),('${id(54)}','Bar freezer','FREEZER-A','Equipment','${id(1)}',true);`);
 await actor(11);const t=await rpc('ops_save_template',[null,id(1),'checklist',{title:'Generic cleaning checklist',items:[{snapshot:{title:'Clean filter'},required:true,response_type:'yes_no'},{snapshot:{title:'Temperature reading',unit:'C'},required:true,response_type:'numeric'}]},null,true]);ver=(await rpc('ops_workspace',[id(1)])).templates.find(x=>x.id===t).versions[0].id;
 for(const emp of [13,15]){await db.exec('reset role');await db.query("insert into payroll_schedule_publications(employee_id,business_unit_id,effective_from,effective_to,snapshot) values($1,$2,$3,$3,$4)",[id(emp),id(1),today,[{date:today,kind:'work',start:'08:00',end:'17:00'}]]);}await actor(11);
 await assert.rejects(()=>save('Wrong BU',{...config,maintenance:{...config.maintenance,asset_id:id(53)}}),/transferred/);
 await assert.rejects(()=>save('Unmarked',{...config,maintenance:{...config.maintenance,asset_id:id(51)}}),/disabled/);
 const custom=await rpc('ops_save_template',[null,id(1),'task',{title:'Freezer only',asset_id:id(54)},null,true]);const cv=(await rpc('ops_workspace',[id(1)])).templates.find(x=>x.id===custom).versions[0].id;await assert.rejects(()=>save('Wrong linked asset',config,'Active',null,null,cv),/different asset/);
 let preview=await rpc('ops_maintenance_preview',[id(1),ver,config,today]);assert.equal(preview.length,12);assert.equal(preview[0].date,today);
 plan=await save('AC filter cleaning');second=await save('AC inspection',{...config,frequency:'weekly',weekdays:[1,2,3,4,5,6,7]});const freezer=await save('Freezer cleaning',{...config,maintenance:{...config.maintenance,asset_id:id(54)}});const draft=await save('Draft plan',config,'Draft');await rpc('ops_retry_rule',[draft]);assert.ok(!(await work()).records.some(o=>o.rule_id===draft));
 for(const p of [plan,second,freezer])await rpc('ops_retry_rule',[p]);let data=await work();assert.equal(data.plans.length,4);let occ=data.records.find(o=>o.rule_id===plan&&o.operating_date===today);assert.equal(occ.asset.id,id(52));assert.equal(occ.asset.asset_tag,'AC-A');assert.equal(occ.assignments.length,2);assert.equal(new Set(occ.assignments.map(a=>a.execution.id)).size,1);assert.ok(data.records.some(o=>o.rule_id===freezer&&o.asset.id===id(54)));
 const count=data.records.length;await rpc('ops_retry_rule',[plan]);assert.equal((await work()).records.length,count);
 // Calendar previews: explicit dates, explicit annual months, leap and last-day behavior.
 const annual={...config,frequency:'annual_dates',times_per_year:4,annual_dates:[{month:1,day:15},{month:4,day:15},{month:7,day:15},{month:10,day:15}],start_date:'2026-01-01'};preview=await rpc('ops_maintenance_preview',[id(1),ver,annual,'2026-01-01']);assert.deepEqual(preview.slice(0,4).map(p=>p.date),['2026-01-15','2026-04-15','2026-07-15','2026-10-15']);await assert.rejects(()=>save('Annual invalid',{...annual,times_per_year:3}),/match explicit/);
 preview=await rpc('ops_maintenance_preview',[id(1),ver,{...config,frequency:'dates',service_dates:['2026-11-01','2027-02-15']},today]);assert.deepEqual(preview.map(p=>p.date),['2026-11-01','2027-02-15']);
 const rec=async(c,d)=>(await db.query('select operations_private.recurrence_due($1,$2) result',[c,d])).rows[0].result;await db.exec('reset role');assert.equal(await rec({...config,frequency:'yearly',start_date:'2028-02-29'},'2029-02-28'),true);assert.equal(await rec({...config,frequency:'yearly',start_date:'2028-02-29',short_month:'skip'},'2029-02-28'),false);assert.equal(await rec({...config,frequency:'monthly',start_date:'2026-01-31'},'2026-02-28'),true);
 // Existing generated work is immutable when a future plan changes schedule or published version.
 await actor(11);await save('AC filter cleaning updated',{...config,due_time:'10:00',frequency:'weekly',weekdays:[1]},'Active',plan,1);await rpc('ops_retry_rule',[plan]);let frozen=(await work()).records.find(o=>o.id===occ.id);assert.equal(frozen.due_at,occ.due_at);assert.equal(frozen.title,'AC filter cleaning');assert.equal(frozen.asset.activity,'AC filter cleaning');assert.equal(frozen.status,'Open');await assert.rejects(()=>save('Stale change',config,'Active',plan,1),/changed/);
 // Shared contributor responses and concurrency. Submission immediately appears in service history.
 await actor(13);let own=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.occurrence_id===occ.id&&a.assignee_id===id(13));assert.equal(own.maintenance.asset_tag,'AC-A');await rpc('ops_save_response',[own.execution.items[0].id,1,'yes','Filter clear',false,'']);await actor(15);let helper=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.occurrence_id===occ.id&&a.assignee_id===id(15));await assert.rejects(()=>rpc('ops_save_response',[helper.execution.items[0].id,1,'no','',false,'']),/changed/);await rpc('ops_save_response',[helper.execution.items[1].id,1,24,'Reading high',true,'']);await actor(13);own=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.id===own.id);await rpc('ops_submit_run',[own.execution.id,own.execution.revision]);assert.equal((await work()).records.find(o=>o.id===occ.id).status,'Completed');
 // Evidence expiry preserves completed status and actor/response history.
 await db.exec('reset role');const item=own.execution.items[0].id;await db.query("insert into ops_evidence(item_id,uploader_id,uploader_name,path,bytes,state,created_at,uploaded_at,expires_at) values($1,$2,'Employee A','qa/photo.jpg',1000,'Ready',now()-interval '61 days',now()-interval '61 days',now()-interval '1 day') returning id",[item,id(13)]);const evidence=(await db.query('select id from ops_evidence where item_id=$1',[item])).rows[0].id;await db.query('select public.ops_cleanup_record($1,null)',[evidence]);await actor(11);let history=(await work()).records.find(o=>o.id===occ.id);assert.equal(history.status,'Completed');assert.equal(history.assignments[0].execution.items[0].evidence[0].state,'Expired');assert.equal(history.assignments[0].execution.items[0].response.actor_name,'Employee A');assert.equal((await rpc('ops_maintenance_workspace',[id(1),today,'2027-12-31',0,{issues:true}])).records.length,1);
 // Uncovered window and notifications remain authoritative; retries cannot duplicate.
 const uncovered=await save('No shift maintenance',{...config,start_time:'19:00',end_time:'22:00',due_time:'21:00'});await rpc('ops_retry_rule',[uncovered]);data=await work();const noStaff=data.records.find(o=>o.rule_id===uncovered&&o.operating_date===today);assert.equal(noStaff.assignments.length,0);assert.ok(['Uncovered','Schedule missing','No owner','At risk'].includes(noStaff.coverage));
 // Pause, cancellation, retirement/opt-out/transfer guards and history isolation.
 await save('AC inspection',config,'Paused',second,1);await rpc('ops_retry_rule',[second]);let automation=await rpc('ops_automation_workspace',[id(1),today]);const other=automation.occurrences.find(o=>o.rule_id===second);await rpc('ops_occurrence_action',[other.id,other.revision,'cancel',null,'Activity not needed today',{}]);assert.equal((await work()).records.find(o=>o.id===other.id).status,'Cancelled');
 await db.exec('reset role');await db.query('update assets set requires_maintenance=false where id=$1',[id(52)]);await actor(11);data=await work();let blocked=data.plans.find(p=>p.id===plan);assert.equal(blocked.status,'Paused');assert.match(blocked.blocked_reason,/disabled/);await rpc('ops_retry_rule',[plan]);assert.equal((await work()).records.find(o=>o.id===occ.id).status,'Completed');await assert.rejects(()=>save('Reactivate',blocked.config,'Active',plan,blocked.revision),/disabled/);
 await db.exec('reset role');const notices=(await db.query("select count(*)::int n from notifications where dedupe_key like 'ops-maintenance:%'")).rows[0].n;await db.query('update assets set requires_maintenance=false where id=$1',[id(52)]);assert.equal((await db.query("select count(*)::int n from notifications where dedupe_key like 'ops-maintenance:%'")).rows[0].n,notices);await db.query('update assets set requires_maintenance=true where id=$1',[id(52)]);await actor(11);blocked=(await work()).plans.find(p=>p.id===plan);assert.match(blocked.blocked_reason,/disabled/);await save(blocked.title,blocked.config,'Active',plan,blocked.revision);assert.equal((await work()).plans.find(p=>p.id===plan).blocked_reason,null);
 await db.exec('reset role');await db.query("update assets set status='Retired' where id=$1",[id(52)]);await actor(11);assert.match((await work()).plans.find(p=>p.id===plan).blocked_reason,/retired/);
 await db.exec('reset role');await db.query("update assets set status='Available',business_unit_id=$2 where id=$1",[id(52),id(2)]);await actor(12);assert.equal((await rpc('ops_maintenance_workspace',[id(2),today,'2027-12-31',0,{}])).records.length,0);await assert.rejects(()=>work(),/authorized/);await actor(16);assert.equal((await work()).records.find(o=>o.id===occ.id).asset.unit_name,'Unit A');assert.ok((await rpc('ops_maintenance_workspace',[id(2),today,'2027-12-31',0,{}])).assets.some(a=>a.id===id(52)));
 await actor(13);assert.equal((await work()).plans.length,0);assert.equal((await work()).assets.length,0);await assert.rejects(()=>save('Employee attack'),/authorized/);await assert.rejects(()=>db.query("update ops_rules set status='Active' where id=$1 returning id",[plan]),/permission/);
 await db.exec('reset role;set role anon');await assert.rejects(()=>work(),/permission/);
 await db.close();db=new PGlite(dir);await actor(11);data=await work();assert.equal(data.records.find(o=>o.id===occ.id).status,'Completed');assert.match(data.plans.find(p=>p.id===plan).blocked_reason,/transferred/);assert.equal(data.records.find(o=>o.id===other.id).status,'Cancelled');
 console.log('Maintenance database passed: multiple activities/assets, draft, calendar previews, generation idempotency, frozen plan context, shared actors/concurrent writes, completed history and expired evidence, uncovered staffing, cancellation/pause, retirement/transfer/opt-out, manager review, deduped notices, BU isolation, multi-unit access, employee mutation denial, persistence.');
}catch(e){console.error(e.message,e.where,e.detail,e.stack);process.exitCode=1;}finally{await db.close();fs.rmSync(dir,{recursive:true,force:true});}
