import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = path => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const awardModal = read('components/evaluation/AssignAwardModal.tsx');
const awardsPage = read('pages/evaluation/Awards.tsx');
const awardService = read('services/awardService.ts');
const requisitionModal = read('components/recruitment/RequisitionModal.tsx');
const requisitionsPage = read('pages/recruitment/Requisitions.tsx');
const requisitionService = read('services/jobRequisitionService.ts');
const migration = read('supabase/migrations/20260824183000_mandatory_bod_awards_requisitions.sql');
const sequentialMigration = read('supabase/migrations/20260824210000_enforce_requisition_hr_then_bod.sql');
const triggerPermissionRepair = read('supabase/migrations/20260825170000_repair_job_requisition_private_schema_trigger.sql');

assert.match(awardService, /error\?\.code === '42703'/);
assert.match(awardModal, /filteredTemplates/);
assert.match(awardModal, /At least one active Board of Director approver is required/);
assert.match(awardModal, /Role\.GeneralManager, Role\.Manager, Role\.BusinessUnitManager/);
assert.match(awardsPage, /from\('user_roles'\)/);
assert.match(requisitionModal, /Step 1 — HR Manager Review \(required\)/);
assert.match(requisitionModal, /Step 2 — Board of Director Approval \(at least one required\)/);
assert.match(requisitionModal, /status: JobRequisitionStepStatus\.Waiting/);
assert.match(requisitionModal, /role: JobRequisitionRole\.BOD/);
assert.doesNotMatch(requisitionModal, /canApprove = !!currentUserStep \|\|/);
assert.match(requisitionsPage, /processJobRequisitionApproval\(requisitionId, 'approve'\)/);
assert.match(requisitionService, /process_job_requisition_approval/);
assert.match(requisitionService, /get_job_requisition_approval_directory/);
assert.match(migration, /add column if not exists sort_order/);
assert.match(migration, /At least one active Board of Director approver is required/);
assert.match(migration, /roleSnapshot/);
assert.match(migration, /employee_awards_bod_gate/);
assert.match(migration, /job_requisitions_bod_workflow/);
assert.match(migration, /A completed Board of Director approval is required/);
assert.match(migration, /process_job_requisition_approval/);
assert.match(migration, /status='Approved'/);
assert.match(migration, /status='PendingApproval'/);
assert.match(sequentialMigration, /An active HR Manager is required as the first requisition approval step/);
assert.match(sequentialMigration, /At least one active Board of Director approver is required after HR Manager approval/);
assert.match(sequentialMigration, /'status', 'Pending',[\s\S]*'order', 1/);
assert.match(sequentialMigration, /'status', 'Waiting'/);
assert.match(sequentialMigration, /Board of Director approval must occur after HR Manager approval/);
assert.match(triggerPermissionRepair, /enforce_job_requisition_bod_workflow\(\)[\s\S]*security definer/);
assert.match(triggerPermissionRepair, /set search_path = ''/);
assert.match(triggerPermissionRepair, /revoke all[\s\S]*from public, anon, authenticated/);
assert.doesNotMatch(triggerPermissionRepair, /grant usage on schema private/);

console.log('Mandatory BOD awards and requisitions smoke tests passed.');
