import assert from 'node:assert/strict';
import { build } from 'esbuild';
import Module,{createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
let states=[],effects=[],cursor=0,pending=[];
const same=(a,b)=>a&&b&&a.length===b.length&&a.every((x,i)=>Object.is(x,b[i]));
const hooks={useState:(v)=>{const i=cursor++;if(!(i in states))states[i]=typeof v==='function'?v():v;return[states[i],v=>{states[i]=typeof v==='function'?v(states[i]):v;}];},useRef:(v)=>{const i=cursor++;return states[i]??(states[i]={current:v});},useEffect:(fn,deps)=>{const i=cursor++;if(!same(effects[i]?.deps,deps)){pending.push(()=>{effects[i]?.cleanup?.();effects[i]={deps,cleanup:fn()};});}}};
let calls=[],gateBlocked=true;
const doc={assignmentId:'assignment',pending:true,title:'Policy',documentType:'Policy',version:1,status:'Not Opened'};
const delivery={deliveryId:'delivery',version:{title:'Policy',version_number:1,content_hash:'abc',published_at:'2026-09-09T01:00:00Z',content_snapshot:{body:'<p>Exact content</p>',files:[]}}};
const receipt={id:'receipt',employee_snapshot:{name:'Test Employee',number:'TEST'},document_snapshot:{title:'Policy',document_type:'Policy',version_number:1},first_viewed_at:'2026-09-09T01:00:00Z',acknowledged_at:'2026-09-09T01:01:00Z',auth_user_id:'authenticated-account',content_hash:'abc',statement:'statement'};
globalThis.__ackHooks=hooks;
globalThis.__ackRpc=async(name,args)=>{calls.push({name,args});return {data:name==='my_acknowledgments'?{documents:[doc],receipts:[]}:name==='open_acknowledgment_document'?delivery:name==='acknowledge_document'?receipt:name==='acknowledgment_gate'?{blocked:gateBlocked}:null,error:null};};
globalThis.window={dispatchEvent(){},addEventListener(){},removeEventListener(){}};
globalThis.document={body:{style:{}}};
const result=await build({stdin:{contents:`export {default as EmployeePage,DocumentViewer} from './modules/acknowledgments/EmployeePage';export {default as Modal} from './components/ui/Modal';export {STATEMENT,receiptText,manila} from './modules/acknowledgments/service';`,resolveDir:root,loader:'tsx'},bundle:true,platform:'node',format:'cjs',packages:'external',write:false,plugins:[{name:'fixtures',setup(b){b.onResolve({filter:/^react$/},args=>args.namespace==='mock-react'?{path:'react',external:true}:{path:'react',namespace:'mock-react'});b.onLoad({filter:/.*/,namespace:'mock-react'},()=>({contents:`const React=require('react');module.exports={...React,...globalThis.__ackHooks,default:{...React,...globalThis.__ackHooks}};`,loader:'js'}));b.onResolve({filter:/useAuth$/},()=>({path:'auth',namespace:'mock'}));b.onResolve({filter:/supabaseClient$/},()=>({path:'client',namespace:'mock'}));b.onResolve({filter:/ApprovalNavigation$/},()=>({path:'navigation',namespace:'mock'}));b.onResolve({filter:/^react-dom$/},()=>({path:'portal',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='auth'?`export const useAuth=()=>({user:{id:'employee'}});`:a.path==='client'?`export const supabase={rpc:(...a)=>globalThis.__ackRpc(...a)};`:a.path==='portal'?`export const createPortal=x=>x;`:`export const ApprovalDialogNavigation=()=>null;`,loader:'js'}));}}]});
const m=new Module(`${root}ack-test.cjs`);m.filename=`${root}ack-test.cjs`;m.paths=Module._nodeModulePaths(root);m.require=createRequire(m.filename);m._compile(result.outputFiles[0].text,m.filename);
const {EmployeePage,DocumentViewer,Modal,STATEMENT,receiptText,manila}=m.exports;
const render=(Component,props={})=>{cursor=0;return Component(props);};
const flush=async()=>{while(pending.length){const q=pending;pending=[];q.forEach(f=>f());}await new Promise(r=>setImmediate(r));};
const nodes=(el)=>!el||typeof el!=='object'?[]:[el,...[el.props?.children].flat(Infinity).flatMap(nodes)];
const find=(el,fn)=>nodes(el).find(fn);
const reset=()=>{effects.forEach(e=>e?.cleanup?.());states=[];effects=[];cursor=0;pending=[];calls=[];};
let el=render(EmployeePage);await flush();el=render(EmployeePage);
await find(el,n=>n.type==='button'&&n.props.children==='Open Document').props.onClick();await flush();el=render(EmployeePage);
let checkbox=find(el,n=>n.type==='input'&&n.props.type==='checkbox');assert.equal(checkbox.props.disabled,true);
let submit=find(el,n=>n.type==='button'&&n.props.children==='Acknowledge Document');assert.equal(submit.props.disabled,true);
assert.equal(calls.filter(c=>c.name==='acknowledge_document').length,0);
await find(el,n=>n.type===DocumentViewer).props.onLoaded();await flush();el=render(EmployeePage);
checkbox=find(el,n=>n.type==='input'&&n.props.type==='checkbox');assert.equal(checkbox.props.disabled,false);
submit=find(el,n=>n.type==='button'&&n.props.children==='Acknowledge Document');assert.equal(submit.props.disabled,true);
checkbox.props.onChange({target:{checked:true}});el=render(EmployeePage);submit=find(el,n=>n.type==='button'&&n.props.children==='Acknowledge Document');assert.equal(submit.props.disabled,false);
submit.props.onClick();submit.props.onClick();await flush();el=render(EmployeePage);assert.equal(calls.filter(c=>c.name==='acknowledge_document').length,1);assert.ok(find(el,n=>n.type==='pre'));
assert.match(receiptText(receipt),/TEST/);assert.match(receiptText(receipt),/Version: 1/);assert.match(manila(receipt.acknowledged_at),/9:01/);
assert.match(STATEMENT,/does not necessarily mean that I agree/);
reset();let viewed=0;el=render(DocumentViewer,{delivery,onLoaded:()=>viewed++});await flush();el=render(DocumentViewer,{delivery,onLoaded:()=>viewed++});assert.equal(viewed,0);find(el,n=>n.type==='iframe').props.onError();await flush();el=render(DocumentViewer,{delivery,onLoaded:()=>viewed++});find(el,n=>n.type==='iframe').props.onLoad();await flush();el=render(DocumentViewer,{delivery,onLoaded:()=>viewed++});await flush();assert.equal(viewed,0,'failed document must never enable acknowledgment');
reset();el=render(DocumentViewer,{delivery,onLoaded:()=>viewed++});await flush();el=render(DocumentViewer,{delivery,onLoaded:()=>viewed++});find(el,n=>n.type==='iframe').props.onLoad();el=render(DocumentViewer,{delivery,onLoaded:()=>viewed++});await flush();assert.equal(viewed,1);
reset();const draft={type:'input',props:{defaultValue:'preserved draft'}};const props={isOpen:true,onClose(){},title:'Request',children:draft,footer:'Submit',acknowledgmentRequestType:'Overtime'};el=render(Modal,props);assert.ok(find(el,n=>n.props?.hidden===true),'form is hidden while initial check runs');await flush();el=render(Modal,props);assert.equal(find(el,n=>n.props?.hidden===true).props.children,draft,'gate preserves mounted draft child');
el=render(Modal,{...props,acknowledgmentDraft:true});assert.equal(find(el,n=>n.props?.hidden===false).props.children,draft,'existing draft stays accessible for saving');
reset();el=render(Modal,{...props,acknowledgmentRequestType:undefined});await flush();assert.equal(calls.filter(c=>c.name==='acknowledgment_gate').length,0,'unrelated modal has no gate check');
console.log('Acknowledgment UI states, successful-load requirement, failure state, checkbox, duplicate submission, receipts and draft preservation passed.');
