import assert from 'node:assert/strict';import fs from 'node:fs';import {PGlite} from '@electric-sql/pglite';
process.on('uncaughtException',e=>{console.error(e.message,e.where||'',e.detail||'');process.exit(1);});
const db=new PGlite(),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`create schema private;create schema auth;create role authenticated;create role anon;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
create function public.current_hris_user_id() returns uuid language sql stable as $$select auth.uid()$$;
create table hris_users(id uuid primary key,full_name text,position text,business_unit_id uuid,status text,email text);
create table business_units(id uuid primary key,name text);
create table ot_requests(id uuid primary key default gen_random_uuid(),employee_id uuid,employee_name text,date date,start_time time,end_time time,hours numeric,reason text,status text,submitted_at timestamptz,business_unit_id uuid,department_id uuid,ot_type text default 'Paid',paid_ot_type text,history_log jsonb,approved_hours numeric,direct_manager_id uuid,approved_by uuid,approved_at timestamptz,updated_at timestamptz default now(),approval_route text,approval_reason text,approval_context jsonb,approval_routed_at timestamptz);
create table time_request_approval_assignments(request_type text,request_id uuid,approver_user_id uuid,status text,is_required boolean default true,updated_at timestamptz,decided_at timestamptz,decision_note text,approver_email text);
create table payroll_schedule_freezes(employee_id uuid,date_from date,date_to date);
create table notifications(user_id text,type text,title text,message text,link text,related_entity_id text,dedupe_key text);
create table audit_logs(user_id text,action text,entity text,entity_id text,details text);
create function private.is_direct_reporting_manager(uuid,uuid) returns boolean language sql stable as $$select $1='${id(2)}'::uuid and $2='${id(1)}'::uuid$$;
create function public.has_active_role(text) returns boolean language sql stable as $$select auth.uid()='${id(3)}'::uuid and $1='Board of Director'$$;
create function private.can_read_ot_report(uuid,uuid) returns boolean language sql stable as $$select auth.uid() in('${id(2)}','${id(3)}')$$;
create function private.is_active_time_request_approver(uuid,text,uuid) returns boolean language sql stable as $$select exists(select 1 from public.time_request_approval_assignments where approver_user_id=$1 and request_type=$2 and request_id=$3 and status='Pending')$$;
create function private.conditional_time_approval_config() returns jsonb language sql as $$select '{"weekly_total_hours":50}'::jsonb$$;
create function private.time_request_context(text,uuid) returns jsonb language sql as $$select '{"preserved":true}'::jsonb$$;
create function private.attendance_pre_leave_schedule(uuid,date) returns jsonb language sql stable as $$select jsonb_build_object('published',current_setting('test.roster',true)='published','entries',case when extract(isodow from $2)=7 then '[{"kind":"rest"}]'::jsonb else '[{"kind":"work","start":"09:00","end":"18:00","endDayOffset":0,"breakMinutes":60}]'::jsonb end)$$;
insert into hris_users(id,full_name,status) values('${id(1)}','Employee','Active'),('${id(2)}','Manager','Active'),('${id(3)}','BOD','Active'),('${id(4)}','Other','Active');
`);
await db.exec(`create type public.ot_status as enum('Draft','Submitted','PendingGM','PendingBOD','Approved','Rejected');
alter table ot_requests alter column status type public.ot_status using status::public.ot_status;
alter table ot_requests add column manager_note text;
alter table time_request_approval_assignments add column id uuid default gen_random_uuid(),add column is_bod boolean default true;
create unique index assignment_identity on time_request_approval_assignments(request_type,request_id,approver_user_id);
alter table audit_logs add column user_email text;
create function private.assign_time_request_approvers(text,uuid,boolean) returns void language sql as $$insert into public.time_request_approval_assignments(request_type,request_id,approver_user_id,status,is_required) values($1,$2,'${id(3)}','Pending',true) on conflict(request_type,request_id,approver_user_id) do update set status='Pending'$$;`);
const coreSql=fs.readFileSync('supabase/migrations/20260910022947_bod_approval_idempotency.sql','utf8');
const coreStart=coreSql.indexOf('create or replace function private.process_time_request_approval_core(');
const coreTail=coreSql.slice(coreStart),coreEnd=coreTail.indexOf('$$;',coreTail.indexOf('as $$')+5)+3;
await db.exec(coreTail.slice(0,coreEnd));
await db.exec(fs.readFileSync('supabase/migrations/20260929150000_manual_overtime_week_review.sql','utf8'));
await db.exec(`set test.actor='${id(1)}';set test.roster='published'`);
const insert=async(n,date,start,end,extra={})=>{await db.query('insert into ot_requests(id,employee_id,date,start_time,end_time,reason,status,requested_minutes,unpaid_break_minutes,end_date) values($1,$2,$3,$4,$5,\'Actual extra work\',\'Submitted\',$6,$7,$8)',[id(n),id(1),date,start,end,extra.minutes??null,extra.breaks??0,extra.endDate??null]);};
await insert(10,'2026-09-21','19:00','20:15');await insert(11,'2026-09-22','23:00','01:15',{breaks:15});
assert.deepEqual((await db.query('select requested_minutes from ot_requests order by id')).rows.map(r=>r.requested_minutes),[75,120]);
await assert.rejects(insert(12,'2026-09-22','23:00','01:00',{endDate:'2026-09-22'}),/Check extra-work/);
await db.exec(`set test.actor='${id(2)}'`);
const weeks=async(ids=[id(10),id(11)])=>(await db.query('select get_ot_week_review($1) data',[ids])).rows[0].data;
let week=(await weeks())[0];assert.equal(week.summary.regularMinutes,2880);assert.equal(week.summary.unreviewedMinutes,195);assert.equal(week.summary.projectedMinutes,2880);
const decide=async(ids,mins,ver,op,decision='approve',note=null)=>(await db.query('select decide_ot_week($1,$2,$3,$4,$5,$6) result',[ids,mins,ver,op,decision,note])).rows[0].result;
const op=id(101);await decide([id(10),id(11)],{[id(10)]:60,[id(11)]:120},week.version,op);
let rows=(await db.query('select status,approved_hours,manager_confirmed_minutes from ot_requests order by id')).rows;assert.deepEqual(rows.map(r=>r.status),['PendingBOD','PendingBOD']);assert.equal(rows[0].manager_confirmed_minutes,60);
const count=(await db.query('select count(*)::int n from audit_logs')).rows[0].n;await decide([id(10),id(11)],{[id(10)]:60,[id(11)]:120},week.version,op);assert.equal((await db.query('select count(*)::int n from audit_logs')).rows[0].n,count,'Retry did not repeat decisions');
await assert.rejects(decide([id(10)],{[id(10)]:60},week.version,id(102)),/changed/);
await db.exec(`set test.actor='${id(3)}'`);week=(await weeks())[0];assert.equal(week.summary.projectedMinutes,3060);assert.equal(week.summary.reviewedMinutes,180);assert.equal(week.summary.approvedMinutes,0);
await assert.rejects(decide([id(10),id(11)],{[id(10)]:60,[id(11)]:121},week.version,id(103)),/match the manager|requested extra-work duration/);
assert.equal((await db.query("select count(*)::int n from ot_requests where status='Approved'")).rows[0].n,0,'Invalid member rolled back entire batch');
await decide([id(10),id(11)],{[id(10)]:60,[id(11)]:120},week.version,id(104));week=(await weeks())[0];assert.equal(week.summary.approvedMinutes,180);assert.equal(week.summary.reviewedMinutes,0);
await db.exec(`set test.actor='${id(1)}';set test.roster='missing'`);await insert(20,'2026-09-28',null,null,{minutes:75});
await db.exec(`set test.actor='${id(2)}'`);week=(await weeks([id(20)]))[0];assert.equal(week.summary.regularMinutes,null);let res=await decide([id(20)],{[id(20)]:{minutes:60,nightMinutes:0}},week.version,id(105));assert.equal(res.baselineNeeded,true);assert.equal((await db.query('select status from ot_requests where id=$1',[id(20)])).rows[0].status,'Submitted');
await db.query('select confirm_ot_week_baseline($1,$2,$3,$4)',[id(1),'2026-09-28',2400,'Published external roster checked']);week=(await weeks([id(20)]))[0];await decide([id(20)],{[id(20)]:{minutes:0,nightMinutes:0}},week.version,id(106));assert.equal((await db.query('select final_approved_minutes from ot_requests where id=$1',[id(20)])).rows[0].final_approved_minutes,0);
await db.exec(`set test.actor='${id(1)}'`);await insert(21,'2026-10-05','19:00','20:00');week=(await weeks([id(21)]))[0];assert.equal(week.requests[0].canDecide,false);await assert.rejects(decide([id(21)],{[id(21)]:60},week.version,id(107)),/assigned/);
await db.exec(`set test.actor='${id(2)}'`);week=(await weeks([id(21)]))[0];await assert.rejects(decide([id(21)],{},week.version,id(108),'reject'),/reason/);await decide([id(21)],{},week.version,id(109),'return','Incorrect work date');assert.equal((await db.query('select status from ot_requests where id=$1',[id(21)])).rows[0].status,'Draft');
await db.exec(`set test.actor='${id(1)}'`);await insert(22,'2026-10-06','19:00','20:00');await insert(23,'2026-10-06','19:30','20:30');await db.exec(`set test.actor='${id(2)}'`);week=(await weeks([id(22),id(23)]))[0];await assert.rejects(decide([id(22)],{[id(22)]:60},week.version,id(110)),/overlaps/);
await db.query('insert into payroll_schedule_freezes values($1,$2,$2)',[id(1),'2026-10-06']);week=(await weeks([id(22)]))[0];assert.match(week.requests.find(r=>r.id===id(22)).blocked,/locked/);await assert.rejects(decide([id(22)],{[id(22)]:60},week.version,id(111)),/locked/);
await db.exec('set role authenticated');await db.exec(`set test.actor='${id(2)}'`);await weeks();await assert.rejects(db.query('select * from private.ot_batch_decisions'),/permission denied/);await db.exec('reset role');
assert.equal((await db.query("select has_function_privilege('anon','public.decide_ot_week(uuid[],jsonb,text,uuid,text,text)','execute') allowed")).rows[0].allowed,false);
await db.exec(fs.readFileSync('supabase/migrations/20260929152000_guard_unknown_legacy_ot_quantities.sql','utf8'));
await db.exec(`set test.actor='${id(2)}';set test.roster='published';alter table ot_requests disable trigger a_manual_ot_guard;`);
await db.query("insert into ot_requests(id,employee_id,date,start_time,end_time,status,reason) values($1,$2,'2026-09-21','10:00','11:00','Approved','Legacy approved record')",[id(99),id(1)]);
await db.exec('alter table ot_requests enable trigger a_manual_ot_guard');
week=(await weeks())[0];assert.equal(week.summary.quantitiesMissing,true);assert.equal(week.summary.approvedMinutes,null);assert.equal(week.summary.projectedMinutes,null);assert.equal(week.summary.knownApprovedMinutes,180);assert.equal(week.summary.quantityIssueIds[0],id(99));
await db.close();console.log('PASS manual OT: exact/overnight/break minutes, no inferred baseline, distinct weekly buckets, adjusted manager amount, atomic batch, stale version, idempotent retry, optional approval note, zero minutes, self-approval denied, return reason, overlap and locked payroll guards; authenticated RPC and private ACLs.');
