import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {readFile} from 'node:fs/promises';
const result=await build({entryPoints:['modules/nte/workflow.ts'],bundle:true,write:false,platform:'node',format:'esm',plugins:[{name:'isolated-client',setup(b){b.onLoad({filter:/services\/supabaseClient.ts$/},()=>({contents:'export const supabase={};',loader:'ts'}));}}]});
const m=await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));
assert.doesNotThrow(()=>m.validateAttachment({size:5242880,type:'application/pdf'}));
assert.throws(()=>m.validateAttachment({size:5242881,type:'application/pdf'}),/5 MB/);
assert.throws(()=>m.validateAttachment({size:10,type:'text/html'}),/PDF/);
assert.doesNotThrow(()=>m.validateLink('https://drive.google.com/file/example'));
assert.throws(()=>m.validateLink('javascript:alert(1)'),/HTTPS/);
assert.throws(()=>m.validateLink('https://user:password@example.com'),/credentials/);
assert.match(m.deadlineLabel('2026-09-14T16:00:00Z'),/Sep 14, 2026.*11:59 PM PHT/i);
const migration=await readFile('supabase/migrations/20260908111156_nte_receipt_response_decision_workflow.sql','utf8');
const attachmentFunction=migration.match(/create function private\.nte_attachment_allowed[\s\S]*?end \$\$;/)?.[0]||'';
const mutationGuard=migration.match(/create function private\.guard_nte_response_fields[\s\S]*?end \$\$;/)?.[0]||'';
assert.doesNotMatch(attachmentFunction,/\b(?:tg_op|new\.|old\.)/i);
assert.match(mutationGuard,/new\.receipt_recorded_at is distinct from old\.receipt_recorded_at/i);
assert.match(mutationGuard,/Issued notices and their history are locked/);
console.log('PASS: 5 MB boundary, safe links, Philippine deadline display, SQL guard placement');
