import fs from 'node:fs';
import assert from 'node:assert/strict';

const builder = fs.readFileSync('components/recruitment/OfferCreationDrawer.tsx', 'utf8');
const offers = fs.readFileSync('pages/recruitment/Offers.tsx', 'utf8');
const publicOffer = fs.readFileSync('supabase/functions/public-offer/index.ts', 'utf8');
const migration = fs.readFileSync('supabase/migrations/20260822060000_offer_value_builder.sql', 'utf8');
const acceptanceMigration = fs.readFileSync('supabase/migrations/20260823075607_complete_offer_acceptance_workflow.sql', 'utf8');
const candidatePage = fs.readFileSync('pages/OfferResponse.tsx', 'utf8');
const appearance = fs.readFileSync('components/recruitment/OfferAppearanceEditor.tsx', 'utf8');
const branding = fs.readFileSync('components/recruitment/offerBranding.ts', 'utf8');
const document = fs.readFileSync('components/recruitment/OfferDocument.tsx', 'utf8');
const detailModal = fs.readFileSync('components/recruitment/OfferDetailModal.tsx', 'utf8');
const pdf = fs.readFileSync('components/recruitment/offerPdf.ts', 'utf8');
const stepSixMigration = fs.readFileSync('supabase/migrations/20260823103000_allow_offer_builder_step_six.sql', 'utf8');
const atomicAcceptanceMigration = fs.readFileSync('supabase/migrations/20260823170000_atomic_signed_offer_acceptance.sql', 'utf8');
const authContext = fs.readFileSync('context/AuthContext.tsx', 'utf8');

for (const label of ['Role & Job Details', 'Compensation', 'Schedule & Location', 'Benefits & Growth', 'Review & Send']) assert.match(builder, new RegExp(label.replace('&', '\\&')));
for (const behavior of ['localStorage', 'beforeunload', 'Saving…', 'Draft saved just now', 'Unable to save. Retry', 'Save Draft', 'Preview Offer', 'Send Offer']) assert.ok(builder.includes(behavior), `Missing ${behavior}`);
assert.match(builder, /z-\[100\]/);
assert.match(builder, /createPortal/);
for (const feature of ['Role Purpose', 'Key Responsibilities', 'What Success Looks Like', 'First 90 Days', 'grossAnnualizedSalary', 'Career Growth Journey', 'Candidate signature', 'Download PDF']) assert.ok(builder.includes(feature), `Missing ${feature}`);
assert.match(builder, /amount \* 12/);
assert.match(builder, /file\.size > 2 \* 1024 \* 1024/);
assert.match(builder, /image\/svg\+xml/);
assert.match(offers, /status: OfferStatus\.Draft/);
assert.match(offers, /send-recruitment-email/);
assert.match(offers, /\/api\/recruitment-email/);
assert.match(offers, /emailDelivery/);
assert.match(offers, /status: OfferStatus\.Sent/);
assert.match(detailModal, /createPortal/);
assert.match(detailModal, /z-\[120\]/);
assert.match(detailModal, /Send Offer/);
assert.match(pdf, /buildOfferPdf/);
assert.match(pdf, /Page \$\{page\} of \$\{totalPages\}/);
assert.match(stepSixMigration, /between 1 and 6/);
assert.doesNotMatch(authContext, /Connect Google is not implemented in Supabase yet/);
assert.match(publicOffer, /\.eq\('secure_token', token\)/);
assert.match(publicOffer, /\['accept', 'decline'\]/);
for (const feature of ['Draw Signature', 'Type Signature', 'Submit Signature', 'electronic signature is legally binding', 'Confirm Decline', 'Download Signed Offer', 'page="continuous"', 'Offer accepted and signed', 'Contract Signing', 'Onboarding']) assert.ok(candidatePage.includes(feature), `Missing candidate feature: ${feature}`);
assert.doesNotMatch(candidatePage, /Page \{page\} of 3|setPage\(/);
for (const feature of ['Primary color', 'Accent color', 'Page background', 'Font family', 'Button style', 'Card style', 'Section layout']) assert.ok(appearance.includes(feature), `Missing appearance setting: ${feature}`);
assert.match(branding, /isLegacyGenericTheme/);
assert.match(appearance, /customized: true/);
assert.match(document, /Page \{number\} of 3/);
assert.match(publicOffer, /accept_and_sign_job_offer/);
assert.match(publicOffer, /status: 'Accepted and Signed'/);
assert.match(publicOffer, /sendGoogleEmail/);
assert.match(publicOffer, /signed-offers/);
assert.match(publicOffer, /Offer declined/);
assert.match(acceptanceMigration, /accepted_at timestamptz/);
assert.match(acceptanceMigration, /signed_pdf_path text/);
assert.match(migration, /offer_details jsonb/);
assert.match(migration, /enable row level security/);
assert.match(migration, /file_size_limit/);
assert.match(migration, /false,\n\s+2097152/);
assert.match(migration, /revoke all on function public\.capture_job_offer_history/);
assert.match(atomicAcceptanceMigration, /'Accepted and Signed'/);
assert.match(atomicAcceptanceMigration, /security invoker/);
assert.match(atomicAcceptanceMigration, /revoke all on function public\.accept_and_sign_job_offer/);

console.log('Offer builder smoke test passed.');
