import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const source = relativePath => readFile(path.join(root, relativePath), 'utf8');

const migration = await source('supabase/migrations/20260901113000_candidate_rating_summary_offer_approval_phase2.sql');
const storageMigration = await source('supabase/migrations/20260901115000_offer_approval_storage_scope.sql');
const service = await source('services/offerApprovalService.ts');
const requester = await source('components/recruitment/OfferApprovalPackageModal.tsx');
const approver = await source('components/recruitment/OfferApprovalReviewModal.tsx');
const offers = await source('pages/recruitment/Offers.tsx');
const offerDetail = await source('components/recruitment/OfferDetailModal.tsx');
const approvalCenter = await source('pages/ApprovalCenter.tsx');
const approvalWidget = await source('components/dashboard/ApprovalWidget.tsx');
const links = await source('services/approvalDeepLinks.ts');
const hook = await source('hooks/useAdditionalApprovals.ts');

for (const table of ['job_candidate_documents', 'job_offer_approval_requests', 'job_offer_approval_assignments', 'job_offer_approval_history']) assert.match(migration, new RegExp(`create table if not exists public\\.${table}`));
for (const functionName of ['upload_job_candidate_document', 'remove_job_candidate_document', 'create_job_offer_approval_request', 'get_my_pending_offer_approval_ids', 'get_job_offer_approval_package', 'process_job_offer_approval']) assert.match(migration, new RegExp(`function public\\.${functionName}`));
assert.match(migration, /alter table public\.job_offers[\s\S]*approval_status/);
assert.match(migration, /job_offer_approval_requests_one_active/);
assert.match(migration, /status in \('Pending Approval', 'Returned for Revision'\)/);
assert.match(migration, /approval_stage text/);
assert.match(migration, /'HR_MANAGER'/);
assert.match(migration, /'BOD_GM'/);
assert.match(migration, /'Board of Director'/);
assert.match(migration, /'GeneralManager'/);
assert.match(migration, /security definer[\s\S]*create_job_offer_approval_request/);
assert.match(migration, /documents_reviewed/);
assert.match(migration, /Closed after another approval in this stage/);
assert.match(migration, /This offer approval has already been processed/);
assert.match(migration, /OFFER_APPROVAL/);
assert.match(migration, /\/approvals\?type=offer&item=/);
assert.match(migration, /enable row level security/);
assert.match(migration, /candidate_id = application_row\.candidate_id/);
assert.match(storageMigration, /job_candidate_documents_recruitment_select/);
assert.match(storageMigration, /candidate_recruitment_documents_storage_select/);
assert.match(storageMigration, /offer_approval_resume_storage_select/);
assert.match(storageMigration, /request\.status = 'Pending Approval'/);
assert.match(storageMigration, /assignment\.status = 'Pending'/);
assert.match(storageMigration, /jsonb_array_elements/);
assert.match(storageMigration, /item->>'sourceId' = job_candidate_documents\.id::text/);

assert.match(service, /fetchCandidatePackageDocuments/);
assert.match(service, /\.eq\('candidate_id', candidate\.id\)/);
assert.match(service, /openOfferPackageDocument/);
assert.match(service, /createOfferApprovalRequest/);
assert.match(service, /processOfferApproval/);
assert.match(service, /getApprovalPackageDocuments/);
assert.match(requester, /Request Offer Approval/);
assert.match(requester, /Add Existing Candidate Document/);
assert.match(requester, /Search by document, reviewer, or candidate/);
assert.match(requester, /Preview \/ Download/);
assert.match(requester, /Move attachment up/);
assert.match(requester, /Move attachment down/);
assert.match(requester, /Resume attached/);
assert.match(requester, /Interview rating\(s\) attached/);
assert.match(requester, /Offer attached/);
assert.match(requester, /overrideIncompleteRatings/);
assert.match(approver, /Offer Approval Package/);
assert.match(approver, /InterviewSummaryPanel/);
assert.match(approver, /Reviewer recommendations/);
assert.match(approver, /Approval trail/);
assert.match(approver, /Return for Revision/);
assert.match(approver, /Add comments before returning or rejecting/);
assert.match(approver, /processOfferApproval/);
assert.match(offers, /OfferApprovalPackageModal/);
assert.match(offers, /handleRequestOfferApproval/);
assert.match((await source('components/recruitment/CandidateProfileModal.tsx')), /Request Offer Approval/);
assert.match((await source('components/recruitment/CandidateProfileModal.tsx')), /mapApprovalOfferRow/);
assert.match(offerDetail, /Request Offer Approval/);
assert.match(approvalCenter, /pendingOfferApprovals/);
assert.match(approvalCenter, /OfferApprovalReviewModal/);
assert.match(approvalCenter, /kind: 'offer'/);
assert.match(approvalWidget, /name:'Offer Approvals'/);
assert.match(approvalWidget, /additional\.pendingOfferApprovals\.length/);
assert.match(links, /type ApprovalRequestKind/);
assert.match(links, /'offer'/);
assert.match(links, /type=offer&item=/);
assert.match(hook, /fetchPendingOfferApprovalIds/);
assert.match(hook, /fetchOfferApprovalPackage/);

console.log('Offer Approval Package Phase 2 smoke checks passed.');
