process.on('uncaughtException',e=>{console.error(e.message, e.where||'', e.stack?.split('\n').filter(x=>x.includes('officialBusinessTest')).join('\n'));process.exit(1);});
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const scalar=async(sql,args=[])=>(await db.query(sql,args)).rows[0]?.v;
await db.exec(`create schema private;create schema auth;create schema storage;create schema extensions;create role authenticated;create role anon;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
create function auth.jwt() returns jsonb language sql stable as $$select '{"email":"fixture@example.invalid"}'::jsonb$$;
create function public.current_hris_user_id() returns uuid language sql stable as $$select auth.uid()$$;
create function private.payroll_actor_id() returns uuid language sql stable as $$select auth.uid()$$;
create function public.has_active_role(text) returns boolean language sql stable as $$select $1=current_setting('test.role')$$;
create function public.can_access_hris_user(uuid) returns boolean language sql stable as $$select $1<>'${id(9)}'::uuid$$;
create function public.has_feature_permission(text,text) returns boolean language sql stable as $$select true$$;
create function private.attendance_admin() returns boolean language sql stable as $$select false$$;
create function private.is_schedule_suspended(uuid,date) returns boolean language sql stable as $$select coalesce(current_setting('test.suspended',true),'no')='yes'$$;
create function private.resolve_direct_manager_id(uuid) returns uuid language sql stable as $$select '${id(2)}'::uuid$$;
create table public.hris_users(id uuid primary key,business_unit_id uuid,full_name text,status text);
create table public.user_roles(user_id uuid,role_id text,is_active boolean,scope_type text,allowed_business_unit_ids uuid[]);
create table public.notifications(user_id text,type text,title text,message text,link text,related_entity_id text,dedupe_key text unique);
create table public.audit_logs(id uuid default gen_random_uuid(),user_id text,user_email text,action text,entity text,entity_id text,details text);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,created_at timestamptz default now(),metadata jsonb);
alter table storage.objects enable row level security;
create function storage.foldername(text) returns text[] language sql immutable as $$select string_to_array($1,'/')$$;
create table public.attendance_clock_sessions(id uuid primary key default gen_random_uuid(),employee_id uuid,work_date date,publication_id uuid not null,schedule_snapshot jsonb,state text default 'not_started',revision int default 0);
create table public.attendance_clock_events(id uuid primary key default gen_random_uuid(),employee_id uuid,session_id uuid,request_id uuid unique,action text,occurred_at timestamptz,revision int,created_by uuid);
create table public.attendance_channel_evidence(event_id uuid primary key,method text,site_id uuid,device_id uuid,challenge_id uuid,detail jsonb);
create table public.time_events(id uuid,employee_id uuid,timestamp timestamptz,type text,source text,timezone text,created_by uuid,notes text);
create table public.payroll_time_compensation_reviews(employee_id uuid,work_date date);
create table public.sites(id uuid,business_unit_id uuid,latitude float8,longitude float8,radius_meters int);
create table public.attendance_devices(id uuid,site_id uuid,active boolean,kind text,business_unit_id uuid);
create table public.attendance_qr_challenges(id uuid,device_id uuid,expires_at timestamptz,token_hash text);
create function private.attendance_channel_config(uuid) returns jsonb language sql stable as $$select '{"web_allowed":true,"gps_enabled":true,"qr_enabled":false}'::jsonb$$;
create function private.payroll_schedule_validate(jsonb) returns void language plpgsql immutable as $$begin if $1->>'kind'='work' and ($1->>'breakMinutes')::int is distinct from 60 then raise exception 'Lunch required';end if;end$$;
create function private.attendance_schedule(uuid,date) returns jsonb language sql stable as $$select jsonb_build_object('publicationId','${id(20)}','published',true,'date',$2,'entries',jsonb_build_array(jsonb_build_object('id','${id(21)}','name','Regular','kind','work','start','09:00','end','18:00','endDayOffset',0,'breakMinutes',60,'flexible',false)))$$;
create function private.attendance_day(uuid,date) returns jsonb language plpgsql stable security definer set search_path='' as $$declare s public.attendance_clock_sessions;begin select * into s from public.attendance_clock_sessions where employee_id=$1 and work_date=$2;return jsonb_build_object('serverTime',clock_timestamp(),'workDate',$2,'sessionId',s.id,'revision',coalesce(s.revision,0),'state',coalesce(s.state,'not_started'),'requiresClock',true,'schedule',coalesce(s.schedule_snapshot,private.attendance_schedule($1,$2)),'events','[]'::jsonb);end$$;
create function public.commit_attendance_import(p_batch uuid,p_hash text) returns jsonb language plpgsql security definer set search_path='' as $$declare emp uuid:=public.current_hris_user_id();r jsonb:=jsonb_build_object('workDate',p_hash);begin
if coalesce((private.attendance_exception(emp,p_hash::date)->>'requires_clock')::boolean,true)=false then raise exception 'Exempt';end if;return '{}'::jsonb;end$$;
create function private.attendance_exception(uuid,date) returns jsonb language sql stable as $$select '{}'::jsonb$$;
create table private.fixture_sources(value jsonb);
create function private.payroll_time_sources(uuid,date,date) returns jsonb language sql stable as $$select value from private.fixture_sources limit 1$$;
grant usage on schema auth,storage to authenticated;grant select,insert on storage.objects to authenticated;
insert into public.hris_users values('${id(1)}','${id(11)}','Employee fixture','Active'),('${id(2)}','${id(11)}','Head fixture','Active'),('${id(3)}','${id(11)}','HR fixture','Active'),('${id(4)}','${id(12)}','Unrelated fixture','Active'),('${id(9)}','${id(12)}','Other BU employee','Active');
insert into public.user_roles values('${id(3)}','HR Staff',true,'HOME_ONLY','{}');`);
await db.exec(fs.readFileSync(new URL('./fixtures/obExistingFunctions.sql',import.meta.url),'utf8'));
const migration=fs.readdirSync('supabase/migrations').find(x=>x.endsWith('_official_business_requests.sql'));
await db.exec(fs.readFileSync('supabase/migrations/'+migration,'utf8'));
await db.exec(fs.readFileSync('supabase/migrations/'+fs.readdirSync('supabase/migrations').find(x=>x.endsWith('_ob_preserve_changed_punch_review.sql')),'utf8'));
await db.exec(fs.readFileSync('supabase/migrations/'+fs.readdirSync('supabase/migrations').find(x=>x.endsWith('_ob_payroll_review_alias.sql')),'utf8'));
const actor=async(n,role='Employee')=>{await db.exec('reset role');await db.query("select set_config('test.actor',$1,false),set_config('test.role',$2,false)",[id(n),role]);await db.exec('set role authenticated');};
const admin=async(sql,args=[])=>{await db.exec('reset role');return db.query(sql,args);};
const revision=async()=>scalar('select revision v from public.official_business_requests where id=$1',[id(100)]);
const command=async(action,data={},reason='',rev)=>scalar('select public.act_on_official_business($1,$2,$3,$4,$5) v',[id(100),action,rev??await revision(),data,reason]);
const fail=async(fn,pattern)=>assert.rejects(fn,pattern);
const now=new Date();const ph=new Date(now.getTime()+8*3600000).toISOString().slice(0,10);
const start=new Date(now.getTime()-60000).toISOString(),end=new Date(now.getTime()+3*3600000).toISOString();
const draft={work_date:ph,starts_at:start,ends_at:end,destination:'Fixture client office',latitude:14.55,longitude:121.02,radius_metres:150,purpose:'Fixture client meeting',client_event:'Fixture',travel_minutes:30,override_schedule:true,supporting_required:true,documents:[]};
await actor(1);await command('save',draft,'',0);
await fail(()=>command('submit'),/Supporting documents/);
const doc=`${id(1)}/${id(100)}/documents/fixture.pdf`;
await db.query("insert into storage.objects(bucket_id,name,metadata) values('official-business',$1,'{\"mimetype\":\"application/pdf\"}')",[doc]);
draft.documents=[{name:'fixture.pdf',path:doc}];await command('save',draft);await command('submit');
await fail(()=>command('approve'),/assigned next approver/);
await actor(3,'HR Staff');await fail(()=>command('approve'),/assigned next approver/);
await actor(4,'Admin');assert.equal((await scalar("select public.get_official_business('all') v")).rows.length,0);
assert.equal(await scalar('select count(*)::int v from official_business_requests'),0);
await fail(()=>db.query('update official_business_requests set status=\'Approved\''),/permission denied/);
await actor(2);await command('approve');
await actor(2,'HR Staff');await fail(()=>command('approve'),/assigned next approver/);
await actor(3,'HR Staff');await command('approve');assert.equal(await scalar('select status v from official_business_requests'),'Approved');
assert.equal(await scalar("select jsonb_array_length(public.get_official_business('approvals')->'rows') v"),0);
await actor(1);const day=await scalar('select public.get_my_attendance() v');assert.equal(day.officialBusiness.reference.startsWith('OB-'),true);assert.equal(day.schedule.entries[0].name,'Official Business');
assert.equal(day.schedule.officialBusiness.documents,undefined);
await fail(()=>scalar('select public.commit_attendance_import($1,$2) v',[id(300),ph]),/biometric import/);
await fail(()=>scalar('select public.record_my_attendance($1,$2,$3,$4) v',['CLOCK_IN',id(200),0,ph]),/OB clock/);
await fail(()=>scalar('select private.record_attendance_without_ob($1,$2,$3,$4,$5) v',['CLOCK_IN',id(200),0,ph,{method:'web'}]),/permission denied/);
const selfie=`${id(1)}/${id(100)}/selfies/fixture.jpg`;
await db.query("insert into storage.objects(bucket_id,name,metadata) values('official-business',$1,'{\"mimetype\":\"image/jpeg\"}')",[selfie]);
const evidence={method:'ob',obId:id(100),latitude:14.55,longitude:121.02,accuracy:10,capturedAt:new Date().toISOString(),selfiePath:selfie};
const punch=(action,req,rev,e=evidence)=>scalar('select public.record_my_attendance_verified($1,$2,$3,$4,$5) v',[action,id(req),rev,ph,e]);
await fail(()=>punch('CLOCK_IN',201,0,{...evidence,selfiePath:'missing'}),/fresh selfie/);
const denied=await punch('CLOCK_IN',202,0,{...evidence,latitude:15});assert.equal(denied.recorded,false);assert.match(denied.error,/outside.*location/);
assert.equal(await scalar('select status v from official_business_requests'),'For Review');
assert.equal((await punch('CLOCK_IN',202,0)).recorded,false);
const saved=await punch('CLOCK_IN',203,0);assert.equal(saved.recorded,true);assert.equal(saved.state,'working');
assert.equal((await punch('CLOCK_IN',203,0)).recorded,true);
await admin('select 1');assert.equal(await scalar('select count(*)::int v from attendance_clock_events'),1);assert.equal(await scalar('select count(*)::int v from official_business_punch_audits'),2);
assert.equal(await scalar("select detail->>'selfiePath' v from attendance_channel_evidence"),selfie);
assert.match(await scalar('select notes v from time_events'),/Official Business/);
await actor(3,'HR Staff');await fail(()=>command('amend',draft),/reason/);await command('amend',draft,'Client moved meeting');
await actor(1);const changed=await punch('CLOCK_OUT',204,1);assert.equal(changed.recorded,false);assert.match(changed.error,/not currently approved/);
await actor(2);await command('approve');await actor(3,'HR Staff');await command('approve');await actor(1);
await fail(()=>punch('CLOCK_OUT',205,0),/Attendance changed/);
assert.equal((await punch('CLOCK_OUT',205,1)).state,'completed');
await actor(3,'HR Staff');await fail(()=>command('cancel'),/reason/);await command('cancel',{},'Fixture cancellation');
await actor(1);assert.equal((await punch('CLOCK_IN',206,2)).recorded,false);
await actor(4);await fail(()=>db.query('select * from storage.objects where name=$1',[selfie]).then(r=>{assert.equal(r.rows.length,0);throw new Error('checked');}),/checked/);
await admin("select set_config('test.suspended','yes',false)");assert.equal(await scalar('select private.attendance_schedule($1,$2)#>>\'{entries,0,name}\' v',[id(1),ph]),'Regular');
await db.exec("select set_config('test.suspended','no',false)");
const source={employees:[{id:id(1),name:'Fixture',hireDate:'2020-01-01',status:'Active'}],rules:[{id:id(30),effective_from:ph,effective_to:ph,revision:1,config:{holidayCoverageConfirmed:true}}],shifts:[{id:id(31),employeeId:id(1),date:ph,kind:'work',published:true,start:'09:00',end:'18:00',endDayOffset:0,breakMinutes:60,flexible:false}],scheduleDays:[{employeeId:id(1),date:ph,status:'published'}],events:[{id:id(40),employeeId:id(1),type:'CLOCK_IN',timestamp:ph+'T09:00:00+08:00'},{id:id(41),employeeId:id(1),type:'CLOCK_OUT',timestamp:ph+'T18:00:00+08:00'}],leave:[],ot:[],holidays:[],wfh:[],leavePolicies:[],officialBusiness:[{id:id(100),employeeId:id(1),date:ph,status:'Approved',originalScheduledMinutes:480,originalRestDay:false,independentPayReview:false}]};
source.events.push({id:id(42),employeeId:id(1),type:'START_BREAK',timestamp:ph+'T12:00:00+08:00'},{id:id(43),employeeId:id(1),type:'END_BREAK',timestamp:ph+'T13:00:00+08:00'});
const interpret=async()=> (await scalar('select private.interpret_payroll_time($1,$2,$2) v',[source,ph])).rows[0];
let row=await interpret();assert.equal(row.attendanceBasis,'Official Business');assert.equal(row.approvedOtMinutes,0);assert.equal(row.issues.some(x=>x.startsWith('OB authorizes')),false);
source.holidays=[{date:ph}];row=await interpret();assert.equal(row.ready,false);assert.equal(row.issues.some(x=>x.startsWith('OB authorizes')),true);
source.officialBusiness[0].independentPayReview=true;row=await interpret();assert.equal(row.issues.some(x=>x.startsWith('OB authorizes')),false);
source.holidays=[];source.officialBusiness[0].independentPayReview=false;source.officialBusiness[0].originalScheduledMinutes=60;assert.equal((await interpret()).issues.some(x=>x.startsWith('OB authorizes')),true);
source.officialBusiness[0].status='For Review';assert.equal((await interpret()).issues.some(x=>x.startsWith('Official Business attendance')),true);
await db.query('insert into private.fixture_sources values($1)',[source]);
await db.query("update official_business_requests set status='Approved',approved_at=now(),override_schedule=true where id=$1",[id(100)]);
const assembled=await scalar('select private.payroll_time_sources($1,$2,$2) v',[id(11),ph]);assert.equal(assembled.officialBusiness.length,1);assert.equal(assembled.shifts[0].name,'Official Business');assert.deepEqual(assembled.originalShiftsBeforeOb,source.shifts);assert.equal(assembled.officialBusiness[0].originalScheduledMinutes,480);
assert.equal(await scalar('select count(*)::int v from payroll_time_compensation_reviews'),0);
await db.query("update official_business_requests set status='Cancelled' where id=$1",[id(100)]);
const cancelledSources=await scalar('select private.payroll_time_sources($1,$2,$2) v',[id(11),ph]);assert.equal(cancelledSources.officialBusiness[0].status,'For Review');assert.equal(cancelledSources.officialBusiness[0].changedAfterPunch,true);
await actor(4);const regular=await scalar('select public.get_my_attendance() v');assert.equal(regular.officialBusiness,undefined);
assert.equal((await scalar('select public.record_my_attendance($1,$2,$3,$4) v',['CLOCK_IN',id(250),0,ph])).state,'working');
console.log('OB integration checks passed: ordered approvals, scoped reads/storage, no direct writes or legacy bypass, GPS/selfie evidence, rejected attempt audit, idempotency, amendments/cancellation, schedule isolation, payroll guard, regular clock.');
await db.close();
