import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import os from 'node:os';
import path from 'node:path';
import {createOperationsFixture,id} from './operationsFixture.mjs';
process.on('uncaughtException',e=>{console.error(e.message,e.where||'',e.detail||'');process.exit(1);});
const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'tng-ops-test-'));
const db=await createOperationsFixture(dataDir);
async function actor(n){await db.exec(`set test.actor='${id(n)}';set role authenticated;`);}
async function reset(){await db.exec('reset role');}
async function rpc(name,args=[]){return (await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;}
const content=(title,extra={})=>({title,description:'Instructions',instructions:'Inspect carefully',priority:'Normal',evidence:'none',category:'Opening',...extra});
async function deny(fn,pattern=/permission|cannot|outside|authorized|Only|unavailable|library|sign-in|eligible/i){await assert.rejects(fn,pattern);}
await actor(11);
assert.equal((await rpc('ops_workspace',[id(1)])).units.length,1);
await deny(()=>rpc('ops_workspace',[id(2)]));
await deny(()=>rpc('ops_save_template',[null,id(2),'task',content('Cross unit'),null,true]));
await deny(()=>rpc('ops_save_template',[null,null,'task',content('Master task'),null,true]));
const task=await rpc('ops_save_template',[null,id(1),'task',content('Check temperature'),null,true]);
let work=await rpc('ops_workspace',[id(1)]);let t=work.templates.find(t=>t.id===task);const first=t.versions[0].id;
const checklist=await rpc('ops_save_template',[null,id(1),'checklist',content('Bar opening',{items:[{task_version_id:first,required:true,response_type:'numeric'},{snapshot:content('Inspect counter'),required:false,response_type:'none'}]}),null,true]);
work=await rpc('ops_workspace',[id(1)]);let c=work.templates.find(t=>t.id===checklist);
const batch=await rpc('ops_assign',[id(1),c.versions[0].id,{mode:'individual',ids:[id(13),id(15)]},'2026-10-11T09:00:00+08:00','High','Opening instructions',[{name:'Manual',url:'https://example.com/manual'}],true]);
work=await rpc('ops_workspace',[id(1)]);assert.equal(work.assignments.filter(a=>a.batch_id===batch).length,2);
await rpc('ops_save_template',[task,id(1),'task',content('Changed temperature SOP'),t.revision,true]);
work=await rpc('ops_workspace',[id(1)]);assert.equal(work.assignments[0].items[0].snapshot.title,'Check temperature');
assert.equal(work.templates.find(t=>t.id===task).versions.length,2);
await deny(()=>rpc('ops_save_template',[task,id(1),'task',content('Stale write'),t.revision,true]),/changed/);
await deny(()=>rpc('ops_assign',[id(1),first,{mode:'individual',ids:[id(13)]},'2026-10-11','Normal','',[],false]),/current published/);
await deny(()=>rpc('ops_assign',[id(1),c.versions[0].id,{mode:'individual',ids:[id(13),id(14)]},'2026-10-11','Normal','',[],false]));
assert.equal((await rpc('ops_workspace',[id(1)])).assignments.length,2,'mixed audience rolled back');
await actor(13);work=await rpc('ops_workspace',[id(1)]);assert.equal(work.assignments.length,1);assert.equal(work.templates.length,0);let a=work.assignments[0];
await deny(()=>rpc('ops_save_template',[null,id(1),'task',content('Unauthorized'),null,true]));
await deny(()=>rpc('ops_delegate',[id(1),id(13),true,true]));
await deny(()=>db.query('update public.ops_assignments set status=\'Completed\''));
assert.equal((await db.query('select * from public.ops_assignments')).rows.length,1,'RLS self only');
assert.equal((await db.query('select * from public.ops_templates')).rows.length,0,'employees see assigned published content only, not template drafts');
await rpc('ops_change_assignment',[a.id,a.revision,'In Progress','Starting']);
await deny(()=>rpc('ops_change_assignment',[a.id,a.revision,'Completed','Old revision']),/changed/);
a=(await rpc('ops_workspace',[id(1)])).assignments[0];
await rpc('ops_change_assignment',[a.id,a.revision,'Completed','Confirmed complete']);
a=(await rpc('ops_workspace',[id(1)])).assignments[0];assert.equal(a.status,'Completed');assert.equal(a.verification_status,'Not yet implemented');assert.equal(a.history.length,3);
await deny(()=>rpc('ops_change_assignment',[a.id,a.revision,'In Progress','Reopen']),/closed/);
await actor(14);await deny(()=>rpc('ops_workspace',[id(1)]));assert.equal((await db.query('select * from public.ops_assignments')).rows.length,0);
await actor(15);await deny(()=>rpc('ops_assign',[id(1),c.versions[0].id,{mode:'individual',ids:[id(13)]},'2026-10-11','Normal','',[],false]));
await actor(11);await rpc('ops_delegate',[id(1),id(15),true,true]);
await actor(15);await deny(()=>rpc('ops_save_template',[task,id(1),'task',content('Edit manager template'),2,true]),/only templates/);await rpc('ops_save_template',[null,id(1),'task',content('Delegated task'),null,true]);
await rpc('ops_assign',[id(1),c.versions[0].id,{mode:'individual',ids:[id(13)]},'2026-10-11','Normal','',[],false]);
await deny(()=>rpc('ops_assign',[id(1),c.versions[0].id,{mode:'individual',ids:[id(11)]},'2026-10-11','Normal','',[],false]));
await actor(11);await rpc('ops_delegate',[id(1),id(15),false,true]);
await actor(15);assert.ok((await rpc('ops_workspace',[id(1)])).templates.length>0,'assign-only supervisor can use library');
await deny(()=>rpc('ops_save_template',[null,id(1),'task',content('No create permission'),null,true]));
await rpc('ops_assign',[id(1),c.versions[0].id,{mode:'department',value:id(3)},'2026-10-11','Normal','',[],false]);
await actor(11);await rpc('ops_assign',[id(1),c.versions[0].id,{mode:'role',value:'Employee'},'2026-10-11','Normal','',[],false]);
await rpc('ops_delegate',[id(1),id(15),false,false]);await actor(15);await deny(()=>rpc('ops_assign',[id(1),c.versions[0].id,{mode:'individual',ids:[id(13)]},'2026-10-11','Normal','',[],false]));
await actor(16);assert.equal((await rpc('ops_workspace',[id(2)])).units.length,2);
const multiTask=await rpc('ops_save_template',[null,id(2),'task',content('Unit B task'),null,true]);
const multiVersion=(await rpc('ops_workspace',[id(2)])).templates.find(t=>t.id===multiTask).versions[0].id;
await rpc('ops_assign',[id(2),multiVersion,{mode:'position',value:'Staff'},'2026-10-11','Normal','',[],false]);
assert.equal((await rpc('ops_workspace',[id(2)])).assignments.length,1);

await actor(10);const master=await rpc('ops_save_template',[null,null,'task',content('Master inspection'),null,true]);
await actor(11);work=await rpc('ops_workspace',[id(1)]);const mt=work.templates.find(t=>t.id===master);assert.ok(mt);
await deny(()=>rpc('ops_template_action',[master,null,'archive',mt.revision]));
const copy=await rpc('ops_template_action',[master,id(1),'duplicate',mt.revision]);assert.ok(copy);
await actor(10);work=await rpc('ops_workspace',[id(1)]);
await rpc('ops_assign',[id(1),mt.versions[0].id,{mode:'bum',ids:[id(11)]},'2026-10-11','Urgent','BOD assignment',[],false]);
await actor(11);work=await rpc('ops_workspace',[id(1)]);let mine=work.assignments.find(a=>a.assignee_id===id(11));await rpc('ops_update_assignment',[mine.id,mine.revision,'2026-10-12T15:00:00+08:00','High','Updated instructions','Deadline revised']);
mine=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.id===mine.id);
assert.equal(mine.priority,'High');assert.equal(mine.history.at(-1).action,'Assignment updated');
const concurrent=await Promise.allSettled([rpc('ops_change_assignment',[mine.id,mine.revision,'In Progress','Start one']),rpc('ops_change_assignment',[mine.id,mine.revision,'Completed','Start two'])]);
assert.equal(concurrent.filter(x=>x.status==='fulfilled').length,1,'one concurrent revision wins');
assert.equal(concurrent.filter(x=>x.status==='rejected').length,1,'stale concurrent request blocked');
let staff=work.assignments.find(a=>a.assignee_id===id(15));await deny(()=>rpc('ops_change_assignment',[staff.id,staff.revision,'Completed','Manager trying to complete']));
await rpc('ops_change_assignment',[staff.id,staff.revision,'Cancelled','No longer needed']);staff=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.id===staff.id);await deny(()=>rpc('ops_change_assignment',[staff.id,staff.revision,'Completed','']),/closed/);
// Department changes affect new audiences without rewriting old assignment ownership.
await reset();await db.query('update public.hris_users set business_unit_id=$1,department_id=$2 where id=$3',[id(2),id(4),id(13)]);
await actor(11);await deny(()=>rpc('ops_assign',[id(1),c.versions[0].id,{mode:'individual',ids:[id(13)]},'2026-10-11','Normal','',[],false]));
await actor(13);assert.ok((await rpc('ops_workspace',[id(1)])).assignments.length>0,'historical own assignment still available after transfer');
await reset();await db.exec('set test.actor=\'\';set role authenticated');await deny(()=>rpc('ops_workspace',[null]));
await reset();await db.exec('set role anon');await deny(()=>rpc('ops_workspace',[null]));
await reset();await db.exec(`set test.actor='${id(13)}';set role authenticated`);await deny(()=>db.query('select operations_private.delegate($1,$2,true,true)',[id(1),id(13)]));
await reset();await db.exec(`set test.actor='${id(11)}';set role authenticated`);await rpc('ops_template_action',[checklist,id(1),'archive',c.revision]);
await deny(()=>rpc('ops_assign',[id(1),c.versions[0].id,{mode:'individual',ids:[id(15)]},'2026-10-11','Normal','',[],false]));
assert.ok((await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.template_version_id===c.versions[0].id));
console.log('Operations Station: libraries, frozen versions, independent recipients, role/BU isolation, delegation, optimistic concurrency, cancellation, transfers, RLS and auth passed.');
await db.close();
const reopened=new PGlite(dataDir);await reopened.exec(`set test.actor='${id(11)}';set role authenticated`);const persisted=(await reopened.query('select public.ops_workspace($1) result',[id(1)])).rows[0].result;assert.ok(persisted.assignments.length>0);assert.equal(persisted.templates.find(t=>t.id===task).versions.length,2);await reopened.close();fs.rmSync(dataDir,{recursive:true});console.log('Persistence after database restart and authenticated reconnection passed.');
