import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {PGlite} from '@electric-sql/pglite';
import {createOperationsFixture,id} from './operationsFixture.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ops-shared-'));let db=await createOperationsFixture(dir);
const actor=async n=>db.exec(`reset role;set test.actor='${id(n)}';set role authenticated`);
const rpc=async(name,args)=>(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
const content={title:'Team opening',category:'Opening',priority:'Normal',items:[{snapshot:{title:'Inspect bar',instructions:'Clean counter'},required:true,response_type:'none'},{snapshot:{title:'Check refrigerator'},required:true,response_type:'none'},{snapshot:{title:'Arrange flowers'},required:false,response_type:'none'}]};
await actor(11);
await assert.rejects(()=>rpc('ops_import_checklists',[id(2),[content],true,'file.csv']),/cannot import/);
await assert.rejects(()=>rpc('ops_import_checklists',[id(1),[content,{...content,title:'X'}],true,'file.csv']),/Title/);
assert.equal((await rpc('ops_workspace',[id(1)])).templates.length,0,'import atomic rollback');
const ids=await rpc('ops_import_checklists',[id(1),[content],true,'file.csv']);
let w=await rpc('ops_workspace',[id(1)]);const version=w.templates.find(t=>t.id===ids[0]).versions[0].id;
const batch=await rpc('ops_assign',[id(1),version,{mode:'individual',ids:[id(13),id(15)],execution:'shared'},'2026-10-11','Normal','',[],true]);
w=await rpc('ops_workspace',[id(1)]);let a=w.assignments.find(a=>a.batch_id===batch);const run=a.checklist_run_id;assert.equal(a.members.length,2);assert.equal(a.checks.length,3);assert.equal(a.can_check,false);
await assert.rejects(()=>rpc('ops_check_item',[run,a.items[0].id,1,true,'']),/assigned team|Run unavailable/);
await assert.rejects(()=>rpc('ops_change_assignment',[a.id,a.revision,'Completed','']),/checking/);
await actor(14);await assert.rejects(()=>rpc('ops_check_item',[run,a.items[0].id,1,true,'']),/assigned team|Run unavailable/);assert.equal((await db.query('select * from public.ops_item_checks')).rows.length,0,'RLS across units');
await actor(13);a=(await rpc('ops_workspace',[id(1)])).assignments[0];assert.equal(a.members.length,2);assert.equal(a.can_check,true);
await assert.rejects(()=>db.query('update public.ops_item_checks set checked=true'),/permission/);
await rpc('ops_check_item',[run,a.items[0].id,1,true,'Ready']);
await assert.rejects(()=>rpc('ops_check_item',[run,a.items[0].id,1,false,'Undo']),/changed/);
await actor(15);a=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.batch_id===batch);assert.equal(a.status,'In Progress');assert.equal(a.checks.find(c=>c.checked).actor_name,'Employee A');
await rpc('ops_check_item',[run,a.items[1].id,1,true,'']);
a=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.batch_id===batch);assert.equal(a.status,'Completed');assert.equal(a.verification_status,'Not yet implemented');assert.ok(a.history.some(h=>h.action==='Item checked'&&h.actor_name==='Employee A'));assert.ok(a.history.some(h=>h.action==='Item checked'&&h.actor_name==='Supervisor A'));
await assert.rejects(()=>rpc('ops_check_item',[run,a.items[1].id,2,false,'']),/reason/);
await rpc('ops_check_item',[run,a.items[1].id,2,false,'Needs another inspection']);
a=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.batch_id===batch);assert.equal(a.status,'In Progress');assert.ok(a.history.some(h=>h.action==='Item unchecked'&&h.detail.note==='Needs another inspection'));
// One wins when competing item updates use the same revision.
const results=await Promise.allSettled([rpc('ops_check_item',[run,a.items[1].id,3,true,'First']),rpc('ops_check_item',[run,a.items[1].id,3,true,'Second'])]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);
await rpc('ops_check_item',[run,a.items[1].id,4,false,'Reopen for test']);
await db.exec(`reset role;update public.hris_users set business_unit_id='${id(2)}',department_id='${id(4)}' where id='${id(13)}'`);
await actor(13);a=(await rpc('ops_workspace',[id(1)])).assignments[0];assert.equal(a.can_check,false);await assert.rejects(()=>rpc('ops_check_item',[run,a.items[1].id,5,true,'']),/assigned team|Run unavailable/);
await actor(11);a=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.batch_id===batch);
await rpc('ops_update_assignment',[a.id,a.revision,'2026-10-12','High','New shared instructions','Reschedule']);w=await rpc('ops_workspace',[id(1)]);assert.ok(w.assignments.filter(a=>a.batch_id===batch).every(a=>a.priority==='High'&&a.instructions==='New shared instructions'));
a=w.assignments.find(a=>a.batch_id===batch);await rpc('ops_change_assignment',[a.id,a.revision,'Cancelled','No longer needed']);w=await rpc('ops_workspace',[id(1)]);assert.ok(w.assignments.every(a=>a.status==='Cancelled'));
await actor(15);await assert.rejects(()=>rpc('ops_check_item',[run,a.items[1].id,5,true,'']),/assigned team|Run unavailable/);
await db.close();db=new PGlite(dir);await actor(15);a=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.batch_id===batch);assert.equal(a.status,'Cancelled');assert.ok(a.checks.some(c=>c.actor_name==='Employee A'));assert.ok(a.history.some(h=>h.action==='Item unchecked'));await db.exec('reset role;set role anon');await assert.rejects(()=>rpc('ops_check_item',[run,a.items[1].id,5,true,'']),/permission/);await db.close();fs.rmSync(dir,{recursive:true,force:true});console.log('Shared checklists passed: atomic import, team checks, actor audit, required/optional progress, uncheck/reopen, stale concurrent update, transfer, shared rescheduling/cancellation, cross-unit RLS.');
