import assert from 'node:assert/strict';import {createPhase3Fixture,id} from './operationsPhase3Fixture.mjs';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {PGlite} from '@electric-sql/pglite';
const dir=mkdtempSync(join(tmpdir(),'tng-p3-'));let db=await createPhase3Fixture(dir);
const actor=async n=>db.exec(`reset role;set request.jwt.claim.sub='';set request.jwt.claims='';set test.actor='${id(n)}';set role authenticated`);
const rpc=async(n,a=[])=> (await db.query(`select public.${n}(${a.map((_,i)=>'$'+(i+1)).join(',')}) result`,n==='ops_save_response'?a.map((v,i)=>i===2?JSON.stringify(v):v):a)).rows[0].result;
const date=(await db.query("select (now() at time zone 'Asia/Manila')::date::text d")).rows[0].d;
const config={frequency:'daily',interval:1,start_date:date,end_date:'',mode:'shift',execution:'shared',timezone:'Asia/Manila',anchor:'fixed',start_time:'08:00',end_time:'12:00',due_time:'11:30',end_day_offset:0,due_day_offset:0,employee_ids:[id(13),id(15)],backup_ids:[id(15)],preferred_owner:id(13),auto_backup:true,allow_claim:true,weekdays:[1,2,3,4,5],month_day:31,short_month:'last',horizon_days:2,grace_minutes:15,remind_before:30,overdue_every:120,priority:'Normal'};
const pub=async(emp,kind='work',extra={})=>{await db.exec('reset role');return (await db.query(`insert into public.payroll_schedule_publications(employee_id,business_unit_id,effective_from,effective_to,snapshot) values($1,$2,$3,$3,$4) returning id`,[id(emp),id(1),date,[{date,kind,start:'08:00',end:'17:00',...extra}]])).rows[0].id;};
try{
 await actor(11);const tid=await rpc('ops_save_template',[null,id(1),'checklist',{title:'Opening automation',category:'Opening',items:[{snapshot:{title:'Check bar'},required:true,response_type:'yes_no'}]},null,true]);let w=await rpc('ops_workspace',[id(1)]);const version=w.templates.find(t=>t.id===tid).versions[0].id;
 await pub(13);await pub(15);await actor(11);let preview=await rpc('ops_preview_rule',[id(1),version,config,date,3]);assert.equal(preview.length,3);assert.ok(preview[0].people.every(p=>p.eligible));assert.ok(preview[1].people.every(p=>p.label==='Schedule missing'));
 const rule=await rpc('ops_save_rule',[null,id(1),'Bar opening',version,config,'Active',null,'']);await rpc('ops_retry_rule',[rule]);let aw=await rpc('ops_automation_workspace',[id(1),date]);let occ=aw.occurrences[0];assert.equal(occ.owner_id,id(13));assert.equal(occ.staff.filter(s=>s.active).length,2);assert.ok(!['Confirmed absence','Uncovered'].includes(occ.coverage));
 await db.exec('reset role');const count=(await db.query('select count(*)::int n from public.ops_assignments')).rows[0].n;await db.query('select operations_private.automation_tick()');assert.equal((await db.query('select count(*)::int n from public.ops_assignments')).rows[0].n,count);const notices=(await db.query('select count(*)::int n from public.notifications')).rows[0].n;await db.query('select operations_private.automation_tick()');assert.equal((await db.query('select count(*)::int n from public.notifications')).rows[0].n,notices);
 // Absence reports are risk; rejected reports cannot disqualify staff.
 await db.query(`insert into attendance_issues.requests values($1,$2,'absence','rejected')`,[id(13),date]);await actor(11);await rpc('ops_retry_rule',[rule]);occ=(await rpc('ops_automation_workspace',[id(1),date])).occurrences[0];assert.equal(occ.owner_id,id(13));
 await db.exec('reset role');await db.query("update attendance_issues.requests set status='pending'");await actor(11);await rpc('ops_retry_rule',[rule]);occ=(await rpc('ops_automation_workspace',[id(1),date])).occurrences[0];assert.equal(occ.owner_id,id(15));assert.ok(occ.staff.some(s=>s.id===id(13)&&!s.active));
 await actor(13);w=await rpc('ops_workspace',[id(1)]);let old=w.assignments.find(a=>a.assignee_id===id(13));await assert.rejects(()=>rpc('ops_save_response',[old.execution.items[0].id,1,'yes','',false,'']),/assigned/);
 await db.exec('reset role');await db.query('delete from attendance_issues.requests');await actor(11);await rpc('ops_retry_rule',[rule]);occ=(await rpc('ops_automation_workspace',[id(1),date])).occurrences[0];
 await actor(15);w=await rpc('ops_workspace',[id(1)]);let own=w.assignments.find(a=>a.assignee_id===id(15)&&a.status!=='Cancelled');await rpc('ops_save_response',[own.execution.items[0].id,1,'yes','',false,'']);
 await actor(11);occ=(await rpc('ops_automation_workspace',[id(1),date])).occurrences[0];await assert.rejects(()=>rpc('ops_occurrence_action',[occ.id,occ.revision,'owner',id(13),'New owner',{}]),/handover/);await rpc('ops_occurrence_action',[occ.id,occ.revision,'handover',id(13),'Staff shift handover',{}]);occ=(await rpc('ops_automation_workspace',[id(1),date])).occurrences[0];assert.equal(occ.owner_id,id(13));assert.ok(occ.history.some(h=>h.action==='handover'));
 await actor(13);own=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.assignee_id===id(13)&&a.status!=='Cancelled');assert.equal(own.execution.items[0].response.actor_name,'Supervisor A');await rpc('ops_submit_run',[own.execution.id,own.execution.revision]);await actor(11);await rpc('ops_retry_rule',[rule]);occ=(await rpc('ops_automation_workspace',[id(1),date])).occurrences[0];assert.equal(occ.coverage,'Completed');
 const completedRun=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.assignee_id===id(13)&&a.status==='Completed');await rpc('ops_reopen_run',[completedRun.execution.id,completedRun.execution.revision,'Correct submitted response']);assert.equal((await rpc('ops_automation_workspace',[id(1),date])).occurrences[0].status,'Open');await actor(13);own=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.id===completedRun.id);assert.equal(own.execution.can_write,true);await rpc('ops_submit_run',[own.execution.id,own.execution.revision]);await actor(11);await rpc('ops_retry_rule',[rule]);
 await actor(14);assert.equal((await db.query('select * from public.ops_occurrences')).rows.length,0);await assert.rejects(()=>rpc('ops_automation_workspace',[id(1),date]),/authorized/);await assert.rejects(()=>rpc('ops_save_rule',[null,id(1),'Intrusion',version,config,'Active',null,'']),/authorized/);await db.exec('reset role;set role anon');await assert.rejects(()=>rpc('ops_retry_rule',[rule]),/permission/);
 // Claims use assignment rights, not manager rights, and reject stale competing claims.
 await actor(11);const claimConfig={...config,frequency:'once',preferred_owner:'',backup_ids:[],auto_backup:false};const claimRule=await rpc('ops_save_rule',[null,id(1),'Claim competition',version,claimConfig,'Active',null,'']);await rpc('ops_retry_rule',[claimRule]);let claiming=(await rpc('ops_automation_workspace',[id(1),date])).occurrences.find(o=>o.rule_id===claimRule);
 await actor(13);const unowned=(await rpc('ops_workspace',[id(1)])).assignments.find(a=>a.occurrence_id===claiming.id&&a.assignee_id===id(13));await assert.rejects(()=>rpc('ops_submit_run',[unowned.execution.id,unowned.execution.revision]),/responsibility/);await rpc('ops_occurrence_action',[claiming.id,claiming.revision,'claim',id(13),'Taking responsibility',{}]);await actor(15);await assert.rejects(()=>rpc('ops_occurrence_action',[claiming.id,claiming.revision,'claim',id(15),'Competing claim',{}]),/changed/);
 await actor(11);const indivRule=await rpc('ops_save_rule',[null,id(1),'Separate staff work',version,{...config,mode:'fixed',execution:'individual',frequency:'once'},'Active',null,'']);await rpc('ops_retry_rule',[indivRule]);const individual=(await rpc('ops_automation_workspace',[id(1),date])).occurrences.find(o=>o.rule_id===indivRule);const indivWork=(await rpc('ops_workspace',[id(1)])).assignments.filter(a=>individual.staff.some(st=>st.assignment_id===a.id));assert.equal(new Set(indivWork.map(a=>a.execution.id)).size,2);assert.ok(indivWork.every(a=>a.occurrence_id===individual.id&&!a.can_cancel));await assert.rejects(()=>rpc('ops_change_assignment',[indivWork[0].id,indivWork[0].revision,'Cancelled','Attempt alternate control']),/Coverage/);
 await rpc('ops_occurrence_action',[individual.id,individual.revision,'skip',null,'Unit closed for event',{}]);assert.equal((await rpc('ops_automation_workspace',[id(1),date])).occurrences.find(o=>o.id===individual.id).status,'Skipped');await rpc('ops_retry_rule',[indivRule]);assert.equal((await rpc('ops_automation_workspace',[id(1),date])).occurrences.filter(o=>o.rule_id===indivRule).length,1);
 // Failed notification inserts remain queued and retry without duplicating successful deliveries.
 await db.exec('reset role');await db.query("update operations_private.ops_deliveries set state='Queued',next_attempt_at=now() where occurrence_id=$1",[claiming.id]);await db.exec("create function private.reject_notice() returns trigger language plpgsql as $$begin raise exception 'test delivery unavailable';end$$;create trigger fail_notice before insert on public.notifications for each row execute function private.reject_notice();");await db.query('select operations_private.deliver_notices()');assert.ok((await db.query("select count(*)::int n from operations_private.ops_deliveries where last_error='test delivery unavailable'")).rows[0].n>0);await db.exec('drop trigger fail_notice on public.notifications');await db.query("update operations_private.ops_deliveries set next_attempt_at=now() where state='Queued'");await db.query('select operations_private.deliver_notices()');assert.equal((await db.query("select count(*)::int n from operations_private.ops_deliveries where state='Queued' and occurrence_id=$1",[claiming.id])).rows[0].n,0);
 // Recurrence and imported attendance precedence, leave, rest, overnight.
 await db.exec('reset role');const rec=async c=>(await db.query('select operations_private.recurrence_due($1,$2) v',[c,'2028-02-29'])).rows[0].v;assert.equal(await rec({...config,start_date:'2028-01-31',frequency:'monthly',month_day:31}),true);assert.equal(await rec({...config,start_date:'2028-01-31',frequency:'monthly',month_day:31,short_month:'skip'}),false);assert.equal(await rec({...config,start_date:'2028-02-29',frequency:'once'}),true);assert.equal(await rec({...config,start_date:'2027-11-29',frequency:'monthly',interval:3,month_day:29}),true);
 const avail=async()=> (await db.query("select operations_private.availability($1,$2,$3,($3::date+time '08:00') at time zone 'Asia/Manila',($3::date+time '12:00') at time zone 'Asia/Manila',($3::date+time '09:00') at time zone 'Asia/Manila') a",[id(13),id(1),date])).rows[0].a;
 await db.query(`insert into private.test_days values($1,$2,$3,$4)`,[id(13),date,{state:'working',requiresClock:true},{}]);assert.equal((await avail()).present,true);await db.query(`insert into private.payroll_actual_days(employee_id,work_date,events,day_status) values($1,$2,'[]','Absent')`,[id(13),date]);assert.equal((await avail()).label,'Confirmed absence');await db.query('delete from private.payroll_actual_days');await db.query('update private.test_days set schedule=$1',[{approvedLeave:[{fullDay:true}]}]);assert.equal((await avail()).label,'Approved leave');await db.query("update private.test_days set schedule='{}'");
 await pub(13,'rest');assert.equal((await avail()).label,'Rest day');await pub(13,'work',{start:'22:00',end:'06:00',endDayOffset:1});const overnight=(await db.query("select operations_private.availability($1,$2,$3,($3::date+time '23:00') at time zone 'Asia/Manila',($3::date+1+time '02:00') at time zone 'Asia/Manila',($3::date+1+time '01:00') at time zone 'Asia/Manila') a",[id(13),id(1),date])).rows[0].a;assert.equal(overnight.eligible,true);
 await actor(11);const paused={...config,mode:'fixed',execution:'individual'};await rpc('ops_save_rule',[rule,id(1),'Bar opening',version,paused,'Paused',1,'Pause for revision']);await rpc('ops_retry_rule',[rule]);assert.equal((await rpc('ops_automation_workspace',[id(1),date])).rules[0].status,'Paused');
 await db.close();db=new PGlite(dir);await actor(11);aw=await rpc('ops_automation_workspace',[id(1),date]);assert.equal(aw.occurrences[0].coverage,'Completed');assert.ok(aw.occurrences[0].history.some(h=>h.action==='handover'));console.log('Phase 3 database passed: recurrence, leap/short months, shifts/overnight/leave/import precedence, missing clock-in, backups, handover preserving answers, removal rights, concurrency revisions, cron idempotency, notification dedupe, isolation, pause and restart persistence.');
}catch(e){console.error(e.message,e.where,e.detail);process.exitCode=1;}finally{await db.close();rmSync(dir,{recursive:true,force:true});}
