import assert from 'node:assert/strict';
import {createOperationsFixture,id} from './operationsFixture.mjs';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {PGlite} from '@electric-sql/pglite';
const dataDir=mkdtempSync(join(tmpdir(),'tng-phase2-'));let db=await createOperationsFixture(dataDir);
const actor=async n=>db.exec(`reset role;set test.actor='${id(n)}';set role authenticated`);
const rpc=async(name,args=[])=>{if(name==='ops_save_response')args=args.map((v,i)=>i===2?JSON.stringify(v):v);return (await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;};
const workspace=async()=>rpc('ops_workspace',[id(1)]);
const current=async batch=>(await workspace()).assignments.find(a=>a.batch_id===batch);
const content={title:'Detailed opening',category:'Opening',items:[{snapshot:{title:'Inspect cooler',min:2,max:5,unit:'°C',photo_required:true},required:true,response_type:'numeric'},{snapshot:{title:'Check counter'},required:true,response_type:'yes_no'},{snapshot:{title:'Outside tent',allow_na:true},required:true,response_type:'none'},{snapshot:{title:'Optional notes'},required:false,response_type:'text'}]};
await actor(11);const tid=await rpc('ops_save_template',[null,id(1),'checklist',content,null,true]);const v=(await workspace()).templates.find(t=>t.id===tid).versions[0].id;
const batch=await rpc('ops_assign',[id(1),v,{mode:'individual',ids:[id(13),id(15)],execution:'shared',phase:'2'},'2026-10-11','Normal','',[],true]);let a=await current(batch);const run=a.execution.id;const items=a.execution.items;
assert.equal(a.execution.items.length,4);assert.equal(a.execution.shared,true);assert.equal(a.execution.can_write,false);
await assert.rejects(()=>rpc('ops_save_response',[items[0].id,1,4,'',false,'']),/assigned/);
await actor(13);await assert.rejects(()=>rpc('ops_change_assignment',[a.id,a.revision,'Completed','']),/Submit work/);await assert.rejects(()=>rpc('ops_check_item',[run,a.items[0].id,1,true,'']),/execution form/);await assert.rejects(()=>rpc('ops_submit_run',[run,1]),/required answer/);
await rpc('ops_save_response',[items[0].id,1,8,'Cooler warmer than expected',false,'']);a=await current(batch);assert.equal(a.execution.items[0].response.issue,true);assert.equal(a.execution.outcome,'Pending');
await assert.rejects(()=>rpc('ops_save_response',[items[0].id,1,4,'',false,'']),/changed/);
await assert.rejects(()=>rpc('ops_save_response',[items[1].id,1,'no','',false,'']),/failed inspection/);
await rpc('ops_save_response',[items[1].id,1,'no','Counter needs cleaning',false,'']);
await assert.rejects(()=>rpc('ops_save_response',[items[1].id,2,'na','Not used today',false,'Change']),/Not Applicable/);
await rpc('ops_save_response',[items[2].id,1,'na','No event scheduled',false,'']);
await assert.rejects(()=>rpc('ops_save_response',[items[0].id,2,4,'Repaired',false,'']),/reason/);
a=await current(batch);await assert.rejects(()=>rpc('ops_submit_run',[run,a.execution.revision]),/photo is required/);
const photo=await rpc('ops_prepare_evidence',[items[0].id,1000]);assert.equal(await rpc('ops_cleanup_authorize',['bad']).catch(()=>false),false);
await assert.rejects(()=>rpc('ops_finish_evidence',[photo.id]),/missing or invalid/);
await db.query(`insert into storage.objects(bucket_id,name,metadata) values('ops-evidence',$1,$2)`,[photo.path,{size:1000,mimetype:'image/jpeg'}]);await rpc('ops_finish_evidence',[photo.id]);
assert.equal((await db.query('select * from storage.objects')).rows.length,1);
await db.query("update storage.objects set name='bypass'");assert.equal((await db.query('select name from storage.objects')).rows[0].name,photo.path);
await actor(14);assert.equal((await db.query('select * from storage.objects')).rows.length,0);assert.equal((await db.query('select * from public.ops_evidence')).rows.length,0);await assert.rejects(()=>rpc('ops_prepare_evidence',[items[0].id,1000]),/assigned/);
await actor(15);a=await current(batch);assert.equal(a.execution.items[0].evidence[0].uploader_name,'Employee A');
await assert.rejects(()=>rpc('ops_finish_evidence',[photo.id]),/not authorized/);
await rpc('ops_save_response',[items[3].id,1,'Opening notes','',false,'']);a=await current(batch);
await rpc('ops_submit_run',[run,a.execution.revision]);a=await current(batch);assert.equal(a.status,'Completed');assert.equal(a.execution.outcome,'Issues');assert.equal(a.execution.can_write,false);assert.equal(a.verification_status,'Not yet implemented');
await assert.rejects(()=>rpc('ops_save_response',[items[0].id,2,4,'fixed',false,'Fix']),/open run/);
await assert.rejects(()=>rpc('ops_prepare_evidence',[items[0].id,1000]),/assigned/);
await rpc('ops_reopen_run',[run,a.execution.revision,'Correct after repair']);
await rpc('ops_save_response',[items[0].id,2,4,'Repaired cooler',false,'Cooler repaired']);
const r=await Promise.allSettled([rpc('ops_save_response',[items[1].id,2,'yes','Counter cleaned',false,'Cleaned now']),rpc('ops_save_response',[items[1].id,2,'yes','Counter cleaned',false,'Concurrent'])]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);
a=await current(batch);await rpc('ops_submit_run',[run,a.execution.revision]);a=await current(batch);assert.equal(a.execution.outcome,'Clear');assert.ok(a.history.some(h=>h.action==='Response saved'&&h.actor_name==='Employee A'));assert.ok(a.history.some(h=>h.action==='Response saved'&&h.actor_name==='Supervisor A'));
// Expiration hides evidence immediately without changing historical completion.
await db.exec('reset role');await db.query("update public.ops_evidence set expires_at=now()-interval '1 second' where id=$1",[photo.id]);await actor(13);a=await current(batch);assert.equal(a.status,'Completed');assert.equal(a.execution.items[0].evidence[0].accessible,false);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await db.exec('reset role;set role service_role');const todo=await rpc('ops_cleanup_batch');assert.equal(todo.length,1);assert.equal(todo[0].id,photo.id);await rpc('ops_cleanup_record',[photo.id,'Temporary failure']);await db.exec('reset role');assert.equal((await db.query('select attempts,deleted_at,last_error from public.ops_evidence')).rows[0].attempts,1);await rpc('ops_cleanup_record',[photo.id,null]);assert.ok((await db.query('select deleted_at from public.ops_evidence')).rows[0].deleted_at);
// Individual checklist and standalone task each get separate detailed runs.
await actor(11);const single=await rpc('ops_assign',[id(1),v,{mode:'individual',ids:[id(13),id(15)],execution:'individual',phase:'2'},'2026-10-12','Normal','',[],false]);let w=await workspace();const singles=w.assignments.filter(a=>a.batch_id===single);assert.equal(new Set(singles.map(a=>a.execution.id)).size,2);assert.ok(singles.every(a=>!a.execution.shared));
const task=await rpc('ops_save_template',[null,id(1),'task',{title:'Read voltage',evidence:'numeric',unit:'V'},null,true]);const tv=(await workspace()).templates.find(t=>t.id===task).versions[0].id;const tb=await rpc('ops_assign',[id(1),tv,{mode:'individual',ids:[id(13)],phase:'2'},'2026-10-12','Normal','',[],false]);const ta=await current(tb);assert.equal(ta.execution.items.length,1);assert.equal(ta.execution.items[0].response_type,'numeric');
await rpc('ops_change_assignment',[singles[0].id,singles[0].revision,'Cancelled','Shift reassigned']);await actor(Number(singles[0].assignee_id.slice(-12)));await assert.rejects(()=>rpc('ops_save_response',[singles[0].execution.items[0].id,1,4,'',false,'']),/open run/);await actor(16);assert.equal((await workspace()).units.length,2);
await db.exec(`reset role;update public.hris_users set business_unit_id='${id(2)}' where id='${id(13)}'`);await actor(13);await assert.rejects(()=>rpc('ops_save_response',[ta.execution.items[0].id,1,220,'',false,'']),/assigned/);
await db.exec('reset role;set role anon');await assert.rejects(()=>rpc('ops_submit_run',[run,1]),/permission/);
await db.close();db=new PGlite(dataDir);await actor(15);const persisted=await current(batch);assert.equal(persisted.execution.outcome,'Clear');assert.equal(persisted.execution.items[0].response.value,4);assert.ok(persisted.execution.items[0].evidence[0].deleted_at);assert.ok(persisted.history.some(h=>h.action==='Run submitted'));await db.close();rmSync(dataDir,{recursive:true,force:true});console.log('Phase 2 passed: detailed shared/individual/task runs, required answers/photos, issue flags, NA reasons, actor audit, submission/reopen, concurrent edits, upload ownership, storage RLS, expiry, retries, transfer and anonymous denial.');
