import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createServer} from 'vite';
import react from '@vitejs/plugin-react';
import {createOperationsFixture,id} from './operationsFixture.mjs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require('playwright');
const db=await createOperationsFixture();
const tailwindPath=process.env.TNG_TEST_TAILWIND_PATH||'/tmp/tng-ops-tailwind.js';
if(!fs.existsSync(tailwindPath)){const response=await fetch('https://cdn.tailwindcss.com');if(!response.ok)throw new Error('Tailwind test asset could not load');fs.writeFileSync(tailwindPath,await response.text());}
const methods={ops_workspace:['p_unit'],ops_save_template:['p_id','p_unit','p_kind','p_content','p_revision','p_publish'],ops_template_action:['p_id','p_unit','p_action','p_revision'],ops_assign:['p_unit','p_version','p_selection','p_due','p_priority','p_instructions','p_attachments','p_verify'],ops_change_assignment:['p_id','p_revision','p_status','p_note'],ops_delegate:['p_unit','p_user','p_create','p_assign'],ops_update_assignment:['p_id','p_revision','p_due','p_priority','p_instructions','p_note']};
const harness=`import React from 'react';import {createRoot} from 'react-dom/client';import {BrowserRouter} from 'react-router-dom';import {AuthContext} from '/context/AuthContext.tsx';import OperationsStation from '/pages/OperationsStation.tsx';const user={id:window.__TEST_ACTOR,fullName:'Test account'};createRoot(document.getElementById('root')).render(React.createElement(BrowserRouter,null,React.createElement(AuthContext.Provider,{value:{user,loading:false,authError:null}},React.createElement(OperationsStation))));`;
const server=await createServer({configFile:false,root:process.cwd(),plugins:[react(),{name:'operations-test-harness',configureServer(server){server.middlewares.use(async(req,res,next)=>{if(req.url?.startsWith('/__operations-test')){res.setHeader('Content-Type','text/html');res.end(await server.transformIndexHtml(req.url,'<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><script src="/__tailwind.js"></script></head><body style="margin:0;padding:24px;background:#f1f5f9"><div id="root"></div><script type="module" src="/__ops-entry.tsx"></script></body></html>'));}else if(req.url==='/__tailwind.js'){res.setHeader('Content-Type','text/javascript');res.end(fs.readFileSync(tailwindPath));}else next();});},resolveId(source){if(source==='/__ops-entry.tsx')return '\0ops-entry.tsx';},load(source){if(source==='\0ops-entry.tsx')return harness;}}],define:{'import.meta.env.VITE_SUPABASE_URL':JSON.stringify('https://operations-test.invalid'),'import.meta.env.VITE_SUPABASE_ANON_KEY':JSON.stringify('test-publishable-key')},server:{host:'127.0.0.1',port:3187,strictPort:true}});
await server.listen();
const browser=await chromium.launch({headless:true,executablePath:process.env.TNG_TEST_CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});
let rpcQueue=Promise.resolve();
const errors=[];
async function newPage(actor,viewport){const context=await browser.newContext({viewport});await context.addInitScript(id=>{window.__TEST_ACTOR=id;},id(actor));const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error('Page error:',e.stack);});await page.route('https://operations-test.invalid/**',async route=>{const req=route.request();const name=new URL(req.url()).pathname.split('/').pop();if(req.method()==='OPTIONS'){await route.fulfill({status:200,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*'}});return;}if(!methods[name]){await route.fulfill({status:400,body:'{}'});return;}const params=req.postDataJSON();rpcQueue=rpcQueue.then(async()=>{try{await db.exec(`reset role;set test.actor='${id(actor)}';set role authenticated`);const args=methods[name].map(k=>params[k]??null);const result=(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(result),headers:{'access-control-allow-origin':'*'}});}catch(e){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({message:e.message,code:e.code}),headers:{'access-control-allow-origin':'*'}});}});await rpcQueue;});await page.goto('http://127.0.0.1:3187/__operations-test');await page.getByRole('heading',{name:'Operations Station',exact:true}).waitFor();await page.getByRole('button',{name:'Refresh',exact:true}).waitFor();await page.waitForFunction(()=>!document.body.textContent.includes('Loading your authorized workspace'));return {context,page};}
async function nav(page,name){const desktop=page.getByRole('navigation',{name:'Operations desktop navigation'});if(await desktop.isVisible())await desktop.getByRole('button',{name,exact:true}).click();else if(['Today','Progress','Tasks','Settings'].includes(name))await page.getByRole('navigation',{name:'Operations bottom navigation'}).getByRole('button',{name,exact:true}).click();else await page.getByRole('navigation',{name:'Operations workspace tools'}).getByRole('button',{name,exact:true}).click();}
async function unit(page,value){await page.getByLabel('Business-unit workspace').selectOption(id(value));await page.waitForFunction(()=>!document.body.textContent.includes('Loading your authorized workspace'));}
try{
const {page,context}=await newPage(11,{width:1440,height:1050});await unit(page,1);
await page.getByRole('button',{name:'Create task',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Check refrigerator temperature');await page.getByLabel('Instructions / SOP').fill('Read the display and check the temperature.');await page.getByLabel('Evidence requirement').selectOption('numeric');await page.getByRole('button',{name:'Publish',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
await nav(page,'Task Library');await page.getByRole('heading',{name:'Check refrigerator temperature',exact:true}).waitFor();assert.equal(await page.getByRole('heading',{name:'Check refrigerator temperature'}).count(),1);
await nav(page,'Create Checklist');await page.getByLabel('Title',{exact:true}).fill('Bar opening checklist');await page.getByLabel('Task from library').selectOption({label:'Check refrigerator temperature'});await page.getByRole('button',{name:'Add task',exact:true}).click();await page.getByLabel('Custom checklist task title').fill('Clean counter');await page.getByRole('button',{name:'Add custom',exact:true}).click();await page.getByRole('button',{name:'Move task 2 up'}).click();await page.getByLabel('Custom instructions').fill('Wipe the bar counter and sanitize.');await page.getByRole('button',{name:'Publish',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
await nav(page,'Checklist Library');await page.getByRole('button',{name:'Assign',exact:true}).click();await page.getByRole('checkbox',{name:/Employee A/}).check();await page.getByRole('checkbox',{name:/Supervisor A/}).check();await page.getByLabel('Due date and time').fill('2026-10-11T09:00');await page.getByRole('checkbox',{name:'Flag for future supervisor verification.',exact:false}).check();await page.getByRole('button',{name:'Assign to 2',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
await nav(page,'Tasks');await page.getByRole('button',{name:'Team Tasks',exact:true}).click();await page.getByRole('button').filter({hasText:'Bar opening checklist'}).first().waitFor();assert.equal(await page.getByRole('button').filter({hasText:'Bar opening checklist'}).count(),2);
await page.screenshot({path:'/tmp/tng-operations-desktop.png',fullPage:true});
await nav(page,'Checklist Library');await page.getByRole('button',{name:'Duplicate',exact:true}).click();await page.getByRole('heading',{name:'Bar opening checklist (copy)',exact:true}).waitFor();
await page.getByRole('article').filter({hasText:'Bar opening checklist (copy)'}).getByRole('button',{name:'Archive',exact:true}).click();await page.getByRole('status').filter({hasText:'Template archived'}).waitFor();
await page.reload();await page.waitForFunction(()=>!document.body.textContent.includes('Loading your authorized workspace'));assert.equal(await page.getByRole('heading',{name:'Bar opening checklist',exact:true}).count(),1);
for(const [name,viewport] of [['tablet',{width:820,height:1180}],['mobile',{width:390,height:844}]]){await page.setViewportSize(viewport);await nav(page,'Today');await page.getByRole('button',{name:'All',exact:true}).click();assert.ok(await page.getByRole('navigation',{name:'Operations bottom navigation'}).isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'no horizontal overflow '+name);await page.screenshot({path:'/tmp/tng-operations-'+name+'.png',fullPage:true});}
await context.close();
const employee=await newPage(13,{width:390,height:844});await nav(employee.page,'Tasks');await employee.page.getByRole('heading',{name:'Tasks',exact:true}).waitFor();assert.equal(await employee.page.getByRole('button',{name:'Create task',exact:true}).count(),0);assert.equal(await employee.page.getByRole('button',{name:'Task Library',exact:true}).count(),0);await employee.page.getByRole('button').filter({hasText:'Bar opening checklist'}).click();assert.equal(await employee.page.getByRole('heading',{name:'Bar opening checklist',exact:true}).count(),1);assert.ok(await employee.page.getByText('1. Clean counter',{exact:true}).isVisible());await employee.page.getByRole('button',{name:'Start task',exact:true}).click();await employee.page.getByRole('dialog').waitFor({state:'hidden'});await employee.page.getByRole('button').filter({hasText:'Bar opening checklist'}).click();await employee.page.getByRole('checkbox',{name:'I confirm I completed'}).check();await employee.page.getByRole('button',{name:'Confirm completed'}).click();await employee.page.getByRole('dialog').waitFor({state:'hidden'});await employee.page.reload();await nav(employee.page,'Tasks');await employee.page.getByRole('button',{name:'Completed',exact:true}).click();assert.ok(await employee.page.getByText('Employee confirmed · not independently verified',{exact:true}).isVisible());await employee.page.screenshot({path:'/tmp/tng-operations-employee.png',fullPage:true});await employee.context.close();
const bod=await newPage(10,{width:1440,height:1050});await bod.page.getByRole('button',{name:'Create task',exact:true}).click();await bod.page.getByLabel('Title',{exact:true}).fill('Master venue inspection');await bod.page.getByRole('button',{name:'Publish',exact:true}).click();await bod.page.getByRole('dialog').waitFor({state:'hidden'});await unit(bod.page,1);await nav(bod.page,'Task Library');const masterArticle=bod.page.getByRole('article').filter({hasText:'Master venue inspection'});await masterArticle.getByRole('button',{name:'Assign',exact:true}).click();await bod.page.getByRole('checkbox',{name:/BUM A/}).check();await bod.page.getByRole('button',{name:'Assign to 1',exact:true}).click();await bod.page.getByRole('dialog').waitFor({state:'hidden'});await nav(bod.page,'Today');await bod.page.getByRole('heading',{name:'Work assigned to Business Unit Managers'}).waitFor();await nav(bod.page,'Progress');await bod.page.getByRole('heading',{name:'Progress',exact:true}).waitFor();await nav(bod.page,'Settings');await bod.page.getByRole('heading',{name:'Supervisor permissions · Unit A',exact:true}).waitFor();await nav(bod.page,'Scheduling');await bod.page.getByText('Manual schedule:',{exact:false}).waitFor();await bod.context.close();
assert.deepEqual(errors,[]);console.log('Browser flow passed: task publishing, ordered checklist, two recipients, duplicate/archive, employee start/completion, refresh persistence, desktop/tablet/mobile and no horizontal overflow.');
}catch(e){for(const c of browser.contexts())for(const p of c.pages()){console.error((await p.locator('body').innerText()).slice(-4000));await p.screenshot({path:'/tmp/tng-ops-browser-failure.png',fullPage:true});}throw e;}finally{await browser.close();await server.close();await db.close();}
