import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import ts from 'typescript';
import ExcelJS from 'exceljs';
const source=await fs.readFile(new URL('../modules/payroll/payPackageImport.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {prepareImport,packageHeaders,componentHeaders}=await import(`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`);
const context={employeeId:'test',sourceHash:'hash',scopes:[{id:'scope',name:'Test BU',canEdit:true}],packages:[],sources:[{id:null,baseAmount:20000,rateType:'Monthly',deminimis:0,reimbursable:0,conflict:false}]};
const values=Object.fromEntries(packageHeaders.map(h=>[h,'']));Object.assign(values,{'Package key':'PKG-1','Employee code':'E-1','Business unit / payroll group':'Test BU','Pay stream':'employee_payroll','Effective from':'2026-09-01','Amount unit':'Monthly','Basic pay / fee amount':'20000','Source reference':'Approved HRIS record',Reason:'Initial setup'});
const row={row:2,values,components:[]};
assert.equal(prepareImport(row,context).payload.treatment.tax,'unreviewed');
assert.throws(()=>prepareImport({...row,values:{...values,'Basic pay / fee amount':'20001'}},context),/match/);
assert.throws(()=>prepareImport({...row,values:{...values,'Effective from':'2026-02-30'}},context),/real/);
assert.throws(()=>prepareImport(row,{...context,scopes:[]}),/access/);
assert.throws(()=>prepareImport(row,{...context,packages:[{engagement_key:'employee',effective_from:'2026-09-01',status:'draft'}]}),/already exists/);
assert.throws(()=>prepareImport(row,{...context,sources:[{...context.sources[0],deminimis:1000}]}),/deminimis/);
assert.throws(()=>prepareImport({...row,values:{...values,'Pay stream':'professional_fee'}},context),/distinct engagement/);
assert.equal(prepareImport({...row,values:{...values,'Pay stream':'professional_fee','Engagement reference':'Consulting agreement','Tax profile reference':'Reviewed profile'}},context).payload.stream,'professional_fee');
const workbook=new ExcelJS.Workbook();await workbook.xlsx.readFile(new URL('../public/templates/Pay-Packages-Batch-Template.xlsx',import.meta.url).pathname);
for(const [name,headers] of [['Packages',packageHeaders],['Components',componentHeaders]])assert.deepEqual(workbook.getWorksheet(name).getRow(1).values.slice(1),headers);
console.log('Passed: source matching, dates, scope denial, duplicate drafts, allowances, separate fees and template compatibility.');
