import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import ts from 'typescript';
import ExcelJS from 'exceljs';
const source=await fs.readFile(new URL('../modules/payroll/payPackageImport.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {prepareImport,packageHeaders,componentHeaders,simpleHeaders,simpleImportRows,assertArrangementLive}=await import(`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`);
const context={employeeId:'test',sourceHash:'hash',scopes:[{id:'scope',name:'Test BU',canEdit:true}],packages:[],sources:[{id:null,baseAmount:20000,rateType:'Monthly',deminimis:0,reimbursable:0,conflict:false}]};
const values=Object.fromEntries(packageHeaders.map(h=>[h,'']));Object.assign(values,{'Package key':'PKG-1','Employee code':'E-1','Business unit / payroll group':'Test BU','Pay stream':'employee_payroll','Effective from':'2026-09-01','Amount unit':'Monthly','Basic pay / fee amount':'20000','Source reference':'Approved HRIS record',Reason:'Initial setup'});
const row={row:2,values,components:[]};
assert.equal(prepareImport(row,context).payload.treatment.tax,'unreviewed');
assert.throws(()=>prepareImport({...row,values:{...values,'Basic pay / fee amount':'20001'}},context),/match/);
assert.throws(()=>prepareImport({...row,values:{...values,'Effective from':'2026-02-30'}},context),/real/);
assert.throws(()=>prepareImport(row,{...context,scopes:[]}),/Business unit/);
assert.throws(()=>prepareImport(row,{...context,scopes:[{...context.scopes[0],canEdit:false}]}),/editing is not allowed/);
assert.throws(()=>prepareImport(row,{...context,packages:[{engagement_key:'employee',effective_from:'2026-09-01',status:'draft'}]}),/already exists/);
assert.throws(()=>prepareImport(row,{...context,sources:[{...context.sources[0],deminimis:1000}]}),/deminimis/);
assert.throws(()=>prepareImport({...row,values:{...values,'Pay stream':'professional_fee'}},context),/distinct engagement/);
assert.equal(prepareImport({...row,values:{...values,'Pay stream':'professional_fee','Engagement reference':'Consulting agreement','Tax profile reference':'Reviewed profile'}},context).payload.stream,'professional_fee');
const workbook=new ExcelJS.Workbook();await workbook.xlsx.readFile(new URL('../public/templates/Pay-Packages-Batch-Template.xlsx',import.meta.url).pathname);
assert.deepEqual(workbook.getWorksheet('Pay Input').getRow(1).values.slice(1),simpleHeaders);
assert.equal(workbook.getWorksheet('Components'),undefined);
assert.equal(workbook.getWorksheet('Pay Input').getCell('A2').value,null);
assert.equal(workbook.getWorksheet('Pay Input').views[0].xSplit,1);
assert.equal(workbook.getWorksheet('Pay Input').getCell('I2').dataValidation.type,'list');
assert.equal(workbook.getWorksheet('Examples').getCell('A5').value,workbook.getWorksheet('Examples').getCell('A6').value);
const flat={'Employee code':'E-1','Business unit':'Test BU','Pay type':'Employee salary','Effective date':'2026-09-01','Amount unit':'Monthly','Approved basic pay / fee':'20000','Salary source':'Current HRIS record','Reason for this record':'Initial setup','Existing de minimis':'0','Existing reimbursable':'0','Extra 1 name':'Custom bike allowance','Extra 1 amount':'123.45','Extra 1 frequency':'Recurring'};
const normalize=v=>simpleImportRows([{row:2,values:v}])[0];
const prepared=prepareImport(normalize(flat),context);
assert.doesNotThrow(()=>assertArrangementLive('gross'));
assert.doesNotThrow(()=>assertArrangementLive('net_tax'));
assert.doesNotThrow(()=>assertArrangementLive('net_all'));
assert.doesNotThrow(()=>assertArrangementLive('custom_review'));
assert.equal(prepared.payload.components[2].name,'Custom bike allowance');
assert.equal(prepared.payload.components[2].amount,'123.45');
assert.equal(prepared.payload.treatment.payBasis,'gross');
assert.throws(()=>prepareImport(normalize({...flat,'Salary arrangement':'Net - company covers tax'}),context),/Agreed net/);
const net={...flat,'Salary arrangement':'Net - company covers tax and employee shares','Agreed net amount':'20000','Arrangement document':'Approved agreement'};
assert.equal(prepareImport(normalize(net),context).payload.treatment.payBasis,'net_all');
assert.equal(prepareImport(normalize(net),context).payload.treatment.tax,'unreviewed');
assert.equal(prepareImport(normalize({...net,'Salary arrangement':'Company pays income tax and employee contributions','Tax treatment':'Normal tax calculation','Arrangement document':'Approved JO dated 2026-09-01, net terms section'}),context).payload.treatment.taxRequest,'Standard - Finance reviews');
assert.throws(()=>prepareImport(normalize({...net,'Arrangement document':''}),context),/approved JO/);
assert(workbook.getWorksheet('Field Guide'));
assert.throws(()=>prepareImport(normalize({...net,'Tax treatment':'Exemption requested - evidence required'}),context),/legal basis/);
assert.equal(prepareImport(normalize({...net,'Tax treatment':'Exemption requested - evidence required','Exemption / tax basis':'Actual legal evidence'}),context).payload.treatment.tax,'unreviewed');
assert.throws(()=>prepareImport(normalize({...flat,'Extra 1 frequency':'One time'}),context),/payable date/);
assert.throws(()=>normalize({...flat,'Salary source':'Approved PAN'}),/PAN ID/);
console.log('Passed: legacy compatibility, single-row fields, custom allowance, dropdowns, freeze panes, separate examples, net metadata, exemption guards, source/date/scope/duplicate validation.');
