import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {nextPayrollStep,modeLabel,validCutoff,readSelection,workspaceKey,payrollGroupFor} from '../modules/payroll/workspace.ts';
const storage=new Map();storage.getItem=storage.get.bind(storage);
storage.set(workspaceKey('a'),JSON.stringify({scope:'aura',from:'2026-08-26',to:'2026-09-10'}));
assert.equal(readSelection(storage,'a').scope,'aura');assert.equal(readSelection(storage,'b').scope,'');
assert(validCutoff('2026-08-26','2026-09-10'));assert(!validCutoff('2026-09-10','2026-08-26'));assert(!validCutoff('2026-08-01','2026-09-10'));
assert.equal(modeLabel('shadow'),'TEST — NO PAYMENT');assert.equal(modeLabel(),'MODE UNAVAILABLE');
assert.equal(payrollGroupFor('Pay Packages'),'Employee Pay Setup');assert.equal(payrollGroupFor('Gross Pay Review'),'Run Payroll');assert.equal(payrollGroupFor('Timekeeping'),'Reports & Settings');
const r={employees:2,totalDays:4,publishedDays:3,payVisible:true,reviewedPayEmployees:1,blockedDays:1,submittedVersions:0,mode:'off',canFinalize:true};
assert.equal(nextPayrollStep(r).path,'/payroll/timekeeping');r.publishedDays=4;assert.equal(nextPayrollStep(r).path,'/payroll/pay-packages');r.reviewedPayEmployees=2;assert.equal(nextPayrollStep(r).path,'/payroll/attendance-readiness');r.blockedDays=0;assert.match(nextPayrollStep(r).label,/submit/);r.submittedVersions=1;assert.match(nextPayrollStep(r).label,/test-processing/);r.mode='shadow';assert.match(nextPayrollStep(r).label,/calculation/);
const db=new PGlite();const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const rows=[1,2].flatMap(n=>[14,15].map(day=>({employeeId:id(n),date:`2026-09-${day}`,issues:n===2&&day===15?['Missing punch']:[]})));
await db.exec(`create schema auth;create schema private;create role authenticated;create role anon;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
create function private.payroll_time_permission(uuid,text) returns boolean language sql as $$select auth.uid()='${id(9)}'::uuid and $1='${id(10)}'::uuid$$;
create function private.payroll_package_permission(uuid,uuid,text) returns boolean language sql as $$select coalesce(current_setting('test.pay',true),'yes')<>'no'$$;
create table payroll_access_scopes(id uuid,processing_mode text);insert into payroll_access_scopes values('${id(10)}','off');
create table payroll_schedule_publications(id uuid,employee_id uuid,effective_from date,effective_to date,approval_required boolean,version integer,snapshot jsonb);
create table payroll_schedule_overrides(publication_id uuid,decision text);
create table payroll_pay_packages(employee_id uuid,scope_id uuid,stream text,effective_from date,status text);
create function public.preview_payroll_time(uuid,date,date) returns jsonb language sql as $$select '${JSON.stringify({result:{rows,totalDays:4,blockedDays:1},packages:[{status:'draft',current:true},{status:'submitted',current:false}]})}'::jsonb$$;
insert into payroll_pay_packages values('${id(1)}','${id(10)}','employee_payroll','2026-09-01','approved'),('${id(2)}','${id(10)}','employee_payroll','2026-09-01','draft');
insert into payroll_schedule_publications values('${id(21)}','${id(1)}','2026-09-14','2026-09-20',false,1,'[{"date":"2026-09-14"},{"date":"2026-09-15"}]'),('${id(22)}','${id(2)}','2026-09-14','2026-09-20',true,1,'[{"date":"2026-09-14"}]');`);
await db.exec(fs.readFileSync('supabase/migrations/20260916013119_payroll_home_readiness.sql','utf8'));
await db.exec(`select set_config('test.actor','${id(9)}',false);set role authenticated;`);
const read=async(scope=id(10))=>(await db.query("select get_payroll_home_readiness($1,'2026-09-14','2026-09-15') r",[scope])).rows[0].r;
let first=await read();assert.equal(first.employees,2);assert.equal(first.publishedDays,2);assert.equal(first.savedPayEmployees,2);assert.equal(first.reviewedPayEmployees,1);assert.equal(first.submittedVersions,0);assert.equal(first.issues[0].issue,'Missing punch');
await assert.rejects(()=>read(id(11)),/scoped payroll/);
await db.exec("select set_config('test.pay','no',false)");assert.equal((await read()).reviewedPayEmployees,null);
await db.exec(`reset role;insert into payroll_schedule_overrides values('${id(22)}','approve');update payroll_pay_packages set status='approved';select set_config('test.pay','yes',false);set role authenticated;`);
let refreshed=await read();assert.equal(refreshed.publishedDays,3);assert.equal(refreshed.reviewedPayEmployees,2);
await db.exec(`select set_config('test.actor','${id(1)}',false)`);await assert.rejects(()=>read(),/scoped payroll/);
await db.exec('reset role;set role anon');await assert.rejects(()=>read(),/permission denied/);
await db.close();console.log('PASS: navigation grouping, per-user persistence, cutoff validation, next action, real refresh counts, approval distinctions, scope/role checks and restricted salary metadata.');
