// Synthetic data only. Builds the actual readiness dialog and OT components for browser checks.
import {build} from 'esbuild';
import fs from 'node:fs';
const dir='/tmp/payroll-ot-bulk-ui';fs.mkdirSync(dir,{recursive:true});
const dates=['2026-08-28','2026-09-01','2026-09-08'];
const rows=dates.map((date,i)=>({id:`r${i}`,date,updated_at:'2026-10-01T00:00:00Z',start_time:'18:30',end_time:'20:30',end_date:date,requestedMinutes:120,reviewedMinutes:null,finalMinutes:null,reason:'Closing coverage',status:'Submitted',canSend:true,canDecide:false,blocked:null,managerName:'Sample Manager',history_log:[]}));
const weeks=rows.map((row,i)=>({employeeId:'sample',employee:{name:'Sample Employee',position:'Cashier',businessUnit:'Sample BU'},version:`v${i}`,requests:[row],canConfirmBaseline:false,summary:{weekStart:['2026-08-24','2026-08-31','2026-09-07'][i],weekEnd:['2026-08-30','2026-09-06','2026-09-13'][i],regularMinutes:2880,approvedMinutes:0,reviewedMinutes:0,projectedMinutes:2880,thresholdMinutes:3000,baselineMissing:false,quantitiesMissing:false}}));
const days=dates.map(date=>({employeeId:'sample',employeeName:'Sample Employee',date,restDay:false,holiday:false,approvedFullLeave:false,scheduledMinutes:480,actualMinutes:600,regularMinutes:480,breakMinutes:60,lateMinutes:0,undertimeMinutes:0,approvedOtMinutes:0,actualOtMinutes:120,workedLunch:false,issues:['Overtime needs approval'],ready:false,shiftIds:[],eventIds:[],leaveIds:[],ot:[],segments:[]}));
await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{MemoryRouter}from'react-router-dom';import{TimekeepingEmployeeTable}from'./modules/payroll/TimekeepingEmployeeTable';function Fixture(){const[rows,setRows]=React.useState(${JSON.stringify(days)}),[refreshes,setRefreshes]=React.useState(0);return <MemoryRouter><main><h1>OT review · synthetic test</h1><p id="calls">0 requests processed</p><p>Parent refreshes: {refreshes}</p><TimekeepingEmployeeTable rows={rows} test={[]} saved={false} canOpenOffset={false} busy={false} hasReason={false} onOpenOffset={()=>{}} scopeName="Sample BU" from="2026-08-26" to="2026-09-10" onApplied={()=>{setRefreshes(n=>n+1);setRows(rows=>rows.map(r=>({...r,issues:[],ready:true})));}}/></main></MemoryRouter>}createRoot(document.getElementById('root')).render(<Fixture/>);`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,outfile:dir+'/app.js',plugins:[{name:'synthetic-only',setup(b){
 b.onResolve({filter:/services\/manualOtService$/},()=>({path:'ot',namespace:'fixture'}));
 b.onResolve({filter:/services\/supabaseClient$/},()=>({path:'supabase',namespace:'fixture'}));
 b.onResolve({filter:/historicalAttendance$/},()=>({path:'history',namespace:'fixture'}));
 b.onLoad({filter:/.*/,namespace:'fixture'},({path})=>({loader:'js',contents:path==='history'?'export const downloadHistoricalSource=()=>{};export const historyDetail=async()=>({});':path==='supabase'?'export const supabase={rpc:async()=>({data:{items:[],reviews:[]}})};':`
 let weeks=${JSON.stringify(weeks)},count=0;const manager=location.search.includes('manager');if(manager)weeks.forEach(w=>w.requests.forEach(r=>{r.canDecide=true;r.canSend=false;}));
 export const getOtWeeks=async()=>structuredClone(weeks);export const getPayrollOtWeeks=getOtWeeks;
 export const minutesLabel=n=>n==null?'Not confirmed':Math.floor(n/60)+'h'+(n%60?' '+n%60+'m':'');
 export const workDateLabel=d=>d;export const confirmOtBaseline=async()=>{};
 function record(ids,minutes,decision){count+=ids.length;document.getElementById('calls').textContent=count+' requests processed';weeks=weeks.map(w=>({...w,version:w.version+'x',requests:w.requests.map(r=>ids.includes(r.id)?{...r,canSend:false,canDecide:false,status:decision==='send'?'Submitted':'PendingBOD',reviewedMinutes:minutes?.[r.id]??null}:r)}));}
 export const sendPayrollOt=async(rows)=>{record(rows.map(r=>r.id),null,'send');return[];};
 export const decideOtWeek=async(ids,minutes)=>{record(ids,minutes,'approve');return ids.map(id=>({result:{status:'PendingBOD'}}));};
 `}));}}]});
fs.writeFileSync(dir+'/index.html','<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:16px Arial;background:#f5f5fa;color:#172033;margin:24px}button,input,textarea{font:inherit}button{padding:10px;margin:5px;cursor:pointer}dialog{width:94%;max-height:90vh;overflow:auto;border:1px solid #ddd;border-radius:16px;padding:24px}dialog::backdrop{background:#0008}table{width:100%;border-collapse:collapse}th,td{padding:12px;border-bottom:1px solid #ddd;text-align:left;vertical-align:top}header{padding:12px;background:#f8f8fb}section[aria-label="Review across all weeks"]>section{border:1px solid #ddd;margin:16px 0;border-radius:12px;overflow:hidden}footer{position:sticky;bottom:0;background:#f5f3ff;padding:16px;border:1px solid #ccc;border-radius:12px}textarea{display:block;width:98%}label span{display:inline-block}details{padding:8px}[role=status]{background:#e6ffef;padding:10px}input[type=number]{width:90px}main{max-width:1400px;margin:auto}</style></head><body><div id="root"></div><script src="app.js"></script></body></html>');
console.log(dir);
