import assert from 'node:assert/strict';
import fs from 'node:fs';
import {build} from 'esbuild';
import {pathToFileURL} from 'node:url';
import {PGlite} from '@electric-sql/pglite';
process.on('uncaughtException',e=>{console.error(e.message,e.where||'',e.actual||'');process.exit(1);});
const compiled='node_modules/.payroll-input-test.mjs';await build({entryPoints:['modules/payroll/inputTemplates.ts'],bundle:true,platform:'node',format:'esm',outfile:compiled,packages:'external'});
const {inputTemplates}=await import(pathToFileURL(process.cwd()+'/'+compiled));fs.unlinkSync(compiled);
const db=new PGlite();
const actor='00000000-0000-4000-8000-000000000001',scope='00000000-0000-4000-8000-000000000002',bu='00000000-0000-4000-8000-000000000003',employee='00000000-0000-4000-8000-000000000004',reviewer='00000000-0000-4000-8000-000000000005';
await db.exec(`create schema private;create schema auth;create role anon;create role authenticated;
create function auth.uid() returns uuid language sql as $$select current_setting('test.actor')::uuid$$;
create function public.current_hris_user_id() returns uuid language sql as $$select auth.uid()$$;
create function private.payroll_actor_id() returns uuid language sql as $$select auth.uid()$$;
create function private.actual_attendance_access(uuid) returns boolean language sql as $$select current_setting('test.allowed')='yes'$$;
create function private.historical_reconciliation_user(uuid) returns boolean language sql as $$select current_setting('test.allowed')='yes'$$;
create function private.payroll_gross_permission(uuid,text) returns boolean language sql as $$select current_setting('test.allowed')='yes'$$;
create function private.payroll_has_access(text,uuid) returns boolean language sql as $$select current_setting('test.allowed')='yes'$$;
create function public.has_active_role(text) returns boolean language sql as $$select current_setting('test.allowed')='yes'$$;
create function private.payroll_net_can_review(uuid) returns boolean language sql as $$select auth.uid()='${reviewer}'::uuid$$;
create function private.payroll_schedule_can_edit(uuid) returns boolean language sql as $$select current_setting('test.edit')='yes'$$;
create function private.schedule_preset_manage(uuid,uuid) returns boolean language sql as $$select current_setting('test.edit')='yes'$$;
create function private.is_schedule_suspended(uuid,date) returns boolean language sql as $$select false$$;
create function private.payroll_debt_creator(uuid) returns boolean language sql as $$select true$$;
create function private.payroll_service_charge_permission(uuid,text) returns boolean language sql as $$select true$$;
create function private.payroll_audit_immutable() returns trigger language plpgsql as $$begin raise exception 'Immutable audit';end$$;
create table public.payroll_access_scopes(id uuid primary key,business_unit_id uuid,name text);
create table public.hris_users(id uuid primary key,employee_id text,full_name text,business_unit_id uuid,department_id uuid,date_hired date,end_date date,is_duplicate boolean);
create table public.departments(id uuid,name text);
create table public.payroll_confirmed_policy(id int,effective_from date);
create table public.payroll_schedule_freezes(employee_id uuid,date_from date,date_to date);
create table public.shift_templates(id uuid primary key default gen_random_uuid(),name text,start_time time,end_time time,break_minutes int,grace_period_minutes int,business_unit_id uuid,created_by uuid,end_day_offset int,paid_minutes int,schedule_kind text);
create table public.shift_assignments(id uuid default gen_random_uuid(),employee_id uuid,date date,shift_template_id uuid);
create table public.payroll_schedule_publications(employee_id uuid,effective_from date,effective_to date);
create table public.payroll_pay_packages(employee_id uuid,scope_id uuid,status text,effective_from date,effective_until date,components jsonb);
create table public.payroll_debts(id uuid,employee_id uuid,authority_reference text);
create table public.leave_types(id uuid,name text);
create table public.leave_requests(id uuid default gen_random_uuid(),employee_id uuid,employee_name text,leave_type_id uuid,selected_leave_type_id uuid,selected_leave_type text,start_date date,end_date date,start_time text,end_time text,duration_days numeric,reason text,status text,attachment_url text,business_unit_id uuid,department_id uuid,history_log jsonb);
create table public.leave_balance_migration_batches(id uuid,status text);
create table public.leave_balance_migration_rows(batch_id uuid,employee_id uuid,leave_type text,as_of_date date);
create table public.payroll_service_charge_setups(id uuid,scope_id uuid,period_from date,period_to date,pay_date date,effective_date date,version int,status text,pool_amount numeric,classification_filter text,approved_rule_name text,approved_rule_reference text,approved_rule_version text,allocation_basis text,funding_source text);
create table public.payroll_service_charge_allocations(setup_id uuid,employee_id uuid,eligibility_status text,amount numeric);
create table public.payroll_disbursements(id uuid default gen_random_uuid(),settlement_key text,scope_id uuid);
create table public.payroll_payment_batches(id uuid default gen_random_uuid(),settlement_key text);
create table public.payroll_payment_closures(batch_id uuid);
create table public.payroll_payment_attempts(batch_id uuid);
create table private.test_calls(kind text,payload jsonb);
create function public.get_normal_payroll_periods(uuid,int) returns jsonb language sql as $$select '[{"releaseDate":"2026-09-20","from":"2026-08-26","to":"2026-09-10"}]'::jsonb$$;
create function public.save_schedule_builder_shift(text,date,uuid,date,uuid,uuid,uuid) returns jsonb language plpgsql as $$declare id uuid;begin insert into public.shift_assignments(employee_id,date,shift_template_id) values($3,$4,$5) returning shift_assignments.id into id;return jsonb_build_object('id',id);end$$;
create function public.save_leave_balance_migration(uuid,text,jsonb,boolean,boolean) returns jsonb language plpgsql as $$begin insert into private.test_calls values('leave-balance',jsonb_build_object('rows',$3,'submit',$4));return jsonb_build_object('id',gen_random_uuid());end$$;
create function public.create_payroll_debt_record(uuid,jsonb) returns uuid language plpgsql as $$begin insert into private.test_calls values('debt',$2);return $1;end$$;
create function public.add_payroll_debt_document_link(uuid,text,text,text,date,boolean) returns uuid language sql as $$select gen_random_uuid()$$;
create function public.act_on_payroll_debt(uuid,text,text,jsonb) returns jsonb language plpgsql as $$begin if $2<>'submit' then raise exception 'Import must not approve';end if;insert into private.test_calls values('debt-submit',jsonb_build_object('action',$2));return '{}'::jsonb;end$$;
create function public.save_payroll_service_charge(uuid,jsonb,jsonb) returns jsonb language plpgsql as $$begin insert into private.test_calls values('service-charge',$3);return '{}'::jsonb;end$$;
create function private.payroll_gross_snapshot(uuid) returns jsonb language sql as $$select jsonb_build_object('scopeId','${scope}','dateFrom','2026-08-26','dateTo','2026-09-10')$$;
create function private.calculate_payroll_gross_v1(jsonb) returns jsonb language sql as $$select '{"employees":[{"employeeId":"${employee}","gross":"1000","lines":[]}],"gross":"1000"}'::jsonb$$;
create function private.payroll_gross_line(text,numeric,numeric,numeric,jsonb) returns jsonb language sql as $$select jsonb_build_object('label',$1,'amount',($2*$3*$4)::text)||$5$$;
insert into public.payroll_access_scopes values('${scope}','${bu}','Fixture');
insert into public.hris_users(id,employee_id,full_name,business_unit_id,date_hired) values('${employee}','00001','Fixture','${bu}','2020-01-01'),('${actor}','ACTOR','Creator','${bu}','2020-01-01'),('${reviewer}','REVIEWER','Reviewer','${bu}','2020-01-01');
insert into public.leave_types values(gen_random_uuid(),'Vacation Leave');
set test.actor='${actor}';set test.allowed='yes';set test.edit='yes';`);
const originalMoney=fs.readFileSync('supabase/migrations/20260906043821_payroll_net_phase5.sql','utf8');const start=originalMoney.indexOf('create function private.payroll_net_money('),end=originalMoney.indexOf('end $$;',start)+7;await db.exec(originalMoney.slice(start,end));
await db.exec(`create function private.payroll_input_catalog() returns jsonb language sql immutable as $catalog$select '${JSON.stringify(inputTemplates).replaceAll("'","''")}'::jsonb$catalog$;`);
await db.exec(fs.readFileSync('supabase/payroll_input_imports.sql','utf8'));
await db.exec(fs.readFileSync('supabase/payroll_previous_payment.sql','utf8'));
const call=async(kind,v,confirm=false)=>(await db.query('select public.import_payroll_inputs($1,$2,$3,$4,$5,$6,$7) r',[kind,scope,'2026-08-26','2026-09-10','fixture.csv',JSON.stringify(v.map(values=>({values,rowNumber:2}))),confirm])).rows[0].r;
const schedule={employeeId:'00001',businessUnit:'Fixture',workDate:'2026-08-26',dayType:'Workday',start:'2026-08-26 22:00',end:'2026-08-27 07:00',breakStart:'2026-08-27 01:00',breakEnd:'2026-08-27 02:00'};
let r=await call('schedules',[schedule]);assert.equal(r.errors.length,0,JSON.stringify(r));assert.equal((await db.query('select count(*) n from public.shift_assignments')).rows[0].n,0);
r=await call('schedules',[schedule],true);assert.equal(r.confirmed,true);r=await call('schedules',[schedule],true);assert.equal(r.alreadyImported,true);
r=await call('schedules',[{...schedule,notes:'Changed'}]);assert.match(r.errors[0].message,/conflicting/);
await db.exec("set test.edit='no'");r=await call('schedules',[{...schedule,workDate:'2026-08-28'}]);assert.match(r.errors[0].message,/editing/);await db.exec("set test.edit='yes'");
r=await call('leave-balances',[{employeeId:'DEMO-001',leaveType:'Vacation Leave',balance:'3.5',asOf:'2026-08-25'}]);assert.match(r.errors[0].message,/Example-only/);
await db.exec(`insert into public.payroll_schedule_freezes values('${employee}','2026-08-26','2026-09-10')`);r=await call('schedules',[{...schedule,workDate:'2026-08-28'}]);assert.match(r.errors[0].message,/locked/);await db.exec('delete from public.payroll_schedule_freezes');
const overlap=[{...schedule,workDate:'2026-08-28',start:'2026-08-28 22:00',end:'2026-08-29 07:00',breakStart:'2026-08-29 01:00',breakEnd:'2026-08-29 02:00'},{...schedule,workDate:'2026-08-29',start:'2026-08-29 06:00',end:'2026-08-29 15:00',breakStart:'2026-08-29 12:00',breakEnd:'2026-08-29 13:00'}];r=await call('schedules',overlap);assert.match(r.errors[0].message,/overlap/);await assert.rejects(()=>call('schedules',overlap,true),/overlap/);assert.equal((await db.query('select count(*) n from public.shift_assignments')).rows[0].n,1);
const opening={employeeId:'00001',leaveType:'Vacation Leave',balance:'3.50',asOf:'2026-08-25'};r=await call('leave-balances',[opening],true);assert.equal(r.errors.length,0,JSON.stringify(r));assert.equal((await db.query("select payload->>'submit' s from private.test_calls where kind='leave-balance'")).rows[0].s,'true');
const debt={employeeId:'00001',reference:'REF001',kind:'Loan',original:'10000',repaid:'4000',balance:'6000',asOf:'2026-08-25',payrollDate:'2026-09-20',method:'Number of cutoffs',duration:'6',frequency:'Every cutoff',document:'https://example.com/authority'};r=await call('deductions',[debt],true);assert.equal(r.errors.length,0,JSON.stringify(r));assert.equal((await db.query("select count(*) n from private.test_calls where kind='debt-submit'")).rows[0].n,1);
const leave={employeeId:'00001',leaveType:'Vacation Leave',startDate:'2026-09-02',endDate:'2026-09-02',dayPart:'Full day',duration:'1',durationUnit:'Days',approvalReference:'REF-L1'};r=await call('leave-taken',[leave],true);assert.equal(r.errors.length,0,JSON.stringify(r));assert.equal((await db.query('select status from public.leave_requests')).rows[0].status,'Pending');
const addition={employeeId:'00001',payrollDate:'2026-09-20',kind:'Reimbursement',description:'Transport',amount:'250',document:'https://example.com/receipt',approvalReference:'R001',tax:'Excluded'};r=await call('additions',[addition],true);assert.equal(r.errors.length,0,JSON.stringify(r));await assert.rejects(()=>db.query('select private.payroll_gross_snapshot($1)',[scope]),/Finance approval/);
const additionId=(await db.query("select id from private.payroll_input_records where kind='additions'")).rows[0].id;await assert.rejects(()=>db.query("select public.review_payroll_input_addition($1,'approved','Verified receipt')",[additionId]),/Independent/);
await db.exec(`set test.actor='${reviewer}'`);await db.query("select public.review_payroll_input_addition($1,'approved','Verified receipt and excluded treatment')",[additionId]);const calculated=(await db.query('select private.calculate_payroll_gross_v1(private.payroll_gross_snapshot($1)) r',[scope])).rows[0].r;assert.equal(calculated.gross,'1250');assert.equal(calculated.employees[0].lines[0].component.tax,'excluded');
await db.exec(`set test.actor='${actor}'`);
const payment=async(ref='P001',amount='1000')=>(await db.query('select public.record_payroll_previous_payment($1,$2,$3,$4,$5,$6,$7) id',[scope,'2026-08-26','2026-09-10',amount,'2026-09-20',ref,'https://example.com/paid'])).rows[0].id;
const pid=await payment();assert.equal(await payment(),pid);await assert.rejects(()=>payment('P001','999'),/different evidence/);
const key=`regular:${scope}:2026-08-26:2026-09-10`;await assert.rejects(()=>db.query('insert into public.payroll_payment_batches(settlement_key) values($1)',[key]),/second disbursement/);
await assert.rejects(()=>db.query("select public.review_payroll_previous_payment($1,'verified','Verified')",[pid]),/Independent/);
await db.exec(`set test.actor='${reviewer}'`);await db.query("select public.review_payroll_previous_payment($1,'verified','Bank evidence verified')",[pid]);await assert.rejects(()=>db.query('insert into public.payroll_disbursements(settlement_key,scope_id) values($1,$2)',[key,scope]),/second disbursement/);
await db.exec("set test.allowed='no'");await assert.rejects(()=>call('schedules',[schedule],true),/authorized/);
await db.exec('set role anon');await assert.rejects(()=>db.query('select * from private.payroll_previous_payments'),/permission denied/);
await db.close();console.log('PASS: real import functions, atomic previews, schedules, opening submission, Finance debt routing, pending leave, approved additions in gross, previous-payment verification and duplicate-disbursement guards.');
