import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
const migration='supabase/migrations/20260930012424_payroll_preparation_single_snapshot.sql';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`create schema private;create schema auth;create schema payroll_workspace_private;
create role anon;create role authenticated;
create sequence permission_calls;create sequence preview_calls;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
create function private.payroll_time_permission(uuid,text) returns boolean language sql stable as $$select auth.uid() is not null and current_setting('test.allowed')='yes'$$;
create function private.payroll_package_permission(uuid,uuid,text) returns boolean language plpgsql as $$begin perform nextval('public.permission_calls');return current_setting('test.pay')='yes';end$$;
create function private.payroll_time_review(uuid,date,date) returns jsonb language plpgsql as $$begin perform nextval('public.preview_calls');return current_setting('test.review')::jsonb;end$$;
create function private.payroll_time_evidence(jsonb,jsonb) returns jsonb language sql stable as $$select $1$$;
create function private.schedule_preset_visible(uuid) returns boolean language sql stable as $$select true$$;
create table hris_users(id uuid,employee_id text);
create table payroll_access_scopes(id uuid,business_unit_id uuid,processing_mode text);
create table payroll_pay_packages(employee_id uuid,scope_id uuid,stream text,status text,effective_from date);
create table payroll_time_packages(id uuid,scope_id uuid,date_from date,date_to date,version int,status text,created_at timestamptz,submitted_at timestamptz,reason text,previous_id uuid,source_hash text,result jsonb);
create table shift_templates(id uuid,name text,start_time time,end_time time,business_unit_id uuid,created_by uuid);
create table payroll_schedule_publications(id uuid,employee_id uuid,effective_from date,effective_to date,approval_required boolean,version int,snapshot jsonb);
create table payroll_schedule_overrides(publication_id uuid,decision text);
set test.allowed='yes';set test.pay='yes';set test.actor='${id(9)}';
insert into payroll_access_scopes values('${id(8)}','${id(8)}','live');
insert into hris_users values('${id(1)}','T1'),('${id(2)}','T2');
insert into payroll_pay_packages values('${id(1)}','${id(8)}','employee_payroll','approved','2026-01-01');
`);
const rows=[1,2].flatMap(n=>Array.from({length:16},(_,i)=>({employeeId:id(n),employeeName:`Employee ${n}`,date:new Date(Date.UTC(2026,7,26+i)).toISOString().slice(0,10),ready:true,issues:i===0?['Employee profile information incomplete']:[]})));
await db.query("select set_config('test.review',$1,false)",[JSON.stringify({sourceHash:'fixed-source',source:{holidays:[],rules:[]},result:{rows,totalDays:32,blockedDays:0}})]);
await db.exec(fs.readFileSync('tests/fixtures/preview_payroll_timeBeforePreparation.sql','utf8'));
await db.exec(fs.readFileSync('tests/fixtures/readinessBeforePreparation.sql','utf8'));
const query=`select public.preview_payroll_time('${id(8)}','2026-08-26','2026-09-10') v`;
const oldTime=(await db.query(query)).rows[0].v;
const oldReadiness=(await db.query(`select payroll_workspace_private.readiness('${id(8)}','2026-08-26','2026-09-10') v`)).rows[0].v;
await db.exec(fs.readFileSync(migration,'utf8'));
await db.exec('alter sequence permission_calls restart with 1;alter sequence preview_calls restart with 1;');
const combined=async()=> (await db.query(`select public.get_payroll_preparation('${id(8)}','2026-08-26','2026-09-10') v`)).rows[0].v;
const result=await combined();
assert.deepEqual(result.time,oldTime);
delete result.readiness.checkedAt;delete oldReadiness.checkedAt;assert.deepEqual(result.readiness,oldReadiness);
assert.equal((await db.query('select last_value from preview_calls')).rows[0].last_value,1,'One attendance engine call');
assert.equal((await db.query('select last_value from permission_calls')).rows[0].last_value,4,'Two passes over employees, not 32 dates');
assert.equal(result.time.result.blockedDays,1,'Missing package still blocks the appropriate day');
await db.exec("set test.pay='no'");
const restricted=await combined();assert.equal(restricted.readiness.payVisible,false);assert.equal(restricted.readiness.reviewedPayEmployees,null);assert.equal(restricted.time.result.blockedDays,0,'No compensation information leaked');
await db.exec("set test.allowed='no'");await assert.rejects(combined,/scoped payroll duty/);
await db.exec("set test.allowed='yes';set test.actor=''");await assert.rejects(combined,/scoped payroll duty/);
assert.equal((await db.query("select has_function_privilege('anon','public.get_payroll_preparation(uuid,date,date)','execute') ok")).rows[0].ok,false);
assert.equal((await db.query("select has_function_privilege('authenticated','payroll_workspace_private.readiness_from_preview(uuid,date,date,jsonb)','execute') ok")).rows[0].ok,false);
console.log('PASS preparation: same rows/readiness, one calculation, employee-level checks, restricted compensation, unauthorized denial, private evidence helper.');
await db.close();
