import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
const scope='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',employee='00000000-0000-4000-8000-000000000003';
await db.exec(`create role anon;create role authenticated;create schema private;create schema auth;
create function auth.uid() returns uuid language sql as $$select null::uuid$$;
create table public.payroll_access_scopes(id uuid primary key);
create function private.payroll_gross_permission(s uuid,a text) returns boolean language sql as $$select s::text=current_setting('test.scope',true) and (a='view' or current_setting('test.duty',true)='prepare')$$;
create function private.payroll_has_access(a text,s uuid) returns boolean language sql as $$select false$$;
create function private.payroll_package_permission(e uuid,s uuid,a text) returns boolean language sql as $$select s::text=current_setting('test.scope',true) and current_setting('test.employee_denied',true)<>'yes'$$;`);
for(const file of ['20260920013529_isolated_payroll_scenario_run.sql','20260920020734_authorized_test_payroll_calculation.sql','20260920021029_test_payroll_calculation_hash_fix.sql','20260920021116_test_payroll_decimal_inputs.sql','20260920021239_test_payroll_view_capabilities.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));
await db.query('insert into public.payroll_access_scopes values($1),($2)',[scope,other]);
await db.query("insert into payroll_scenario_private.runs(seed_run_id,scope_id,label,date_from,date_to,pay_date,snapshot) values('fixture',$1,'TEST','2026-08-11','2026-08-25','2026-09-05',$2)",[scope,JSON.stringify({employees:[{id:employee}],initialSnapshot:{privateHistory:true},beforeMockSnapshot:{privateHistory:true}})]);
// Pure calculation arithmetic is checked against the existing engines separately.
// Stub only this leaf to exercise the public authorization wrapper without real data.
await db.exec(`create or replace function payroll_scenario_private.calculate_mock_run(p_seed text) returns jsonb language sql as $$select jsonb_build_object('seed',p_seed,'isTest',true)$$;`);
await db.exec(`set role authenticated;set test.scope='${scope}';set test.duty='view';set test.employee_denied='no';`);
const read=async(s=scope)=>(await db.query('select public.get_payroll_scenario_run($1,$2,$3) r',[s,'2026-08-11','2026-08-25'])).rows[0].r;
const calc=async(s=scope)=>(await db.query('select public.calculate_payroll_scenario_demo($1,$2,$3) r',[s,'2026-08-11','2026-08-25'])).rows[0].r;
assert.equal((await read()).canCalculateTest,false);
assert.equal((await read()).snapshot.initialSnapshot,undefined);
await assert.rejects(()=>read(other),/Scoped payroll/);
await assert.rejects(()=>calc(),/Scoped payroll preparation/);
await db.exec("set test.duty='prepare'");assert.equal((await read()).canCalculateTest,true);assert.equal((await calc()).isTest,true);
await db.exec("set test.employee_denied='yes'");await assert.rejects(()=>read(),/Employee compensation/);await assert.rejects(()=>calc(),/Employee compensation/);
await assert.rejects(()=>db.exec('select * from payroll_scenario_private.runs'),/permission denied/);
await assert.rejects(()=>db.exec('delete from payroll_scenario_private.calculations'),/permission denied/);
await db.exec('reset role;set role anon');await assert.rejects(()=>calc(),/permission denied/);
await db.close();console.log('PASS: authorized read/calculate; view-only denied; wrong BU denied; restricted employee denied; private tables inaccessible; anonymous denied; historic snapshots omitted.');
