import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
const source=readFileSync('modules/payroll/RunPayroll.tsx','utf8');
const ast=ts.createSourceFile('run.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
let calculate,footer;
function visit(n){if(ts.isFunctionDeclaration(n)&&n.name?.text==='calculate')calculate=n.getText(ast);if(ts.isJsxElement(n)&&n.openingElement.tagName.getText(ast)==='footer')footer=n.getText(ast);ts.forEachChild(n,visit);}visit(ast);
const compile=s=>ts.transpileModule('('+s+')',{compilerOptions:{jsx:ts.JsxEmit.React,target:ts.ScriptTarget.ES2020}}).outputText;
let calls=0;
const state={submitted:null,attendanceCanHandover:true,existing:'previous-draft',gross:null,unit:{gross:{canCalculate:false}},scope:'fixture',from:'2026-08-26',to:'2026-09-10',time:{sourceHash:'verified'},busy:false,error:'',notice:'',setBusy:x=>state.busy=x,setError:x=>state.error=x,setNotice:x=>state.notice=x,setRevision:()=>{},prepareAttendance:async()=>{calls++;throw Error('Attendance fixes still await approval. Complete those decisions before calculating payroll.');}};
const action=vm.runInNewContext(compile(calculate),state);
await action();assert.equal(calls,1);assert.match(state.error,/await approval/);assert.equal(state.busy,false);assert.equal(state.notice,'');
state.prepareAttendance=async()=>{calls++;return 'saved-handover';};
await action();assert.equal(calls,2);assert.match(state.notice,/sent to Finance/);assert.equal(state.error,'');
state.unit.gross.canCalculate=true;await action();assert.match(state.error,/Open the existing payroll/);assert.equal(calls,2);
const props={...state,React,step:0,fresh:false,button:'button',busy:false,saveDraft(){},calculate(){},setStep(){}};
props.error='Attendance fixes still await approval.';props.notice='';
const html=renderToStaticMarkup(vm.runInNewContext(compile(footer),props));
assert.match(html,/role="alert"/);assert.match(html,/href="#payroll-attendance-approvals"/);assert.match(html,/pr-24/);assert.doesNotMatch(html,/class="[^"]*fixed/);
console.log('PASS: handover errors are visible beside the action; approval link, successful HR handover with existing draft, and Finance recalculation guard.');
