import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import {jsPDF} from 'jspdf';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
const source=readFileSync('modules/payroll/RunPayroll.tsx','utf8');
const ast=ts.createSourceFile('run.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),functions={};let footer;
function visit(n){if(ts.isFunctionDeclaration(n)&&n.name)functions[n.name.text]=n.getText(ast);if(ts.isJsxElement(n)&&n.openingElement.tagName.getText(ast)==='footer')footer=n.getText(ast);ts.forEachChild(n,visit);}visit(ast);
const compile=s=>ts.transpileModule('('+s+')',{compilerOptions:{jsx:ts.JsxEmit.React,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const employee={employeeId:'e',employeeName:'Fixture Employee',gross:'15000.00',deductions:'2228.70',net:'12771.30',tax:'100.00',mandatory:'1628.70',employer:'2300.00',contributions:[{label:'SSS EE',monthly:'1500.00',prior:'0.00',amount:'750.00'}],loans:[{account:'Fixture loan',amount:'400.00',sourceRef:'Authorized fixture'}],otherDeductions:[{label:'Fixture deduction',amount:'100.00',sourceRef:'Authorized fixture'}]};
const gross={id:'gross',result:{employees:[employee]}},net={id:'net',current:true,payDate:'2026-09-20',result:{employees:[employee]}};
let grossCalls=0,pdf;const downloads=[],persisted=[];
const state={React,Link:({to,children,...p})=>React.createElement('a',{href:to,...p},children),calculationBlocked:true,submitted:{id:'time'},attendanceCanHandover:true,existing:'',gross:null,net:null,unit:{name:'Fixture BU',gross:{canCalculate:true}},scope:'scope',from:'2026-08-26',to:'2026-09-10',time:{sourceHash:'hash'},busy:false,error:'',notice:'',step:0,fresh:true,button:'button',setBusy:x=>state.busy=x,setError:x=>state.error=x,setNotice:x=>state.notice=x,setGross:x=>state.gross=x,setNet:x=>state.net=x,setStep:x=>state.step=x,setFinance:x=>state.finance=x,setRevision(){},remember:x=>persisted.push(x),prepareGross:async()=>{grossCalls++;return 'gross';},getGrossRun:async()=>gross,netWorkspace:async()=>({review:null}),prepareNet:async()=> 'net',getNetRun:async()=>net,saveNetReview:async()=>{},saveDraft(){},downloadText:(name,text)=>downloads.push({name,text}),require:name=>{assert.equal(name,'jspdf');return {jsPDF:class {constructor(){const doc=new jsPDF();doc.save=name=>{pdf={name,bytes:doc.output('arraybuffer')};};return doc;}}};}};
const calculate=vm.runInNewContext(compile(functions.calculate),state);state.calculate=calculate;
await calculate();assert.equal(grossCalls,0);assert.match(state.error,/checklist/);
state.calculationBlocked=false;await calculate();assert.equal(state.step,1);assert.equal(state.gross.id,'gross');assert.equal(state.net,null);assert.match(state.notice,/Finance must review/);
const review=vm.runInNewContext(compile(functions.reviewAndCalculate),state);
state.saveNetReview=async()=>{throw Error('Opening balances missing');};await review({},'fixture');assert.equal(state.step,1);assert.match(state.error,/Opening balances/);assert.equal(state.net,null);assert.equal(state.busy,false);
state.saveNetReview=async()=>{};await review({},'fixture');assert.equal(state.step,2);assert.equal(state.net.id,'net');assert.deepEqual(JSON.parse(JSON.stringify(persisted.at(-1))),{grossId:'gross',netId:'net'});
const exportDraft=vm.runInNewContext(compile(functions.exportDraft),state);
for(const kind of ['register','contributions','deductions','payslips'])await exportDraft(kind);
assert.equal(state.error,'');assert.equal(downloads.length,3);assert.match(downloads[0].text,/Fixture Employee.*15000.00.*2228.70.*12771.30/);assert.match(downloads[1].text,/SSS EE/);assert.match(downloads[2].text,/Fixture loan/);assert.ok(pdf.bytes.byteLength>1000);assert.match(pdf.name,/DRAFT-payslips/);
const html=renderToStaticMarkup(vm.runInNewContext(compile(footer),state));assert.match(html,/href="\/payroll\/approvals\?net=net"/);
state.getNetRun=async()=>({...net,current:false});await exportDraft('register');assert.equal(downloads.length,3);assert.match(state.error,/Source records changed/);
console.log('PASS: blocked setup → gross → missing Finance input recovery → net → all four real document exports → correct approval link; stale downloads rejected. Synthetic records only.');
