import {build} from 'esbuild';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const dir=await mkdtemp(join(tmpdir(),'payroll-self-service-'));
try{
 const output=join(dir,'test.cjs');await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import assert from 'node:assert/strict';import PayslipView,{payslipGroups} from './modules/payroll/PayslipView';import {buildPayslipPdf} from './modules/payroll/payslipPdf';
const slip={id:'fixture',employeeName:'Sample Employee',employeeNumber:'TEST-001',businessUnit:'Sample BU',from:'2026-08-16',to:'2026-08-31',payDate:'2026-09-01',version:'2',payrollStatus:'Released',gross:'1000',deductions:'100',net:'900',tax:'100',contact:'Payroll team',lines:[{label:'Regular pay',amount:'800',date:'2026-08-17',quantity:'8',rate:'100'},{label:'Approved overtime',amount:'200',quantity:'2',rate:'100'}],contributions:[],loans:[],otherDeductions:[]};
const markup=renderToStaticMarkup(<PayslipView slip={slip}/>);assert.match(markup,/<details/);assert.match(markup,/Approved overtime/);assert.match(markup,/Attendance date/);assert.match(markup,/2026-08-17/);assert.match(markup,/TEST-001/);assert.doesNotMatch(markup,/<input|<textarea/);
const special={...slip,lines:[{kind:'earning',label:'Additional pay',amount:'1200',remaining:'200',settled:'1000'},{kind:'deduction',label:'Company deduction',amount:'100',remaining:'20'},{kind:'employer',label:'Employer only cost',amount:'30',remaining:'30'}]};const groups=payslipGroups(special);assert.equal(groups[0].lines.length,1);assert.equal(groups[5].lines[0].label,'Company deduction');assert.doesNotMatch(renderToStaticMarkup(<PayslipView slip={special}/>),/Employer only cost/);
(async()=>{const pdf=await buildPayslipPdf(slip);const bytes=pdf.output('arraybuffer');assert.ok(bytes.byteLength>1000);assert.equal(Buffer.from(bytes).subarray(0,5).toString(),'%PDF-');console.log('PASS: read-only snapshot rendering, expandable item details, special-pay categories and PDF generation');})().catch(e=>{console.error(e);process.exitCode=1;});`},outfile:output,bundle:true,platform:'node',format:'cjs',plugins:[{name:'no-network',setup(b){b.onResolve({filter:/supabaseClient$/},()=>({path:'stub',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:'export const supabase={};',loader:'js'}));}}]});await import(pathToFileURL(output));
 const quick=await readFile('components/dashboard/QuickLinks.tsx','utf8'),dashboard=await readFile('pages/Dashboard.tsx','utf8'),app=await readFile('App.tsx','utf8');assert.ok(quick.indexOf("id: 'payslips'")>quick.indexOf("id: 'profile'"));assert.ok(quick.indexOf("id: 'payslips'")<quick.indexOf("id: 'oncall'"));assert.match(quick,/name: 'My Payslips', path: '\/payroll\/payslips'/);assert.doesNotMatch(dashboard,/>My payslips<|>My Payslips</);assert.equal((app.match(/path="payslips"/g)||[]).length,1);console.log('PASS: Quick Link order, original route, loose link removed');
}finally{await rm(dir,{recursive:true,force:true});}
