import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import ts from 'typescript';
import vm from 'node:vm';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const sql=fs.readFileSync('supabase/migrations/20261002065315_automatic_payroll_review_context.sql','utf8');
const helper=sql.slice(sql.indexOf('create or replace function private.payroll_net_package_terms'),sql.indexOf('revoke all on function private.payroll_net_package_terms'));
const db=new PGlite();await db.exec('create schema private;');await db.exec(helper);
const pkg=(id,basis,date)=>({id,effective_from:date,rate_type:'Monthly',base_amount:'30000',source_ref:'Synthetic approved agreement',stream:'employee_payroll',treatment:{payBasis:basis,tax:'included',netTarget:'30000',arrangementRef:'Synthetic approved agreement'}});
const result={employees:[{employeeId:'employee',employeeName:'Synthetic employee',gross:'15000.00',lines:[{label:'Basic',packageId:'approved',amount:'15000.00'}]}]};
const packages=[pkg('approved','net_all','2026-01-01'),pkg('future','gross','2027-01-01')];
const terms=async(r=result,p=packages)=>(await db.query('select private.payroll_net_package_terms($1::jsonb,$2::jsonb) t',[JSON.stringify(r),JSON.stringify(p)])).rows[0].t;
const auto=await terms();assert.equal(auto[0].payBasis,'net_all');assert.equal(auto[0].packages.length,1,'Future and unused packages do not override the snapshot');assert.equal(auto[0].taxLines[0].treatment,'included');assert.equal(auto[0].cutoffTarget,'15000.00');
const mixed=structuredClone(result);mixed.employees[0].lines.push({packageId:'changed',amount:'100.00'});const conflict=await terms(mixed,[...packages,pkg('changed','net_tax','2026-09-01')]);assert.equal(conflict[0].payBasis,'mixed');assert.match(conflict[0].issue,/during this cutoff/);
const dir=mkdtempSync(join(tmpdir(),'finance-defaults-'));
try{
 const output=await build({entryPoints:['modules/payroll/netPay.ts'],bundle:true,platform:'node',format:'cjs',write:false,define:{'import.meta.env.VITE_SUPABASE_URL':'"https://example.invalid"','import.meta.env.VITE_SUPABASE_ANON_KEY':'"fixture-only"'}});
 fs.writeFileSync(join(dir,'test.cjs'),output.outputFiles[0].text);const {initialNetInputs,arrangementLabel}=createRequire(import.meta.url)(join(dir,'test.cjs'));
 const w={gross:{id:'fixture-gross',from:'2026-08-26',to:'2026-09-10',current:true,result},runs:[],loans:[],packageTerms:auto,review:null,defaults:{payDate:'2026-09-20',contributionMonth:'2026-09-01',cutoff:'2',insufficientNet:'block',policyRef:'Configured fixture',previousRunId:'',sourceRef:'Automatic fixture reference'}};const p=initialNetInputs(w);assert.equal(p.payDate,'2026-09-20');assert.equal(p.cutoff,'2');assert.equal(p.employees[0].netTarget,'15000.00');
 assert.equal(p.employees[0].payBasis,'net_all');assert.equal(p.employees[0].arrangementRef,'Synthetic approved agreement');assert.equal(p.employees[0].taxLines[0].taxable,'15000.00');
 assert.equal(p.employees[0].openingTaxable,'','Unknown tax history is not fabricated as zero');assert.deepEqual(p.allocation,{sss:'0.5',philhealth:'0.5',pagibig:'0.5'});
 w.review={inputs:{...p,allocation:{sss:'1',philhealth:'0',pagibig:'1'},employees:[{...p.employees[0],payBasis:'gross'}]}};
 const reopened=initialNetInputs(w);assert.equal(reopened.employees[0].payBasis,'net_all');assert.equal(reopened.allocation.sss,'0.5');
 const page=fs.readFileSync('modules/payroll/NetPayPage.tsx','utf8');const ast=ts.createSourceFile('review.tsx',page,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let initializer;
 const visit=n=>{if(ts.isVariableDeclaration(n)&&n.name.getText(ast)==='ReviewForm')initializer=n.initializer.getText(ast);ts.forEachChild(n,visit);};visit(ast);
 const component=vm.runInNewContext(ts.transpileModule('('+initializer+')',{compilerOptions:{jsx:ts.JsxEmit.React,target:ts.ScriptTarget.ES2022}}).outputText,{React,useState:React.useState,initialNetInputs,arrangementLabel,input:'input',Card:({title,children})=>React.createElement('section',null,title,children),Button:({children,disabled,type})=>React.createElement('button',{disabled,type},children),PayrollATDQueue:()=>null});
 const html=renderToStaticMarkup(React.createElement(component,{w,busy:false,onWorking(){},save:async()=>{}}));
 assert.match(html,/2026-09-20/);assert.match(html,/2026-09/);assert.match(html,/Second cutoff/);assert.match(html,/50% each payroll cutoff/);
 assert.doesNotMatch(html,/<select|type="date"|type="text"|type="number"/,'Known settings and net guarantee are no longer manual inputs');
 assert.doesNotMatch(html,/Different dated package terms|choose per employee/);assert.match(html,/Calculated cutoff entitlement/);

}finally{rmSync(dir,{recursive:true,force:true});}
// Exercise the real save function's canonicalization with minimal persistence fixtures.
await db.exec(`create schema auth;create table public.payroll_gross_runs(id uuid,scope_id uuid,result jsonb,source_snapshot jsonb,date_from date,date_to date);
create table public.payroll_net_reviews(id uuid default gen_random_uuid(),revision serial,gross_run_id uuid,scope_id uuid,inputs jsonb,source_ref text,approved_by uuid,approved_at timestamptz default now());
create table public.payroll_net_runs(id uuid,scope_id uuid,date_from date,date_to date,source_snapshot jsonb,version int);
create function private.payroll_gross_permission(uuid,text) returns boolean language sql as $$select true$$;
create table public.hris_users(id uuid,sss_no text,philhealth_no text,pagibig_no text,tin text);
create function private.payroll_net_can_review(uuid) returns boolean language sql as $$ select coalesce(current_setting('test.allowed',true),'yes')='yes' $$;
create function public.current_hris_user_id() returns uuid language sql as $$select '00000000-0000-0000-0000-000000000099'::uuid$$;
create function private.payroll_net_review_for_actor(jsonb,jsonb,text) returns jsonb language sql as $$select $1$$;
create function private.payroll_net_review_validate(uuid,jsonb) returns void language plpgsql as $$begin null;end$$;`);
const start=sql.indexOf('CREATE OR REPLACE FUNCTION public.save_payroll_net_review');const end=sql.length;await db.exec(sql.slice(start,end));
await db.exec(sql.slice(sql.indexOf('create or replace function private.payroll_net_context'),sql.indexOf('revoke all on function private.payroll_net_context')));
// Use the app's two monthly periods, including cross-year cutoffs.
await db.exec(`create or replace function public.get_normal_payroll_periods(uuid,integer) returns jsonb language sql as $$select jsonb_agg(jsonb_build_object('releaseDate',(m+(c->>'releaseDay')::int-1)::date,'from',((m+make_interval(months=>(c->>'startMonthOffset')::int))::date+(c->>'startDay')::int-1)::date,'to',((m+make_interval(months=>(c->>'endMonthOffset')::int))::date+(c->>'endDay')::int-1)::date,'policy','Synthetic configured calendar')) from (select make_date($2,n,1) m from generate_series(1,12)n) months cross join lateral jsonb_array_elements('[{"releaseDay":5,"startDay":11,"endDay":25,"startMonthOffset":-1,"endMonthOffset":-1},{"releaseDay":20,"startDay":26,"endDay":10,"startMonthOffset":-1,"endMonthOffset":0}]'::jsonb)c$$;`);
const eid='00000000-0000-0000-0000-000000000001',gid='00000000-0000-0000-0000-000000000002',sid='00000000-0000-0000-0000-000000000003';
const r=structuredClone(result);r.employees[0].employeeId=eid;
await db.query("insert into public.payroll_gross_runs values($1,$2,$3,$4,'2026-08-26','2026-09-10')",[gid,sid,JSON.stringify(r),JSON.stringify({packages})]);await db.query('insert into public.hris_users(id) values($1)',[eid]);
const payload={payDate:'2026-12-25',contributionMonth:'2026-12-01',cutoff:'1',allocation:{sss:'1',philhealth:'0',pagibig:'1'},employees:[{employeeId:eid,payBasis:'gross',arrangementRef:'client override'}]};
const saved=await db.query('select public.save_payroll_net_review($1,$2,$3) id',[gid,JSON.stringify(payload),'Synthetic review']);
const stored=(await db.query('select inputs from public.payroll_net_reviews where id=$1',[saved.rows[0].id])).rows[0].inputs;
assert.equal(stored.payDate,'2026-09-20');assert.equal(stored.contributionMonth,'2026-09-01');assert.equal(stored.cutoff,'2');assert.equal(stored.insufficientNet,'block');assert.equal(stored.employees[0].netTarget,'15000.00');
assert.equal(stored.employees[0].payBasis,'net_all');assert.equal(stored.employees[0].arrangementRef,'Synthetic approved agreement');assert.deepEqual(stored.allocation,{sss:'0.5',philhealth:'0.5',pagibig:'0.5'});
await db.query('insert into public.payroll_net_runs values($1,$2,$3,$4,$5,1)',['00000000-0000-0000-0000-000000000004',sid,'2026-08-11','2026-08-25',JSON.stringify({review:{payDate:'2026-09-05'}})]);
const context=async()=>(await db.query('select private.payroll_net_context($1) c',[gid])).rows[0].c;
assert.equal((await context()).previousRunId,'00000000-0000-0000-0000-000000000004');
await db.query("update public.payroll_gross_runs set date_from='2026-12-11',date_to='2026-12-25' where id=$1",[gid]);
assert.equal((await context()).payDate,'2027-01-05');assert.equal((await context()).cutoff,'1');assert.equal((await context()).previousRunId,'');
await db.query("update public.payroll_gross_runs set date_from='2026-12-12' where id=$1",[gid]);
await assert.rejects(context,/configured payroll period/);
await db.exec("select set_config('test.allowed','no',false)");
await assert.rejects(()=>db.query('select public.save_payroll_net_review($1,$2,$3)',[gid,JSON.stringify(payload),'Synthetic']),/authorization/);
await db.close();
console.log('PASS: approved package and cutoff target; automatic calendar (including year rollover), prior payroll link and server enforcement; rendered form has no manual date, salary or reference controls; preserved unknown history and authorization. Synthetic data only.');
