import assert from 'node:assert/strict';
import {build} from 'esbuild';
const {outputFiles}=await build({entryPoints:['services/pulseCompliance.ts'],bundle:true,platform:'node',format:'esm',write:false});
const {filterCompliance,emptyComplianceFilters,complianceCsv,complianceSummary,complianceExportSheets}=await import('data:text/javascript;base64,'+Buffer.from(outputFiles[0].text).toString('base64'));
const rows=[{id:'1',name:'Ada',employeeNumber:'E1',businessUnit:'Unit A',department:'Ops',employmentStatus:'Regular',isManager:true,roles:['Manager'],complianceStatus:'Completed'},{id:'2',name:'Ben',employeeNumber:'E2',businessUnit:'Unit B',department:'Ops',employmentStatus:'Seasonal',isManager:false,complianceStatus:'Pending'},{id:'3',name:'Cal',employeeNumber:'E3',businessUnit:'Unit A',department:'Finance',employmentStatus:'Consultant',isManager:true,complianceStatus:'Overdue'},{id:'4',name:'Dan',employmentStatus:'Contractual',businessUnit:'Unit A',complianceStatus:'Pending'}];
const f=(filters)=>filterCompliance(rows,{...emptyComplianceFilters(),...filters}).map(r=>r.id);
assert.deepEqual(f({businessUnit:'Unit A',classification:'regular',level:'manager'}),['1']);
assert.deepEqual(f({classification:'managers'}),['1','3']);
assert.deepEqual(f({classification:'seasonal',businessUnit:'Unit B',status:'Pending'}),['2']);
assert.deepEqual(f({classification:'consultants',department:'Finance'}),['3']);
assert.deepEqual(f({classification:'nonRegular'}),['2','3','4']);
assert.deepEqual(f({level:'role:Manager',search:' e1 '}),['1']);
assert.deepEqual(f({classification:'regular',status:'Pending'}),[]);
const csv=complianceCsv([rows[0]],'=test',{criteria:{preset:'managers'},published_at:'2026-09-09T00:00:00Z'});
assert.ok(csv.includes("'=test"));assert.ok(csv.includes('Regular'));assert.ok(csv.includes('managers'));assert.ok(!csv.includes('Ben'));
console.log('Combined classification, scope filters, search, status and filtered CSV tests passed.');
const filtered=filterCompliance(rows,{...emptyComplianceFilters(),businessUnit:'Unit A'});
assert.deepEqual(complianceSummary(filtered),{total:3,completed:1,pending:1,overdue:1,excluded:0,percentage:33.33});
const sheets=complianceExportSheets({title:'Test report',rows:filtered,publication:{published_at:'2026-09-09'},dueDate:'2026-09-20',results:[{question:'Renew HMO?',answer:'Yes',count:1}]},{...emptyComplianceFilters(),businessUnit:'Unit A'});
assert.deepEqual(Object.keys(sheets),['Compliance Details','Compliance Summary','Survey Results']);
assert.ok(JSON.stringify(sheets).includes('Renew HMO?'));assert.ok(!JSON.stringify(sheets).includes('Ben'));
const {default:ExcelJS}=await import('exceljs');const book=new ExcelJS.Workbook();for(const [name,data] of Object.entries(sheets))book.addWorksheet(name).addRows(data);
const copy=new ExcelJS.Workbook();await copy.xlsx.load(await book.xlsx.writeBuffer());
assert.equal(copy.worksheets.length,3);assert.equal(copy.getWorksheet('Compliance Summary').getCell('B7').value,3);assert.equal(copy.getWorksheet('Survey Results').getCell('A8').value,'Renew HMO?');
console.log('PASS: filtered details, non-overlapping summary totals, results and three-sheet XLSX round-trip.');
