import assert from 'node:assert/strict';
import { build } from 'esbuild';
import Module, { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
const root=fileURLToPath(new URL('../',import.meta.url));
const result=await build({stdin:{contents:`export * from './services/pulseQuestionRules'; export {default as Input} from './components/evaluation/PulseQuestionInput';`,resolveDir:root,loader:'tsx'},bundle:true,platform:'node',format:'cjs',packages:'external',write:false});
const m=new Module(`${root}pulse-test.cjs`);m.filename=`${root}pulse-test.cjs`;m.paths=Module._nodeModulePaths(root);m.require=createRequire(m.filename);m._compile(result.outputFiles[0].text,m.filename);
const {validateAnswer,validateQuestion,formatPulseAnswer,csvCell,Input}=m.exports;
const q={id:'test',text:'Question',type:'yes_no',required:true};
assert.equal(validateAnswer(q,'No'),'');assert.notEqual(validateAnswer(q,['Yes','No']),'');assert.notEqual(validateAnswer(q),'');
assert.equal(validateAnswer({...q,required:false}),'');
const checks={...q,type:'checkboxes',choices:[{id:'a',label:'Alpha'},{id:'b',label:'Beta'}],minSelections:1,maxSelections:2};
assert.equal(validateAnswer(checks,['a','b']),'');assert.notEqual(validateAnswer(checks,['a','a']),'');assert.notEqual(validateAnswer(checks,['x']),'');
assert.notEqual(validateAnswer({...checks,maxSelections:1},['a','b']),'');
assert.equal(validateAnswer({...checks,required:false,minSelections:2},[]),'');
assert.notEqual(validateAnswer({...checks,minSelections:2},['a']),'');
assert.notEqual(validateQuestion({...checks,maxSelections:3}),'');
assert.notEqual(validateQuestion({...checks,choices:[{id:'a',label:'A'},{id:'b',label:'a'}]}),'');
assert.equal(formatPulseAnswer({...checks,choices:[...checks.choices].reverse()},['a','b']),'Alpha; Beta');
const date={...q,type:'date',minDate:'2026-01-01',maxDate:'2026-12-31'};
assert.equal(validateAnswer(date,'2026-09-09'),'');assert.notEqual(validateAnswer(date,'2026-02-30'),'');assert.notEqual(validateAnswer(date,'2027-01-01'),'');
assert.equal(validateAnswer({...date,minDate:undefined,maxDate:undefined},'2028-02-29'),'');
const time={...q,type:'time',timeFormat:'12'};
assert.equal(validateAnswer(time,'00:15'),'');assert.equal(formatPulseAnswer(time,'00:15'),'12:15 AM');assert.equal(formatPulseAnswer(time,'12:15'),'12:15 PM');assert.notEqual(validateAnswer(time,'24:00'),'');
assert.equal(validateAnswer({...q,type:'rating'},5),'');assert.notEqual(validateAnswer({...q,type:'rating'},6),'');assert.notEqual(validateAnswer({...q,type:'rating'},2.5),'');
assert.equal(csvCell('A,"B"'),'"A,""B"""');assert.equal(csvCell('=1+1'),'"\'=1+1"');
const render=(question,value)=>renderToStaticMarkup(React.createElement(Input,{question,value,onChange:()=>{}}));
assert.match(render(q,'No'),/type="radio"/);assert.match(render(checks,['a']),/type="checkbox"/);assert.match(render(date,'2026-09-09'),/type="date"/);assert.match(render(time,'00:15'),/AM or PM/);assert.doesNotMatch(render({...time,timeFormat:'24'},'00:15'),/AM or PM/);
console.log('Pulse response validation, input rendering, choice labels and CSV tests passed.');
