-- Append to migration inside BEGIN ... ROLLBACK; never persist fixtures.
do $$declare hr uuid;hauth uuid;emp uuid:=gen_random_uuid();eauth uuid:=gen_random_uuid();bu uuid;site uuid;dev uuid:=gen_random_uuid();tpl uuid:=gen_random_uuid();
 d date:=(now() at time zone 'Asia/Manila')::date;wk date;tok text;a jsonb;r jsonb;k uuid:=gen_random_uuid();offline uuid:=gen_random_uuid();code text:='PS'||substr(emp::text,1,8);denied boolean;photo text:='/9j/AA==';begin
 select h.id,h.auth_user_id into strict hr,hauth from public.hris_users h join public.user_roles ur on ur.user_id=h.id where ur.role_id='Admin' and ur.is_active and lower(h.status)='active' and h.auth_user_id is not null limit 1;
 select s.id,s.business_unit_id into strict site,bu from public.sites s where s.business_unit_id is not null limit 1;
 insert into auth.users(id,email) values(eauth,'punch-'||eauth||'@example.invalid');
 insert into public.hris_users(id,auth_user_id,employee_id,email,first_name,last_name,full_name,status,role,business_unit_id,date_hired,reports_to) values(emp,eauth,code,'punch-'||emp||'@example.invalid','Rollback','Punch','Rollback Punch','Active','Employee',bu,d-60,hr::text);
 insert into public.user_roles(user_id,role_id,is_active) values(emp,'Employee',true);
 insert into public.attendance_devices(id,business_unit_id,site_id,name,kind,created_by) values(dev,bu,site,'Rollback Punch Station','qr',hr);
 insert into public.shift_templates(id,name,start_time,end_time,break_minutes,grace_period_minutes,business_unit_id,color,schedule_kind,end_day_offset,created_by) values(tpl,'Rollback work','09:00','18:00',60,5,bu,'blue','work',0,hr);
 insert into public.shift_assignments(employee_id,shift_template_id,date,business_unit_id,created_by) values(emp,tpl,d,bu,hr);
 wk:=date_trunc('week',d)::date;
 insert into public.payroll_schedule_publications(employee_id,business_unit_id,effective_from,effective_to,version,source_hash,snapshot,approval_required,published_by,reference) values(emp,bu,wk,wk+6,1,md5(private.payroll_schedule_draft(emp,wk)::text),private.payroll_schedule_draft(emp,wk),false,hr,'Rollback published schedule');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',hauth,'role','authenticated')::text,true);set local role authenticated;
 tok:=public.punch_station_pair(dev);
 perform public.punch_station_credential(emp,'AABBCCDD','5729',null,true,'Rollback credential');reset role;
 perform set_config('request.jwt.claims','{"role":"anon"}',true);set local role anon;
 if not(public.punch_station_status('invalid')?'error') then raise exception 'Unpaired device accepted';end if;
 if not(public.punch_station_auth(tok,null,code,'0000',false)?'error') then raise exception 'Invalid PIN accepted';end if;
 a:=public.punch_station_auth(tok,null,code,'5729',false);
 if a->>'state'<>'not_started' then raise exception 'Valid PIN did not resolve attendance: %',a;end if;
 denied:=false;begin perform public.punch_station_submit(tok,k,a->>'ticket','CLOCK_IN','',now(),null);exception when others then denied:=true;end;
 if not denied then raise exception 'Missing photo accepted';end if;
 r:=public.punch_station_submit(tok,k,a->>'ticket','CLOCK_IN',photo,now(),null);
 if r->>'status'<>'Accepted' then raise exception 'Valid punch failed: %',r;end if;
 perform public.punch_station_submit(tok,k,a->>'ticket','CLOCK_IN',photo,now(),null);reset role;
 if (select count(*) from punch_station.captures where id=k)<>1 or (select count(*) from public.attendance_clock_events where employee_id=emp)<>1 then raise exception 'Duplicate or missing attendance/photo';end if;
 set local role anon;
 if not(public.punch_station_auth(tok,null,code,'5729',true)?'error') then raise exception 'Employee PIN opened supervisor';end if;
 a:=public.punch_station_auth(tok,'AABBCCDD',null,null,false);
 if a->>'state'<>'working' then raise exception 'Badge failed';end if;
 r:=public.punch_station_submit(tok,offline,null,'START_BREAK',photo,clock_timestamp(),'AABBCCDD');
 if r->>'status'<>'Pending HR verification' then raise exception 'Offline capture not pending';end if;
 denied:=false;begin perform public.punch_station_photo(k);exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Public photo access';end if;reset role;
 if (select count(*) from public.attendance_clock_events where employee_id=emp)<>1 then raise exception 'Offline capture counted as actual';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',hauth,'role','authenticated')::text,true);set local role authenticated;
 perform public.punch_station_photo(k);
 perform public.punch_station_review(offline,true,d,'Photo and actual shift time verified');
 perform public.punch_station_review(offline,true,d,'Safe review retry');reset role;
 if (select count(*) from public.attendance_clock_events where employee_id=emp)<>2 then raise exception 'Offline review did not reconcile';end if;
 update public.attendance_devices set active=false where id=dev;
 if punch_station.device(tok) is not null then raise exception 'Revoked device usable';end if;
end $$;
select 'PASS: public capability, PIN/badge authentication, camera evidence requirement, atomic attendance/photo, idempotency, supervisor denial, private photo access, offline staging and audited review, device revocation. Fixtures rolled back.' result;
