// Actual readiness component, synthetic data, no production API calls.
import {build} from 'esbuild';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const pw=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const {chromium}=pw.default||pw;
const dir='/tmp/readiness-buttons-ui';fs.mkdirSync(dir,{recursive:true});
const day={employeeId:'employee-a',employeeName:'Sample Employee',date:'2026-09-01',restDay:false,holiday:false,approvedFullLeave:false,scheduledMinutes:480,actualMinutes:540,regularMinutes:480,breakMinutes:60,lateMinutes:0,undertimeMinutes:0,approvedOtMinutes:0,actualOtMinutes:60,workedLunch:false,issues:['Worked and scheduled minutes need reconciliation','Approved time rules missing','Missing punch'],ready:false,shiftIds:['shift-original'],eventIds:['punch-original'],leaveIds:[],ot:[],segments:[]};
await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{MemoryRouter,Routes,Route,useLocation}from'react-router-dom';import{TimekeepingEmployeeTable}from'./modules/payroll/TimekeepingEmployeeTable';function Target(){const l=useLocation();return <p data-testid="destination">{l.pathname+l.search+l.hash}</p>}createRoot(document.getElementById('root')).render(<MemoryRouter><Routes><Route path="/" element={<TimekeepingEmployeeTable rows={${JSON.stringify([day,{...day,date:'2026-09-02'}])}} test={[]} saved={false} canOpenOffset={false} busy={false} hasReason={false} onOpenOffset={()=>{}} scopeName="Sample BU" from="2026-08-26" to="2026-09-10"/>}/><Route path="*" element={<Target/>}/></Routes></MemoryRouter>);`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,outfile:dir+'/app.js',plugins:[{name:'no-production',setup(b){b.onResolve({filter:/historicalAttendance$/},()=>({path:'history',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const downloadHistoricalSource=()=>{};export const historyDetail=async()=>({});',loader:'js'}));}}]});
fs.writeFileSync(dir+'/index.html','<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div><script src="app.js"></script>');
const browser=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE,headless:true,args:['--no-sandbox']});
const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function open(){await page.goto('file://'+dir+'/index.html');await page.getByRole('button',{name:/Sample Employee/}).click();}
await open();await page.getByRole('button',{name:'Review all issues',exact:true}).click();
const dialog=page.getByRole('dialog');await dialog.waitFor();assert.match(await dialog.innerText(),/Sample BU · 2026-08-26 – 2026-09-10/);assert.match(await dialog.innerText(),/2 affected dates/);assert.equal(await dialog.getByRole('combobox').inputValue(),'');
await page.keyboard.press('Escape');assert.equal(await dialog.count(),0);
await page.getByRole('button',{name:'Fix next',exact:true}).click();await dialog.waitFor();assert.equal(await dialog.getByRole('combobox').inputValue(),'Worked and scheduled minutes need reconciliation');
await dialog.getByRole('link',{name:'Review scheduled and worked time'}).first().click();assert.equal(await page.getByTestId('destination').innerText(),'/payroll/daily-review?employee=employee-a&date=2026-09-01');
await open();await page.getByRole('button',{name:/● Missing punch/}).click();await dialog.waitFor();assert.equal(await dialog.getByRole('combobox').inputValue(),'Missing punch');await dialog.getByRole('link',{name:'Review actual-time evidence'}).first().click();assert.equal(await page.getByTestId('destination').innerText(),'/payroll/historical-corrections?employee=employee-a&date=2026-09-01');
await open();await page.getByRole('button',{name:'Review all issues',exact:true}).click();await dialog.getByRole('combobox').selectOption('Attendance policy — Needs setup');await dialog.getByRole('link',{name:/Open attendance settings/}).click();assert.equal(await page.getByTestId('destination').innerText(),'/payroll/attendance-readiness#attendance-references');
await open();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Fix next',exact:true}).click();assert.equal(await dialog.isVisible(),true);await dialog.getByRole('button',{name:'Close review'}).click();assert.equal(await dialog.count(),0);assert.deepEqual(errors,[]);
await browser.close();console.log('PASS: review all, focused fix next, grouped issue click, employee/date routing, setup hash, keyboard close and mobile close; no runtime errors or API mutations.');
