import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const source = async relativePath => readFile(path.join(root, relativePath), 'utf8');

const app = await source('App.tsx');
const publicCareers = await source('services/publicCareersService.ts');
const openRoles = await source('components/recruitment/OpenRolesPage.tsx');
const rolePage = await source('components/recruitment/CareerRolePage.tsx');
const applicationPage = await source('components/recruitment/CareerApplicationPage.tsx');
const fileUploader = await source('components/ui/FileUploader.tsx');
const roleTypes = await source('types.ts');
const migration = await source('supabase/migrations/20260822030000_recruitment_application_flow.sql');
const resumeMigration = await source('supabase/migrations/20260822040000_recruitment_resume_link.sql');

assert.match(app, /path="\/careers\/:slug\/apply\/:roleSlug"/);
assert.match(app, /path="\/careers\/:slug\/apply"/);
assert.match(publicCareers, /getApplicationPath/);
assert.match(publicCareers, /roleId=/);
assert.match(publicCareers, /isJobCurrentlyOpen/);
assert.match(openRoles, /Submit General Application/);
assert.match(rolePage, /This role is no longer accepting applications/);
assert.match(applicationPage, /Application Details/);
assert.match(applicationPage, /Role Questions/);
assert.doesNotMatch(applicationPage, /No additional experience questions are configured/);
assert.match(applicationPage, /recruitment-uploads/);
assert.match(applicationPage, /MAX_RESUME_SIZE = 1024 \* 1024 - 1/);
assert.match(applicationPage, /Takes about/);
assert.match(applicationPage, /Your resume file must be less than 1 MB\./);
assert.match(applicationPage, /Please provide either a resume link or upload your resume\./);
assert.match(applicationPage, /Provide either a resume link or upload a file under 1 MB\./);
assert.match(applicationPage, /collectCurrentCity/);
assert.match(applicationPage, /collectLinkedIn/);
assert.match(applicationPage, /collectCurrentEmployer/);
assert.match(applicationPage, /collectEarliestStartDate/);
assert.match(applicationPage, /role_id: liveJob\?\.id \|\| null/);
assert.match(applicationPage, /resume_link: resumeLinkValue/);
assert.match(applicationPage, /submission_token: submissionToken/);
assert.match(applicationPage, /This role is no longer accepting applications/);
assert.match(applicationPage, /Submit Application/);
assert.match(fileUploader, /maxSizeErrorMessage/);
assert.match(roleTypes, /collectCurrentCity\?: boolean/);
assert.match(roleTypes, /collectLinkedIn\?: boolean/);
assert.match(migration, /add column if not exists role_id text/);
assert.match(migration, /add column if not exists role_answers jsonb/);
assert.match(migration, /add column if not exists submission_token text/);
assert.match(migration, /alter column job_post_id drop not null/);
assert.match(migration, /Public applicants can upload resumes/);
assert.match(resumeMigration, /add column if not exists resume_link text/);

console.log('Recruitment flow smoke test passed.');
