-- Transaction-only fixtures. All flags, IRs, notifications, profiles and schedules are rolled back.
begin;set local lock_timeout='2s';set local statement_timeout='40s';
do $$declare hr uuid;hauth uuid;emp uuid:=gen_random_uuid();eauth uuid:=gen_random_uuid();bu uuid:=gen_random_uuid();tpl uuid:=gen_random_uuid();d date:=(now() at time zone 'Asia/Manila')::date-1;wk date;pub uuid;facts jsonb;sid uuid;pol uuid;paid uuid;unpaid uuid;lid uuid;denied boolean;cnt integer;begin
 select h.id,h.auth_user_id into strict hr,hauth from public.hris_users h join public.user_roles ur on ur.user_id=h.id where ur.role_id='Admin' and ur.is_active and lower(h.status)='active' and h.auth_user_id is not null limit 1;
 insert into public.business_units(id,name) values(bu,'Rollback attendance fixtures');
 insert into auth.users(id,email) values(eauth,'attendance-'||eauth||'@example.invalid');
 insert into public.hris_users(id,auth_user_id,email,first_name,last_name,full_name,status,role,business_unit_id,date_hired,reports_to) values(emp,eauth,'attendance-'||emp||'@example.invalid','Rollback','Employee','Rollback Employee','Active','Employee',bu,d-60,hr::text);
 insert into public.user_roles(user_id,role_id,is_active) values(emp,'Employee',true);
 insert into storage.objects(bucket_id,name) values('employee-profile-photos',emp::text||'/rollback.png'),('employee-profile-photos',hr::text||'/rollback-'||emp||'.png');
 insert into public.employee_profile_photos(employee_id,storage_path,created_by) values(emp,emp::text||'/rollback.png',hr),(hr,hr::text||'/rollback-'||emp||'.png',hr);
 insert into public.shift_templates(id,name,start_time,end_time,break_minutes,grace_period_minutes,business_unit_id,color,schedule_kind,end_day_offset,created_by) values(tpl,'Rollback work','09:00','18:00',60,5,bu,'blue','work',0,hr);
 insert into public.shift_assignments(employee_id,shift_template_id,date,business_unit_id,created_by) values(emp,tpl,d,bu,hr);
 wk:=date_trunc('week',d)::date;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',hauth,'role','authenticated')::text,true);set local role authenticated;
 perform public.set_schedule_day_status(emp,d,'skeletal','Rollback skeletal');
 reset role;
 if private.payroll_schedule_draft(emp,wk)->0->>'statusTag'<>'skeletal' then raise exception 'Skeletal tag missing';end if;
 set local role authenticated;perform public.set_schedule_day_status(emp,d,'rest','Rollback rest');reset role;
 if private.payroll_schedule_draft(emp,wk)->0->>'kind'<>'rest' then raise exception 'Rest status not in publication source';end if;
 if not exists(select 1 from public.shift_assignments where employee_id=emp and date=d) then raise exception 'Original shift erased';end if;
 set local role authenticated;perform public.set_schedule_day_status(emp,d,null,'Restore working shift');reset role;
 insert into public.payroll_schedule_publications(employee_id,business_unit_id,effective_from,effective_to,version,source_hash,snapshot,approval_required,published_by,reference) values(emp,bu,wk,wk+6,1,md5(private.payroll_schedule_draft(emp,wk)::text),private.payroll_schedule_draft(emp,wk),false,hr,'Rollback published schedule') returning id into pub;
 facts:=private.attendance_review_facts(emp,d);if not(facts->>'eligible')::boolean or (facts->>'hasPunch')::boolean then raise exception 'Published no-punch day not eligible';end if;
 insert into public.attendance_review_policies(business_unit_id,revision,enabled,effective_from,late_minutes,late_count,window_days,auto_ir,created_by) values(bu,1,true,d,15,3,30,true,hr) returning id into pol;
 cnt:=private.scan_attendance_review();
 if not exists(select 1 from public.attendance_review_flags f join public.incident_reports i on i.id=f.incident_id where f.employee_id=emp and f.kind='absence' and i.status='Submitted' and i.pipeline_stage='ir-review') then raise exception 'Absence IR did not enter review';end if;
 perform private.scan_attendance_review();if(select count(*) from public.attendance_review_flags where employee_id=emp and kind='absence')<>1 then raise exception 'Repeated scan duplicated flag';end if;
 insert into public.attendance_clock_sessions(employee_id,work_date,publication_id,schedule_snapshot,state,revision) values(emp,d,pub,private.attendance_schedule(emp,d),'completed',2) returning id into sid;
 insert into public.attendance_clock_events(session_id,employee_id,action,occurred_at,request_id,revision,created_by) values(sid,emp,'CLOCK_IN',(d+'09:21'::time) at time zone 'Asia/Manila',gen_random_uuid(),1,emp),(sid,emp,'CLOCK_OUT',(d+'18:00'::time) at time zone 'Asia/Manila',gen_random_uuid(),2,emp);
 facts:=private.attendance_review_facts(emp,d);if (facts->>'lateMinutes')::integer<>16 then raise exception 'Company grace changed';end if;
 perform private.scan_attendance_review();if not exists(select 1 from public.attendance_review_flags where employee_id=emp and kind='tardiness') then raise exception 'Tardiness threshold did not flag';end if;
 -- Verify unpaid/paid decisions through the same stored leave type source.
 insert into public.leave_types(id,name,paid,unit,min_increment) values(gen_random_uuid(),'Rollback paid',true,'day',1) returning id into paid;
 insert into public.leave_types(id,name,paid,unit,min_increment) values(gen_random_uuid(),'Rollback unpaid',false,'day',1) returning id into unpaid;
 insert into public.leave_requests(employee_id,employee_name,leave_type_id,start_date,end_date,duration_days,status,business_unit_id,reason) values(emp,'Rollback Employee',paid,d,d,1,'Approved',bu,'Rollback leave') returning id into lid;
 update public.leave_requests set status='Approved',approver_configuration_required=false where id=lid;
 if private.attendance_schedule(emp,d)->'entries'->0->>'name'<>'Paid Leave' then raise exception 'Approved paid leave not reflected';end if;
 update public.leave_requests set leave_type_id=unpaid where id=lid;
 if private.attendance_schedule(emp,d)->'entries'->0->>'name'<>'Unpaid Leave' then raise exception 'Approved unpaid leave not reflected';end if;
 if (private.attendance_review_facts(emp,d)->>'eligible')::boolean then raise exception 'Approved leave triggered discipline';end if;
 -- An approved decision cannot simply be rejected again; test a separate rejected request.
 insert into public.shift_assignments(employee_id,shift_template_id,date,business_unit_id,created_by) values(emp,tpl,d-1,bu,hr);
 insert into public.leave_requests(employee_id,employee_name,leave_type_id,start_date,end_date,duration_days,status,business_unit_id,reason) values(emp,'Rollback Employee',unpaid,d-1,d-1,1,'Rejected',bu,'Rollback rejected request');
 insert into public.payroll_schedule_publications(employee_id,business_unit_id,effective_from,effective_to,version,source_hash,snapshot,approval_required,published_by,reference) values(emp,bu,wk,wk+6,2,md5(private.payroll_schedule_draft(emp,wk)::text),private.payroll_schedule_draft(emp,wk),false,hr,'Rollback second publication');
 if private.attendance_schedule(emp,d-1)->'entries'->0->>'kind'<>'work' then raise exception 'Rejected leave removed original shift';end if;
 set local role authenticated;
 perform public.copy_schedule_week_with_statuses(array[emp],wk+7);
 reset role;
 if not exists(select 1 from public.shift_assignments where employee_id=emp and date=d+7) then raise exception 'Copy week lost expected shifts';end if;
 if exists(select 1 from public.leave_requests where employee_id=emp and start_date=d+7) then raise exception 'Leave incorrectly copied';end if;
 set local role authenticated;perform public.get_live_shift_status(array[emp]);reset role;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',eauth,'role','authenticated')::text,true);set local role authenticated;
 if not exists(select 1 from public.employee_profile_photos where employee_id=emp) then raise exception 'Own profile photo missing';end if;
 if exists(select 1 from public.employee_profile_photos where employee_id=hr) then raise exception 'Employee read another profile photo outside scope';end if;
 denied:=false;begin perform public.set_schedule_day_status(emp,d,'rest','Unauthorized self schedule');exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Employee changed schedule';end if;
 denied:=false;begin perform public.save_attendance_review_policy(bu,true,d+1,15,3,30,true);exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Employee enabled discipline automation';end if;
 reset role;set local role anon;
 denied:=false;begin perform public.get_attendance_review();exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Anonymous attendance review';end if;
 reset role;
end $$;
select 'PASS: status source and original shift retention, published absence -> IR review, duplicate scans, grace/tardiness, paid/unpaid/rejected leave, employee and anonymous denial. All fixtures rolled back.' as result;
rollback;
