import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { BusinessUnit, OfferTemplate, Permission } from '../../types';
import { usePermissions } from '../../hooks/usePermissions';
import { useAuth } from '../../hooks/useAuth';
import { supabase } from '../../services/supabaseClient';
import Button from '../../components/ui/Button';
import OfferTemplateCard from '../../components/recruitment/OfferTemplateCard';
import OfferTemplateEditor from '../../components/recruitment/OfferTemplateEditor';
import { cloneOfferTemplate, OFFER_TEMPLATE_PRESETS } from '../../components/recruitment/offerTemplatePresets';

export const mapOfferTemplate = (row: any): OfferTemplate => ({ id: row.id, name: row.name, businessUnitId: row.business_unit_id || undefined, businessUnit: row.business_unit || '', description: row.description || '', category: row.category || 'General', status: row.status || 'Draft', templateKey: row.template_key || undefined, isStarter: row.is_starter === true, templateData: row.template_data || {}, logoUrl: row.logo_url || undefined, logoPath: row.logo_path || undefined, headerImageUrl: row.header_image_url || undefined, headerImagePath: row.header_image_path || undefined, createdByUserId: row.created_by_user_id || undefined, createdAt: row.created_at ? new Date(row.created_at) : new Date(), updatedAt: row.updated_at ? new Date(row.updated_at) : new Date(), archivedAt: row.archived_at ? new Date(row.archived_at) : undefined, persisted: true });
export const offerTemplatePayload = (template: OfferTemplate, userId?: string) => ({ name: template.name.trim(), business_unit_id: template.businessUnitId || null, business_unit: template.businessUnit, description: template.description || '', category: template.category || 'General', status: template.status, template_key: template.templateKey || null, is_starter: template.isStarter === true, template_data: template.templateData, logo_url: template.logoUrl || null, logo_path: template.logoPath || null, header_image_url: template.headerImageUrl || null, header_image_path: template.headerImagePath || null, created_by_user_id: template.createdByUserId || userId || null, archived_at: template.status === 'Archived' ? new Date().toISOString() : null });

const OfferTemplates: React.FC = () => {
  const { can } = usePermissions(); const { user } = useAuth(); const navigate = useNavigate(); const canManage = can('Offers', Permission.Manage); const canView = can('Offers', Permission.View) || canManage;
  const [templates, setTemplates] = useState<OfferTemplate[]>([]); const [businessUnits, setBusinessUnits] = useState<BusinessUnit[]>([]); const [loading, setLoading] = useState(true); const [editorOpen, setEditorOpen] = useState(false); const [selected, setSelected] = useState<OfferTemplate | null>(null); const [search, setSearch] = useState(''); const [businessUnit, setBusinessUnit] = useState('All'); const [status, setStatus] = useState('Current'); const [message, setMessage] = useState('');
  const load = useCallback(async () => { if (!canView) return; setLoading(true); try { const [templateResult, buResult] = await Promise.all([supabase.from('job_offer_templates').select('*').order('updated_at', { ascending: false }), supabase.from('business_units').select('id,name').order('name')]); if (templateResult.error) throw templateResult.error; setBusinessUnits((buResult.data || []).map((item:any)=>({ id:item.id,name:item.name } as BusinessUnit))); const loaded = (templateResult.data || []).map(mapOfferTemplate); const keys = new Set(loaded.map(item=>item.templateKey)); const missing = OFFER_TEMPLATE_PRESETS.filter(item=>!keys.has(item.templateKey)); if (canManage && missing.length) { const seeded = await supabase.from('job_offer_templates').insert(missing.map(item=>offerTemplatePayload(item,user?.id))).select('*'); if (!seeded.error) loaded.push(...(seeded.data || []).map(mapOfferTemplate)); } setTemplates(loaded.length ? loaded : OFFER_TEMPLATE_PRESETS.map(cloneOfferTemplate)); } catch (reason:any) { setMessage(reason.message || 'Unable to load templates.'); setTemplates(OFFER_TEMPLATE_PRESETS.map(cloneOfferTemplate)); } finally { setLoading(false); } }, [canManage,canView,user?.id]);
  useEffect(()=>{ void load(); },[load]);
  const filtered = useMemo(()=>templates.filter(item => (status === 'All' || (status === 'Current' ? item.status !== 'Archived' : item.status === status)) && (businessUnit === 'All' || item.businessUnit === businessUnit) && `${item.name} ${item.businessUnit} ${item.category}`.toLowerCase().includes(search.toLowerCase())),[templates,status,businessUnit,search]);
  const save = async (template: OfferTemplate) => { if (!template.name.trim() || !template.businessUnit) throw new Error('Template name and Business Unit are required.'); const payload = offerTemplatePayload(template,user?.id); const result = template.persisted && template.id ? await supabase.from('job_offer_templates').update(payload).eq('id',template.id).select('*').single() : await supabase.from('job_offer_templates').insert(payload).select('*').single(); if (result.error) throw result.error; const mapped=mapOfferTemplate(result.data); setTemplates(previous => template.persisted ? previous.map(item=>item.id===mapped.id?mapped:item) : [mapped,...previous]); setEditorOpen(false); setMessage('Offer template saved.'); };
  const duplicate = async (template: OfferTemplate) => { const copy={...cloneOfferTemplate(template),id:'',name:`${template.name} Copy`,status:'Draft' as const,templateKey:undefined,isStarter:false,persisted:false,createdAt:new Date(),updatedAt:new Date()}; await save(copy); };
  const archive = async (template: OfferTemplate) => { if (!window.confirm(`Archive “${template.name}”? Existing offers will keep their saved snapshot.`)) return; const result=await supabase.from('job_offer_templates').update({status:'Archived',archived_at:new Date().toISOString()}).eq('id',template.id).select('*').single(); if(result.error){setMessage(result.error.message);return;} setTemplates(previous=>previous.map(item=>item.id===template.id?mapOfferTemplate(result.data):item)); };
  if (!canView) return <div className="rounded-2xl bg-white p-8">You do not have permission to view offer templates.</div>;
  return <div className="space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold text-violet-600">Recruitment / Offers</p><h1 className="text-3xl font-black">Offer Templates</h1><p className="mt-1 text-sm text-slate-500">Reusable, business-unit-branded starting points. Existing offers retain their original snapshot.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>navigate('/recruitment/offers')}>Job Offers</Button>{canManage&&<Button onClick={()=>{setSelected(null);setEditorOpen(true);}}>Create Offer Template</Button>}</div></header>{message&&<div className="rounded-xl border border-violet-200 bg-violet-50 p-3 text-sm text-violet-800">{message}</div>}<section className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3 dark:bg-slate-900"><input className="rounded-xl border px-4 py-2.5 dark:bg-slate-800" placeholder="Search templates" value={search} onChange={event=>setSearch(event.target.value)}/><select className="rounded-xl border px-4 py-2.5 dark:bg-slate-800" value={businessUnit} onChange={event=>setBusinessUnit(event.target.value)}><option>All</option>{[...new Set(templates.map(item=>item.businessUnit))].sort().map(item=><option key={item}>{item}</option>)}</select><select className="rounded-xl border px-4 py-2.5 dark:bg-slate-800" value={status} onChange={event=>setStatus(event.target.value)}><option>Current</option><option>Active</option><option>Draft</option><option>Archived</option><option>All</option></select></section>{loading?<p className="py-16 text-center text-slate-500">Loading offer templates…</p>:<div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{filtered.map(template=><OfferTemplateCard key={template.id} template={template} canManage={canManage} onEdit={()=>{setSelected(template);setEditorOpen(true);}} onUse={()=>navigate(`/recruitment/offers?template=${template.id}`)} onDuplicate={()=>void duplicate(template)} onArchive={()=>void archive(template)}/>)}</div>}<OfferTemplateEditor open={editorOpen} template={selected} businessUnits={businessUnits} onClose={()=>setEditorOpen(false)} onSave={save}/></div>;
};

export default OfferTemplates;

