import React,{useCallback,useEffect,useRef,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {reviewBenefitRequest} from '../../services/benefitApprovalService';
import FamilyVisitOperationsSettings from './FamilyVisitOperationsSettings';
import {saveFamilyVisitDraft} from '../../services/familyVisitService';
import {FamilyMember,FamilyVisit,FamilyVisitData,consumesVisit,reservesVisit,familyVisitYear,loadFamilyVisits,loadFamilyVisitDetail,submitFamilyVisit,familyVisitAction,downloadFamilyVisitPass,visitStatus,manilaTime} from '../../services/familyVisitService';

const input='w-full rounded-lg border border-slate-300 bg-white p-2 text-slate-900 dark:border-slate-600 dark:bg-slate-900 dark:text-white';
const button='rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white hover:bg-violet-700 disabled:opacity-50 disabled:cursor-not-allowed';
const secondary='rounded-lg border border-slate-300 px-3 py-2 text-sm dark:border-slate-600 hover:bg-slate-100 dark:hover:bg-slate-700';
const box='rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-800';
const message=(e:unknown)=>e instanceof Error?e.message:String((e as {message?:string})?.message||'Unable to complete this action. Please retry.');

export default function FamilyVisitPanel({mode='mine'}:{mode?:'mine'|'all'}) {
 const location=useLocation(),navigate=useNavigate();
 const [year,setYear]=useState(familyVisitYear()),[data,setData]=useState<FamilyVisitData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [form,setForm]=useState(false),[destination,setDestination]=useState(''),[date,setDate]=useState(''),[family,setFamily]=useState<FamilyMember[]>([]),[entry,setEntry]=useState(false),[confirmed,setConfirmed]=useState(false);
 const [detail,setDetail]=useState<any>(null),[note,setNote]=useState(''),[value,setValue]=useState('');
 const lock=useRef(false),generation=useRef(0),draftLoaded=useRef(false);
 const selectedId=new URLSearchParams(location.search).get('requestId');
 const refresh=useCallback(async()=>{const g=++generation.current;const result=await loadFamilyVisits(year);if(g===generation.current)setData(result);},[year]);
 useEffect(()=>{refresh().catch(e=>setError(message(e)));return()=>{generation.current++;};},[refresh]);
 useEffect(()=>{if(data&&!draftLoaded.current){draftLoaded.current=true;if(data.draft){setDestination(data.draft.destination||'');setDate(data.draft.date||'');setFamily(Array.isArray(data.draft.family)?data.draft.family:[]);setEntry(data.draft.entry===true);setConfirmed(data.draft.confirmed===true);}}},[data]);
 useEffect(()=>{let live=true;setDetail(null);setNote('');setValue('');if(selectedId)loadFamilyVisitDetail(selectedId).then(d=>{if(live){setDetail(d);setYear(Number(d.request.date_needed.slice(0,4)));}}).catch(e=>{if(live)setError(message(e));});return()=>{live=false;};},[selectedId]);
 useEffect(()=>{if(!form)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[form]);
 const run=async(fn:()=>Promise<unknown>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();await refresh();if(selectedId)setDetail(await loadFamilyVisitDetail(selectedId));}catch(e){setError(message(e));}finally{lock.current=false;setBusy(false);}};
 const open=(id:string)=>navigate(`?tab=family_visits&requestId=${id}`);
 const action=(name:string)=>run(()=>familyVisitAction(selectedId!,name,note,value));
 if(!data)return <section className={box} role="status">{error||'Loading Family Visit Privilege…'}{error&&<button className={secondary} onClick={()=>run(refresh)}>Retry</button>}</section>;
 const mine=data.requests.filter(r=>r.employee_id===data.employee.id),reserved=mine.filter(reservesVisit),used=mine.filter(consumesVisit).length,pending=mine.filter(r=>r.status.startsWith('Pending')).length;
 const unknown=reserved.some(r=>!r.family_visit.destination_id);
 const available=data.employee.eligible&&reserved.length<4&&!unknown&&year===familyVisitYear();
 const current=detail?.request as FamilyVisit|undefined;
 const selected=current&&(data.requests.find(r=>r.id===current.id)||current);
 const history=current?data.requests.filter(r=>r.employee_id===current.employee_id):[];
 const close=()=>navigate('?tab=family_visits');
 const rows=mode==='mine'?mine:data.requests;
 return <section id="family-visits" className="space-y-5 text-slate-900 dark:text-slate-100">
  <div className={box}>
   <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-bold">{year} Family Visit Privilege</h2><label className="text-sm">Calendar year <input className={input} type="number" min="2000" max={familyVisitYear()} value={year} onChange={e=>{const v=Number(e.target.value);if(v>=2000&&v<=familyVisitYear())setYear(v);}} /></label></div>
   <p className="mt-2">Four BU visits per calendar year · Four different destinations · Entry only</p>
   {mode==='mine'&&<p className="mt-3 font-semibold">Used: {used} of 4 | Remaining: {Math.max(0,4-used)} of 4{pending>0&&` | ${pending} pending (reserved)`}</p>}
   {!data.employee.eligible&&mode==='mine'&&<p className="mt-3 text-amber-700 dark:text-amber-300">Not Eligible – Employee Is Not Regular</p>}
   {unknown&&mode==='mine'&&<p className="mt-3 text-amber-700 dark:text-amber-300">Action required: a historical destination is not recorded. That visit remains counted; contact HR to correct its destination before requesting another visit.</p>}
   {used>=4&&mode==='mine'&&<p className="mt-3 font-bold">4 of 4 Family Visit Privileges Used</p>}
   <details className="mt-4 text-sm"><summary className="cursor-pointer font-semibold">Coverage and policy</summary><p className="mt-2">Each approved visit provides free entry for the employee and up to four immediate family members, maximum five total guests. Food, games, activities, souvenirs, transportation and other charges are excluded unless separately stated in an approved company policy. Unused guest slots cannot be combined, transferred, carried over or converted to cash. Unused BU visits expire at year end. Rejected and withdrawn requests do not consume entitlement. Approved cancellations restore entitlement only after HR review.</p></details>
  </div>
  {data.hr&&mode==='all'&&<FamilyVisitOperationsSettings destinations={data.destinations}/>}
  {error&&<div className="rounded-lg border border-red-400 p-4 text-red-700 dark:text-red-300" role="alert">{error}{/acknowledg/i.test(error)&&<a className="ml-2 underline" href="/acknowledgments">Review Pending Documents</a>}</div>}
  {mode==='mine'&&<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:4},(_,i)=>{const r=reserved[i];const dest=data.destinations.find(d=>d.id===r?.family_visit.destination_id);return <article key={i} className={box} style={{borderTopWidth:4,borderTopColor:dest?.color||'#7c3aed'}}>
   <p className="text-sm font-semibold text-violet-700 dark:text-violet-300">Visit {i+1} of 4</p><h3 className="mt-3 text-lg font-bold">{r?r.family_visit.destination_name||'Destination BU Not Recorded':'Choose a Business Unit'}</h3>
   <p className="my-3 text-sm">{r?visitStatus(r):'Available'}</p>
   {r?<><p>{r.date_needed} · {r.family_visit.family?`${1+r.family_visit.family.length} guests`:'Guests not recorded'}</p><p className="my-2 break-all text-xs">{r.family_visit.reference||r.id}</p><div className="flex flex-wrap gap-2"><button className={button} onClick={()=>open(r.id)}>View Details</button>{['Approved','Fulfilled'].includes(r.status)&&<button disabled={busy} className={secondary} onClick={()=>run(()=>downloadFamilyVisitPass(r.id))}>Download PDF</button>}</div></>:<><p className="mb-4 text-sm text-slate-600 dark:text-slate-300">Employee + up to four immediate family members</p><button disabled={!available||busy} className={button} onClick={()=>setForm(true)}>Request Visit</button></>}
  </article>;})}</div>}
  {mode==='mine'&&data.draft&&!form&&<div className={box}><strong>Draft visit saved</strong><button className={secondary+' ml-3'} onClick={()=>setForm(true)}>Resume Draft</button></div>}
  {form&&<form className={box+' space-y-4'} onSubmit={e=>{e.preventDefault();run(async()=>{const id=await submitFamilyVisit(destination,date,family,entry,confirmed);setForm(false);setFamily([]);setDestination('');setDate('');setEntry(false);setConfirmed(false);open(id);});}}>
   <h3 className="text-xl font-bold">Request a Family Visit</h3><p>{data.employee.name} · {data.employee.number||'Employee ID not recorded'} · Home BU: {data.employee.home_bu} · {data.employee.employment_status}</p>
   <div className="grid gap-4 sm:grid-cols-2"><label>Destination BU / branch<select required className={input} value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Choose a Business Unit</option>{data.destinations.map(d=>{const conflict=reserved.some(r=>r.family_visit.brand===d.brand);return <option key={d.id} value={d.id} disabled={conflict}>{d.name}{conflict?' — Already used or pending':''}</option>;})}</select></label><label>Intended visit date<input required type="date" min={new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())} max={`${year}-12-31`} className={input} value={date} onChange={e=>setDate(e.target.value)} /></label></div>
   <p className="font-semibold">Accompanying family members: {family.length} of 4 · Total visitors: {family.length+1} of 5</p>
   {family.map((f,i)=><div key={i} className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><label>Full name<input required maxLength={160} className={input} value={f.name} onChange={e=>setFamily(family.map((x,j)=>i===j?{...x,name:e.target.value}:x))}/></label><label>Relationship<input required maxLength={80} className={input} value={f.relationship} onChange={e=>setFamily(family.map((x,j)=>i===j?{...x,relationship:e.target.value}:x))}/></label><button type="button" className={secondary} onClick={()=>setFamily(family.filter((_,j)=>i!==j))}>Remove</button></div>)}
   <button type="button" disabled={family.length>=4} className={secondary} onClick={()=>setFamily([...family,{name:'',relationship:''}])}>Add family member</button>
   <button type="button" disabled={busy} className={secondary+' ml-2'} onClick={()=>run(async()=>{await saveFamilyVisitDraft({destination,date,family,entry,confirmed});setForm(false);})}>Save Draft</button>
   <label className="flex items-start gap-2"><input type="checkbox" required checked={entry} onChange={e=>setEntry(e.target.checked)}/>I understand that only entry is covered.</label><label className="flex items-start gap-2"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm that the information is correct and all accompanying guests are my immediate family members.</label>
   <div className="flex gap-2"><button disabled={busy||!entry||!confirmed} className={button}>{busy?'Submitting…':'Submit for Approval'}</button><button type="button" className={secondary} disabled={busy} onClick={()=>{if(window.confirm('Close this form? Your entries will stay here until you leave this page.'))setForm(false);}}>Close</button></div>
  </form>}
  <div className={box}><h3 className="mb-4 text-xl font-bold">{mode==='mine'?'My Annual History':'Family Visit Requests & Fulfillment History'}</h3><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Employee','Destination BU','Intended Visit Date','Guests','Status','Operations Acknowledgment','Fulfillment Date','Actions'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-200 dark:border-slate-700"><td className="p-3">{r.employee_name}</td><td className="p-3">{r.family_visit.destination_name||'Destination BU Not Recorded'}</td><td className="p-3">{r.date_needed}</td><td className="p-3">{r.family_visit.family?1+r.family_visit.family.length:'Not recorded'}</td><td className="p-3">{visitStatus(r)}</td><td className="p-3">{manilaTime(r.family_visit.operations_acknowledged_at)}</td><td className="p-3">{manilaTime(r.fulfilled_at)}</td><td className="p-3"><button className={secondary} onClick={()=>open(r.id)}>View Details</button></td></tr>)}</tbody></table>{rows.length===0&&<p className="py-8 text-center text-slate-500">No visits for this year.</p>}</div></div>
  {current&&<div role="dialog" aria-modal="true" aria-label="Family Visit Details" className="fixed inset-0 z-50 overflow-y-auto bg-black/60 p-3 sm:p-8"><div className={box+' mx-auto max-w-4xl space-y-4'}>
   <div className="flex items-start justify-between gap-3"><h2 className="text-xl font-bold">Family Visit Privilege · {current.family_visit.destination_name||'Destination BU Not Recorded'}</h2><button disabled={busy} className={secondary} onClick={close}>Close</button></div>
   <p className="break-all text-xs">{current.family_visit.reference||current.id}</p><p>{current.employee_name} · Employee ID: {current.family_visit.employee_number||'Not recorded'} · Home BU: {current.family_visit.home_bu||'Not recorded'}</p><p>Visit date: {current.date_needed} · {visitStatus(current)}</p><p>Submitted: {manilaTime(current.submission_date)} · Approved: {manilaTime(current.bod_approved_at)} · Authority: {detail.approver||'Not recorded'}</p>
   <h3 className="font-bold">Approved/requested guests</h3><ul className="list-disc pl-5"><li>{current.employee_name} — Employee</li>{current.family_visit.family?.map((f,i)=><li key={i}>{f.name} — {f.relationship}</li>)}</ul>{!current.family_visit.family&&<p>Historical family-member details not recorded.</p>}
   <p className="text-sm">Entry only. Employee plus up to four immediate family members (five total guests).</p>
   {selected?.eligibility&&<div className="rounded-lg bg-slate-100 p-4 dark:bg-slate-900"><h3 className="font-bold">{current.date_needed.slice(0,4)} Family Visit Privilege Record</h3><p>Annual entitlement: Four different BU visits</p><p>Other approved/availed: {selected.eligibility.used} of 4 · Pending: {selected.eligibility.pending} · Remaining after approval: {selected.eligibility.remaining_after_approval}</p><p className="mt-2 font-semibold">{selected.eligibility.reason}</p>{selected.eligibility.conflict_id&&<button className={secondary} onClick={()=>open(selected.eligibility!.conflict_id!)}>View conflicting transaction</button>}<details className="mt-3"><summary>View Annual History</summary>{history.map(r=><button className="block py-2 text-left underline" key={r.id} onClick={()=>open(r.id)}>{r.family_visit.destination_name||'Destination BU Not Recorded'} · {r.date_needed} · {visitStatus(r)}</button>)}</details></div>}
   {current.family_visit.cancellation&&<p>Cancellation: {current.family_visit.cancellation.status} — {current.family_visit.cancellation.reason} {current.family_visit.cancellation.review_reason}</p>}
   <p>Operations acknowledgment: {manilaTime(current.family_visit.operations_acknowledged_at)} · Fulfilled: {manilaTime(current.fulfilled_at)}</p>{current.family_visit.operational_note&&<p>Operations note: {current.family_visit.operational_note}</p>}
   {error&&<p role="alert" className="text-red-600 dark:text-red-300">{error}</p>}
   <label className="block">Reason / operational note<textarea className={input} value={note} onChange={e=>setNote(e.target.value)}/></label>
   <div className="flex flex-wrap gap-2">
    {selected?.can_review&&<><button disabled={busy||!selected.eligibility?.eligible} className={button} onClick={()=>run(()=>reviewBenefitRequest(current.id,true))}>Approve</button><button disabled={busy||!note.trim()} className={secondary} onClick={()=>run(()=>reviewBenefitRequest(current.id,false,note))}>Reject</button></>}
    {['Approved','Fulfilled'].includes(current.status)&&<button disabled={busy} className={button} onClick={()=>run(()=>downloadFamilyVisitPass(current.id))}>Download PDF Pass</button>}
    {(current.employee_id===data.employee.id||data.hr)&&current.status.startsWith('Pending')&&<button disabled={busy||!note.trim()} className={secondary} onClick={()=>action('withdraw')}>Withdraw Request</button>}
    {(current.employee_id===data.employee.id||data.hr)&&current.status==='Approved'&&<button disabled={busy||!note.trim()} className={secondary} onClick={()=>action('cancel_request')}>Request Cancellation</button>}
    {data.hr&&current.family_visit.cancellation?.status==='Pending HR Review'&&<><button disabled={busy||!note.trim()} className={button} onClick={()=>action('cancel_approve')}>Approve Cancellation & Restore Visit</button><button disabled={busy||!note.trim()} className={secondary} onClick={()=>action('cancel_reject')}>Reject Cancellation</button></>}
    {selected?.can_operate&&current.status==='Approved'&&<><button disabled={busy||!!current.family_visit.operations_acknowledged_at} className={button} onClick={()=>action('acknowledge')}>Acknowledge Receipt</button><button disabled={busy} className={button} onClick={()=>action('fulfill')}>Mark Availed/Fulfilled</button><button disabled={busy||!note.trim()} className={secondary} onClick={()=>action('no_show')}>Report No-show</button><button disabled={busy||!note.trim()} className={secondary} onClick={()=>action('discrepancy')}>Report Discrepancy</button></>}
   </div>
   {data.hr&&current.family_visit.legacy&&<div className="flex flex-wrap gap-2"><select className={input} value={value} onChange={e=>setValue(e.target.value)}><option value="">Correct historical destination</option>{data.destinations.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button disabled={busy||!value||!note.trim()} className={secondary} onClick={()=>action('correct_destination')}>Save Audited Correction</button></div>}
   {data.hr&&current.status==='Approved'&&<div className="flex flex-wrap gap-2"><label>New visit date<input type="date" className={input} value={value} onChange={e=>setValue(e.target.value)}/></label><button disabled={busy||!value||!note.trim()} className={secondary} onClick={()=>action('reschedule')}>Reschedule & Notify Operations</button></div>}
   <details><summary className="cursor-pointer font-bold">Audit & fulfillment history</summary>{detail.audit?.map((a:any)=><div className="border-t py-3 dark:border-slate-600" key={a.id}><p>{a.action} · {a.actor} · {manilaTime(a.created_at)}</p><p className="text-sm">{a.new_value?.note||a.new_value?.status||a.new_value?.event||''}</p></div>)}{detail.audit?.length===0&&<p>Original approval and fulfillment timestamps are retained above. No post-migration actions yet.</p>}</details>
  </div></div>}
 </section>;
}
