import React, {useCallback,useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {supabase} from '../../services/supabaseClient';
import RequestInformationForm from './RequestInformationForm';
import {useAuth} from '../../hooks/useAuth';

const panel='rounded-xl border border-slate-200 bg-white p-4 sm:p-6 dark:border-slate-700 dark:bg-slate-800';
const input='block w-full rounded-lg border border-slate-300 bg-white p-2.5 dark:border-slate-600 dark:bg-slate-900';
const button='inline-flex items-center justify-center rounded-lg bg-violet-600 px-4 py-2 font-semibold text-white disabled:opacity-50';
const secondary='inline-flex items-center rounded-lg border border-slate-400 px-4 py-2 font-medium disabled:opacity-50';
const time=(v:string)=>new Date(v).toLocaleString('en-PH',{timeZone:'Asia/Manila',dateStyle:'medium',timeStyle:'short'})+' PHT';
async function call(name:string,args?:Record<string,unknown>){const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message);return data;}
const recipientLabel=(kind:string)=>kind==='respondent'?'Respondent':kind==='manager'?'Manager':'Incident Reporter';
function deadline(value:string){return new Date(value+':00+08:00').toISOString();}
export function CaseFollowups(){
 const {user}=useAuth();const [rows,setRows]=useState<any[]>([]);
 useEffect(()=>{let active=true; const refresh=()=>call('get_my_case_questions').then(d=>{if(active)setRows(d||[]);}).catch(()=>{});refresh();window.addEventListener('case-questions-updated',refresh);return()=>{active=false;window.removeEventListener('case-questions-updated',refresh);};},[user?.id]);
 if(!rows.length)return null;
 return <section className={panel+' mb-4 border-amber-400'}><h2 className="text-lg font-bold">Action Required: Case Questions</h2>{rows.map(r=><div key={r.id} className="mt-3 flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{r.reference}</p><p className="text-sm">Response due {time(r.deadline)}</p></div><Link className={button} to={'/case-questions?case='+r.case_id}>Reply to questions</Link></div>)}</section>;
}
function Attachments({files,bucket='case-correspondence'}:{files:string[];bucket?:string}){
 const [error,setError]=useState('');
 const open=async(path:string)=>{try{const {data,error}=await supabase.storage.from(bucket).createSignedUrl(path,60);if(error)throw error;window.open(data.signedUrl,'_blank','noopener,noreferrer');}catch(e:any){setError(e.message);}};
 return <div className="flex flex-wrap gap-2">{files.map((f,i)=><button type="button" key={f} className="text-violet-700 underline dark:text-violet-300" onClick={()=>void open(f)}>Attachment {i+1}</button>)}{error&&<p role="alert">{error}</p>}</div>;
}
function OriginalEvidence({original}:{original:any}) {
 const values=[original.attachment,...(Array.isArray(original.files)?original.files:[])];
 const paths=[...new Set(values.map(v=>typeof v==='string'?v:v?.path||v?.url||v?.href||v?.storagePath).filter(v=>typeof v==='string'&&v&&!/^https?:/i.test(v)))];
 return <Attachments files={paths} bucket="incident_reports_attachments"/>;
}
function Reply({data,q,refresh}:{data:any;q:any;refresh:()=>Promise<void>}){
 const drafts=data.messages.filter((m:any)=>m.question_id===q.id&&m.draft&&m.author===data.actorId);
 const last=drafts[drafts.length-1];
 const [body,setBody]=useState(last?.body||'');const [files,setFiles]=useState<string[]>(last?.files||[]);const [links,setLinks]=useState((last?.links||[]).join('\n'));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const lock=useRef(false);const nonce=useRef({draft:crypto.randomUUID(),final:crypto.randomUUID()});
 const edit=()=>{nonce.current={draft:crypto.randomUUID(),final:crypto.randomUUID()};setMessage('');};
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(files.length>=10){setError('Maximum 10 attachments.');return;}if(f.size>5242880){setError('Each attachment must be 5 MB or smaller.');return;}const ext:Record<string,string>={'application/pdf':'pdf','image/png':'png','image/jpeg':'jpg','image/webp':'webp'};if(!ext[f.type]){setError('Use a PDF, PNG, JPG, or WebP file.');return;}setBusy(true);try{const path=`${data.id}/${data.actorId}/${crypto.randomUUID()}.${ext[f.type]}`;const {error}=await supabase.storage.from('case-correspondence').upload(path,f,{upsert:false,contentType:f.type});if(error)throw error;setFiles(v=>[...v,path]);edit();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const save=async(draft:boolean)=>{if(lock.current||busy)return;lock.current=true;setBusy(true);setError('');try{await call('save_case_reply',{p_id:data.id,p_question:q.id,p_body:body,p_files:files,p_links:links.split('\n').map((v:string)=>v.trim()).filter(Boolean),p_draft:draft,p_kind:'reply',p_nonce:draft?nonce.current.draft:nonce.current.final});nonce.current={draft:crypto.randomUUID(),final:crypto.randomUUID()};setMessage(draft?'Draft saved':'Response submitted');await refresh();window.dispatchEvent(new Event('case-questions-updated'));}catch(e:any){setError(e.message);}finally{lock.current=false;setBusy(false);}};
 return <div className="mt-4 space-y-3"><h4 className="font-semibold">Your response</h4><p className="text-sm">Your previous drafts are retained. Submit a final response when ready.</p><label className="block">Written response<textarea className={input} rows={5} maxLength={10000} value={body} onChange={e=>{setBody(e.target.value);edit();}}/></label><label className="block">Supporting HTTPS links (one per line)<textarea className={input} rows={2} value={links} onChange={e=>{setLinks(e.target.value);edit();}}/></label><label className="block">Attach Response · up to 5 MB per file<input type="file" accept="application/pdf,image/png,image/jpeg,image/webp" disabled={busy} onChange={upload} className="block max-w-full"/></label><Attachments files={files}/>{q.request_id&&q.attachment_requested&&!files.length&&<p className="text-sm text-amber-700 dark:text-amber-300">A supporting attachment is required before submitting.</p>}<div className="flex flex-wrap gap-2"><button className={secondary} disabled={busy} onClick={()=>void save(true)}>Save Draft</button><button className={button} disabled={busy||!body.trim()||(!!q.request_id&&q.attachment_requested&&!files.length)} onClick={()=>void save(false)}>Submit Reply</button></div>{error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}{message&&<p role="status">{message}</p>}</div>;
}
export function CaseQuestions({caseId,nteId}:{caseId:string;nteId?:string}){
 const [data,setData]=useState<any>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [compose,setCompose]=useState(false);const [body,setBody]=useState('');const [details,setDetails]=useState('');const [due,setDue]=useState('');const [manager,setManager]=useState('');const [attachment,setAttachment]=useState(false);const [note,setNote]=useState('');const [reason,setReason]=useState('');const [message,setMessage]=useState('');const lock=useRef(false);const nonce=useRef(crypto.randomUUID());const generation=useRef(0);
 const refresh=useCallback(async()=>{const n=++generation.current;const next=await call('get_case_questions',{p_id:caseId});if(n===generation.current)setData(next);},[caseId]);
 useEffect(()=>{setData(undefined);setError('');refresh().catch(e=>setError(e.message));return()=>{generation.current++;};},[refresh]);
 const run=async(fn:()=>Promise<any>,success:string)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();setMessage(success);nonce.current=crypto.randomUUID();await refresh();window.dispatchEvent(new Event('case-questions-updated'));}catch(e:any){setError(e.message);}finally{lock.current=false;setBusy(false);}};
 const action=(q:string|null,value:string)=>run(()=>call('review_case_correspondence',{p_id:caseId,p_question:q,p_action:value,p_reason:reason,p_deadline:value==='deadline'&&due?deadline(due):null}),'Review recorded');
 if(!data)return <div className={panel}>{error?<p role="alert">{error}</p>:<p role="status">Loading case questions…</p>}</div>;
 return <section className={panel+' space-y-5'}><header className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">Case Questions and Replies</h2><p>{data.reference} · {data.status}</p></div>{data.canRequest&&<button className={button} onClick={()=>setCompose(v=>!v)}>Request additional information</button>}</header>
 {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-800 dark:bg-red-950 dark:text-red-200">{error}</p>}{message&&<p role="status" className="text-emerald-700 dark:text-emerald-300">{message}</p>}
 {data.original&&<details className="rounded-lg border p-3"><summary className="cursor-pointer font-semibold">Original Incident Report</summary><p className="mt-2 text-sm">Submitted {data.original.submittedAt?time(data.original.submittedAt):'—'}</p><p className="font-semibold">{data.original.category}</p><p className="whitespace-pre-wrap break-words">{data.original.description}</p><OriginalEvidence original={data.original}/></details>}
 {data.pendingInformation&&<p role="status" className="rounded-lg bg-amber-50 p-3 text-amber-900 dark:bg-amber-950 dark:text-amber-200">Additional information is pending. The case remains open until all requests are reviewed or explicitly resolved.</p>}
 {compose&&data.canRequest&&<RequestInformationForm data={data} nteId={nteId} onCancel={()=>setCompose(false)} onSent={async()=>{await refresh();setCompose(false);setMessage('Additional information requested. HRIS and email notifications queued.');window.dispatchEvent(new Event('case-questions-updated'));}}/>}
 {data.internalNotes?.length>0&&<section className="space-y-2"><h3 className="font-semibold">Request notes · HR/Admin only</h3>{data.internalNotes.map((n:any)=><div key={n.id} className="rounded-lg bg-slate-100 p-3 dark:bg-slate-900"><p className="text-sm">{n.author} · {time(n.createdAt)}</p><p className="whitespace-pre-wrap">{n.body}</p></div>)}</section>}

 {!data.questions.length&&<p>No questions have been sent.</p>}
 {data.questions.map((q:any)=><article key={q.id} className="rounded-lg border border-slate-300 p-4 dark:border-slate-600"><p className="text-sm font-semibold text-violet-700 dark:text-violet-300">Message to {recipientLabel(q.kind)} · {q.recipient_name}</p><p className="mt-1 text-sm">From {q.sender_name} · {time(q.created_at)}</p><p className="mt-3 whitespace-pre-wrap break-words">{q.body}</p>{q.details&&<p className="mt-2 whitespace-pre-wrap">{q.details}</p>}<p className="mt-3 text-sm font-medium">Due {time(q.deadline)} · {q.state}{q.attachment_requested?' · Supporting attachment required':''}</p>{q.opened_at&&<p className="text-xs">Opened {time(q.opened_at)}</p>}
 {data.messages.filter((m:any)=>m.question_id===q.id&&!m.draft).map((m:any)=><div key={m.id} className="mt-4 border-l-4 border-emerald-500 pl-3"><p className="font-semibold">{recipientLabel(q.kind)} supplemental response · {m.author_name}</p><p className="text-sm">Response submitted · {time(m.created_at)} · Revision {m.revision}</p><p className="mt-2 whitespace-pre-wrap break-words">{m.body}</p><Attachments files={m.files}/>{m.links.map((url:string)=><a className="block break-all underline" key={url} href={url} target="_blank" rel="noopener noreferrer">Supporting documentation</a>)}</div>)}
 {q.recipient===data.actorId&&q.state==='awaiting'&&<Reply data={data} q={q} refresh={refresh}/>}
 {data.canManage&&<div className="mt-3 flex flex-wrap gap-2">{q.state==='received'&&<button disabled={busy||!reason.trim()} className={secondary} onClick={()=>void action(q.id,'reviewed')}>Mark response reviewed</button>}{['awaiting','received'].includes(q.state)&&<button disabled={busy||!reason.trim()} className={secondary} onClick={()=>void action(q.id,'resolve')}>Resolve question</button>}{q.state==='awaiting'&&<button disabled={busy||!reason.trim()||!due} className={secondary} onClick={()=>void action(q.id,'deadline')}>Update deadline</button>}</div>}</article>)}
 {data.canManage&&<div className="space-y-3 border-t pt-4"><h3 className="font-bold">HR review</h3><label className="block">Review reason (required for review actions)<textarea className={input} rows={2} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="block">New response deadline, when needed (Philippine time)<input className={input} type="datetime-local" value={due} onChange={e=>{setDue(e.target.value);nonce.current=crypto.randomUUID();}}/></label><div className="flex flex-wrap gap-2"><button disabled={busy||!reason.trim()} className={secondary} onClick={()=>void action(null,'Ready for Endorsement')}>Ready for Endorsement</button><button disabled={busy||!reason.trim()} className={secondary} onClick={()=>void action(null,'Closed')}>Close communication review</button><Link className={secondary} to="/feedback/cases">Continue case review</Link></div><p className="text-sm">Case endorsement, closure, and NTE issuance continue through their existing authorized workflows.</p></div>}
 {data.canComment&&<section className="space-y-3 border-t pt-4"><h3 className="font-bold">Internal HR notes and approver comments</h3><p className="text-sm">Private to authorized reviewers. Never sent to the complainant.</p>{data.messages.filter((m:any)=>m.kind!=='reply'&&!m.draft).map((m:any)=><div key={m.id} className="rounded bg-slate-100 p-3 dark:bg-slate-900"><p className="text-sm font-semibold">{m.kind==='internal'?'Internal HR note':'BOD or approver comment'} · {m.author_name} · {time(m.created_at)}</p><p className="whitespace-pre-wrap">{m.body}</p></div>)}<textarea aria-label="Private note" className={input} rows={3} maxLength={10000} value={note} onChange={e=>{setNote(e.target.value);nonce.current=crypto.randomUUID();}}/><button className={secondary} disabled={busy||!note.trim()} onClick={()=>void run(async()=>{await call('save_case_reply',{p_id:caseId,p_question:null,p_body:note,p_files:[],p_links:[],p_draft:false,p_kind:data.canManage?'internal':'comment',p_nonce:nonce.current});setNote('');},'Private note saved')}>Add private note</button></section>}
 {data.canComment&&<details><summary className="cursor-pointer font-semibold">Audit timeline</summary>{data.timeline.map((t:any,i:number)=><div key={i} className="mt-2 border-b py-2 text-sm"><p>{time(t.created_at)} · {t.action} · {t.actor_name||'System'}</p><p>{t.new_value?.reason||''}</p></div>)}</details>}
 </section>;
}
export default function CaseQuestionsPage(){const [params]=useSearchParams();const id=params.get('case');return <main className="mx-auto max-w-5xl space-y-4 text-slate-900 dark:text-slate-100"><Link className="inline-block underline" to="/dashboard">Back to Dashboard</Link>{id&&/^[0-9a-f-]{36}$/i.test(id)?<CaseQuestions caseId={id}/>:<p>Select a case from your notification or review page.</p>}</main>;}
