import { Offer, OfferApprovalStatus, OfferStatus } from '../types';

const dateOrUndefined = (value?: string | null) => value ? new Date(value) : undefined;

export const mapJobOfferRow = (row: any): Offer => ({
  id: row.id,
  applicationId: row.application_id,
  offerNumber: row.offer_number || '',
  basePay: Number(row.base_pay || 0),
  basePaySpecified: row.offer_details?.compensationEntered === true || Number(row.base_pay || 0) > 0,
  allowanceJSON: JSON.stringify(row.allowance_json || {}),
  startDate: new Date(row.start_date || Date.now()),
  probationMonths: row.probation_months ?? 0,
  employmentType: row.employment_type || 'Full-Time',
  employmentTypeCustomName: row.employment_type_custom_name || undefined,
  employmentEndDate: dateOrUndefined(row.employment_end_date),
  supersedesOfferId: row.supersedes_offer_id || undefined,
  status: row.status as OfferStatus,
  reportingTo: row.reporting_to || '',
  jobDescription: row.job_description || '',
  offerDetails: row.offer_details || {},
  draftStep: row.draft_step || 1,
  offerExpirationDate: dateOrUndefined(row.offer_expiration_date),
  logoUrl: row.logo_url || undefined,
  logoPath: row.logo_path || undefined,
  lastSavedAt: dateOrUndefined(row.last_saved_at),
  sentAt: dateOrUndefined(row.sent_at),
  sentByUserId: row.sent_by_user_id || undefined,
  recipientEmail: row.recipient_email || undefined,
  emailSubject: row.email_subject || undefined,
  emailMessage: row.email_message || undefined,
  secureToken: row.secure_token || undefined,
  revision: row.revision || 1,
  viewedAt: dateOrUndefined(row.viewed_at),
  acceptedAt: dateOrUndefined(row.accepted_at),
  signedAt: dateOrUndefined(row.signed_at),
  declinedAt: dateOrUndefined(row.declined_at),
  declineReason: row.decline_reason || undefined,
  signatureName: row.signature_name || undefined,
  signatureType: row.signature_type || undefined,
  signaturePath: row.signature_path || undefined,
  signedPdfPath: row.signed_pdf_path || undefined,
  requireSignature: row.require_signature !== false,
  offerTemplateId: row.offer_template_id || undefined,
  offerTemplateName: row.offer_template_name || undefined,
  offerTemplateSnapshot: row.offer_template_snapshot || undefined,
  approvalStatus: (row.approval_status || 'Not Requested') as OfferApprovalStatus,
  approvalRequestId: row.approval_request_id || undefined,
});
