import {supabase} from './supabaseClient';
export type ScheduleEntry={name:string;date:string;start:string;end:string;kind:string;flexible:boolean;paidMinutes:number|null;endDayOffset:number|null};
export type SchedulePublication={employeeId:string;draftHash:string;publicationId:string|null;version:number|null;activeVersion:number|null;current:boolean;published:boolean;pending:boolean;frozen:boolean;reference:string;decision:string|null;before:ScheduleEntry[]|null;after:ScheduleEntry[]|null;canApprove:boolean};
export async function getScheduleWeek(employees:string[],week:string):Promise<SchedulePublication[]>{const {data,error}=await supabase.rpc('get_payroll_schedule_week',{p_employee_ids:employees,p_week:week});if(error)throw new Error(error.message);return data;}
export async function publishScheduleWeek(employees:string[],week:string,reference:string,rows:SchedulePublication[]){const {data,error}=await supabase.rpc('publish_payroll_schedule_week',{p_employee_ids:employees,p_week:week,p_reference:reference,p_expected:Object.fromEntries(rows.map(r=>[r.employeeId,r.draftHash]))});if(error)throw new Error(error.message);return data;}
export async function reviewScheduleOverride(id:string,approve:boolean,reference:string){const {error}=await supabase.rpc('review_payroll_schedule_override',{p_id:id,p_approve:approve,p_reference:reference});if(error)throw new Error(error.message);}
export type ScheduleReview=SchedulePublication & {ready:boolean;name:string;businessUnit:string;saved:number;restDays:number;absences:number;issues:{date?:string;message:string}[]};
export async function reviewScheduleWeek(employees:string[],week:string):Promise<ScheduleReview[]>{const {data,error}=await supabase.rpc('review_payroll_schedule_week',{p_employee_ids:employees,p_week:week});if(error)throw new Error(error.message);return data;}
export type PublicationHistory={version:number;publishedAt:string;publisher:string;note:string;from:string;to:string;approvalRequired:boolean;decision:string|null;reviewedAt:string|null};
export async function getPublicationHistory(employee:string,week:string):Promise<PublicationHistory[]>{const {data,error}=await supabase.rpc('get_schedule_publication_history',{p_employee:employee,p_week:week});if(error)throw new Error(error.message);return data;}
