const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export type Notice = { title: string; intro: string; badge?: string; urgent?: boolean; facts?: Array<[string,string]>; paragraphs?: string[]; actions?: Array<{label:string;url:string}> };
export function noticeHtml(notice: Notice) {
 const color = notice.urgent ? '#b91c1c' : '#6d28d9';
 const actions = (notice.actions || []).filter(a => { try { const u=new URL(a.url); return u.protocol==='https:' && !u.username && !u.password; } catch { return false; } });
 return `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"></head><body style="margin:0;background:#eef2f7;font-family:Arial,Helvetica,sans-serif;color:#172033"><div style="display:none;max-height:0;overflow:hidden">${escape(notice.intro)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:24px 12px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;margin:auto;background:#fff;border-radius:16px;overflow:hidden"><tr><td style="padding:24px;background:#101a30;color:#fff;font-size:22px;font-weight:700">TNG <span style="color:#c4b5fd">HRIS</span><div style="font-size:12px;font-weight:400;margin-top:8px;color:#cbd5e1">Your workplace, connected</div></td></tr><tr><td style="padding:28px 24px">${notice.badge?`<span style="display:inline-block;padding:7px 12px;border-radius:20px;background:#f3e8ff;color:${color};font-size:12px;font-weight:700">${escape(notice.badge)}</span>`:''}<h1 style="font-size:25px;line-height:1.3;margin:18px 0 12px">${escape(notice.title)}</h1><p style="font-size:16px;line-height:1.6;color:#475569">${escape(notice.intro)}</p>${notice.facts?.length?`<table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e2e8f0;border-radius:10px;margin:20px 0">${notice.facts.map(([label,value])=>`<tr><th scope="row" style="padding:12px;text-align:left;font-size:13px;color:#64748b;border-bottom:1px solid #e2e8f0;width:35%">${escape(label)}</th><td style="padding:12px;font-size:14px;font-weight:600;border-bottom:1px solid #e2e8f0">${escape(value)}</td></tr>`).join('')}</table>`:''}${(notice.paragraphs||[]).map(p=>`<p style="font-size:14px;line-height:1.6;overflow-wrap:anywhere">${escape(p).replace(/\n/g,'<br>')}</p>`).join('')}${actions.map((a,i)=>`<table role="presentation" cellpadding="0" cellspacing="0" style="margin:14px 0"><tr><td style="border-radius:8px;background:${i?'#ede9fe':'#7c3aed'}"><a href="${escape(a.url)}" style="display:inline-block;padding:15px 22px;font-size:15px;font-weight:700;text-decoration:none;color:${i?'#5b21b6':'#fff'}">${escape(a.label)} &rarr;</a></td></tr></table>`).join('')}<p style="margin-top:26px;font-size:12px;line-height:1.6;color:#64748b">Open HRIS and sign in to view current information and complete any required action.</p></td></tr><tr><td style="padding:18px 24px;background:#f8fafc;font-size:12px;color:#64748b">TNG HRIS · The Nextperience Group</td></tr></table></td></tr></table></body></html>`;
}
export function textNoticeHtml(subject: string, text: string, baseUrl: string) {
 const actions: Array<{label:string;url:string}>=[];
 const paragraphs=text.split(/\n\s*\n/).map(block=>block.split('\n').filter(line=>{
 const match=line.match(/^([^\n]+?):\s*(https:\/\/\S+)\s*$/);
 if(!match)return true;
 try { if(new URL(match[2]).origin!==new URL(baseUrl).origin)return true; }catch{return true;}
 actions.push({label:match[1],url:match[2]});return false;
 }).join('\n')).filter(Boolean);
 return noticeHtml({title:subject.replace(/^\[TNG HRIS\]\s*/,''),intro:'You have an update in TNG HRIS.',paragraphs,actions,badge:/overdue/i.test(subject)?'Overdue':/action|required|pending|waiting|review/i.test(subject)?'Action required':'HRIS update',urgent:/overdue/i.test(subject)});
}
