import React,{useCallback,useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

// Deliberately isolated from AuthProvider, normal navigation and persisted sessions.
const client=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
export default function OffboardingAccessPortal(){
 const [token]=useState(()=>window.location.hash.slice(1));
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[responses,setResponses]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{const {data,error}=await client.rpc('offboarding_portal',{p_token:token});if(error){setData(null);throw new Error(error.message);}setData(data);setError('');},[token]);
 useEffect(()=>{history.replaceState(null,'',window.location.pathname);void load().catch(e=>setError(e.message));const timer=setInterval(()=>void load().catch(e=>setError(e.message)),30000);return()=>clearInterval(timer);},[load]);
 useEffect(()=>{if(!data?.expiresAt)return;const remaining=new Date(data.expiresAt).getTime()-Date.now();const timer=setTimeout(()=>{setData(null);setError('Offboarding access has expired. Please contact HR.');},Math.max(0,Math.min(remaining,2147483647)));return()=>clearTimeout(timer);},[data?.expiresAt]);
 async function submit(id:string){setBusy(true);setNotice('');setError('');try{const {data,error}=await client.rpc('offboarding_portal',{p_token:token,p_task:id,p_response:responses[id]||''});if(error)throw new Error(error.message);setData(data);setNotice('Response submitted for HR clearance review.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(task:string,file?:File){if(!file)return;setBusy(true);setError('');try{if(file.size>1048576)throw new Error('Choose a document up to 1 MB.');const content=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Could not read this document.'));reader.readAsDataURL(file);});const {data,error}=await client.rpc('upload_offboarding_document',{p_token:token,p_task:task,p_id:crypto.randomUUID(),p_filename:file.name,p_content:content});if(error)throw new Error(error.message);setData(data);setNotice('Document submitted for HR review.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="min-h-screen bg-slate-100 p-4 text-slate-900"><div className="mx-auto max-w-3xl space-y-5"><h1 className="text-3xl font-bold">TNG HRIS · Offboarding</h1><p>This access is limited to your offboarding checklist. Your regular HRIS account remains inactive.</p>{error&&<p role="alert" className="rounded border border-red-300 bg-white p-4 text-red-700">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!data&&!error&&<p>Checking offboarding access…</p>}{data&&<><section className="rounded-xl bg-white p-4"><h2 className="text-xl font-semibold">{data.employee}</h2><p>Status: {data.status}</p><p>Access expires: {new Date(data.expiresAt).toLocaleString()}</p></section>{data.tasks.map((t:any)=><section key={t.id} className="space-y-3 rounded-xl bg-white p-4"><h2 className="text-lg font-semibold">{t.name}</h2><p>{t.description}</p><p className="whitespace-pre-wrap">{t.readContent}</p>{t.assetDescription&&<p>Company property: {t.assetDescription}</p>}<p>{t.status}{t.dueDate?` · Due ${new Date(t.dueDate).toLocaleDateString()}`:''}</p>{t.submissionValue&&<p className="whitespace-pre-wrap">Your response: {t.submissionValue}</p>}{t.canSubmit&&<>{t.taskType==='Upload Document'&&<label className="block">Upload document (PDF, image or text; up to 1 MB)<input type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" disabled={busy} onChange={e=>void upload(t.id,e.target.files?.[0])} className="block min-h-11"/></label>}<label className="block">Acknowledgment, clearance response or return confirmation<textarea maxLength={10000} className="mt-1 w-full rounded border p-2" value={responses[t.id]||''} onChange={e=>setResponses({...responses,[t.id]:e.target.value})}/></label><button disabled={busy||!responses[t.id]?.trim()} onClick={()=>void submit(t.id)} className="min-h-11 rounded bg-violet-600 px-4 text-white disabled:opacity-50">Submit to HR</button></>}</section>)}{!data.tasks.length&&<p>No employee tasks are currently assigned. Please contact HR.</p>}</>}
 <button onClick={()=>{setData(null);window.location.replace('/login');}} className="min-h-11 underline">Exit offboarding</button></div></main>;
}
