import React,{useEffect,useRef,useState} from 'react';
import {supabase} from '../../services/supabaseClient';
import {AttendanceIssue,attendanceChanged,issueLabels,issueRpc,todayManila,manila} from '../../services/attendanceIssues';
import Modal from '../ui/Modal';
const field='mt-1 min-h-12 w-full rounded-xl border border-slate-300 bg-white p-3 text-slate-900 dark:border-slate-600 dark:bg-slate-900 dark:text-white';
export default function AttendanceIssueForm({onClose,onSaved,initial}:{onClose:()=>void;onSaved:(id:string)=>void;initial?:AttendanceIssue}){
 const [kind,setKind]=useState<keyof typeof issueLabels>(initial?.kind||'absence');const [date,setDate]=useState(initial?.work_date||todayManila());
 const local=initial?.requested_time?new Date(Date.parse(initial.requested_time)+8*3600000).toISOString():'';
 const [time,setTime]=useState(local.slice(11,16));const [nextDay,setNextDay]=useState(!!local&&local.slice(0,10)!==date);const [category,setCategory]=useState(initial?.category||'Sickness');const [note,setNote]=useState(initial?.explanation||'');const [punch,setPunch]=useState(initial?.punch_type||'CLOCK_IN');const [confirmed,setConfirmed]=useState(initial?.confirmed||false);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const key=useRef(crypto.randomUUID());const uploading=useRef(false);const path=useRef(initial?.attachment||'');const [dirty,setDirty]=useState(false);const [changesConfirmed,setChangesConfirmed]=useState(false);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const close=()=>{if(!busy&&(!dirty||window.confirm('Discard your unsaved attendance report?')))onClose();};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(uploading.current)return;uploading.current=true;setBusy(true);setError('');try{
 if(file&&!path.current){if(file.size>10*1024*1024||!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Attach a PDF, JPG, PNG, or WebP file up to 10 MB.');const auth=await supabase.auth.getUser();if(!auth.data.user)throw new Error('Sign in again to upload your attachment.');const p=`${auth.data.user.id}/${key.current}/${crypto.randomUUID()}`;const result=await supabase.storage.from('attendance-issue-files').upload(p,file,{contentType:file.type});if(result.error)throw result.error;path.current=p;}
 const day=nextDay?new Date(Date.parse(date+'T00:00:00Z')+86400000).toISOString().slice(0,10):date;
 const id=await issueRpc<string>('submit_attendance_issue',{p_key:key.current,p_id:initial?.id||null,p_revision:initial?.revision||null,p_data:{kind,date,time:kind==='absence'?null:`${day}T${time}:00+08:00`,punch,category,explanation:note,confirmed,changesConfirmed,attachment:path.current||null}});
 attendanceChanged();setDirty(false);onSaved(id);
 }catch(e){setError((e as Error).message);}finally{uploading.current=false;setBusy(false);}};
 return <Modal isOpen onClose={close} title={initial?'Edit and Resubmit':'Report attendance issue'} size="lg"><form onSubmit={submit} onChange={()=>{setDirty(true);}} className="space-y-5 p-4 sm:p-6">{initial&&<section className="rounded-xl border border-amber-400 bg-amber-50 p-4 text-amber-950 dark:bg-amber-950 dark:text-amber-100"><h3 className="font-bold">Manager’s clarification</h3><p className="whitespace-pre-wrap">{initial.clarification_message||initial.audit.filter(a=>a.action==='details').at(-1)?.reason}</p><p className="mt-2 text-sm">Original reference: {initial.id} · Revision {initial.revision}</p><details className="mt-3"><summary>Previously submitted fields</summary><p>{issueLabels[initial.kind]} · {initial.work_date}</p><p>{initial.requested_time&&manila(initial.requested_time)}</p><p>{initial.category}</p><p className="whitespace-pre-wrap">{initial.explanation}</p><p>{initial.attachment?'Previous attachment is preserved in request history.':'No previous attachment.'}</p></details></section>}<fieldset disabled={busy} className="space-y-4"><legend className="mb-3">Select the issue you want to report.</legend><div className="grid gap-2 sm:grid-cols-2">{Object.entries(issueLabels).map(([value,label])=><label key={value} className={'flex min-h-16 cursor-pointer items-center gap-3 rounded-xl border p-4 '+(kind===value?'border-violet-500 bg-violet-50 dark:bg-violet-950':'border-slate-300 dark:border-slate-600')}><input type="radio" name="issue-kind" value={value} checked={kind===value} onChange={()=>setKind(value as typeof kind)}/>{label}</label>)}</div>
 <label className="block">Work date<input className={field} required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>
 {kind==='punch'&&<label className="block">Punch type<select className={field} value={punch} onChange={e=>setPunch(e.target.value)}>{[['CLOCK_IN','Clock In'],['START_BREAK','Break Start'],['END_BREAK','Break End'],['CLOCK_OUT','Clock Out']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
 {kind!=='absence'&&<><label className="block">{kind==='early'?'Requested clock-out time':kind==='late'?'Expected arrival time':'Correct punch time'} (Philippine time)<input className={field} type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label><label className="flex gap-2"><input type="checkbox" checked={nextDay} onChange={e=>setNextDay(e.target.checked)}/>Time is on the following day (overnight shift)</label></>}
 <label className="block">Reason category<select className={field} value={category} onChange={e=>setCategory(e.target.value)}>{['Sickness','Emergency','Personal matter','Transportation or travel issue','Other'].map(v=><option key={v}>{v}</option>)}</select></label>
 <label className="block">Short explanation<textarea className={field} required minLength={3} maxLength={1000} rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label>
 <label className="block">Attachment (optional, up to 10 MB)<input className={field} type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>{setFile(e.target.files?.[0]||null);path.current='';}}/></label>
 {kind==='absence'&&<label className="flex items-start gap-3"><input className="mt-1" type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm that I am unable to report for the scheduled shift.</label>}
 {initial&&<label className="flex gap-3"><input type="checkbox" required checked={changesConfirmed} onChange={e=>setChangesConfirmed(e.target.checked)}/>I have reviewed and confirm these changes. Resubmit this same request for approval.</label>}<p className="text-sm text-slate-600 dark:text-slate-300">This is sent to your active direct manager. If no manager is assigned, HR will receive it for review.</p></fieldset>
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800 dark:bg-red-950 dark:text-red-200">{error} Your entry has been retained. Correct it and retry.</p>}
 <button type="submit" disabled={busy||(!!initial&&!changesConfirmed)} className="min-h-14 w-full rounded-xl bg-violet-600 p-3 font-semibold text-white disabled:opacity-50">{busy?'Submitting…':initial?'Resubmit for Approval':error?'Retry submission':'Submit for approval'}</button></form></Modal>;
}
