import React,{useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {AttendanceIssue,attendanceChanged,caseStates,issueLabels,issueRpc,manila,shiftText} from '../../services/attendanceIssues';
import {supabase} from '../../services/supabaseClient';
import {EligibleNTEApprover,fetchEligibleNTEApprovers} from '../../services/nteService';
import {fetchMemos} from '../../services/memoService';
const input='mt-1 w-full rounded-xl border border-slate-300 bg-white p-3 text-slate-900 dark:border-slate-600 dark:bg-slate-900 dark:text-white';
const button='min-h-11 rounded-xl border border-slate-300 px-4 py-2 font-semibold dark:border-slate-600 disabled:opacity-50';
const checks:Record<string,string>={irReviewed:'I reviewed the Incident Report.',timelineComplete:'The factual timeline is complete.',clarificationsConsidered:'I considered the employee’s clarification and attachments.',reasonDocumented:'The reason for issuing the NTE is documented.',policySelected:'The applicable policy or rule is selected.',deadlineCorrect:'The response deadline is correct.',contentReviewed:'I reviewed the complete NTE content as an authorized HR user.'};
export function PrivateAttachment({path}:{path:string}){const [error,setError]=useState('');return <><button className={button} onClick={async()=>{try{const {data,error}=await supabase.storage.from('attendance-issue-files').createSignedUrl(path,60);if(error)throw error;window.open(data.signedUrl,'_blank','noopener,noreferrer');}catch(e){setError((e as Error).message);}}}>Open private attachment</button>{error&&<p role="alert">{error}</p>}</>;}
function Snapshot({value}:{value:any}){if(!value?.work_date)return null;return <dl className="mt-2 space-y-1 text-sm"><div>Date: {value.work_date}</div><div>Scheduled shift: {shiftText(value.schedule)}</div><div>Reason: {value.category}</div><div className="whitespace-pre-wrap">Explanation: {value.explanation}</div>{value.requested_time&&<div>Requested time: {manila(value.requested_time)}</div>}{value.attachment&&<PrivateAttachment path={value.attachment}/>}</dl>;}
export default function AttendanceCasePanel({request,onChanged}:{request:AttendanceIssue;onChanged:()=>void}){
 const [data,setData]=useState<any>();const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const guard=useRef(false);
 const [action,setAction]=useState('close');const [reason,setReason]=useState('');const [deadline,setDeadline]=useState('');const [approveAttendance,setApproveAttendance]=useState(false);
 const [facts,setFacts]=useState('');const [allegation,setAllegation]=useState('');const [body,setBody]=useState('');const [policyIds,setPolicyIds]=useState<string[]>([]);const [memos,setMemos]=useState<any[]>([]);
 const [approvers,setApprovers]=useState<EligibleNTEApprover[]>([]);const [selected,setSelected]=useState<Record<string,string>>({});const [confirmed,setConfirmed]=useState<Record<string,boolean>>({});
 const [file,setFile]=useState<File|null>(null);const [link,setLink]=useState('');const upload=useRef('');
 const load=async()=>{const d=await issueRpc('get_attendance_case',{p_id:request.id});setData(d);return d;};
 useEffect(()=>{let active=true;issueRpc('get_attendance_case',{p_id:request.id}).then(d=>{if(!active)return;setData(d);const draft=d.case?.nte_draft;if(draft){setFacts(draft.facts||'');setAllegation(draft.allegation||'');setBody(draft.body||'');setPolicyIds(draft.policyIds||[]);setReason(draft.rationale||'');setDeadline(draft.deadline?new Date(Date.parse(draft.deadline)+8*3600000).toISOString().slice(0,16):'');}else if(d.canNTE&&d.case?.facts){const f=d.case.facts;const timeline=[`${f.employeeName} · ${f.employeeCode} · ${f.businessUnit}`,`${issueLabels[request.kind]} · ${request.work_date}`,`Scheduled shift: ${shiftText(f.request.schedule)}`,`Employee explanation: ${f.request.explanation}`,`Manager’s recorded reason: ${f.rejectionCategory}`,`Manager comments: ${f.managerComments}`].join('\n');setFacts(timeline);setBody('Notice to Explain — Draft for HR Review\n\n'+timeline+'\n\nPlease provide your written explanation of the facts and proposed allegation reviewed by HR. No conclusion has been made.');}if(d.canNTE&&d.case){Promise.all([fetchMemos(),fetchEligibleNTEApprovers(d.case.incident_id,request.employee_id)]).then(([m,a])=>{if(active){setMemos(m);setApprovers(a);}}).catch(e=>{if(active)setError(e.message);});}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[request.id,request.revision]);
 const run=async(a:string)=>{if(guard.current)return;guard.current=true;setBusy(true);setError('');try{
 if(a==='respond'&&file&&!upload.current){if(file.size>10485760||!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Use a PDF, JPG, PNG or WebP file up to 10 MB.');const auth=await supabase.auth.getUser();if(!auth.data.user)throw new Error('Please sign in again.');const p=`${auth.data.user.id}/${request.id}/${crypto.randomUUID()}`;const result=await supabase.storage.from('attendance-issue-files').upload(p,file);if(result.error)throw result.error;upload.current=p;}
 await issueRpc('act_attendance_hr_case',{p_id:request.id,p_revision:data.case.revision,p_action:a,p_data:{reason,deadline:deadline?`${deadline}:00+08:00`:null,approveAttendance,facts,allegation,body,policyIds,approvers:Object.entries(selected).map(([userId,roleId])=>({userId,roleId,selectionReason:'Selected by HR for attendance NTE review'})),confirmed:confirmed.draft,...confirmed,attachment:upload.current||null,link}});
 setMessage(a==='send_nte'?'NTE sent through the employee response workflow.':a==='submit_nte'?'NTE submitted to designated approvers. It has not been sent to the employee.':'Update recorded successfully.');setConfirmed({});attendanceChanged();await load();onChanged();
 }catch(e){setError((e as Error).message);}finally{guard.current=false;setBusy(false);}};
 const c=data?.case;const closed=c?.state?.startsWith('closed');
 return <section className="mt-5 space-y-5 border-t border-slate-200 pt-5 dark:border-slate-600">{error&&<p role="alert" className="text-red-700 dark:text-red-300">{error} <button className="underline" onClick={()=>load().catch(e=>setError(e.message))}>Refresh</button></p>}{message&&<p role="status" className="text-emerald-700 dark:text-emerald-300">{message}</p>}
 {c&&<><h3 className="text-xl font-bold">{caseStates[c.state]||c.state}</h3>{!closed&&!['nte_sent','nte_response_received'].includes(c.state)&&<p className="rounded-xl border border-amber-400 p-4">No conclusion has been made. This record is pending HR review. Attendance remains unapproved.</p>}{c.decision&&<p>HR decision: {c.decision}</p>}{c.question&&<div className="rounded-xl bg-violet-50 p-4 dark:bg-violet-950"><strong>HR clarification</strong><p className="whitespace-pre-wrap">{c.question}</p><p>Response deadline: {manila(c.response_due)}</p></div>}
 {data.canHR&&c.facts&&<details><summary className="font-semibold">Incident Report draft — factual source at rejection</summary><div className="mt-3 grid gap-4 md:grid-cols-2"><div><p>{c.facts.employeeName} · {c.facts.employeeCode}</p><p>{c.facts.businessUnit} · {c.facts.department}</p><p>Source: {c.facts.source} · GC report status: {c.facts.gcReportStatus}</p><Snapshot value={c.facts.request}/></div><div><p>Rejection reason: {c.facts.rejectionCategory}</p><p className="whitespace-pre-wrap">{c.facts.managerComments}</p><h4 className="mt-3 font-semibold">Original punches at review</h4>{c.facts.punches?.original?.length?c.facts.punches.original.map((p:any,i:number)=><p key={i}>{p.type.replaceAll('_',' ')} · {manila(p.timestamp)}</p>):<p>No punch records recorded at rejection.</p>}<p className="mt-3 text-sm">Incident reference: {c.incident_id}</p></div></div></details>}
 {data.responses?.map((r:any,i:number)=><div className="rounded-xl border p-4" key={i}><strong>Employee clarification · {manila(r.at)}</strong><p className="whitespace-pre-wrap">{r.message}</p>{r.attachment&&<PrivateAttachment path={r.attachment}/>} {r.link&&/^https:\/\//.test(r.link)&&<a className="underline" href={r.link} target="_blank" rel="noopener noreferrer">Supporting link</a>}</div>)}
 {request.isOwn&&c.state==='employee_clarification'&&<div className="space-y-3"><h4 className="font-bold">Submit your explanation to HR</h4><label className="block">Written explanation<textarea className={input} maxLength={4000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="block">Supporting document<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className={input} onChange={e=>{setFile(e.target.files?.[0]||null);upload.current='';}}/></label><label className="block">Supporting link (optional)<input type="url" className={input} value={link} onChange={e=>setLink(e.target.value)}/></label><button disabled={busy||reason.trim().length<3} className={button+' bg-violet-600 text-white'} onClick={()=>void run('respond')}>Submit Explanation to HR</button></div>}
 {data.canHR&&!closed&&!['nte_sent','nte_response_received'].includes(c.state)&&<div className="rounded-xl border border-violet-300 p-4 dark:border-violet-700"><h4 className="text-lg font-bold">HR decision</h4>{c.state==='employee_clarification'?<p>Awaiting the employee’s response. The NTE decision is paused.</p>:<fieldset disabled={busy} className="mt-3 space-y-4">
 {!c.nte_id&&<><label className="block">Action<select className={input} value={action} onChange={e=>setAction(e.target.value)}><option value="close">Close – No Violation</option><option value="clarify">Request Employee Clarification</option>{data.canNTE&&<option value="draft">{c.nte_draft?'Edit NTE Draft':'Create NTE Draft'}</option>}</select></label><label className="block">{action==='clarify'?'Clarification message':'HR reason / documented rationale'}<textarea className={input} rows={3} maxLength={4000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{action==='close'&&<label className="flex gap-2"><input type="checkbox" checked={approveAttendance} onChange={e=>setApproveAttendance(e.target.checked)}/>Approve the attendance exception and create the Timekeeping overlay. The original schedule is preserved.</label>}
 {(action==='clarify'||action==='draft')&&<label className="block">Response deadline (Philippine time)<input type="datetime-local" className={input} value={deadline} onChange={e=>setDeadline(e.target.value)}/></label>}
 {action==='draft'&&<><p className="rounded-lg border border-amber-400 p-3">Do not send an NTE solely because an attendance request was rejected. Confirm that the facts and company policy support issuing an NTE.</p><label className="block">Verified factual timeline<textarea className={input} rows={4} value={facts} onChange={e=>setFacts(e.target.value)}/></label><label className="block">Proposed allegation — for HR review<textarea className={input} rows={2} value={allegation} onChange={e=>setAllegation(e.target.value)}/></label><label className="block">Applicable policy / memorandum<select multiple className={input} value={policyIds} onChange={e=>setPolicyIds(Array.from(e.target.selectedOptions as HTMLCollectionOf<HTMLOptionElement>,o=>o.value))}>{memos.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label className="block">NTE content<textarea className={input} rows={8} value={body} onChange={e=>setBody(e.target.value)}/></label><details><summary>NTE preview — Draft, Not Sent</summary><div className="mt-3 whitespace-pre-wrap rounded-lg border p-4">{body||'Enter the notice content to preview it.'}</div></details></>}
 <button className={button+' bg-violet-600 text-white'} disabled={reason.trim().length<3||(action==='draft'&&(!facts.trim()||!allegation.trim()))} onClick={()=>void run(action==='draft'&&c.nte_draft?'edit_draft':action)}>{action==='close'?'Close – No Violation':action==='clarify'?'Request Employee Clarification':'Save NTE Draft – Not Sent'}</button></>}
 {c.nte_draft&&!c.nte_id&&<details><summary className="font-bold">Submit saved NTE draft for existing designated approvals</summary><p className="mt-3">Save any edits first. At least one designated BOD approver is required by the existing NTE workflow.</p>{approvers.map(a=><label key={a.id} className="mt-2 block"><input type="checkbox" checked={!!selected[a.id]} onChange={e=>setSelected(prev=>{const next={...prev};if(e.target.checked)next[a.id]=a.preferredRoleId;else delete next[a.id];return next;})}/> {a.name}{selected[a.id]&&<select className={input} value={selected[a.id]} onChange={e=>setSelected({...selected,[a.id]:e.target.value})}>{a.eligibleRoleIds.map((id,i)=><option key={id} value={id}>{a.eligibleRoleLabels[i]||id}</option>)}</select>}</label>)}<label className="my-3 flex gap-2"><input type="checkbox" checked={!!confirmed.draft} onChange={e=>setConfirmed({...confirmed,draft:e.target.checked})}/>I reviewed the saved facts, policy, content and response deadline.</label><button className={button} disabled={!confirmed.draft||!Object.keys(selected).length} onClick={()=>void run('submit_nte')}>Submit NTE for Designated Approvals</button></details>}
 {data.nte&&<><Link className="inline-flex min-h-11 items-center underline" to={'/feedback/nte/'+data.nte.id}>Review NTE {data.nte.number} →</Link><p>{data.nte.status==='Approved'?'Designated approvals completed. Awaiting HR sending.':`NTE status: ${data.nte.status} — Not Sent`}</p>{data.nte.status==='Approved'&&data.canNTE&&<><p className="rounded-lg border border-red-400 p-3">Do not send an NTE solely because an attendance request was rejected. Confirm that the facts and company policy support issuing an NTE.</p><p>Employee response deadline: {manila(data.nte.deadline)}</p><label className="block">Reason for issuance<textarea className={input} value={reason} onChange={e=>setReason(e.target.value)}/></label>{Object.entries(checks).map(([key,label])=><label key={key} className="flex gap-3"><input type="checkbox" checked={!!confirmed[key]} onChange={e=>setConfirmed({...confirmed,[key]:e.target.checked})}/>{label}</label>)}<button className={button+' bg-violet-600 text-white'} disabled={reason.trim().length<3||Object.keys(checks).some(k=>!confirmed[k])} onClick={()=>void run('send_nte')}>HR Approve and Send NTE</button></>}</>}
 </fieldset>}</div>}
 {['nte_sent','nte_response_received'].includes(c.state)&&c.nte_id&&<Link className="inline-flex min-h-11 items-center underline" to={'/feedback/nte/'+c.nte_id}>Open NTE receipt, response and case history →</Link>}</>}
 <details className="rounded-xl border p-4"><summary className="font-bold">Revision history and audit trail</summary>{data?.history?.map((a:any)=><article key={a.id} className="mt-4 border-t pt-3"><strong>{a.action} · Revision {a.revision||'—'}</strong><p className="text-sm">{a.actorName||'System'}{a.roles?.length?' · '+a.roles.join(', '):''} · {manila(a.created_at)}</p><p className="whitespace-pre-wrap">{a.reason}</p>{['submitted','edited and resubmitted'].includes(a.action)&&<div className="grid gap-4 md:grid-cols-2">{a.previous?.work_date&&<section><h5 className="font-semibold">Before</h5><Snapshot value={a.previous}/></section>}<section><h5 className="font-semibold">Submitted values</h5><Snapshot value={a.new_value}/></section></div>}{data.canHR&&['HR case draft','HR case edit_draft'].includes(a.action)&&<details><summary>Saved NTE draft at this revision</summary><p className="whitespace-pre-wrap">{a.new_value?.case?.nte_draft?.body}</p><p>Facts: {a.new_value?.case?.nte_draft?.facts}</p><p>Proposed allegation: {a.new_value?.case?.nte_draft?.allegation}</p></details>}</article>)}</details></section>;
}
