import React,{useEffect,useRef,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {useAttendanceClock} from '../../hooks/useAttendanceClock';
import {AttendanceMissionView} from './AttendanceMission';
import {captureGps,Channels,getChannels} from '../../services/attendanceChannels';
import type {ClockAction} from '../../services/employeeAttendance';
export default function AttendanceClock(){
 const c=useAttendanceClock();const location=useLocation();const [channels,setChannels]=useState<Channels|null>(null);const [method,setMethod]=useState('web');const [site,setSite]=useState('');const [token,setToken]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const preparing=useRef(false);
 useEffect(()=>{let active=true;getChannels().then(v=>{if(!active)return;setChannels(v);setSite(v.sites[0]?.id??'');const scanned=new URLSearchParams(location.hash.slice(1)).get('kiosk');setToken(scanned??'');setMethod(scanned&&v.config.qr_enabled?'qr':v.config.web_allowed?'web':v.config.gps_enabled?'gps':'qr');}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[location.hash]);
 const act=async(action:ClockAction)=>{if(preparing.current||!channels)return;preparing.current=true;setBusy(true);setError('');try{const evidence=method==='gps'?await captureGps(site):method==='qr'?{method:'qr' as const,token:token.trim()}:{method:'web' as const};await c.act(action,evidence);}catch(e){setError((e as Error).message);}finally{preparing.current=false;setBusy(false);}};
 const eligible=c.day?.requiresClock&&c.day.state!=='completed';
 return <>{channels&&eligible&&<div className="mb-4 flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><label className="text-sm font-semibold">Clock method<select disabled={busy||c.busy} value={method} onChange={e=>{setMethod(e.target.value);setError('');}} className="ml-3 min-h-12 rounded-lg border bg-transparent px-3 dark:bg-slate-800">{channels.config.web_allowed&&<option value="web">Web / mobile clock</option>}{channels.config.gps_enabled&&<option value="gps">GPS at work site</option>}{channels.config.qr_enabled&&<option value="qr">Scan kiosk QR</option>}</select></label>{method==='gps'&&<label className="text-sm">Work site<select className="ml-2 min-h-12 rounded-lg border bg-transparent px-3 dark:bg-slate-800" value={site} onChange={e=>setSite(e.target.value)}>{channels.sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}{method==='qr'&&<div className="text-sm"><p>{token?'Kiosk code received. Choose your clock action below.':'Sign in on your phone, then scan the displayed kiosk QR with your phone camera.'}</p><label>Scanned code<input autoComplete="off" className="ml-2 min-h-12 rounded-lg border bg-transparent px-3" value={token} onChange={e=>setToken(e.target.value.trim())} placeholder="QR token"/></label></div>}</div>}
 <AttendanceMissionView day={c.day} elapsed={c.elapsed} busy={busy||c.busy||c.loading||!channels} error={error||c.error} onAction={a=>void act(a)} onRefresh={()=>void c.refresh()}/>
 {channels?.canManage&&<Link className="mb-6 inline-block min-h-11 font-semibold text-violet-600 dark:text-violet-300 underline" to="/payroll/attendance-devices">Set up GPS, QR kiosks & biometric imports</Link>}</>;
}
