import React,{useEffect,useState} from 'react';
import {AttendanceDay,ClockAction,ClockEvent,correctAttendanceDay,getHrAttendanceDay} from '../../services/employeeAttendance';
const field='mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800';
const local=(stamp:string)=>new Date(Date.parse(stamp)+8*3600000).toISOString().slice(0,16);
const AttendanceCorrection: React.FC<{employee:string;date:string;onSaved?:()=>void;proposed?:ClockEvent[]}> = ({employee,date,onSaved,proposed}) => {
 const [day,setDay]=useState<AttendanceDay|null>(null);const [events,setEvents]=useState<{type:ClockAction;value:string}[]>([]);const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{let active=true;setDay(null);setError('');setReason('');if(!employee||!date)return;setBusy(true);getHrAttendanceDay(employee,date).then(d=>{if(active){setDay(d);const values:{type:ClockAction;value:string}[]=d.events.length?d.events.map(e=>({type:e.type,value:local(e.timestamp)})):[{type:'CLOCK_IN',value:''},{type:'START_BREAK',value:''},{type:'END_BREAK',value:''},{type:'CLOCK_OUT',value:''}];for(const ev of proposed??[]){const found=values.find(x=>x.type===ev.type);if(found)found.value=local(ev.timestamp);else values.push({type:ev.type,value:local(ev.timestamp)});}if(!values.some(x=>x.type==='CLOCK_OUT'))values.push({type:'CLOCK_OUT',value:''});values.sort((a,b)=>a.value&&b.value?a.value.localeCompare(b.value):a.value?-1:b.value?1:0);setEvents(values);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[employee,date]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!day)return;setBusy(true);setError('');setMessage('');try{const values:ClockEvent[]=events.filter(x=>x.value).map(x=>({type:x.type,timestamp:`${x.value}:00+08:00`}));await correctAttendanceDay(employee,date,day.revision,values,reason);setDay(await getHrAttendanceDay(employee,date));setMessage('HR correction saved as a new version. Prior records are retained.');setReason('');onSaved?.();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="mt-4 space-y-4">{error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}{message&&<p role="status" className="text-emerald-700 dark:text-emerald-300">{message}</p>}{day&&<><p className="text-sm">Recorded state: <strong>{day.state.replaceAll('_',' ')}</strong> · revision {day.revision}. {day.requiresClock?'Clocking required.':'Schedule-based attendance exemption.'}</p><p className="text-sm">Use verified actual times in Asia/Manila. Original punches remain in the audit trail. Payroll still applies the five-minute grace, unpaid lunch and approved overtime rules.</p>
 <form onSubmit={e=>void save(e)} className="space-y-3"><fieldset disabled={busy} className="space-y-3">{events.map((event,i)=><div key={i} className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Event {i+1}<select aria-label={`Event ${i+1} type`} className={field} value={event.type} onChange={e=>setEvents(prev=>prev.map((x,j)=>i===j?{...x,type:e.target.value as ClockAction}:x))}><option value="CLOCK_IN">Clock In</option><option value="START_BREAK">Take a Break</option><option value="END_BREAK">End Break</option><option value="CLOCK_OUT">Clock Out</option></select></label><label className="text-sm">Recorded time (Manila)<input aria-label={`Event ${i+1} recorded time`} className={field} type="datetime-local" value={event.value} onChange={e=>setEvents(prev=>prev.map((x,j)=>i===j?{...x,value:e.target.value}:x))}/></label></div>)}
 <p className="text-xs text-slate-500">Empty break fields are omitted. Do not invent break or attendance times.</p><label className="block text-sm">Correction reason and supporting reference<textarea className={field} required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="min-h-12 rounded-xl bg-violet-600 px-5 py-3 font-semibold text-white disabled:opacity-50" disabled={!reason.trim()||busy}>Save HR correction version</button></fieldset></form>
 {day.originalEvents&&day.originalEvents.length>0&&<details><summary className="cursor-pointer font-semibold">Original recorded punches</summary>{day.originalEvents.map((e,i)=><p className="mt-2 text-sm" key={i}>{e.type}: {new Date(e.timestamp).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</p>)}</details>}{day.audit&&day.audit.length>0&&<details><summary className="cursor-pointer font-semibold">Correction audit history</summary>{day.audit.map(a=><div key={a.id} className="mt-3 border-t pt-3 text-sm"><p>Revision {a.revision} · {new Date(a.created_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</p><p>{a.reason}</p><p>Recorded by: {a.createdByName??a.created_by}</p>{a.events.map((e,i)=><p key={i}>{e.type}: {new Date(e.timestamp).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</p>)}</div>)}</details>}</>}</div>;
}

export default AttendanceCorrection;
