import React,{useState} from 'react';
import Modal from '../ui/Modal';
import {channelRpc} from '../../services/attendanceChannels';
import type {ClockAction} from '../../services/employeeAttendance';
const field='mt-1 min-h-12 w-full rounded-lg border bg-transparent p-3';
export default function MissedPunchModal({date,initial,onClose}:{date:string;initial:ClockAction;onClose:()=>void}){const [workDate,setDate]=useState(date);const [action,setAction]=useState(initial);const [actual,setActual]=useState('');const [end,setEnd]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [sent,setSent]=useState(false);const [key]=useState(()=>crypto.randomUUID());
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await channelRpc('submit_missed_punch',{p_date:workDate,p_action:action,p_actual:actual+':00+08:00',p_break_end:action==='START_BREAK'&&end?end+':00+08:00':null,p_reason:note,p_key:key});setSent(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Modal acknowledgmentRequestType={sent ? undefined : "AttendanceCorrection"} isOpen onClose={()=>{if(!busy)onClose();}} title="Fix a missed punch" size="md">{sent?<div className="space-y-3 p-4"><p role="status">Sent to your manager for approval. HR will apply approved times through attendance review.</p><p>Continue recording your current clock actions normally.</p><button className="min-h-12 rounded-lg bg-violet-600 px-5 text-white" onClick={onClose}>Done</button></div>:<form onSubmit={e=>void submit(e)} className="space-y-3 p-4"><fieldset disabled={busy} className="space-y-3"><label className="block">Work date<input className={field} type="date" value={workDate} onChange={e=>setDate(e.target.value)} required/></label><label className="block">Missed action<select className={field} value={action} onChange={e=>setAction(e.target.value as ClockAction)}><option value="CLOCK_IN">Clock In</option><option value="START_BREAK">Break start / missed break</option><option value="END_BREAK">End Break</option><option value="CLOCK_OUT">Clock Out</option></select></label><label className="block">Actual time (Manila)<input className={field} type="datetime-local" value={actual} onChange={e=>setActual(e.target.value)} required/></label>{action==='START_BREAK'&&<label className="block">Actual break end, if also missed<input className={field} type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label>}<label className="block">Brief note<textarea className={field} value={note} onChange={e=>setNote(e.target.value)} required minLength={3} maxLength={1000} placeholder="Arrived on site at 8:50 AM, forgot to hit the button."/></label>{error&&<p role="alert" className="text-red-600">{error}</p>}<button className="min-h-14 w-full rounded-xl bg-violet-600 px-4 text-white font-semibold">{busy?'Submitting…':'Submit for Manager Approval'}</button></fieldset></form>}</Modal>;
}
