import React,{useEffect,useState} from 'react';
import {channelRpc,AttendanceDevice} from '../../services/attendanceChannels';
import EmployeePhoto from '../employees/EmployeePhoto';
type Props={devices:AttendanceDevice[];employees:{id:string;name:string}[]};
export default function PunchStationAdmin({devices,employees}:Props){
 const [employee,setEmployee]=useState('');const [badge,setBadge]=useState('');const [pin,setPin]=useState('');const [superPin,setSuperPin]=useState('');const [reason,setReason]=useState('');const [active,setActive]=useState(true);const [link,setLink]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [report,setReport]=useState<any>(null);const [photo,setPhoto]=useState<{id:string;data:string;employee:string}|null>(null);const [workDate,setWorkDate]=useState('');
 const load=async()=>setReport(await channelRpc('punch_station_admin'));
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const field='rounded border bg-white text-slate-900 p-3 min-h-12';
 return <section className="rounded-2xl border bg-white p-5 dark:bg-slate-800 space-y-4"><h2 className="text-2xl font-bold">Punch Station — tablet setup & audit</h2><p>Public badge / ID + PIN clocking with a required audit photo. Configure the ACS ACR1552U in keyboard-emulation mode, with Enter as the terminator. Physical tablet/reader verification is required before rollout.</p>
 {error&&<p role="alert" className="text-red-600">{error}</p>}
 <div className="flex flex-wrap gap-3">{devices.filter(d=>d.active&&d.kind==='qr').map(d=><button className={field} disabled={busy} key={d.id} onClick={()=>run(async()=>{const t=await channelRpc<string>('punch_station_pair',{p_device:d.id});setLink(t);})}>Pair {d.name}</button>)}</div>
 {link&&<div><p>Copy this device credential directly to the signed-out tablet setup screen. Pairing expires after 30 days; re-pairing revokes the prior credential. Do not share publicly.</p><input className={field} type="password" readOnly value={link} aria-label="Pairing credential"/><button className={field} onClick={()=>navigator.clipboard.writeText(link)}>Copy pairing credential</button><button className={field} onClick={()=>setLink('')}>Hide</button></div>}
 <a className="underline" href="/punch-station/" target="_blank" rel="noreferrer">Open Punch Station on a dedicated signed-out browser</a>
 <h3 className="font-bold">Issue / replace badge or reset PIN</h3><p>Use the actual reader output. Replacement revokes the previous badge. A card UID is cloneable: photo review is still required to investigate misuse. Blank PIN fields keep existing PINs. No existing PIN is displayed.</p>
 <div className="grid sm:grid-cols-2 gap-3"><select className={field} value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">Choose employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><input className={field} placeholder="Badge reader output (optional)" value={badge} onChange={e=>setBadge(e.target.value.trim())}/><input className={field} type="password" autoComplete="new-password" placeholder="New personal PIN: 4 digits" value={pin} maxLength={4} onChange={e=>setPin(e.target.value)}/><input className={field} type="password" autoComplete="new-password" placeholder="Separate supervisor PIN: 8–12 digits" value={superPin} maxLength={12} onChange={e=>setSuperPin(e.target.value)}/><input className={field} placeholder="Reason for credential change / review" value={reason} onChange={e=>setReason(e.target.value)}/><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Badge/PIN access enabled</label></div>
 <button className={field} disabled={busy||!employee||reason.trim().length<3} onClick={()=>run(async()=>{await channelRpc('punch_station_credential',{p_employee:employee,p_badge:badge||null,p_pin:pin||null,p_supervisor_pin:superPin||null,p_active:active,p_reason:reason});setBadge('');setPin('');setSuperPin('');})}>Save credential change</button>
 <h3 className="font-bold">Photo review & offline verification — latest 200 captures</h3><p>Offline captures do not enter accepted attendance until reviewed. Check the photo, recorded time, receipt time and shift date. Review in chronological order. Unknown/revoked badges require the existing attendance correction workflow.</p><label>Actual shift work date for offline approval <input className={field} type="date" value={workDate} onChange={e=>setWorkDate(e.target.value)}/></label><button className={field} disabled={busy} onClick={()=>run(load)}>Refresh</button>
 <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr>{['Employee','Action / method','Captured / received','Status','Review'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{report?.captures?.map((r:any)=><tr key={r.id} className="border-t"><td>{r.full_name||'Unknown badge'}</td><td>{r.action}<br/>{r.method}</td><td>{new Date(r.captured_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}<br/>{new Date(r.received_at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</td><td>{r.status}</td><td><button disabled={busy} className={field} onClick={()=>run(async()=>setPhoto({id:r.id,employee:r.employee_id,data:await channelRpc<string>('punch_station_photo',{p_id:r.id})}))}>Review photo</button>{r.status==='Pending HR verification'&&<><button className={field} disabled={busy||!workDate||reason.trim().length<3} onClick={()=>run(()=>channelRpc('punch_station_review',{p_id:r.id,p_approve:true,p_work_date:workDate,p_reason:reason}))}>Approve</button><button className={field} disabled={busy||reason.trim().length<3} onClick={()=>run(()=>channelRpc('punch_station_review',{p_id:r.id,p_approve:false,p_work_date:workDate||null,p_reason:reason}))}>Reject</button></>}</td></tr>)}</tbody></table></div>
 {photo&&<div className="rounded border p-4"><p>Manual comparison only — no automated facial matching.</p><div className="flex items-center gap-8"><img className="max-w-xs" src={'data:image/jpeg;base64,'+photo.data} alt="Punch audit capture"/>{photo.employee&&<EmployeePhoto employeeId={photo.employee} name={employees.find(e=>e.id===photo.employee)?.name||'Employee'}/>}</div><button className={field} onClick={()=>setPhoto(null)}>Close photo</button></div>}
 <details><summary>Recent device attempts</summary>{report?.attempts?.map((a:any,i:number)=><p key={i}>{a.created_at} · {a.reason}</p>)}</details>
 </section>;
}
