import React, { useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { OfferTemplate } from '../../types';
import Button from '../ui/Button';
import OfferTemplateCard from './OfferTemplateCard';

interface Props { open: boolean; templates: OfferTemplate[]; onClose: () => void; onContinue: (template: OfferTemplate | null) => void; }
const OfferTemplatePicker: React.FC<Props> = ({open,templates,onClose,onContinue}) => { const [search,setSearch]=useState(''); const [unit,setUnit]=useState('All'); const [selected,setSelected]=useState<OfferTemplate|null>(null); const filtered=useMemo(()=>templates.filter(item=>item.status==='Active'&&(unit==='All'||item.businessUnit===unit)&&`${item.name} ${item.businessUnit} ${item.category}`.toLowerCase().includes(search.toLowerCase())),[templates,unit,search]); if(!open)return null; return createPortal(<div className="fixed inset-0 z-[70] flex flex-col bg-slate-100"><header className="flex flex-wrap items-center justify-between gap-4 border-b bg-white px-5 py-4"><div><h1 className="text-2xl font-black">Choose an Offer Template</h1><p className="text-sm text-slate-500">The selected template becomes an independent, fully editable offer snapshot.</p></div><button onClick={onClose} className="rounded-xl border px-4 py-2 font-bold">× Close</button></header><div className="border-b bg-white p-4"><div className="mx-auto grid max-w-7xl gap-3 md:grid-cols-2"><input className="rounded-xl border px-4 py-2.5" placeholder="Search templates" value={search} onChange={event=>setSearch(event.target.value)}/><select className="rounded-xl border px-4 py-2.5" value={unit} onChange={event=>setUnit(event.target.value)}><option>All</option>{[...new Set(templates.map(item=>item.businessUnit))].sort().map(item=><option key={item}>{item}</option>)}</select></div></div><main className="flex-1 overflow-y-auto p-5"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-2 xl:grid-cols-3">{filtered.map(template=><OfferTemplateCard key={template.id} template={template} selected={selected?.id===template.id} onUse={()=>setSelected(template)}/>)}</div></main><footer className="sticky bottom-0 border-t bg-white p-4"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3"><button className="text-sm font-bold text-slate-600 underline" onClick={()=>onContinue(null)}>Start Blank</button><div className="flex items-center gap-3"><span className="text-sm text-slate-500">{selected?`Selected: ${selected.name}`:'Select a template to continue'}</span><Button disabled={!selected} onClick={()=>onContinue(selected)}>Continue</Button></div></div></footer></div>,document.body); };
export default OfferTemplatePicker;

