import React from 'react';
import { Offer, OfferBuilderDetails } from '../../types';
import { mergeAppearance } from './offerBranding';
import { formatPHP } from './offerCurrency';

const peso = (value?: number) => formatPHP(value);
const formatDate = (value?: Date | string) => value ? new Date(value).toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' }) : '—';

interface Props {
  offer: Partial<Offer>;
  details: OfferBuilderDetails;
  candidateName: string;
  companyName: string;
  logoUrl?: string;
  previewRef?: React.RefObject<HTMLDivElement | null>;
  page?: number | 'all';
}

const OfferDocument: React.FC<Props> = ({ offer, details, candidateName, companyName, logoUrl, previewRef, page = 'all' }) => {
  const theme = mergeAppearance(companyName, details.appearance);
  const benefits = (details.benefits || []).filter(item => item.included);
  const growth = (details.growthItems || []).filter(item => item.included);
  const responsibilities = (details.responsibilities || []).filter(item => item.label.trim());
  const outcomes = (details.successOutcomes || []).filter(item => item.label.trim());
  const response = (details as any).candidateResponse || {};
  const pages: number[] = page === 'all' ? [1, 2, 3] : [Number(page)];
  const radius = theme.cardStyle === 'Flat' ? '0px' : theme.cardStyle === 'Outlined' ? '10px' : '18px';
  const cardBackground = theme.cardStyle === 'Flat' ? 'transparent' : `${theme.primaryColor}0D`;
  const buttonRadius = theme.buttonStyle === 'Pill' ? '999px' : theme.buttonStyle === 'Square' ? '2px' : '12px';
  const card = { borderRadius: radius, border: `1px solid ${theme.primaryColor}25`, background: cardBackground } as React.CSSProperties;
  const PageShell: React.FC<{ number: number; children: React.ReactNode }> = ({ number, children }) => <article data-offer-page={number} className="offer-page relative mx-auto min-h-[1120px] w-full max-w-5xl overflow-hidden bg-white p-8 shadow-xl sm:p-12 print:min-h-0 print:max-w-none print:shadow-none" style={{ color: theme.textColor, backgroundColor: theme.pageBackgroundColor, fontFamily: theme.fontFamily }}><div className="min-h-[970px]">{children}</div><footer className="mt-8 flex items-center justify-between border-t pt-4 text-xs" style={{ borderColor: `${theme.primaryColor}35`, color: `${theme.textColor}99` }}><span>{theme.footerContent}</span><span>Page {number} of 3</span></footer></article>;
  return <div ref={previewRef} id="offer-document" className="space-y-6" style={{ backgroundColor: `${theme.primaryColor}0A` }}>
    <style>{`@media print { body * { visibility:hidden !important } #offer-document, #offer-document * { visibility:visible !important } #offer-document { position:absolute; inset:0; width:100%; background:white !important } .offer-page { width:210mm !important; min-height:297mm !important; margin:0 !important; break-after:page; box-shadow:none !important } .offer-page:last-child { break-after:auto } }`}</style>
    {pages.includes(1) && <PageShell number={1}>
      <header className="relative overflow-hidden p-7 text-white sm:p-9" style={{ backgroundColor: theme.primaryColor, borderRadius: radius, backgroundImage: theme.backgroundImageUrl ? `linear-gradient(90deg, ${theme.primaryColor}F2, ${theme.primaryColor}A8), url(${theme.backgroundImageUrl})` : undefined, backgroundSize: 'cover', backgroundPosition: 'center' }}><div className="flex flex-wrap items-start justify-between gap-6"><div className="max-w-xl">{logoUrl ? <img src={logoUrl} alt={`${companyName} logo`} className="mb-5 h-14 max-w-[220px] object-contain object-left"/> : <p className="mb-5 text-sm font-black uppercase tracking-[.2em]">{companyName}</p>}<h1 className="text-4xl font-black sm:text-5xl">{theme.offerTitle}</h1><p className="mt-2 text-xl font-bold" style={{ color: theme.accentColor }}>at {companyName}</p><p className="mt-5 text-sm text-white/85">{theme.headerContent}</p></div><div className="min-w-[250px] bg-white/10 p-5 backdrop-blur" style={{ borderRadius: radius }}><p className="text-2xl font-black">{candidateName || 'Candidate name'}</p><p className="font-bold" style={{ color: theme.accentColor }}>{details.jobTitle || 'Job title'}</p><div className="mt-4 space-y-2 text-sm text-white/85"><p>Start date: <b>{formatDate(offer.startDate)}</b></p><p>Location: <b>{details.workLocation || '—'}</b></p><p>Employment: <b>{offer.employmentType || '—'}</b></p></div></div></div></header>
      <p className="my-6 text-sm leading-6">{details.welcomeMessage}</p>
      <div className={`grid gap-4 ${theme.sectionLayout === 'Classic' ? 'md:grid-cols-1' : 'md:grid-cols-3'}`}><section className="p-5" style={card}><h2 className="text-lg font-black" style={{ color: theme.primaryColor }}>What you earn</h2><p className="mt-4 text-3xl font-black" style={{ color: theme.primaryColor }}>{peso(details.grossMonthlySalary || offer.basePay)}</p><p className="text-xs opacity-60">gross monthly salary</p><hr className="my-4"/><p className="text-xl font-bold">{peso(details.grossAnnualizedSalary)}</p><p className="text-xs opacity-60">annualized salary</p></section><section className="p-5" style={card}><h2 className="text-lg font-black" style={{ color: theme.primaryColor }}>What you receive</h2><ul className="mt-4 space-y-2 text-sm">{benefits.slice(0, 8).map(item => <li key={item.id}>● <b>{item.name}</b>{item.value ? ` — ${item.value}` : ''}</li>)}</ul></section><section className="p-5" style={card}><h2 className="text-lg font-black" style={{ color: theme.primaryColor }}>Where you can grow</h2><ul className="mt-4 space-y-2 text-sm">{growth.slice(0, 6).map(item => <li key={item.id}>● <b>{item.name}</b><span className="block pl-3 text-xs opacity-65">{item.description}</span></li>)}</ul></section></div>
      <section className="mt-6 p-5" style={card}><h2 className="text-xl font-black">Your Role</h2><div className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><p><b>Position</b><br/>{details.jobTitle || '—'}</p><p><b>Department</b><br/>{details.department || '—'}</p><p><b>Reports to</b><br/>{details.reportingManager || '—'}</p><p><b>Work arrangement</b><br/>{details.workSetup || '—'} · {details.workLocation || '—'}</p><p><b>Schedule</b><br/>{details.workScheduleDays || '—'} · {details.workScheduleHours || '—'}</p><p><b>Business unit</b><br/>{companyName}</p></div></section>
    </PageShell>}
    {pages.includes(2) && <PageShell number={2}>
      <h1 className="text-3xl font-black" style={{ color: theme.primaryColor }}>Your Role and Success Plan</h1><section className="mt-6 p-6" style={card}><h2 className="text-xl font-black">Role Purpose</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{details.rolePurpose || 'To be discussed with your manager.'}</p></section>
      <div className="mt-6 grid gap-6 md:grid-cols-2"><section className="p-6" style={card}><h2 className="text-xl font-black">Key Responsibilities</h2><ol className="mt-4 list-decimal space-y-3 pl-5 text-sm leading-6">{responsibilities.map(item => <li key={item.id}>{item.label}{item.notes && <span className="block text-xs opacity-60">{item.notes}</span>}</li>)}</ol></section><section className="p-6" style={card}><h2 className="text-xl font-black">What Success Looks Like</h2><ul className="mt-4 space-y-3 text-sm leading-6">{outcomes.map(item => <li key={item.id}>✓ {item.label}</li>)}</ul></section></div>
      <section className="mt-6 p-6" style={card}><h2 className="text-xl font-black">Your First 90 Days</h2><div className="mt-5 grid gap-5 md:grid-cols-3">{(['30','60','90'] as const).map(day => <div key={day}><p className="font-black" style={{ color: theme.primaryColor }}>First {day} Days</p><p className="mt-2 text-sm">{details.milestones?.[day]?.description || 'Milestone to be discussed.'}</p>{details.milestones?.[day]?.successCriteria && <p className="mt-2 text-xs opacity-60">Success: {details.milestones[day].successCriteria}</p>}</div>)}</div></section>
    </PageShell>}
    {pages.includes(3) && <PageShell number={3}>
      <h1 className="text-3xl font-black" style={{ color: theme.primaryColor }}>Your Complete Package</h1><div className="mt-6 grid gap-6 md:grid-cols-2"><section className="p-6" style={card}><h2 className="text-xl font-black">What You Earn</h2><div className="mt-4 grid gap-4 text-sm"><p><b>Monthly salary</b><br/>{peso(details.grossMonthlySalary || offer.basePay)}</p><p><b>Annualized salary</b><br/>{peso(details.grossAnnualizedSalary)} annualized</p><p><b>Probationary salary</b><br/>{peso(details.probationarySalary)}</p><p><b>Regularization salary</b><br/>{peso(details.regularizationSalary)}</p><p><b>Incentive eligibility</b><br/>{details.commissionOrIncentive || 'None specified'}</p><p><b>Bonus eligibility</b><br/>{details.bonusEligibility || 'Subject to policy and eligibility'}</p>{(details.allowances || []).filter(item => item.name).map(item => <p key={item.id}><b>{item.name}</b><br/>{peso(item.amount)} {item.guaranteed ? 'guaranteed' : 'estimated'}</p>)}</div></section><section className="p-6" style={card}><h2 className="text-xl font-black">Benefits & Growth</h2><ul className="mt-4 space-y-3 text-sm">{benefits.map(item => <li key={item.id}>✓ <b>{item.name}</b>{item.value ? ` — ${item.value}` : ''}{item.eligibility && <span className="block pl-4 text-xs opacity-60">Eligibility: {item.eligibility}</span>}</li>)}</ul><h3 className="mt-6 font-black">Growth opportunities</h3><ul className="mt-3 space-y-2 text-sm">{growth.map(item => <li key={item.id}>• <b>{item.name}</b> — {item.description}</li>)}</ul></section></div>
      <p className="mt-5 text-xs opacity-60">Bonuses, incentives, and estimated compensation depend on company policy, eligibility, and/or performance unless expressly stated otherwise.</p>
      <section id="candidate-response" className="mt-6 p-6" style={card}><h2 className="text-xl font-black">Next Steps</h2><p className="mt-2 text-sm">Please respond by <b>{formatDate(offer.offerExpirationDate)}</b>.</p><div className="mt-5 flex flex-wrap gap-3"><a href="#candidate-actions" className="px-6 py-3 font-bold text-white" style={{ backgroundColor: theme.primaryColor, borderRadius: buttonRadius }}>Accept Offer</a><a href="#candidate-actions" className="border px-6 py-3 font-bold" style={{ borderColor: theme.primaryColor, color: theme.primaryColor, borderRadius: buttonRadius }}>Decline Offer</a><a className="px-6 py-3 font-bold" style={{ color: theme.primaryColor }} href="mailto:recruitment@thenextperience.com">Ask a Question</a></div><div className="mt-8 grid gap-5 border-t pt-5 text-sm sm:grid-cols-2" style={{ borderColor: `${theme.primaryColor}35` }}><p>Candidate signature: <b>{response.signatureName || offer.signatureName || '____________________'}</b></p><p>Signature date: <b>{formatDate(response.respondedAt || offer.signedAt)}</b></p></div>{offer.status === 'Signed' && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">Offer accepted and signed</p>}</section>
    </PageShell>}
  </div>;
};

export default OfferDocument;
