import {configured,env,rpc,sendResend,serviceClient,validEmail} from '../../server/approvalEmail.js';
export const config={maxDuration:60};
export default async function handler(req:any,res:any){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).end();const token=req.headers['x-attendance-worker'];if(typeof token!=='string'||!/^[0-9a-f-]{36}$/.test(token))return res.status(401).end();
 const db=serviceClient();try{if(!await rpc(db,'validate_attendance_worker',{p_token:token}))return res.status(401).end();if(!configured())return res.status(503).json({error:'Email configuration incomplete; deliveries retained for retry'});
 let sent=0,failed=0;const deadline=Date.now()+40000;while(Date.now()<deadline){let c=await rpc(db,'claim_attendance_issue_email');let pulse=false;if(!c){c=await rpc(db,'claim_attendance_pulse_email');pulse=true;}let correspondence=false;if(!c){c=await rpc(db,'claim_case_correspondence_email');correspondence=true;}if(!c)break;if(c.skipped)continue;let provider=null,error=null;try{const p=c.payload;if(!validEmail(p.email))throw new Error('Recipient email unavailable');if(correspondence){const url=new URL('/case-questions?case='+p.caseId,env('APP_BASE_URL')).toString();provider=await sendResend({from:env('APPROVAL_EMAIL_FROM'),to:[p.email],subject:'HRIS: Private case update',text:`You have a private case update in HRIS. Sign in to review the questions, response deadline, or case status.\n\nOpen secure case: ${url}\n\nThis email contains no case details or internal HR notes.`},'case-correspondence-'+c.id);}else if(pulse){const url=new URL('/payroll/attendance-pulse?date='+p.date,env('APP_BASE_URL')).toString();const late=p.summaryType==='late';const subject=late?`Late attendance summary — ${p.date}`:`${p.event} — ${p.date}`;const intro=late?`Reports submitted after the previous 11:00 AM pulse are summarized here so late-opening units are not missed.`:`This is the 11:00 AM Philippine-time attendance pulse for reports requiring attention.`;const concerns=(p.concerns||[]).map((c:any)=>c.text).filter(Boolean);provider=await sendResend({from:env('APPROVAL_EMAIL_FROM'),to:[p.email],subject,text:`Attendance pulse · ${p.date} (Philippine time)\n${p.scope}\n${intro}\n${p.reported} employees reported unable to work\n${p.approved} approved · ${p.pending} pending · ${p.attention} need attention\n${(p.units||[]).map((b:any)=>b.name+': '+b.count+' reports').join('\n')}${concerns.length?'\n\n'+concerns.join('\n'):''}\n\nReview reports and impacted schedules: ${url}\n\nReports are not approved absences. Sign in to view your authorized staffing scope.`},'attendance-pulse-'+c.id);
}else{const url=new URL('/payroll/attendance-requests?review='+p.requestId,env('APP_BASE_URL')).toString();const labels:Record<string,string>={absence:'Unable to report to work',early:'Early out',late:'Late arrival',punch:'Missed punch'};const shift=(p.schedule?.entries||[]).map((s:any)=>s.kind==='work'?s.start+'–'+s.end:s.name||s.kind).join(' · ')||'Schedule not yet published';
 provider=await sendResend({from:env('APPROVAL_EMAIL_FROM'),to:[p.email],subject:`Attendance: ${p.event} — ${labels[p.kind]}`,text:`${p.employeeName}\n${labels[p.kind]} · ${p.date}\nScheduled shift: ${shift} (Philippine time)\nReason: ${p.category}\n${p.explanation}\n${p.reviewMessage?'Review message: '+p.reviewMessage+'\n':''}Status: ${p.status}\n${p.attachment?'Private attachment: open the authenticated request below.\n':''}\nReview request: ${url}\n\nSign in to review. This email cannot approve a request. Payroll and leave treatment remain subject to HR review.`},'attendance-issue-'+c.id);}
 }catch(e){error=(e as Error).message;}await rpc(db,correspondence?'finish_case_correspondence_email':pulse?'finish_attendance_pulse_email':'finish_attendance_issue_email',{p_id:c.id,p_token:c.token,p_provider:provider,p_error:error});if(provider)sent++;else failed++;await new Promise(resolve=>setTimeout(resolve,600));}return res.status(200).json({sent,failed});
 }catch{return res.status(503).json({error:'Delivery worker could not complete; queued messages will retry'});}}
