import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import Modal from '../components/ui/Modal';
import TemplateEditor from '../modules/operations/TemplateEditor';
import AssignmentEditor from '../modules/operations/AssignmentEditor';
import ChecklistImport from '../modules/operations/ChecklistImport';
import { exportChecklistSample } from '../modules/operations/checklistImport';
import AutomationWorkspace from '../modules/operations/AutomationWorkspace';
import MaintenanceWorkspace from '../modules/operations/MaintenanceWorkspace';
import AssignmentDetail from '../modules/operations/AssignmentDetail';
import { getOperationsWorkspace, operationsRpc } from '../modules/operations/service';
import { filters, matchesFilter, formatDue, isOpen, manilaDay, safeUrl, assignmentTitle, assignmentSearchText } from '../modules/operations/presentation';
import type { OpsFilter } from '../modules/operations/presentation';
import type { OpsWorkspace, OpsTemplate, OpsKind, OpsAssignment } from '../modules/operations/types';
import { OpsIcon, buttonClass, primaryClass, inputClass } from '../modules/operations/ui';

const mainTabs=['Today','Progress','Tasks','Settings'];
const managerTabs=['Task Library','Checklist Library','Create Checklist','Assign Tasks','Scheduling','Team Progress'];
export default function OperationsStation() {
  const {user}=useAuth();
  const [searchParams,setSearchParams]=useSearchParams();
  const tab=searchParams.get('view')||'Today';
  const [unit,setUnit]=useState(''),[data,setData]=useState<OpsWorkspace|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [collapsed,setCollapsed]=useState(false),[filter,setFilter]=useState<OpsFilter>('Due Today'),[team,setTeam]=useState(false),[query,setQuery]=useState(''),[libraryFilter,setLibraryFilter]=useState('All');
  const [editor,setEditor]=useState<{kind:OpsKind;template?:OpsTemplate}|null>(null),[assign,setAssign]=useState<string|null>(null),[detail,setDetail]=useState<OpsAssignment|null>(null),[versionHistory,setVersionHistory]=useState<OpsTemplate|null>(null),[busy,setBusy]=useState(false);
  const [importing,setImporting]=useState(false);
  const [delegateId,setDelegateId]=useState(''),[delegateCreate,setDelegateCreate]=useState(false),[delegateAssign,setDelegateAssign]=useState(false);
  const loadSeq=useRef(0);
  const initialActor=useRef('');
  const detailRun=detail?.checklist_run_id;
  const preferenceKey=`tng-operations-unit:${user?.id||''}`;
  const selection=data?.units.find(u=>u.id===unit);
  const canEdit=!!(unit?selection?.edit:data?.masterAdmin);
  const canAssign=!!(unit&&selection?.assign);
  const canManage=!!(unit&&selection?.manage);
  const hasTeam=!!data?.assignments.some(a=>a.assignee_id!==data.actor)||!!selection?.manage||!!selection?.assign;
  const hasCreationAccess=!!data?.masterAdmin||!!data?.units.some(u=>u.edit);
  const hasAssignmentAccess=!!data?.units.some(u=>u.assign);
  const workspaceTools=managerTabs.filter(x=>(x!=='Create Checklist'||hasCreationAccess)&&(x!=='Assign Tasks'||hasAssignmentAccess));
  const hasLibraries=!!data?.masterAdmin||!!data?.units.some(u=>u.edit||u.assign);
  const canMaster=!!data?.masterAdmin;
  const load=useCallback(async(silent=false)=>{
    const seq=++loadSeq.current;if(!silent){setLoading(true);setError('');}
    try {const next=await getOperationsWorkspace(unit);if(seq===loadSeq.current){setData(next);setError('');if(initialActor.current!==next.actor){initialActor.current=next.actor;if(next.masterAdmin)setTeam(true);}}}
    catch(e){if(seq===loadSeq.current){setError((e as Error).message);if(!silent)setData(null);}}
    finally{if(seq===loadSeq.current)setLoading(false);}
  },[unit,user?.id]);
  useEffect(()=>{setData(null);void load();return()=>{loadSeq.current++;};},[load]);
  useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')void load(true);};window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[load]);
  useEffect(()=>{if(!detailRun&&!['Today','Tasks'].includes(tab))return;const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load(true);},detailRun?15000:30000);return()=>window.clearInterval(timer);},[detailRun,tab,load]);
  useEffect(()=>{try {const saved=localStorage.getItem(preferenceKey);if(saved)setUnit(saved);}catch{/* Preferences do not affect permissions. */}},[preferenceKey]);
  function switchUnit(next:string){setUnit(next);setDetail(null);setEditor(null);setAssign(null);setImporting(false);setVersionHistory(null);setQuery('');setDelegateId('');setMessage('');try{localStorage.setItem(preferenceKey,next);}catch{}}
  function navigate(next:string){setSearchParams({view:next});setQuery('');setFilter(next==='Today'?'Due Today':'All');setMessage('');}
  async function mutation(name:string,args:Record<string,unknown>,success:string){setBusy(true);setError('');try{await operationsRpc(name,args);await load();setMessage(success);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const assignments=useMemo(()=>{const rows=data?.assignments||[];const seen=new Set<string>();return [...rows].sort((a,b)=>Number(b.assignee_id===data?.actor)-Number(a.assignee_id===data?.actor)).filter(a=>{const key=a.checklist_run_id||a.id;if(seen.has(key))return false;seen.add(key);return true;});},[data]);
  const scoped=useMemo(()=>assignments.filter(a=>(team||tab==='Team Progress'||tab==='Scheduling'||tab==='Progress')||a.assignee_id===data?.actor),[assignments,team,tab,data?.actor]);
  const visible=useMemo(()=>scoped.filter(a=>matchesFilter(a,filter)&&assignmentSearchText(a).includes(query.toLowerCase())),[scoped,filter,query]);
  const open=assignments.filter(isOpen),completed=assignments.filter(a=>a.status==='Completed'),total=assignments.filter(a=>a.status!=='Cancelled').length;
  const completion=total?Math.round(completed.length/total*100):0;
  const libraryKind:OpsKind=tab==='Checklist Library'?'checklist':'task';
  const library=(data?.templates||[]).filter(t=>t.kind===libraryKind&&(libraryFilter==='All'||t.status===libraryFilter)&&(t.draft.title||'').toLowerCase().includes(query.toLowerCase()));
  const title=tab==='Today'?'Let’s get things done.':tab;
  const navigateManager=(next:string)=>{
    if(next==='Create Checklist'){if(canEdit)setEditor({kind:'checklist'});else {navigate('Checklist Library');setMessage('Select an authorized business-unit workspace to create a checklist.');}}
    else if(next==='Assign Tasks'){if(canAssign)setAssign('');else {navigate('Tasks');setMessage('Select an authorized business-unit workspace to assign work.');}}
    else navigate(next);
  };
  const allowedTabs=['Maintenance','Coverage',...mainTabs,...(hasLibraries?workspaceTools:hasTeam?['Scheduling','Team Progress']:[])];
  const knownTab=allowedTabs.includes(tab);
  return <div className="overflow-hidden rounded-3xl border border-slate-200 bg-[#fdfcfa] text-slate-800 shadow-sm dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100">
    <div className="flex min-h-[calc(100dvh-12rem)]">
      <aside className={`hidden shrink-0 border-r border-slate-200 bg-white px-3 py-6 transition-all lg:block dark:border-slate-700 dark:bg-slate-900 ${collapsed?'w-20':'w-56'}`}>
        <button type="button" aria-label={collapsed?'Expand workspace sidebar':'Collapse workspace sidebar'} className={`${buttonClass} mb-7`} onClick={()=>setCollapsed(!collapsed)}><OpsIcon name="menu"/></button>
        <nav aria-label="Operations desktop navigation" className="space-y-2">{mainTabs.map(x=><button key={x} title={collapsed?x:undefined} aria-current={tab===x?'page':undefined} className={`flex min-h-12 w-full items-center gap-3 rounded-2xl px-4 text-sm font-semibold ${tab===x?'bg-violet-100 text-violet-800 dark:bg-violet-900/40 dark:text-violet-200':'hover:bg-slate-50 dark:hover:bg-slate-800'}`} onClick={()=>navigate(x)}><OpsIcon name={x}/>{!collapsed&&x}</button>)}
          {(hasLibraries||hasTeam)&&<div className="!mt-8 space-y-1 border-t border-slate-100 pt-5 dark:border-slate-700">{!collapsed&&<p className="mb-3 px-4 text-[10px] font-bold uppercase tracking-[.2em] text-slate-400">Workspace tools</p>}{(hasLibraries?workspaceTools:['Scheduling','Team Progress']).map(x=><button key={x} title={collapsed?x:undefined} className={`flex min-h-11 w-full items-center gap-3 rounded-xl px-4 text-left text-sm ${tab===x?'bg-violet-50 font-semibold text-violet-800 dark:bg-violet-900/40 dark:text-violet-200':'hover:bg-slate-50 dark:hover:bg-slate-800'}`} onClick={()=>navigateManager(x)}><OpsIcon name={x.includes('Library')?'library':'Tasks'}/>{!collapsed&&x}</button>)}</div>}
          <button title="Maintenance" className={`${buttonClass} mt-4 flex w-full items-center gap-3 text-left`} onClick={()=>navigate('Maintenance')}><OpsIcon name="Tasks"/>{!collapsed&&'Maintenance'}</button>
        </nav>
      </aside>
      <section className="min-w-0 flex-1 pb-24 lg:pb-10">
        <header className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 px-5 py-6 sm:px-8 dark:border-slate-700">
          <div><p className="text-xs font-semibold uppercase tracking-[.2em] text-violet-600 dark:text-violet-300">The Nextperience Group</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-violet-800 sm:text-3xl dark:text-violet-200">Operations Station</h1></div>
          <div className="flex flex-wrap gap-2"><select aria-label="Business-unit workspace" className={`${inputClass} max-w-60`} value={unit} onChange={e=>switchUnit(e.target.value)}><option value="">All workspaces</option>{data?.units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><button className={buttonClass} disabled={loading||busy} onClick={()=>void load()}>Refresh</button></div>
        </header>
        <div className="space-y-6 px-5 py-6 sm:px-8">
          {message&&<p role="status" className="rounded-xl bg-violet-50 p-3 text-sm text-violet-800 dark:bg-violet-950/40 dark:text-violet-200">{message}</p>}
          {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-800 dark:bg-red-950/30 dark:text-red-200"><p>{error}</p><button className="mt-2 underline" onClick={()=>unit?switchUnit(''):void load()}>Retry / reset workspace</button></div>}
          {loading?<p role="status" className="py-16 text-center text-slate-500">Loading your authorized workspace…</p>:data&&<>
            <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">{knownTab?title:'Choose a workspace view'}</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{selection?.name||'All authorized business units'} · {manilaDay(new Date())} · Manila time</p></div>{(canEdit||canAssign)&&<div className="flex flex-wrap gap-2">{canEdit&&<button className={buttonClass} onClick={()=>setEditor({kind:'task'})}>Create task</button>}{canAssign&&<button className={primaryClass} onClick={()=>setAssign('')}>Assign work</button>}</div>}</div>
            {(hasLibraries||hasTeam)&&<nav aria-label="Operations workspace tools" className="flex gap-2 overflow-x-auto pb-1 lg:hidden">{(hasLibraries?workspaceTools:['Scheduling','Team Progress']).map(x=><button className={`${buttonClass} shrink-0 ${tab===x?'border-violet-400 text-violet-700':''}`} key={x} onClick={()=>navigateManager(x)}>{x}</button>)}</nav>}
            {!knownTab&&<button className={primaryClass} onClick={()=>navigate('Today')}>Open Today</button>}
            {['Scheduling','Coverage'].includes(tab)&&<AutomationWorkspace workspace={data} unit={unit} rulesView={tab==='Scheduling'} onNavigate={navigate} onOpen={async id=>{const next=await getOperationsWorkspace(unit);setData(next);const row=next.assignments.find(a=>a.id===id);if(!row)throw new Error('Assignment is unavailable; refresh coverage');setDetail(row);}}/>}
            {tab==='Maintenance'&&<MaintenanceWorkspace key={unit} workspace={data} unit={unit} onNavigate={navigateManager} onRefresh={()=>load(true)} onOpen={async id=>{const next=await getOperationsWorkspace(unit);setData(next);const row=next.assignments.find(a=>a.id===id);if(!row)throw new Error('Assignment is unavailable; refresh maintenance');setDetail(row);}}/>}
            {tab!=='Maintenance'&&<button className={`${buttonClass} lg:hidden`} onClick={()=>navigate('Maintenance')}>Maintenance</button>}
            {tab==='Today'&&<button className={buttonClass} onClick={()=>navigate('Coverage')}>Today’s coverage & responsibility</button>}
            {['Today','Tasks'].includes(tab)&&<>
              {tab==='Today'&&canMaster&&<section className="rounded-2xl border border-violet-100 bg-violet-50 p-5 dark:border-slate-700 dark:bg-violet-950/30"><h3 className="font-semibold">Work assigned to Business Unit Managers</h3><p className="mt-1 text-sm text-slate-500">{assignments.filter(a=>a.assignee_is_bum&&isOpen(a)).length} outstanding · {assignments.filter(a=>a.assignee_is_bum&&matchesFilter(a,'Overdue')).length} overdue</p><div className="mt-3 space-y-2">{assignments.filter(a=>a.assignee_is_bum&&isOpen(a)).slice(0,5).map(a=><button key={a.id} className="block w-full rounded-xl bg-white p-3 text-left text-sm dark:bg-slate-800" onClick={()=>setDetail(a)}><strong>{assignmentTitle(a)}</strong><span className="mt-1 block text-slate-500">{a.assignee_name} · {a.unit_name} · {formatDue(a.due_at)}</span></button>)}</div><button className={`${buttonClass} mt-3`} onClick={()=>{setTeam(true);navigate('Tasks');}}>View team assignments</button></section>}
              {hasTeam&&tab!=='Scheduling'&&<div className="flex gap-2"><button className={`${buttonClass} ${!team?'bg-violet-100 text-violet-800 dark:bg-violet-950 dark:text-violet-200':''}`} onClick={()=>setTeam(false)}>My Tasks</button><button className={`${buttonClass} ${team?'bg-violet-100 text-violet-800 dark:bg-violet-950 dark:text-violet-200':''}`} onClick={()=>setTeam(true)}>Team Tasks</button></div>}
              <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{filters.map(x=><button key={x} aria-pressed={filter===x} className={`min-h-11 rounded-full border px-4 text-sm font-semibold ${filter===x?'border-violet-600 bg-violet-600 text-white':'border-slate-200 bg-white text-slate-500 hover:border-violet-300 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-300'}`} onClick={()=>setFilter(x)}>{x}</button>)}</div><input aria-label="Search assignments" className={`${inputClass} sm:max-w-60`} placeholder="Search tasks, assets or assignees" value={query} onChange={e=>setQuery(e.target.value)}/></div>
              <div className="grid grid-cols-3 gap-2 sm:gap-4">{[['Outstanding',scoped.filter(isOpen).length],['Due today',scoped.filter(a=>matchesFilter(a,'Due Today')).length],['Completed',scoped.filter(a=>a.status==='Completed').length]].map(([label,value])=><div className="rounded-2xl border border-slate-100 bg-white p-3 sm:p-5 dark:border-slate-700 dark:bg-slate-800" key={label}><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-3xl">{value}</strong></div>)}</div>
              {tab==='Today'&&scoped.some(a=>isOpen(a)&&manilaDay(a.due_at)>manilaDay(new Date()))&&<section className="rounded-2xl border border-slate-100 bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><div className="flex items-center justify-between"><h3 className="font-semibold">Upcoming</h3><button className="text-sm font-semibold text-violet-700 underline dark:text-violet-300" onClick={()=>navigate('Tasks')}>View all</button></div>{scoped.filter(a=>isOpen(a)&&manilaDay(a.due_at)>manilaDay(new Date())).slice(0,3).map(a=><button key={a.id} className="mt-3 flex w-full flex-wrap justify-between gap-2 text-left text-sm" onClick={()=>setDetail(a)}><span>{assignmentTitle(a)}</span><span className="text-slate-500">{formatDue(a.due_at)}</span></button>)}</section>}
              {!visible.length?<div className="rounded-2xl border border-dashed border-slate-200 py-20 text-center dark:border-slate-700"><OpsIcon name="Tasks" className="mx-auto h-10 w-10 text-violet-300"/><h3 className="mt-4 text-xl font-semibold">{scoped.length?'No tasks match this view':'No assignments yet'}</h3><p className="mx-auto mt-2 max-w-sm text-sm text-slate-500">{scoped.length?'Try another filter to see your other assignments.':canAssign?'Assign a published task or checklist from your library.':'Your assigned work and instructions will appear here.'}</p>{filter!=='All'&&<button className={`${buttonClass} mt-4`} onClick={()=>setFilter('All')}>Show all tasks</button>}</div>:<div className="space-y-5">{data.units.filter(u=>visible.some(a=>a.business_unit_id===u.id)).map(u=><section key={u.id}><h3 className="mb-3 text-xs font-bold uppercase tracking-widest text-slate-400">{u.name}</h3><div className="grid gap-3 xl:grid-cols-2">{visible.filter(a=>a.business_unit_id===u.id).map(a=><button key={a.id} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:border-violet-300 hover:shadow-md dark:border-slate-700 dark:bg-slate-800" onClick={()=>setDetail(a)}><span className={`mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-full border ${a.status==='Completed'?'border-violet-600 bg-violet-600 text-white':'border-violet-200 text-violet-500'}`}>{a.status==='Completed'?'✓':<OpsIcon name="Tasks"/>}</span><span className="min-w-0 flex-1"><span className="block font-semibold">{assignmentTitle(a)}</span>{a.maintenance&&<span className="mt-1 block text-sm text-violet-700">{a.maintenance.name} · {a.maintenance.asset_tag}</span>}<span className="mt-1 block text-sm text-slate-500 dark:text-slate-400">{(a.execution?a.execution.shared:!!a.checklist_run_id)?`Shared team · ${a.members?.length||0} staff`:a.assignee_name} · {a.kind} v{a.version}</span><span className={`mt-2 block text-xs ${matchesFilter(a,'Overdue')?'font-semibold text-red-600':'text-slate-500 dark:text-slate-400'}`}>{formatDue(a.due_at)} · {a.priority}</span>{a.requires_verification&&<span className="mt-2 block text-xs text-amber-700 dark:text-amber-300">{a.status==='Completed'?'Submitted · not independently verified':'Future supervisor verification flagged'}</span>}</span>{a.execution?.outcome==='Issues'&&<span className="text-xs font-semibold text-amber-700">Issues flagged</span>}<span className="h-fit rounded-full bg-violet-50 px-2 py-1 text-[10px] font-bold text-violet-800 dark:bg-violet-950 dark:text-violet-200">{a.execution?.submitted_at?'Submitted':a.status}</span></button>)}</div></section>)}</div>}
            </>}
            {['Progress','Team Progress'].includes(tab)&&<>
              <div className="rounded-3xl border border-violet-100 bg-white p-7 dark:border-slate-700 dark:bg-slate-800"><div className="flex items-end justify-between"><div><p className="text-sm text-slate-500">Completion · all visible assignments</p><strong className="mt-2 block text-5xl text-violet-800 dark:text-violet-200">{completion}%</strong></div><p className="text-sm text-slate-500">{completed.length} of {total} completed</p></div><div className="mt-6 h-3 overflow-hidden rounded-full bg-violet-100"><div className="h-full rounded-full bg-violet-600" style={{width:`${completion}%`}}/></div><p className="mt-3 text-xs text-slate-500">Cancelled assignments are excluded. Completion is employee confirmation; supervisor verification is not yet implemented.</p></div>
              <div className="grid grid-cols-3 gap-2 sm:gap-4">{[['Outstanding',open.length],['Overdue',assignments.filter(a=>matchesFilter(a,'Overdue')).length],['Cancelled',assignments.filter(a=>a.status==='Cancelled').length]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-3xl">{value}</strong></div>)}</div>
              <div className="overflow-auto rounded-2xl border bg-white dark:border-slate-700 dark:bg-slate-800"><table className="w-full text-left text-sm"><thead><tr className="border-b dark:border-slate-700">{['Business unit','Assigned / in progress','Completed','Overdue'].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{data.units.filter(u=>!unit||u.id===unit).map(u=><tr key={u.id} className="border-b last:border-0 dark:border-slate-700"><td className="p-4"><button className="font-semibold text-violet-700 underline dark:text-violet-300" onClick={()=>switchUnit(u.id)}>{u.name}</button></td><td className="p-4">{open.filter(a=>a.business_unit_id===u.id).length}</td><td className="p-4">{completed.filter(a=>a.business_unit_id===u.id).length}</td><td className="p-4">{assignments.filter(a=>a.business_unit_id===u.id&&matchesFilter(a,'Overdue')).length}</td></tr>)}</tbody></table></div>
              {tab==='Team Progress'&&<div className="space-y-3">{Array.from(new Set((data.assignments||[]).map(a=>a.assignee_id))).map(id=>{const rows=data.assignments.filter(a=>a.assignee_id===id);return <div key={id} className="flex flex-wrap justify-between gap-2 rounded-xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><strong>{rows[0].assignee_name}</strong><span className="text-sm text-slate-500">{rows.filter(a=>a.status==='Completed').length} completed · {rows.filter(isOpen).length} outstanding</span></div>;})}</div>}
              {hasLibraries&&<div className="flex flex-wrap gap-3"><button className={buttonClass} onClick={()=>navigate('Task Library')}>{canMaster?'Master & Unit Task Library':'Task Library'}</button><button className={buttonClass} onClick={()=>navigate('Checklist Library')}>Checklist Library</button></div>}
            </>}
            {['Task Library','Checklist Library'].includes(tab)&&hasLibraries&&<>
              <div className="flex flex-wrap gap-3"><input aria-label="Search templates" className={`${inputClass} sm:max-w-xs`} placeholder="Search library" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Template status" className={`${inputClass} w-auto`} value={libraryFilter} onChange={e=>setLibraryFilter(e.target.value)}>{['All','Draft','Published','Archived'].map(x=><option key={x}>{x}</option>)}</select>{canEdit&&<button className={primaryClass} onClick={()=>setEditor({kind:libraryKind})}>Create {libraryKind}</button>}{libraryKind==='checklist'&&<><button className={buttonClass} onClick={exportChecklistSample}>Export sample to fill up</button>{canEdit&&<button className={buttonClass} onClick={()=>setImporting(true)}>Import checklists</button>}</>}</div>
              <p className="text-sm text-slate-500">{unit?'Unit templates and reusable TNG masters. Duplicate a master to customize it for this unit.':canMaster?'TNG Master Library. Select a business unit for its own library.':'Select an authorized business unit to view and manage its library.'}</p>
              {!library.length&&<div className="py-16 text-center text-slate-500">No {libraryKind} templates in this view.</div>}
              <div className="grid gap-4 xl:grid-cols-2">{library.map(t=>{const editable=t.business_unit_id?(data.units.find(u=>u.id===t.business_unit_id)?.manage||(data.units.find(u=>u.id===t.business_unit_id)?.edit&&t.created_by===data.actor)):canMaster;return <article key={t.id} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><div className="flex items-start justify-between gap-3"><div><p className="mb-1 text-[10px] font-bold uppercase tracking-widest text-violet-600">{t.business_unit_id?'Unit library':'TNG Master'}</p><h3 className="text-lg font-semibold">{t.draft.title}</h3></div><span className="rounded-full bg-violet-50 px-3 py-1 text-xs text-violet-800 dark:bg-violet-950 dark:text-violet-200">{t.status}</span></div><p className="mt-2 line-clamp-2 text-sm text-slate-500">{t.draft.description||t.draft.instructions||'Reusable operating procedure'}</p><p className="mt-3 text-xs text-slate-400">{t.draft.category||'Operations'} · {t.latest_version?`Published v${t.latest_version}`:'No published version'}{t.kind==='checklist'?` · ${t.draft.items?.length||0} tasks`:''}</p><p className="mt-1 break-all text-[10px] text-slate-400">ID: {t.id}</p><div className="mt-4 flex flex-wrap gap-2">{editable&&t.status!=='Archived'&&<button className={buttonClass} onClick={()=>setEditor({kind:t.kind,template:t})}>Edit / new version</button>}{canEdit&&(t.business_unit_id===unit||!t.business_unit_id)&&<button className={buttonClass} disabled={busy} onClick={()=>void mutation('ops_template_action',{p_id:t.id,p_unit:unit||null,p_action:'duplicate',p_revision:t.revision},'Draft copy created in this library.')}>Duplicate</button>}{!!t.versions.length&&<button className={buttonClass} onClick={()=>setVersionHistory(t)}>Versions & instructions</button>}{canAssign&&t.status==='Published'&&<button className={primaryClass} onClick={()=>setAssign(t.versions[0].id)}>Assign</button>}{editable&&t.status!=='Archived'&&<button className={buttonClass} disabled={busy} onClick={()=>void mutation('ops_template_action',{p_id:t.id,p_unit:t.business_unit_id,p_action:'archive',p_revision:t.revision},'Template archived. Existing assignments are preserved.')}>Archive</button>}</div></article>;})}</div>
            </>}
            {tab==='Settings'&&<>
              <section className="space-y-3 rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h3 className="font-semibold">Workspace preferences</h3><p className="text-sm text-slate-500">Your selected workspace is remembered on this device. Access comes from your active HRIS roles and business-unit assignments. Times use Asia/Manila.</p><p className="text-sm">{data.units.length} authorized workspace{data.units.length===1?'':'s'} available.</p><div className="flex flex-wrap gap-2">{data.units.map(u=><button key={u.id} className={buttonClass} onClick={()=>switchUnit(u.id)}>{u.name}</button>)}</div></section>
              {canManage&&<section className="space-y-4 rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><h3 className="font-semibold">Supervisor permissions · {selection?.name}</h3><p className="text-sm text-slate-500">Grant task creation and assignment separately. Assignment access remains restricted to the supervisor’s direct reporting team in this unit. Revoking permissions takes effect immediately.</p><select aria-label="Supervisor" className={inputClass} value={delegateId} onChange={e=>{setDelegateId(e.target.value);const p=data.permissions.find(p=>p.user_id===e.target.value);setDelegateCreate(!!p?.can_create);setDelegateAssign(!!p?.can_assign);}}><option value="">Select unit staff</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.position}</option>)}</select><label className="flex gap-3 text-sm"><input type="checkbox" checked={delegateCreate} onChange={e=>setDelegateCreate(e.target.checked)}/>Create and publish unit templates</label><label className="flex gap-3 text-sm"><input type="checkbox" checked={delegateAssign} onChange={e=>setDelegateAssign(e.target.checked)}/>Assign to direct reports</label><button className={primaryClass} disabled={!delegateId||busy} onClick={()=>void mutation('ops_delegate',{p_unit:unit,p_user:delegateId,p_create:delegateCreate,p_assign:delegateAssign},'Supervisor permissions saved.')}>Save permissions</button></section>}
            </>}
          </>}
        </div>
      </section>
    </div>
    {canEdit&&!loading&&<button aria-label="Create an operational task" title="Create task" className="fixed bottom-24 right-6 z-30 flex h-16 w-16 items-center justify-center rounded-full bg-[#3d1952] text-4xl font-light text-white shadow-xl hover:bg-violet-800 lg:bottom-28" onClick={()=>setEditor({kind:'task'})}>+</button>}
    <nav aria-label="Operations bottom navigation" className="fixed bottom-0 left-0 right-0 z-30 grid grid-cols-4 border-t border-slate-200 bg-white pb-[env(safe-area-inset-bottom)] lg:hidden dark:border-slate-700 dark:bg-slate-900">{mainTabs.map(x=><button key={x} aria-current={tab===x?'page':undefined} className={`flex min-h-20 flex-col items-center justify-center gap-1 text-sm ${tab===x?'font-semibold text-violet-800 dark:text-violet-200':'text-slate-500'}`} onClick={()=>navigate(x)}><OpsIcon name={x} className="h-6 w-6"/>{x}</button>)}</nav>
    {data&&importing&&<ChecklistImport unit={unit} unitName={selection?.name||'TNG Master Library'} onClose={()=>setImporting(false)} onSaved={()=>load()}/>}
    {data&&editor&&<TemplateEditor workspace={data} unit={editor.template?(editor.template.business_unit_id||''):unit} kind={editor.kind} template={editor.template} onClose={()=>setEditor(null)} onSaved={()=>load()}/>}
    {data&&assign!==null&&<AssignmentEditor workspace={data} unit={unit} initialVersion={assign} onClose={()=>setAssign(null)} onSaved={()=>load()}/>}
    {data&&detail&&<AssignmentDetail assignment={data.assignments.find(a=>a.id===detail.id)||detail} workspace={data} onClose={()=>setDetail(null)} onSaved={()=>load()}/>}
    {versionHistory&&<Modal isOpen onClose={()=>setVersionHistory(null)} title={`${versionHistory.draft.title} · published versions`} size="3xl" viewportFit><div className="space-y-4">{versionHistory.versions.map(v=><details key={v.id} className="rounded-xl border p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">Version {v.version} · {formatDue(v.published_at)}</summary><h3 className="mt-3 font-semibold">{v.content.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm">{v.content.description}</p><p className="mt-2 whitespace-pre-wrap text-sm">{v.content.instructions}</p>{safeUrl(v.content.sop_url)&&<a className="text-violet-700 underline" href={safeUrl(v.content.sop_url)} target="_blank" rel="noopener noreferrer">Open SOP ↗</a>}{v.items.map(i=><div key={i.id} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-800"><strong>{i.ordinal+1}. {i.snapshot.title}</strong><p className="mt-1 whitespace-pre-wrap">{i.snapshot.instructions}</p><span className="text-xs text-slate-500">{i.required?'Required':'Optional'} · {i.response_type}</span></div>)}</details>)}</div></Modal>}
  </div>;
}
