import React, { useEffect, useRef, useState } from 'react';
import { useAuth } from '../../hooks/useAuth';
import { ackRpc, download, manila, receiptText, STATEMENT } from './service';

export function DocumentViewer({ delivery, onLoaded }: { key?: React.Key; delivery: any; onLoaded: () => void }) {
 const v=delivery.version;
 const [loaded,setLoaded]=useState<Record<string,boolean>>({});
 const [failure,setFailure]=useState('');
 const [files,setFiles]=useState<any[]>([]);
 const done=useRef(false);
 useEffect(()=>{
  const urls:string[]=[];
  try { setFiles((v.content_snapshot.files||[]).map((f:any,i:number)=>{const bytes=Uint8Array.from(atob(f.base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:f.mime}));urls.push(url);return {...f,url,key:String(i)};})); }
  catch {setFailure('The archived attachment could not be loaded. Please contact HR.');}
  return ()=>urls.forEach(URL.revokeObjectURL);
 },[delivery.deliveryId]);
 useEffect(()=>{if(!failure && loaded.body && files.length===(v.content_snapshot.files||[]).length && files.every(f=>loaded[f.key]) && !done.current){done.current=true;onLoaded();}},[loaded,files,failure,onLoaded]);
 const mark=(key:string)=>setLoaded(s=>({...s,[key]:true}));
 // Isolated document: no scripts, external content, forms or navigation. The stored
 // HTML remains immutable; sandbox/CSP controls how it is displayed.
 const html=`<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:"><style>body{font:16px/1.6 system-ui;padding:16px;overflow-wrap:anywhere;white-space:pre-wrap}img{max-width:100%}</style>${v.content_snapshot.body}`;
 return <div className="space-y-4"><h2 className="text-xl font-bold">{v.title} · Version {v.version_number}</h2><p>Published {manila(v.published_at)} · SHA-256: <code className="break-all text-xs">{v.content_hash}</code></p><iframe title="Published document content" sandbox="" srcDoc={html} onLoad={()=>mark('body')} onError={()=>setFailure('Document failed to load.')} className="w-full min-h-[350px] border rounded-lg bg-white"/>{files.map(f=><section key={f.key}><h3 className="font-semibold">{f.name}</h3>{f.mime.startsWith('image/')?<img src={f.url} alt={f.name} onLoad={()=>mark(f.key)} onError={()=>setFailure('Attachment failed to load.')} className="max-w-full"/>:<iframe title={f.name} src={f.url} onLoad={()=>mark(f.key)} onError={()=>setFailure('Attachment failed to load.')} className="w-full h-[500px] border"/>}<a href={f.url} download={f.name} className="underline">Download archived attachment</a></section>)}{failure&&<p role="alert" className="text-red-700">{failure}</p>}</div>;
}
export default function EmployeeAcknowledgments() {
 const {user}=useAuth();
 const [data,setData]=useState<any>({documents:[],receipts:[]});const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 const [delivery,setDelivery]=useState<any>(null);const [viewed,setViewed]=useState(false);const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [receipt,setReceipt]=useState<any>(null);const submitLock=useRef(false);
 useEffect(()=>{let live=true;setData({documents:[],receipts:[]});setDelivery(null);setReceipt(null);ackRpc('my_acknowledgments').then(d=>{if(live)setData(d);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[user?.id]);
 async function open(id:string){if(busy)return;setBusy(true);setError('');setViewed(false);setConfirmed(false);setReceipt(null);setDelivery(null);try{setDelivery(await ackRpc('open_acknowledgment_document',{p_assignment:id}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function loaded(){try{await ackRpc('record_acknowledgment_view',{p_delivery:delivery.deliveryId});setViewed(true);setData(await ackRpc('my_acknowledgments'));}catch(e){setError((e as Error).message);}}
 async function acknowledge(){if(!confirmed||!viewed||submitLock.current)return;submitLock.current=true;setBusy(true);setError('');try{const r=await ackRpc('acknowledge_document',{p_delivery:delivery.deliveryId,p_confirmed:true,p_source:'web'});setReceipt(r);setData(await ackRpc('my_acknowledgments'));window.dispatchEvent(new Event('acknowledgment-changed'));}catch(e){setError((e as Error).message);}finally{submitLock.current=false;setBusy(false);}}
 const list=(docs:any[])=>docs.length?<div className="space-y-3">{docs.map(d=><article key={d.assignmentId} className="border rounded-xl p-4 space-y-2"><h3 className="font-semibold">{d.title} · {d.documentType} · Version {d.version}</h3><p>Published: {manila(d.publishedAt)} · Effective: {d.effectiveDate}{d.dueDate&&` · Due: ${d.dueDate}`}</p><p>Issuing department: {d.issuingDepartment||'—'} · {d.status}{d.exempt?' · Exempt':''}</p><button className="underline font-semibold" disabled={busy} onClick={()=>void open(d.assignmentId)}>Open Document</button></article>)}</div>:<p>No documents in this section.</p>;
 return <main className="max-w-5xl mx-auto p-4 space-y-6"><h1 className="text-3xl font-bold">Pending Acknowledgments</h1><p>Open each published document before confirming receipt and review.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{loading?<p>Loading documents…</p>:<>{list(data.documents.filter((d:any)=>d.pending))}{delivery&&<section className="border rounded-xl p-4 space-y-4 bg-white text-slate-900"><DocumentViewer key={delivery.deliveryId} delivery={delivery} onLoaded={()=>void loaded()}/>{receipt?<><p role="status">Document acknowledged successfully on {new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',dateStyle:'long'}).format(new Date(receipt.acknowledged_at))} at {new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',timeStyle:'short'}).format(new Date(receipt.acknowledged_at))}.</p><pre className="whitespace-pre-wrap text-sm">{receiptText(receipt)}</pre><button className="underline" onClick={()=>download(`acknowledgment-${receipt.id}.txt`,receiptText(receipt))}>Download Receipt</button></>:<><label className="flex gap-3"><input type="checkbox" disabled={!viewed||busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>{STATEMENT}</span></label>{!viewed&&<p>The acknowledgment control becomes available after the document and attachments load successfully.</p>}<button className="rounded-lg bg-violet-700 px-5 py-3 text-white disabled:opacity-50" disabled={!viewed||!confirmed||busy} onClick={()=>void acknowledge()}>{busy?'Saving…':'Acknowledge Document'}</button></>}</section>}<h2 className="text-2xl font-semibold">Previously acknowledged documents</h2>{list(data.documents.filter((d:any)=>d.status==='Acknowledged'))}<h2 className="text-2xl font-semibold">Acknowledgment receipts</h2>{data.receipts.map((r:any)=><div key={r.id} className="border rounded p-3"><span>{r.document_snapshot.title} · Version {r.document_snapshot.version_number} · {manila(r.acknowledged_at)} </span><button className="underline" onClick={()=>download(`acknowledgment-${r.id}.txt`,receiptText(r))}>View / Download Receipt</button></div>)}<details><summary>Other assigned versions and exemptions</summary>{list(data.documents.filter((d:any)=>!d.pending&&d.status!=='Acknowledged'))}</details></>}</main>;
}
