-- Additive verified attendance channels. No existing RLS policy is replaced.
create table public.attendance_channel_settings(id uuid primary key default gen_random_uuid(),business_unit_id uuid not null references public.business_units(id),revision integer not null,web_allowed boolean not null default true,gps_enabled boolean not null default false,qr_enabled boolean not null default false,created_by uuid not null references public.hris_users(id),created_at timestamptz not null default clock_timestamp(),reason text not null check(length(trim(reason))>=3),unique(business_unit_id,revision));
create table public.attendance_devices(id uuid primary key default gen_random_uuid(),business_unit_id uuid not null references public.business_units(id),site_id uuid not null references public.sites(id),name text not null check(length(trim(name)) between 3 and 100),kind text not null check(kind in('qr','biometric')),active boolean not null default true,created_by uuid not null references public.hris_users(id),created_at timestamptz not null default clock_timestamp());
create table public.attendance_device_audit(id uuid primary key default gen_random_uuid(),device_id uuid not null references public.attendance_devices(id),detail jsonb not null,actor uuid not null references public.hris_users(id),created_at timestamptz not null default clock_timestamp());
create table public.attendance_device_mappings(id uuid primary key default gen_random_uuid(),device_id uuid not null references public.attendance_devices(id),device_employee_code text not null check(length(device_employee_code) between 1 and 100),employee_id uuid not null references public.hris_users(id),revision integer not null,active boolean not null default true,created_by uuid not null references public.hris_users(id),created_at timestamptz not null default clock_timestamp(),unique(device_id,device_employee_code,revision));
create table public.attendance_qr_challenges(id uuid primary key default gen_random_uuid(),device_id uuid not null references public.attendance_devices(id),token_hash text not null unique,expires_at timestamptz not null,created_by uuid not null references public.hris_users(id),created_at timestamptz not null default clock_timestamp());
create table public.attendance_import_batches(id uuid primary key default gen_random_uuid(),device_id uuid not null references public.attendance_devices(id),filename text not null,source_hash text not null,rows jsonb not null,created_by uuid not null references public.hris_users(id),created_at timestamptz not null default clock_timestamp(),committed_at timestamptz,committed_by uuid references public.hris_users(id),result jsonb);
create table public.attendance_channel_evidence(event_id uuid primary key references public.attendance_clock_events(id),method text not null check(method in('web','gps','qr','biometric')),site_id uuid references public.sites(id),device_id uuid references public.attendance_devices(id),challenge_id uuid references public.attendance_qr_challenges(id),batch_id uuid references public.attendance_import_batches(id),source_key text,detail jsonb not null default '{}',recorded_at timestamptz not null default clock_timestamp(),unique(device_id,source_key));
create unique index attendance_qr_employee_use on public.attendance_channel_evidence(challenge_id,(detail->>'employeeId')) where challenge_id is not null;
create index attendance_mapping_lookup on public.attendance_device_mappings(device_id,device_employee_code,revision desc);
create index attendance_qr_expiry on public.attendance_qr_challenges(device_id,expires_at);
do $$declare t text;begin foreach t in array array['attendance_channel_settings','attendance_devices','attendance_device_audit','attendance_device_mappings','attendance_qr_challenges','attendance_import_batches','attendance_channel_evidence'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);if t not in('attendance_devices','attendance_import_batches') then execute format('create trigger immutable before update or delete on public.%I for each row execute function private.payroll_audit_immutable()',t);end if;end loop;end $$;
create function private.attendance_channel_config(p_bu uuid) returns jsonb language sql stable security definer set search_path='' as $$select coalesce((select to_jsonb(s) from public.attendance_channel_settings s where business_unit_id=p_bu order by revision desc limit 1),jsonb_build_object('business_unit_id',p_bu,'revision',0,'web_allowed',true,'gps_enabled',false,'qr_enabled',false))$$;
create function private.attendance_bu_admin(p_bu uuid) returns boolean language sql stable security definer set search_path='' as $$select private.attendance_admin() and exists(select 1 from public.hris_users h where h.business_unit_id=p_bu and public.can_access_hris_user(h.id))$$;
create function public.get_attendance_channels() returns jsonb language plpgsql stable security definer set search_path='' as $$declare bu uuid;begin if private.payroll_actor_id() is null then raise exception 'Active sign-in required' using errcode='42501';end if;select business_unit_id into bu from public.hris_users where id=public.current_hris_user_id();return jsonb_build_object('config',private.attendance_channel_config(bu),'sites',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name)),'[]') from public.sites where business_unit_id=bu),'canManage',private.attendance_admin());end $$;
create function public.get_attendance_channel_admin() returns jsonb language plpgsql stable security definer set search_path='' as $$begin if not private.attendance_admin() then raise exception 'HR/Admin access required' using errcode='42501';end if;return jsonb_build_object('businessUnits',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'config',private.attendance_channel_config(id)) order by name),'[]') from public.business_units where private.attendance_bu_admin(id)),'sites',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'business_unit_id',business_unit_id,'latitude',latitude,'longitude',longitude,'radius_meters',radius_meters)),'[]') from public.sites where private.attendance_bu_admin(business_unit_id)),'devices',(select coalesce(jsonb_agg(to_jsonb(d)),'[]') from public.attendance_devices d where private.attendance_bu_admin(business_unit_id)),'mappings',(select coalesce(jsonb_agg(to_jsonb(m) order by m.created_at desc),'[]') from public.attendance_device_mappings m join public.attendance_devices d on d.id=m.device_id where private.attendance_bu_admin(d.business_unit_id)),'batches',(select coalesce(jsonb_agg(to_jsonb(b)-'rows' order by b.created_at desc),'[]') from public.attendance_import_batches b join public.attendance_devices d on d.id=b.device_id where private.attendance_bu_admin(d.business_unit_id)),'history',(select coalesce(jsonb_agg(to_jsonb(s) order by created_at desc),'[]') from public.attendance_channel_settings s where private.attendance_bu_admin(business_unit_id)),'deviceAudit',(select coalesce(jsonb_agg(to_jsonb(a) order by a.created_at desc),'[]') from public.attendance_device_audit a join public.attendance_devices d on d.id=a.device_id where private.attendance_bu_admin(d.business_unit_id)));end $$;
create function public.save_attendance_channel_settings(p_bu uuid,p_revision integer,p_web boolean,p_gps boolean,p_qr boolean,p_reason text) returns void language plpgsql security definer set search_path='' as $$begin if not private.attendance_bu_admin(p_bu) then raise exception 'Scoped HR/Admin access required' using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended('attendance-channel:'||p_bu::text,0));if (private.attendance_channel_config(p_bu)->>'revision')::int<>p_revision then raise exception 'Settings changed; refresh' using errcode='40001';end if;if not(p_web or p_gps or p_qr) then raise exception 'Keep at least one live employee clock method enabled';end if;if p_gps and not exists(select 1 from public.sites where business_unit_id=p_bu and latitude between -90 and 90 and longitude between -180 and 180 and radius_meters>0) then raise exception 'Configure a valid site geofence first';end if;if p_qr and not exists(select 1 from public.attendance_devices where business_unit_id=p_bu and kind='qr' and active) then raise exception 'Register a QR kiosk first';end if;insert into public.attendance_channel_settings(business_unit_id,revision,web_allowed,gps_enabled,qr_enabled,created_by,reason) values(p_bu,p_revision+1,p_web,p_gps,p_qr,public.current_hris_user_id(),p_reason);end $$;
create function public.save_attendance_device(p_id uuid,p_bu uuid,p_site uuid,p_name text,p_kind text,p_active boolean) returns uuid language plpgsql security definer set search_path='' as $$declare d public.attendance_devices;begin if not private.attendance_bu_admin(p_bu) then raise exception 'Scoped HR/Admin access required' using errcode='42501';end if;if not exists(select 1 from public.sites where id=p_site and business_unit_id=p_bu) then raise exception 'Choose a site in this business unit';end if;if p_id is null then insert into public.attendance_devices(business_unit_id,site_id,name,kind,active,created_by) values(p_bu,p_site,p_name,p_kind,p_active,public.current_hris_user_id()) returning * into d;else select * into d from public.attendance_devices where id=p_id for update;if d.business_unit_id is distinct from p_bu or d.kind is distinct from p_kind or d.site_id is distinct from p_site then raise exception 'Device scope/type/site cannot be reassigned. Register a new device.';end if;update public.attendance_devices set name=p_name,active=p_active where id=p_id returning * into d;end if;insert into public.attendance_device_audit(device_id,detail,actor) values(d.id,to_jsonb(d),public.current_hris_user_id());return d.id;end $$;
create function public.map_attendance_device_employee(p_device uuid,p_code text,p_employee uuid,p_active boolean) returns void language plpgsql security definer set search_path='' as $$declare d public.attendance_devices;rev int;begin select * into d from public.attendance_devices where id=p_device;if not private.attendance_bu_admin(d.business_unit_id) or not public.can_access_hris_user(p_employee) then raise exception 'Scoped HR/Admin access required' using errcode='42501';end if;if d.kind<>'biometric' or not exists(select 1 from public.hris_users where id=p_employee and business_unit_id=d.business_unit_id and not coalesce(is_duplicate,false)) then raise exception 'Choose an employee in this device business unit';end if;perform pg_advisory_xact_lock(hashtextextended('attendance-device:'||p_device::text,0));select coalesce(max(revision),0)+1 into rev from public.attendance_device_mappings where device_id=p_device and device_employee_code=trim(p_code);insert into public.attendance_device_mappings(device_id,device_employee_code,employee_id,revision,active,created_by) values(p_device,trim(p_code),p_employee,rev,p_active,public.current_hris_user_id());end $$;
create function public.issue_attendance_qr(p_device uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare d public.attendance_devices;t text;exp timestamptz:=clock_timestamp()+interval '60 seconds';begin select * into d from public.attendance_devices where id=p_device;if not private.attendance_bu_admin(d.business_unit_id) then raise exception 'Scoped kiosk operator access required' using errcode='42501';end if;if not d.active or d.kind<>'qr' or not(private.attendance_channel_config(d.business_unit_id)->>'qr_enabled')::boolean then raise exception 'Enable this QR kiosk first';end if;perform pg_advisory_xact_lock(hashtextextended('attendance-kiosk:'||p_device::text,0));if exists(select 1 from public.attendance_qr_challenges where device_id=p_device and created_at>clock_timestamp()-interval '10 seconds') then raise exception 'Wait before refreshing this kiosk code';end if;t:=encode(extensions.gen_random_bytes(24),'hex');insert into public.attendance_qr_challenges(device_id,token_hash,expires_at,created_by) values(p_device,encode(extensions.digest(t,'sha256'),'hex'),exp,public.current_hris_user_id());return jsonb_build_object('token',t,'expiresAt',exp,'serverTime',clock_timestamp(),'site',d.name);end $$;
-- Preserve the existing server state machine and close all old bypass routes.
do $$declare ddl text;begin ddl:=pg_get_functiondef('public.record_my_attendance(text,uuid,integer,date)'::regprocedure);execute replace(ddl,'FUNCTION public.record_my_attendance(','FUNCTION private.record_attendance_core(');end $$;
create function public.record_my_attendance_verified(p_action text,p_request_id uuid,p_expected_revision integer,p_work_date date,p_evidence jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare emp uuid:=public.current_hris_user_id();bu uuid;cfg jsonb;method text:=coalesce(p_evidence->>'method','web');s public.sites;d public.attendance_devices;q public.attendance_qr_challenges;lat double precision;lon double precision;acc double precision;distance double precision;result jsonb;ev uuid;detail jsonb:='{}';begin
 if private.payroll_actor_id() is null then raise exception 'Active sign-in required' using errcode='42501';end if;
 select business_unit_id into bu from public.hris_users where id=emp;perform pg_advisory_xact_lock_shared(hashtextextended('attendance-channel:'||bu::text,0));perform pg_advisory_xact_lock(hashtextextended('attendance-clock:'||emp::text,0));
 if exists(select 1 from public.attendance_clock_events where employee_id=emp and request_id=p_request_id and action=p_action) then return public.get_my_attendance();end if;cfg:=private.attendance_channel_config(bu);
 if method='web' then if not(cfg->>'web_allowed')::boolean then raise exception 'Use your configured GPS or QR clock method';end if;
 elsif method='gps' then
 if not(cfg->>'gps_enabled')::boolean then raise exception 'GPS clocking is not enabled for your business unit';end if;
 select * into s from public.sites where id=(p_evidence->>'siteId')::uuid and business_unit_id=bu;
 lat:=(p_evidence->>'latitude')::double precision;lon:=(p_evidence->>'longitude')::double precision;acc:=(p_evidence->>'accuracy')::double precision;
 if s.id is null or s.latitude is null or s.longitude is null or s.radius_meters is null or s.radius_meters<=0 or lat is null or lon is null or acc is null or lat not between -90 and 90 or lon not between -180 and 180 or acc not between 0 and 100 then raise exception 'Use a configured work site and a fresh location reading accurate within 100 metres';end if;
 distance:=6371000*2*asin(sqrt(least(1.0,power(sin(radians(lat-s.latitude)/2),2)+cos(radians(lat))*cos(radians(s.latitude))*power(sin(radians(lon-s.longitude)/2),2))));
 if distance+acc>s.radius_meters then raise exception 'Your location is outside the site boundary or not accurate enough. Retry at the work site.';end if;
 detail:=jsonb_build_object('latitude',lat,'longitude',lon,'accuracy',acc,'distanceMetres',distance,'radiusMetres',s.radius_meters,'locationSource','Device-reported GPS');
 elsif method='qr' then
 if not(cfg->>'qr_enabled')::boolean then raise exception 'QR clocking is not enabled for your business unit';end if;
 select * into q from public.attendance_qr_challenges where token_hash=encode(extensions.digest(coalesce(p_evidence->>'token',''),'sha256'),'hex');
 select * into d from public.attendance_devices where id=q.device_id for share;
 if q.id is null or q.expires_at<=clock_timestamp() or not d.active or d.kind<>'qr' or d.business_unit_id is distinct from bu then raise exception 'QR code expired or belongs to another business unit. Scan the current kiosk code.';end if;
 if exists(select 1 from public.attendance_channel_evidence where challenge_id=q.id and detail->>'employeeId'=emp::text) then raise exception 'You already used this kiosk code. Scan the next code.';end if;
 detail:=jsonb_build_object('employeeId',emp);else raise exception 'Choose Web, GPS or QR clocking';end if;
 result:=private.record_attendance_core(p_action,p_request_id,p_expected_revision,p_work_date);select id into strict ev from public.attendance_clock_events where employee_id=emp and request_id=p_request_id;
 insert into public.attendance_channel_evidence(event_id,method,site_id,device_id,challenge_id,detail) values(ev,method,coalesce(s.id,d.site_id),d.id,q.id,detail);
 return result;
end $$;
create or replace function public.record_my_attendance(p_action text,p_request_id uuid,p_expected_revision integer,p_work_date date) returns jsonb language sql security definer set search_path='' as $$select public.record_my_attendance_verified(p_action,p_request_id,p_expected_revision,p_work_date,'{"method":"web"}')$$;
-- Import preview saves source evidence only. Commit validates all mappings and
-- timelines atomically, preserves actual device times and deduplicates across files.
create function public.preview_attendance_import(p_device uuid,p_filename text,p_rows jsonb) returns jsonb language plpgsql security definer set search_path='' as $$declare d public.attendance_devices;r jsonb;outp jsonb:='[]';m public.attendance_device_mappings;ts timestamptz;day date;prior jsonb;b uuid;begin
 select * into d from public.attendance_devices where id=p_device;
 if not private.attendance_bu_admin(d.business_unit_id) then raise exception 'Scoped HR/Admin import access required' using errcode='42501';end if;
 if not d.active or d.kind<>'biometric' or length(p_filename) not between 1 and 200 or jsonb_typeof(p_rows) is distinct from 'array' or jsonb_array_length(p_rows) not between 1 and 1000 then raise exception 'Choose an active biometric device and 1–1000 rows';end if;
 perform pg_advisory_xact_lock(hashtextextended('attendance-device:'||p_device::text,0));
 for r in select value from jsonb_array_elements(p_rows) loop
 select * into m from public.attendance_device_mappings where device_id=p_device and device_employee_code=trim(r->>'code') order by revision desc limit 1;
 if m.id is null or not m.active or not public.can_access_hris_user(m.employee_id) then raise exception 'Map device employee code % before importing',r->>'code';end if;
 if r->>'timestamp' !~ '(Z|[+-][0-9]{2}:[0-9]{2})$' or r->>'action' not in('CLOCK_IN','START_BREAK','END_BREAK','CLOCK_OUT') then raise exception 'Each row needs an explicit timezone and mapped clock action';end if;
 ts:=(r->>'timestamp')::timestamptz;if ts is null or ts>clock_timestamp() then raise exception 'Invalid or future device timestamp';end if;
 day:=coalesce(nullif(r->>'workDate','')::date,(ts at time zone 'Asia/Manila')::date);
 if nullif(r->>'workDate','') is null then prior:=private.attendance_schedule(m.employee_id,day-1);if (prior->>'published')::boolean and exists(select 1 from jsonb_array_elements(prior->'entries') x where x->>'endDayOffset'='1' and (ts at time zone 'Asia/Manila')::time<=(x->>'end')::time) then day:=day-1;end if;end if;
 if (ts at time zone 'Asia/Manila')::date not between day and day+1 then raise exception 'Work date must match shift day or overnight next day';end if;
 outp:=outp||jsonb_build_array(jsonb_build_object('employeeId',m.employee_id,'employeeName',(select full_name from public.hris_users where id=m.employee_id),'mappingId',m.id,'code',trim(r->>'code'),'timestamp',ts,'action',r->>'action','workDate',day,'key',encode(extensions.digest(m.employee_id::text||'|'||ts::text||'|'||(r->>'action'),'sha256'),'hex')));
 end loop;
 insert into public.attendance_import_batches(device_id,filename,source_hash,rows,created_by) values(p_device,p_filename,encode(extensions.digest(outp::text,'sha256'),'hex'),outp,public.current_hris_user_id()) returning id into b;
 return jsonb_build_object('id',b,'rows',outp,'sourceHash',encode(extensions.digest(outp::text,'sha256'),'hex'));
end $$;
create function public.commit_attendance_import(p_batch uuid,p_hash text) returns jsonb language plpgsql security definer set search_path='' as $$declare b public.attendance_import_batches;d public.attendance_devices;r jsonb;emp uuid;s public.attendance_clock_sessions;sch jsonb;m public.attendance_device_mappings;next_state text;ev uuid;last_ts timestamptz;inserted int:=0;duplicates int:=0;begin
 select * into b from public.attendance_import_batches where id=p_batch for update;select * into d from public.attendance_devices where id=b.device_id;
 if b.id is null or not private.attendance_bu_admin(d.business_unit_id) then raise exception 'Scoped HR/Admin import access required' using errcode='42501';end if;
 if b.source_hash is distinct from p_hash then raise exception 'Preview changed; review again';end if;if b.committed_at is not null then return b.result;end if;if not d.active then raise exception 'Device is disabled';end if;
 perform pg_advisory_xact_lock(hashtextextended('attendance-device:'||d.id::text,0));
 for emp in select distinct (x->>'employeeId')::uuid from jsonb_array_elements(b.rows) x order by 1 loop perform pg_advisory_xact_lock(hashtextextended('attendance-clock:'||emp::text,0));end loop;
 perform pg_advisory_xact_lock_shared(hashtextextended('payroll-schedule-publication',0));
 for r in select value from jsonb_array_elements(b.rows) order by value->>'employeeId',(value->>'timestamp')::timestamptz,value->>'action' loop
 emp:=(r->>'employeeId')::uuid;
 select * into m from public.attendance_device_mappings where device_id=d.id and device_employee_code=r->>'code' order by revision desc limit 1;
 if m.id::text is distinct from r->>'mappingId' or not m.active or not public.can_access_hris_user(emp) then raise exception 'Employee mapping/access changed. Preview again';end if;
 if exists(select 1 from public.attendance_channel_evidence where device_id=d.id and source_key=r->>'key') then duplicates:=duplicates+1;continue;end if;
 if coalesce((private.attendance_exception(emp,(r->>'workDate')::date)->>'requires_clock')::boolean,true)=false then raise exception 'Employee is exempt on an imported work date; HR must review the conflict';end if;
 select * into s from public.attendance_clock_sessions where employee_id=emp and work_date=(r->>'workDate')::date;
 if s.id is null then sch:=private.attendance_schedule(emp,(r->>'workDate')::date);if not(sch->>'published')::boolean then raise exception 'Publish the actual schedule for % on % first',r->>'employeeName',r->>'workDate';end if;if not exists(select 1 from jsonb_array_elements(sch->'entries') x where x->>'kind'='work') then raise exception 'Imported work conflicts with a non-working schedule';end if;
 insert into public.attendance_clock_sessions(employee_id,work_date,publication_id,schedule_snapshot) values(emp,(r->>'workDate')::date,(sch->>'publicationId')::uuid,sch) returning * into s;end if;
 if exists(select 1 from public.attendance_clock_adjustments where session_id=s.id) then raise exception 'This day has an HR correction. Review it through attendance corrections';end if;
 select max(occurred_at) into last_ts from public.attendance_clock_events where session_id=s.id;if last_ts is not null and (r->>'timestamp')::timestamptz<=last_ts then raise exception 'Imported time overlaps an existing record. Use HR correction review';end if;
 next_state:=private.attendance_next_state(s.state,r->>'action');
 insert into public.attendance_clock_events(session_id,employee_id,action,occurred_at,request_id,revision,created_by) values(s.id,emp,r->>'action',(r->>'timestamp')::timestamptz,gen_random_uuid(),s.revision+1,public.current_hris_user_id()) returning id into ev;
 insert into public.time_events(id,employee_id,timestamp,type,source,timezone,created_by,notes) values(ev,emp,(r->>'timestamp')::timestamptz,case r->>'action' when 'CLOCK_IN' then 'ClockIn' when 'CLOCK_OUT' then 'ClockOut' when 'START_BREAK' then 'BreakStart' else 'BreakEnd' end,'Biometrics','Asia/Manila',public.current_hris_user_id(),'Reviewed biometric import');
 insert into public.attendance_channel_evidence(event_id,method,site_id,device_id,batch_id,source_key,detail) values(ev,'biometric',d.site_id,d.id,b.id,r->>'key',r);
 update public.attendance_clock_sessions set state=next_state,revision=s.revision+1 where id=s.id;inserted:=inserted+1;
 end loop;
 update public.attendance_import_batches set committed_at=clock_timestamp(),committed_by=public.current_hris_user_id(),result=jsonb_build_object('inserted',inserted,'duplicates',duplicates) where id=b.id;
 return jsonb_build_object('inserted',inserted,'duplicates',duplicates);
end $$;
do $$declare r record;begin for r in select p.oid::regprocedure sig,n.nspname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname='private' and p.proname in('attendance_channel_config','attendance_bu_admin','record_attendance_core')) or (n.nspname='public' and p.proname in('get_attendance_channels','get_attendance_channel_admin','save_attendance_channel_settings','save_attendance_device','map_attendance_device_employee','issue_attendance_qr','record_my_attendance_verified','preview_attendance_import','commit_attendance_import')) loop execute 'revoke all on function '||r.sig||' from public,anon,authenticated';if r.nspname='public' then execute 'grant execute on function '||r.sig||' to authenticated';end if;end loop;end $$;
notify pgrst,'reload schema';
