create table public.attendance_punch_requests(id uuid primary key default gen_random_uuid(),employee_id uuid not null references public.hris_users(id),manager_id uuid not null references public.hris_users(id),work_date date not null,action text not null check(action in('CLOCK_IN','START_BREAK','END_BREAK','CLOCK_OUT')),actual_time timestamptz not null,break_end timestamptz,reason text not null check(length(trim(reason)) between 3 and 1000),request_key uuid not null,status text not null default 'pending' check(status in('pending','approved','rejected','applied')),created_at timestamptz not null default clock_timestamp(),unique(employee_id,request_key));
create unique index attendance_punch_pending on public.attendance_punch_requests(employee_id,work_date,action) where status in('pending','approved');
create table public.attendance_punch_request_audit(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.attendance_punch_requests(id),action text not null,actor uuid not null references public.hris_users(id),note text not null,adjustment_id uuid references public.attendance_clock_adjustments(id),created_at timestamptz not null default clock_timestamp());
alter table public.attendance_punch_requests enable row level security;alter table public.attendance_punch_request_audit enable row level security;
revoke all on public.attendance_punch_requests,public.attendance_punch_request_audit from public,anon,authenticated;
create trigger immutable before update or delete on public.attendance_punch_request_audit for each row execute function private.payroll_audit_immutable();
create function private.punch_direct_manager(p_employee uuid) returns uuid language sql stable security definer set search_path='' as $$select case when count(*)=1 then (array_agg(m.id))[1] end from public.hris_users e join public.hris_users m on e.reports_to in(m.id::text,m.auth_user_id::text,m.employee_id,m.full_name) where e.id=p_employee and m.id<>e.id and lower(m.status)='active' and m.auth_user_id is not null$$;
create function public.submit_missed_punch(p_date date,p_action text,p_actual timestamptz,p_break_end timestamptz,p_reason text,p_key uuid) returns uuid language plpgsql security definer set search_path='' as $$declare emp uuid:=private.payroll_actor_id();mgr uuid;rid uuid;old public.attendance_punch_requests;begin
 if emp is null then raise exception 'Sign in required' using errcode='42501';end if;
 select * into old from public.attendance_punch_requests where employee_id=emp and request_key=p_key;if old.id is not null then if old.work_date=p_date and old.action=p_action and old.actual_time=p_actual and old.break_end is not distinct from p_break_end and old.reason=p_reason then return old.id;end if;raise exception 'Request identifier already used';end if;
 mgr:=private.punch_direct_manager(emp);if mgr is null then raise exception 'Ask HR to set your Direct Reporting To manager before submitting.';end if;
 if p_date is null or p_date>(clock_timestamp() at time zone 'Asia/Manila')::date or p_actual is null or p_actual>clock_timestamp() or p_actual<(p_date::timestamp at time zone 'Asia/Manila') or p_actual>=((p_date+2)::timestamp at time zone 'Asia/Manila') then raise exception 'Enter an actual past time within the work day or overnight next day.';end if;
 if p_break_end is not null and (p_action<>'START_BREAK' or p_break_end<=p_actual or p_break_end>clock_timestamp() or p_break_end>=((p_date+2)::timestamp at time zone 'Asia/Manila')) then raise exception 'Enter a valid actual break end after its start.';end if;
 insert into public.attendance_punch_requests(employee_id,manager_id,work_date,action,actual_time,break_end,reason,request_key) values(emp,mgr,p_date,p_action,p_actual,p_break_end,p_reason,p_key) returning id into rid;
 insert into public.attendance_punch_request_audit(request_id,action,actor,note) values(rid,'submitted',emp,p_reason);
 insert into public.notifications(user_id,type,title,message,link,related_entity_id,dedupe_key) values(mgr::text,'info','Missed punch approval','A direct report submitted an attendance correction for your review.','/payroll/missed-punches',rid::text,'missed-punch:'||rid::text);
 return rid;end $$;
create function public.get_missed_punches() returns jsonb language plpgsql stable security definer set search_path='' as $$declare actor uuid:=private.payroll_actor_id();begin
 if actor is null then raise exception 'Sign in required' using errcode='42501';end if;
 return(select coalesce(jsonb_agg(to_jsonb(r)||jsonb_build_object('employeeName',(select full_name from public.hris_users where id=r.employee_id),'canApprove',r.status='pending' and r.manager_id=actor and private.punch_direct_manager(r.employee_id)=actor,'canApply',r.status='approved' and private.attendance_admin() and public.can_access_hris_user(r.employee_id),'audit',(select coalesce(jsonb_agg(to_jsonb(a) order by created_at),'[]') from public.attendance_punch_request_audit a where a.request_id=r.id)) order by r.created_at desc),'[]') from public.attendance_punch_requests r where r.employee_id=actor or (r.manager_id=actor and private.punch_direct_manager(r.employee_id)=actor) or (private.attendance_admin() and public.can_access_hris_user(r.employee_id)));end $$;
create function public.review_missed_punch(p_id uuid,p_approve boolean,p_note text) returns void language plpgsql security definer set search_path='' as $$declare r public.attendance_punch_requests;actor uuid:=private.payroll_actor_id();begin
 select * into r from public.attendance_punch_requests where id=p_id for update;
 if actor is null or r.id is null or r.employee_id=actor or r.manager_id<>actor or private.punch_direct_manager(r.employee_id) is distinct from actor then raise exception 'Assigned direct manager approval required' using errcode='42501';end if;
 if r.status<>'pending' or p_approve is null or length(trim(coalesce(p_note,'')))<3 then raise exception 'Request already reviewed or review note missing';end if;
 update public.attendance_punch_requests set status=case when p_approve then 'approved' else 'rejected' end where id=p_id;
 insert into public.attendance_punch_request_audit(request_id,action,actor,note) values(p_id,case when p_approve then 'approved' else 'rejected' end,actor,p_note);
 insert into public.notifications(user_id,type,title,message,link,related_entity_id,dedupe_key) values(r.employee_id::text,'info','Missed punch reviewed',case when p_approve then 'Your manager approved the request. HR will apply it through attendance review.' else 'Your request was declined. Open it for the review note.' end,'/payroll/missed-punches',p_id::text,'missed-punch-review:'||p_id::text);
end $$;
create function public.complete_missed_punch(p_id uuid) returns void language plpgsql security definer set search_path='' as $$declare r public.attendance_punch_requests;a public.attendance_clock_adjustments;begin
 select * into r from public.attendance_punch_requests where id=p_id for update;
 if r.id is null or not private.attendance_admin() or not public.can_access_hris_user(r.employee_id) then raise exception 'Scoped HR attendance review required' using errcode='42501';end if;
 if r.status='applied' then return;end if;if r.status<>'approved' then raise exception 'Manager approval required';end if;
 select x.* into a from public.attendance_clock_adjustments x join public.attendance_clock_sessions s on s.id=x.session_id where s.employee_id=r.employee_id and s.work_date=r.work_date order by x.revision desc limit 1;
 if a.id is null or a.created_at<r.created_at or not exists(select 1 from jsonb_array_elements(a.events) e where e->>'type'=r.action and (e->>'timestamp')::timestamptz=r.actual_time) or (r.break_end is not null and not exists(select 1 from jsonb_array_elements(a.events) e where e->>'type'='END_BREAK' and (e->>'timestamp')::timestamptz=r.break_end)) then raise exception 'Apply the approved actual times in HR attendance review first';end if;
 update public.attendance_punch_requests set status='applied' where id=p_id;
 insert into public.attendance_punch_request_audit(request_id,action,actor,note,adjustment_id) values(p_id,'applied',public.current_hris_user_id(),'Linked to HR correction version',a.id);
end $$;
create function private.prevent_duplicate_shift_assignment() returns trigger language plpgsql security definer set search_path='' as $$begin
 if tg_op='UPDATE' and new.employee_id=old.employee_id and new.date=old.date and new.shift_template_id=old.shift_template_id then return new;end if;
 if exists(select 1 from public.shift_assignments a where a.employee_id=new.employee_id and a.date=new.date and a.shift_template_id=new.shift_template_id and a.id<>new.id) then raise exception 'This shift is already assigned to this employee on this date. Refresh the roster.';end if;return new;end $$;
create trigger prevent_duplicate_shift_assignment before insert or update on public.shift_assignments for each row execute function private.prevent_duplicate_shift_assignment();
revoke all on function private.punch_direct_manager(uuid),private.prevent_duplicate_shift_assignment() from public,anon,authenticated;
revoke all on function public.submit_missed_punch(date,text,timestamptz,timestamptz,text,uuid),public.get_missed_punches(),public.review_missed_punch(uuid,boolean,text),public.complete_missed_punch(uuid) from public,anon;
grant execute on function public.submit_missed_punch(date,text,timestamptz,timestamptz,text,uuid),public.get_missed_punches(),public.review_missed_punch(uuid,boolean,text),public.complete_missed_punch(uuid) to authenticated;
notify pgrst,'reload schema';
