create table public.attendance_kiosk_pairings(id uuid primary key default gen_random_uuid(),device_id uuid not null references public.attendance_devices(id),token_hash text not null unique,expires_at timestamptz not null,created_by uuid not null references public.hris_users(id),created_at timestamptz not null default clock_timestamp());
alter table public.attendance_kiosk_pairings enable row level security;revoke all on public.attendance_kiosk_pairings from public,anon,authenticated;
create trigger immutable before update or delete on public.attendance_kiosk_pairings for each row execute function private.payroll_audit_immutable();
create function public.pair_attendance_kiosk(p_device uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare d public.attendance_devices;t text:=encode(extensions.gen_random_bytes(24),'hex');exp timestamptz:=clock_timestamp()+interval '8 hours';begin select * into d from public.attendance_devices where id=p_device;if not private.attendance_bu_admin(d.business_unit_id) then raise exception 'Scoped HR/Admin access required' using errcode='42501';end if;if not d.active or d.kind<>'qr' then raise exception 'Choose an active QR kiosk';end if;perform pg_advisory_xact_lock(hashtextextended('attendance-kiosk:'||d.id::text,0));insert into public.attendance_kiosk_pairings(device_id,token_hash,expires_at,created_by) values(d.id,encode(extensions.digest(t,'sha256'),'hex'),exp,public.current_hris_user_id());return jsonb_build_object('token',t,'expiresAt',exp);end $$;
create function public.get_attendance_kiosk_display(p_pair_token text) returns jsonb language plpgsql security definer set search_path='' as $$declare p public.attendance_kiosk_pairings;d public.attendance_devices;t text;exp timestamptz;begin
 select * into p from public.attendance_kiosk_pairings where token_hash=encode(extensions.digest(coalesce(p_pair_token,''),'sha256'),'hex');select * into d from public.attendance_devices where id=p.device_id;
 if p.id is null or p.expires_at<=clock_timestamp() or not d.active or d.kind<>'qr' or not(private.attendance_channel_config(d.business_unit_id)->>'qr_enabled')::boolean or exists(select 1 from public.attendance_kiosk_pairings n where n.device_id=d.id and n.created_at>p.created_at) then raise exception 'Kiosk pairing expired or disabled. Ask HR/Admin to pair it again.' using errcode='42501';end if;
 perform pg_advisory_xact_lock(hashtextextended('attendance-kiosk:'||d.id::text,0));if exists(select 1 from public.attendance_qr_challenges where device_id=d.id and created_at>clock_timestamp()-interval '10 seconds') then raise exception 'Kiosk code refreshed recently. Try again shortly.';end if;
 t:=encode(extensions.gen_random_bytes(24),'hex');exp:=clock_timestamp()+interval '60 seconds';insert into public.attendance_qr_challenges(device_id,token_hash,expires_at,created_by) values(d.id,encode(extensions.digest(t,'sha256'),'hex'),exp,p.created_by);return jsonb_build_object('token',t,'expiresAt',exp,'serverTime',clock_timestamp(),'site',d.name);
end $$;
revoke all on function public.pair_attendance_kiosk(uuid) from public,anon,authenticated;grant execute on function public.pair_attendance_kiosk(uuid) to authenticated;
revoke all on function public.get_attendance_kiosk_display(text) from public,anon,authenticated;grant execute on function public.get_attendance_kiosk_display(text) to anon,authenticated;
notify pgrst,'reload schema';
