import React, {useEffect, useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../../services/supabaseClient';

type Person={id:string;name:string;businessUnit:string;businessUnitId:string;department:string;exempt:boolean;complete:boolean;missingDates:string[];publication:string;days:{date:string;status:string}[]};
type Task={managerId:string;managerName:string;week:string;deadline:string;required:number;completed:number;remaining:number;exempt:number;percentage:number;status:string;employees:Person[];hr:boolean;overdueTasks?:Task[]};
const box='mb-5 rounded-2xl border border-slate-200 bg-white p-5 text-slate-900 dark:border-slate-700 dark:bg-slate-800 dark:text-white';
const input='min-h-11 rounded-lg border border-slate-300 bg-white p-2 text-slate-900 dark:border-slate-600 dark:bg-slate-900 dark:text-white';
const button='inline-flex min-h-11 items-center justify-center rounded-lg bg-violet-600 px-4 py-2 font-semibold text-white disabled:opacity-50';
const date=(s:string)=>new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',month:'short',day:'numeric',year:'numeric'}).format(new Date(s.length===10?s+'T00:00:00+08:00':s));
const deadline=(s:string)=>new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',weekday:'long',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(s));
const scheduleLink=(t:Task)=>`/payroll/timekeeping?week=${t.week}&manager=${t.managerId}`;
async function call(name:string,args:Record<string,unknown>={}){const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message);return data;}

export function ScheduleTask({week,manager,refresh=0,details=false}:{week?:string;manager?:string;refresh?:number;details?:boolean}){
 const [task,setTask]=useState<Task|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;const load=()=>{void call('get_schedule_compliance',{p_week:week||null,p_manager:manager||null}).then(x=>{if(active){setTask(x);setError('');}}).catch(e=>{if(active)setError(e.message);});};load();window.addEventListener('focus',load);return()=>{active=false;window.removeEventListener('focus',load);};},[week,manager,refresh,retry]);
 if(error)return <div className={box} role="alert">Schedule task could not be checked: {error} <button className="underline" onClick={()=>setRetry(v=>v+1)}>Retry</button></div>;
 if(!task)return null;
 const hasOverdueAction=Boolean(task.overdueTasks?.some(t=>t.remaining>0));
 const hasCurrentAction=task.required>0&&task.remaining>0;
 // Completed schedule tasks should leave the dashboard. Keep the card only when
 // this week's work is still outstanding or an older overdue week needs action.
 if(!details&&!hasCurrentAction&&!hasOverdueAction)return task.hr?<div className="mb-4"><Link className="font-semibold text-violet-600 dark:text-violet-300" to="/payroll/schedule-compliance">Schedule Compliance →</Link></div>:null;
 const urgent=['Overdue','Due Today','Due Tomorrow'].includes(task.status)||Boolean(task.overdueTasks?.some(t=>t.remaining>0));
 const overdue=task.status==='Overdue'||Boolean(task.overdueTasks?.some(t=>t.remaining>0));
 return <section id="schedule-task" className={urgent?'mb-5 rounded-2xl border-2 border-red-500 bg-red-50 p-5 text-slate-900 dark:border-red-400 dark:bg-red-950/30 dark:text-white':box}>
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{urgent&&<span aria-label="Urgent" className="mr-2 text-red-600 dark:text-red-300">⚠</span>}{details?'Employee Schedule Progress':'Complete Next Week’s Employee Schedules'}</h2><p className="mt-1">Week of {date(task.week)} · Monday–Sunday</p></div><span className={`rounded-full px-3 py-1 text-sm font-semibold ${urgent?'bg-red-100 text-red-900 dark:bg-red-900 dark:text-red-100':'bg-violet-100 text-violet-900'}`}>{urgent?(overdue?'OVERDUE':'URGENT'):task.status}</span></div>
  {task.overdueTasks?.filter(t=>t.remaining>0).map(t=><p className="mt-3 font-semibold text-orange-700 dark:text-orange-300" key={t.week}>Overdue: week of {date(t.week)} · {t.remaining} employees remaining. <Link className="underline" to={scheduleLink(t)}>Complete schedules</Link></p>)}
  <p className="mt-4 text-xl font-semibold">{task.completed} of {task.required} completed · {task.remaining} remaining</p>
  <progress className="mt-3 h-3 w-full accent-violet-600" max={100} value={task.percentage} aria-label="Saved schedule completion"/>
  <p className="mt-2">{task.percentage}% complete · {task.exempt} exempt employees excluded</p><p className={urgent?"mt-2 text-red-800 dark:text-red-200":"mt-2"}>Deadline: <strong>{deadline(task.deadline)} Philippine time</strong></p>
  <div className="mt-4 flex flex-wrap items-center gap-4"><Link className={button} to={scheduleLink(task)}>Set Schedules</Link>{task.hr&&<Link className="underline" to="/payroll/schedule-compliance">Schedule Compliance</Link>}<button className="underline" onClick={()=>setRetry(v=>v+1)}>Refresh progress</button>{details&&task.hr&&<Link className="underline" to="/payroll/clocking-exceptions">Clock-in exemptions</Link>}</div>
  {details&&task.hr&&<p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Employees exempt from clock-in/out are also excluded from scheduling requirements for their exempt dates.</p>}
 </section>;
}

export default function CompliancePage(){
 const [deliveries,setDeliveries]=useState<any[]>([]),[notice,setNotice]=useState('');
 const [week,setWeek]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 const [bu,setBu]=useState(''),[manager,setManager]=useState(''),[status,setStatus]=useState('');
 const [days,setDays]=useState(2),[time,setTime]=useState('23:59'),[reason,setReason]=useState('');
 const [employee,setEmployee]=useState(''),[from,setFrom]=useState(''),[until,setUntil]=useState(''),[exempt,setExempt]=useState(true),[exemptionReason,setExemptionReason]=useState('');
 useEffect(()=>{let active=true;setError('');void call('get_schedule_compliance_report',{p_week:week||null}).then(x=>{if(active){setData(x);setDays(x.settings.days_before);setTime(x.settings.deadline_time.slice(0,5));}}).catch(e=>{if(active){setData(null);setError(e.message);}});return()=>{active=false;};},[week,revision]);
 useEffect(()=>{let active=true;void call('get_schedule_compliance_deliveries').then(x=>{if(active)setDeliveries(x);}).catch(()=>{});return()=>{active=false;};},[revision]);
 async function save(name:string,args:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{await call(name,args);setNotice(name==='request_schedule_compliance_reminder'?'Reminder queued for the next daily email run.':'Saved successfully.');setRevision(x=>x+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const rows:Task[]=data?.rows||[];
 const units=[...new Set(rows.flatMap(r=>r.employees.map(e=>e.businessUnit)).filter(Boolean))].sort();
 const people=[...new Map(rows.flatMap(r=>r.employees).map(e=>[e.id,e])).values()];
 const filtered=rows.filter(r=>(!manager||r.managerId===manager)&&(!bu||r.employees.some(e=>e.businessUnit===bu))&&(!status||(status==='Exempt'?r.exempt>0:r.status===status)));
 return <main><h1 className="mb-4 text-2xl font-bold">Schedule Compliance</h1><SuspensionStatusReport />{error&&<p className={`${box} text-red-700 dark:text-red-300`} role="alert">{error}</p>}
 {notice&&<p role="status" className={box}>{notice}</p>}
 {!data?<p>{error?'Access could not be loaded.':'Loading authorized schedule compliance…'}</p>:<>
 <details className={box}><summary>Email delivery history</summary><p className="my-2 text-sm">Daily at 8 AM Philippine time. Sent means accepted by the email provider. Up to five retries use the same delivery key.</p>{deliveries.map((d,i)=><p className="py-2" key={i}>{d.recipient} · {d.week} · {d.event} · {d.status} · {d.attempts} attempts {d.error&&`· ${d.error}`}</p>)}</details>
 <section className={box}><div className="flex flex-wrap gap-5">{[['Required',rows.filter(r=>r.required>0).length],['Completed',rows.filter(r=>r.status==='Completed').length],['In progress',rows.filter(r=>r.completed>0&&r.remaining>0).length],['Overdue',rows.filter(r=>r.status==='Overdue').length],['No scheduling required',rows.filter(r=>!r.required).length],['Employees missing schedules',rows.reduce((n,r)=>n+r.remaining,0)]].map(([label,n])=><p key={label}><strong className="block text-2xl">{n}</strong>{label}</p>)}</div>
 <details className="mt-4"><summary>Completion by business unit</summary>{units.map(unit=>{const es=people.filter(e=>e.businessUnit===unit&&!e.exempt);return <p key={unit}>{unit}: {es.filter(e=>e.complete).length} of {es.length} · {es.length?Math.round(100*es.filter(e=>e.complete).length/es.length):0}%</p>;})}</details></section>
 <section className={box}><div className="flex flex-wrap gap-3"><label>Schedule week <input className={input} type="date" value={week} onChange={e=>setWeek(e.target.value)}/></label><select aria-label="Business unit" className={input} value={bu} onChange={e=>setBu(e.target.value)}><option value="">All business units</option>{units.map(u=><option key={u}>{u}</option>)}</select><select aria-label="Manager" className={input} value={manager} onChange={e=>setManager(e.target.value)}><option value="">All managers</option>{rows.map(r=><option key={r.managerId} value={r.managerId}>{r.managerName}</option>)}</select><select aria-label="Status" className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['Not Started','In Progress','Completed','Due Today','Due Tomorrow','Overdue','Exempt','No Scheduling Required'].map(s=><option key={s}>{s}</option>)}</select></div></section>
 {filtered.map(r=><section className={box} key={r.managerId}><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-bold">{r.managerName} · {r.status}</h2><span>{r.completed}/{r.required} · {r.percentage}%</span></div><p>{date(r.week)} · Deadline {deadline(r.deadline)} Philippine time</p><p>{[...new Set(r.employees.filter(e=>!e.exempt).map(e=>e.businessUnit))].join(' · ')}</p><div className="my-3 flex gap-3"><Link className={button} to={scheduleLink(r)}>Open Schedule Manager</Link><button className={button} disabled={busy||!r.remaining} onClick={()=>save('request_schedule_compliance_reminder',{p_manager:r.managerId,p_week:r.week})}>Send Reminder</button></div><details><summary>Employees and missing dates · {r.exempt} excluded</summary>{r.employees.filter(e=>!e.exempt).map(e=><p className="mt-2" key={e.id}><strong>{e.name}</strong> · {e.businessUnit} · {e.complete?'Completed':e.missingDates.join(', ')} · {e.publication}</p>)}{!r.employees.some(e=>!e.exempt)&&<p className="mt-2 text-sm">No employees require schedules for this week.</p>}</details></section>)}
 <section className={box}><h2 className="text-lg font-bold">HR scheduling controls</h2><p className="mb-3">Deadline changes apply to newly opened periods. Existing deadlines and payroll rules stay unchanged.</p><div className="flex flex-wrap gap-3"><label>Days before Monday <input className={input} type="number" min={1} max={7} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label>Philippine time <input className={input} type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><input className={input} aria-label="Deadline change reason" placeholder="Change reason" value={reason} onChange={e=>setReason(e.target.value)}/><button className={button} disabled={busy||reason.trim().length<3} onClick={()=>save('save_schedule_compliance_setting',{p_days:days,p_time:time,p_reason:reason})}>Save deadline</button></div><p className="mt-2 text-sm">Last changed: {date(data.settings.changed_at)} · {data.settings.changed_by||'Default configuration'}</p>
 <h3 className="mt-6 font-bold">Scheduling exemption</h3><div className="mt-3 flex flex-wrap gap-3"><select className={input} aria-label="Employee" value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">Select employee</option>{people.map(e=><option key={e.id} value={e.id}>{e.name} · {e.businessUnit}</option>)}</select><label>Effective date <input className={input} type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Expiry (optional) <input className={input} type="date" value={until} onChange={e=>setUntil(e.target.value)}/></label><select className={input} aria-label="Exemption action" value={String(exempt)} onChange={e=>setExempt(e.target.value==='true')}><option value="true">Grant exemption</option><option value="false">Remove exemption</option></select><input className={input} aria-label="Exemption reason" placeholder="Required reason" value={exemptionReason} onChange={e=>setExemptionReason(e.target.value)}/><button className={button} disabled={busy||!employee||!from||exemptionReason.trim().length<3} onClick={()=>save('save_schedule_exemption',{p_employee:employee,p_from:from,p_to:until||null,p_exempt:exempt,p_reason:exemptionReason})}>Record HR decision</button></div>
 <details className="mt-4"><summary>Exemption audit history</summary>{data.exemptions.map((e:any)=><p className="mt-2" key={e.id}>{people.find(p=>p.id===e.employee_id)?.name||e.employee_id} · {e.exempt?'Granted':'Removed'} · {e.effective_from} to {e.effective_to||'No expiry'} · {e.reason} · {date(e.approved_at)}</p>)}</details></section>
 </> }</main>;
}
import SuspensionStatusReport from '../../components/payroll/SuspensionStatusReport';
