import React, { useState } from 'react';
import Modal from '../../components/ui/Modal';
import { operationsRpc } from './service';
import type { OpsPriority, OpsWorkspace } from './types';
import { buttonClass, primaryClass, inputClass, Field } from './ui';
import { manilaDay } from './presentation';
interface Props { workspace: OpsWorkspace; unit: string; initialVersion?: string; onClose: () => void; onSaved: () => Promise<void> }
export default function AssignmentEditor({workspace,unit,initialVersion,onClose,onSaved}: Props) {
  const [version,setVersion]=useState(initialVersion||''),[mode,setMode]=useState(workspace.masterAdmin?'bum':'individual'),[ids,setIds]=useState<string[]>([]),[value,setValue]=useState('');
  const [due,setDue]=useState(manilaDay(new Date())+'T17:00'),[priority,setPriority]=useState<OpsPriority>('Normal'),[instructions,setInstructions]=useState(''),[verify,setVerify]=useState(false);
  const [attachments,setAttachments]=useState<{name:string;url:string}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [execution,setExecution]=useState('shared');
  const [assetFilter,setAssetFilter]=useState('');
  const templates=workspace.templates.filter(t=>t.status==='Published');
  const matchesAsset=(t: typeof templates[number],assetId:string)=>t.versions[0]?.content.asset_id===assetId||t.versions[0]?.items.some(item=>item.snapshot.asset_id===assetId);
  const filteredTemplates=assetFilter?templates.filter(t=>matchesAsset(t,assetFilter)):templates;
  const isChecklist=templates.some(t=>t.kind==='checklist'&&t.versions[0]?.id===version);
  const people=workspace.people.filter(p=>p.can_assign&&(mode!=='bum'||p.bum));
  const selected=mode==='individual'||mode==='bum'?people.filter(p=>ids.includes(p.id)):people.filter(p=>mode==='department'?p.department_id===value:mode==='role'?p.roles.includes(value):p.position===value);
  async function submit(){setBusy(true);setError('');try {await operationsRpc('ops_assign',{p_unit:unit,p_version:version,p_selection:{mode,ids,value,execution:isChecklist?execution:'individual',phase:'2'},p_due:new Date(due+':00+08:00').toISOString(),p_priority:priority,p_instructions:instructions,p_attachments:attachments,p_verify:verify});await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal isOpen onClose={onClose} title="Assign work" size="3xl" viewportFit><form className="space-y-5" onSubmit={e=>{e.preventDefault();void submit();}}>
    <p className="text-sm text-slate-500">Select the staff working that day. Dates and times use Asia/Manila.</p>
    <Field label="Maintenance asset"><select aria-label="Maintenance asset" className={inputClass} value={assetFilter} onChange={e=>{const assetId=e.target.value;setAssetFilter(assetId);if(assetId&&!templates.some(t=>t.versions[0]?.id===version&&matchesAsset(t,assetId)))setVersion('');}}><option value="">All tasks and checklists</option>{workspace.assets.map(asset=><option key={asset.id} value={asset.id}>{asset.name}</option>)}</select><p className="mt-1 text-xs text-slate-500">Choose equipment to find its linked tasks and checklists. Only assets marked Requires maintenance in this unit appear.</p></Field>
    <Field label="Published task or checklist"><select aria-label="Published task or checklist" className={inputClass} required value={version} onChange={e=>setVersion(e.target.value)}><option value="">Choose from library</option>{filteredTemplates.map(t=><option key={t.id} value={t.versions[0]?.id}>{t.versions[0]?.content.title} · {t.kind} v{t.latest_version}{!t.business_unit_id?' · Master':''}</option>)}</select>{assetFilter&&!filteredTemplates.length&&<p className="mt-1 text-sm text-slate-500">No published work is linked to this asset yet. Create a task in Task Library and select its Linked maintenance asset.</p>}</Field>
    {isChecklist&&<Field label="Checklist completion"><select className={inputClass} value={execution} onChange={e=>setExecution(e.target.value)}><option value="shared">Shared team checklist — one set of checks</option><option value="individual">Separate checklist per employee</option></select><p className="mt-2 text-sm text-slate-500">{execution==='shared'?'All selected staff share progress. Every check and uncheck records who did it and when. Create a new assignment for each day or shift.':'Each employee saves and submits their own checklist independently.'}</p></Field>}
    <Field label="Assign by"><select className={inputClass} value={mode} onChange={e=>{setMode(e.target.value);setIds([]);setValue('');}}>{['individual','department','position','role',...(workspace.masterAdmin?['bum']:[])].map(x=><option key={x} value={x}>{x==='bum'?'Business Unit Managers':x[0].toUpperCase()+x.slice(1)}</option>)}</select></Field>
    {(mode==='individual'||mode==='bum')?<div className="max-h-56 space-y-1 overflow-y-auto rounded-xl border p-3 dark:border-slate-700">{people.length?people.map(p=><label key={p.id} className="flex min-h-11 items-center gap-3 rounded-lg px-2 hover:bg-violet-50 dark:hover:bg-slate-800"><input type="checkbox" checked={ids.includes(p.id)} onChange={e=>setIds(e.target.checked?[...ids,p.id]:ids.filter(x=>x!==p.id))}/><span>{p.name}{' '}<small className="ml-2 text-slate-500">{p.position}</small></span></label>):<p>No eligible employees in this workspace.</p>}</div>:<Field label={mode==='department'?'Department':mode==='role'?'HRIS role':'Position'}><select className={inputClass} required value={value} onChange={e=>setValue(e.target.value)}><option value="">Choose {mode}</option>{mode==='department'?workspace.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>):Array.from(new Set(people.flatMap(p=>mode==='role'?p.roles:[p.position]).filter(Boolean))).sort().map(p=><option key={p}>{p}</option>)}</select></Field>}
    <p className="text-sm font-semibold text-violet-700 dark:text-violet-300">{selected.length} eligible recipient{selected.length===1?'':'s'}</p>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Due date and time (Manila)"><input className={inputClass} type="datetime-local" required value={due} onChange={e=>setDue(e.target.value)}/></Field><Field label="Priority"><select className={inputClass} value={priority} onChange={e=>setPriority(e.target.value as OpsPriority)}>{['Low','Normal','High','Urgent'].map(x=><option key={x}>{x}</option>)}</select></Field></div>
    <Field label="Additional instructions"><textarea rows={3} className={inputClass} value={instructions} onChange={e=>setInstructions(e.target.value)}/></Field>
    <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-semibold">Attachments</h3><button type="button" className={buttonClass} disabled={attachments.length>=20} onClick={()=>setAttachments([...attachments,{name:'',url:''}])}>Add link</button></div><p className="text-xs text-slate-500">Use existing document or manual links. File and employee evidence uploads come in later phases.</p>{attachments.map((a,i)=><div key={i} className="grid gap-2 sm:grid-cols-[1fr_2fr_auto]"><input aria-label={`Attachment ${i+1} name`} className={inputClass} placeholder="Document name" required value={a.name} onChange={e=>setAttachments(attachments.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input aria-label={`Attachment ${i+1} URL`} type="url" className={inputClass} required placeholder="https://…" value={a.url} onChange={e=>setAttachments(attachments.map((x,j)=>j===i?{...x,url:e.target.value}:x))}/><button type="button" className={buttonClass} onClick={()=>setAttachments(attachments.filter((_,j)=>j!==i))}>Remove</button></div>)}</div>
    <label className="flex items-start gap-3 rounded-xl bg-violet-50 p-4 text-sm dark:bg-violet-950/30"><input type="checkbox" className="mt-1" checked={verify} onChange={e=>setVerify(e.target.checked)}/><span>Flag for future supervisor verification. Submission records completion and evidence; it does not record independent approval.</span></label>
    {error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}
    <div className="flex justify-end gap-3"><button type="button" className={buttonClass} onClick={onClose}>Cancel</button><button className={primaryClass} disabled={busy||!selected.length||!version}>{busy?'Assigning…':`Assign to ${selected.length}`}</button></div>
  </form></Modal>;
}
