import React, { useState } from 'react';
import ExecutionPanel from './ExecutionPanel';
import Modal from '../../components/ui/Modal';
import type { OpsAssignment, OpsWorkspace } from './types';
import { buttonClass, primaryClass, inputClass, Field } from './ui';
import { formatDue, isOpen, safeUrl, manilaDay, assignmentTitle } from './presentation';
import { operationsRpc } from './service';
export default function AssignmentDetail({assignment:a,workspace,onClose,onSaved}: {assignment:OpsAssignment;workspace:OpsWorkspace;onClose:()=>void;onSaved:()=>Promise<void>}) {
  const [note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [hasUnsaved,setHasUnsaved]=useState(false);
  const close=()=>{if(!hasUnsaved||window.confirm('Discard unsaved responses or photo previews? Saved responses will remain.'))onClose();};
  const mine=a.assignee_id===workspace.actor;
  const [editDue,setEditDue]=useState(manilaDay(a.due_at)+'T'+new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Manila',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(a.due_at)));
  const [editPriority,setEditPriority]=useState(a.priority),[editInstructions,setEditInstructions]=useState(a.instructions);
  async function check(item:string,revision:number,checked:boolean){setBusy(true);setError('');try{await operationsRpc('ops_check_item',{p_run:a.checklist_run_id,p_item:item,p_revision:revision,p_checked:checked,p_note:note});setNote('');await onSaved();}catch(e){setError((e as Error).message);await onSaved();}finally{setBusy(false);}}
  async function update(){setBusy(true);setError('');try{await operationsRpc('ops_update_assignment',{p_id:a.id,p_revision:a.revision,p_due:new Date(editDue+':00+08:00').toISOString(),p_priority:editPriority,p_instructions:editInstructions,p_note:note});await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function change(status:string) {setBusy(true);setError('');try{await operationsRpc('ops_change_assignment',{p_id:a.id,p_revision:a.revision,p_status:status,p_note:note});await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal isOpen onClose={close} title={assignmentTitle(a)} size="3xl" viewportFit><div className="space-y-5">
    <div className="flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-violet-100 px-3 py-1 text-violet-800">{a.status}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-slate-700">{a.priority} priority</span><span className="rounded-full border px-3 py-1">{a.kind} · version {a.version}</span></div>
    <dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Assignee</dt><dd className="font-semibold">{a.checklist_run_id?a.members?.map(m=>m.name).join(', '):a.assignee_name}</dd></div><div><dt className="text-slate-500">Business unit</dt><dd className="font-semibold">{a.unit_name}</dd></div><div><dt className="text-slate-500">Due (Manila)</dt><dd className="font-semibold">{formatDue(a.due_at)}</dd></div><div><dt className="text-slate-500">Assignment ID</dt><dd className="break-all text-xs">{a.id}</dd></div></dl>
    {a.maintenance&&<section className="space-y-2 rounded-2xl border border-violet-200 bg-violet-50 p-4 dark:bg-violet-950/30"><h3 className="font-semibold">Maintenance · {a.maintenance.name} · {a.maintenance.asset_tag}</h3><p className="text-sm">{a.maintenance.unit_name} · {[a.maintenance.type,a.maintenance.brand,a.maintenance.model,a.maintenance.serial_number].filter(Boolean).join(' · ')}</p><p className="text-sm">Responsible owner: {a.maintenance_owner||'Unassigned — review coverage'}</p><p className="whitespace-pre-wrap text-sm">{a.maintenance.maintenance.description}</p>{safeUrl(a.maintenance.maintenance.sop_url)&&<a className="text-sm font-semibold text-violet-700 underline" href={safeUrl(a.maintenance.maintenance.sop_url)} target="_blank" rel="noopener noreferrer">Maintenance manual / SOP ↗</a>}</section>}
    {a.content.description&&<p className="whitespace-pre-wrap">{a.content.description}</p>}
    {a.content.instructions&&<section><h3 className="font-semibold">Instructions</h3><p className="mt-2 whitespace-pre-wrap text-slate-600 dark:text-slate-300">{a.content.instructions}</p></section>}
    {safeUrl(a.content.sop_url)&&<a className="inline-block font-semibold text-violet-700 underline dark:text-violet-300" href={safeUrl(a.content.sop_url)} target="_blank" rel="noopener noreferrer">Open SOP / manual ↗</a>}
    {a.instructions&&<section className="rounded-xl bg-violet-50 p-4 dark:bg-violet-950/30"><h3 className="font-semibold">Assignment instructions</h3><p className="mt-1 whitespace-pre-wrap">{a.instructions}</p></section>}
    {a.execution&&<ExecutionPanel assignment={a} onSaved={onSaved} onDirtyChange={setHasUnsaved}/>}
    {!a.execution&&a.checklist_run_id&&<section className="space-y-3 rounded-xl bg-violet-50 p-4 dark:bg-violet-950/30"><h3 className="font-semibold">Shared team checklist · {a.checks?.filter(c=>c.checked).length||0} / {a.items.length} checked</h3><p className="text-sm">All assigned staff share these checks. Required items determine completion. Every check and uncheck is recorded below.</p>{(a.can_check||(a.can_cancel&&isOpen(a)))&&<Field label="Note / reason for unchecking or cancellation"><textarea className={inputClass} value={note} onChange={e=>setNote(e.target.value)} placeholder="Enter a reason before unchecking"/></Field>}</section>}
    {!a.execution&&!!a.items.length&&<div className="space-y-3"><h3 className="font-semibold">Published checklist · {a.items.length} tasks</h3>{a.items.map((i,index)=>{const state=a.checks?.find(c=>c.item_id===i.id);return <section key={i.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex flex-wrap justify-between gap-2"><label className="flex items-start gap-3 font-semibold">{a.checklist_run_id&&state&&<input type="checkbox" aria-label={`Check ${i.snapshot.title}`} className="mt-1 h-5 w-5 accent-violet-600" checked={state.checked} disabled={busy||!a.can_check||a.status==='Cancelled'} onChange={e=>void check(i.id,state.revision,e.target.checked)}/>}<strong>{index+1}. {i.snapshot.title}</strong></label><span className="text-xs text-slate-500">{i.required?'Required':'Optional'} · {a.checklist_run_id?'Confirmation':i.response_type}</span></div>{i.snapshot.safety_critical&&<p className="mt-1 font-semibold text-amber-700">Safety-critical</p>}<p className="mt-2 whitespace-pre-wrap text-sm text-slate-600 dark:text-slate-300">{i.snapshot.instructions||i.snapshot.description||'Follow the applicable operating procedure.'}</p>{safeUrl(i.snapshot.sop_url)&&<a href={safeUrl(i.snapshot.sop_url)} target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-sm font-semibold text-violet-700 underline dark:text-violet-300">Open SOP ↗</a>}{state?.updated_at&&<p className="mt-2 text-xs text-violet-700 dark:text-violet-300">{state.checked?'Checked':'Unchecked'} by {state.actor_name} · {formatDue(state.updated_at)}</p>}</section>;})}</div>}
    {a.content.safety_critical&&<p className="font-semibold text-amber-700">Safety-critical task</p>}
    <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600 dark:bg-slate-800 dark:text-slate-300">{a.execution?'Submission records completion and evidence. Supervisor approval is not recorded here.':<>Phase 1 captures a completion confirmation. Detailed text, photo, and numeric evidence will be collected in Phase 2. {a.requires_verification?'Supervisor verification is flagged for a future phase. Completion here is not independently approved.':''}</>}</p>
    {!!a.attachments.length&&<section><h3 className="font-semibold">Attachments</h3><ul className="mt-2 space-y-2">{a.attachments.map((x,i)=><li key={i}><a href={safeUrl(x.url)} target="_blank" rel="noopener noreferrer" className="font-semibold text-violet-700 underline dark:text-violet-300">{x.name} ↗</a></li>)}</ul></section>}
    {a.occurrence_id&&<p className="rounded-xl border border-violet-100 p-3 text-sm"><a className="font-semibold text-violet-700 underline" href="/operations?view=Coverage">Open coverage & responsibility</a> to manage recurring staffing, handovers and due times.</p>}
    {isOpen(a)&&<>{(!a.checklist_run_id||(a.execution&&a.can_cancel))&&<Field label="Completion note / cancellation reason"><textarea className={inputClass} value={note} onChange={e=>setNote(e.target.value)}/></Field>}{mine&&!a.checklist_run_id&&<label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I confirm I completed the assigned work and followed its instructions.</span></label>}<div className="flex flex-wrap gap-3">{mine&&!a.checklist_run_id&&a.status==='Assigned'&&<button className={buttonClass} disabled={busy} onClick={()=>void change('In Progress')}>Start task</button>}{mine&&!a.checklist_run_id&&<button className={primaryClass} disabled={busy||!confirmed} onClick={()=>void change('Completed')}>Confirm completed</button>}{a.can_cancel&&<button className={buttonClass} disabled={busy||note.trim().length<3} onClick={()=>void change('Cancelled')}>{a.execution?(a.execution.shared?'Cancel team assignment':'Cancel assignment'):a.checklist_run_id?'Cancel shared checklist':'Cancel assignment'}</button>}</div></>}
    {a.can_cancel&&isOpen(a)&&<details className="rounded-xl border p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">Change due date or assignment instructions</summary><div className="mt-4 space-y-3"><Field label="New due date / time (Manila)"><input type="datetime-local" className={inputClass} value={editDue} onChange={e=>setEditDue(e.target.value)}/></Field><Field label="Assignment priority"><select className={inputClass} value={editPriority} onChange={e=>setEditPriority(e.target.value as typeof editPriority)}>{['Low','Normal','High','Urgent'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Updated instructions"><textarea className={inputClass} value={editInstructions} onChange={e=>setEditInstructions(e.target.value)}/></Field><p className="text-xs text-slate-500">Enter a change reason in the note above. Published template instructions stay preserved.</p><button className={buttonClass} disabled={busy||!editDue||note.trim().length<3} onClick={()=>void update()}>Save assignment changes</button></div></details>}
    {error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}
    <details className="rounded-xl border p-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold">Audit trail</summary><ol className="mt-3 space-y-3">{a.history.map(h=><li key={h.id} className="border-l-2 border-violet-200 pl-3 text-sm"><strong>{h.action}</strong><p className="text-slate-500">{formatDue(h.created_at)} · {h.actor_name||workspace.people.find(p=>p.id===h.actor_id)?.name||(h.actor_id===workspace.actor?'You':h.actor_id)}</p>{h.detail.item_title&&<p>{h.detail.item_title}</p>}{h.detail.note&&<p>{h.detail.note}</p>}</li>)}</ol></details>
  </div></Modal>;
}
