import React,{useCallback,useEffect,useRef,useState} from 'react';
import Modal from '../../components/ui/Modal';
import type {OpsWorkspace} from './types';
import {operationsRpc} from './service';
import {buttonClass,primaryClass,inputClass,Field} from './ui';
import {manilaDay,formatDue} from './presentation';
export type Config={maintenance?:{asset_id:string;description:string;category:string;sop_url:string;estimated_minutes:number;responsible_manager_id:string};service_dates?:string[];annual_dates?:{month:number;day:number}[];times_per_year?:number;frequency:string;interval:number;start_date:string;end_date:string;mode:string;execution:string;timezone:string;anchor:string;start_time:string;end_time:string;due_time:string;end_day_offset:number;due_day_offset:number;employee_ids:string[];backup_ids:string[];preferred_owner:string;auto_backup:boolean;allow_claim:boolean;weekdays:number[];month_day:number;short_month:string;horizon_days:number;grace_minutes:number;remind_before:number;overdue_every:number;priority:string;department_id:string;position:string;role:string;reference_employee:string;start_offset:number;duration_minutes:number;due_offset:number;instructions:string;requires_verification:boolean;excluded_dates:string[]};
export type Rule={asset_id?:string|null;id:string;business_unit_id:string;title:string;template_version_id:string;config:Config;status:string;revision:number;last_error:string|null;last_success_at:string|null};
export type Availability={label:string;eligible:boolean;present:boolean;warning?:string;source?:string};
type Person={id:string;name:string;availability:Availability;assignment_id?:string;active?:boolean;confirmed_until?:string};
type Occurrence={id:string;rule_id:string;business_unit_id:string;operating_date:string;title:string;status:string;revision:number;coverage:string;coverage_reason:string;window_start:string;window_end:string;due_at:string;owner_id:string|null;owner_name:string|null;shared:boolean;can_manage:boolean;can_claim:boolean;staff:Person[];candidates:Person[];history:{id:string;action:string;actor_name:string;created_at:string;detail:{reason?:string;to?:string}}[]};
type Workspace={rules:Rule[];occurrences:Occurrence[];health:{last_success_at:string|null;last_error:string|null}|null};
export const defaults=():Config=>({frequency:'daily',interval:1,start_date:manilaDay(new Date()),end_date:'',mode:'shift',execution:'shared',timezone:'Asia/Manila',anchor:'fixed',start_time:'08:00',end_time:'12:00',due_time:'11:30',end_day_offset:0,due_day_offset:0,employee_ids:[],backup_ids:[],preferred_owner:'',auto_backup:false,allow_claim:true,weekdays:[1,2,3,4,5],month_day:1,short_month:'skip',horizon_days:7,grace_minutes:15,remind_before:30,overdue_every:120,priority:'Normal',department_id:'',position:'',role:'',reference_employee:'',start_offset:0,duration_minutes:60,due_offset:60,instructions:'',requires_verification:false,excluded_dates:[]});
export default function AutomationWorkspace({workspace,unit,rulesView,onOpen,onNavigate}:{workspace:OpsWorkspace;unit:string;rulesView:boolean;onOpen:(id:string)=>Promise<void>;onNavigate:(view:string)=>void}){
 const [date,setDate]=useState(manilaDay(new Date())),[data,setData]=useState<Workspace|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('All');
 const [editing,setEditing]=useState<Rule|null|undefined>(undefined),[selected,setSelected]=useState<Occurrence|null>(null),[employee,setEmployee]=useState(''),[note,setNote]=useState(''),[action,setAction]=useState('owner');
 const [timing,setTiming]=useState({start:'',end:'',due:''});const sequence=useRef(0);
 const canRules=!!unit&&!!workspace.units.find(u=>u.id===unit)?.assign&&!!workspace.units.find(u=>u.id===unit)?.edit;
 const load=useCallback(async()=>{const seq=++sequence.current;try{const next=await operationsRpc<Workspace>('ops_automation_workspace',{p_unit:unit||null,p_date:date});if(seq===sequence.current){setData(next);setError('');setSelected(prev=>prev?next.occurrences.find(o=>o.id===prev.id)||null:null);}}catch(e){if(seq===sequence.current)setError((e as Error).message);}},[unit,date]);
 useEffect(()=>{setData(null);void load();const refresh=()=>{if(document.visibilityState==='visible')void load();};const t=window.setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{sequence.current++;clearInterval(t);window.removeEventListener('focus',refresh);};},[load]);
 async function mutate(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await load();setSelected(null);setNote('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const rows=(data?.occurrences||[]).filter(o=>filter==='All'||(filter==='Open'?o.status==='Open':o.coverage===filter));
 return <div className="space-y-5">
  <div className="flex flex-wrap justify-between gap-3"><p className="max-w-xl text-sm text-slate-500">Published schedules determine who can take the work. A named owner takes responsibility for shared work; attendance confirms presence.</p>{(rulesView||workspace.units.some(u=>u.edit&&u.assign))&&<button className={buttonClass} onClick={()=>onNavigate(rulesView?'Coverage':'Scheduling')}>{rulesView?'Today’s coverage':'Recurring rules'}</button>}</div>
  {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}
  {rulesView?<>
   {!unit&&<p className="rounded-xl bg-violet-50 p-4">Select a business-unit workspace to configure recurring work.</p>}
   {canRules&&<button className={primaryClass} onClick={()=>setEditing(null)}>Create recurring rule</button>}
   <p className="text-xs text-slate-500">Backend automation runs every minute. Rules stay inactive until saved as Active. {data?.health?.last_success_at&&`Last worker success: ${formatDue(data.health.last_success_at)}`}</p>
   {data?.health?.last_error&&<p role="alert">Worker needs attention: {data.health.last_error}</p>}
   <div className="grid gap-4 xl:grid-cols-2">{data?.rules.filter(r=>!r.asset_id).map(r=><article key={r.id} className="space-y-3 rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><div className="flex justify-between gap-3"><h3 className="font-semibold">{r.title}</h3><span>{r.status}</span></div><p className="text-sm text-slate-500">{r.config.frequency} · every {r.config.interval} · {r.config.mode==='shift'?'Published-shift staffing':'Fixed employee pool'} · {r.config.execution} · revision {r.revision}</p>{r.last_error&&<p role="alert" className="text-sm text-red-700">{r.last_error}</p>}<p className="text-xs">{r.last_success_at?`Last generation: ${formatDue(r.last_success_at)}`:'Not generated yet'}</p><div className="flex flex-wrap gap-2"><button className={buttonClass} onClick={()=>setEditing(r)}>Edit / pause / archive</button><button className={buttonClass} disabled={busy} onClick={()=>void mutate(()=>operationsRpc('ops_retry_rule',{p_id:r.id}))}>Generate / retry now</button><button className={buttonClass} onClick={()=>setEditing({...r,id:'',revision:0,title:`${r.title} (copy)`,status:'Paused'})}>Duplicate rule</button></div></article>)}</div>
   {data&&!data.rules.length&&<p className="rounded-2xl border border-dashed p-8 text-center text-slate-500">No recurring rules yet. Manual assignments continue to work.</p>}
  </>:<>
   <div className="flex flex-wrap gap-3"><Field label="Operating date"><input aria-label="Operating date" className={inputClass} type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Coverage filter"><select aria-label="Coverage filter" className={inputClass} value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Open','Covered','Planned','Needs confirmation','No owner','Uncovered','Schedule missing','At risk','Completed','Skipped','Cancelled'].map(x=><option key={x}>{x}</option>)}</select></Field><button className={buttonClass} disabled={busy} onClick={()=>void load()}>Refresh coverage</button></div>
   <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Covered',data?.occurrences.filter(o=>o.coverage==='Covered').length||0],['Planned',data?.occurrences.filter(o=>o.coverage==='Planned').length||0],['Need attention',data?.occurrences.filter(o=>o.status==='Open'&&!['Covered','Planned'].includes(o.coverage)).length||0],['Completed',data?.occurrences.filter(o=>o.status==='Completed').length||0]].map(([label,n])=><div key={label} className="rounded-2xl border bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><span className="text-sm text-slate-500">{label}</span><strong className="mt-2 block text-2xl">{n}</strong></div>)}</div>
   <div className="grid gap-4 xl:grid-cols-2">{rows.map(o=><article key={o.id} className="space-y-3 rounded-2xl border bg-white p-5 dark:border-slate-700 dark:bg-slate-800"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="font-semibold">{o.title}</h3><span className={`rounded-full px-3 py-1 text-xs font-semibold ${['Covered','Completed'].includes(o.coverage)?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-800'}`}>{o.coverage}</span></div><p className="text-xs text-slate-500">{workspace.units.find(u=>u.id===o.business_unit_id)?.name} · operating date {o.operating_date}</p><p className="text-sm">{formatDue(o.window_start)} – {formatDue(o.window_end)}<br/>Due {formatDue(o.due_at)}</p><p className="text-sm font-semibold">Responsible: {o.shared?(o.owner_name||'No owner assigned'):'Each individual assignee'}</p><p className="text-sm text-slate-500">{o.coverage_reason}</p><ul className="space-y-2 text-sm">{o.staff.filter(s=>s.active).map(s=><li key={s.id} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><strong>{s.name}</strong><span className="block text-slate-500">{s.availability.label}{s.confirmed_until&&new Date(s.confirmed_until)>new Date()?' · Presence confirmed by manager':''}</span></li>)}</ul><div className="flex flex-wrap gap-2">{o.staff.some(s=>s.active&&(s.id===workspace.actor||o.can_manage))&&<button className={primaryClass} disabled={busy} onClick={()=>{const s=o.staff.find(s=>s.active&&s.id===workspace.actor)||o.staff.find(s=>s.active);if(s?.assignment_id)void onOpen(s.assignment_id).catch(e=>setError(e.message));}}>Open assigned work</button>}{o.can_claim&&o.status==='Open'&&<button className={buttonClass} disabled={busy} onClick={()=>void mutate(()=>operationsRpc('ops_occurrence_action',{p_id:o.id,p_revision:o.revision,p_action:'claim',p_employee:workspace.actor,p_note:'Claimed responsibility for this operating date',p_payload:{}}))}>Take responsibility</button>}<button className={buttonClass} onClick={()=>{setSelected(o);setEmployee(o.owner_id||'');setNote('');setAction('owner');setTiming({start:localTime(o.window_start),end:localTime(o.window_end),due:localTime(o.due_at)});}}>{o.can_manage&&o.status==='Open'?'Manage responsibility':'View history'}</button></div></article>)}</div>
   {data&&!rows.length&&<p className="rounded-2xl border border-dashed p-8 text-center text-slate-500">No authorized generated work for this date and filter.</p>}
  </>}
  {!data&&!error&&<p role="status">Loading recurring work…</p>}
  {editing!==undefined&&canRules&&<RuleEditor rule={editing} workspace={workspace} unit={unit} onClose={()=>setEditing(undefined)} onSaved={async()=>{setEditing(undefined);await load();}}/>}
  {selected&&<Modal isOpen title={`${selected.title} · responsibility`} onClose={()=>setSelected(null)} size="3xl" viewportFit><div className="space-y-4">
   {selected.can_manage&&selected.status==='Open'&&<><Field label="Responsibility action"><select aria-label="Responsibility action" className={inputClass} value={action} onChange={e=>setAction(e.target.value)}>{[['owner','Set owner (before execution)'],['handover','Handover started work'],['add','Add helper'],['remove','Remove helper'],['confirm','Confirm presence / flexible timing'],['reschedule','Reschedule this occurrence'],['skip','Skip occurrence'],['cancel','Cancel occurrence']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></Field>{!['skip','cancel','reschedule'].includes(action)&&<Field label="Responsible employee"><select aria-label="Responsible employee" className={inputClass} value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">Choose from authorized pool</option>{selected.candidates.map(p=><option key={p.id} value={p.id}>{p.name} · {p.availability.label}</option>)}</select></Field>}{action==='reschedule'&&<div className="grid gap-3 md:grid-cols-3">{(['start','end','due'] as const).map(k=><div key={k}><Field label={`New ${k} (Manila)`}><input aria-label={`New ${k} (Manila)`} type="datetime-local" className={inputClass} value={timing[k]} onChange={e=>setTiming({...timing,[k]:e.target.value})}/></Field></div>)}</div>}<Field label="Reason for change"><textarea aria-label="Reason for change" className={inputClass} value={note} onChange={e=>setNote(e.target.value)}/></Field><p className="text-xs text-slate-500">Handovers preserve answers, photos and their original authors. Presence confirmation is operational and does not modify attendance or payroll.</p><button className={primaryClass} disabled={busy||note.trim().length<3||(!['skip','cancel','reschedule'].includes(action)&&!employee)} onClick={()=>void mutate(()=>operationsRpc('ops_occurrence_action',{p_id:selected.id,p_revision:selected.revision,p_action:action,p_employee:employee||null,p_note:note,p_payload:action==='reschedule'?{start:timing.start+'+08:00',end:timing.end+'+08:00',due:timing.due+'+08:00'}:{}}))}>Save responsibility change</button></>}
   <details open><summary className="font-semibold">Responsibility audit trail</summary><ul className="mt-3 space-y-3">{selected.history.map(h=><li key={h.id} className="rounded-xl border p-3 text-sm"><strong>{h.action}</strong><p>{h.actor_name} · {formatDue(h.created_at)}</p><p className="text-slate-500">{h.detail.reason||h.detail.to||''}</p></li>)}</ul></details>
  </div></Modal>}
 </div>;
}
function localTime(value:string){return new Date(new Date(value).getTime()+8*60*60*1000).toISOString().slice(0,16);}
export function RuleEditor({rule,workspace,unit,onClose,onSaved,assets,managers}:{rule:Rule|null;workspace:OpsWorkspace;unit:string;onClose:()=>void;onSaved:()=>Promise<void>;assets?:{id:string;name:string;asset_tag:string}[];managers?:{id:string;name:string}[]}){
 const maintenance=!!assets;
 const [title,setTitle]=useState(rule?.title||''),[version,setVersion]=useState(rule?.template_version_id||''),[c,setC]=useState<Config>({...defaults(),...(maintenance?{mode:'shift',execution:'shared',anchor:'fixed',maintenance:{asset_id:assets?.[0]?.id||'',description:'',category:'Cleaning',sop_url:'',estimated_minutes:30,responsible_manager_id:workspace.people.find(p=>p.bum)?.id||managers?.[0]?.id||(workspace.masterAdmin?workspace.actor:'')}}:{}),...rule?.config}),[status,setStatus]=useState(rule?.status||(maintenance?'Draft':'Paused')),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<{date:string;window:{start:string;end:string;due:string;warning?:string};people:(Availability&{employee_id:string;name:string})[]}[]|null>(null);
 const set=<K extends keyof Config>(k:K,v:Config[K])=>{setC(prev=>({...prev,[k]:v}));setPreview(null);};
 const people=workspace.people.filter(p=>p.can_assign&&(!c.department_id||p.department_id===c.department_id)&&(!c.position||p.position===c.position)&&(!c.role||p.roles.includes(c.role)));
 const versions=workspace.templates.filter(t=>t.business_unit_id===unit||t.business_unit_id===null).flatMap(t=>t.versions.map(v=>({id:v.id,title:`${v.content.title} · published v${v.version}`})));
 async function run(save:boolean){setBusy(true);setError('');try{if(save){await operationsRpc('ops_save_rule',{p_id:rule?.id||null,p_unit:unit,p_title:title,p_version:version,p_config:c,p_status:status,p_revision:rule?.revision||null,p_note:reason});await onSaved();}else {const from=c.start_date>manilaDay(new Date())?c.start_date:manilaDay(new Date());const rows=await operationsRpc<{date:string;window:{start:string;end:string;due:string;warning?:string};people?:(Availability&{employee_id:string;name:string})[]}[]>(maintenance?'ops_maintenance_preview':'ops_preview_rule',{p_unit:unit,p_version:version,p_config:c,p_from:from,...(maintenance?{}:{p_days:14})});setPreview(rows.map(p=>({...p,people:p.people||[]})));}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const input=(label:string,key:keyof Config,type='text',min?:number,max?:number)=><Field label={label}><input aria-label={label} className={inputClass} type={type} min={min} max={max} value={String(c[key]??'')} onChange={e=>set(key,(type==='number'?Number(e.target.value):e.target.value) as never)}/></Field>;
 const choice=(label:string,key:keyof Config,options:[string,string][])=> <Field label={label}><select aria-label={label} className={inputClass} value={String(c[key])} onChange={e=>set(key,(key==='end_day_offset'||key==='due_day_offset'?Number(e.target.value):e.target.value) as never)}>{options.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></Field>;
 return <Modal isOpen title={maintenance?(rule?.id?'Edit maintenance plan':'Create maintenance plan'):(rule?.id?'Edit recurring rule':'Create recurring rule')} onClose={onClose} size="5xl" viewportFit><div className="space-y-5">
  {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}
  {maintenance&&<div className="grid gap-4 md:grid-cols-2"><Field label="Maintenance asset"><select aria-label="Maintenance asset" className={inputClass} disabled={!!rule?.id} value={c.maintenance?.asset_id||''} onChange={e=>set('maintenance',{...c.maintenance!,asset_id:e.target.value})}><option value="">Choose eligible asset</option>{assets?.map(a=><option key={a.id} value={a.id}>{a.name} · {a.asset_tag}</option>)}{rule?.id&&!assets?.some(a=>a.id===c.maintenance?.asset_id)&&<option value={c.maintenance?.asset_id}>Previously linked asset — blocked</option>}</select></Field><Field label="Activity category"><select aria-label="Activity category" className={inputClass} value={c.maintenance?.category} onChange={e=>set('maintenance',{...c.maintenance!,category:e.target.value})}>{['Cleaning','Inspection','Preventive Maintenance','Servicing','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Activity description"><textarea aria-label="Activity description" className={inputClass} value={c.maintenance?.description} onChange={e=>set('maintenance',{...c.maintenance!,description:e.target.value})}/></Field><Field label="Manual / SOP URL"><input aria-label="Manual / SOP URL" type="url" className={inputClass} value={c.maintenance?.sop_url} onChange={e=>set('maintenance',{...c.maintenance!,sop_url:e.target.value})}/></Field><Field label="Estimated minutes"><input aria-label="Estimated minutes" type="number" min="0" max="10080" className={inputClass} value={c.maintenance?.estimated_minutes} onChange={e=>set('maintenance',{...c.maintenance!,estimated_minutes:Number(e.target.value)})}/></Field><Field label="Responsible manager"><select aria-label="Responsible manager" className={inputClass} value={c.maintenance?.responsible_manager_id} onChange={e=>set('maintenance',{...c.maintenance!,responsible_manager_id:e.target.value})}><option value="">Choose a unit manager</option>{(managers||workspace.people.filter(p=>p.bum||p.roles.some(x=>['Admin','Board of Director','GeneralManager'].includes(x)))).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}{workspace.masterAdmin&&!workspace.people.some(p=>p.id===workspace.actor)&&<option value={workspace.actor}>You · TNG administrator</option>}</select></Field></div>}
  <div className="grid gap-4 md:grid-cols-2"><Field label="Rule title"><input aria-label="Rule title" className={inputClass} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Published task or checklist"><select aria-label="Published task or checklist" className={inputClass} value={version} onChange={e=>{setVersion(e.target.value);setPreview(null);}}><option value="">Choose a published version</option>{versions.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></Field>
   {choice('Frequency','frequency',[['daily','Every X days'],['weekly','Selected weekdays / every X weeks'],['monthly','Every X months'],['yearly','Yearly'],['dates','Specific calendar dates'],['annual_dates','X times per year — explicit dates'],['once','One time']])}{input('Repeat interval','interval','number',1,366)}{input('Start date','start_date','date')}{input('End date (optional)','end_date','date')}
   {['monthly','yearly','annual_dates'].includes(c.frequency)&&<>{c.frequency==='monthly'&&input('Day of month','month_day','number',1,31)}{choice('Short month behavior','short_month',[['skip','Skip unavailable date'],['last','Use last day of month']])}</>}
  </div>
  {c.frequency==='dates'&&<section className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">Explicit service dates</h3>{(c.service_dates||[]).map((date,i)=><div className="flex gap-2" key={i}><input aria-label={`Service date ${i+1}`} type="date" className={inputClass} value={date} onChange={e=>set('service_dates',c.service_dates!.map((d,j)=>i===j?e.target.value:d))}/><button className={buttonClass} onClick={()=>set('service_dates',c.service_dates!.filter((_,j)=>i!==j))}>Remove date</button></div>)}<button className={buttonClass} onClick={()=>set('service_dates',[...(c.service_dates||[]),c.start_date])}>Add calendar date</button></section>}
  {c.frequency==='annual_dates'&&<section className="space-y-3 rounded-xl border p-4"><Field label="Times per year"><input aria-label="Times per year" type="number" min="1" max="366" className={inputClass} value={c.times_per_year||1} onChange={e=>set('times_per_year',Number(e.target.value))}/></Field><p className="text-xs text-slate-500">Choose one actual month and day for each service. The preview shows calendar dates.</p>{(c.annual_dates||[]).map((d,i)=><div className="flex flex-wrap gap-2" key={i}><input aria-label={`Service month ${i+1}`} type="number" min="1" max="12" className={`${inputClass} !w-28`} value={d.month} onChange={e=>set('annual_dates',c.annual_dates!.map((x,j)=>j===i?{...x,month:Number(e.target.value)}:x))}/><input aria-label={`Service day ${i+1}`} type="number" min="1" max="31" className={`${inputClass} !w-28`} value={d.day} onChange={e=>set('annual_dates',c.annual_dates!.map((x,j)=>j===i?{...x,day:Number(e.target.value)}:x))}/><button className={buttonClass} onClick={()=>set('annual_dates',c.annual_dates!.filter((_,j)=>j!==i))}>Remove date</button></div>)}<button className={buttonClass} onClick={()=>set('annual_dates',[...(c.annual_dates||[]),{month:1,day:1}])}>Add service date</button></section>}
  {c.frequency==='weekly'&&<fieldset><legend className="text-sm font-medium">Operating weekdays</legend><div className="mt-2 flex flex-wrap gap-4">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((n,i)=><label key={n} className="flex gap-2"><input type="checkbox" checked={c.weekdays.includes(i+1)} onChange={e=>set('weekdays',e.target.checked?[...c.weekdays,i+1]:c.weekdays.filter(v=>v!==i+1))}/>{n}</label>)}</div></fieldset>}
  <Field label="Non-operating dates (YYYY-MM-DD, comma separated)"><input aria-label="Non-operating dates" className={inputClass} value={c.excluded_dates.join(',')} onChange={e=>set('excluded_dates',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></Field>
  <div className="grid gap-4 md:grid-cols-2">{!maintenance&&choice('Staffing mode','mode',[['shift','Resolve pool against published shifts'],['fixed','Assign fixed pool regardless of shift (coverage warnings apply)']])}{!maintenance&&choice('Execution','execution',[['shared','Shared checklist with one responsible owner'],['individual','Separate execution per employee']])}
   <Field label="Department"><select aria-label="Department" className={inputClass} value={c.department_id} onChange={e=>set('department_id',e.target.value)}><option value="">All authorized departments</option>{workspace.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field>
   <Field label="Position"><select aria-label="Position" className={inputClass} value={c.position} onChange={e=>set('position',e.target.value)}><option value="">All positions</option>{[...new Set(workspace.people.map(p=>p.position).filter(Boolean))].map(p=><option key={p}>{p}</option>)}</select></Field>
   <Field label="Role"><select aria-label="Role" className={inputClass} value={c.role} onChange={e=>set('role',e.target.value)}><option value="">All authorized roles</option>{[...new Set(workspace.people.flatMap(p=>p.roles))].map(p=><option key={p}>{p}</option>)}</select></Field>
  </div>
  <fieldset><legend className="font-medium">Eligible employee pool · empty selection uses authorized department / position / role</legend><div className="mt-3 grid max-h-56 gap-2 overflow-auto sm:grid-cols-2">{people.map(p=><label key={p.id} className="flex gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" checked={c.employee_ids.includes(p.id)} onChange={e=>set('employee_ids',e.target.checked?[...c.employee_ids,p.id]:c.employee_ids.filter(x=>x!==p.id))}/>{p.name} · {p.position}</label>)}</div></fieldset>
  <div className="grid gap-4 md:grid-cols-2">
   <Field label="Preferred owner"><select aria-label="Preferred owner" className={inputClass} value={c.preferred_owner} onChange={e=>set('preferred_owner',e.target.value)}><option value="">Manager selection / employee claim</option>{people.filter(p=>!c.employee_ids.length||c.employee_ids.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
   <Field label="Ordered backup employees"><select aria-label="Add backup employee" className={inputClass} value="" onChange={e=>{if(e.target.value&&!c.backup_ids.includes(e.target.value))set('backup_ids',[...c.backup_ids,e.target.value]);}}><option value="">Add in priority order</option>{people.filter(p=>!c.employee_ids.length||c.employee_ids.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><ol className="space-y-2">{c.backup_ids.map((id,i)=><li key={id} className="flex justify-between gap-3 text-sm"><span>{i+1}. {workspace.people.find(p=>p.id===id)?.name}</span><button type="button" className="underline" onClick={()=>set('backup_ids',c.backup_ids.filter(x=>x!==id))}>Remove backup</button></li>)}</ol></Field>
  </div>
  <label className="flex gap-3 text-sm"><input type="checkbox" checked={c.auto_backup} onChange={e=>set('auto_backup',e.target.checked)}/>Automatically use ordered eligible backups before work starts</label><label className="flex gap-3 text-sm"><input type="checkbox" checked={c.allow_claim} onChange={e=>set('allow_claim',e.target.checked)}/>Allow assigned employees to claim unowned shared work</label>
  <div className="grid gap-4 md:grid-cols-3">{!maintenance&&choice('Timing anchor','anchor',[['fixed','Fixed Manila times'],['shift_start','Relative to published shift start'],['shift_end','Relative to published shift end']])}{input('Window start / fallback','start_time','time')}{input('Window end / fallback','end_time','time')}{choice('Window end day','end_day_offset',[['0','Operating date'],['1','Next day']])}{input('Due time / fallback','due_time','time')}{choice('Deadline day','due_day_offset',[['0','Operating date'],['1','Next day']])}</div>
  {c.anchor!=='fixed'&&<div className="grid gap-4 md:grid-cols-2"><Field label="Published shift reference employee"><select aria-label="Published shift reference employee" className={inputClass} value={c.reference_employee} onChange={e=>set('reference_employee',e.target.value)}><option value="">Choose reference</option>{people.filter(p=>!c.employee_ids.length||c.employee_ids.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>{input('Start offset minutes','start_offset','number',-1440,1440)}{input('Execution window minutes','duration_minutes','number',1,1440)}{input('Deadline minutes after window starts','due_offset','number',0,1440)}</div>}
  <div className="grid gap-4 md:grid-cols-3">{choice('Priority','priority',[['Low','Low'],['Normal','Normal'],['High','High'],['Urgent','Urgent']])}{input('Generate ahead days','horizon_days','number',0,31)}{input('Attendance grace minutes','grace_minutes','number',0,240)}{input('Due reminder minutes (0 = off)','remind_before','number',0,1440)}{input('Overdue reminder interval (0 = off, minimum 60)','overdue_every','number',0,1440)}<Field label="Rule status"><select aria-label="Rule status" className={inputClass} value={status} onChange={e=>setStatus(e.target.value)}>{(maintenance?['Draft','Paused','Active','Archived']:['Paused','Active','Archived']).map(s=><option key={s}>{s}</option>)}</select></Field></div>
  <Field label="Additional instructions"><textarea aria-label="Additional instructions" className={inputClass} value={c.instructions} onChange={e=>set('instructions',e.target.value)}/></Field><label className="flex gap-3 text-sm"><input type="checkbox" checked={c.requires_verification} onChange={e=>set('requires_verification',e.target.checked)}/>Future supervisor verification required (Phase 4; completion is not approval)</label>
  {rule?.id&&<Field label="Reason for rule change"><textarea aria-label="Reason for rule change" className={inputClass} value={reason} onChange={e=>setReason(e.target.value)}/></Field>}
  {version&&<details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Preview published instructions & requirements</summary>{workspace.templates.flatMap(t=>t.versions).filter(v=>v.id===version).map(v=><div key={v.id} className="mt-3 space-y-2 text-sm"><strong>{v.content.title} · v{v.version}</strong><p className="whitespace-pre-wrap">{v.content.instructions||v.content.description}</p>{v.items.map(i=><div key={i.id} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><strong>{i.snapshot.title}</strong><p>{i.snapshot.instructions||i.snapshot.description}</p><p>{i.required?'Required':'Optional'} · {i.response_type}{i.snapshot.photo_required?' · photo required':''}</p></div>)}</div>)}</details>}
  <p className="text-xs text-slate-500">Existing started work requires a manager handover. Pausing stops new generation; existing work remains. Resuming starts from today. Published versions remain frozen. All times use Manila time.</p>
  <div className="flex flex-wrap gap-3"><button className={buttonClass} disabled={busy||!version} onClick={()=>void run(false)}>{maintenance?'Preview next 12 occurrences':'Preview next 14 days'}</button><button className={primaryClass} disabled={busy||!version||title.trim().length<3||(!!rule?.id&&reason.trim().length<3)||(!preview&&status==='Active')} onClick={()=>void run(true)}>{maintenance?'Save maintenance plan':'Save recurring rule'}</button></div>
  {preview&&<section className="space-y-3"><h3 className="font-semibold">Generation preview</h3>{!preview.length&&<p>No matching operating dates in this preview.</p>}{preview.map(p=><article key={p.date} className="rounded-xl border p-3 text-sm"><strong>{p.date} · {formatDue(p.window.start)} – {formatDue(p.window.end)}</strong>{p.window.warning&&<p className="text-amber-700">{p.window.warning}</p>}<ul className="mt-2 space-y-1">{p.people.map(e=><li key={e.employee_id}>{e.name}: {e.label}{e.warning?` · ${e.warning}`:''}</li>)}</ul></article>)}</section>}
 </div></Modal>;
}
