import React, {useState} from 'react';
import Modal from '../../components/ui/Modal';
import type { OpsContent } from './types';
import { readChecklistFile, exportChecklistSample } from './checklistImport';
import { operationsRpc } from './service';
import { buttonClass, primaryClass, inputClass } from './ui';
export default function ChecklistImport({unit,unitName,onClose,onSaved}:{unit:string;unitName:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [checklists,setChecklists]=useState<OpsContent[]>([]),[fileName,setFileName]=useState(''),[publish,setPublish]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function read(file?:File){setChecklists([]);setFileName('');setError('');if(!file)return;setBusy(true);try{const c=await readChecklistFile(file);setChecklists(c);setFileName(file.name);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');try{await operationsRpc('ops_import_checklists',{p_unit:unit||null,p_checklists:checklists,p_publish:publish,p_source:fileName});await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal isOpen title="Import checklists" onClose={()=>{if(!busy)onClose();}} size="3xl" viewportFit><div className="space-y-4"><p>Import into <strong>{unitName}</strong>. Creates new templates. Existing versions and assignments are preserved.</p><button className={buttonClass} onClick={exportChecklistSample}>Export sample to fill up</button><p className="text-sm text-slate-500">Open the CSV sample in Excel or Google Sheets. Use one row per task and repeat the checklist title to group tasks. Set response types (none, yes_no, text, photo or numeric), photo requirements, allowed NA and numeric ranges. Save as CSV or XLSX. The Fun Roof YES / NO form is also supported. Files up to 5 MB.</p><input aria-label="Checklist import file" type="file" accept=".csv,.xlsx" className={inputClass} disabled={busy} onChange={e=>void read(e.target.files?.[0])}/>{!!checklists.length&&<><p className="font-semibold">Preview: {checklists.length} checklists · {checklists.reduce((n,c)=>n+(c.items?.length||0),0)} tasks</p><div className="max-h-80 space-y-2 overflow-auto">{checklists.map((c,i)=><details key={i} className="rounded-xl border p-3"><summary>{c.title} · {c.items?.length} tasks</summary><ol className="mt-2 list-inside list-decimal text-sm">{c.items?.map((x,j)=><li key={j}>{x.snapshot?.title}{x.required?'':' (optional)'}</li>)}</ol></details>)}</div><label className="flex gap-3"><input type="checkbox" checked={publish} disabled={busy} onChange={e=>setPublish(e.target.checked)}/>Publish after import (ready for assignment)</label><p className="text-sm text-slate-500">Preview carefully. Every import creates new templates, including when the same file is imported again.</p></>}{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex justify-end gap-3"><button className={buttonClass} disabled={busy} onClick={onClose}>Cancel</button><button className={primaryClass} disabled={busy||!checklists.length} onClick={()=>void save()}>{busy?'Processing…':publish?'Import and publish':'Import as drafts'}</button></div></div></Modal>;
}
