import React,{useState,useEffect,useCallback} from 'react';
import type {OpsAssignment,OpsRunItem,OpsEvidence} from './types';
import {Field,inputClass,primaryClass,buttonClass} from './ui';
import {operationsRpc} from './service';
import {compressEvidencePhoto,uploadEvidence,downloadEvidence} from './evidence';
import {formatDue,safeUrl} from './presentation';
export function Photo({e,editable,onRemove}:{key?:string;e:OpsEvidence;editable:boolean;onRemove:()=>void}){
 const [url,setUrl]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url);},[url]);
 async function view(){setBusy(true);setError('');try{setUrl(await downloadEvidence(e.path));}catch(x){setError((x as Error).message);}finally{setBusy(false);}}
 return <div className="rounded-xl border p-3 dark:border-slate-700"><p className="text-xs text-slate-500">{e.uploader_name} · {Math.ceil(e.bytes/1024)} KB · {formatDue(e.uploaded_at||e.created_at)}</p>{e.accessible?<><p className="mt-1 text-xs text-slate-500">Expires {formatDue(e.expires_at)}</p>{url?<img src={url} alt="Checklist photo evidence" className="mt-2 max-h-72 w-full rounded-lg object-contain"/>:<button className={`${buttonClass} mt-2`} disabled={busy} onClick={()=>void view()}>{busy?'Loading photo…':'View photo'}</button>}{editable&&<button className={`${buttonClass} ml-2 mt-2`} onClick={onRemove}>Remove photo</button>}</>:<p className="mt-2 text-sm text-slate-500">{e.state==='Removed'?'Photo removed':e.state==='Pending'&&!e.deleted_at?'Upload not completed':'Evidence expired (60-day maximum)'}</p>}{error&&<p role="alert" className="mt-2 text-sm text-red-700">{error}</p>}</div>;
}
function ResponseItem({item:i,editable,submitted,onSaved,onDirty}:{key?:string;item:OpsRunItem;editable:boolean;submitted:boolean;onSaved:()=>Promise<void>;onDirty:(id:string,dirty:boolean)=>void}){
 const [value,setValue]=useState(i.response.value),[remarks,setRemarks]=useState(i.response.remarks),[issue,setIssue]=useState(i.response.issue),[revision,setRevision]=useState(i.response.revision),[reason,setReason]=useState('');
 const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[photo,setPhoto]=useState<File|null>(null),[preview,setPreview]=useState('');
 useEffect(()=>{if(!dirty){setValue(i.response.value);setRemarks(i.response.remarks);setIssue(i.response.issue);setRevision(i.response.revision);}},[i.response.revision,dirty]);
 useEffect(()=>{onDirty(i.id,dirty||!!photo);return()=>onDirty(i.id,false);},[i.id,dirty,photo,onDirty]);
 useEffect(()=>{if(!photo){setPreview('');return;}const url=URL.createObjectURL(photo);setPreview(url);return()=>URL.revokeObjectURL(url);},[photo]);
 const change=(v:typeof value)=>{setValue(v);setDirty(true);setError('');};
 async function save(){setBusy(true);setError('');try{await operationsRpc('ops_save_response',{p_item:i.id,p_revision:revision,p_value:value,p_remarks:remarks,p_issue:issue,p_note:reason});await onSaved();setDirty(false);setReason('');}catch(e){setError((e as Error).message);await onSaved();}finally{setBusy(false);}}
 async function pick(file?:File){if(!file)return;setBusy(true);setError('');try{setPhoto(await compressEvidencePhoto(file));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(){if(!photo)return;setBusy(true);setError('');try{await uploadEvidence(i.id,photo);setPhoto(null);await onSaved();}catch(e){setError((e as Error).message);await onSaved();}finally{setBusy(false);}}
 async function remove(e:OpsEvidence){setBusy(true);setError('');try{await operationsRpc('ops_remove_evidence',{p_id:e.id,p_note:reason});await onSaved();setReason('');}catch(x){setError((x as Error).message);}finally{setBusy(false);}}
 const na=value==='na';const type=i.response_type;const label=type==='none'?'Checkbox':type==='yes_no'?'Yes / No':type==='numeric'?'Numeric reading':type==='text'?'Text response':'Photo confirmation';
 return <section className="space-y-3 rounded-2xl border bg-white p-4 sm:p-5 dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap justify-between gap-2"><h4 className="font-semibold">{i.ordinal+1}. {i.snapshot.title}</h4><span className="text-xs text-slate-500">{i.required?'Required':'Optional'} · {label}</span></div>{i.snapshot.safety_critical&&<p className="text-sm font-semibold text-amber-700">Safety-critical</p>}<p className="whitespace-pre-wrap text-sm text-slate-600 dark:text-slate-300">{i.snapshot.instructions||i.snapshot.description}</p>{safeUrl(i.snapshot.sop_url)&&<a href={safeUrl(i.snapshot.sop_url)} className="text-sm text-violet-700 underline" target="_blank" rel="noopener noreferrer">Open SOP / manual</a>}
  {editable?<fieldset disabled={busy} className="space-y-3"><legend className="sr-only">Response for {i.snapshot.title}</legend>{i.snapshot.allow_na&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={na} onChange={e=>change(e.target.checked?'na':null)}/>Not Applicable</label>}{!na&&<>{(type==='none'||type==='photo')&&<label className="flex min-h-11 items-center gap-3"><input aria-label={`Confirm ${i.snapshot.title}`} type="checkbox" className="h-5 w-5 accent-violet-600" checked={value===true} onChange={e=>change(e.target.checked)}/>{type==='photo'?'Photo documents the completed work':'I completed this item'}</label>}{type==='yes_no'&&<Field label={`Answer: ${i.snapshot.title}`}><select aria-label={`Answer: ${i.snapshot.title}`} className={inputClass} value={typeof value==='string'?value:''} onChange={e=>change(e.target.value||null)}><option value="">Choose answer</option><option value="yes">Yes — passed</option><option value="no">No — issue found</option></select></Field>}{type==='numeric'&&<><Field label={`Reading: ${i.snapshot.title}${i.snapshot.unit?' ('+i.snapshot.unit+')':''}`}><input type="number" step="any" className={inputClass} value={typeof value==='number'?value:''} onChange={e=>change(e.target.value===''?null:Number(e.target.value))}/></Field>{(i.snapshot.min!=null||i.snapshot.max!=null)&&<p className="text-xs text-slate-500">Expected range: {i.snapshot.min??'No minimum'} to {i.snapshot.max??'No maximum'} {i.snapshot.unit}</p>}</>}{type==='text'&&<Field label={`Response: ${i.snapshot.title}`}><textarea className={inputClass} maxLength={4000} value={typeof value==='string'?value:''} onChange={e=>change(e.target.value.trim()?e.target.value:null)}/></Field>}</>}
   <Field label={`Remarks: ${i.snapshot.title}`}><textarea className={inputClass} maxLength={2000} value={remarks} onChange={e=>{setRemarks(e.target.value);setDirty(true);}} placeholder={na?'Explain why this item does not apply':value==='no'?'Describe the issue':'Optional notes'}/></Field><label className="flex gap-2 text-sm"><input type="checkbox" checked={issue} onChange={e=>{setIssue(e.target.checked);setDirty(true);}}/>Flag an issue</label>{(i.response.actor_name||i.evidence.some(e=>e.accessible))&&<Field label={`Change reason: ${i.snapshot.title}`}><input className={inputClass} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required when changing a saved response or removing a photo"/></Field>}
   {dirty&&revision!==i.response.revision&&<div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Another team member changed this response. Your edits have been kept. <button className="underline" onClick={()=>{setDirty(false);setReason('');setError('');}}>Load latest answer</button></div>}<button className={primaryClass} disabled={!dirty} onClick={()=>void save()}>{busy?'Saving…':'Save response'}</button>{dirty&&<p className="text-xs text-amber-700">Unsaved response — save before leaving.</p>}
  </fieldset>:<div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p className="font-semibold">{value==='na'?'Not Applicable':value===null?'No answer saved':typeof value==='boolean'?(value?'Confirmed':'Not confirmed'):String(value)} {type==='numeric'?i.snapshot.unit:''}</p>{remarks&&<p className="mt-1 whitespace-pre-wrap text-sm">{remarks}</p>}</div>}
  {i.response.issue&&<p className="rounded-xl bg-amber-50 p-3 text-sm font-semibold text-amber-800">Issue flagged — completion does not mean this inspection passed.</p>}{i.response.actor_name&&<p className="text-xs text-slate-500">Saved by {i.response.actor_name} · {i.response.updated_at&&formatDue(i.response.updated_at)}</p>}{!submitted&&i.error&&<p className="text-xs text-amber-700">Before submission: {i.error}</p>}
  <div className="space-y-2"><p className="text-sm font-semibold">Photos{(type==='photo'||i.snapshot.photo_required)&&!na?' · required':''}</p>{i.evidence.map(e=><Photo key={e.id} e={e} editable={editable&&!busy} onRemove={()=>void remove(e)}/>)}{editable&&<><p className="text-xs text-slate-500">Up to 3 photos per item. Compressed to 1,280 pixels and 500 KB maximum. Stored for up to 60 days.</p><input aria-label={`Add photo: ${i.snapshot.title}`} type="file" accept="image/*" disabled={busy} className={inputClass} onChange={e=>{void pick(e.target.files?.[0]);e.target.value='';}}/>{preview&&photo&&<div className="space-y-3 rounded-xl bg-violet-50 p-3 dark:bg-violet-950"><img src={preview} alt="Compressed photo preview" className="max-h-72 w-full rounded-lg object-contain"/><p className="text-sm">{Math.ceil(photo.size/1024)} KB — confirm the label, reading or defect is clear before uploading.</p><button className={primaryClass} disabled={busy} onClick={()=>void upload()}>Upload clear photo</button><button className={`${buttonClass} ml-2`} disabled={busy} onClick={()=>setPhoto(null)}>Discard preview</button></div>}</>}</div>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
 </section>;
}
export default function ExecutionPanel({assignment:a,onSaved,onDirtyChange}:{assignment:OpsAssignment;onSaved:()=>Promise<void>;onDirtyChange?:(dirty:boolean)=>void}){
 const run=a.execution!;const [dirty,setDirty]=useState<Set<string>>(new Set()),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const markDirty=useCallback((id:string,value:boolean)=>setDirty(previous=>{const next=new Set(previous);value?next.add(id):next.delete(id);return next;}),[]);
 useEffect(()=>{onDirtyChange?.(!!dirty.size);},[dirty.size,onDirtyChange]);
 useEffect(()=>{if(!dirty.size)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty.size]);
 async function action(name:string){setBusy(true);setError('');try{await operationsRpc(name,{p_run:run.id,p_revision:run.revision,...(name==='ops_reopen_run'?{p_note:reason}:{})});await onSaved();setReason('');}catch(e){setError((e as Error).message);await onSaved();}finally{setBusy(false);}}
 const missing=run.items.filter(i=>i.error);const saved=run.items.filter(i=>i.response.value!==null).length;
 return <div className="space-y-4"><section className="space-y-2 rounded-2xl bg-violet-50 p-4 dark:bg-violet-950/30"><h3 className="font-semibold">{run.shared?'Shared team':'Individual'} execution · {saved} / {run.items.length} answered</h3><p className="text-sm">{run.submitted_at?'Submitted — not independently verified.':'Save each response to resume later. Submit after required responses and photos are complete.'}</p>{run.outcome==='Issues'&&<p className="font-semibold text-amber-800">Submitted with issues — manager attention needed.</p>}{run.submitted_at&&<p className="text-xs text-slate-500">Submitted {formatDue(run.submitted_at)}</p>}{a.status==='Cancelled'&&<p className="font-semibold">This assignment is cancelled. Responses are read-only.</p>}</section>
  {run.items.map(i=><ResponseItem key={i.id} item={i} editable={run.can_write&&!busy} submitted={!!run.submitted_at} onSaved={onSaved} onDirty={markDirty}/>)}
  {run.can_write&&<section className="space-y-3 rounded-xl border p-4 dark:border-slate-700"><p className="text-sm">{dirty.size?`${dirty.size} item(s) have unsaved edits or a photo preview.`:missing.length?`${missing.length} item(s) need attention before submission.`:'All required items are ready.'}</p><button className={primaryClass} disabled={busy||!!dirty.size||!!missing.length} onClick={()=>void action('ops_submit_run')}>{busy?'Submitting…':'Submit work'}</button></section>}
  {run.can_reopen&&<section className="space-y-3 rounded-xl border p-4 dark:border-slate-700"><Field label="Reason for reopening"><input className={inputClass} value={reason} onChange={e=>setReason(e.target.value)}/></Field><button className={buttonClass} disabled={busy||reason.trim().length<3} onClick={()=>void action('ops_reopen_run')}>Reopen for corrections</button></section>}{error&&<p role="alert" className="text-red-700">{error}</p>}
 </div>;
}
