import React,{useEffect,useRef,useState} from 'react';
import {confirmOtBaseline,decideOtWeek,getOtWeeks,minutesLabel,workDateLabel,OtWeek,verifyLegacyOtHours} from '../../services/manualOtService';
import {supabase} from '../../services/supabaseClient';

type Props={key?:string;requestIds:string[];onChanged?:()=>void;initialRequestId?:string};
const panel='rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-600 dark:bg-slate-800';
function offlineOt(r:OtWeek['requests'][number]){
 const record=(r.history_log as Array<{action?:string;details?:{offlineManagerOtHours?:number;offlineOtReference?:string}}>||[]).find(item=>item.action==='Imported for manager approval');
 return record?.details?.offlineManagerOtHours==null?null:{minutes:Math.round(Number(record.details.offlineManagerOtHours)*60),reference:record.details.offlineOtReference||''};
}
export default function OvertimeWeekReview({requestIds,onChanged,initialRequestId}:Props){
 const [weeks,setWeeks]=useState<OtWeek[]>([]),[active,setActive]=useState(''),[selected,setSelected]=useState<string[]>([]),[amounts,setAmounts]=useState<Record<string,number>>({}),[nightAmounts,setNightAmounts]=useState<Record<string,number>>({}),[notesOpen,setNotesOpen]=useState(false),[note,setNote]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[baseline,setBaseline]=useState(''),[evidence,setEvidence]=useState(''),[search,setSearch]=useState('');
 const [legacyAmounts,setLegacyAmounts]=useState<Record<string,string>>({});
 const inFlight=useRef(false),operation=useRef<{key:string;id:string}|null>(null);
 const idsKey=[...requestIds].sort().join(',');
 useEffect(()=>{let live=true;setLoading(true);getOtWeeks(idsKey?idsKey.split(','):[]).then(data=>{if(!live)return;setWeeks(data);setError('');setActive(prev=>data.some(w=>`${w.employeeId}:${w.summary.weekStart}`===prev)?prev:(data.find(w=>w.requests.some(r=>r.id===initialRequestId))||data[0])?`${(data.find(w=>w.requests.some(r=>r.id===initialRequestId))||data[0]).employeeId}:${(data.find(w=>w.requests.some(r=>r.id===initialRequestId))||data[0]).summary.weekStart}`:'');setSelected([]);setNightAmounts(Object.fromEntries(data.flatMap(w=>w.requests.map(r=>[r.id,r.manager_night_minutes??NaN]))));setAmounts(Object.fromEntries(data.flatMap(w=>w.requests.map(r=>[r.id,r.reviewedMinutes??offlineOt(r)?.minutes??r.requestedMinutes??0]))));}).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false};},[idsKey,refresh,initialRequestId]);
 const week=weeks.find(w=>`${w.employeeId}:${w.summary.weekStart}`===active);
 const scope=new Set(requestIds);
 const selectable=week?.requests.filter(r=>r.canDecide&&scope.has(r.id)&&!r.blocked?.startsWith('Payroll locked'))||[];
 const eligible=selectable.filter(r=>!r.blocked);
 const selectedRows=selectable.filter(r=>selected.includes(r.id));
 const selectedMinutes=selectedRows.reduce((sum,r)=>sum+(Number.isFinite(amounts[r.id])?amounts[r.id]:0),0);
 const invalidRow=(r:OtWeek['requests'][number])=>!Number.isInteger(amounts[r.id])||amounts[r.id]<0||amounts[r.id]>(r.status==='PendingBOD'?(r.reviewedMinutes??-1):(r.requestedMinutes??-1))||!r.start_time&&r.status!=='PendingBOD'&&(!Number.isInteger(nightAmounts[r.id])||nightAmounts[r.id]<0||nightAmounts[r.id]>amounts[r.id]);
 const invalid=selectedRows.find(r=>r.blocked||invalidRow(r));
 const changeWeek=(key:string)=>{setActive(key);setSelected([]);setNote('');setBaseline('');setEvidence('');setMessage('');};
 const decide=async(decision:string,chosen=selectedRows)=>{if(!week||inFlight.current)return;if(decision!=='approve'&&!note.trim()){setNotesOpen(true);setError('Enter a specific reason to return or reject.');return;}
 const quantities=Object.fromEntries(chosen.map(r=>[r.id,!r.start_time&&r.status!=='PendingBOD'?{minutes:amounts[r.id],nightMinutes:nightAmounts[r.id]}:amounts[r.id]]));const key=JSON.stringify([chosen.map(r=>r.id),quantities,week.version,decision,note]);if(operation.current?.key!==key)operation.current={key,id:crypto.randomUUID()};
 inFlight.current=true;setBusy(true);setError('');try{const result=await decideOtWeek(chosen.map(r=>r.id),quantities,week.version,operation.current!.id,decision,note);setMessage(result?.quantityReviewNeeded?'Manager review saved. HR must reconcile older approved requests with missing hours before final routing.':result?.baselineNeeded?'Manager review saved. Confirm the regular-hour baseline below, then complete approval.':'Decision saved. Requests still waiting for another required reviewer remain pending.');operation.current=null;setRefresh(n=>n+1);onChanged?.();}catch(e){setError((e as Error).message);}finally{inFlight.current=false;setBusy(false);}};
 const saveBaseline=async()=>{if(!week||busy)return;setBusy(true);try{await confirmOtBaseline(week.employeeId,week.summary.weekStart,Number(baseline),evidence);setRefresh(n=>n+1);setMessage('Weekly baseline saved with its evidence.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const verifyLegacy=async()=>{if(!week||busy)return;const rows=week.requests.filter(r=>scope.has(r.id)&&r.status==='Approved'&&r.finalMinutes==null&&legacyAmounts[r.id]!==undefined&&legacyAmounts[r.id]!=='' );if(!rows.length)return;setBusy(true);setError('');try{await verifyLegacyOtHours(Object.fromEntries(rows.map(r=>[r.id,Number(legacyAmounts[r.id])])),note);setMessage(`${rows.length} older approved OT amount${rows.length===1?'':'s'} verified by the business unit manager.`);setLegacyAmounts({});setRefresh(n=>n+1);onChanged?.();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const openEvidence=async(path:string)=>{try{const {data,error}=await supabase.storage.from('overtime_request_attachments').createSignedUrl(path,300);if(error)throw error;if(data?.signedUrl)window.open(data.signedUrl,'_blank','noopener,noreferrer');}catch(e){setError((e as Error).message);}};
 return <section className="space-y-4 text-slate-900 dark:text-white" aria-label="Weekly overtime review">
 <div className="rounded-xl border border-violet-200 bg-violet-50 p-4 text-violet-950"><b>Temporary manual OT mode</b><p>Managers verify extra work beyond normal hours. HRIS clock-in/out matching is not required for OT approval.</p></div>
 {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error} <button className="underline" onClick={()=>setRefresh(n=>n+1)} disabled={busy}>Refresh review</button></div>}
 {message&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-900">{message}</p>}
 {loading?<p role="status">Loading current weekly totals…</p>:!weeks.length?<p>No overtime requests in this view.</p>:<div className="grid items-start gap-5 xl:grid-cols-[280px_1fr]">
 <aside className="max-h-60 space-y-3 overflow-y-auto xl:max-h-[70vh]"><h2 className="text-xl font-bold">Employee weeks</h2><label className="block text-sm">Find employee or business unit<input className="mt-1 w-full rounded-lg border bg-transparent p-3" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 {weeks.filter(w=>`${w.employee.name} ${w.employee.businessUnit}`.toLowerCase().includes(search.toLowerCase())).map(w=><button key={`${w.employeeId}:${w.summary.weekStart}`} disabled={busy} onClick={()=>changeWeek(`${w.employeeId}:${w.summary.weekStart}`)} className={`w-full rounded-xl border p-4 text-left ${w===week?'border-violet-500 bg-violet-50 text-violet-950':'border-slate-200 bg-white dark:bg-slate-800'}`}><b className="block">{w.employee.name}</b><span className="mt-1 block text-sm">{workDateLabel(w.summary.weekStart)} – {workDateLabel(w.summary.weekEnd)}</span><span className="mt-2 block text-sm">{w.requests.filter(r=>['Submitted','PendingGM','PendingBOD'].includes(r.status)).length} pending · {minutesLabel(w.summary.reviewedMinutes)} reviewed</span></button>)}</aside>
 {week&&<div className="min-w-0 space-y-4">
 {week.requests.some(r=>scope.has(r.id)&&r.status==='Approved'&&r.finalMinutes==null)&&<section className="rounded-xl border border-amber-300 bg-amber-50 p-5 text-amber-950"><h3 className="text-lg font-bold">Older approved OT · hours need verification</h3><p className="mt-1 text-sm">These requests were already approved, but the approved duration was not saved. The business unit manager must enter the amount actually approved for each date. The original approval stays in the audit history.</p><div className="mt-3 space-y-2">{week.requests.filter(r=>scope.has(r.id)&&r.status==='Approved'&&r.finalMinutes==null).map(r=><label key={r.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-white p-3"><span>{workDateLabel(r.date)} · requested interval {r.start_time?.slice(0,5)||'—'}–{r.end_time?.slice(0,5)||'—'} · {r.reason}{week.requests.some(other=>other.id!==r.id&&other.date===r.date&&other.start_time===r.start_time)&&<strong className="block text-rose-700">Overlapping requests: verify payable hours on only one; enter 0 for a duplicate.</strong>}</span><span className="flex items-center gap-2">Approved minutes <input className="w-24 rounded border p-2" type="number" min="0" max={r.requestedMinutes??1440} step="1" value={legacyAmounts[r.id]??''} onChange={e=>setLegacyAmounts(old=>({...old,[r.id]:e.target.value}))} placeholder="Enter" disabled={!week.canConfirmBaseline}/></span></label>)}</div>{week.canConfirmBaseline?<button className="mt-3 rounded-lg bg-violet-700 px-4 py-3 font-semibold text-white disabled:opacity-40" onClick={verifyLegacy} disabled={busy||!week.requests.some(r=>scope.has(r.id)&&r.status==='Approved'&&r.finalMinutes==null&&legacyAmounts[r.id]!==undefined&&legacyAmounts[r.id]!==''&&Number.isInteger(Number(legacyAmounts[r.id]))&&Number(legacyAmounts[r.id])>=0&&Number(legacyAmounts[r.id])<=(r.requestedMinutes??-1))}>Verify entered hours</button>:<p className="mt-2 text-sm">Awaiting this employee’s business unit manager.</p>}</section>}
 <div className={panel}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl font-bold">{week.employee.name}</h2><p>{week.employee.position||'Position not recorded'}</p><p className="text-sm text-slate-500">{week.employee.businessUnit}</p></div><div><p className="text-sm font-semibold">Week · Philippine time</p><b>{workDateLabel(week.summary.weekStart)} – {workDateLabel(week.summary.weekEnd)}</b></div></div></div>
 <div className={`rounded-xl border p-5 ${week.summary.requiresBod||week.summary.baselineMissing||week.summary.quantitiesMissing?'border-amber-300 bg-amber-50 text-amber-950':'border-indigo-200 bg-indigo-50 text-indigo-950'}`}>
 <h3 className="text-lg font-bold">{week.summary.quantitiesMissing?'Approved hours need review':week.summary.baselineMissing?'Regular-hour baseline needs confirmation':week.summary.requiresBod?'Why BOD review?':'Projected weekly hours for approval routing'}</h3>
 {week.summary.quantitiesMissing&&<p className="mt-2 font-semibold">{week.summary.quantityIssueIds?.length} older approved or escalated requests have no recorded approved hours. HR must reconcile those records. Their hours have not been treated as zero, and their decisions are retained.</p>}
 <p className="mt-2 text-xl font-bold">{minutesLabel(week.summary.regularMinutes)} regular + {minutesLabel(week.summary.approvedMinutes)} approved OT + {minutesLabel(week.summary.reviewedMinutes)} manager-reviewed OT = {minutesLabel(week.summary.projectedMinutes)}</p>
 <p className="mt-2 text-sm">{week.summary.baselineSource} · {minutesLabel(week.summary.thresholdMinutes)} escalation threshold. This is a projection, not actual attendance.</p>
 <p className="mt-2 text-sm">Unreviewed requests: <b>{minutesLabel(week.summary.unreviewedMinutes)}</b> — excluded until a manager verifies them. An absence on another day does not cancel daily overtime.</p>
 {week.summary.baselineMissing&&week.canConfirmBaseline&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><label>Regular minutes for this week<input type="number" min="0" max="10080" step="1" value={baseline} onChange={e=>setBaseline(e.target.value)} className="block w-full rounded border p-2"/></label><label>Schedule / evidence used<input value={evidence} onChange={e=>setEvidence(e.target.value)} className="block w-full rounded border p-2"/></label><button disabled={busy||baseline===''||!evidence.trim()} onClick={saveBaseline} className="rounded-lg bg-indigo-600 p-3 font-bold text-white disabled:opacity-40">Save verified baseline</button></div>}
 </div>
 <div className={panel}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-xl font-bold">Requests this week</h3><a className="text-sm font-semibold text-violet-600 underline" href={`/payroll/timekeeping?week=${week.summary.weekStart}`}>View published schedule</a></div>
 <label className="my-3 flex min-h-11 items-center gap-2"><input type="checkbox" disabled={busy||!eligible.length} checked={eligible.length>0&&selectedRows.length===eligible.length} onChange={e=>setSelected(e.target.checked?eligible.map(r=>r.id):[])}/>Select all eligible requests in this view ({eligible.length})</label>
 <div className="space-y-3">{week.requests.map(r=><article key={r.id} className={`rounded-xl border p-4 ${selected.includes(r.id)?'border-violet-400 bg-violet-50 text-slate-900':'border-slate-200'}`}><div className="flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-3 font-bold"><input type="checkbox" aria-label={`Select ${workDateLabel(r.date)} ${r.start_time||'duration request'}`} disabled={busy||!selectable.some(x=>x.id===r.id)} checked={selected.includes(r.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,r.id]:old.filter(id=>id!==r.id))}/>{workDateLabel(r.date)} · {r.start_time?`${r.start_time.slice(0,5)}–${r.end_time?.slice(0,5)}${r.end_date&&r.end_date!==r.date?' (+1 day)':''}`:'Duration-only request'}</label><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700">{r.status==='PendingBOD'?'Pending BOD':r.status==='Submitted'?'Manager review':r.status}</span></div>
 <div className="my-3 rounded-lg border border-violet-200 bg-violet-50 p-3 text-violet-950"><b>Reason for overtime</b><p className="mt-1 whitespace-pre-wrap">{r.reason||'Reason not recorded'}</p></div>
 <div className="flex flex-wrap items-center gap-5 text-sm"><span>Requested <b>{minutesLabel(r.requestedMinutes)}</b></span><span>Manager-reviewed <b>{minutesLabel(r.reviewedMinutes)}</b></span><span>Finally approved <b>{minutesLabel(r.finalMinutes)}</b></span></div>
 {offlineOt(r)&&<p className="mt-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950"><b>Previous offline manager confirmation: {minutesLabel(offlineOt(r)!.minutes)}</b> · {offlineOt(r)!.reference}. This is a suggested quantity from the uploaded file, not HRIS approval. Verify it and click Approve to record your decision.</p>}
 {eligible.some(x=>x.id===r.id)&&r.status!=='PendingBOD'&&<label className="mt-3 flex flex-wrap items-center gap-3 text-sm font-semibold">{r.status==='PendingBOD'?'Minutes to approve':'Manager-verified minutes'}<input type="number" min="0" max={r.status==='PendingBOD'?r.reviewedMinutes??0:r.requestedMinutes??0} step="1" disabled={busy||r.status==='PendingBOD'} value={Number.isFinite(amounts[r.id])?amounts[r.id]:''} onChange={e=>setAmounts(old=>({...old,[r.id]:e.target.value===''?NaN:Number(e.target.value)}))} className="w-28 rounded-lg border bg-white p-2 text-slate-900"/> <span>{Number.isFinite(amounts[r.id])?minutesLabel(amounts[r.id]):'Enter whole minutes'}</span></label>}
 {!r.start_time&&eligible.some(x=>x.id===r.id)&&<label className="mt-3 block text-sm">Night-work minutes within this total, on {workDateLabel(r.date)} (enter 0 if none)<input type="number" min="0" max={amounts[r.id]} step="1" disabled={busy||r.status==='PendingBOD'} value={Number.isFinite(nightAmounts[r.id])?nightAmounts[r.id]:''} onChange={e=>setNightAmounts(old=>({...old,[r.id]:e.target.value===''?NaN:Number(e.target.value)}))} className="ml-2 w-24 rounded border p-2 text-slate-900"/></label>}
 {r.blocked&&<p className="mt-2 font-semibold text-red-700">{r.blocked}</p>}
 <div className="mt-3 flex flex-wrap gap-4 text-sm">{r.attachment_url&&<button className="font-semibold text-violet-600 underline" onClick={()=>openEvidence(r.attachment_url!)}>View supporting evidence</button>}<details><summary className="cursor-pointer font-semibold">Approval history</summary><ol className="mt-2 space-y-2">{(r.history_log as Array<Record<string,unknown>>).map((h,i)=><li key={i} className="rounded-lg bg-slate-50 p-2 text-slate-800"><b>{String(h.action||'Updated')}</b><span className="block text-xs">{String(h.userName||h.by||h.userId||'Recorded reviewer')} · {h.date||h.timestamp?new Date(String(h.date||h.timestamp)).toLocaleString('en-PH',{timeZone:'Asia/Manila'}):'Timestamp unavailable'}</span>{(h.note||h.details)&&<p>{typeof(h.note||h.details)==='string'?String(h.note||h.details):'Supporting record retained in audit history.'}</p>}</li>)}</ol></details></div></article>)}</div>
 </div>
 {!!selectable.length&&<div className={`${panel} xl:sticky bottom-0 z-10 shadow-lg`}><details open={notesOpen} onToggle={e=>setNotesOpen(e.currentTarget.open)}><summary className="cursor-pointer text-sm font-semibold">Add optional comment / return or rejection reason</summary><label className="mt-2 block text-sm font-semibold">Approval comment (optional); reason required for return or rejection<textarea className="mt-2 w-full rounded-lg border bg-transparent p-2" rows={2} value={note} disabled={busy} onChange={e=>setNote(e.target.value)}/></label></details>{invalid&&<p role="alert" className="text-red-700">{invalid.blocked||`Check minutes for ${workDateLabel(invalid.date)}. Use whole minutes within the reviewed/requested amount, and confirm any night-work minutes.`}</p>}<div className="mt-3 flex flex-wrap justify-end gap-3"><button disabled={busy||!selectedRows.length} onClick={()=>decide('return')} className="min-h-11 rounded-lg border px-4 disabled:opacity-40">Return for revision</button><button disabled={busy||!selectedRows.length} onClick={()=>decide('reject')} className="min-h-11 rounded-lg bg-red-600 px-4 text-white disabled:opacity-40">Reject selected</button><button disabled={busy||!eligible.length||eligible.length>100||eligible.some(invalidRow)||week.summary.baselineMissing||week.summary.quantitiesMissing} onClick={()=>decide('approve',eligible)} className="min-h-12 rounded-lg border border-violet-400 px-4 font-semibold disabled:opacity-40">Approve all {eligible.length} eligible · {minutesLabel(eligible.reduce((n,r)=>n+(Number.isFinite(amounts[r.id])?amounts[r.id]:0),0))}</button><button disabled={busy||!selectedRows.length||!!invalid||(week.summary.baselineMissing||week.summary.quantitiesMissing)&&selectedRows.some(r=>r.status==='PendingBOD')} onClick={()=>decide('approve')} className="min-h-12 rounded-lg bg-violet-600 px-5 py-3 font-bold text-white disabled:opacity-40">{busy?'Saving…':week.summary.baselineMissing||week.summary.quantitiesMissing?'Save manager review':`Approve selected · ${selectedRows.length} request${selectedRows.length===1?'':'s'} · ${minutesLabel(selectedMinutes)}`}</button></div><p className="mt-2 text-xs text-slate-500">One click records your decision. Other required approvers remain required. Blocked requests are never included.</p></div>}
 </div>}
 </div>}
 </section>;
}
